/* PIGMENT — artists 3/7 : Revolution to Impressionism */
window.ARTISTS.push(
{ id:"elisabeth-vigee-le-brun", name:"Élisabeth Vigée Le Brun", years:"1755–1842", born:1755, died:1842,
  nation:"france", eras:["18th-century","19th-century"], movements:["rococo","neoclassicism"],
  techniques:["oil-painting","pastel"], style:"rococo",
  palette:["#d9c4b0","#8a4a4e","#5e7a8e","#e9ddc4","#3a3430"],
  tagline:"Marie Antoinette's painter — and Europe's most resourceful exile",
  works:[{t:"Self-Portrait in a Straw Hat",y:"1782"},{t:"Marie Antoinette and Her Children",y:"1787"},{t:"Self-Portrait with Her Daughter Julie",y:"1786"}],
  life:"A pastellist's daughter who was painting professional portraits in her teens, Vigée Le Brun became Marie Antoinette's favourite painter and confidante. She fled Paris by stagecoach the night the royal family was seized in October 1789, and spent twelve years as a celebrity exile, painting the courts of Naples, Vienna and St Petersburg before returning under Napoleon.",
  career:"She produced over 600 portraits with a signature blend of Rococo warmth and Neoclassical clarity, famous for relaxed poses and open-mouthed smiles that scandalised the Salon — teeth were simply not shown. Her some thirty portraits of the queen were political image management of the highest stakes; her self-portraits, brush in hand, are manifestos of professional womanhood.",
  outside:"Her three-volume memoirs, Souvenirs, written in her eighties, remain a sparkling eyewitness tour of pre-revolutionary Europe. Her hard-won admission to the French Academy in 1783 — one of only four women — required royal intervention over academicians' objections.",
  facts:["Her smiling 1786 self-portrait broke a centuries-old taboo on visible teeth; a critic called it 'an affectation artists, connoisseurs and persons of taste unite in condemning.'",
    "Empress Catherine II initially balked at her fee; she charged it anyway, and stayed six years in Russia.",
    "She was admitted to academies in Rome, Parma, Bologna, St Petersburg and Berlin during exile — networking as survival."] },

{ id:"jacques-louis-david", name:"Jacques-Louis David", years:"1748–1825", born:1748, died:1825,
  nation:"france", eras:["18th-century","19th-century"], movements:["neoclassicism"],
  techniques:["oil-painting","glazing"], style:"neoclassical",
  palette:["#8a1f2b","#3b5a8a","#d9c49a","#2a2622","#e8e0cc"],
  tagline:"Painting as politics — Rome's virtues, the Revolution's martyrs, Napoleon's crown",
  works:[{t:"Oath of the Horatii",y:"1784"},{t:"The Death of Marat",y:"1793"},{t:"The Coronation of Napoleon",y:"1805–07"}],
  life:"A Paris silk merchant's son scarred in a fencing accident — the tumour slurred his speech for life — David rose through the Academy he would later help abolish. Jacobin deputy, friend of Robespierre, he voted for the king's execution, was twice imprisoned after Thermidor, reinvented himself as Napoleon's painter, and died in Brussels exile, refused burial in France.",
  career:"The Oath of the Horatii hit the 1785 Salon like a drumbeat: rigid Roman resolve scrubbed clean of Rococo sugar, an aesthetic revolution four years ahead of the political one. The Death of Marat turned a murdered radical into a secular pietà painted from the actual crime scene. As pageant-master of the Revolution and then Empire, he designed festivals, uniforms and the very look of regime change.",
  outside:"His studio trained a generation — Ingres, Gros, Girodet — making his classroom the most consequential in art history. In prison he painted his only landscape, the view from his window at the Luxembourg.",
  facts:["He sketched Marie Antoinette from a window as she passed in the tumbril — five quick, pitiless pen lines.",
    "The Coronation contains a diplomatic fiction: Napoleon's mother, who boycotted the event, sits enthroned at its centre.",
    "Officially erased after 1815, his Marat was hidden for decades — too dangerous to display."] },

{ id:"francisco-goya", name:"Francisco Goya", years:"1746–1828", born:1746, died:1828,
  nation:"spain", eras:["18th-century","19th-century"], movements:["romanticism"],
  techniques:["oil-painting","etching","fresco","alla-prima"], style:"romantic",
  palette:["#191512","#6e5a3a","#b0884a","#8a2e26","#d9cba8"],
  tagline:"From royal tapestries to the Black Paintings — reason's sleep, documented",
  works:[{t:"The Third of May 1808",y:"1814"},{t:"Saturn Devouring His Son",y:"c. 1820–23"},{t:"The Naked Maja",y:"c. 1797–1800"},{t:"Los Caprichos",y:"1799"}],
  life:"An Aragonese gilder's son, Goya climbed slowly to First Court Painter — then, at forty-six, a mysterious illness left him permanently deaf. Through war, famine and the Inquisition's attention he kept painting; at seventy-three he covered the walls of his farmhouse with the Black Paintings, and died in voluntary exile in Bordeaux at eighty-two.",
  career:"No artist ever travelled further within one lifetime: sunny Rococo tapestry cartoons, glittering royal portraits that flatter no one, then the Caprichos' donkey-doctors and witches, the unflinching Disasters of War etchings, and finally Saturn eating his child on his own dining-room wall. The Third of May — a man in a white shirt before a firing squad — is the modern war picture, sixty years early.",
  outside:"Deafness sealed him into an inner world he charted in albums of private drawings. His relationship with the Duchess of Alba fuelled two centuries of gossip; his loyal companion Leocadia Weiss shared the Quinta del Sordo — the Deaf Man's Villa — where the Black Paintings were never meant to be seen by anyone.",
  facts:["Los Caprichos went on sale in a perfume shop in 1799 and was withdrawn within days — the Inquisition was curious.",
    "The Naked Maja earned him an Inquisition summons in 1815 to name who commissioned it; his answer is lost.",
    "His skull was missing when his remains were repatriated to Madrid — no one knows where it went."] },

{ id:"jmw-turner", name:"J.M.W. Turner", years:"1775–1851", born:1775, died:1851,
  nation:"britain", eras:["19th-century"], movements:["romanticism"],
  techniques:["oil-painting","watercolor","impasto"], style:"romantic",
  palette:["#f2d9a0","#e8a85e","#a8b8c4","#d97a3e","#f4ecd8"],
  tagline:"The painter of light — weather, steam and apocalypse in gold",
  works:[{t:"The Fighting Temeraire",y:"1839"},{t:"Rain, Steam and Speed",y:"1844"},{t:"Snow Storm — Steam-Boat off a Harbour's Mouth",y:"1842"},{t:"The Slave Ship",y:"1840"}],
  life:"A Covent Garden barber's son, Turner entered the Royal Academy schools at fourteen and never really left the institution — full Academician at twenty-six, professor of perspective, fixture of varnishing days. Gruff, secretive and tender, he spent his last years incognito as 'Mr Booth' in Chelsea with his companion Sophia Booth, and died leaving his life's work to the nation.",
  career:"Turner pushed landscape from topography to cataclysm: ships against burning skies, avalanches, a hare outrunning a locomotive through veils of rain. His late canvases dissolve subject into pure vortices of colour that contemporaries called unfinished and Impressionists, then abstractionists, called prophecy. The Fighting Temeraire — a sailing warship tugged to scrap by a steam tug — packs the entire industrial revolution into one sunset.",
  outside:"He travelled incessantly with sketchbooks — some 19,000 drawings and watercolours entered the Turner Bequest — and famously repainted rivals into the shade on the Academy's walls during varnishing days. Legend says he had himself lashed to a ship's mast in a storm; the story is suspect, the painting (Snow Storm) is not.",
  facts:["His alleged last words: 'The Sun is God.'",
    "He left instructions that two of his canvases hang forever beside two Claudes in the National Gallery — they still do.",
    "Britain's biggest art prize, the Turner Prize, borrows his name precisely because he was controversial."] },

{ id:"john-constable", name:"John Constable", years:"1776–1837", born:1776, died:1837,
  nation:"britain", eras:["19th-century"], movements:["romanticism"],
  techniques:["oil-painting","impasto","alla-prima"], style:"romantic",
  palette:["#7a9a6e","#a8c4d9","#5e4a32","#d9d3ba","#3e5238"],
  tagline:"Six feet of Suffolk sky — landscape as autobiography",
  works:[{t:"The Hay Wain",y:"1821"},{t:"Salisbury Cathedral from the Meadows",y:"1831"},{t:"Cloud Studies",y:"1821–22"}],
  life:"A prosperous miller's son from East Bergholt, Constable spent seven years courting Maria Bicknell against her family's opposition, marrying her only after inheriting independence. Her death from tuberculosis in 1828, with seven children at home, darkened his late skies permanently. London's Academy made him wait until fifty-two for full membership; he never left England.",
  career:"Constable painted one square mile of boyhood — mills, locks, towpaths — with revolutionary fidelity: flickering whites, real clouds, dung and dew. London shrugged, but at the 1824 Paris Salon The Hay Wain won a gold medal and stunned Delacroix into repainting parts of his own canvas. His full-size oil sketches, looser than the exhibited versions, now look like the main event.",
  outside:"He spent summers 'skying' on Hampstead Heath, painting pure cloud studies annotated with wind and weather like a meteorologist. His lectures on landscape argued that painting is a science 'of which pictures are but the experiments.'",
  facts:["He sold more paintings in France than in England during his lifetime, yet refused to travel there.",
    "Lucian Freud curated a Constable show in Paris in 2002 — painter's homage across two centuries.",
    "'Constable country' is now the official tourist name of the Stour valley."] },

{ id:"caspar-david-friedrich", name:"Caspar David Friedrich", years:"1774–1840", born:1774, died:1840,
  nation:"germany", eras:["19th-century"], movements:["romanticism"],
  techniques:["oil-painting","watercolor"], style:"romantic",
  palette:["#9aacb8","#d9d3c4","#5e6e7a","#3a4450","#e8e4d8"],
  tagline:"The back turned to us, the infinite ahead",
  works:[{t:"Wanderer above the Sea of Fog",y:"c. 1818"},{t:"The Sea of Ice",y:"1823–24"},{t:"Abbey in the Oakwood",y:"1809–10"}],
  life:"Born on the Baltic coast at Greifswald, Friedrich was marked at thirteen when his younger brother drowned saving him from breaking ice — a guilt that shadowed everything after. He worked in Dresden in near-monastic routine, married late, suffered a stroke that ended his oil painting, and died poor and unfashionable in 1840.",
  career:"Friedrich invented the Rückenfigur — the figure seen from behind, gazing into fog, moonrise or ice — making the viewer stand inside longing itself. His landscapes are composed like liturgy: ruins, crucifixes on peaks, ships departing at dusk. Dismissed as morbid by mid-century, he was resurrected around 1900 and now defines Romanticism; the Wanderer is among the most reproduced images on Earth.",
  outside:"He walked the Baltic shores and Saxon mountains at dawn and dusk, sketching precisely dated studies he recombined in the studio, working in silence — he refused to let visitors watch. The Nazis' later embrace of his imagery briefly contaminated his reputation until post-war scholarship reclaimed him.",
  facts:["The Sea of Ice — a ship crushed by Arctic plates — flopped unsold; it now reads as the century's bleakest masterpiece.",
    "Samuel Beckett said Waiting for Godot's image came from Friedrich's Two Men Contemplating the Moon.",
    "His studio contained nothing but an easel, a chair and a T-square — visitors found the emptiness 'uncanny.'"] },

{ id:"theodore-gericault", name:"Théodore Géricault", years:"1791–1824", born:1791, died:1824,
  nation:"france", eras:["19th-century"], movements:["romanticism"],
  techniques:["oil-painting","lithography","chiaroscuro"], style:"romantic",
  palette:["#2c2620","#6e5238","#a8a094","#7a2a22","#d9cdb8"],
  tagline:"The Raft of the Medusa — journalism at the scale of history painting",
  works:[{t:"The Raft of the Medusa",y:"1818–19"},{t:"The Charging Chasseur",y:"1812"},{t:"Portraits of the Insane",y:"c. 1822"}],
  life:"Born rich in Rouen, Géricault lived like one of his runaway horses: a scandalous affair with his young aunt-by-marriage, a hidden son, England, racetracks, and a string of riding accidents that — with tuberculosis of the spine — killed him at thirty-two. 'If only I had painted five pictures,' he said at the end; he had painted enough.",
  career:"For the Raft he interviewed survivors of the Medusa shipwreck, built a model raft, and studied severed limbs from the morgue in his studio — modern investigative method fused with Michelangelo's bodies. Exhibited in 1819 as the wreck remained a political scandal, it made suffering anonymous men the subject of a colossal machine: Romanticism's opening cannon-shot, with Delacroix posing among the dying.",
  outside:"Horses obsessed him — cavalry mounts, Epsom races, slaughterhouse studies. His late portraits of psychiatric patients, painted for an alienist doctor, are unprecedented in their level, unjudging humanity; only five of the ten survive.",
  facts:["He shaved his head to force himself into studio seclusion while painting the Raft.",
    "The Raft toured Britain as a paying spectacle — 50,000 visitors in London alone.",
    "Delacroix modelled for one of the dying figures, face down at the raft's centre."] },

{ id:"eugene-delacroix", name:"Eugène Delacroix", years:"1798–1863", born:1798, died:1863,
  nation:"france", eras:["19th-century"], movements:["romanticism"],
  techniques:["oil-painting","broken-color","lithography"], style:"romantic",
  palette:["#8a2620","#2e4a72","#d9b05e","#3e3228","#e3d5b8"],
  tagline:"Colour as passion — the lion of Romanticism",
  works:[{t:"Liberty Leading the People",y:"1830"},{t:"The Death of Sardanapalus",y:"1827"},{t:"Women of Algiers",y:"1834"}],
  life:"Possibly the natural son of Talleyrand — Paris certainly whispered so — Delacroix cultivated a dandy's reserve over a furnace of ambition. Friend of Chopin and George Sand, lifelong bachelor guarded by his housekeeper, he kept a Journal whose intelligence matches his canvases, and died at sixty-five having decorated half the official ceilings of Paris.",
  career:"Delacroix unleashed colour and movement against Ingres's cult of line: massacres, lion hunts, Byron's heroes, and Liberty herself striding the barricade — tricolour up, musket bayoneted. His 1832 journey to Morocco re-tuned his palette for life and filled notebooks the Impressionists later mined. His marbled, vibrating colour handling — tones broken against each other — points straight to Monet, Seurat and Van Gogh.",
  outside:"The Journal records everything: technique, gossip, music criticism, despair at frittered days. He loved cats, painted them as tigers, and famously defined painting as 'a bridge between the soul of the artist and that of the spectator.'",
  facts:["Liberty Leading the People was bought by the state — and then hidden as too inflammatory for most of two decades.",
    "Cézanne, Renoir and Van Gogh all painted homages to Delacroix; Baudelaire built modern art criticism around him.",
    "He appears on the old 100-franc note, palette in hand."] },

{ id:"jean-auguste-dominique-ingres", name:"J.-A.-D. Ingres", years:"1780–1867", born:1780, died:1867,
  nation:"france", eras:["19th-century"], movements:["neoclassicism"],
  techniques:["oil-painting","glazing"], style:"neoclassical",
  palette:["#3a4a6e","#caa86e","#e8ddc8","#7a2e34","#2a2824"],
  tagline:"Line above all — perfection with a deliberately extra vertebra",
  works:[{t:"La Grande Odalisque",y:"1814"},{t:"The Turkish Bath",y:"1862"},{t:"Portrait of Comtesse d'Haussonville",y:"1845"}],
  life:"Born in Montauban, trained under David, Ingres spent long years in Italy nursing genius and grievances in equal measure. He returned to Paris as the anointed guardian of classical line against Delacroix's colour, ruled the Academy with prickly absolutism, and was still painting nudes of impossible smoothness — The Turkish Bath — at eighty-two.",
  career:"'Drawing is the probity of art,' he decreed, then cheerfully broke anatomy whenever beauty demanded: the Grande Odalisque's back has extra vertebrae, necks swan beyond nature. His society portraits — satin, cashmere, mirror reflections — are among the most precise objects ever painted. The moderns he would have despised adored him: Degas, Picasso and Matisse all studied his line like scripture.",
  outside:"His violin was no metaphor — he played seriously, even alongside Paganini, and 'violon d'Ingres' became the French phrase for a passionate hobby. Man Ray's photograph of that name, turning a woman's back into a violin, sealed the joke into art history.",
  facts:["Critics savaged the Odalisque's anatomy in 1814; radiologists have since counted the surplus vertebrae for fun.",
    "He kept a lifelong grudge list and a lifelong devotion to Raphael — both well documented.",
    "The Turkish Bath, a tondo of entwined bathers, was finished when he was 82 and inscribed with his age."] },

{ id:"katsushika-hokusai", name:"Katsushika Hokusai", years:"1760–1849", born:1760, died:1849,
  nation:"japan", eras:["18th-century","19th-century"], movements:["ukiyo-e"],
  techniques:["woodblock"], style:"ukiyoe",
  palette:["#1f3a5f","#5e8ab0","#e8e0c8","#b0b8b4","#2a2c30"],
  tagline:"Old Man Mad About Painting — and one immortal wave",
  works:[{t:"The Great Wave off Kanagawa",y:"c. 1831"},{t:"Fine Wind, Clear Morning (Red Fuji)",y:"c. 1830–32"},{t:"Hokusai Manga",y:"1814–78"}],
  life:"Born in Edo (Tokyo), Hokusai changed his name some thirty times and his address over ninety — when a house grew too cluttered, he reportedly just moved. Widowed twice, bailing out a gambler grandson, he worked into his ninetieth year, signing late works 'Old Man Mad About Painting' and wishing aloud for just ten more years — 'even five' — to become a true artist.",
  career:"His Thirty-six Views of Mount Fuji, produced in his seventies, gave the world the Great Wave: claw-crested water dwarfing boats while Fuji sits tiny and eternal — printed in the new imported Prussian blue. His fifteen-volume Manga sketchbooks catalogued everything that moves: wrestlers, ghosts, waterfalls, cats. When his prints reached Paris, Monet, Degas and Van Gogh collected them like relics; the wave now rides emojis and passports alike.",
  outside:"A showman, he painted a colossal Daruma with a broom-sized brush before crowds, and sparrows on a single grain of rice. His daughter Katsushika Ōi, a formidable painter of nocturnes, ran the studio and likely worked on his late masterpieces.",
  facts:["His deathbed poem hoped his spirit would wander the summer fields as a ghost.",
    "The Great Wave was printed in the thousands and sold for the price of a bowl of noodles.",
    "Debussy's La Mer was published with the Wave on its cover — Japonisme in sound."] },

{ id:"gustave-courbet", name:"Gustave Courbet", years:"1819–1877", born:1819, died:1877,
  nation:"france", eras:["19th-century"], movements:["realism"],
  techniques:["oil-painting","palette-knife","impasto"], style:"tonal",
  palette:["#2e3a2c","#5e6e4a","#8a6e46","#d9cfb4","#1d1a16"],
  tagline:"'Show me an angel and I'll paint one' — Realism's battering ram",
  works:[{t:"A Burial at Ornans",y:"1849–50"},{t:"The Stone Breakers",y:"1849"},{t:"The Artist's Studio",y:"1855"}],
  life:"A vintner's son from Ornans in the Franche-Comté, Courbet stormed Paris with provincial confidence the size of his canvases. President of the arts under the 1871 Paris Commune, he was blamed for toppling the Vendôme Column, jailed, then billed for its re-erection — an impossible sum that drove him to Swiss exile, where he died at fifty-eight.",
  career:"A Burial at Ornans put fifty life-size villagers around an ordinary grave on the scale reserved for kings and gods — 'the burial of Romanticism,' critics fumed. Rejected by the 1855 Exposition, he built his own pavilion next door, titled it REALISM, and charged admission: the first artist-run secession. His palette-knife landscapes, waves and frank nudes kept scandal profitably alive.",
  outside:"Loud, bearded and brilliant at self-promotion, he refused the Legion of Honour from an empire he despised. The Stone Breakers was destroyed in the 1945 Dresden firestorm — Realism's manifesto surviving only in reproduction.",
  facts:["He told the jury he could not paint an angel because he had never seen one.",
    "The state's bill for the Vendôme Column: 323,091 francs — payable in annual instalments he died before starting.",
    "His L'Origine du monde stayed hidden in private collections (one behind a Masson panel at Lacan's house) until 1995."] },

{ id:"jean-francois-millet", name:"Jean-François Millet", years:"1814–1875", born:1814, died:1875,
  nation:"france", eras:["19th-century"], movements:["realism","barbizon-school"],
  techniques:["oil-painting","pastel"], style:"tonal",
  palette:["#9a8a5e","#d9c890","#6e5a3a","#a8b09a","#3e3a2a"],
  tagline:"The gleaners' painter — peasant labour given gravity",
  works:[{t:"The Gleaners",y:"1857"},{t:"The Angelus",y:"1857–59"},{t:"The Sower",y:"1850"}],
  life:"Born to a farming family on the Normandy coast, Millet knew field work before he knew Paris — and fled the city's cholera in 1849 for the village of Barbizon, where he stayed for life, poor for most of it, raising nine children at the forest's edge.",
  career:"His monumental peasants — sowing, gleaning, pausing for the evening Angelus bell — gave agricultural labour the dignity and scale of scripture, which conservative critics read, nervously, as socialism. The Gleaners' three bent women scandalised the Salon of 1857; within decades The Angelus was the most reproduced painting in France, hanging in parlours that had never seen a museum.",
  outside:"Van Gogh copied him obsessively — over twenty painted homages — calling him 'father Millet.' Dalí was so haunted by The Angelus that he wrote a 'paranoiac-critical' book claiming the couple mourned a buried child; an X-ray later showed a painted-over shape Dalí declared a coffin, with satisfaction.",
  facts:["A bidding war for The Angelus between France and America in 1889 made it briefly the world's most expensive painting.",
    "The Sower was reproduced on countless political posters — the Church and the Left both claimed him.",
    "Boston's MFA holds a major Millet trove thanks to early American admirers — he sold to the New World before the old one caught on."] },

{ id:"edouard-manet", name:"Édouard Manet", years:"1832–1883", born:1832, died:1883,
  nation:"france", eras:["19th-century"], movements:["realism","impressionism"],
  techniques:["oil-painting","alla-prima"], style:"impressionist",
  palette:["#1d1a18","#e8e0d0","#8a2e34","#5e6e5a","#caa45c"],
  tagline:"The reluctant revolutionary in a top hat",
  works:[{t:"Olympia",y:"1863"},{t:"Le Déjeuner sur l'herbe",y:"1863"},{t:"A Bar at the Folies-Bergère",y:"1882"}],
  life:"Son of a Parisian judge who wanted law, Manet failed the naval academy twice (sailing to Rio in between) before being permitted to paint. An elegant boulevardier with radical instincts, he craved official honours while collecting official scandals, and died at fifty-one of complications of syphilis, his left leg amputated days before.",
  career:"The Déjeuner — a nude woman picnicking with dressed dandies — detonated the 1863 Salon des Refusés; Olympia, a courtesan returning the viewer's stare, required guards at the next Salon. His flat lighting, frank blacks and quotations of Titian and Velázquez declared that painting was about painting now. Mentor and magnet for the Impressionists, he never once exhibited with them — the Salon was the battlefield he refused to leave.",
  outside:"His circle was literary as much as painterly: Baudelaire's companion, Zola's defender (and portraitist), Mallarmé's weekly conversation partner. Berthe Morisot, his model and intellectual equal, married his brother Eugène.",
  facts:["A Bar at the Folies-Bergère, with its impossible mirror, was painted while he was dying — barmaids came to pose at his studio.",
    "He slashed The Incident in a Bullring after mockery, keeping two fragments now in different countries.",
    "The Legion of Honour finally arrived in 1881; 'It is too late,' he wrote — but he wore it."] },

{ id:"claude-monet", name:"Claude Monet", years:"1840–1926", born:1840, died:1926,
  nation:"france", eras:["19th-century","20th-century"], movements:["impressionism"],
  techniques:["oil-painting","broken-color","alla-prima","impasto"], style:"impressionist",
  palette:["#9ab8d9","#b4d9c4","#e8c8d4","#f0e8c8","#7a8ab0"],
  tagline:"Impression, sunrise to water lilies — sixty years chasing light",
  works:[{t:"Impression, Sunrise",y:"1872"},{t:"Rouen Cathedral series",y:"1892–94"},{t:"Water Lilies (Grandes Décorations)",y:"1914–26"},{t:"Haystacks series",y:"1890–91"}],
  life:"A Le Havre grocer's son who first earned money drawing caricatures, Monet endured decades of poverty — dunning letters, a near-suicidal plunge in the Seine in 1868, the death of his first wife Camille at thirty-two — before Giverny, gardens and worldwide fame. He painted his lily pond through cataracts and two operations until his death at eighty-six.",
  career:"His harbour sketch Impression, Sunrise lent the whole movement its mocking name. Monet's method — broken colour, no black, the same motif repainted as the light turned — culminated in the series: twenty-five haystacks, thirty Rouen Cathedrals, then three decades of water lilies ending in the panoramic Orangerie cycle he donated to France as a 'haven of peaceful meditation' after WWI.",
  outside:"Giverny was his other masterpiece: he diverted a river arm for the pond, imported Japanese prints and bridges, employed six gardeners, and scheduled lunch by the light. A gourmand and tyrant of the table, he kept cooking journals now published as books.",
  facts:["During cataract years his palette slid red; some late canvases were repainted after surgery restored his blues.",
    "He insisted on painting outdoors in winter with hot-water bottles and three overcoats, his beard hung with icicles.",
    "The Orangerie's oval Water Lily rooms opened months after his death — called 'the Sistine Chapel of Impressionism.'"] },

{ id:"pierre-auguste-renoir", name:"Pierre-Auguste Renoir", years:"1841–1919", born:1841, died:1919,
  nation:"france", eras:["19th-century","20th-century"], movements:["impressionism"],
  techniques:["oil-painting","broken-color","alla-prima"], style:"impressionist",
  palette:["#e8c4a8","#d98a96","#8aa7c4","#a8c49a","#f2e8d4"],
  tagline:"'The pain passes, but the beauty remains'",
  works:[{t:"Bal du moulin de la Galette",y:"1876"},{t:"Luncheon of the Boating Party",y:"1880–81"},{t:"The Umbrellas",y:"c. 1881–86"}],
  life:"A tailor's son from Limoges, Renoir started at thirteen painting flowers on porcelain — factory training he credited for his lightness of hand. Fame came with middle age; rheumatoid arthritis came with it, twisting his hands until brushes had to be wedged between his fingers. He painted from a wheelchair to the end, dying at seventy-eight after reportedly finishing a last still life of anemones.",
  career:"Renoir painted happiness as a serious subject: dance halls dappled with afternoon light, boating parties, plush-cheeked children and nudes like ripe fruit. The Moulin de la Galette and Boating Party are Impressionism at its most sociable — friends, lovers and dogs, identifiable by name. A later 'sour period' of tighter classical drawing alienated some allies but fed directly into Picasso's neoclassicism.",
  outside:"His household — the boisterous Aline Charigot, three sons, the indomitable nurse-model Gabrielle — appears throughout the work. Son Jean became one of cinema's greatest directors, and his memoir 'Renoir, My Father' is among the best books ever written about a painter.",
  facts:["Asked how he painted with crippled hands, he supposedly answered: 'With my eye.' The quote varies; the wheelchair didn't.",
    "He and Monet painted side by side at La Grenouillère in 1869 — paired canvases historians call Impressionism's birth certificate.",
    "In his last years he 'sculpted' by directing an assistant's hands — sculpture by dictation."] }
);
