/* PIGMENT — artists 7/7 : Pop to the present */
window.ARTISTS.push(
{ id:"lucian-freud", name:"Lucian Freud", years:"1922–2011", born:1922, died:2011,
  nation:"britain", eras:["20th-century","21st-century"], movements:["school-of-london","realism"],
  techniques:["oil-painting","impasto","etching"], style:"tonal",
  palette:["#a8896e","#d9c4a8","#5e5648","#8a5e52","#e8e0d0"],
  tagline:"Flesh, scrutinised — thousands of hours per portrait",
  works:[{t:"Benefits Supervisor Sleeping",y:"1995"},{t:"Reflection (Self-Portrait)",y:"1985"},{t:"Girl with a White Dog",y:"1950–51"}],
  life:"Grandson of Sigmund Freud, born in Berlin and brought to London in 1933 as the Nazis rose, Freud lived as he painted: on his own terms — gambler, recluse, father of at least fourteen acknowledged children, friend and portraitist of everyone from gangsters to the Queen. He painted standing up to the end, dying at eighty-eight.",
  career:"From hypnotic early precision he shifted, with hog-hair brushes and the dry granular pigment cremnitz white, to paint-as-flesh: nudes observed across hundreds of hours until, as he said, the paint 'works as skin does.' Benefits Supervisor Sleeping — Sue Tilley on a battered sofa — sold in 2008 for $33.6 million, then a record for a living artist. Sitters' time, not flattery, was his only fee.",
  outside:"He bet catastrophically on horses ('the money had to not matter'), bred whippets who entered the portraits, and guarded his privacy with a ferocity that made every interview an event. His tiny 2001 portrait of Elizabeth II — unflinching, jaw set — split the press between outrage and awe.",
  facts:["Sitters logged up to 2,400 hours; one portrait of his mother spanned years of daily sessions.",
    "He painted standing, palette in hand, wiping brushes on rags that became a wall-sized installation in themselves.",
    "Kate Moss sat for him; he also etched her — pregnant — at night sessions after dinner."] },

{ id:"andy-warhol", name:"Andy Warhol", years:"1928–1987", born:1928, died:1987,
  nation:"usa", eras:["20th-century"], movements:["pop-art"],
  techniques:["silkscreen","acrylic-painting","flat-color"], style:"pop",
  palette:["#e0427a","#f0c82e","#2e8a8a","#c4302a","#1a1a1a"],
  tagline:"The Factory's silver mirror — fifteen minutes, infinitely reprinted",
  works:[{t:"Campbell's Soup Cans",y:"1962"},{t:"Marilyn Diptych",y:"1962"},{t:"Shot Sage Blue Marilyn",y:"1964"},{t:"Mao",y:"1972"}],
  life:"Born Andrew Warhola to Carpatho-Rusyn immigrants in Pittsburgh, a sickly child who collected movie-star photos in bed, Warhol conquered New York first as its best-paid shoe illustrator. He survived Valerie Solanas's 1968 shooting — clinically dead on the table, scarred for life — and died in 1987 after routine gallbladder surgery, at fifty-eight.",
  career:"In 1962 he exhibited thirty-two Campbell's soup cans and erased the line between supermarket and museum. The silkscreened Marilyns, Elvises, car crashes and electric chairs — repetition as both glamour and numbness — made the Factory the engine room of Pop. 'I want to be a machine,' he said, then proved a machine could have the era's sharpest eye.",
  outside:"He filmed eight-hour sleeping men, managed the Velvet Underground, founded Interview magazine, wore silver wigs he treated as sculpture — and attended Mass quietly for decades, volunteering at soup kitchens, a fact that startled obituarists. His 612 'Time Capsules' — sealed boxes of everything — took archivists decades to open.",
  facts:["Shot Sage Blue Marilyn sold in 2022 for $195 million — the most expensive 20th-century artwork ever auctioned.",
    "The 'fifteen minutes of fame' line may have been a collaborator's — Warhol happily took the credit either way.",
    "His mother Julia lived with him in Manhattan for twenty years and lettered some early works."] },

{ id:"roy-lichtenstein", name:"Roy Lichtenstein", years:"1923–1997", born:1923, died:1997,
  nation:"usa", eras:["20th-century"], movements:["pop-art"],
  techniques:["oil-painting","acrylic-painting","benday-dots","flat-color"], style:"pop",
  palette:["#c4302a","#f0c82e","#2e50c4","#f4f1e8","#1a1a1a"],
  tagline:"WHAAM! — comic-strip romance and warfare, dot by hand-painted dot",
  works:[{t:"Whaam!",y:"1963"},{t:"Drowning Girl",y:"1963"},{t:"Look Mickey",y:"1961"}],
  life:"A Manhattan jazz kid who served as an army draftsman and enlarged-map maker in WWII, Lichtenstein taught college art for years while painting in styles that wouldn't stick. The breakthrough came at thirty-seven — by family legend, when one of his sons pointed at a Mickey Mouse comic and bet he couldn't paint 'as good as that.' He worked serenely until his death at seventy-three.",
  career:"Look Mickey (1961) imported the comic frame whole: Ben-Day dots, speech balloon, primary colours. Whaam! and Drowning Girl blew pulp melodrama to history-painting scale, every mechanical-looking dot stencilled by hand. Critics asked if it was art at all — Life ran 'Is He the Worst Artist in the U.S.?' — while he coolly proceeded to redo Monet, Picasso and finally his own brushstroke as a cartoon of itself.",
  outside:"Soft-spoken and wry where Warhol was spectral, he kept jazz saxophone, sailing and a studio routine of monastic regularity. The original comic artists whose panels he enlarged received neither fee nor credit — a debate that still shadows the work and fuels its scholarship.",
  facts:["Whaam!'s source panel came from DC's All-American Men of War; the original artist, Irv Novick, had once been Lichtenstein's army superior.",
    "He tested compositions in tiny collages, then projected and traced — precision masquerading as print.",
    "His Brushstrokes series renders the 'heroic' AbEx gesture in flat dots: the politest assassination in art history."] },

{ id:"jasper-johns", name:"Jasper Johns", years:"b. 1930", born:1930, died:null,
  nation:"usa", eras:["20th-century","21st-century"], movements:["neo-dada","pop-art"],
  techniques:["encaustic","oil-painting","lithography","collage"], style:"pop",
  palette:["#b03a32","#e8e0c8","#2e3e8a","#caa45c","#3e3a36"],
  tagline:"Flags, targets, numbers — things the mind already knows, made strange",
  works:[{t:"Flag",y:"1954–55"},{t:"Target with Four Faces",y:"1955"},{t:"False Start",y:"1959"}],
  life:"Raised in small-town South Carolina by relatives after his parents' divorce, Johns reached New York at twenty-two, destroyed nearly everything he'd made, and began again with a dream: he would paint a large American flag. With Robert Rauschenberg — partner in art and life through the pivotal years — he dismantled Abstract Expressionism's heroics. He works still, in Connecticut, into his nineties.",
  career:"Flag (1954–55) — the Stars and Stripes in encaustic over shredded newspaper — is both a flag and a painting of one, a koan that rerouted art toward the conceptual. Targets, stencilled numbers and maps followed: 'things seen but not looked at.' Leo Castelli's 1958 debut show sold to MoMA off the walls; Pop, minimalism and conceptualism all claim him as ancestor.",
  outside:"Famously guarded, he collects Cézanne, gardens, and answers interpretation with courteous fog: 'My work is largely concerned with relations between seeing and knowing, seeing and saying, seeing and believing.' In 2011 he received the Presidential Medal of Freedom — the first painter since Calder's era so honoured.",
  facts:["False Start sold privately in 2006 for a reported $80 million — then the record for a living artist.",
    "The army stationed him in Sendai, Japan, during the Korean War — encaustic's wax patience perhaps owes something to it.",
    "He and Rauschenberg paid early bills designing department-store windows as 'Matson Jones.'"] },

{ id:"david-hockney", name:"David Hockney", years:"b. 1937", born:1937, died:null,
  nation:"britain", eras:["20th-century","21st-century"], movements:["pop-art","contemporary-art"],
  techniques:["acrylic-painting","oil-painting","collage","watercolor"], style:"contemporary",
  palette:["#3e9ad9","#7ac4e8","#e8a85e","#2e8a5e","#f0ece0"],
  tagline:"A bigger splash — from Bradford to LA pools to iPad springs",
  works:[{t:"A Bigger Splash",y:"1967"},{t:"Portrait of an Artist (Pool with Two Figures)",y:"1972"},{t:"Pearblossom Highway",y:"1986"},{t:"A Year in Normandie",y:"2020–21"}],
  life:"A Bradford clerk's son who announced his vocation at eleven, Hockney left for California in 1964 and found his great subject: sunlight on water and on tanned Los Angeles leisure. Openly gay in his work years before decriminalisation in Britain, hearing-impaired since mid-life and cheerfully chain-smoking against all advice, he paints daily in Normandy and London well into his late eighties.",
  career:"A Bigger Splash froze a dive's aftermath into acrylic flatness; Portrait of an Artist set a living-artist auction record of $90.3 million in 2018. Restless with media — Polaroid 'joiner' collages, fax art, opera sets, iPhone dawns, the 90-metre iPad frieze A Year in Normandie — he treats each device as a new brush. His book Secret Knowledge argued the old masters used optics; art historians are still arguing back.",
  outside:"He fought smoking bans with op-eds, painted his dachshunds Stanley and Boodgie by the dozen, and keeps opera blasting in the studio. 'I can draw anywhere,' he says of the iPad — 'and I no longer need to carry the wet canvas.'",
  facts:["He sent spring drawings from his iPad to friends during the 2020 lockdown: 'Do remember they can't cancel the spring.'",
    "Pearblossom Highway was assembled from over 700 photographs taken across nine days.",
    "His Yorkshire Wolds paintings required a purpose-built rig to paint 15-metre works outdoors in winter."] },

{ id:"gerhard-richter", name:"Gerhard Richter", years:"b. 1932", born:1932, died:null,
  nation:"germany", eras:["20th-century","21st-century"], movements:["contemporary-art","abstract-art","postmodernism"],
  techniques:["oil-painting","squeegee"], style:"gestural",
  palette:["#8a8a8a","#c4c4c4","#3e3e3e","#c4302a","#e8e8e8"],
  tagline:"The blur and the squeegee — doubt made visible, beautifully",
  works:[{t:"Betty",y:"1988"},{t:"October 18, 1977 cycle",y:"1988"},{t:"Abstraktes Bild series",y:"1976– "},{t:"Cologne Cathedral window",y:"2007"}],
  life:"Born in Dresden, Richter grew up under two dictatorships: an aunt murdered in the Nazi euthanasia programme, a father broken by war, then socialist realism's drab demands. He escaped to West Germany in 1961, months before the Wall, and rebuilt painting from zero in Cologne, where — officially retired from painting since 2017 — he still draws and designs, past ninety.",
  career:"Richter refused to choose between photography and paint: grey-blurred family snapshots and newspaper images (including the harrowing Baader-Meinhof cycle October 18, 1977) alternate with vast Abstraktes Bilder dragged into being with metre-wide squeegees — chance layered, scraped, vetoed, accepted. The double practice made him contemporary painting's central figure and its most expensive living European painter at auction.",
  outside:"His Cologne Cathedral window — 11,500 hand-blown squares in 72 colours, arranged by controlled randomness — drew the archbishop's sniff that it belonged 'in a mosque'; the public disagreed. Aunt Marianne, painted from a family photo, was later identified by researchers as his euthanised aunt — biography surfacing through the blur.",
  facts:["He painted over dozens of early canvases; his catalogue raisonné famously starts at a self-chosen 'opus 1', the Table, of 1962.",
    "With Sigmar Polke he coined 'Capitalist Realism' — Pop's wry East-West cousin — in 1963.",
    "His painted-over photographs sell for fortunes; he gives many away to friends as postcards."] },

{ id:"yayoi-kusama", name:"Yayoi Kusama", years:"b. 1929", born:1929, died:null,
  nation:"japan", eras:["20th-century","21st-century"], movements:["contemporary-art","pop-art"],
  techniques:["acrylic-painting","flat-color","mixed-media"], style:"pointillist",
  palette:["#e8c43e","#c4302a","#1a1a1a","#f4f1e8","#e0427a"],
  tagline:"Infinity nets and polka dots — obliteration as ecstasy",
  works:[{t:"Infinity Nets series",y:"1958– "},{t:"Pumpkin",y:"1994"},{t:"Infinity Mirror Rooms",y:"1965– "}],
  life:"Born to a seed-nursery family in Matsumoto, Kusama began hallucinating fields of dots as a child — visions her mother punished her for drawing. She stormed avant-garde New York from 1958, returned to Tokyo in 1973, and since 1977 has lived voluntarily in a psychiatric hospital, crossing the street each day to a studio where, in her nineties, she paints with undimmed velocity.",
  career:"Her white-on-white Infinity Net paintings — thousands of looping strokes — predated and influenced minimalism; her mirrored Infinity Rooms now generate museum queues measured in hours. Dots cover her pumpkins, her installations, naked happenings of 1960s New York and Louis Vuitton flagship stores alike: 'polka dots are a way to infinity.' She is reportedly the world's top-selling living female artist.",
  outside:"In 1960s New York she staged anti-war 'body festivals,' wrote an open letter offering to paint dots on Richard Nixon, and accused the art world of borrowing her ideas without credit — claims history has largely vindicated. She has published novels and poetry; her red-wigged, dot-gowned persona is itself a continuous artwork.",
  facts:["Her giant pumpkin on Naoshima island was swept away by a 2021 typhoon — fished from the sea and replaced to national relief.",
    "She offered to sell her Venice Biennale mirror balls for $2 each in 1966 — 'narcissism for sale'; officials stopped her.",
    "Her obliteration rooms invite visitors to sticker white interiors into total dot-saturation — participatory infinity."] },

{ id:"anselm-kiefer", name:"Anselm Kiefer", years:"b. 1945", born:1945, died:null,
  nation:"germany", eras:["20th-century","21st-century"], movements:["neo-expressionism","contemporary-art"],
  techniques:["oil-painting","impasto","mixed-media"], style:"tonal",
  palette:["#3e3a36","#6e6252","#a89272","#1d1c1a","#8a6e46"],
  tagline:"Lead, ash and straw — German memory at the scale of myth",
  works:[{t:"Margarethe",y:"1981"},{t:"The Orders of the Night",y:"1996"},{t:"Sulamith",y:"1983"}],
  life:"Born in the war's final months in a Black Forest town under bombardment, Kiefer studied law before art and announced himself in 1969 with Occupations — photographs of himself giving the banned Nazi salute at European sites, forcing the amnesia question. He moved to France in 1992, transforming a derelict silk factory at Barjac into a 35-hectare artwork of towers and tunnels, and now works outside Paris at aircraft-hangar scale.",
  career:"His vast canvases — encrusted with straw, ash, clay, sunflower seeds, dresses, molten lead — excavate German history and myth through Paul Celan's Holocaust poetry (Margarethe's golden hair in straw, Sulamith's ashen hair in char), alchemy and Kabbalah. Painting, in his hands, regained the moral weight critics said it had lost; the Louvre commissioned him in 2007, its first living artist since Braque.",
  outside:"He collects lead by the ton — including the roof of Cologne Cathedral, bought when it was replaced — and lets his works weather in rain and fields, calling decay a collaborator. Trained on Joyce, Bachofen and the mystics, he gives interviews like seminars; his studio compounds, periodically opened to film crews, resemble the ruins he paints.",
  facts:["His Barjac estate, La Ribaute, with its 48 concrete towers, opened to the public as a foundation in 2022.",
    "Occupations (1969) remains divisive — confrontation or provocation — exactly as designed.",
    "Wim Wenders's 3D documentary 'Anselm' (2023) tours his hangars like a planet."] },

{ id:"jean-michel-basquiat", name:"Jean-Michel Basquiat", years:"1960–1988", born:1960, died:1988,
  nation:"usa", eras:["20th-century"], movements:["neo-expressionism","street-art"],
  techniques:["acrylic-painting","spray-paint","collage","mixed-media"], style:"street",
  palette:["#1a1a1a","#e8c43e","#c4302a","#2e8a8a","#f0ece0"],
  tagline:"SAMO© to the auction block — crowns, anatomy and eight furious years",
  works:[{t:"Untitled (Skull)",y:"1981"},{t:"Hollywood Africans",y:"1983"},{t:"Horn Players",y:"1983"}],
  life:"Born in Brooklyn to a Haitian father and Puerto Rican mother, Basquiat was a gifted, restless kid whose mother took him to museums and whose hospital stay at seven (hit by a car) came with a gift of Gray's Anatomy — a lifelong source. He left home at seventeen, slept on benches and friends' floors, and was an international star by twenty-two; heroin killed him at twenty-seven.",
  career:"As SAMO©, with Al Diaz, he aphorised SoHo's walls; by 1981 the 'Radiant Child' essay in Artforum announced the gallery phase. His canvases fuse crowned Black heroes — boxers, jazzmen, saints — with anatomy diagrams, lists, erasures ('I cross out words so you will see them more'), hoboglyphs and Caribbean history at allover velocity. The Warhol collaborations (1984–85) were panned then, treasured now.",
  outside:"He played in the noise band Gray, appeared in Blondie's 'Rapture' video, dated Madonna before fame found her, and painted in Armani suits he then wore, paint-spattered, to dinner. His estate, managed by his father and sisters, now licenses a global iconography of crowns.",
  facts:["Untitled (1982), a blue skull canvas, sold in 2017 for $110.5 million — the record for an American artist at auction at the time.",
    "He sold hand-painted postcards to Warhol at a restaurant years before they met as equals.",
    "The crown motif, friends said, crowned his heroes — and dared anyone to deny him his own."] },

{ id:"keith-haring", name:"Keith Haring", years:"1958–1990", born:1958, died:1990,
  nation:"usa", eras:["20th-century"], movements:["street-art","pop-art"],
  techniques:["spray-paint","flat-color","acrylic-painting"], style:"street",
  palette:["#c4302a","#f0c82e","#2e50c4","#2e8a5e","#1a1a1a"],
  tagline:"Radiant babies in the subway — art for everybody, drawn at full sprint",
  works:[{t:"Radiant Baby",y:"1982"},{t:"Crack is Wack",y:"1986"},{t:"Tuttomondo",y:"1989"}],
  life:"A church-raised kid from Kutztown, Pennsylvania who learned cartooning from his father, Haring hit New York's School of Visual Arts in 1978 and its club scene simultaneously. Diagnosed with AIDS in 1988, he spent his last two years working and giving at double speed, dying at thirty-one; his foundation continues both missions.",
  career:"Spotting empty black ad panels in the subway, he began chalking — quick, linear, joyous: barking dogs, radiant babies, dancing figures — up to forty drawings a day, arrested repeatedly, adored universally. Gallery fame followed without dimming the public mission: murals on the Berlin Wall, hospitals and schoolyards worldwide, and Tuttomondo in Pisa, finished months before his death.",
  outside:"His 1986 Pop Shop sold his imagery on T-shirts and buttons at street prices — sacrilege to purists, democracy to him ('My work was starting to become too expensive… the Pop Shop makes it accessible'). An untiring AIDS and anti-apartheid activist, he painted Grace Jones's body and children's hospital corridors with equal devotion.",
  facts:["He drew an estimated 5,000 subway chalk drawings between 1980 and 1985; almost all were papered over or stolen.",
    "Crack is Wack, painted without permission on a Harlem handball court, was protected by the city within weeks.",
    "Madonna donated proceeds of her 'Like a Prayer' single launch performances to his memory's causes."] },

{ id:"fernando-botero", name:"Fernando Botero", years:"1932–2023", born:1932, died:2023,
  nation:"colombia", eras:["20th-century","21st-century"], movements:["contemporary-art"],
  techniques:["oil-painting","pastel"], style:"naive",
  palette:["#e8c8a8","#c4763e","#8a4a42","#5e7a8e","#f0e6d0"],
  tagline:"Boterismo — volume as joy, satire and national monument",
  works:[{t:"Mona Lisa, Age Twelve",y:"1959"},{t:"The Presidential Family",y:"1967"},{t:"Abu Ghraib series",y:"2005"}],
  life:"Born in Medellín and briefly enrolled in matador school before choosing the gentler bullring of art, Botero left for Europe at twenty to copy the old masters and never stopped conversing with them. Working between Paris, Monte Carlo and Pietrasanta, he donated entire museums' worth of art to Bogotá and Medellín, and died at ninety-one — Colombia declared days of national mourning.",
  career:"His inflated figures — generals, cardinals, dancers, plump Mona Lisas — began, he said, with a mandolin whose soundhole he drew too small in 1956: suddenly volume itself was the style, 'Boterismo.' Dismissed by some critics as decorative, he answered with the searing Abu Ghraib series (2005), donated to Berkeley, proving the rounded style could carry rage as well as tenderness.",
  outside:"He insisted his figures weren't fat: 'I paint volume, not fat women.' His donations — including works by Picasso, Monet and Dalí from his own collection — created Bogotá's Museo Botero, free to the public by his condition. The death of his four-year-old son Pedro in a 1974 car crash entered the work in tender, recurring portraits.",
  facts:["His bronze fat cat in Barcelona and doves in Medellín are among the world's most-photographed public sculptures.",
    "A 1995 guerrilla bomb destroyed his Medellín dove sculpture, killing 23; he donated a twin to stand beside the ruin, 'wounded and whole.'",
    "He painted every day including his ninetieth birthday: 'The day I don't paint, I feel guilty.'"] },

{ id:"marlene-dumas", name:"Marlene Dumas", years:"b. 1953", born:1953, died:null,
  nation:"south-africa", eras:["20th-century","21st-century"], movements:["contemporary-art"],
  techniques:["oil-painting","watercolor","alla-prima"], style:"colorfield",
  palette:["#8a9bb0","#d9b4be","#3e3a44","#e8dcd0","#6e3a4e"],
  tagline:"Faces at their most exposed — ink, oil and moral discomfort",
  works:[{t:"The Painter",y:"1994"},{t:"Models",y:"1994"},{t:"For Whom the Bell Tolls",y:"2008"}],
  life:"Raised on a vineyard near Cape Town under apartheid — an experience that fixed her attention on how images carry power — Dumas moved to Amsterdam in 1976 for study and stayed. She works from her Amsterdam studio, writes poetic texts to accompany exhibitions, and has become one of the most influential and highest-valued living painters.",
  career:"She paints only from photographs — Polaroids, newspaper clippings, film stills — never live models: lovers, corpses, strippers, her daughter Helena as a glowering toddler-painter, Amy Winehouse, Osama bin Laden. Thin oil washes and inks let faces bloom and smear into ambiguity; tenderness and threat share every surface. The Visitor sold in 2008 for $6.3 million, then a record for a living female artist.",
  outside:"Her catalogue texts and aphorisms are quoted like the paintings — 'I paint because I am a dirty woman' begins a famous one; 'Painting is about the trace of the human touch' ends arguments. She collaborates with poets and has written on Baldwin and on the ethics of depicting the dead.",
  facts:["The Painter — her daughter with paint-stained hands — became a defining image of contemporary portraiture.",
    "She calls her sources a 'morgue' of images, after newspaper archives.",
    "Her Stedelijk/Tate/Beyeler retrospective was titled 'The Image as Burden' — her whole aesthetic in four words."] },

{ id:"kerry-james-marshall", name:"Kerry James Marshall", years:"b. 1955", born:1955, died:null,
  nation:"usa", eras:["20th-century","21st-century"], movements:["contemporary-art"],
  techniques:["acrylic-painting","collage"], style:"fauvist",
  palette:["#1a1a1a","#2e8a5e","#c4302a","#e8c43e","#5e3a8a"],
  tagline:"Mastry — painting Black life into the canon, in unapologetic black",
  works:[{t:"Past Times",y:"1997"},{t:"De Style",y:"1993"},{t:"School of Beauty, School of Culture",y:"2012"}],
  life:"Born in Birmingham, Alabama at the civil-rights flashpoint and raised near Watts in Los Angeles — 'You can't grow up there and not feel like you've got some kind of social responsibility' — Marshall studied at Otis, settled in Chicago, and taught for years while building his project with deliberate patience.",
  career:"Confronting the near-absence of Black figures in museum painting, he resolved to fill the gap genre by genre — garden scenes, barbershops, beauty salons, housing-project pastorals — with figures painted in literal, luminous carbon black. Every canvas deploys old-master structure on purpose: 'mastry' claimed, not requested. His 2016–17 retrospective 'Mastry' was a landmark; Past Times sold in 2018 for $21.1 million, a record for a living African-American artist.",
  outside:"A comics devotee, he created the Black superhero strip Rythm Mastr, and lectures with a historian's command of Géricault as readily as George Clinton. The buyer of Past Times turned out to be Sean 'Diddy' Combs — a circulation of Black wealth and imagery Marshall noted with satisfaction.",
  facts:["He keeps paint recipes for his blacks — ivory, mars, carbon mixed with blues and greens — like a colourist's grimoire.",
    "A Marshall hung in the Obama White House — the first work by a Black artist purchased for its public rooms came earlier, but his loomed largest in the era's imagery.",
    "He has said he wants his paintings 'unequivocally, emphatically Black' — adjective and noun both."] },

{ id:"julie-mehretu", name:"Julie Mehretu", years:"b. 1970", born:1970, died:null,
  nation:"ethiopia", eras:["21st-century"], movements:["contemporary-art","abstract-art"],
  techniques:["acrylic-painting","mixed-media"], style:"contemporary",
  palette:["#3e4a5e","#8a9bb0","#d9d3c4","#c4542e","#1d1c22"],
  tagline:"Maps, riots and weather systems — abstraction at stadium scale",
  works:[{t:"Stadia II",y:"2004"},{t:"Mural (Goldman Sachs)",y:"2009"},{t:"HOWL, eon (I, II)",y:"2017"}],
  life:"Born in Addis Ababa to an Ethiopian geography professor and an American Montessori teacher, Mehretu fled with her family in 1977 as the Derg regime closed in, growing up in East Lansing, Michigan. Yale-trained, MacArthur-anointed (2005), she works from a Manhattan studio whose paintings require scaffolding, and co-runs residencies supporting African artists.",
  career:"Her canvases laminate strata — architectural plans, stadium diagrams, migration routes, news photographs blurred to weather — under storms of inked gesture, building what she calls 'story maps of no location.' Mural, her 25-metre commission for Goldman Sachs's lobby, compresses the history of capitalism into a single weather system; HOWL, eon, her two-canvas epic for SFMOMA, does it for the American West.",
  outside:"She speaks of Ethiopia's revolution, the Rodney King uprising and dislocation as her underlayers — literally: erased photographs of unrest seed many grounds. With her former partner, artist Jessica Rankin, she raised two sons; with Mickalene Thomas and others she has organised artist-led philanthropy for East Africa.",
  facts:["Mural was painted over two years with a team of assistants and its own engineered scaffolding rig.",
    "Her Whitney retrospective (2021) filled two museum floors — drawings to seven-metre canvases.",
    "She was among Time's 100 most influential people in 2020 — rare air for an abstract painter."] },

{ id:"takashi-murakami", name:"Takashi Murakami", years:"b. 1962", born:1962, died:null,
  nation:"japan", eras:["20th-century","21st-century"], movements:["superflat","pop-art","contemporary-art","postmodernism","nihonga"],
  techniques:["acrylic-painting","flat-color","silkscreen"], style:"pop",
  palette:["#e0427a","#7ac4e8","#f0c82e","#2e8a5e","#f4f1e8"],
  tagline:"Superflat — smiling flowers from a PhD in traditional painting",
  works:[{t:"727",y:"1996"},{t:"Flower Ball series",y:"2002– "},{t:"Tan Tan Bo Puking",y:"2002"}],
  life:"A Tokyo taxi driver's son who wanted to animate like Miyazaki, Murakami instead earned the first PhD in nihonga (traditional Japanese painting) from Tokyo University of the Arts — then spent a decade broke, eating instant noodles in New York residencies, before building Kaikai Kiki, his Warhol-Factory-meets-anime-studio enterprise employing hundreds.",
  career:"His Superflat theory (2001) connects Edo-period picture-flatness, post-war anime and consumer culture into one lineage — and erases the high/low wall on principle. Mr. DOB, his mouse-eared alter ego, mutates from cute to monstrous across decades; his grinning flowers carpet museum retrospectives, Kanye West's Graduation cover and Louis Vuitton handbags alike, each platform treated as equally serious.",
  outside:"He runs an art fair for young artists (GEISAI), produces films and streetwear, collaborated with Billie Eilish and Drake, and tweets through crunches like a one-man studio diary. After the 2011 tsunami he painted his vast Five Hundred Arhats cycle — Buddhist consolation at 100 metres long.",
  facts:["His Vuitton 'Multicolore' monogram (2003, with Marc Jacobs) ran for twelve years and reshaped luxury collaboration forever.",
    "My Lonesome Cowboy, his anime-erotic sculpture, sold for $15.2 million in 2008.",
    "He names Sen no Rikyū, the tea master, among his heroes: flatness, he argues, is five centuries deep."] },

{ id:"banksy", name:"Banksy", years:"b. circa 1974", born:1974, died:null,
  nation:"britain", eras:["21st-century"], movements:["street-art","contemporary-art"],
  techniques:["spray-paint","flat-color"], style:"street",
  palette:["#1a1a1a","#c4302a","#8a8a8a","#e8e4d8","#3e3e3e"],
  tagline:"Identity unknown, message unmissable — the stencil as global headline",
  works:[{t:"Girl with Balloon",y:"2002"},{t:"Love is in the Bin",y:"2018"},{t:"Devolved Parliament",y:"2009"}],
  life:"Presumed born in Bristol around 1974, Banksy emerged from the city's 1990s graffiti scene and has kept his identity unconfirmed through three decades of global fame — an anonymity that is itself his most durable artwork. Investigations, lawsuits and documentary sleuths circle; the work keeps appearing overnight on walls from London to the West Bank to war-time Ukraine.",
  career:"His stencils — rats with paintbrushes, a protester hurling flowers, a girl losing a heart balloon — fuse one-liner speed with political bite. Dismaland (2015), his 'bemusement park,' and Bethlehem's Walled Off Hotel (with 'the worst view in the world') scaled the prank to institution size. When Girl with Balloon shredded itself at Sotheby's mid-auction in 2018, the stunt instantly became the artwork: retitled Love is in the Bin, it resold in 2021 for £18.6 million.",
  outside:"His film Exit Through the Gift Shop earned an Oscar nomination while possibly being a hoax about hoaxes. During 'Better Out Than In' (New York, 2013) he sold original canvases from an anonymous Central Park stall for $60 — passers-by bought eight all day.",
  facts:["The shredder was built into the frame years in advance; it jammed halfway, which Banksy claimed was not the plan.",
    "His authentication body is named Pest Control — it certifies street pieces never, canvases reluctantly.",
    "A Bristol school named a house after him; he repaid them with a mural and a note excusing students from homework."] },

{ id:"njideka-akunyili-crosby", name:"Njideka Akunyili Crosby", years:"b. 1983", born:1983, died:null,
  nation:"nigeria", eras:["21st-century"], movements:["contemporary-art"],
  techniques:["acrylic-painting","collage","mixed-media"], style:"contemporary",
  palette:["#b0703a","#2e6e5a","#e8c89a","#8a3a4e","#3e3a30"],
  tagline:"Lagos and Los Angeles on one surface — intimacy, layered like memory",
  works:[{t:"The Beautyful Ones series",y:"2012– "},{t:"I Refuse to be Invisible",y:"2010"},{t:"Dwell: Aso Ebi",y:"2017"}],
  life:"Born in Enugu, Nigeria — her mother, Dora Akunyili, became a national hero battling counterfeit drugs as a regulator — Akunyili Crosby came to the US at sixteen, studied at Swarthmore and Yale, and married American artist Justin Crosby. She works in Los Angeles, a MacArthur 'genius' fellow at thirty-four whose canvases now anchor museum collections worldwide.",
  career:"Her large-scale interiors — couples at tea, families on patterned sofas, her own wedding — are built from paint, coloured pencil and acetone photo-transfers of Nigerian magazines, family albums and fabric, so every shadow teems with imagery. The technique is the thesis: diasporic life as layered simultaneity, 'the third space' where Lagos commercials glow inside an LA living room.",
  outside:"She speaks often of her mother's example — public service as fearlessness — and mines the family archive openly; her Predecessors pair grandmother and mother across generations. Her works' market ascent (eight figures at auction) has made her, by choice, vocal about artist resale rights.",
  facts:["She received the MacArthur Fellowship in 2017, eleven years after her first painting class.",
    "Her series title 'The Beautyful Ones' borrows Ayi Kwei Armah's novel — hope spelled against the grain.",
    "A 2018 mural version of her work wrapped MOCA Los Angeles's exterior wall above Grand Avenue."] }
);
