/* PIGMENT — artists 9/13 : still life, the 18th century & the Ottoman nakkaşhane */
window.ARTISTS.push(
{ id:"jacob-van-ruisdael", name:"Jacob van Ruisdael", years:"c. 1629–1682", born:1629, died:1682,
  nation:"netherlands", eras:["17th-century"], movements:["dutch-golden-age","baroque"],
  techniques:["oil-painting","etching","glazing"], style:"tonal",
  palette:["#5b6e5a","#a8b8c4","#8a6e46","#32433f","#e8e3d3"],
  tagline:"Two-thirds sky — the landscape learns to brood",
  works:[{t:"The Windmill at Wijk bij Duurstede",y:"c. 1670"},{t:"The Jewish Cemetery",y:"c. 1654–55"},{t:"View of Haarlem with Bleaching Grounds",y:"c. 1670–75"}],
  life:"Born into a Haarlem family of frame-makers and painters, Ruisdael never married, caring for his father into old age. A document suggests he may also have qualified in medicine and performed surgeries in Amsterdam — scholars still argue. He died at about fifty-three and was buried in Haarlem's St Bavo.",
  career:"Ruisdael made Dutch flatness monumental: towering cloudbanks over tiny human business, a windmill standing against weather like a fate. The Jewish Cemetery — tombs, ruin, rainbow, rushing stream — is allegory by pure landscape. Constable called his skies the finest ever painted and copied them stroke by stroke; Romanticism begins here, quietly.",
  outside:"Goethe devoted an essay, 'Ruisdael as Poet', to three of his paintings. His only documented pupil was Meindert Hobbema, whose avenue at Middelharnis became almost as famous as anything by the master.",
  facts:["He painted at least a dozen versions of Haarlem seen from the dunes — locals call them 'Haerlempjes'.",
    "The waterfall pictures of his middle years were inspired by another artist's Scandinavian sketches — Ruisdael never saw Norway.",
    "Constable: 'The sky is the chief organ of sentiment' — a lesson learned from Ruisdael."] },

{ id:"clara-peeters", name:"Clara Peeters", years:"c. 1589–after 1657", born:1589, died:1657,
  nation:"belgium", eras:["17th-century"], movements:["flemish-baroque","baroque"],
  techniques:["oil-painting","glazing"], style:"tonal",
  palette:["#1d1a16","#caa45c","#8a8276","#5e2a2a","#e8e0d0"],
  tagline:"Breakfast pieces with a secret — her own face in the pewter",
  works:[{t:"Still Life with Cheeses, Almonds and Pretzels",y:"c. 1615"},{t:"Still Life with Flowers and Goblets",y:"1612"},{t:"Still Life with Fish",y:"c. 1611"}],
  life:"Almost nothing documents Clara Peeters's life — probably Antwerp-born, possibly trained outside the guild system that excluded women, active by 1607. Her survival in history rests entirely on the roughly forty masterly panels that carry her signature, sometimes carved into a painted knife handle.",
  career:"She helped invent the 'breakfast piece': cheeses stacked like geology, pretzels, olives, a knocked-over goblet catching the light. Her trademark is hidden in plain sight — minute self-portraits reflected in pewter lids and gilt goblets, sometimes seven times in one painting: a woman painter insisting, covertly, I am here.",
  outside:"In 2016 the Prado gave her its first solo exhibition of any woman painter — four centuries after her lifetime, with a catalogue essay built largely from those tiny reflections.",
  facts:["Several signatures appear on painted knives — the bridal-gift kind engraved with a name.",
    "Her reflections predate and outnumber most male painters' hidden self-portraits.",
    "She painted fish so precisely that marine biologists can identify the species."] },

{ id:"rachel-ruysch", name:"Rachel Ruysch", years:"1664–1750", born:1664, died:1750,
  nation:"netherlands", eras:["17th-century","18th-century"], movements:["dutch-golden-age","baroque"],
  techniques:["oil-painting","glazing"], style:"rococo",
  palette:["#1d2416","#c4663a","#d9b4be","#caa45c","#e8e3d3"],
  tagline:"Sixty years of impossible bouquets",
  works:[{t:"Flower Still Life",y:"c. 1700"},{t:"Roses, Convolvulus, Poppies and Other Flowers",y:"c. 1680s"},{t:"Fruit and Insects",y:"1711"}],
  life:"Daughter of Amsterdam's famed anatomist-botanist Frederik Ruysch — whose curiosity cabinets she helped decorate as a girl — Ruysch painted from fifteen to eighty-five, through marriage and ten children. Court painter to the Elector Palatine in Düsseldorf, she was celebrated across Europe and died at eighty-six, the unrivalled queen of flower painting.",
  career:"Her bouquets are botanically impossible — spring tulips beside autumn grapes — and optically irresistible: asymmetric spills of blossom alive with caterpillars, beetles and dew. In her lifetime her paintings fetched higher prices than Rembrandt's ever had; signed and dated into her eighties, they form one of art's longest careers.",
  outside:"Her father's scientific specimens — and his macabre dioramas of skeletons weeping into handkerchiefs — trained her eye for the border of beauty and decay; an insect always gnaws somewhere in the perfection.",
  facts:["She and her husband won 75,000 guilders in the 1723 Dutch lottery — she kept painting anyway.",
    "Dated works exist from when she was 15 and when she was 83.",
    "Düsseldorf made her court painter without requiring her to leave Amsterdam — remote work, 1708."] },

{ id:"francois-boucher", name:"François Boucher", years:"1703–1770", born:1703, died:1770,
  nation:"france", eras:["18th-century"], movements:["rococo"],
  techniques:["oil-painting","pastel","etching"], style:"rococo",
  palette:["#8aa7c4","#e8b4c8","#f2d9a8","#7da26e","#f0e8d8"],
  tagline:"Pompadour's painter — pink clouds, available by the metre",
  works:[{t:"The Toilette of Venus",y:"1751"},{t:"Madame de Pompadour",y:"1756"},{t:"The Rising of the Sun",y:"1753"}],
  life:"A Parisian lace-designer's son, Boucher rose through engraving Watteau to become First Painter to Louis XV, director of the Academy, and drawing tutor and image-maker to Madame de Pompadour. Working dawn to dusk for decades — some 10,000 drawings — he died in his Louvre studio at sixty-six.",
  career:"Boucher industrialised the Rococo: Venuses on demand, shepherdesses, chinoiserie, tapestry cartoons for Beauvais and Gobelins, porcelain for Sèvres, opera sets — an entire decorative universe in powder blue and rose. Diderot scolded that he had 'everything except truth'; Boucher cheerfully agreed, finding nature 'too green and badly lit.'",
  outside:"His studio was a famous cabinet of curiosities — shells, lacquer, Chinese porcelain — raw material for fantasy. Pupil and son-in-law ran satellite production; Fragonard learned the trade in his shop.",
  facts:["His quip about nature being 'badly lit' is the Rococo's whole aesthetic in five words.",
    "Pompadour's portraits by him are political manifestos in lace — patron and painter co-authoring an image.",
    "The Goncourt brothers' rediscovery of him in the 1860s rescued the entire century's reputation."] },

{ id:"rosalba-carriera", name:"Rosalba Carriera", years:"1673–1757", born:1673, died:1757,
  nation:"italy", eras:["18th-century"], movements:["rococo"],
  techniques:["pastel","miniature-painting","watercolor"], style:"rococo",
  palette:["#d9b4be","#a8c4d9","#e8d9c0","#8a8276","#f0e8d8"],
  tagline:"The Venetian who made pastel a continental craze",
  works:[{t:"Self-Portrait Holding a Portrait of Her Sister",y:"1715"},{t:"Portrait of Louis XV as a Young Man",y:"1720–21"},{t:"A Young Lady with a Parrot",y:"c. 1730"}],
  life:"A Venetian lace-maker's daughter, Carriera began by painting snuffbox miniatures on ivory for Grand Tourists, then conquered Europe with pastel portraits — Paris fêted her for a triumphant year in 1720–21, electing her to the royal Academy. Cataracts stole her sight in old age despite operations; she died in Venice at eighty-four.",
  career:"She made pastel — until then a sketching tool — the medium of aristocratic portraiture: powdery skin, shimmering silk, likenesses flattering yet alive, finished in sittings short enough for royal patience. Her Paris visit set off a pastel mania that lasted a century; Maurice Quentin de La Tour and Liotard walked through the door she opened.",
  outside:"Her diary of the Paris year records sittings with the boy-king Louis XV and visits from Watteau, whom she portrayed months before his death. Her sister Giovanna was her lifelong studio partner; Giovanna's death broke her years before blindness did.",
  facts:["Augustus III of Saxony amassed over 150 of her pastels — a dedicated 'Rosalba cabinet' in Dresden.",
    "She was elected to academies in Rome, Bologna and Paris — a woman, a foreigner, and a pastelist.",
    "Her late self-portraits, eyes failing, are among the era's most unflinching images of age."] },

{ id:"joshua-reynolds", name:"Joshua Reynolds", years:"1723–1792", born:1723, died:1792,
  nation:"britain", eras:["18th-century"], movements:["rococo","neoclassicism"],
  techniques:["oil-painting","glazing"], style:"baroque",
  palette:["#5e2a2a","#caa45c","#3e4a6e","#d9cdb4","#1d1a16"],
  tagline:"The Grand Manner, by committee of one — first president of the Royal Academy",
  works:[{t:"Portrait of Omai",y:"c. 1776"},{t:"Mrs Siddons as the Tragic Muse",y:"1784"},{t:"Self-Portrait as a Deaf Man",y:"c. 1775"}],
  life:"A Devon schoolmaster's son, Reynolds studied Italy's masters, then organised British art into existence: founding president of the Royal Academy (1768), knighted, host of London's great dinner table — Johnson, Burke, Garrick, the original 'Club'. Deaf in one ear from a Roman cold, he worked until blindness, dying at sixty-eight.",
  career:"His 'Grand Manner' dressed English sitters in the poses of gods and Caesars — actresses as muses, colonels as Apollo — flattery elevated to theory in his fifteen Discourses, the most influential art lectures in English. Output was industrial: thousands of portraits, a fee ladder published like a menu.",
  outside:"His pigment experiments — bitumen, carmine, wax — faded and cracked notoriously fast; wags said his portraits 'die before the man.' He bid for posterity anyway, and the Discourses outlived every cracked canvas.",
  facts:["He painted himself cupping his deaf ear — disability as self-branding.",
    "Gainsborough's deathbed reconciliation: 'We are all going to heaven, and Van Dyck is of the company.'",
    "Turner asked to be buried beside him in St Paul's — and was."] },

{ id:"angelica-kauffman", name:"Angelica Kauffman", years:"1741–1807", born:1741, died:1807,
  nation:"switzerland", eras:["18th-century","19th-century"], movements:["neoclassicism"],
  techniques:["oil-painting","etching"], style:"neoclassical",
  palette:["#8a4a4e","#5e7a8e","#d9c49a","#e9ddc4","#3a3430"],
  tagline:"Founding mother of the Royal Academy — history painting in a woman's hand",
  works:[{t:"Cornelia Presenting Her Children as Her Treasures",y:"c. 1785"},{t:"Self-Portrait Hesitating between Music and Painting",y:"1794"},{t:"Ariadne Abandoned by Theseus",y:"1774"}],
  life:"A Swiss muralist's prodigy daughter, fluent in four languages and trained on the road, Kauffman conquered London in 1766 and was one of only two women among the Royal Academy's thirty-six founders. After a bigamous con-man 'count' nearly wrecked her, she married painter Antonio Zucchi and reigned over Rome's art world until her death at sixty-five.",
  career:"She insisted on history painting — the noblest, most male genre — staging Roman virtue with female protagonists: Cornelia offering her children as her jewels. Her designs spread across Europe on engravings, Wedgwood and painted ceilings; clients from Catherine the Great to Goethe (her close friend, who sat for her) queued in Rome.",
  outside:"Because women were barred from nude study, she built her histories from draped figures and ingenuity — and was painted into Zoffany's group portrait of the Academy only as a picture on the wall, since the room contained naked models.",
  facts:["Canova directed her Rome funeral on the model of Raphael's; two of her paintings were carried in procession.",
    "No woman followed her and Mary Moser as full Royal Academicians until 1936.",
    "Her self-portrait choosing between Music and Painting stages her life as a parable — career as classical allegory."] },

{ id:"george-stubbs", name:"George Stubbs", years:"1724–1806", born:1724, died:1806,
  nation:"britain", eras:["18th-century","19th-century"], movements:["romanticism"],
  techniques:["oil-painting","etching"], style:"tonal",
  palette:["#8a6e46","#d9c890","#5e4a32","#a8b09a","#2e2a22"],
  tagline:"Whistlejacket, life-size — anatomy raised to majesty",
  works:[{t:"Whistlejacket",y:"c. 1762"},{t:"The Anatomy of the Horse",y:"1766"},{t:"Horse Attacked by a Lion",y:"1769"}],
  life:"A Liverpool currier's son, self-taught and stubborn, Stubbs spent eighteen months in a remote Lincolnshire farmhouse dissecting horse carcasses suspended from the ceiling, drawing every layer — then etched the plates himself when no engraver would. The resulting Anatomy of the Horse (1766) made his name; he worked until his death at eighty-one.",
  career:"Whistlejacket — a rearing Arabian, life-size, against bare gold ground, no rider, no landscape, no master — is the most radical portrait of the British eighteenth century, and it's of a horse. The racing aristocracy paid him to paint their champions; he gave them, again and again, the animal as a being rather than a possession.",
  outside:"Obsessed by a (possibly invented) lion-attacking-horse antique he saw in Rome, he repainted the violence seventeen times. With Josiah Wedgwood he developed enamel painting on ceramic plaques — chemistry experiments between commissions; at 75 he began a comparative anatomy of humans, tigers and chickens.",
  facts:["The Anatomy of the Horse stayed a veterinary reference for a century.",
    "Whistlejacket's empty background was so unusual that legends invented an unfinished King George on top.",
    "He reportedly carried horse carcasses up to his dissection room alone — the strongest arms in British art."] },

{ id:"joseph-wright-of-derby", name:"Joseph Wright of Derby", years:"1734–1797", born:1734, died:1797,
  nation:"britain", eras:["18th-century"], movements:["romanticism"],
  techniques:["oil-painting","tenebrism","chiaroscuro"], style:"baroque",
  palette:["#120c08","#d9852e","#f0c878","#5e7a8e","#3a2416"],
  tagline:"Candlelight for the age of science",
  works:[{t:"An Experiment on a Bird in the Air Pump",y:"1768"},{t:"A Philosopher Lecturing on the Orrery",y:"c. 1766"},{t:"Vesuvius in Eruption",y:"c. 1776–80"}],
  life:"Wright stayed loyal to Derby — England's industrial crucible — while London beckoned, painting the scientists, mill-owners and experiments of the Midlands Enlightenment. Plagued by depression and asthma, he quarrelled with the Royal Academy, exhibited independently, and died at sixty-two in the town that became his surname.",
  career:"He transplanted Caravaggio's candlelight from saints to science: a travelling lecturer suffocating a cockatoo in a vacuum jar while a family watches — wonder, doubt and a little girl's grief in one pool of lamplight. The Orrery, the forge scenes and Arkwright's cotton mills by night made him the Industrial Revolution's first and greatest painter.",
  outside:"His circle overlapped the Lunar Society — Erasmus Darwin (his doctor and sitter), Wedgwood (his patron) — science and art dining at the same table. A trip to Naples yielded an obsession: over thirty eruptions of Vesuvius, most painted from memory.",
  facts:["The Air Pump experiment shown was a real popular-science demonstration — bird usually spared.",
    "He painted Vesuvius erupting about 30 times but saw only minor activity in person.",
    "Museums class him as the first professional painter to express the Industrial Revolution's spirit."] },

{ id:"piranesi", name:"Giovanni Battista Piranesi", years:"1720–1778", born:1720, died:1778,
  nation:"italy", eras:["18th-century"], movements:["neoclassicism","romanticism"],
  techniques:["etching","printmaking"], style:"metaphysical",
  palette:["#2c2620","#6e5238","#a8a094","#d9cdb8","#1d1a16"],
  tagline:"Imaginary prisons, printed forever — Rome bigger than Rome",
  works:[{t:"Carceri d'invenzione",y:"1750/1761"},{t:"Vedute di Roma",y:"1748–78"},{t:"Antichità Romane",y:"1756"}],
  life:"A Venetian stonemason's son trained as an architect, Piranesi reached Rome at twenty and never recovered: 'These speaking ruins have filled my spirit.' He built almost nothing — one church — but etched over a thousand colossal plates, ran a famous print shop and antiquities business near the Spanish Steps, and worked until his death at fifty-eight.",
  career:"His Views of Rome supplied Europe's imagination with a city grander, darker and taller than reality — Goethe found the real Rome a disappointment by comparison. The Carceri — fourteen imaginary prisons of staircases to nowhere, chains, and impossible vaults — leapt from souvenir to nightmare, haunting the Romantics, Surrealists, Escher and every dungeon ever filmed.",
  outside:"He fought the era's Greece-versus-Rome debate like a street brawl, publishing polemics with measured drawings as ammunition. His sons kept printing his coppers for decades; the plates survive in Rome, still capable of printing.",
  facts:["De Quincey described the Carceri from memory in his opium memoirs — having never actually seen them.",
    "His one completed building, Santa Maria del Priorato, can be glimpsed through the famous Aventine keyhole.",
    "Architects from Adam to OMA cite him — the most influential architect who barely built."] },

{ id:"matrakci-nasuh", name:"Matrakçı Nasuh", years:"c. 1480–c. 1564", born:1480, died:1564,
  nation:"turkey", eras:["16th-century"], movements:["ottoman-miniature"],
  techniques:["miniature-painting","gouache","watercolor"], style:"ornament",
  palette:["#1f6e8a","#c4302a","#caa43e","#2e4a3e","#e8dcc0"],
  tagline:"The polymath who painted cities like maps that dream",
  works:[{t:"View of Istanbul (Mecmu-ı Menazil)",y:"c. 1537"},{t:"Stations of the Iraq Campaign",y:"1537"},{t:"View of Aleppo",y:"c. 1537"}],
  life:"Recruited through the Ottoman palace system, Nasuh of Visoko served Süleyman the Magnificent as mathematician, historian, master swordsman and inventor of a martial game with cudgels — the 'matrak' that gave him his name. Painter was only one line on history's most intimidating CV; he died around 1564.",
  career:"Chronicling Süleyman's Baghdad campaign, he invented a genre: topographic miniatures that portray each halting-place — Istanbul, Tabriz, Aleppo — as a jewel-bright city of mosques, bridges and gardens seen from everywhere at once, with not a single human figure. His Istanbul, with its crowded Golden Horn, remains the city's most beloved early portrait.",
  outside:"He wrote arithmetic textbooks used in Ottoman schools, staged mock-fortress tournaments for the sultan with siege engines of his own design, and earned a patent declaring him 'üstad' — master — of lance and club. Turkey's TÜBİTAK science institution and a crater on Mercury bear his name.",
  facts:["His city views double as military intelligence — itinerary, water sources and defences, beautifully encrypted.",
    "UNESCO marked his (approximate) 450th anniversary in 2014.",
    "Historians mine his Istanbul view for buildings that no longer exist — art as urban archive."] },

{ id:"nakkas-osman", name:"Nakkaş Osman", years:"fl. 1560–1595", born:1535, died:1595,
  nation:"turkey", eras:["16th-century"], movements:["ottoman-miniature"],
  techniques:["miniature-painting","gouache","gold-leaf"], style:"ornament",
  palette:["#8a2620","#1f6e8a","#caa43e","#2e4a3e","#e8dcc0"],
  tagline:"The sultan's chief eye — an empire documented in gold and lapis",
  works:[{t:"Surname-i Hümayun (Imperial Festival Book)",y:"1582–88"},{t:"Şemailname (Portraits of the Sultans)",y:"1579"},{t:"Hünername",y:"1584–88"}],
  life:"Head of the imperial nakkaşhane — the palace painting workshop — under three sultans, Osman is the classical Ottoman miniature's defining master. Of the man himself the archives keep palace ledgers, not personality: wages, bolts of cloth, the respect of the court historian Lokman, with whom he produced the age's great illustrated chronicles.",
  career:"His workshop's Surname-i Hümayun records the 1582 circumcision festival of Prince Mehmed — fifty-two days of guild parades, acrobats, fireworks and confectionery palaces marching across hundreds of double pages: the Ottoman sixteenth century filmed in gouache. His Şemailname portrait series fixed the official likenesses of the first twelve sultans, copied for centuries.",
  outside:"He directed teams the way a film director runs a set — outlining compositions, assigning faces, drapery and gold to specialists. The crisp drawing, banded compositions and documentary appetite of 'the Osman style' became the house manner of the entire empire.",
  facts:["The festival book shows Istanbul's guilds parading their crafts — including miniaturists painting a parade, inside the parade.",
    "His sultan portraits drew on Italian models, including medals — and Gentile Bellini's Mehmed II.",
    "Wage registers list him for decades — art history reconstructed from payroll."] },

{ id:"levni", name:"Abdulcelil Levni", years:"c. 1680–1732", born:1680, died:1732,
  nation:"turkey", eras:["18th-century"], movements:["ottoman-miniature"],
  techniques:["miniature-painting","gouache","gold-leaf"], style:"ornament",
  palette:["#c4663a","#1f6e8a","#e8cd7a","#5e3450","#f0e8d8"],
  tagline:"The Tulip Era's last great miniaturist — colour was literally his name",
  works:[{t:"Surname-i Vehbi",y:"c. 1720–27"},{t:"Portrait of Sultan Ahmed III",y:"c. 1720"},{t:"Single-figure studies of women and musicians",y:"c. 1710–25"}],
  life:"Born in Edirne, Abdulcelil Çelebi rose through the palace workshop to become chief painter under Ahmed III, taking the pen-name 'Levnî' — 'the colourful'. He presided over the miniature's swan song during the pleasure-loving Tulip Era, wrote folk poetry on the side, and died in Istanbul in 1732; his grave survives near the Otakçılar mosque.",
  career:"His masterwork illustrates the 1720 festival for the sultan's sons: fireworks over the Golden Horn, dancing, oiled wrestlers, sugar gardens floated on barges — 137 paintings looser, wittier and more atmospheric than anything before. His single-figure studies — a woman tying her sash, a sleepy musician — bring an almost modern intimacy and softness into the tradition.",
  outside:"As 'Levnî' he composed songs and verses in the folk tradition that are still anthologised. After him the Ottoman court's taste drifted to Westernising oil painting — he is the tradition's golden sunset, studied by every Turkish artist who later sought a national modernism.",
  facts:["His name is a one-word artist statement: 'of colour'.",
    "Art historians read his loosened line and three-quarter faces as the miniature meeting the Baroque.",
    "The 1720 festival book pairs his images with the poet Vehbi's text — a deluxe multimedia production."] },

{ id:"william-blake", name:"William Blake", years:"1757–1827", born:1757, died:1827,
  nation:"britain", eras:["18th-century","19th-century"], movements:["romanticism","symbolism"],
  techniques:["etching","watercolor","tempera"], style:"surreal",
  palette:["#d9852e","#8a2620","#3e3a52","#e8c43e","#1d1410"],
  tagline:"Visions printed at home — heaven and hell, hand-coloured",
  works:[{t:"The Ancient of Days",y:"1794"},{t:"Newton",y:"1795–c. 1805"},{t:"The Great Red Dragon series",y:"1805–10"}],
  life:"A London hosier's son who saw a tree filled with angels at eight and never stopped seeing, Blake trained as an engraver and lived poor, radical and unwavering. With his wife Catherine — whom he taught to read, write and print — he produced his books at home. He died at sixty-nine, singing, he said, of what he saw in heaven.",
  career:"Inventing 'illuminated printing' — relief-etched plates combining his poems and images, hand-coloured copy by copy — he created the Songs of Innocence and of Experience, The Marriage of Heaven and Hell, and prophetic epics nobody bought. His colour prints of Newton bent over compasses and the Ancient of Days measuring the deep are Romanticism's metaphysics in pictures.",
  outside:"Tried for sedition in 1803 after ejecting a soldier from his garden (acquitted), he sided with every revolution, walked London talking with prophets, and held that 'the imagination is not a state: it is the human existence itself.' Patron John Linnell's circle of young 'Ancients' venerated his last years.",
  facts:["He and Catherine printed, coloured and bound nearly every copy of his books personally — no two identical.",
    "His grave's exact spot in Bunhill Fields was only re-identified and marked in 2018.",
    "At his death he was working on Dante watercolours — 102 survive, many unfinished mid-vision."] },

{ id:"camille-corot", name:"Camille Corot", years:"1796–1875", born:1796, died:1875,
  nation:"france", eras:["19th-century"], movements:["realism","barbizon-school"],
  techniques:["oil-painting","alla-prima","etching"], style:"tonal",
  palette:["#9a8a5e","#a8b8a4","#5e6e7a","#d9d3ba","#3e3a2a"],
  tagline:"Silver mornings — the bridge from Claude to Monet",
  works:[{t:"The Bridge at Narni",y:"1826"},{t:"Souvenir de Mortefontaine",y:"1864"},{t:"Woman with a Pearl",y:"c. 1868–70"}],
  life:"A Parisian draper's son freed by a small family allowance, Corot painted across Italy and France for fifty years, unmarried — 'my only mistress is nature' — and grew into the most beloved figure in French art: 'Père Corot', endlessly generous. He died at seventy-eight, weeks after his last landscape.",
  career:"His Italian open-air sketches of the 1820s — walls of light, structure without fuss — anticipate everything plein-air painting became; his late 'souvenirs', silver-grey willows dissolving in mist, sold as fast as he could dream them. Bridging Neoclassical order and Impressionist freedom, he was claimed as master by Pissarro, Morisot and Monet alike.",
  outside:"He quietly bought a cottage for the blind, destitute Daumier and pensioned Millet's widow. His generosity extended, awkwardly, to authentication: he sometimes signed students' and copyists' works so they could eat — feeding the most-forged reputation in art.",
  facts:["The joke runs: 'Corot painted 3,000 canvases, 10,000 of which are in America.'",
    "He kept painting figures privately for decades; the late Woman with a Pearl now hangs near the Mona Lisa it echoes.",
    "Degas preferred his figures to his trees — and bought them."] },

{ id:"honore-daumier", name:"Honoré Daumier", years:"1808–1879", born:1808, died:1879,
  nation:"france", eras:["19th-century"], movements:["realism"],
  techniques:["lithography","oil-painting","watercolor"], style:"expressionist",
  palette:["#2c2620","#8a6e46","#a8a094","#5e2a2a","#d9cdb8"],
  tagline:"Four thousand lithographs against the powerful — six months in prison for one",
  works:[{t:"Gargantua",y:"1831"},{t:"Rue Transnonain, le 15 avril 1834",y:"1834"},{t:"The Third-Class Carriage",y:"c. 1862–64"}],
  life:"A Marseille glazier's son raised poor in Paris, Daumier drew for satirical papers nearly fifty years — four thousand lithographs skewering kings, lawyers, landlords and speculators. Imprisoned six months at twenty-four for caricaturing King Louis-Philippe as Gargantua swallowing the people's taxes, he went nearly blind in old age and died in a cottage Corot had quietly given him.",
  career:"His Rue Transnonain — a massacred working-class family sprawled by their bed — proved a lithograph could be a history painting. The paintings he made for himself, barely exhibited (one solo show, the year before his death), are astonishing: third-class railway passengers, Don Quixote dissolving into ochre light — Realism shading into something close to Expressionism.",
  outside:"Champfleury, Baudelaire and Degas championed him; Balzac reportedly said 'there's a Michelangelo in that fellow.' He refused the Legion of Honour, consistent with a lifetime of refusing power its comforts.",
  facts:["The censors banned political caricature in 1835 — so he satirised 'manners' with equal venom for decades.",
    "His clay caricature busts of parliamentarians, kneaded for reference, are now museum sculpture.",
    "Almost blind, he was saved from eviction by Corot's gift of the Valmondois cottage where he died."] }
);
