/* PIGMENT — artists 14/14 : the 15th-century founders & one chess player */
window.ARTISTS.push(
{ id:"jan-van-eyck", name:"Jan van Eyck", years:"c. 1390–1441", born:1390, died:1441,
  nation:"belgium", eras:["15th-century"], movements:["early-netherlandish"],
  techniques:["oil-painting","glazing"], style:"renaissance",
  palette:["#7a1f2b","#1f3a5f","#caa43e","#2e4a3e","#e8dcc4"],
  tagline:"'As I can' — oil paint perfected, reality outdone",
  works:[{t:"The Ghent Altarpiece (with Hubert van Eyck)",y:"1432"},{t:"The Arnolfini Portrait",y:"1434"},{t:"Man in a Red Turban",y:"1433"}],
  life:"Painter, courtier and occasional secret agent to Philip the Good of Burgundy, van Eyck ran a Bruges workshop while undertaking confidential missions — including a journey to Portugal to paint a princess his duke was considering marrying, portrait as diplomatic intelligence. Honoured and well paid in his lifetime, he died in Bruges in 1441.",
  career:"He did not invent oil paint, but he perfected it so completely that legend credited him anyway: translucent glazes building light inside the picture, brocade thread by thread, a mirror reflecting a whole room in a circle the size of a plum. The Ghent Altarpiece, begun with his brother Hubert, is Northern painting's founding monument; the Arnolfini Portrait its most debated double act.",
  outside:"He signed works with a personal motto, 'Als ich kan' — 'as I can (but not as I would)' — false modesty from the most precise eye in Europe, and wrote himself into the Arnolfini mirror's graffiti: 'Johannes de eyck fuit hic. 1434.' Jan van Eyck was here.",
  facts:["The Ghent Altarpiece is the most stolen artwork in history — about thirteen crimes, from Napoleon to the Nazis.",
    "Its Just Judges panel, stolen in 1934, is still missing; Ghent police technically keep the case open.",
    "Philip the Good stood godfather to his child and paid him 'for certain secret journeys' the ledgers decline to describe."] },

{ id:"rogier-van-der-weyden", name:"Rogier van der Weyden", years:"c. 1399–1464", born:1399, died:1464,
  nation:"belgium", eras:["15th-century"], movements:["early-netherlandish"],
  techniques:["oil-painting","glazing"], style:"renaissance",
  palette:["#8a1f2b","#2e3e6e","#d9b46a","#5e2a2a","#e9ddc8"],
  tagline:"The painter of tears — emotion engineered with Flemish precision",
  works:[{t:"The Descent from the Cross",y:"c. 1435"},{t:"The Last Judgment Polyptych (Beaune)",y:"c. 1445–50"},{t:"Portrait of a Lady",y:"c. 1460"}],
  life:"Born in Tournai and trained under Robert Campin, Rogier became official painter to the city of Brussels — a post created for him — and the most influential Northern artist of his century, with patrons from the Burgundian court to the Medici and the kings of Castile. He died in Brussels in 1464, wealthy, charitable and internationally famous.",
  career:"His Descent from the Cross compresses ten grieving figures into a shallow golden box, Mary's swoon rhyming with her son's dead arc — choreography of pure sorrow that painters copied for a century. Where van Eyck observed, Rogier moved: the tears on his mourners' cheeks, each a tiny van Eyck of optics, exist to make yours answer.",
  outside:"Not one surviving work bears his signature; his entire oeuvre is scholarly reconstruction from copies, documents and style — fame so great it survived the loss of every label. His four Justice panels for Brussels' town hall, praised across Europe, burned in the French bombardment of 1695.",
  facts:["Cardinal Nicholas of Cusa cited a Rogier in a treatise on God's all-seeing gaze — theology by way of his realism.",
    "Pilgrims to Beaune's hospital saw his Last Judgment opened only on Sundays — the original limited screening.",
    "The Prado's Descent began as a crossbowmen's guild altarpiece; tiny crossbows hide in the tracery corners."] },

{ id:"fra-angelico", name:"Fra Angelico", years:"c. 1395–1455", born:1395, died:1455,
  nation:"italy", eras:["15th-century"], movements:["early-renaissance"],
  techniques:["tempera","fresco","gold-leaf"], style:"renaissance",
  palette:["#9ab8d9","#e8cd7a","#d97a8a","#5e7a9e","#f4ecd8"],
  tagline:"Painting as prayer — the friar beatified for his brushwork",
  works:[{t:"The Annunciation (San Marco)",y:"c. 1440–45"},{t:"The Deposition",y:"c. 1432–34"},{t:"Coronation of the Virgin",y:"c. 1435"}],
  life:"Guido di Pietro took vows as the Dominican friar Giovanni da Fiesole; posterity renamed him Angelico, the angelic one. He painted the friars' own cells at San Marco in Florence as aids to meditation, served his order as prior, declined (says Vasari) an archbishopric, and died in Rome painting chapels for the pope.",
  career:"He fused the new Renaissance space with the old gold-ground radiance: his San Marco Annunciation greets the friars at the top of the dormitory stairs with an angel whose wings still carry rainbow gradients of pure pigment. Vasari claims he never retouched a stroke, believing the first attempt was God's will, and never painted a Crucifixion without weeping.",
  outside:"Pope John Paul II beatified him in 1982 — the only canonical painter who is also, officially, Blessed — and declared him patron of artists. His feast day, February 18, is effectively painting's name day.",
  facts:["He is the only major painter with a Vatican-approved halo of his own.",
    "Each San Marco cell got its own fresco — art assigned like scripture readings, monk by monk.",
    "Ruskin called his work 'not art, but inspired devotion' — meant as the highest praise, taken as both."] },

{ id:"masaccio", name:"Masaccio", years:"1401–1428", born:1401, died:1428,
  nation:"italy", eras:["15th-century"], movements:["early-renaissance"],
  techniques:["fresco","tempera"], style:"renaissance",
  palette:["#b06a4a","#5e7250","#d9b27c","#2e3440","#e8dcc3"],
  tagline:"Perspective's big bang — dead at twenty-six, copied for centuries",
  works:[{t:"The Holy Trinity",y:"c. 1427"},{t:"The Tribute Money",y:"c. 1425"},{t:"The Expulsion from the Garden of Eden",y:"c. 1425"}],
  life:"Tommaso di Ser Giovanni earned the nickname Masaccio — 'clumsy Tom' — for caring about everything except appearances and accounts. In barely six working years in Florence and Pisa he rebuilt painting on Brunelleschi's perspective and Donatello's gravity, then died in Rome at twenty-six or twenty-seven — of plague, or, Vasari hints darkly, of poison.",
  career:"His Holy Trinity in Santa Maria Novella opens the church wall into the first rigorously constructed perspective space in Western art — Florentines queued, Vasari says, as if at a hole punched in the wall. In the Brancacci Chapel, his Adam and Eve stumble out of Eden howling, the first bodies in art that seem to weigh and grieve at once.",
  outside:"The Brancacci Chapel became Florence's free academy: Michelangelo, Leonardo and Raphael all sketched there as students — and it was while copying Masaccio that the sculptor Torrigiano broke young Michelangelo's nose for talking back.",
  facts:["The Trinity's skeleton below warns in Italian: 'I once was what you are; what I am, you also will be.'",
    "Restoration removed prudish fig-leaves added to his Adam and Eve in the 1680s — the despair was always nude.",
    "Brunelleschi reportedly mourned: 'We have suffered a great loss' — engineer to engineer."] },

{ id:"piero-della-francesca", name:"Piero della Francesca", years:"c. 1415–1492", born:1415, died:1492,
  nation:"italy", eras:["15th-century"], movements:["early-renaissance"],
  techniques:["fresco","tempera","oil-painting"], style:"renaissance",
  palette:["#9aacb8","#d9c8a4","#7a9a6e","#5e4a32","#ece4d2"],
  tagline:"Geometry at dawn — the mathematician whose silence outlasted empires",
  works:[{t:"The Resurrection",y:"c. 1463–65"},{t:"The Flagellation of Christ",y:"c. 1455–60"},{t:"The Legend of the True Cross",y:"c. 1452–66"}],
  life:"Born in the small Tuscan town of Borgo Sansepolcro, which he never really left in spirit, Piero divided his life between painting and mathematics — his treatises on perspective and the five regular solids circulated among scholars. Legend says he went blind in old age; he died on 12 October 1492, the day Columbus sighted land.",
  career:"His Resurrection — Christ stepping from the tomb over sleeping guards, half the landscape dead and half in leaf — was called 'the best picture in the world' in a famous Aldous Huxley essay. The Flagellation's three foreground gentlemen, serenely ignoring the scourging behind them, remain art history's favourite unsolved equation; the Arezzo fresco cycle stages the True Cross legend with the calm of celestial mechanics.",
  outside:"His mathematics was no hobby: Luca Pacioli built famous textbooks on Piero's treatises (with, scholars grumble, insufficient credit). During WWII, a British artillery officer — remembering Huxley's essay — reportedly held fire on Sansepolcro, sparing the Resurrection.",
  facts:["The town his Resurrection guards is named 'Holy Sepulchre' — the painting is its civic seal made flesh.",
    "Captain Tony Clarke's shell-holding restraint earned him a street name in Sansepolcro.",
    "He died on the day the Old World found the New — historians cannot resist the symbolism."] },

{ id:"marcel-duchamp", name:"Marcel Duchamp", years:"1887–1968", born:1887, died:1968,
  nation:"france", eras:["20th-century"], movements:["dada","cubism"],
  techniques:["oil-painting","mixed-media","collage"], style:"cubist",
  palette:["#8a7a5e","#5e5648","#b09a6e","#3e3a36","#d9d0bc"],
  tagline:"The man who signed a urinal — and changed the question forever",
  works:[{t:"Nude Descending a Staircase, No. 2",y:"1912"},{t:"Fountain",y:"1917"},{t:"The Bride Stripped Bare by Her Bachelors, Even (The Large Glass)",y:"1915–23"}],
  life:"Born into a Normandy family that produced four artists, Duchamp painted his way through Impressionism and Cubism by thirty — then largely stopped, preferring chess, puns and ideas. He played for France in international chess Olympiads, became a US citizen, and spent his last twenty years secretly building one final work revealed only after his death in 1968.",
  career:"Nude Descending a Staircase scandalised the 1913 Armory Show ('an explosion in a shingle factory'); four years later Fountain — a porcelain urinal signed 'R. Mutt' — asked whether choosing could be making, the question conceptual art has been answering ever since. The Large Glass occupied him for eight years and was finished, he ruled, when shippers cracked it: 'completed by chance.'",
  outside:"His female alter ego Rrose Sélavy (say it: 'Eros, c'est la vie') signed works and aphorisms; his first marriage ended swiftly after his bride, finding him studying chess problems on their honeymoon, glued his pieces to the board. Étant donnés, the posthumous peep-show diorama in Philadelphia, ambushed an art world convinced he had retired.",
  facts:["A 2004 poll of 500 art professionals voted Fountain the most influential artwork of the 20th century.",
    "The original Fountain was lost almost immediately — every museum copy is an authorised replica.",
    "He drew a moustache on a Mona Lisa postcard and titled it with a pun so rude the Louvre took 50 years to forgive it."] }
);
