/* PIGMENT — artists 8/13 : Renaissance reinforcements & the 17th century */
window.ARTISTS.push(
{ id:"sandro-botticelli", name:"Sandro Botticelli", years:"c. 1445–1510", born:1445, died:1510,
  nation:"italy", eras:["15th-century","16th-century"], movements:["early-renaissance"],
  techniques:["tempera","glazing"], style:"renaissance",
  palette:["#7da26e","#e8c4a8","#d9b46a","#3b5a8a","#f0e8d4"],
  tagline:"Venus on a shell — grace itself, then the bonfire",
  works:[{t:"The Birth of Venus",y:"c. 1485"},{t:"Primavera",y:"c. 1480"},{t:"The Mystical Nativity",y:"1500–01"}],
  life:"Alessandro Filipepi — 'Botticelli', little barrel, a nickname borrowed from his brother — spent nearly his whole life in one Florentine neighbourhood, working for the Medici at the centre of the city's golden age. He never married, quipping that the idea gave him nightmares, and died poor and lame at about sixty-five.",
  career:"The Birth of Venus and Primavera turned Neoplatonic philosophy into the most graceful figures ever painted — mythology given the tenderness of altarpieces. After the friar Savonarola's fire-and-brimstone revolution, his style darkened into the strange, urgent Mystical Nativity; out of fashion for 350 years, he was resurrected by the Victorians into universal fame.",
  outside:"Vasari says he prospered, wasted it all, and laughed constantly — a notorious workshop prankster. He illustrated Dante's Divine Comedy in nearly a hundred exquisite drawings, a project that consumed his later years and survives split between Berlin and the Vatican.",
  facts:["Some of his mythological paintings on canvas may have escaped the Bonfire of the Vanities — legend insists he threw works on it himself.",
    "He asked to be buried at the feet of Simonetta Vespucci, Florence's great beauty, in the Ognissanti church — and is.",
    "Venus's pose copies a classical 'Venus Pudica' statue the Medici owned."] },

{ id:"giorgione", name:"Giorgione", years:"c. 1477–1510", born:1477, died:1510,
  nation:"italy", eras:["16th-century"], movements:["venetian-school","high-renaissance"],
  techniques:["oil-painting","glazing","sfumato"], style:"renaissance",
  palette:["#5e7250","#b06a42","#2b3a52","#d9c49a","#e8dcc4"],
  tagline:"Half a dozen paintings, five centuries of mystery",
  works:[{t:"The Tempest",y:"c. 1508"},{t:"Sleeping Venus",y:"c. 1510"},{t:"The Three Philosophers",y:"c. 1505–09"}],
  life:"Of Giorgio da Castelfranco — 'Giorgione', big George — we know almost nothing certain: born in the Veneto, trained beside Titian under Bellini, famously handsome, a lute player beloved at Venetian gatherings. He died of plague around thirty-two, allegedly caught from a mistress he refused to abandon.",
  career:"Perhaps six paintings are securely his, and they changed everything: The Tempest — a soldier, a nursing woman, a lightning bolt, and no agreed meaning — may be Western art's first painting of pure mood. His Sleeping Venus, finished by Titian after his death, invented the reclining nude that runs from Titian's Urbino to Manet's Olympia.",
  outside:"Contemporaries describe him improvising songs as readily as paintings; Vasari credits him with painting directly in colour without drawings, scandalising Florentine theory. X-rays of The Tempest show he swapped a bathing woman for the soldier — composing, as Venice would, with paint itself.",
  facts:["The Tempest has accumulated dozens of published interpretations; none has stuck.",
    "Isabella d'Este tried to buy a Giorgione within months of his death — the cult began immediately.",
    "Attribution fights over 'Giorgione or young Titian?' still employ scholars full-time."] },

{ id:"matthias-grunewald", name:"Matthias Grünewald", years:"c. 1470–1528", born:1470, died:1528,
  nation:"germany", eras:["16th-century"], movements:["northern-renaissance"],
  techniques:["oil-painting","tempera","glazing"], style:"baroque",
  palette:["#1d1410","#8a2620","#d9852e","#5e7250","#e8d9b4"],
  tagline:"The Isenheim Altarpiece — agony and radiance for a plague hospital",
  works:[{t:"The Isenheim Altarpiece",y:"c. 1512–16"},{t:"The Mocking of Christ",y:"c. 1503–05"},{t:"Stuppach Madonna",y:"c. 1516–19"}],
  life:"His real name was probably Mathis Gothardt; 'Grünewald' was a biographer's error that stuck. A court painter and hydraulic engineer to two archbishops of Mainz, he apparently sympathised with the Peasants' Revolt, lost his post, and died in Halle selling soap and pigments, leaving Lutheran pamphlets in his trunk.",
  career:"For the Antonite hospital at Isenheim, which treated victims of ergot poisoning, he painted Christianity's most harrowing Crucifixion — Christ's skin studded with sores like the patients viewing it — which opens, wing by wing, into the most incandescent Resurrection in art. Barely ten paintings survive; each looks like no one else before Expressionism.",
  outside:"While Dürer built a print empire, Grünewald left almost no trace — no prints, few drawings, two documented signatures. The Expressionists canonised him as their ancestor, and Hindemith's opera Mathis der Maler dramatised his caught-between-powers life.",
  facts:["Isenheim's patients were brought before the altarpiece in hope of healing — art as literal medicine.",
    "The Resurrection's glowing Christ has been called painting's first 'light effect' worthy of science fiction.",
    "His true identity was only untangled from archives in the twentieth century."] },

{ id:"lucas-cranach", name:"Lucas Cranach the Elder", years:"1472–1553", born:1472, died:1553,
  nation:"germany", eras:["16th-century"], movements:["northern-renaissance"],
  techniques:["oil-painting","tempera","woodblock"], style:"renaissance",
  palette:["#2e4a3e","#a83a2a","#d9b46a","#1d2430","#e8dcc4"],
  tagline:"The Reformation's image machine — and Luther's best man",
  works:[{t:"Portrait of Martin Luther",y:"1529"},{t:"Adam and Eve",y:"1526"},{t:"The Judgment of Paris",y:"c. 1528"}],
  life:"Court painter to three Electors of Saxony in Wittenberg, Cranach was also the town's richest citizen: pharmacist, wine merchant, print publisher, thrice mayor. Witness at Martin Luther's wedding and godfather to his children, he followed his captive prince into exile at eighty and died at eighty-one.",
  career:"His workshop was a production line of genius: slinky Venuses in feathered hats, serpent-signed portraits of Luther by the dozen (the Reformation's official face), hunting scenes and altarpieces — over a thousand surviving works. Contemporaries called him 'celerrimus pictor', the fastest of painters; the brand mattered more than the hand, centuries before Warhol.",
  outside:"His pharmacy monopoly included sweet wine and printing licences; he published Luther's German Bible and pamphlets while painting Catholic commissions on the side — a businessman's ecumenism. Son Lucas the Younger continued the firm seamlessly.",
  facts:["He signed with a crowned winged serpent — a trademark his workshop kept after his death (lowering its wings in mourning).",
    "He painted Luther in secret as 'Junker Jörg' during the Wartburg hiding.",
    "Cranach's slender, sly nudes were a deliberate northern answer to Italy's classical bodies."] },

{ id:"correggio", name:"Correggio", years:"1489–1534", born:1489, died:1534,
  nation:"italy", eras:["16th-century"], movements:["high-renaissance","mannerism"],
  techniques:["fresco","oil-painting","sfumato"], style:"rococo",
  palette:["#9ec0d9","#e8c4a8","#d9a86e","#7a8ab0","#f0e8d8"],
  tagline:"Ceilings that open to heaven — the Baroque, a century early",
  works:[{t:"Assumption of the Virgin (Parma Cathedral)",y:"1526–30"},{t:"Jupiter and Io",y:"c. 1530"},{t:"Adoration of the Shepherds (The Night)",y:"c. 1529–30"}],
  life:"Antonio Allegri, called Correggio after his small hometown near Parma, lived a quiet provincial life that biographers found maddeningly undramatic — marriage, children, steady work — and died suddenly at about forty-five. The mystery is how, far from Rome and Venice, he invented effects nobody else imagined for a hundred years.",
  career:"His Parma Cathedral dome dissolves architecture into a vortex of ascending bodies — the first true 'ceiling of heaven', ancestor of every Baroque illusion. His Loves of Jupiter series painted desire with unprecedented softness: Io embraced by a god who is literally a cloud. Eighteenth-century collectors ranked him beside Raphael.",
  outside:"A cathedral canon famously dismissed the dome as a 'hash of frogs' legs'; Titian, passing through, reportedly answered that if the dome were turned upside down and filled with gold it would not equal its worth.",
  facts:["His sfumato out-melts Leonardo's — contemporaries swore his figures were painted with smoke.",
    "Jupiter and Io was once owned by a prudish duke who reportedly wanted the canvas destroyed; it survived him.",
    "The Rococo treated him as a patron saint — Boucher and Fragonard copied him devoutly."] },

{ id:"parmigianino", name:"Parmigianino", years:"1503–1540", born:1503, died:1540,
  nation:"italy", eras:["16th-century"], movements:["mannerism"],
  techniques:["oil-painting","etching","glazing"], style:"renaissance",
  palette:["#5e2430","#7b8fb0","#cfa44e","#2e4a3e","#e3d5b8"],
  tagline:"The swan-necked Madonna and a mirror full of tricks",
  works:[{t:"Madonna with the Long Neck",y:"1534–40"},{t:"Self-Portrait in a Convex Mirror",y:"c. 1524"},{t:"Cupid Making His Bow",y:"c. 1533–35"}],
  life:"Girolamo Mazzola of Parma — 'the little Parmesan' — was painting prodigiously by his teens and dazzled papal Rome at twenty-one with a self-portrait painted on a convex wooden ball, mimicking a mirror's distortion. He fled the 1527 Sack of Rome, grew obsessed with alchemy, neglected his commissions, was briefly jailed for breach of contract, and died at thirty-seven.",
  career:"His Madonna with the Long Neck stretches grace past anatomy — a neck like a swan's, an infant sliding from the lap, a prophet the size of a toy — Mannerism's elegant manifesto. Among the first Italians to make original etchings, he spread his sinuous line across Europe through prints; Vasari mourned him as Raphael's spirit gone strange.",
  outside:"Vasari blamed alchemy for his decline: beard wild, nails long, furnaces where easels should be — art history's first portrait of the artist as obsessive dropout. The unfinished Long Neck was inscribed by admirers as perfect precisely because incomplete.",
  facts:["His convex self-portrait inspired a major John Ashbery poem four centuries later.",
    "He reportedly painted his self-portrait on a specially turned half-sphere of poplar to match a barber's mirror.",
    "The Long Neck includes a single, famously unexplained column supporting nothing."] },

{ id:"bronzino", name:"Agnolo Bronzino", years:"1503–1572", born:1503, died:1572,
  nation:"italy", eras:["16th-century"], movements:["mannerism"],
  techniques:["oil-painting","fresco","glazing"], style:"renaissance",
  palette:["#1d2430","#7a1f2b","#caa45c","#2e6e5e","#e8dcc8"],
  tagline:"Porcelain courtiers — the Medici frozen in perfect enamel",
  works:[{t:"Portrait of Eleonora di Toledo with Her Son",y:"c. 1545"},{t:"An Allegory with Venus and Cupid",y:"c. 1545"},{t:"Portrait of a Young Man with a Book",y:"c. 1530s"}],
  life:"A butcher's son from outside Florence, Bronzino was the devoted pupil — effectively adopted son — of the painter Pontormo, whose diary records their decades of shared meals. As court painter to Duke Cosimo I de' Medici he became Florence's defining image-maker, a founding member of its art academy, and a celebrated burlesque poet.",
  career:"His Medici portraits are marvels of glacial perfection: Eleonora di Toledo's brocade gown painted thread by thread, faces like lacquered masks of power. The London Allegory — Venus, Cupid, Folly and a honey-offering monster with reversed hands — remains Mannerism's most debated puzzle picture, equal parts eros and warning.",
  outside:"His comic poems celebrated, among other things, paintbrushes and onions, with double meanings his courtly sitters pretended not to notice. He tended the aging, increasingly eccentric Pontormo to the end, finishing his frescoes after his death.",
  facts:["Eleonora's gown was so famous that legend long claimed she was buried in it (she wasn't — scholars checked).",
    "The Allegory was likely a diplomatic gift for the king of France — moral riddle as luxury export.",
    "Florence's academy sent him to organise Michelangelo's funeral — the establishment honouring its own."] },

{ id:"lavinia-fontana", name:"Lavinia Fontana", years:"1552–1614", born:1552, died:1614,
  nation:"italy", eras:["16th-century","17th-century"], movements:["mannerism"],
  techniques:["oil-painting","glazing"], style:"renaissance",
  palette:["#3a2a2e","#8a4a3e","#caa481","#1d2430","#e9dccb"],
  tagline:"Bologna's professional — the first woman to run the full game",
  works:[{t:"Self-Portrait at the Clavichord",y:"1577"},{t:"Portrait of the Gozzadini Family",y:"1584"},{t:"Minerva Dressing",y:"1613"}],
  life:"Daughter of a Bolognese painter, Lavinia Fontana turned her father's modest workshop into her own thriving practice — the first woman in Europe to build a full professional career as a painter, with public commissions, papal patrons and market-rate prices. She bore eleven children while doing it; her husband managed the studio and minded the family.",
  career:"Bologna's noblewomen queued for her portraits, trusting her with their jewels and their faces alike; her fame carried her to Rome under Pope Paul V. She painted large public altarpieces — territory previously closed to women — and late in life the Minerva Dressing, among the first female nudes painted by a woman.",
  outside:"Her marriage contract effectively made her the breadwinner — her husband Gian Paolo Zappi accepted a dowry of her future earnings, a stunning role reversal for 1577. She was elected to Rome's Accademia di San Luca, and a medal was struck with her portrait.",
  facts:["Over 100 documented works — the largest surviving output of any woman artist before 1700.",
    "She painted Antonietta Gonzalez, a girl with hypertrichosis ('the hairy child'), with remarkable dignity.",
    "Her self-portrait at the clavichord advertised every accomplishment a court could want in one image."] },

{ id:"nicholas-hilliard", name:"Nicholas Hilliard", years:"c. 1547–1619", born:1547, died:1619,
  nation:"britain", eras:["16th-century","17th-century"], movements:["northern-renaissance"],
  techniques:["miniature-painting","watercolor","gold-leaf"], style:"ornament",
  palette:["#1d3a5f","#a83a4e","#caa43e","#2e6e5e","#e8e0d0"],
  tagline:"Elizabeth I in your pocket — portraits the size of a kiss",
  works:[{t:"Young Man Among Roses",y:"c. 1587"},{t:"Portrait of Queen Elizabeth I",y:"c. 1572"},{t:"Self-Portrait Aged 30",y:"1577"}],
  life:"An Exeter goldsmith's son, Hilliard trained in jewellery before becoming limner — miniature painter — to Queen Elizabeth I, capturing her image for lockets, rings and diplomatic gifts for four decades. Perpetually short of money despite royal favour, he was briefly imprisoned for debt in his last years, and died in London at about seventy-two.",
  career:"His watercolour-on-vellum miniatures, often no bigger than a playing card, fixed the Elizabethan age's intimate face: ruffs like spun sugar, lovesick young men among symbolic roses, jewels rendered with a goldsmith's truth. His treatise The Arte of Limning insists on painting 'without shadows' in clean light — portraiture as jewel, not window.",
  outside:"Miniatures were worn against the body, exchanged as tokens of love and loyalty — Hilliard's work lived in court intrigue, hidden in cabinets and bodices. He also engraved Great Seals of the realm and designed the queen's second Great Seal.",
  facts:["Elizabeth reportedly chose to sit for him in open sunlight to avoid any shadow on her face — politics as lighting design.",
    "The Young Man Among Roses is widely read as the Earl of Essex, lovesick for the Queen.",
    "He used real powdered gold and burnished silver in the jewels — goldsmithing by brush."] },

{ id:"annibale-carracci", name:"Annibale Carracci", years:"1560–1609", born:1560, died:1609,
  nation:"italy", eras:["16th-century","17th-century"], movements:["baroque"],
  techniques:["fresco","oil-painting","chiaroscuro"], style:"baroque",
  palette:["#3b5a8a","#b0703a","#d9c49a","#2e4a3e","#e8dcc4"],
  tagline:"The other road to the Baroque — Caravaggio's great rival, by daylight",
  works:[{t:"The Farnese Gallery ceiling",y:"1597–1608"},{t:"The Beaneater",y:"c. 1583"},{t:"Domine, Quo Vadis?",y:"1601–02"}],
  life:"With his brother Agostino and cousin Ludovico, Annibale ran Bologna's revolutionary teaching academy — drawing from life, studying nature against Mannerist artifice. Summoned to Rome by Cardinal Farnese, he spent a decade on the palace ceiling, was paid an insulting pittance, sank into depression, and died at forty-nine — buried, at his wish, near Raphael in the Pantheon.",
  career:"While Caravaggio plunged painting into shadow, Carracci rebuilt it in daylight: the Farnese Gallery's Loves of the Gods fused Michelangelo's bodies, Titian's colour and sheer wit into the ceiling every Baroque decorator studied. His early Beaneater — a peasant mid-mouthful, beans glistening — is genre painting's blunt, brilliant manifesto.",
  outside:"The Carracci academy's life-drawing sessions and caricature games (Annibale is credited with inventing the caricature) trained a generation — Reni, Domenichino, Guercino. Roman gossip pitted him against Caravaggio; he reportedly admired the rival he was supposed to despise.",
  facts:["His fee for eight years of the Farnese ceiling was famously delivered as a dish of coins — roughly 500 scudi.",
    "Art history's 'caricatura' begins in Carracci workshop drawing games.",
    "Poussin said Rome held three great sights: ancient sculpture, Raphael, and the Farnese Gallery."] },

{ id:"guido-reni", name:"Guido Reni", years:"1575–1642", born:1575, died:1642,
  nation:"italy", eras:["17th-century"], movements:["baroque"],
  techniques:["oil-painting","fresco","glazing"], style:"baroque",
  palette:["#9ec0d9","#d9b46a","#8a2634","#e8e0d0","#3e4a6e"],
  tagline:"'Divine Guido' — heavenly grace, gambled away nightly",
  works:[{t:"Aurora",y:"1614"},{t:"Saint Michael Archangel",y:"c. 1636"},{t:"Atalanta and Hippomenes",y:"c. 1620–25"}],
  life:"A Bolognese musician's son trained in the Carracci academy, Reni became Italy's most celebrated painter — courted by popes, nicknamed 'the divine'. Behind the silk: a compulsive gambler who lost fortunes at cards and dice, painting ever faster potboilers to cover debts, dying in 1642 owing money across Bologna.",
  career:"His Aurora ceiling — dawn's chariot streaming across gold — was engraved into every European print shop; his upturned-eyed saints defined sacred beauty for two centuries until Victorian critics gagged on the sweetness. At his best (Atalanta's crossing diagonals, Michael's cool triumph) the elegance is steel, not sugar.",
  outside:"Terrified of witchcraft and poison, devoted to his mother, he reportedly trembled around women yet painted the era's most graceful ones. His late, near-monochrome 'unfinished' canvases — debts paid in silver paint — now look startlingly modern.",
  facts:["At his peak he charged by the figure — and kept a price list like a tailor.",
    "Goethe and Stendhal swooned over him; Ruskin's generation demoted him to kitsch; the pendulum is swinging back.",
    "His Saint Michael's Satan was rumoured to wear the face of a cardinal who'd crossed him."] },

{ id:"francisco-de-zurbaran", name:"Francisco de Zurbarán", years:"1598–1664", born:1598, died:1664,
  nation:"spain", eras:["17th-century"], movements:["baroque"],
  techniques:["oil-painting","tenebrism","chiaroscuro"], style:"baroque",
  palette:["#1d1a16","#8a8276","#d9c49a","#5e2a2a","#e8e0d0"],
  tagline:"Monks and lemons in God's spotlight",
  works:[{t:"Still Life with Lemons, Oranges and a Rose",y:"1633"},{t:"Saint Serapion",y:"1628"},{t:"Saint Francis in Meditation",y:"c. 1635–39"}],
  life:"From Extremadura, Zurbarán became Seville's painter of the cloister: monastery cycles for Dominicans, Mercedarians, Carthusians — white habits against darkness. Felled by changing taste as Murillo's softness conquered Seville, he moved to Madrid late in life seeking work, and died there in modest circumstances at sixty-five.",
  career:"He painted fabric the way mystics pray: the hanging weight of Saint Serapion's robes is as devotional as the martyr's face. His lone signed still life — four objects on a ledge, lemons like planets — achieves with citrus what others needed crucifixions for. Exported by the shipload to Spanish America, his monks colonised two continents' imaginations.",
  outside:"He ran an efficient family workshop with serial production for the colonial market — sets of Roman emperors, founders of orders, painted partly by assistants and shipped to Lima and Buenos Aires. Manet's generation rediscovered him; modern abstractionists claim his geometry.",
  facts:["Saint Serapion hung in a monastery room where deceased monks lay — a painting meant to console the dead's companions.",
    "His habit-whites are built from greys, ochres and blues — almost no pure white.",
    "Three of his children died in Seville's 1649 plague, which also gutted his patron monasteries."] },

{ id:"bartolome-murillo", name:"Bartolomé Esteban Murillo", years:"1617–1682", born:1617, died:1682,
  nation:"spain", eras:["17th-century"], movements:["baroque"],
  techniques:["oil-painting","glazing","alla-prima"], style:"baroque",
  palette:["#8a6e4a","#d9b894","#5e7a9e","#e8dcc4","#3a2e22"],
  tagline:"Street urchins and floating Madonnas — Seville's gentle Baroque",
  works:[{t:"The Immaculate Conception of Los Venerables",y:"c. 1678"},{t:"Boys Eating Grapes and Melon",y:"c. 1645–46"},{t:"The Young Beggar",y:"c. 1645"}],
  life:"Orphaned at ten, youngest of fourteen children of a Seville barber-surgeon, Murillo rose to become the city's most beloved painter and a founder of its drawing academy. He died at sixty-four after falling from scaffolding while painting an altarpiece in Cádiz — working to the literal end.",
  career:"His Immaculate Conceptions — the Virgin on a crescent moon in spirals of cherubim — became Catholicism's default vision of the doctrine. Equally tender with the unholy, he painted Seville's street boys eating fruit and playing dice with a warmth that founded a whole genre. For 150 years he ranked among the most expensive painters on earth.",
  outside:"Napoleon's marshal Soult looted Seville's Murillos by the dozen, scattering them through Europe's museums — the thefts ironically cementing his international fame before the backlash ('too sweet') of the modern era.",
  facts:["The Young Beggar was the first Spanish painting bought by the Louvre.",
    "His childhood neighbourhood gate, the Puerta de la Carne, appears smuggled into several backgrounds.",
    "Nineteenth-century copies of his urchins hung in countless European parlours — sentimental piracy at scale."] },

{ id:"claude-lorrain", name:"Claude Lorrain", years:"c. 1604–1682", born:1604, died:1682,
  nation:"france", eras:["17th-century"], movements:["baroque"],
  techniques:["oil-painting","glazing","etching"], style:"romantic",
  palette:["#f2d9a0","#a8c4d9","#5e7250","#b06a42","#f4ecd8"],
  tagline:"The man who taught Europe what sunset means",
  works:[{t:"Seaport with the Embarkation of the Queen of Sheba",y:"1648"},{t:"Landscape with Aeneas at Delos",y:"1672"},{t:"The Enchanted Castle",y:"1664"}],
  life:"Born Claude Gellée in Lorraine, orphaned young, he reached Rome reportedly as a pastry cook and stayed for life, drawing in the Campagna at dawn and dusk. Unmarried, semi-literate, wholly devoted to light, he became Europe's most sought-after landscapist and died in Rome at about seventy-eight.",
  career:"Claude invented the ideal landscape as theatre of light: harbours dissolving into golden haze, classical ruins framing the sun itself — the first painter to stare it down on canvas. English milords bought him by the gallery wall; for two centuries gardeners landscaped estates, and tourists viewed scenery, through his eyes.",
  outside:"Plagued by forgers, he kept the Liber Veritatis — a notebook of drawings recording every authentic painting, nearly 200 sheets now in the British Museum: art history's first catalogue raisonné, made in self-defence. The tinted 'Claude glass' tourists used to view landscapes bears his name.",
  facts:["Turner's will demanded his paintings hang beside Claude's in London's National Gallery forever — they still do.",
    "Keats wrote 'Ode to a Nightingale' imagery under the spell of The Enchanted Castle.",
    "He sold light, not stories: patrons chose the myth, Claude chose the hour."] },

{ id:"judith-leyster", name:"Judith Leyster", years:"1609–1660", born:1609, died:1660,
  nation:"netherlands", eras:["17th-century"], movements:["dutch-golden-age","baroque"],
  techniques:["oil-painting","alla-prima"], style:"impressionist",
  palette:["#23201c","#caa45c","#8a4a3e","#5e7a8e","#e8e0d0"],
  tagline:"The leading star of Haarlem — erased, then found by a monogram",
  works:[{t:"Self-Portrait",y:"c. 1630"},{t:"The Proposition",y:"1631"},{t:"The Concert",y:"c. 1633"}],
  life:"A Haarlem brewer's daughter (the brewery was called the Leister — 'lodestar'), Leyster was among the first women admitted to the painters' Guild of St Luke with her own workshop and apprentices. She married painter Jan Miense Molenaer, largely set down her brush for family and business, and died at fifty.",
  career:"Her laughing musicians and candlelit scenes sparkle with Hals-like speed — she sued Hals, in fact, for poaching an apprentice, and won costs. The Proposition, a man offering coins to a sewing woman who simply ignores him, reads today as a quietly radical reversal of a leering genre. After her death she vanished: her works sold under men's names for 230 years.",
  outside:"In 1893 the Louvre discovered her JL★ monogram under a fake Hals signature on a prized 'Hals' — the lawsuit that followed began her resurrection, and a re-examination of how many women the canon had simply filed under men.",
  facts:["Her monogram puns on her name: J, L and a shooting star — the 'leidstar'.",
    "Her confident self-portrait, brush mid-air, was long catalogued as a Hals too.",
    "Fewer than 35 works are currently attributed to her — numbers still climbing as labels are corrected."] },

{ id:"jan-steen", name:"Jan Steen", years:"c. 1626–1679", born:1626, died:1679,
  nation:"netherlands", eras:["17th-century"], movements:["dutch-golden-age","baroque"],
  techniques:["oil-painting","alla-prima","glazing"], style:"baroque",
  palette:["#8a5e3a","#c4763e","#5e7a8e","#e8d9b4","#2e2a22"],
  tagline:"'A Jan Steen household' — chaos, painted with love",
  works:[{t:"The Feast of Saint Nicholas",y:"c. 1665–68"},{t:"Beware of Luxury",y:"1663"},{t:"The Merry Family",y:"1668"}],
  life:"Born in Leiden to a family of brewers, Steen ran taverns and a brewery alongside painting — research, one suspects. He moved restlessly between Dutch towns, fathered at least eight children, weathered bankruptcy years, and died in Leiden at about fifty-three, leaving some 350 paintings.",
  career:"His crowded households — children smoking, dogs on the table, grandmothers cackling, the moral unravelling in real time — made his name a Dutch proverb for happy domestic chaos. But the disorder is choreography: every spilled jug and side-glance argues a proverb, and his self-portrait often grins from the middle of the mess, implicating everyone.",
  outside:"He painted himself as lute-playing wastrel, drunken reveller and grinning corrupter of youth — art history's most cheerful self-incrimination, almost certainly a persona: the bankruptcies were real, but so was a disciplined, hugely productive studio.",
  facts:["'Een huishouden van Jan Steen' is still everyday Dutch for a gloriously messy home.",
    "The Feast of Saint Nicholas hides the whole drama of gift-day — including the boy who got the birch rod.",
    "He layered proverbs like Easter eggs; Dutch schoolchildren still decode them."] }
);
