/* PIGMENT artists — part 16 (atlas widening: Utamaro, Ensor, Hodler, Church) */
window.ARTISTS = (window.ARTISTS || []).concat([

{ id:"kitagawa-utamaro", name:"Kitagawa Utamaro", years:"c. 1753–1806", born:1753, died:1806,
  nation:"japan", eras:["18th-century","19th-century"], movements:["ukiyo-e"],
  techniques:["woodblock"], style:"ukiyoe",
  palette:["#c9b8a0","#8a3a3e","#1d1c22","#e8d9c0","#5e6e8a"],
  tagline:"The floating world's great portraitist of women",
  works:[{t:"Three Beauties of the Present Day",y:"c. 1793"},{t:"Ten Studies in Female Physiognomy",y:"c. 1792–93"},{t:"Woman Playing a Poppin",y:"c. 1790"},{t:"Flowers of Edo: Young Woman with Samisen",y:"c. 1800"}],
  life:"Almost nothing is certain about his origins — birthplace disputed, family unknown — until he surfaces in Edo as a pupil of Toriyama Sekien and, decisively, as the house artist of the brilliant publisher Tsutaya Jūzaburō, above whose shop he lived. In 1804 the shogunate punished him with fifty days in manacles over prints depicting the warlord Hideyoshi's private life; by most accounts the humiliation broke him. He died two years later.",
  career:"Utamaro turned the courtesans, waitresses and teahouse beauties of Edo into the most refined portraiture of the floating world — inventing the ōkubi-e 'large head' close-up, setting faces against shimmering mica grounds, and finding individual psychology inside an idealized type. His nature studies (the exquisite insect and shell picture-books) show the same precision aimed at moths and grasshoppers.",
  outside:"He was, by the standards of ukiyo-e artists, a celebrity — his name traded on by imitators so aggressively that publishers stamped 'the genuine Utamaro' on prints. He reportedly lived inside the pleasure quarters he depicted, less an observer than a resident.",
  facts:["The 1804 manacling — fifty days in handcuffs for prints about Hideyoshi — is one of art history's starkest censorship cases.",
    "His ōkubi-e 'large head' portraits were the close-up centuries before cinema claimed the idea.",
    "Edmond de Goncourt's 1891 monograph made him Japonisme's favorite painter; Cassatt's color prints answer him directly.",
    "Mica dust mixed into the background ink makes his best prints literally shimmer in raking light."] },

{ id:"james-ensor", name:"James Ensor", years:"1860–1949", born:1860, died:1949,
  nation:"belgium", eras:["19th-century","20th-century"], movements:["expressionism","symbolism"],
  techniques:["oil-painting","etching"], style:"expressionist",
  palette:["#e8dcc8","#c23a3a","#3e7a8a","#e8b43a","#4a3a4e"],
  tagline:"Masks, skeletons, and Christ stuck in traffic",
  works:[{t:"Christ's Entry into Brussels in 1889",y:"1888"},{t:"The Intrigue",y:"1890"},{t:"Skeletons Fighting over a Pickled Herring",y:"1891"},{t:"Self-Portrait with Masks",y:"1899"}],
  life:"Born in Ostend above his family's souvenir shop — carnival masks, seashells, chinoiserie — and he essentially never left: eighty-nine years in one seaside town, most of them in rooms above the masks that colonized his art. His English father drank himself to an early death; his formidable mother and aunt ran the shop and, in their way, the painter.",
  career:"He co-founded the Brussels avant-garde group Les XX — which then rejected his masterpiece: Christ's Entry into Brussels in 1889, a four-metre carnival mob swallowing a tiny Christ, stayed rolled in his attic studio for decades. His masks, skeletons and jeering crowds anticipated Expressionism by a generation; when fame finally arrived he was made a baron by the Belgian king, long after the radical years were over.",
  outside:"He played the harmonium daily and composed a ballet, La Gamme d'Amour; visitors to the old baron found him performing it among the masks. He painted little of consequence in his last three decades and enjoyed the irony immensely.",
  facts:["Christ's Entry into Brussels in 1889 hung in his own studio for around forty years before the world caught up; it now anchors the Getty.",
    "His own avant-garde group, Les XX, voted to reject the painting — and nearly expelled its maker.",
    "The family shop's carnival masks became his life's cast: he painted crowds as masks and masks as crowds.",
    "Ennobled as a baron in 1929 — the anarchist of Ostend ended as official national treasure."] },

{ id:"ferdinand-hodler", name:"Ferdinand Hodler", years:"1853–1918", born:1853, died:1918,
  nation:"switzerland", eras:["19th-century","20th-century"], movements:["symbolism","art-nouveau"],
  techniques:["oil-painting","flat-color"], style:"ornament",
  palette:["#7da8c9","#dce8f0","#8a9a5e","#c9a45c","#3e4a5e"],
  tagline:"Parallel lives, painted in rhythm",
  works:[{t:"Night",y:"1889–90"},{t:"The Chosen One",y:"1893–94"},{t:"Lake Thun with Symmetric Reflection",y:"1905"},{t:"The Woodcutter",y:"1910"}],
  life:"Born into Bern poverty, he buried his entire family — father, mother, all five siblings — mostly to tuberculosis before he reached middle age: 'there was always a corpse in the house,' he said, and death walked through his art accordingly. Apprenticed to a painter of tourist views, he walked to Geneva at eighteen and stayed.",
  career:"He called his method Parallelism: figures repeated in rhythmic symmetry like a ritual frieze, mountains doubled in mirror-still lakes — order as a spiritual argument. Night, with its black-shrouded figure of death crouched on a sleeper, was banned from Geneva's 1891 salon by the mayor and promptly celebrated in Paris. The 1904 Vienna Secession retrospective made him a European force; Klimt's generation took notes.",
  outside:"Between 1914 and 1915 he recorded his dying companion Valentine Godé-Darel in a series of unflinching canvases — from illness to deathbed to the empty horizon of Lake Geneva — perhaps the most harrowing sustained document of dying in Western painting. He followed her three years later, painting the lake to the end.",
  facts:["Night was banned by Geneva's mayor as obscene, then triumphed in Paris with Puvis de Chavannes leading the applause.",
    "His paintings appeared on Swiss banknotes — the woodcutter and the mower swung their tools on the 50- and 100-franc notes for decades.",
    "The Valentine Godé-Darel cycle tracks a single human death across dozens of canvases; museums still hang it with warnings.",
    "He painted the lakes of Geneva and Thun over a hundred times, flattening them toward pure horizontal abstraction."] },

{ id:"frederic-edwin-church", name:"Frederic Edwin Church", years:"1826–1900", born:1826, died:1900,
  nation:"usa", eras:["19th-century"], movements:["hudson-river-school","romanticism"],
  techniques:["oil-painting","glazing"], style:"romantic",
  palette:["#e8944a","#7da8c9","#3e5e40","#d9c9a0","#5e3a2a"],
  tagline:"The showman of the sublime",
  works:[{t:"Niagara",y:"1857"},{t:"The Heart of the Andes",y:"1859"},{t:"The Icebergs",y:"1861"},{t:"Cotopaxi",y:"1862"},{t:"Aurora Borealis",y:"1865"}],
  life:"Hartford money bought him the only apprenticeship Thomas Cole ever granted, and Alexander von Humboldt's 'Cosmos' gave him a mission: paint the whole planet as connected spectacle. He chased it in person — twice up the Andes, north to iceberg waters off Newfoundland, later to Petra and Jerusalem — until rheumatism crippled his painting arm in his fifties.",
  career:"Church invented the blockbuster: single paintings toured like operas, one canvas alone in a darkened room, tickets twenty-five cents, opera glasses recommended. Twelve thousand New Yorkers queued for The Heart of the Andes in three weeks, and its $10,000 sale set an American record. Niagara did for a waterfall what national anthems do for countries; Cotopaxi staged a volcano as apocalypse with the Civil War burning offstage.",
  outside:"When his hand failed he composed with landscape itself: Olana, the Persian-fantasy house he designed above the Hudson, arranges its windows and carriage roads like framed canvases. It survives intact — furniture, paint pots, views — as one of America's great artist-made places.",
  facts:["The Heart of the Andes was exhibited with a frame built like a window and viewers were encouraged to scan it through opera glasses.",
    "The Icebergs disappeared after an 1863 English sale and was rediscovered in 1979 hanging in a Manchester boys' school stairwell — it now anchors the Dallas Museum of Art.",
    "Mark Twain wrote pages trying to describe his Niagara and gave up, delighted.",
    "He was Thomas Cole's only pupil — the Hudson River School's founder taught exactly one successor, and chose well."] }
]);
