/* PIGMENT — artists 15/15 : Russia's icons & avant-garde, Asia's ink and gold */
window.ARTISTS.push(
{ id:"andrei-rublev", name:"Andrei Rublev", years:"c. 1360s–1428", born:1365, died:1428,
  nation:"russia", eras:["14th-century","15th-century"], movements:["icon-painting"],
  techniques:["tempera","gold-leaf","fresco"], style:"ornament",
  palette:["#caa43e","#8a2620","#2e4a6e","#3e3a30","#e8d9b4"],
  tagline:"The Trinity — three angels, one cup, a millennium of prayer distilled",
  works:[{t:"The Trinity",y:"c. 1411 or 1425–27"},{t:"Dormition Cathedral frescoes, Vladimir",y:"1408"},{t:"The Saviour (Zvenigorod)",y:"c. 1410"}],
  life:"Of the monk Andrei Rublev history keeps a handful of chronicle lines: he worked beside Theophanes the Greek on Moscow's Annunciation Cathedral in 1405, frescoed Vladimir's Dormition Cathedral in 1408, and died at the Andronikov Monastery around 1428. The silence around the life only deepened the legend around the work.",
  career:"His Trinity icon — Abraham's three angelic visitors seated about a single chalice, painted in tones critics compare to 'colour heard as music' — became the standard against which all Orthodox icon painting is measured. Where Byzantine severity reigned, Rublev introduced an unprecedented tenderness: inclined heads, conversation conducted in silence, theology as gentleness.",
  outside:"Russia canonised him as a saint in 1988 — art history's only canonical painter who is also literally canonical. Andrei Tarkovsky's 1966 film Andrei Rublev, framing the icon painter against a brutal century, became one of cinema's monuments and carried his name worldwide.",
  facts:["The Church declared the Trinity the model for all icons at the Stoglav Council of 1551.",
    "Icon painters say icons are 'written', not painted — image as scripture.",
    "The Trinity's 2023 transfer from the Tretyakov Gallery to church custody set off an international conservation controversy."] },

{ id:"karl-bryullov", name:"Karl Bryullov", years:"1799–1852", born:1799, died:1852,
  nation:"russia", eras:["19th-century"], movements:["romanticism","neoclassicism"],
  techniques:["oil-painting","watercolor","glazing"], style:"romantic",
  palette:["#8a2620","#e8a85e","#2e3440","#d9b46a","#1d1410"],
  tagline:"The Last Day of Pompeii — Russia's first international sensation",
  works:[{t:"The Last Day of Pompeii",y:"1830–33"},{t:"The Rider",y:"1832"},{t:"Self-Portrait",y:"1848"}],
  life:"Born into a Petersburg family of artists of Huguenot descent, Bryullov spent his glory years in Italy, where Vesuvius gave him his subject and Europe gave him fame no Russian painter had known. He taught at the Petersburg Academy he privately scorned, escaped back south for his health, and died near Rome at fifty-two.",
  career:"The Last Day of Pompeii — lightning, collapsing statues, citizens shielding children under a volcanic sky — toured Europe to delirium: Walter Scott reportedly sat before it for an hour and called it an epic. Pushkin versified it; Gogol declared it Russian art's resurrection. His society portraits, all velvet flash and Italian light, made 'the great Karl' the empire's first celebrity painter.",
  outside:"He joined the campaign that bought the Ukrainian serf-poet Taras Shevchenko's freedom — his portrait of the poet Zhukovsky was raffled in 1838 to raise the 2,500 rubles. Pompeii's crowd includes his own self-portrait, paintbox on head.",
  facts:["The Last Day of Pompeii was arguably the first Russian painting to become a European event.",
    "Shevchenko later studied under Bryullov at the Academy — freed by a raffle, trained by the raffler.",
    "Bulwer-Lytton's novel The Last Days of Pompeii appeared a year after the painting — the canvas helped launch a craze."] },

{ id:"ivan-shishkin", name:"Ivan Shishkin", years:"1832–1898", born:1832, died:1898,
  nation:"russia", eras:["19th-century"], movements:["peredvizhniki","realism"],
  techniques:["oil-painting","etching"], style:"tonal",
  palette:["#2e4a2e","#5e7250","#a8b09a","#8a6e46","#e8e3d0"],
  tagline:"Tsar of the forest — pines counted needle by needle",
  works:[{t:"Morning in a Pine Forest",y:"1889"},{t:"Rye",y:"1878"},{t:"In the Wild North",y:"1891"}],
  life:"A merchant's son from Yelabuga on the Kama river, Shishkin studied in Moscow, Petersburg and Düsseldorf before co-founding the Peredvizhniki, the realist Wanderers. Twice widowed, he buried two wives and two sons and answered grief with work — he died at his easel in 1898, brush in hand, before an unfinished forest.",
  career:"Nobody painted Russian woodland with such botanical conviction: ferns, lichens and bark rendered so exactly that foresters could classify the trees. Rye — a country road through head-high grain beneath pines — became an image of Russia itself; Morning in a Pine Forest, with its tumbling bear cubs, became the most reproduced painting in the country.",
  outside:"The famous bears were actually painted by his friend Konstantin Savitsky; the collector Pavel Tretyakov wiped Savitsky's signature off, and Russia has argued about the credit ever since. The painting's afterlife is sweet in every sense — it wraps the beloved 'Clumsy Bear' chocolates to this day.",
  facts:["Generations of Russians know Morning in a Pine Forest primarily as a candy wrapper.",
    "Colleagues nicknamed him 'the bookkeeper of leaves' — he took it as praise.",
    "He died mid-brushstroke at 66, working on a canvas titled Forest Kingdom."] },

{ id:"isaac-levitan", name:"Isaac Levitan", years:"1860–1900", born:1860, died:1900,
  nation:"russia", eras:["19th-century"], movements:["peredvizhniki","realism"],
  techniques:["oil-painting","pastel"], style:"tonal",
  palette:["#5e7a8e","#caa45c","#8a6e46","#3e4a3e","#e8e0c8"],
  tagline:"The mood landscape — Russia's melancholy, painted at dusk",
  works:[{t:"Above Eternal Peace",y:"1894"},{t:"Golden Autumn",y:"1895"},{t:"The Vladimirka Road",y:"1892"}],
  life:"Born poor and Jewish in a Lithuanian shtetl, Levitan was twice expelled from Moscow during anti-Jewish edicts even as the city celebrated him. Chekhov was his closest friend — they quarrelled for years over a story that borrowed his love affairs, and reconciled. Heart disease killed him at thirty-nine, forty canvases unfinished in the studio.",
  career:"He invented what Russians call the 'mood landscape': nothing happens — a river bend, a darkening sky, the road convicts walked to Siberia — and everything is felt. Above Eternal Peace, a tiny church on a bluff under an enormous cold sky, may be the loneliest painting in Russian art; Golden Autumn its one blaze of consolation.",
  outside:"He taught landscape at the Moscow School in his final years, telling students to paint 'not a birch but the song of the birch.' Chekhov's story 'The Grasshopper' lifted his romantic entanglements so transparently that the friendship broke for three years; readers of both men keep finding each in the other's work.",
  facts:["The Vladimirka is the road to Siberian exile — a landscape that doubled as a political statement, painted empty.",
    "He completed about a thousand paintings in a twenty-year career despite chronic illness.",
    "Chekhov: 'Levitan's landscapes need no people — God walks through them unseen.'"] },

{ id:"mikhail-vrubel", name:"Mikhail Vrubel", years:"1856–1910", born:1856, died:1910,
  nation:"russia", eras:["19th-century","20th-century"], movements:["symbolism","art-nouveau"],
  techniques:["oil-painting","watercolor","mixed-media"], style:"cubist",
  palette:["#5e3450","#2e4a6e","#caa43e","#8a3a4e","#1d1c22"],
  tagline:"The Demon in crystal — facets a generation before Cubism",
  works:[{t:"The Demon Seated",y:"1890"},{t:"The Demon Downcast",y:"1902"},{t:"The Swan Princess",y:"1900"}],
  life:"Omsk-born, classically trained, Vrubel restored Byzantine frescoes in Kyiv before Moscow's merchant-patrons adopted him. His lifelong subject was Lermontov's Demon — neither devil nor man, 'the spirit of doubt' — painted, repainted and finally pursued into a psychiatric clinic, where he died in 1910, blind, after years of illness.",
  career:"He built form from crystalline facets — wings like shattered amethyst, faces assembled from prisms — a private geometry that anticipates Cubism by fifteen years and earned only mockery at first. The Demon Seated glows like stained glass ground into paint; his majolica fireplaces and panels for Mamontov's circle carried Russian Art Nouveau to its strangest heights.",
  outside:"He married the soprano Nadezhda Zabela and designed her stage costumes; his Swan Princess is her, mid-transformation. During the 1902 exhibition of The Demon Downcast he came daily, brush in hand, repainting the face while visitors watched — illness and perfectionism indistinguishable.",
  facts:["He repainted the Demon's face up to forty times — sometimes after the canvas was already hung.",
    "His decorative panels were rejected by the 1896 Nizhny Novgorod fair jury; the patron Mamontov built a pavilion for them next door.",
    "Picasso's generation in Moscow collections grew up on Vrubel — the facets travelled west."] },

{ id:"zinaida-serebriakova", name:"Zinaida Serebriakova", years:"1884–1967", born:1884, died:1967,
  nation:"russia", eras:["20th-century"], movements:["realism","impressionism"],
  techniques:["oil-painting","pastel","tempera"], style:"impressionist",
  palette:["#e8c4a8","#8aa7c4","#d9886e","#5e4a3e","#f2e8d4"],
  tagline:"At the dressing table — radiance painted on the eve of catastrophe",
  works:[{t:"At the Dressing-Table (Self-Portrait)",y:"1909"},{t:"Whitening Canvas",y:"1917"},{t:"House of Cards",y:"1919"}],
  life:"Born into the Benois dynasty of artists on a Ukrainian estate, Serebriakova painted her luminous self-portrait at twenty-five and woke up famous. The Revolution took the estate, typhus took her husband, and a 1924 trip to Paris became a forty-year exile: two children with her, two behind the Iron Curtain — her daughter Tatiana saw her again only after thirty-six years.",
  career:"At the Dressing-Table — a young woman combing her hair in candid morning happiness — was bought by the Tretyakov within months and remains among Russia's most loved paintings. Her peasant cycles dignify harvest and banya with a classical calm; House of Cards, her four fatherless children at play, holds the era's grief in a single tabletop.",
  outside:"In exile she painted Moroccan journeys and ballet dancers backstage while sending money east and refusing to commercialise. A 1965 Moscow retrospective, arranged at last by her children, sold out the catalogue and restored her to Soviet art history two years before her death in Paris.",
  facts:["She was among the first Russian women to be recognised as a major painter — without ever joining a movement.",
    "Her uncle Alexandre Benois co-founded the Ballets Russes' design world she later drew from backstage.",
    "Her four children split two-and-two across the Iron Curtain; both pairs became artists and keepers of her work."] },

{ id:"natalia-goncharova", name:"Natalia Goncharova", years:"1881–1962", born:1881, died:1962,
  nation:"russia", eras:["20th-century"], movements:["rayonism","abstract-art","expressionism"],
  techniques:["oil-painting","flat-color","lithography"], style:"artdeco",
  palette:["#c4302a","#e8a82e","#2e50c4","#1d1c22","#e8dcc4"],
  tagline:"Rays, icons and painted faces — Moscow's avant-garde amazon",
  works:[{t:"Cyclist",y:"1913"},{t:"The Cathedral (Rayonist composition)",y:"1913"},{t:"Peasants Picking Apples",y:"1911"}],
  life:"Great-grand-niece of Pushkin's wife, Goncharova scandalised and led Moscow's avant-garde beside her lifelong partner Mikhail Larionov: futurist face-painting on the boulevards, blasphemy trials, manifestos. From 1915 they designed for Diaghilev's Ballets Russes, settling in Paris, where she worked until her death in 1962.",
  career:"She burned through neo-primitivism, cubo-futurism and her own invention, Rayonism — pictures built from the light rays between objects — at a pace that made Paris look slow; her 1913 Moscow retrospective held around 760 works, by a woman of thirty-two. Her Coq d'Or and Firebird designs re-dressed Russian folk splendour for the world stage.",
  outside:"She and Larionov paraded with painted faces and radish-buttoned coats ('why do we paint ourselves: because museums are graveyards'); she was tried — and acquitted — for exhibiting nudes 'pornographically'. They married only in 1955, after fifty years together, to secure each other's estates.",
  facts:["Her 1913 retrospective is still among the largest ever given a living woman artist.",
    "For a time in the 2000s she was the most expensive woman painter at auction.",
    "Religious censors confiscated her four-part Evangelists in 1914 — avant-garde icons proved too literal for both sides."] },

{ id:"lyubov-popova", name:"Lyubov Popova", years:"1889–1924", born:1889, died:1924,
  nation:"russia", eras:["20th-century"], movements:["constructivism","cubism","abstract-art"],
  techniques:["oil-painting","flat-color","collage"], style:"geometric",
  palette:["#c4302a","#1a1a1a","#e8e0d0","#3e3a36","#caa43e"],
  tagline:"Painterly architectonics — then fabric by the metre for the Revolution",
  works:[{t:"Painterly Architectonic",y:"1917"},{t:"Space-Force Construction",y:"1921"},{t:"Textile designs, First State Factory",y:"1923–24"}],
  life:"Born to a wealthy merchant family near Moscow, Popova studied with Le Fauconnier and Metzinger in Paris, absorbed Tatlin's studio culture at home, and became the Russian avant-garde's most rigorous builder of pictures. She died at thirty-five of scarlet fever, caught at the bedside of her small son, who died two days before her.",
  career:"Her Painterly Architectonics stack tilted planes of red, black and ochre like girders under stress — abstraction with a structural engineer's conviction. After 1921 she renounced easel painting as bourgeois ('no artistic success equals the satisfaction of seeing a peasant buy a length of my fabric') and designed textiles, stage sets and workers' clothing: Constructivism kept its word through her.",
  outside:"Her set for Meyerhold's The Magnanimous Cuckold — a bare machine of wheels and platforms the actors operated — remains a landmark of theatre design taught in every stagecraft course. The 1924 memorial exhibition opened months after her death; the avant-garde buried its conscience early.",
  facts:["Her quote about the peasant and the fabric is Constructivism's most cited sentence.",
    "She taught colour at the Vkhutemas, the Soviet Bauhaus, alongside Rodchenko.",
    "Scarlet fever took her son on the 23rd of May and Popova on the 25th."] },

{ id:"shen-zhou", name:"Shen Zhou", years:"1427–1509", born:1427, died:1509,
  nation:"china", eras:["15th-century","16th-century"], movements:["literati-painting"],
  techniques:["ink-wash","watercolor"], style:"tonal",
  palette:["#5e5648","#8a8276","#d9d0bc","#5e6e5a","#ece8dc"],
  tagline:"Master of the Wu School — mountains painted between cups of tea",
  works:[{t:"Lofty Mount Lu",y:"1467"},{t:"Poet on a Mountaintop",y:"c. 1500"},{t:"Watching the Mid-Autumn Moon",y:"c. 1486"}],
  life:"Born into a scholarly landowning family in Suzhou, Shen Zhou declined the examination path to office — citing his duty to his ageing mother — and spent eighty-two years exactly where he wished: among gardens, poems and friends. He founded the Wu School, the literati current that dominated Ming painting, and taught the great Wen Zhengming.",
  career:"His ink landscapes carry a companionable warmth rare in monumental painting: a tiny poet on a cliff faces the void, and the void feels friendly. Lofty Mount Lu, painted for his teacher's birthday, stacks a mountain like a career of accumulated kindness; his garden scenes and vegetables made the humble subjects of daily life worthy of the scholar's brush.",
  outside:"Famously generous, he is said to have signed forgeries of his own work brought to him by struggling painters, reasoning that his name cost him nothing and fed a family. Poetry, calligraphy and painting were one practice to him — 'the three perfections' lived daily.",
  facts:["He never held office in a culture where office defined a man — filial piety as career plan.",
    "His authentication of his own fakes is the most quoted act of art-world kindness in Chinese history.",
    "Poet on a Mountaintop inscribes its poem into the sky — text as weather."] },

{ id:"bada-shanren", name:"Bada Shanren", years:"c. 1626–1705", born:1626, died:1705,
  nation:"china", eras:["17th-century","18th-century"], movements:["literati-painting"],
  techniques:["ink-wash"], style:"naive",
  palette:["#2a2c30","#8a8276","#d9d0bc","#5e6e5a","#ece8dc"],
  tagline:"Fish with rolling eyes — a fallen prince's magnificent sulk",
  works:[{t:"Fish and Rocks",y:"c. 1690"},{t:"Lotus and Birds",y:"c. 1690s"},{t:"Two Birds",y:"c. 1694"}],
  life:"Born Zhu Da, a prince of the Ming imperial house, he watched his dynasty fall to the Manchus in 1644 and vanished into a Buddhist monastery. Episodes of muteness and reputed madness followed — he once inked the word 'dumb' on his door and refused to speak — before he re-emerged under the name Bada Shanren, 'Mountain Man of the Eight Greats', selling paintings to live.",
  career:"His ink creatures are unforgettable: fish and birds with eyes rolled upward in cosmic disdain, one-legged birds balancing like questions, lotus stems slashed in seconds. The minimal means — a few wet strokes on empty paper — carry maximum charge: grief, satire and Zen blankness in the same flick of the wrist. Modern Chinese painting reveres him as its secret source.",
  outside:"Whether the madness was illness, mourning or self-protection from Qing authorities remains debated — a prince who couldn't be seen to mourn made his birds do it. His signature, scrawled, can be read as both 'laughing' and 'weeping'.",
  facts:["Qi Baishi: 'I wish I could have been born three hundred years earlier, to grind ink and prepare paper for Bada Shanren.'",
    "His rolled-eye fish are routinely described as art history's best passive aggression.",
    "Forgeries multiplied within his lifetime — connoisseurs joke his fish glare hardest in the fakes."] },

{ id:"xu-beihong", name:"Xu Beihong", years:"1895–1953", born:1895, died:1953,
  nation:"china", eras:["20th-century"], movements:["realism"],
  techniques:["ink-wash","oil-painting"], style:"gestural",
  palette:["#2a2c30","#8a6e46","#d9d0bc","#b0884a","#ece8dc"],
  tagline:"Galloping horses — Chinese ink schooled in Paris anatomy",
  works:[{t:"Galloping Horse",y:"1941"},{t:"The Foolish Old Man Removes the Mountains",y:"1940"},{t:"Slave and Lion",y:"1924"}],
  life:"A poor seal-carver's son from Jiangsu, Xu Beihong drew for rice before scholarships carried him to Paris's École des Beaux-Arts. He returned convinced Chinese painting needed Western anatomy and perspective grafted onto the ink tradition, led academies through war and revolution, and died in 1953 as founding president of the Central Academy of Fine Arts.",
  career:"His galloping horses — ribcages of wet ink, manes flying in dry-brush — became modern China's most reproduced images, painted by the hundred during the war years and sold abroad to fund relief. Monumental history paintings like The Foolish Old Man harnessed myth to national perseverance; his realist curriculum shaped Chinese art education for half a century.",
  outside:"During WWII he toured Southeast Asia exhibiting for war relief, raising fortunes brushstroke by brushstroke. His collection — including the Eighty-seven Immortals scroll he bought back from abroad — anchors the Beijing memorial museum bearing his name.",
  facts:["Chinese diplomacy long gifted Xu Beihong horse paintings — ink as statecraft.",
    "Slave and Lion set a then-record for Asian oil painting at auction in 2006 (~HK$54 million).",
    "He repurchased the Tang-attributed Eighty-seven Immortals scroll twice — once after it was stolen from him in wartime."] },

{ id:"zhang-daqian", name:"Zhang Daqian", years:"1899–1983", born:1899, died:1983,
  nation:"china", eras:["20th-century"], movements:["literati-painting","abstract-art"],
  techniques:["ink-wash","splashed-ink","watercolor"], style:"colorfield",
  palette:["#2e6e8a","#5e8a6e","#caa43e","#2a2c30","#ece8dc"],
  tagline:"Five hundred years of Chinese painting in one man — forgeries included",
  works:[{t:"Panorama of Mount Lu",y:"1981–83"},{t:"Splashed-colour lotus series",y:"1960s–70s"},{t:"Peach Blossom Spring",y:"1982"}],
  life:"Sichuan-born, briefly a novice monk (he kept the dharma name Daqian), Zhang lived like a Ming scholar with a jet pass: gowned and long-bearded through Brazil, California and Taipei, gibbons at his heels, banquets cooked to his own recipes. He copied the Dunhuang cave murals for three years, met Picasso as an equal, and died in Taipei at eighty-three.",
  career:"He mastered every classical manner so completely that his forgeries of old masters entered major museums — curators still audit holdings against his hand. Then, as his eyesight failed in the 1960s, he invented his late glory: splashed-colour landscapes, azurite and malachite poured into mountains half abstract, a thousand-year tradition crashing gloriously into Abstract Expressionism's decade.",
  outside:"The 1956 summit with Picasso in Nice — gifts exchanged, Picasso showing his own brush-paintings — was billed as East meets West; Picasso reportedly asked why Chinese artists studied in Paris at all. In 2011 Zhang topped global auction turnover, outselling Picasso and Warhol.",
  facts:["The Met and Boston's MFA have both re-catalogued 'ancient' works as Zhang Daqian forgeries.",
    "He kept pet gibbons all his life, believing (his joke) he had been one.",
    "His splashed-colour Panorama of Mount Lu, painted nearly blind, spans over ten metres."] },

{ id:"sesshu-toyo", name:"Sesshū Tōyō", years:"1420–1506", born:1420, died:1506,
  nation:"japan", eras:["15th-century","16th-century"], movements:["zen-painting"],
  techniques:["ink-wash","splashed-ink"], style:"tonal",
  palette:["#2a2c30","#8a8276","#b0b8b4","#5e6e5a","#ece8dc"],
  tagline:"Splashed-ink mountains — Zen's greatest brush",
  works:[{t:"Haboku (Splashed Ink) Landscape",y:"1495"},{t:"Long Scroll of Landscapes (Sansui Chōkan)",y:"1486"},{t:"Winter Landscape",y:"c. 1470s"}],
  life:"A samurai family's son sent young to a Zen temple, Sesshū trained in Kyoto before sailing with a trade mission to Ming China in 1467 — studying the masters at the source and finding them, he reported with monkish cheek, less instructive than China's actual mountains. He worked from a studio called the 'Boat-of-Heaven' in western Japan until his mid-eighties.",
  career:"His Long Scroll unrolls sixteen metres of seasons, cliffs and travellers in strokes like axe cuts — the summit of Japanese ink landscape. The 1495 Haboku Landscape condenses everything to a dozen wet flicks: mountain, mist, tavern flag, fisherman, all emerging from what looks one second earlier like spilled ink. It remains the tradition's most studied page.",
  outside:"The beloved legend: as a boy punished by being tied to a temple pillar, he drew a mouse on the floor with his tears and toe — so lifelike the priest thought it ran. Japan has designated more of his works National Treasures than any other artist's.",
  facts:["Six of his paintings are National Treasures of Japan — the record for one hand.",
    "He signed late works 'the man who went to China and found nothing to learn but the mountains.'",
    "Five centuries before action painting, haboku meant flinging ink and finding the picture."] },

{ id:"ogata-korin", name:"Ogata Kōrin", years:"1658–1716", born:1658, died:1716,
  nation:"japan", eras:["17th-century","18th-century"], movements:["rinpa"],
  techniques:["gold-leaf","ink-wash","silk-painting"], style:"ornament",
  palette:["#caa43e","#2e4a8a","#2e6e5a","#e8cd7a","#8a2620"],
  tagline:"Irises on gold — design raised to the level of weather",
  works:[{t:"Irises (Kakitsubata-zu)",y:"c. 1701–05"},{t:"Red and White Plum Blossoms",y:"c. 1712–15"},{t:"Wind God and Thunder God (after Sōtatsu)",y:"c. 1700s"}],
  life:"Heir to a luxurious Kyoto kimono house patronised by court ladies, Kōrin spent the family fortune with both hands — theatre, teahouses, legendary extravagances — until bankruptcy obliged genius to work. With his potter brother Kenzan he perfected the decorative current later named Rinpa in his honour, dying in 1716 with debts and immortality.",
  career:"The Irises screens repeat one motif — blue iris, green blade, gold ground — into a rhythm so perfect it reads as music notation; Red and White Plum Blossoms bends a patterned river between two trees like lacquered lightning. Using tarashikomi — pigment pooled into wet pigment — he made decoration carry the weight other schools gave narrative.",
  outside:"One famous picnic tale has him unwrapping gold-leafed bamboo skins at a riverside party and tossing them in the stream — conspicuous consumption as performance art, duly punished by the shogunate's sumptuary laws. 'Kōrin pattern' remains a working term in kimono design three centuries on.",
  facts:["Both Irises screens sets are National Treasures; one pair returns to public view only weeks per year.",
    "Klimt's gold period owes a documented debt to Rinpa screens exhibited in Vienna.",
    "He reworked Sōtatsu's Wind and Thunder Gods a century later — Rinpa's relay race of homage."] },

{ id:"ito-jakuchu", name:"Itō Jakuchū", years:"1716–1800", born:1716, died:1800,
  nation:"japan", eras:["18th-century"], movements:["rinpa"],
  techniques:["silk-painting","ink-wash","woodblock"], style:"fauvist",
  palette:["#c4302a","#e8e0d0","#2e6e5a","#caa43e","#3e3a36"],
  tagline:"The greengrocer's roosters — feathers counted like sutras",
  works:[{t:"Colorful Realm of Living Beings",y:"c. 1757–66"},{t:"Birds and Animals in the Flower Garden",y:"c. 1760s"},{t:"White Phoenix",y:"c. 1770s"}],
  life:"Heir to a Kyoto wholesale greengrocery, Jakuchū ran the family business dutifully until forty, then handed it to a brother and gave himself to painting and Zen — his name, taken from the Tao Te Ching, means 'like the void'. He kept dozens of chickens in his yard as live models and worked into his eighties, dying in 1800.",
  career:"His thirty-scroll Colorful Realm — roosters, phoenixes, octopus and frost-bitten lotus on silk, donated with a Buddha triad to the Shōkoku-ji temple — counts among painting's most intense devotional projects: pigment layered behind the silk to make whites glow, every feather a separate decision. His mosaic-gridded Birds and Animals screens look startlingly like pixel art.",
  outside:"Long a connoisseur's secret, he became a national obsession: the 2016 Tokyo anniversary show drew lines of five hours, and 'Jakuchū' is now shorthand in Japan for obsessive splendour. The Colorful Realm scrolls were reunited with their Buddha triad for the first time in a century at that show.",
  facts:["He reportedly observed his roosters for years before allowing himself to paint one.",
    "The mosaic screens use some 86,000 hand-painted grid squares — Edo-period pixels.",
    "His prayer inscribed with the temple donation asks that the scrolls 'benefit beings for a thousand years.'"] },

{ id:"uemura-shoen", name:"Uemura Shōen", years:"1875–1949", born:1875, died:1949,
  nation:"japan", eras:["19th-century","20th-century"], movements:["nihonga"],
  techniques:["silk-painting","ink-wash"], style:"rococo",
  palette:["#d9b4be","#8aa7c4","#e8dcc4","#5e6e5a","#caa45c"],
  tagline:"Bijin-ga with a spine — the first woman of Japanese painting",
  works:[{t:"Jo no Mai (Dance Performed in a Noh Play)",y:"1936"},{t:"Flame (Honō)",y:"1918"},{t:"Late Autumn",y:"1943"}],
  life:"Born Uemura Tsune above her widowed mother's Kyoto tea shop, Shōen entered painting school at twelve — the only girl — and survived scandal (a son born out of wedlock, raised proudly under her own name) to become the first woman appointed Imperial Household Artist and, in 1948, the first woman awarded Japan's Order of Culture. She died the next year.",
  career:"She took bijin-ga, the 'beautiful women' genre men had painted for male eyes, and gave it interiority: her women in mineral pigment on silk read, work, wait and decide. Jo no Mai's dancer, fan raised mid-form, is dignity itself in seven colours; Flame, her one venture into jealous fury via a Noh ghost, still startles museumgoers expecting politeness.",
  outside:"Her son Uemura Shōkō and grandson Atsushi both became celebrated nihonga painters — a three-generation dynasty from a tea-shop widow's daughter. 'My women,' she wrote, 'are no mere pretty likenesses; I want a fragrance of the soul.'",
  facts:["Japan's postwar banknote committee shortlisted her portrait — a tea-shop girl nearly on the money.",
    "Flame was her single excursion into the demonic; she said it frightened her to finish it.",
    "Order of Culture, 1948: no woman had received it in its eleven prior years."] },

{ id:"kim-hong-do", name:"Kim Hong-do (Danwon)", years:"1745–c. 1806", born:1745, died:1806,
  nation:"korea", eras:["18th-century","19th-century"], movements:["realism"],
  techniques:["ink-wash","silk-painting"], style:"naive",
  palette:["#d9cdb4","#8a6e46","#3e3a36","#5e6e5a","#ece4d2"],
  tagline:"Joseon's everyday genius — wrestling matches, schoolboys, smiles in ink",
  works:[{t:"Ssireum (Wrestling)",y:"c. 1780"},{t:"A Schoolroom (Sodang)",y:"c. 1780"},{t:"Dano Day",y:"c. 1780"}],
  life:"Court painter to King Jeongjo — who reportedly declared no portrait of himself complete without Kim's hand — Danwon painted royal ceremonies, Buddhist guardians and diplomatic missions to Japan. Yet his immortality rests on album leaves of ordinary Koreans, and his last years fade from the record into illness and obscurity around 1806.",
  career:"His genre albums catch eighteenth-century Korea mid-laugh: wrestlers straining while a fan-seller scans the crowd, a schoolboy sniffling after the switch as classmates smirk, women on a swing at Dano festival. The brush is shorthand — a dozen strokes per figure — but the sociology is complete; Korean historians read his albums like census data with jokes.",
  outside:"King Jeongjo's trust extended to sending him (scholars believe) on a covert survey of Japanese terrain via a Tsushima mission — court painter as cartographer-spy. The 'Danwon style' became the template for Korean genre painting and, centuries later, for historical drama set design.",
  facts:["The Ssireum wrestling leaf hides a famous error — a spectator's hands are switched — debated as joke or slip.",
    "Korea's Boys' Day stamps, textbooks and banknote vignettes have all borrowed his album figures.",
    "His teacher Pyo-am praised him as 'able to paint everything under heaven' — the court tested the claim regularly."] },

{ id:"park-soo-keun", name:"Park Soo-keun", years:"1914–1965", born:1914, died:1965,
  nation:"korea", eras:["20th-century"], movements:["realism","naive-art"],
  techniques:["oil-painting","impasto"], style:"pointillist",
  palette:["#a8a094","#8a8276","#caa45c","#5e5648","#e8e0d0"],
  tagline:"Granite-textured tenderness — postwar Korea's beloved painter of the poor",
  works:[{t:"Tree and Two Women",y:"1962"},{t:"A Wash Place",y:"1950s"},{t:"Grandfather and Grandson",y:"1960"}],
  life:"Born to a poor family in Gangwon province, Park finished only primary school and taught himself painting from a borrowed Millet reproduction, vowing to 'paint the good and the honest'. He survived war and division selling portraits to American soldiers at the Seoul PX, lost an eye to cataract complications, and died at fifty-one — months before the fame that would canonise him.",
  career:"His surfaces are his signature: oil built up and scraped into a granular grey crust like weathered granite or Silla stone Buddhas, on which market women, leafless trees and children sit in profile, monumental and humble at once. Postwar Korea recognised itself in that patience; for decades he held the auction record for any Korean artwork.",
  outside:"The American collectors he met at the PX — secretaries and officers' wives — carried his small boards home, which is why early Parks kept surfacing in US garage sales decades later. A museum in his home county now anchors Korean art pilgrimage routes.",
  facts:["A Wash Place sold in 2007 for about 4.5 billion won, then the highest price for any Korean painting.",
    "He painted Millet's Angelus from a magazine at twelve and called it his conversion.",
    "Seoul's PX portrait stand also employed a young novelist's mother — Park Wan-suh later wrote him into her fiction."] },

{ id:"raja-ravi-varma", name:"Raja Ravi Varma", years:"1848–1906", born:1848, died:1906,
  nation:"india", eras:["19th-century","20th-century"], movements:["realism","orientalism"],
  techniques:["oil-painting","lithography"], style:"baroque",
  palette:["#8a2620","#caa43e","#2e6e5a","#5e3450","#e8d4b0"],
  tagline:"The gods in oil paint — and on every calendar in India",
  works:[{t:"Shakuntala",y:"1870"},{t:"Lady in the Moonlight",y:"1889"},{t:"Galaxy of Musicians",y:"1889"}],
  life:"Born into the Travancore royal house in Kerala, Ravi Varma taught himself European oil technique from palace paintings and visiting portraitists, then conquered colonial India's exhibitions — a Vienna medal in 1873 announced him internationally. He travelled the subcontinent painting maharajas and goddesses until his death in 1906.",
  career:"He gave Hindu epics the full apparatus of academic oil painting — Shakuntala glancing back under the pretence of a thorn, Saraswati and Lakshmi with human warmth — and then, decisively, founded a Bombay lithographic press so the gods could hang in every home. His oleographs standardised divine iconography and the draped sari 'national' look across regions; calendar art, cinema posters and a billion devotional images descend from him.",
  outside:"The press bankrupted him (he sold it to his German printer Fritz Schleicher, who prospered); purists attacked his 'theatrical' gods then, and postcolonial critics debate him still — while his images remain inescapable. India's highest art award in Kerala bears his name.",
  facts:["His Galaxy of Musicians poses women from across India's regions in one frame — a unity allegory in 1889.",
    "Vienna 1873 and Chicago 1893 both medalled him — colonial India's first international art star.",
    "Bollywood's visual grammar of the mythological owes him its founding look."] },

{ id:"mf-husain", name:"M. F. Husain", years:"1915–2011", born:1915, died:2011,
  nation:"india", eras:["20th-century","21st-century"], movements:["modernism","expressionism"],
  techniques:["oil-painting","acrylic-painting"], style:"expressionist",
  palette:["#c4302a","#1d1c22","#e8a82e","#2e50c4","#e8dcc4"],
  tagline:"Barefoot with a six-foot brush — India's most famous, most exiled modernist",
  works:[{t:"Horses series",y:"1950s–2000s"},{t:"Between the Spider and the Lamp",y:"1956"},{t:"Mother Teresa series",y:"1980s"}],
  life:"Born in Pandharpur, Maqbool Fida Husain painted Bombay cinema billboards for pennies before co-founding the Progressive Artists' Group in 1947, the collective that built Indian modernism alongside the new republic. Hindu-nationalist campaigns over his goddess nudes drove him into exile at ninety-one; he accepted Qatari citizenship and died in London in 2011.",
  career:"His rearing horses — Cubism's angles galloping through Indian epic — became independent India's visual heartbeat, painted across six decades with undiminished velocity. He worked enormous, fast and everywhere: Ramayana and Mahabharata cycles for village viewings, films (his Through the Eyes of a Painter won at Berlin), and series on Mother Teresa, cinema and the British Raj.",
  outside:"Famously barefoot in every setting — five-star lobbies included — he wielded brushes taller than himself and courted Bollywood openly, painting the actress Madhuri Dixit as a muse-cycle and directing her in a feature film. Obscenity cases (eventually dismissed by India's Supreme Court) kept him from ever returning home.",
  facts:["He skipped a London club dinner in his honour rather than wear shoes.",
    "Christie's 2008: his Battle of Ganga and Jamuna set the then-record for Indian art at auction.",
    "Forbes once called him 'the Picasso of India' — he answered that Picasso was 'the Husain of Spain.'"] },

{ id:"reza-abbasi", name:"Reza Abbasi", years:"c. 1565–1635", born:1565, died:1635,
  nation:"iran", eras:["16th-century","17th-century"], movements:["persian-miniature"],
  techniques:["miniature-painting","gouache","gold-leaf"], style:"ornament",
  palette:["#1f6e8a","#c4663a","#caa43e","#5e3450","#e8dcc0"],
  tagline:"Isfahan's dreaming line — the Persian miniature's last great master",
  works:[{t:"Youth Reading",y:"c. 1625–26"},{t:"Two Lovers",y:"1630"},{t:"Portrait of a Dervish",y:"c. 1600"}],
  life:"Son of a court painter, Reza rose young in Shah Abbas the Great's Isfahan workshop and was honoured with the royal epithet 'Abbasi'. Mid-career he abruptly quit the court for years among wrestlers, dervishes and street company — to his biographers' scandal — before returning, deepened, to serve until his death in 1635.",
  career:"He turned the Persian tradition from crowded manuscript epics toward the single-page album leaf: a youth swaying like his own calligraphic outline, lovers entwined in three colours and gold, dervishes drawn with a reed pen's pressure changes doing the work of paint. His line — elastic, musical, slightly ironic — defined the Isfahan school and every Persian drawing after.",
  outside:"The wrestler years gave him subjects court art had ignored: labourers, pilgrims, sharp-eyed old men sketched with documentary affection. Tehran's museum of the classical book arts bears his name; his Two Lovers leaf is among the Met's most reproduced Islamic works.",
  facts:["Contemporary chronicler Qazi Ahmad lamented the genius who preferred 'the company of wrestlers' to the palace.",
    "His single-page works were made for muraqqa albums — collectors curated him like a playlist.",
    "Signature flourish: dated inscriptions noting the hour and his mood — seventeenth-century time-stamps."] },

{ id:"giotto", name:"Giotto di Bondone", years:"c. 1267–1337", born:1267, died:1337,
  nation:"italy", eras:["14th-century"], movements:["proto-renaissance"],
  techniques:["fresco","tempera","gold-leaf"], style:"renaissance",
  palette:["#2e4a8a","#b06a4a","#d9b27c","#7a8e66","#e8dcc3"],
  tagline:"The shepherd boy who taught painting to weep",
  works:[{t:"The Scrovegni (Arena) Chapel frescoes",y:"c. 1303–05"},{t:"Ognissanti Madonna",y:"c. 1310"},{t:"The Lamentation",y:"c. 1305"}],
  life:"Vasari's legend has Cimabue discovering a Tuscan shepherd boy drawing sheep on a rock with a pointed stone; documented fact has Giotto running Italy's busiest workshop, buying farms, lending money and ending as chief architect of Florence Cathedral, whose bell tower still bears his name. He died in 1337, already a classic — Dante had put him in the Divine Comedy a generation earlier.",
  career:"In Padua's Scrovegni Chapel he repainted the rules: figures with weight and backs, grief that bends bodies, a kiss between Joachim and Anna that is the first believable embrace in European art. The blue of that ceiling became painting's most famous sky. Every account of the Renaissance — starting with the Renaissance's own — begins with him.",
  outside:"Boccaccio made him a wit in the Decameron; the anecdote tradition adores him — asked by a papal envoy for proof of skill, he drew a perfect circle freehand and said 'send that.' The chapel's Adoration includes a blazing comet, very likely Halley's of 1301, observed from life.",
  facts:["'The O of Giotto' is still an Italian proverb for effortless mastery.",
    "The European Space Agency named its Halley's Comet probe 'Giotto' after his Scrovegni comet.",
    "Dante, in Purgatorio: 'Cimabue thought to hold the field, and now Giotto has the cry.'"] },

{ id:"duccio", name:"Duccio di Buoninsegna", years:"c. 1255–1319", born:1255, died:1319,
  nation:"italy", eras:["14th-century"], movements:["proto-renaissance"],
  techniques:["tempera","gold-leaf"], style:"ornament",
  palette:["#caa43e","#8a2620","#2e4a6e","#5e3450","#e8d9b4"],
  tagline:"The Maestà carried through Siena to the sound of bells",
  works:[{t:"Maestà",y:"1308–11"},{t:"Rucellai Madonna",y:"1285"},{t:"Madonna and Child (Stoclet Madonna)",y:"c. 1290–1300"}],
  life:"Siena's greatest painter appears in the archives mostly through fines — for debts, for declining militia duty, for what one scholar calls 'a distaste for civic obligation matched only by his genius.' Whatever his citizenship record, when his Maestà was finished in 1311 the city closed its shops and carried the altarpiece from studio to cathedral in procession, trumpets and bells sounding.",
  career:"The Maestà — Madonna enthroned among ranked saints on gold, backed by dozens of narrative panels — is the summit of Sienese painting: Byzantine splendour warmed into swaying line and human glance. Where Giotto built bodies, Duccio perfected tenderness; the two roads out of the icon start with these two contemporaries.",
  outside:"The altarpiece was sawn apart in the eighteenth century and its panels scattered from London to New York — museum labels reading 'from the Maestà of Duccio' mark one of art's great diasporas. His workshop seeded the whole Sienese school: Simone Martini and the Lorenzetti brothers walked out of it.",
  facts:["The Met paid a reported $45 million-plus for his small Stoclet Madonna in 2004 — then its costliest purchase ever.",
    "A contemporary chronicle records the 1311 procession: 'the shops were shut, and the bells rang the Gloria.'",
    "The Maestà's back panels tell Christ's Passion in over 40 scenes — a cathedral's cinema, both sides playing."] },

{ id:"theophanes-the-greek", name:"Theophanes the Greek", years:"c. 1340–c. 1410", born:1340, died:1410,
  nation:"greece", eras:["14th-century","15th-century"], movements:["icon-painting"],
  techniques:["fresco","tempera"], style:"expressionist",
  palette:["#8a5e3a","#b0884a","#3e3a30","#d9c8a4","#1d1410"],
  tagline:"Byzantium's lightning, loosed on Russian walls — Rublev's teacher",
  works:[{t:"Frescoes of the Transfiguration Church, Novgorod",y:"1378"},{t:"Deesis tier, Annunciation Cathedral, Moscow",y:"1405"},{t:"Our Lady of the Don (attributed)",y:"c. 1380–95"}],
  life:"A master from Constantinople who had frescoed, by a contemporary's count, some forty churches across Byzantium and the Black Sea, Theophanes arrived in Novgorod around 1370 and spent his last decades electrifying Russian art. In 1405 he led the decoration of Moscow's Annunciation Cathedral with a young monk named Andrei Rublev on the team.",
  career:"His Novgorod frescoes are unlike anything before them: saints in near-monochrome ochre, modelled by slashes of white — 'lightning strokes' — as if holiness were voltage. The monk Epiphanius the Wise left an astonished eyewitness account: Theophanes painted without model books, walking, talking with visitors, 'pondering lofty things while his hand painted without rest.'",
  outside:"Epiphanius' letter is effectively art history's first studio profile, five centuries before art journalism. The pairing of master and pupil — Theophanes' storm beside Rublev's calm — remains Russian art's founding dialogue: severity and mercy sharing one scaffold.",
  facts:["He is one of the very few medieval painters described at work by a named eyewitness.",
    "Only the Novgorod frescoes survive as documented work — one church holding an entire reputation.",
    "Greece and Russia share his legacy: Constantinople trained the hand, Novgorod kept the walls."] }
);
