/* PIGMENT — atlas widening batch 3: the New York School's second rank and
   the Washington colourists. Every painter here died after 1955, so their
   work is under copyright: pages carry generative covers, never reproductions. */
window.ARTISTS = (window.ARTISTS || []).concat([

{ id:"hans-hofmann", name:"Hans Hofmann", years:"1880–1966", born:1880, died:1966,
  nation:"germany", eras:["20th-century"], movements:["abstract-expressionism","color-field"],
  techniques:["oil-painting","gestural-abstraction","impasto"], style:"gestural",
  palette:["#c8352b","#f0b429","#2f6fb0","#2e7d4f","#f2ece0"],
  tagline:"The teacher who taught America to paint",
  works:[{t:"The Gate",y:"1959–60"},{t:"Pompeii",y:"1959"},{t:"Memoria in Aeternum",y:"1962"},{t:"To Miz — Pax Vobiscum",y:"1964"}],
  life:"Born in Bavaria and raised in Munich, he was a scientific boy who filed patents before he settled on paint. From 1904 he spent a decade in Paris among Matisse, Braque, Delaunay and Picasso, watching Cubism arrive in real time. The First World War stranded him in Germany, where he opened his own art school in 1915; the rise of the Nazis sent him to America in 1932, aged fifty-two, with a European avant-garde education nobody in New York yet had.",
  career:"His doctrine was push and pull: flat planes of colour, correctly weighted, could open depth without a single line of perspective. He taught it in New York and Provincetown for a quarter century to Lee Krasner, Helen Frankenthaler, Joan Mitchell, Louise Nevelson and hundreds more, drawing over their canvases in charcoal to prove the point. He closed both schools in 1958, at seventy-eight, to paint full time — and the last eight years produced his best work, rectangular slabs of pure colour floating on stormy grounds. MoMA gave him a retrospective at eighty-three.",
  outside:"His English stayed magnificently broken, and students quoted his pronouncements for the rest of their lives. He married Maria Wolfegg — Miz — in 1924; after her death in 1963 he painted a memorial canvas and, at eighty-four, married again. He left his estate to the University of California, Berkeley.",
  facts:["He shut his famous school at seventy-eight so he could finally paint full time.",
    "Krasner, Frankenthaler and Mitchell all passed through his classrooms.",
    "He knew Matisse and Picasso in pre-war Paris and carried that education to New York in 1932.",
    "Push and pull — his term for depth built from flat colour alone — is still taught."] },

{ id:"clyfford-still", name:"Clyfford Still", years:"1904–1980", born:1904, died:1980,
  nation:"usa", eras:["20th-century"], movements:["abstract-expressionism","color-field"],
  techniques:["oil-painting","palette-knife","impasto"], style:"colorfield",
  palette:["#111112","#b3452c","#d9a441","#6d7b6a","#e8e2d6"],
  tagline:"Jagged fields, and a lifelong exit",
  works:[{t:"1957-D No. 1",y:"1957"},{t:"1948-C",y:"1948"},{t:"PH-118",y:"1947"},{t:"Jamais",y:"1944"}],
  life:"He grew up working wheat on the northern plains — North Dakota, Alberta, eastern Washington — and the labour never left his painting: hard weather, hard ground, nothing decorative. He taught at Washington State College for years while pushing toward abstraction, and reached it around 1940, earlier than Pollock or Rothko.",
  career:"His canvases are vast vertical fields torn by ragged edges, laid on thick with a palette knife, as if the surface had split to show something behind it. Then he did the rarest thing in modern art: he left. Contemptuous of dealers, critics and museums, he cut his ties through the 1950s, moved to a Maryland farm in 1961, and withheld almost everything he made from sale or exhibition. His will offered the entire hoard to any American city that would build a museum for his work and nothing else. Denver accepted in 2004 and opened it in 2011 — 3,125 works, one artist, one building.",
  outside:"He wrote furious open letters to institutions, including one to the president of the Metropolitan Museum, and revoked works from collections that displeased him. He forbade his paintings from being sold, lent or shown alongside other artists — conditions that still govern the museum bearing his name.",
  facts:["He kept roughly ninety-five percent of his output out of circulation for decades.",
    "His will demanded a city build a museum for his work alone; Denver did.",
    "He arrived at full abstraction before either Pollock or Rothko.",
    "The Clyfford Still Museum holds 3,125 works and shows no other artist."] },

{ id:"norman-lewis", name:"Norman Lewis", years:"1909–1979", born:1909, died:1979,
  nation:"usa", eras:["20th-century"], movements:["abstract-expressionism"],
  techniques:["oil-painting","gestural-abstraction"], style:"gestural",
  palette:["#15171c","#e6e0d4","#c9a227","#2f5d7c","#9b3f3f"],
  tagline:"Abstraction with Harlem inside it",
  works:[{t:"Migrating Birds",y:"1953"},{t:"Processional",y:"1965"},{t:"American Totem",y:"1960"},{t:"Harlem Turns White",y:"1955"}],
  life:"Born in Harlem to Bermudian immigrant parents, he studied with the sculptor Augusta Savage, went to sea as a young man, and taught for the WPA at the Harlem Community Art Center. He began as a social realist painting evictions and breadlines, and spent the 1940s deciding that protest painting had not, in fact, changed anything.",
  career:"His answer was abstraction that kept its subject smuggled inside. Small white marks gather across dark grounds and resolve, the longer you look, into crowds: a procession, a congregation, a march — or, in the works he made during the civil-rights years, the pointed hoods of a Klan rally. He was the only Black artist at the celebrated 1950 Studio 35 sessions where the New York School defined itself, won the popular prize at the Carnegie International in 1955, and co-founded the Spiral group in 1963 — and was still left out of the movement's histories for another forty years.",
  outside:"He taught for most of his life, at the Harlem Art Center, the Art Students League and elsewhere, and stayed active in civil-rights organising. Recognition arrived largely after his death; major retrospectives began in 2015.",
  facts:["He was the only African-American artist at the 1950 Studio 35 roundtable.",
    "He co-founded Spiral in 1963 with Romare Bearden and Charles Alston.",
    "His white processions read as both civil-rights marches and Klan hoods, deliberately.",
    "He won the Carnegie International's popular prize in 1955 and was still written out of the story."] },

{ id:"franz-kline", name:"Franz Kline", years:"1910–1962", born:1910, died:1962,
  nation:"usa", eras:["20th-century"], movements:["abstract-expressionism","action-painting"],
  techniques:["oil-painting","gestural-abstraction"], style:"gestural",
  palette:["#0f0f0f","#f2efe8","#4a4a48","#d8d2c4","#1d1d1c"],
  tagline:"Black on white, at the speed of a girder",
  works:[{t:"Chief",y:"1950"},{t:"Mahoning",y:"1956"},{t:"Painting Number 2",y:"1954"},{t:"New York, N.Y.",y:"1953"}],
  life:"He came from the Pennsylvania coal country, lost his father to suicide at seven, and trained in Boston and London as a perfectly conventional painter of figures, city scenes and barrooms. He spent his thirties in New York making a modest living from murals and portraits while the men around him were inventing something else.",
  career:"The turn came around 1949. As Elaine de Kooning told it, Kline projected one of his small brush drawings onto a studio wall with a borrowed Bell-Opticon and saw a fragment of it become architecture. He began painting huge black strokes across white with house-painter's brushes and cheap enamel, the pictures reading like scaffolding, track and bridge — an association he flatly refused, and refused equally the comparison to Japanese calligraphy. They look like one immense gesture; they were composed slowly, revised for weeks, the white painted around the black as carefully as the black itself.",
  outside:"He was the great talker of the Cedar Tavern, generous, funny, chronically broke until suddenly he wasn't. He loved trains, boxing and fast cars. He died at fifty-one of rheumatic heart disease, four years after the money finally arrived.",
  facts:["A projector accident in 1949 turned a small drawing into his whole late style.",
    "The paintings look instantaneous; some took weeks, with the white as worked as the black.",
    "He rejected both readings pressed on him: bridges and girders, and Zen calligraphy.",
    "He was fifty-one when he died, right as recognition arrived."] },

{ id:"morris-louis", name:"Morris Louis", years:"1912–1962", born:1912, died:1962,
  nation:"usa", eras:["20th-century"], movements:["color-field","washington-color-school"],
  techniques:["acrylic-painting","soak-stain"], style:"colorfield",
  palette:["#3a2c6e","#2e7d6b","#c2622c","#8a2a4a","#efe7d8"],
  tagline:"Colour poured, canvas untouched",
  works:[{t:"Beta Zeta",y:"1960–61"},{t:"Where",y:"1960"},{t:"Alpha-Pi",y:"1960"},{t:"Point of Tranquility",y:"1959–60"}],
  life:"Born Morris Louis Bernstein in Baltimore, he dropped the surname and most of the biography with it. He taught to survive, showed little, destroyed much of his early work, and settled in Washington, D.C. — a city with no art market, which suited him.",
  career:"In April 1953 he and Kenneth Noland visited Helen Frankenthaler's studio and saw Mountains and Sea; Louis described her as a bridge between Pollock and what was possible. He went home and stopped using brushes. Thinned acrylic resin, poured down raw unprimed canvas, soaked in until colour and cloth were the same object — no gesture, no impasto, no hand. The Veils, then the Unfurleds, then the Stripes, all made in a dining room fourteen feet across, with canvases bigger than the walls. Nobody ever saw him do it. He allowed no visitors, kept no notes, and left almost no evidence of a method.",
  outside:"He was intensely private even with friends, and diffident about his own importance. He died at forty-nine of lung cancer, widely attributed to years spent breathing solvent fumes in an unventilated room.",
  facts:["No one ever watched him paint; his technique is still partly guesswork.",
    "He worked in a dining room smaller than the canvases he was making.",
    "The 1953 studio visit to Frankenthaler changed his practice within days.",
    "Lung cancer killed him at forty-nine, almost certainly from the paint solvents."] },

{ id:"philip-guston", name:"Philip Guston", years:"1913–1980", born:1913, died:1980,
  nation:"canada", eras:["20th-century"], movements:["abstract-expressionism","expressionism"],
  techniques:["oil-painting","gestural-abstraction"], style:"expressionist",
  palette:["#e8a7a1","#c0392b","#1a1a1a","#8f6f5e","#efe3d6"],
  tagline:"He gave up abstraction to paint hoods",
  works:[{t:"City Limits",y:"1969"},{t:"The Studio",y:"1969"},{t:"Painting, Smoking, Eating",y:"1973"},{t:"Dial",y:"1956"}],
  life:"Born in Montreal to Jewish refugees from Odessa, raised in Los Angeles, he found his father's body after his suicide at the age of ten and began drawing alone in a closet. At Manual Arts High School he made a friend named Jackson Pollock and was expelled alongside him for a satirical leaflet mocking the school's sports culture.",
  career:"He painted anti-Klan murals in the 1930s, won every prize American art could give a muralist, then spent the 1950s as the most lyrical of the Abstract Expressionists — hovering pinks and greys that critics called abstract impressionism. In 1970 he showed cartoons instead: hooded, cigar-smoking Klansmen driving around in jalopies, painted in ham pink and cadmium red. The reviews were savage, friendships ended, and he left New York for Woodstock. He kept painting hoods, shoes, ashtrays, light bulbs and his own bloodshot eye for another decade. Almost every generation of painters since has been under their spell.",
  outside:"He read philosophy and Kafka, and his closest late friendships were with writers rather than painters. His long friendship with the composer Morton Feldman did not survive the figurative turn. He worked at night, chain-smoked, and painted the objects nearest to hand.",
  facts:["He was expelled from high school with Jackson Pollock over a satirical leaflet.",
    "The 1970 show of hooded figures cost him friendships and most of his critical standing.",
    "He had painted the Klan as a subject four decades earlier, in Depression-era murals.",
    "The late work is now among the most imitated painting of the last fifty years."] },

{ id:"robert-motherwell", name:"Robert Motherwell", years:"1915–1991", born:1915, died:1991,
  nation:"usa", eras:["20th-century"], movements:["abstract-expressionism"],
  techniques:["oil-painting","gestural-abstraction","collage"], style:"gestural",
  palette:["#141414","#f0ece1","#b03a2e","#d9a441","#2f4858"],
  tagline:"One elegy, painted a hundred and seventy times",
  works:[{t:"Elegy to the Spanish Republic, 108",y:"1965–67"},{t:"At Five in the Afternoon",y:"1949"},{t:"The Little Spanish Prison",y:"1941–44"},{t:"Open No. 24",y:"1968"}],
  life:"The son of a bank president, asthmatic and bookish, he studied philosophy at Stanford and Harvard and art history at Columbia, where Meyer Schapiro told him to stop writing about painting and go paint. He was the youngest of the New York School and the only one with a graduate seminar's vocabulary, which made him its explainer to the world — and made the others suspicious.",
  career:"From 1948 until his death he returned to a single image: heavy black ovoids clamped between vertical bars, titled Elegy to the Spanish Republic and numbered past 170. He was a child when the Republic fell, and said the pictures insisted that a terrible death had happened which should not be forgotten. Alongside them ran the Opens — quiet fields with a drawn rectangle — and a lifetime of collage, where he was arguably at his most inventive. He also edited the anthology that taught America what Dada had been.",
  outside:"He was married to Helen Frankenthaler from 1958 to 1971; the art world called them the golden couple and watched accordingly. He wrote constantly, lectured, and defended the movement in print when its members would not.",
  facts:["He came to painting from philosophy, on Meyer Schapiro's advice.",
    "The Elegies number more than 170 canvases over forty years.",
    "He edited The Dada Painters and Poets, the anthology that carried Dada into American art.",
    "He and Helen Frankenthaler were married for thirteen years."] },

{ id:"josef-albers", name:"Josef Albers", years:"1888–1976", born:1888, died:1976,
  nation:"germany", eras:["20th-century"], movements:["abstract-art","op-art","minimalism"],
  techniques:["oil-painting","flat-color","printmaking"], style:"geometric",
  palette:["#e0a12c","#c05a2a","#7a8f4a","#3f5d8a","#efe9dc"],
  tagline:"One square inside another, two thousand times",
  works:[{t:"Homage to the Square: Apparition",y:"1959"},{t:"Homage to the Square: Soft Spoken",y:"1969"},{t:"Structural Constellation",y:"1953"},{t:"Interaction of Color",y:"1963"}],
  life:"A Westphalian house-painter's son and a schoolteacher by training, he arrived at the Bauhaus in 1920 as its oldest student and stayed to run the glass workshop and the preliminary course. When the Nazis closed the school in 1933 he was offered a post at a brand-new experimental college in the North Carolina hills, sight unseen. He arrived at Black Mountain speaking almost no English and told his students his aim was to make their eyes open.",
  career:"From 1950 until his death he painted one motif: three or four flat squares nested inside each other, in a strictly fixed format, with the paint applied straight from the tube with a palette knife and never mixed. He made around two thousand of them. The point was never composition but interaction — how identical colours change when their neighbours change, an argument he set out in Interaction of Color in 1963 and proved on canvas for a quarter of a century. As head of design at Yale he taught Rauschenberg, Twombly and Kenneth Noland; a whole generation of American colour came through his classroom.",
  outside:"He and Anni Albers, the weaver, were married for fifty years and travelled repeatedly to Mexico, where the stepped pyramids fed his geometry. He wrote poetry, made hundreds of prints, and insisted to the end that he was teaching seeing rather than art.",
  facts:["He painted roughly two thousand Homages to the Square in a single fixed format.",
    "Paint went on with a palette knife straight from the tube, never mixed on a palette.",
    "Interaction of Color, published in 1963, is still assigned in art schools.",
    "He taught Rauschenberg, Twombly and Noland after the Bauhaus closed in 1933."] },

{ id:"kenneth-noland", name:"Kenneth Noland", years:"1924–2010", born:1924, died:2010,
  nation:"usa", eras:["20th-century"], movements:["color-field","washington-color-school"],
  techniques:["acrylic-painting","soak-stain","flat-color"], style:"geometric",
  palette:["#2f6fb0","#e0533a","#f0c33c","#1a1a1a","#f3efe6"],
  tagline:"The picture is the shape it is in",
  works:[{t:"Beginning",y:"1958"},{t:"Bloom",y:"1960"},{t:"Turnsole",y:"1961"},{t:"Gift",y:"1961–62"}],
  life:"Raised in Asheville, North Carolina, he served in the Air Force in the war and spent his G.I. Bill on Black Mountain College, up the road — studying Mondrian's neo-plasticism with Ilya Bolotowsky and, crucially, colour theory with Josef Albers. Two years in Paris with the sculptor Ossip Zadkine followed. He settled in Washington, D.C., taught night classes, and in 1952 met a fellow teacher named Morris Louis.",
  career:"In 1953 the two of them stood in Helen Frankenthaler's studio in front of Mountains and Sea, and the Washington Color School began that afternoon. Noland's question for the next fifty years was where a painting's image should sit in relation to its edge. The answers came in families: concentric circles first — targets, of which Beginning is among the earliest — then chevrons pointing into the corners, then horizontal stripes, and finally, when the rectangle could no longer contain the logic, diamonds and irregular shaped canvases. Colour was stained straight into raw cotton duck, so nothing sits on top of anything.",
  outside:"He showed in the American pavilion at the 1964 Venice Biennale and became the standard-bearer for what Clement Greenberg christened post-painterly abstraction. He later lived and worked quietly in Vermont and Maine, making prints and shaped canvases into his eighties.",
  facts:["He learned colour from Josef Albers at Black Mountain College.",
    "The 1953 visit to Frankenthaler's studio, with Morris Louis, started the Washington Color School.",
    "His work falls into four families: circles, chevrons, stripes and shaped canvases.",
    "He stained raw canvas so the colour is in the cloth, not on it."] }
]);
