/* PIGMENT — artists 1/7 : the 16th century */
window.ARTISTS = window.ARTISTS || [];
window.ARTISTS.push(
{ id:"leonardo-da-vinci", name:"Leonardo da Vinci", years:"1452–1519", born:1452, died:1519,
  nation:"italy", eras:["15th-century","16th-century"], movements:["high-renaissance"],
  techniques:["oil-painting","sfumato","fresco","tempera"], style:"renaissance",
  palette:["#3b2f1e","#6b5635","#a08552","#d6c39a","#5a6b5d"],
  tagline:"The universal mind who painted the world's most famous smile",
  works:[{t:"Mona Lisa",y:"c. 1503–19"},{t:"The Last Supper",y:"1495–98"},{t:"Lady with an Ermine",y:"c. 1490"},{t:"Salvator Mundi",y:"c. 1500"}],
  life:"Born illegitimate in the Tuscan hill town of Vinci, Leonardo was apprenticed to the Florentine sculptor-painter Verrocchio, whom legend says he surpassed as a teenager. He served the courts of Milan, Florence and Rome before accepting King Francis I's invitation to France, where he died in the royal manor of Cloux at sixty-seven, reportedly in the king's affection if not literally in his arms.",
  career:"Leonardo finished perhaps fifteen paintings in fifty years — and changed painting forever with them. His sfumato modelling dissolved the hard contours of the early Renaissance into breathing atmosphere, while The Last Supper reinvented narrative composition. Endlessly distracted by anatomy, engineering and water, he treated painting as science and science as art, leaving patrons exasperated and posterity in awe.",
  outside:"His notebooks — over 7,000 surviving pages written in mirror-image script — sketch helicopters, tanks, anatomy from some thirty dissections, and grocery lists. Vasari records that he bought caged birds at market simply to set them free, and contemporaries describe a charming, left-handed vegetarian dandy in rose-coloured tunics.",
  facts:["He wrote his notes right-to-left in mirror script, legible only with a looking glass.",
    "Salvator Mundi sold in 2017 for $450.3 million, the highest price ever paid for a painting.",
    "The Mona Lisa only became a global celebrity after it was stolen from the Louvre in 1911 — Picasso was briefly a suspect."] },

{ id:"michelangelo", name:"Michelangelo Buonarroti", years:"1475–1564", born:1475, died:1564,
  nation:"italy", eras:["16th-century"], movements:["high-renaissance","mannerism"],
  techniques:["fresco","tempera"], style:"renaissance",
  palette:["#2e4a62","#b06a4a","#d9b27c","#7a8e66","#e8dcc3"],
  tagline:"The sculptor who, under protest, painted heaven itself",
  works:[{t:"Sistine Chapel Ceiling",y:"1508–12"},{t:"The Last Judgment",y:"1536–41"},{t:"Doni Tondo",y:"c. 1507"},{t:"The Creation of Adam",y:"1511–12"}],
  life:"Born near Arezzo and raised in Florence, Michelangelo insisted to his dying day that he was a sculptor, not a painter. Irascible, devout and famously unwashed, he outlived all his great rivals, working until days before his death at eighty-eight — by then so revered that Italians simply called him Il Divino, the divine one.",
  career:"Bullied by Pope Julius II into frescoing the Sistine ceiling, he spent four years on scaffolding painting some 500 square metres of prophets and the famous touch of Adam — then returned decades later to fill the altar wall with the swirling, terrifying Last Judgment. His muscular figures and twisting poses became the grammar of Mannerism and the obsession of every artist who followed.",
  outside:"He wrote some 300 sonnets and madrigals, many of them love poems of startling tenderness, and ended his life as chief architect of St Peter's Basilica — refusing payment for it. Despite a miser's habits, he died one of the richest artists who had ever lived.",
  facts:["He wrote a comic poem complaining the Sistine ceiling had ruined his body: 'my beard turns up to heaven... I am bent like a Syrian bow.'",
    "When the Pope's master of ceremonies criticised the Last Judgment's nudes, Michelangelo painted him into hell with donkey ears.",
    "He carved the Vatican Pietà at 24 — and signed it in a fit of pride he said he always regretted."] },

{ id:"raphael", name:"Raphael", years:"1483–1520", born:1483, died:1520,
  nation:"italy", eras:["16th-century"], movements:["high-renaissance"],
  techniques:["fresco","oil-painting","tempera"], style:"renaissance",
  palette:["#7a1f2b","#1f3a5f","#d9b46a","#e9ddc8","#5b7a5e"],
  tagline:"Grace itself — the prince of painters, gone at thirty-seven",
  works:[{t:"The School of Athens",y:"1509–11"},{t:"Sistine Madonna",y:"1512"},{t:"La Fornarina",y:"c. 1518–19"}],
  life:"Son of the court painter of Urbino, orphaned at eleven, Raphael rose with uncanny speed and uncanny charm — contemporaries marvelled that so gifted a man could also be so likeable. He died in Rome on his thirty-seventh birthday, according to Vasari, and all of Rome mourned; he was buried, by his own request, in the Pantheon.",
  career:"Summoned by Pope Julius II at twenty-five, Raphael frescoed the papal apartments while Michelangelo painted the Sistine ceiling next door. The School of Athens — philosophy as a serene architectural cosmos — became the very emblem of the High Renaissance. Running a workshop of fifty assistants, he was painter, architect of St Peter's and superintendent of Roman antiquities at once.",
  outside:"Famously amorous, he kept his engagement to a cardinal's niece unconsummated for years while devoted to Margherita Luti, the baker's daughter known as La Fornarina, whose portrait he kept and whose name may be inked on her armband. Vasari blamed his early death on overindulgence in love.",
  facts:["In The School of Athens he painted Leonardo as Plato, brooding Michelangelo as Heraclitus, and himself peeking from the right edge.",
    "His tomb in the Pantheon reads: 'Here lies Raphael, by whom nature feared to be outdone while he lived.'",
    "His tapestry cartoons for the Sistine Chapel shaped European design for two centuries."] },

{ id:"titian", name:"Titian", years:"c. 1488–1576", born:1488, died:1576,
  nation:"italy", eras:["16th-century"], movements:["venetian-school","high-renaissance"],
  techniques:["oil-painting","glazing","impasto"], style:"renaissance",
  palette:["#7a2419","#c4541f","#e0a95e","#2b3a52","#efe1c4"],
  tagline:"Venice's emperor of colour, painter to actual emperors",
  works:[{t:"Assumption of the Virgin",y:"1516–18"},{t:"Venus of Urbino",y:"1538"},{t:"Bacchus and Ariadne",y:"1522–23"}],
  life:"Born Tiziano Vecellio in the Dolomite town of Pieve di Cadore, he came to Venice as a boy and ruled its painting for sixty years. Shrewd with money and honours alike, he lived in grand style entertaining poets and princes, and worked until the plague carried him off at nearly ninety.",
  career:"His thunderous Assumption made him Venice's official painter at thirty; Holy Roman Emperor Charles V made him court painter, knight and count — legend says the emperor once stooped to pick up Titian's dropped brush. His late works, painted with fingers as much as brushes in broken, smouldering colour, anticipate Rembrandt and even Impressionism by a century.",
  outside:"He ran a famous house and garden in Venice's Biri Grande, hosting the writer Aretino and architect Sansovino in a celebrated triumvirate of talent and gossip. A devoted father, he never fully recovered from the death of his favourite son Orazio, who died of plague in the same epidemic that killed him.",
  facts:["'Titian red' — the glowing auburn of his models' hair — is still a hairdresser's term.",
    "Charles V reportedly declared that no other hand would paint him.",
    "X-rays show he reworked canvases for years, turning them to the wall between campaigns."] },

{ id:"tintoretto", name:"Tintoretto", years:"1518–1594", born:1518, died:1594,
  nation:"italy", eras:["16th-century"], movements:["venetian-school","mannerism"],
  techniques:["oil-painting","chiaroscuro","alla-prima"], style:"baroque",
  palette:["#1c1a24","#5a2330","#c08a3e","#3e5570","#d8c8a8"],
  tagline:"Il Furioso — Venice's fastest, stormiest brush",
  works:[{t:"The Miracle of the Slave",y:"1548"},{t:"The Last Supper (San Giorgio)",y:"1592–94"},{t:"Paradise",y:"1588–92"}],
  life:"Jacopo Robusti, nicknamed Tintoretto — 'little dyer' — after his father's trade, barely left Venice in seventy-six years. Combative, pious and tireless, he married the daughter of a confraternity official and trained his children in the workshop; his daughter Marietta became a celebrated portraitist in her own right.",
  career:"Allegedly expelled from Titian's studio after days, he posted his ambition on his wall: 'Michelangelo's drawing and Titian's colour.' He won the Scuola di San Rocco commission by scandalously installing a finished painting while rivals submitted sketches, then spent twenty-five years filling the building — a Sistine Chapel of slashing light, plunging perspectives and paint applied at the speed of thought.",
  outside:"He loved music, played several instruments and reportedly rigged theatrical lighting and wax figurines in boxes to stage his compositions before painting them. He charged little or nothing for works in his beloved confraternity, treating the project as devotion rather than business.",
  facts:["His Paradise in the Doge's Palace, over 22 metres wide, is among the largest old-master canvases on Earth.",
    "Rivals joked he painted faster than others could look.",
    "He kept his nickname 'the little dyer' all his life — branding before branding existed."] },

{ id:"paolo-veronese", name:"Paolo Veronese", years:"1528–1588", born:1528, died:1588,
  nation:"italy", eras:["16th-century"], movements:["venetian-school"],
  techniques:["oil-painting","fresco","glazing"], style:"renaissance",
  palette:["#2e6e5e","#b03a48","#d9b958","#3b5a8a","#ece0c8"],
  tagline:"Painter of silver banquets — and a very cool head before the Inquisition",
  works:[{t:"The Wedding at Cana",y:"1563"},{t:"Feast in the House of Levi",y:"1573"},{t:"The Family of Darius before Alexander",y:"1565–67"}],
  life:"Born Paolo Caliari in Verona — hence Veronese — he settled in Venice in his twenties and became, with Titian and Tintoretto, the third pillar of its golden age. Even-tempered where Tintoretto was furious, he ran a serene family workshop with his brother and sons, who continued it after his death at sixty.",
  career:"Veronese painted Venice as it wished to see itself: colossal feasts in marble loggias, silks and silver, dwarfs, parrots and Germans drinking. The Wedding at Cana — now the largest painting in the Louvre, facing the Mona Lisa — crams over a hundred figures into a single shimmering banquet. His cool harmonies of silver, lemon and rose became a textbook for Rubens, Tiepolo and Delacroix.",
  outside:"Summoned by the Inquisition in 1573 to explain the 'buffoons, drunkards and Germans' in a Last Supper, he calmly defended a painter's poetic licence — then satisfied the tribunal by simply renaming the picture Feast in the House of Levi, changing not one brushstroke.",
  facts:["His Inquisition transcript survives — one of art history's great defences of creative freedom.",
    "The Wedding at Cana was looted by Napoleon and has stayed in Paris ever since.",
    "'Veronese green' is named for the deep green he loved."] },

{ id:"albrecht-durer", name:"Albrecht Dürer", years:"1471–1528", born:1471, died:1528,
  nation:"germany", eras:["16th-century"], movements:["northern-renaissance"],
  techniques:["woodblock","etching","watercolor","oil-painting"], style:"renaissance",
  palette:["#4a3b28","#86683f","#c7b287","#2f3d34","#ece4d2"],
  tagline:"The Renaissance arrives in the North — by printing press",
  works:[{t:"Melencolia I",y:"1514"},{t:"Young Hare",y:"1502"},{t:"Self-Portrait at 28",y:"1500"},{t:"Knight, Death and the Devil",y:"1513"}],
  life:"Son of a Nuremberg goldsmith, Dürer crossed the Alps twice to study Italian art and brought the Renaissance home in his saddlebags. Vain, brilliant and curious about everything, he painted himself at twenty-eight full-face like Christ — an astonishing claim for art's new dignity. He died at fifty-six, possibly from malaria caught while travelling to sketch a beached whale.",
  career:"Dürer made the print a major art form: his woodcuts and engravings — the Apocalypse, Melencolia I, the Rhinoceros — circulated through Europe like wildfire and made him the first artist with an international public in his own lifetime. His watercolours of a hare and a clump of turf treat humble nature with a reverence not seen again before the nineteenth century.",
  outside:"He wrote treatises on measurement, fortification and human proportion, corresponded with humanists like Erasmus, and kept travel diaries rich in expense accounts and wonder. His famous 'AD' monogram was so valuable he pursued copyists in court — one of history's first trademark disputes.",
  facts:["He engraved a rhinoceros in 1515 without ever seeing one; the image stayed in school books for 300 years.",
    "His legal action against the copyist Marcantonio Raimondi is an early landmark of intellectual property.",
    "The Young Hare is so fragile it is shown only a few months per decade."] },

{ id:"hans-holbein", name:"Hans Holbein the Younger", years:"c. 1497–1543", born:1497, died:1543,
  nation:"germany", eras:["16th-century"], movements:["northern-renaissance"],
  techniques:["oil-painting","tempera","glazing"], style:"renaissance",
  palette:["#143c34","#7a1f2b","#caa45c","#26343f","#e8ddc8"],
  tagline:"The cool eye of the Tudor court",
  works:[{t:"The Ambassadors",y:"1533"},{t:"Portrait of Henry VIII",y:"c. 1537"},{t:"Portrait of Erasmus",y:"1523"}],
  life:"Born in Augsburg into a family of painters, Holbein worked in Basel until the Reformation's iconoclasm dried up commissions. Armed with a letter from Erasmus to Thomas More — 'the arts are freezing here' — he moved to London, where he became King's Painter to Henry VIII and died of plague at about forty-five.",
  career:"Holbein's portraits are almost frightening in their precision: Erasmus at his desk, Thomas More in velvet, Henry VIII as a wall of menace. The Ambassadors hides a distorted skull that snaps into focus from the side — Renaissance virtuosity doubling as a memento mori. His designs for jewels, pageants and book illustrations made him a one-man Tudor design agency.",
  outside:"He navigated Europe's most dangerous court with a diplomat's discretion, leaving a wife and children in Basel whom he supported but rarely saw. His sketchbook portraits of the Tudor elite, mostly in coloured chalks, survive at Windsor as a who's-who of the age.",
  facts:["His flattering portrait of Anne of Cleves reportedly helped talk Henry VIII into a marriage he instantly regretted — Holbein, unusually, escaped blame.",
    "The skull in The Ambassadors only resolves when viewed at a steep angle — a built-in optical illusion.",
    "He designed everything from daggers to chimney pieces for the court."] },

{ id:"pieter-bruegel", name:"Pieter Bruegel the Elder", years:"c. 1525–1569", born:1525, died:1569,
  nation:"belgium", eras:["16th-century"], movements:["northern-renaissance"],
  techniques:["oil-painting","tempera"], style:"renaissance",
  palette:["#aeb9b4","#5b6e5a","#8a5a32","#32433f","#e8e3d3"],
  tagline:"Peasant weddings, proverb worlds and the first great snow in art",
  works:[{t:"Hunters in the Snow",y:"1565"},{t:"Netherlandish Proverbs",y:"1559"},{t:"The Tower of Babel",y:"1563"}],
  life:"Little is certain about Bruegel's origins; he emerges in Antwerp's painters' guild in 1551, travelled over the Alps to Italy — returning with mountains in his imagination rather than Roman statues — and settled in Brussels, where he married his teacher's daughter and died young, around forty-four.",
  career:"In barely forty surviving panels Bruegel built a complete world: seasons turning over village life, children's games catalogued by the hundred, proverbs literalised into absurdist theatre, and Babel rising like a doomed termite mound. He painted peasants without mockery or sentimentality at a time when they were considered comedy — and his Hunters in the Snow practically invented winter as a subject.",
  outside:"His friend the cartographer Ortelius eulogised him as 'the most perfect painter of his century.' An early biographer claims he disguised himself as a peasant to crash village weddings, earning the nickname 'Peasant Bruegel' — gossip, perhaps, but in the pictures it rings true.",
  facts:["He fathered a dynasty: sons Pieter the Younger and Jan 'Velvet' Brueghel kept the family firm going for a century.",
    "Netherlandish Proverbs illustrates over a hundred sayings in one village scene.",
    "On his deathbed he reportedly told his wife to burn drawings too biting to be safe."] },

{ id:"hieronymus-bosch", name:"Hieronymus Bosch", years:"c. 1450–1516", born:1450, died:1516,
  nation:"netherlands", eras:["15th-century","16th-century"], movements:["northern-renaissance"],
  techniques:["oil-painting","alla-prima"], style:"surreal",
  palette:["#26424e","#c4663a","#a7b06a","#5e3450","#e3d3a8"],
  tagline:"Hell's most inventive travel agent, five centuries early",
  works:[{t:"The Garden of Earthly Delights",y:"c. 1490–1510"},{t:"The Haywain Triptych",y:"c. 1516"},{t:"The Temptation of St Anthony",y:"c. 1501"}],
  life:"Jheronimus van Aken took his name from his hometown, 's-Hertogenbosch, which he apparently never left for long. A respected citizen and member of the conservative Brotherhood of Our Lady, he married a wealthy older woman and lived on the market square — outwardly the most ordinary man ever to imagine tree-bodied monsters and bird-headed demons.",
  career:"Across roughly twenty-five surviving works Bosch painted morality as hallucination: paradise sliding into orgy sliding into a hell of musical instruments turned torture devices. The Garden of Earthly Delights remains painting's most analysed dream. Philip II of Spain collected him obsessively, which is why the Prado, not the Netherlands, owns his masterpieces.",
  outside:"Almost nothing personal survives — no letters, no diaries, no scandals — which has made him a screen for five centuries of speculation: heretic, mystic, moralist, proto-surrealist. The Surrealists claimed him as their ancestor; Dalí called on him directly.",
  facts:["His hometown threw him a 500th-anniversary blockbuster in 2016 — borrowing back masterpieces although it owns none.",
    "A figure in his Hell plays music written on a sinner's buttocks; the 'butt song' has been transcribed and performed.",
    "He painted alla prima with unusually free, sketchy strokes for his era — restorers love him."] },

{ id:"el-greco", name:"El Greco", years:"1541–1614", born:1541, died:1614,
  nation:"greece", eras:["16th-century","17th-century"], movements:["mannerism"],
  techniques:["oil-painting","tempera","glazing"], style:"expressionist",
  palette:["#2b3a52","#7b8fb0","#bfc8d8","#5e2430","#cfa44e"],
  tagline:"The Greek of Toledo — flames for figures, storms for skies",
  works:[{t:"The Burial of the Count of Orgaz",y:"1586–88"},{t:"View of Toledo",y:"c. 1599"},{t:"The Opening of the Fifth Seal",y:"1608–14"}],
  life:"Doménikos Theotokópoulos trained as a Byzantine icon painter in Venetian Crete, absorbed Titian in Venice, irritated Rome — reportedly offering to repaint Michelangelo's Last Judgment 'with decency' — and finally found his stage in Toledo, Spain, where he lived grandly, litigated constantly, and signed every canvas in Greek letters until his death at seventy-three.",
  career:"Spain gave him freedom Italy never would: his saints stretched into flames, his colours turned phosphorescent, his skies churned like the end of the world. The Burial of the Count of Orgaz splits heaven and earth into two registers of equal reality. Dismissed for centuries as mad or astigmatic, he was resurrected by the moderns — Picasso's Demoiselles d'Avignon leans directly on his Fifth Seal.",
  outside:"He kept a library of Greek philosophy and Italian art theory, annotating Vasari with combative marginalia, and reportedly hired musicians to play while he dined. He never married his companion Jerónima, mother of his son Jorge Manuel, for reasons still unknown.",
  facts:["The 'astigmatism' theory of his elongations is optically debunked — distorted vision would distort his perception of the canvas too.",
    "He demanded — and litigated for — fees that scandalised Spanish patrons used to paying painters like carpenters.",
    "Cézanne, Picasso and the Expressionists all explicitly claimed him as an ancestor."] },

{ id:"sofonisba-anguissola", name:"Sofonisba Anguissola", years:"c. 1532–1625", born:1532, died:1625,
  nation:"italy", eras:["16th-century","17th-century"], movements:["high-renaissance","mannerism"],
  techniques:["oil-painting","glazing"], style:"renaissance",
  palette:["#3a2a2e","#8a4a3e","#caa481","#2f4a44","#e9dccb"],
  tagline:"The noblewoman who proved, at the Spanish court, what a woman's brush could do",
  works:[{t:"The Chess Game",y:"1555"},{t:"Self-Portrait at the Easel",y:"c. 1556"},{t:"Portrait of Philip II",y:"1565"}],
  life:"Born to minor nobility in Cremona, Sofonisba was one of six sisters educated like Renaissance princes — and the first woman painter to win international fame. She served fourteen years at the Spanish court, married twice (the second time to a sea captain she met on the voyage home), and lived past ninety, hosting young artists in Palermo as a living legend.",
  career:"Barred as a woman from studying anatomy or large religious commissions, she conquered the genre open to her: the portrait, charged with wit and inner life. Her Chess Game — three sisters mid-match, one grinning at the viewer — is among the first paintings of a genuinely informal moment. At Madrid she was court portraitist in all but title, her works long misattributed to male painters.",
  outside:"Michelangelo himself reviewed her drawings, challenging her to draw a crying boy — she sent back a sketch of her brother bitten by a crab, which he praised. In 1624 the young Anthony van Dyck visited and sketched the 92-year-old, noting her advice on lighting was sharper than any master's.",
  facts:["Van Dyck recorded her last art lesson to him in his Italian sketchbook — given when she was 92 and nearly blind.",
    "Several of her royal portraits hung for centuries under Titian's and Coello's names.",
    "Her success persuaded noble families across Italy to train their daughters — Lavinia Fontana followed directly."] },

{ id:"giuseppe-arcimboldo", name:"Giuseppe Arcimboldo", years:"1526–1593", born:1526, died:1593,
  nation:"italy", eras:["16th-century"], movements:["mannerism"],
  techniques:["oil-painting","glazing"], style:"naive",
  palette:["#6e8a3a","#c47a2e","#a83a2a","#d9c267","#4a5a30"],
  tagline:"Faces built from fruit — the emperor's favourite visual pun",
  works:[{t:"Vertumnus",y:"c. 1590"},{t:"The Four Seasons",y:"1563–73"},{t:"The Librarian",y:"c. 1566"}],
  life:"A Milanese painter of conventional church windows and frescoes, Arcimboldo moved to the Habsburg courts of Vienna and Prague, serving three emperors for twenty-five years as portraitist, festival designer and procurer of wonders for the imperial cabinet of curiosities. He returned to Milan laden with honours and died there at sixty-six.",
  career:"His composite heads — Spring assembled from blossoms, the Librarian from books, Emperor Rudolf II as the harvest god Vertumnus built entirely of produce — delighted a court obsessed with riddles and natural marvels. Read as flattering allegory then and as proto-Surrealism now, they were precision botany as much as joke: each fruit and flower is identifiable.",
  outside:"He doubled as the court's events designer, inventing costumes, tournaments and even a 'colour harpsichord' that allegedly matched tones to hues. After his death the style was forgotten for three centuries until Dalí and the Surrealists adopted him as a patron saint.",
  facts:["Rudolf II, rather than taking offence at being painted as a pile of vegetables, made him a Count Palatine.",
    "Some heads are reversible: his Vegetable Gardener becomes a bowl of vegetables upside-down.",
    "Almost no other painter copied him in his lifetime — the trick was considered inimitable."] },

{ id:"caravaggio", name:"Caravaggio", years:"1571–1610", born:1571, died:1610,
  nation:"italy", eras:["16th-century","17th-century"], movements:["baroque"],
  techniques:["oil-painting","tenebrism","chiaroscuro","alla-prima"], style:"baroque",
  palette:["#0e0c0a","#5e1f1a","#b06a32","#d9b27c","#3a2e22"],
  tagline:"Saints with dirty feet, painted by a man on the run",
  works:[{t:"The Calling of St Matthew",y:"1599–1600"},{t:"Judith Beheading Holofernes",y:"c. 1599"},{t:"David with the Head of Goliath",y:"c. 1610"},{t:"The Beheading of Saint John the Baptist",y:"1608"}],
  life:"Michelangelo Merisi from Caravaggio, near Milan, arrived in Rome penniless and left it a fugitive: in 1606 he killed Ranuccio Tomassoni in a duel over — depending on the source — a tennis wager, a woman, or both. Sentenced to death, he fled through Naples, Malta (knighted, then jailed, then escaped) and Sicily, dying of fever at thirty-eight while sailing toward a papal pardon.",
  career:"Caravaggio detonated European painting in a single decade: street kids as angels, pilgrims with filthy soles, biblical violence staged in cellar darkness under one brutal shaft of light. He painted directly from the model without preparatory drawings — none survive — and his tenebrism spawned imitators from Naples to Utrecht, the 'Caravaggisti', within years.",
  outside:"Police archives document his other career: sword-carrying, libellous poems, a waiter assaulted with an artichoke plate. He painted his own face onto Goliath's severed head — held by a pensive young David — and sent it, scholars believe, to Rome as a plea for mercy.",
  facts:["Roman police records mention him at least eleven times — the best-documented temper in art history.",
    "He used the same Roman courtesans as models for the Madonna, scandalising clergy.",
    "Not a single drawing by him is known: he composed with the loaded brush, incising guide-lines straight into wet paint."] },

{ id:"artemisia-gentileschi", name:"Artemisia Gentileschi", years:"1593–c. 1656", born:1593, died:1656,
  nation:"italy", eras:["17th-century"], movements:["baroque"],
  techniques:["oil-painting","tenebrism","chiaroscuro"], style:"baroque",
  palette:["#161210","#6e1f26","#c98a3e","#d9c49a","#324a3e"],
  tagline:"'I will show Your Lordship what a woman can do'",
  works:[{t:"Judith Slaying Holofernes",y:"c. 1614–20"},{t:"Self-Portrait as the Allegory of Painting",y:"1638–39"},{t:"Judith and her Maidservant",y:"c. 1625"}],
  life:"Daughter of the Caravaggesque painter Orazio Gentileschi, Artemisia was raped at seventeen by her tutor Agostino Tassi. At the 1612 trial she was tortured with thumbscrews to 'verify' her testimony — repeating 'it is true, it is true' as the cords tightened. She rebuilt her life in Florence, Naples, Venice and London, running her own workshop until her death around sixty-three.",
  career:"She took Caravaggio's darkness and gave it muscle and fury: her Judiths don't shrink from the beheading, they brace into it, sleeves rolled, blood arcing. The first woman admitted to Florence's Accademia del Disegno, she counted Galileo among her correspondents and the Medici, Philip IV and Charles I among her patrons — negotiating fees with the confidence her letters still radiate.",
  outside:"Her surviving letters are masterpieces of self-possession: 'You will find the spirit of Caesar in this soul of a woman,' she warned a slow-paying patron. In London she worked alongside her aging father on a royal ceiling — a reconciliation after decades of distance.",
  facts:["The Florence Accademia admitted her in 1616 — no woman had entered in its 53 years.",
    "Her Judith was hung in a dim Uffizi corridor for centuries, reportedly because grand dukes found it too disturbing.",
    "Her rediscovery since the 1970s has made her the most studied seventeenth-century woman painter."] }
);
