/* PIGMENT — artists 12/13 : European modernists — Kupka to Vasarely */
window.ARTISTS.push(
{ id:"burhan-dogancay", name:"Burhan Doğançay", years:"1929–2013", born:1929, died:2013,
  nation:"turkey", eras:["20th-century","21st-century"], movements:["contemporary-art","pop-art"],
  techniques:["acrylic-painting","collage","mixed-media"], style:"street",
  palette:["#2e50c4","#c4302a","#e8c43e","#8a8a8a","#e8e4d8"],
  tagline:"Half a century reading the writing on the wall",
  works:[{t:"Blue Symphony",y:"1987"},{t:"Ribbons series",y:"1972–89"},{t:"Walls of the World (photo archive)",y:"1975–2013"}],
  life:"Son of a painter-cartographer, Doğançay took a law degree in Ankara, played amateur football, earned an economics doctorate in Paris and entered the diplomatic service — then resigned a New York posting in 1964 to paint full-time. He worked between Manhattan and Turkey for five decades, dying in Istanbul at eighty-four.",
  career:"One subject, fifty years: the urban wall — peeling posters, graffiti, ripped edges and shadows, reconstructed in paint and collage. His Ribbons series turned torn paper into calligraphic shadows of astonishing elegance; Blue Symphony became, in 2009, the most expensive Turkish painting ever auctioned. Alongside ran the Walls of the World archive: 30,000 photographs of walls in 114 countries — sociology disguised as obsession.",
  outside:"His photographs and paintings were exhibited as conversation — the Pompidou and the Met collect both. Istanbul Modern gave him its first retrospective for a living Turkish artist in 2012, and his namesake museum in Beyoğlu was Turkey's first single-artist contemporary museum.",
  facts:["Blue Symphony's 2009 sale (about $1.7M) set the Turkish auction record.",
    "He documented the Berlin Wall before and after — walls falling being, after all, his genre.",
    "Fellow wall-obsessive Jacques Villeglé called him a brother-in-décollage across the Atlantic."] },

{ id:"kathe-kollwitz", name:"Käthe Kollwitz", years:"1867–1945", born:1867, died:1945,
  nation:"germany", eras:["19th-century","20th-century"], movements:["expressionism","realism"],
  techniques:["etching","lithography","woodblock"], style:"expressionist",
  palette:["#1d1a18","#5e5648","#a8a094","#8a2e26","#d9cdb8"],
  tagline:"Grief, printed — the mother of modern protest art",
  works:[{t:"The Weavers cycle",y:"1893–97"},{t:"Woman with Dead Child",y:"1903"},{t:"The Grieving Parents",y:"1932"}],
  life:"Born in Königsberg into a family of radical preachers, Kollwitz married a doctor serving Berlin's poor and drew the patients in his waiting room for fifty years. Her younger son Peter died at Ypres in 1914; her grandson Peter in Russia in 1942. Expelled from the Prussian Academy by the Nazis — she had been its first woman member — she died two weeks before the war's end.",
  career:"She chose printmaking deliberately — cheap, multiple, democratic — and made the era's defining images of hunger, revolt and mourning: the Weavers cycle, the Peasants' War etchings, the woodcut war portfolios, the late lithograph 'Seed corn must not be ground'. Almost alone among her contemporaries she made the grieving mother, not the soldier, war's central figure.",
  outside:"Her sculpted Grieving Parents kneel over the Belgian war cemetery where Peter lies — eighteen years in the making. An enlarged cast of her Pietà now sits at Berlin's Neue Wache as Germany's central war memorial; her diaries are among the great artist documents of conscience.",
  facts:["Both a son and a grandson named Peter died in the two world wars — the work's wound, twice over.",
    "The Nazis banned her exhibitions but dared not arrest her — she was too beloved.",
    "Germany's main memorial to victims of war and tyranny is, in effect, a Kollwitz."] },

{ id:"franz-marc", name:"Franz Marc", years:"1880–1916", born:1880, died:1916,
  nation:"germany", eras:["20th-century"], movements:["expressionism","der-blaue-reiter"],
  techniques:["oil-painting","woodblock"], style:"fauvist",
  palette:["#2e50c4","#e8c43e","#c4302a","#2e8a5e","#e8dcc4"],
  tagline:"Blue horses, golden cows — animals as the souls we lost",
  works:[{t:"Blue Horse I",y:"1911"},{t:"The Fate of the Animals",y:"1913"},{t:"The Tower of Blue Horses",y:"1913 (lost)"}],
  life:"A Munich philosophy student turned painter, Marc co-founded Der Blaue Reiter with Kandinsky in 1911, convinced animals saw the world more purely than corrupted mankind. He volunteered in 1914, was assigned to camouflage work — painting tarpaulins 'from Manet to Kandinsky' — and was killed by a shell at Verdun in 1916, at thirty-six, days after being listed for recall as a national treasure.",
  career:"His colour was theology: blue for the spiritual and male, yellow for gentle joy, red for the violence of matter — deer, foxes and above all horses painted as creatures of pure feeling. The Fate of the Animals, a forest shattering over terrified creatures, carried the inscription 'And all being is flaming agony'; from the trenches he wrote that it was 'like a premonition of this war'.",
  outside:"His war letters and aphorisms became a bestseller of mourning; Klee and Kandinsky never fully recovered the movement without him. The Tower of Blue Horses, confiscated as 'degenerate', vanished after 1945 — German museums still keep a symbolic empty hook for it.",
  facts:["The Tower of Blue Horses is the most famous missing painting of the 20th century.",
    "He painted his canvases' backs with colour-theory notes to Kandinsky.",
    "Verdun killed him during reassignment paperwork meant to save artists of national importance."] },

{ id:"fernand-leger", name:"Fernand Léger", years:"1881–1955", born:1881, died:1955,
  nation:"france", eras:["20th-century"], movements:["cubism"],
  techniques:["oil-painting","flat-color"], style:"cubist",
  palette:["#c4302a","#2e50c4","#f0c82e","#1a1a1a","#e8e4d8"],
  tagline:"Cubism with engine oil — the machine age, painted in primary gears",
  works:[{t:"The City",y:"1919"},{t:"Three Women (Le Grand Déjeuner)",y:"1921"},{t:"The Builders",y:"1950"}],
  life:"A Normandy cattle-merchant's son and architectural draughtsman, Léger reached Cubism via Cézanne — critics mocked his cylinders as 'tubism'. Two years at the Verdun front rewired him: 'the breech of a 75 in full sunlight taught me more than all the museums.' He taught, filmed, muralled and militated until his death in 1955.",
  career:"The City made modern life — billboards, scaffolds, traffic — painting's subject at mural scale; his figures became magnificent machine-parts with souls, workers and acrobats assembled like engines in primary colours. His Ballet Mécanique (1924) is experimental cinema's founding loop; late cycles like The Builders aimed squarely at the people his politics served.",
  outside:"A wartime exile professorship at Yale and travels through America fed his love of 'bad taste' vitality; back home, a communist, he designed church mosaics at Assy and windows at Audincourt without blinking at the contradiction. The Léger museum at Biot wears a façade-sized mosaic like a flag.",
  facts:["He survived a Verdun gas attack; the front's gun-metal gleam became a palette.",
    "Ballet Mécanique was scored for player pianos, sirens and aircraft propellers.",
    "He taught a generation of Americans — including, briefly, a young Louise Bourgeois."] },

{ id:"frantisek-kupka", name:"František Kupka", years:"1871–1957", born:1871, died:1957,
  nation:"czechia", eras:["19th-century","20th-century"], movements:["orphism","abstract-art"],
  techniques:["oil-painting","glazing"], style:"abstract",
  palette:["#c4302a","#2e50c4","#e8c43e","#5e3450","#f4f1e8"],
  tagline:"Fugues in colour — abstraction's quiet first chair",
  works:[{t:"Amorpha: Fugue in Two Colors",y:"1912"},{t:"Disks of Newton",y:"1912"},{t:"Vertical Planes III",y:"1912–13"}],
  life:"Born in eastern Bohemia, apprenticed to a saddler, Kupka paid for art school by working as a spiritualist medium — séances that left him lifelong convinced of unseen orders. Settled outside Paris from 1896, he drew anarchist satire for the press, volunteered at fifty... at forty-three for the Czech legion in WWI, and died at Puteaux in 1957, recognised at the very last.",
  career:"At the 1912 Salon d'Automne his Amorpha: Fugue in Two Colors — red and blue arcs orbiting on white, depicting precisely nothing — became one of the first fully abstract paintings ever publicly exhibited, before Kandinsky's or Malevich's hung anywhere. Music gave him the model: chromatic fugues, Newton's disks, vertical planes like organ chords. He rejected even the 'Orphist' label Apollinaire offered — system-builders, he felt, painted; he composed.",
  outside:"His illustrated anarchist and satirical work (L'Assiette au Beurre) fed him for years; his treatise 'Creation in the Plastic Arts' codified the mysticism. The Czech state pensioned him as a legionnaire-professor; Paris finally gave him a joint retrospective with Mucha's generation only after WWII.",
  facts:["He worked as a medium in Prague and Vienna — and never entirely stopped believing the visions.",
    "Amorpha was lampooned in newspapers as wallpaper; it now anchors Prague's National Gallery.",
    "A 2018 Paris retrospective drew the headline 'the first abstract painter' — a century late, arguably accurate."] },

{ id:"sonia-delaunay", name:"Sonia Delaunay", years:"1885–1979", born:1885, died:1979,
  nation:"france", eras:["20th-century"], movements:["orphism","abstract-art"],
  techniques:["oil-painting","flat-color","collage"], style:"abstract",
  palette:["#c4302a","#2e50c4","#f0c82e","#2e8a5e","#1d1a20"],
  tagline:"Simultaneous colour — from a baby quilt to the whole modern world",
  works:[{t:"Bal Bullier",y:"1913"},{t:"Electric Prisms",y:"1914"},{t:"Rythme Couleur series",y:"1960s"}],
  life:"Born Sara Stern in Ukraine and raised by a wealthy St Petersburg uncle, Sonia reached Paris at twenty, married the dealer Wilhelm Uhde (amicably, for residency), then the painter Robert Delaunay — partner in life and in 'simultaneism' for thirty years. She carried their colour theory through fashion, textiles and decades of widowhood, dying at ninety-four.",
  career:"A patchwork quilt sewn for her son in 1911 — pure colour blocks, no image — preceded the movement it predicted; with Robert she built Orphism's spinning chromatic discs, then took them dancing: simultaneous dresses, Ballets Russes costumes, painted Citroëns, the poem-scarf, an entire boutique. In 1964 she became the first living woman artist given a retrospective at the Louvre.",
  outside:"Her Casa Sonia boutiques dressed Nancy Cunard and Gloria Swanson; Diaghilev commissioned, Tzara collaborated, and son Charles Delaunay grew up to co-found jazz's Hot Club de France and write its discographies — rhythm running in the family.",
  facts:["The 1911 quilt hangs in Paris's Musée National d'Art Moderne — modernism's most famous baby blanket.",
    "She and Robert painted the Paris airshow pavilion and a Citroën B12 — art on wheels, 1925.",
    "Louvre retrospective, 1964: first living woman artist so honoured."] },

{ id:"otto-dix", name:"Otto Dix", years:"1891–1969", born:1891, died:1969,
  nation:"germany", eras:["20th-century"], movements:["new-objectivity","expressionism"],
  techniques:["oil-painting","etching","tempera"], style:"expressionist",
  palette:["#3e4a52","#8a3a32","#caa45c","#1d1c22","#d9cdb8"],
  tagline:"Weimar's cold mirror — the war painted by a machine-gunner who survived it",
  works:[{t:"The War (Der Krieg) triptych",y:"1929–32"},{t:"Metropolis triptych",y:"1927–28"},{t:"Portrait of the Journalist Sylvia von Harden",y:"1926"}],
  life:"A Gera foundry worker's son, Dix volunteered in 1914 and served as a machine-gunner at the Somme — nightmares of crawling through ruined houses pursued him for decades. Weimar Berlin made him its sharpest portraitist; the Nazis made him the Degenerate Art show's star exhibit, sacked him and briefly jailed him. He painted on Lake Constance in 'inner exile' until his death in 1969.",
  career:"His Der Krieg etchings — gas, craters, the dead in wire — stand with Goya's Disasters as war reporting from inside the nightmare; the War triptych reframes it as a Grünewald altarpiece. In between: Weimar's profiteers, war cripples, dancers and the monocled journalist Sylvia von Harden, painted with old-master tempera precision and a coroner's tenderness.",
  outside:"He answered every why with 'I had to see it all myself' — art as exorcism, not politics, he claimed, while politics burned his canvases. Conscripted into the Volkssturm at fifty-three, he ended WWII a French prisoner painting Madonnas for the camp chapel.",
  facts:["The Nazis hung his work under mocking labels in 1937 — then destroyed several major paintings, including War Cripples.",
    "He was briefly arrested in 1939 over the Bürgerbräukeller bomb plot — guilt by aura.",
    "Sylvia von Harden outlived the painting's fame to confirm: yes, the rolled stockings were accurate."] },

{ id:"max-beckmann", name:"Max Beckmann", years:"1884–1950", born:1884, died:1950,
  nation:"germany", eras:["20th-century"], movements:["expressionism","new-objectivity"],
  techniques:["oil-painting","lithography"], style:"expressionist",
  palette:["#1d1c22","#c4302a","#e8c43e","#2e5e8a","#e8dcc4"],
  tagline:"Triptychs for a century in flames — the self-portraitist in the tuxedo",
  works:[{t:"Departure",y:"1932–35"},{t:"Self-Portrait in Tuxedo",y:"1927"},{t:"The Night",y:"1918–19"}],
  life:"A Leipzig merchant's son who measured himself against Rembrandt early, Beckmann broke down as a WWI medical orderly and rebuilt his art from the rubble. The day after Hitler's 1937 'degenerate art' radio speech he left Germany forever — ten years in an Amsterdam attic, then America. He died of a heart attack in 1950, mid-Manhattan, walking to see his own painting hang at the Met.",
  career:"He refused both abstraction and -isms: 'I paint the visible world plus the inner experience.' The Night's torture chamber announced Weimar's nerves; the nine great triptychs, beginning with Departure, staged exile, cabaret and myth like medieval altars rebuilt for the age of passports. His sixty-plus self-portraits — clown, king, sailor, exile in a bar — are German art's great autobiography.",
  outside:"In Amsterdam he painted through the occupation a flight of stairs from deportation routes; his diaries record cigars, despair and discipline in equal measure. American students at Washington University found the master spoke aphorisms: 'If you wish to get hold of the invisible, you must penetrate as deeply as possible into the visible.'",
  facts:["He died en route to view his Self-Portrait in Blue Jacket at the Metropolitan Museum.",
    "Departure was smuggled out labelled 'Scenes from Shakespeare's Tempest'.",
    "Over 500 of his works were seized from German museums in 1937."] },

{ id:"kurt-schwitters", name:"Kurt Schwitters", years:"1887–1948", born:1887, died:1948,
  nation:"germany", eras:["20th-century"], movements:["dada"],
  techniques:["collage","mixed-media"], style:"cubist",
  palette:["#8a6e4a","#3e4a5e","#c4302a","#d9cdb4","#1d1a16"],
  tagline:"Merz — a one-man movement built from tram tickets",
  works:[{t:"Merzbild 1A (The Psychiatrist)",y:"1919"},{t:"The Merzbau",y:"1923–37 (destroyed)"},{t:"Ursonate",y:"1922–32"}],
  life:"A respectable Hanover landlord's son, Schwitters invented 'Merz' — his private Dada, named from a torn 'Kommerz' scrap — after Berlin's Dadaists rejected him as too bourgeois. Fleeing the Gestapo via Norway to Britain (and internment on the Isle of Man), he died in Kendal in 1948, one day after receiving British citizenship.",
  career:"His collages composed bus tickets, buttons and broken wood into chamber music; his Merzbau grew through his Hanover house for fourteen years as a walk-in grotto of plaster and memory — destroyed by a 1943 air raid, twice restarted in exile, never finished. The Ursonate, a forty-minute sonata of pure phonemes, stands at sound poetry's summit.",
  outside:"Interned on the Isle of Man, he charmed fellow refugees with readings and sculpted with leftover porridge when materials ran out. He supported his last years painting conventional Lake District portraits and landscapes — Merz by day, rent by evening.",
  facts:["British citizenship arrived January 7, 1948; he died January 8.",
    "The porridge sculptures reportedly grew mould in interesting colours — he approved.",
    "A barn wall from his final, unfinished English Merzbau is preserved at Newcastle University."] },

{ id:"hannah-hoch", name:"Hannah Höch", years:"1889–1978", born:1889, died:1978,
  nation:"germany", eras:["20th-century"], movements:["dada"],
  techniques:["photomontage","collage","watercolor"], style:"cubist",
  palette:["#1a1a1a","#c4302a","#8a9bb0","#e8e0d0","#caa43e"],
  tagline:"Cut with the kitchen knife — Berlin Dada's only woman, and its sharpest blade",
  works:[{t:"Cut with the Kitchen Knife Dada through the Last Weimar Beer-Belly Cultural Epoch of Germany",y:"1919–20"},{t:"From an Ethnographic Museum series",y:"1924–34"},{t:"The Beautiful Girl",y:"1920"}],
  life:"Trained in Berlin's applied arts schools, Höch worked a decade at the Ullstein press empire designing handicraft patterns — and quietly pocketing the photo archives that became her ammunition. Berlin Dada's male in-crowd grudgingly admitted her ('a good girl', sneered one, who then needed her sandwiches and her artworks). She survived the Third Reich hiding in a garden house outside Berlin, dying at eighty-eight.",
  career:"Her giant photomontage Cut with the Kitchen Knife shredded Weimar's generals, dadaists and dancers into one whirling indictment — the medium's founding masterpiece. The Ethnographic Museum series spliced mass-media women with museum artefacts, dissecting the 'New Woman' myth and Europe's exotic gaze decades before the terms existed.",
  outside:"Her garden refuge in Heiligensee concealed a banned art collection through the war — her own and her friends'. Rediscovered by feminist art history in the 1970s, she lived just long enough to watch the textbooks correct themselves.",
  facts:["Raoul Hausmann claimed photomontage's invention; the surviving masterpieces are mostly hers.",
    "Her Ullstein day job — embroidery patterns 'for the German woman' — funded the montages that mocked the genre.",
    "The Gestapo classified her as a 'cultural bolshevist'; the garden house never gave her up."] },

{ id:"leonora-carrington", name:"Leonora Carrington", years:"1917–2011", born:1917, died:2011,
  nation:"mexico", eras:["20th-century","21st-century"], movements:["surrealism"],
  techniques:["oil-painting","tempera","glazing"], style:"surreal",
  palette:["#2e4a3e","#d9a83e","#8a3a4e","#3e4a6e","#e8d9b4"],
  tagline:"The runaway debutante who out-dreamed the Surrealists",
  works:[{t:"Self-Portrait (Inn of the Dawn Horse)",y:"1937–38"},{t:"The Giantess",y:"c. 1947"},{t:"And Then We Saw the Daughter of the Minotaur",y:"1953"}],
  life:"Born to a textile-fortune family in Lancashire and expelled from two convent schools, Carrington fled her debutante season for Max Ernst at twenty. His wartime internment broke her; institutionalised in a Spanish asylum (recorded in her memoir Down Below), she escaped via a marriage of convenience to a Mexican diplomat — and made Mexico City home for seventy years, dying at ninety-four as its beloved 'última surrealista'.",
  career:"Her paintings are fairy tales with teeth: white horses, hyenas at the table, alchemical kitchens where giantesses shelter geese — myth cooked from Celtic nursery lore, the Kabbalah and Mexican magic. Where male Surrealists painted muses, she painted female power at work. Her novel The Hearing Trumpet — a 92-year-old heroine storms a sinister retirement home — is Surrealism's funniest book.",
  outside:"With Remedios Varo she formed history's great witchy friendship: shared kitchens, invented recipes, pranks and cosmologies. She co-founded Mexico's women's liberation movement in the 1970s and refused, charmingly and absolutely, to explain a single picture.",
  facts:["Asked to explain her paintings: 'I have no time for other people's interpretations — or my own.'",
    "Her Self-Portrait rides a rocking-horse's escape into a wild mare — biography in one image.",
    "She turned down a London debutante presentation at court; the hyena in her story 'The Debutante' attended instead."] },

{ id:"remedios-varo", name:"Remedios Varo", years:"1908–1963", born:1908, died:1963,
  nation:"spain", eras:["20th-century"], movements:["surrealism"],
  techniques:["oil-painting","glazing","tempera"], style:"surreal",
  palette:["#8a6e3a","#3e4a6e","#d9a83e","#2e4a3e","#e8d9b4"],
  tagline:"Alchemy in the kitchen — clockwork pilgrims grinding starlight",
  works:[{t:"Embroidering the Earth's Mantle",y:"1961"},{t:"Creation of the Birds",y:"1957"},{t:"Papilla Estelar (Celestial Pablum)",y:"1958"}],
  life:"Daughter of an Andalusian hydraulic engineer who taught her technical drawing — the precision never left — Varo passed through Madrid's academy (Dalí's cohort), anarchist Barcelona and Surrealist Paris with the poet Benjamin Péret, fleeing to Mexico City in 1941. There, beside Leonora Carrington, she built her mature decade and died of a heart attack at fifty-four, at the height of her powers.",
  career:"Her small panels are machines of the soul, painted with miniaturist exactness: an owl-woman distilling birds from violin-light, towers where girls embroider the world into being, a moon fed porridge of ground stars. Science, alchemy and feminine interiority run on the same gears. Mexico City's crowds at her retrospectives broke museum records; the auction market now treats her like the old master she secretly was.",
  outside:"She and Carrington wrote joint dream-recipes and absurdist letters mailed to strangers picked from the phone book — Surrealism as municipal prank. Years of commercial work for the pharmaceutical firm Bayer trained the uncanny precision her cosmologies demanded.",
  facts:["Embroidering the Earth's Mantle anchored a record-shattering 2021 auction — and Pynchon described it lovingly in The Crying of Lot 49.",
    "Her father had her copy his engineering blueprints as a child; every tower she painted thanks him.",
    "André Breton listed her among Surrealism's essential painters — one of few women so named while alive."] },

{ id:"hans-hartung", name:"Hans Hartung", years:"1904–1989", born:1904, died:1989,
  nation:"germany", eras:["20th-century"], movements:["art-informel","abstract-art"],
  techniques:["oil-painting","gestural-abstraction","spray-paint","acrylic-painting"], style:"gestural",
  palette:["#1d1c22","#3e5570","#caa45c","#8a2634","#e8e0d0"],
  tagline:"Lightning, archived — gesture at the speed of a nervous system",
  works:[{t:"T1935-1",y:"1935"},{t:"T1956-9",y:"1956"},{t:"Late sprayed canvases (T1989 series)",y:"1989"}],
  life:"A Leipzig doctor's son who as a boy filled 'lightning notebooks', sketching storms before the thunder arrived, Hartung fled Nazi Germany, joined the French Foreign Legion under a false name, and lost a leg at Belfort in 1944. Naturalised French and slowly canonised — Venice Biennale Grand Prize, 1960 — he painted until weeks before his death at Antibes in 1989, aged eighty-five.",
  career:"His black calligraphic bundles on luminous grounds — catalogued with cool T-numbers, 'T' for toile — made him Art Informel's defining stroke: spontaneity, he confessed late, often rehearsed in small studies then enlarged with a craftsman's calm, a scandal of honesty his admirers forgave. In his eighties, wheelchair-bound, he attacked canvases with garden sprayers, sulfateuses and olive branches — a last decade as radical as anyone's first.",
  outside:"He married the Norwegian painter Anna-Eva Bergman twice — 1929 and again 1957 — their twinned studios at Antibes now a joint foundation. The teenage lightning notebooks survive: the whole career, pre-drawn by weather.",
  facts:["He lost his right leg as a Foreign Legion volunteer fighting the country of his birth.",
    "Late works were sprayed from a wheelchair using garden equipment — assistants rotated the canvases like compass dials.",
    "His storm-chasing childhood sketchbooks are displayed beside the late spray paintings: same hand, seventy years apart."] },

{ id:"victor-vasarely", name:"Victor Vasarely", years:"1906–1997", born:1906, died:1997,
  nation:"hungary", eras:["20th-century"], movements:["op-art","abstract-art"],
  techniques:["acrylic-painting","flat-color","silkscreen"], style:"geometric",
  palette:["#1a1a1a","#f4f1e8","#2e50c4","#e0427a","#f0c82e"],
  tagline:"The grandfather of Op — grids that breathe, art for everyone",
  works:[{t:"Zebra",y:"1937"},{t:"Vega-Nor",y:"1969"},{t:"Alphabet Plastique",y:"1960s"}],
  life:"Born in Pécs, Hungary, Vasarely abandoned medical studies for Budapest's 'Mühely', the local Bauhaus, then built a Paris career in advertising graphics whose optical tricks ripened, by the 1950s, into a complete art. Patriarch of a movement, a foundation and a familial workshop (son Yvaral painted alongside), he died in Paris at ninety.",
  career:"Zebra (1937) — two beasts woven from warping stripes — is op art's commonly cited big bang; the Vega series bulged checkerboard grids into spheres that swell off the wall. Time magazine's 1964 coinage 'op art' crowned him; the 1965 MoMA show The Responsive Eye made the style a craze that devoured fashion and album sleeves. His 'plastic alphabet' of permutable units aimed at art as programmable, reproducible, democratic — pixels before pixels.",
  outside:"He insisted on multiples and affordable editions — 'art for all' was doctrine, not marketing — and built foundation buildings at Gordes and Aix-en-Provence, the latter a hexagon-celled mothership of monumental integrations. In 1972 he restyled the Renault diamond logo; France drove behind an op artwork for decades.",
  facts:["The Renault logo (1972, with son Yvaral) may be the most-viewed artwork in French history.",
    "David Bowie's Space Oddity LP and countless 1960s sleeves borrowed his vibrations.",
    "His Aix foundation's façade alternates 87 aluminium circles and squares — a building wearing its own painting."] },

{ id:"grant-wood", name:"Grant Wood", years:"1891–1942", born:1891, died:1942,
  nation:"usa", eras:["20th-century"], movements:["regionalism"],
  techniques:["oil-painting","glazing"], style:"naive",
  palette:["#7a9a5e","#d9c890","#8a5e3a","#3e5238","#e8e0c8"],
  tagline:"American Gothic — the most parodied painting on Earth",
  works:[{t:"American Gothic",y:"1930"},{t:"Stone City, Iowa",y:"1930"},{t:"Daughters of Revolution",y:"1932"}],
  life:"An Iowa farm boy who lost his stern Quaker father at ten, Wood trained as a metalworker, taught school, and made four trips to Europe that ended, paradoxically, in conversion to home: 'I had to go to France to appreciate Iowa.' He led the Regionalist movement from Cedar Rapids and Iowa City until cancer killed him the night before his fifty-first birthday.",
  career:"American Gothic — his sister Nan and his dentist posed before a carpenter-Gothic cottage window — became the national mirror: read as satire in Depression-era cities, as homage on the farms, and as both forever after. Flemish primitives taught him the lacquered finish; his rolling, quilted Iowa landscapes are Eden drawn by a sign-painter angel.",
  outside:"He ran the Stone City art colony from ice wagons painted with murals, wore overalls as a uniform-manifesto, and feuded gently with coastal critics who called Regionalism isolationist. Daughters of Revolution — three smug patriots before Washington Crossing the Delaware — was his driest revenge on his hometown's gatekeepers.",
  facts:["The American Gothic models never posed together; dentist and sister met mostly in the painting.",
    "The actual Eldon, Iowa cottage still stands; visitors queue with pitchforks provided by the visitor centre.",
    "He painted Washington Crossing the Delaware's parody using the DAR ladies after they criticised his Memorial Window — petty, perfect."] }
);
