/* PIGMENT artists — part 16 (atlas widening: Utamaro, Ensor, Hodler, Church) */
window.ARTISTS = (window.ARTISTS || []).concat([

{ id:"kitagawa-utamaro", name:"Kitagawa Utamaro", years:"c. 1753–1806", born:1753, died:1806,
  nation:"japan", eras:["18th-century","19th-century"], movements:["ukiyo-e"],
  techniques:["woodblock"], style:"ukiyoe",
  palette:["#c9b8a0","#8a3a3e","#1d1c22","#e8d9c0","#5e6e8a"],
  tagline:"The floating world's great portraitist of women",
  works:[{t:"Three Beauties of the Present Day",y:"c. 1793"},{t:"Ten Studies in Female Physiognomy",y:"c. 1792–93"},{t:"Woman Playing a Poppin",y:"c. 1790"},{t:"Flowers of Edo: Young Woman with Samisen",y:"c. 1800"}],
  life:"Almost nothing is certain about his origins — birthplace disputed, family unknown — until he surfaces in Edo as a pupil of Toriyama Sekien and, decisively, as the house artist of the brilliant publisher Tsutaya Jūzaburō, above whose shop he lived. In 1804 the shogunate punished him with fifty days in manacles over prints depicting the warlord Hideyoshi's private life; by most accounts the humiliation broke him. He died two years later.",
  career:"Utamaro turned the courtesans, waitresses and teahouse beauties of Edo into the most refined portraiture of the floating world — inventing the ōkubi-e 'large head' close-up, setting faces against shimmering mica grounds, and finding individual psychology inside an idealized type. His nature studies (the exquisite insect and shell picture-books) show the same precision aimed at moths and grasshoppers.",
  outside:"He was, by the standards of ukiyo-e artists, a celebrity — his name traded on by imitators so aggressively that publishers stamped 'the genuine Utamaro' on prints. He reportedly lived inside the pleasure quarters he depicted, less an observer than a resident.",
  facts:["The 1804 manacling — fifty days in handcuffs for prints about Hideyoshi — is one of art history's starkest censorship cases.",
    "His ōkubi-e 'large head' portraits were the close-up centuries before cinema claimed the idea.",
    "Edmond de Goncourt's 1891 monograph made him Japonisme's favorite painter; Cassatt's color prints answer him directly.",
    "Mica dust mixed into the background ink makes his best prints literally shimmer in raking light."] },

{ id:"james-ensor", name:"James Ensor", years:"1860–1949", born:1860, died:1949,
  nation:"belgium", eras:["19th-century","20th-century"], movements:["expressionism","symbolism"],
  techniques:["oil-painting","etching"], style:"expressionist",
  palette:["#e8dcc8","#c23a3a","#3e7a8a","#e8b43a","#4a3a4e"],
  tagline:"Masks, skeletons, and Christ stuck in traffic",
  works:[{t:"Christ's Entry into Brussels in 1889",y:"1888"},{t:"The Intrigue",y:"1890"},{t:"Skeletons Fighting over a Pickled Herring",y:"1891"},{t:"Self-Portrait with Masks",y:"1899"}],
  life:"Born in Ostend above his family's souvenir shop — carnival masks, seashells, chinoiserie — and he essentially never left: eighty-nine years in one seaside town, most of them in rooms above the masks that colonized his art. His English father drank himself to an early death; his formidable mother and aunt ran the shop and, in their way, the painter.",
  career:"He co-founded the Brussels avant-garde group Les XX — which then rejected his masterpiece: Christ's Entry into Brussels in 1889, a four-metre carnival mob swallowing a tiny Christ, stayed rolled in his attic studio for decades. His masks, skeletons and jeering crowds anticipated Expressionism by a generation; when fame finally arrived he was made a baron by the Belgian king, long after the radical years were over.",
  outside:"He played the harmonium daily and composed a ballet, La Gamme d'Amour; visitors to the old baron found him performing it among the masks. He painted little of consequence in his last three decades and enjoyed the irony immensely.",
  facts:["Christ's Entry into Brussels in 1889 hung in his own studio for around forty years before the world caught up; it now anchors the Getty.",
    "His own avant-garde group, Les XX, voted to reject the painting — and nearly expelled its maker.",
    "The family shop's carnival masks became his life's cast: he painted crowds as masks and masks as crowds.",
    "Ennobled as a baron in 1929 — the anarchist of Ostend ended as official national treasure."] },

{ id:"ferdinand-hodler", name:"Ferdinand Hodler", years:"1853–1918", born:1853, died:1918,
  nation:"switzerland", eras:["19th-century","20th-century"], movements:["symbolism","art-nouveau"],
  techniques:["oil-painting","flat-color"], style:"ornament",
  palette:["#7da8c9","#dce8f0","#8a9a5e","#c9a45c","#3e4a5e"],
  tagline:"Parallel lives, painted in rhythm",
  works:[{t:"Night",y:"1889–90"},{t:"The Chosen One",y:"1893–94"},{t:"Lake Thun with Symmetric Reflection",y:"1905"},{t:"The Woodcutter",y:"1910"}],
  life:"Born into Bern poverty, he buried his entire family — father, mother, all five siblings — mostly to tuberculosis before he reached middle age: 'there was always a corpse in the house,' he said, and death walked through his art accordingly. Apprenticed to a painter of tourist views, he walked to Geneva at eighteen and stayed.",
  career:"He called his method Parallelism: figures repeated in rhythmic symmetry like a ritual frieze, mountains doubled in mirror-still lakes — order as a spiritual argument. Night, with its black-shrouded figure of death crouched on a sleeper, was banned from Geneva's 1891 salon by the mayor and promptly celebrated in Paris. The 1904 Vienna Secession retrospective made him a European force; Klimt's generation took notes.",
  outside:"Between 1914 and 1915 he recorded his dying companion Valentine Godé-Darel in a series of unflinching canvases — from illness to deathbed to the empty horizon of Lake Geneva — perhaps the most harrowing sustained document of dying in Western painting. He followed her three years later, painting the lake to the end.",
  facts:["Night was banned by Geneva's mayor as obscene, then triumphed in Paris with Puvis de Chavannes leading the applause.",
    "His paintings appeared on Swiss banknotes — the woodcutter and the mower swung their tools on the 50- and 100-franc notes for decades.",
    "The Valentine Godé-Darel cycle tracks a single human death across dozens of canvases; museums still hang it with warnings.",
    "He painted the lakes of Geneva and Thun over a hundred times, flattening them toward pure horizontal abstraction."] },

{ id:"frederic-edwin-church", name:"Frederic Edwin Church", years:"1826–1900", born:1826, died:1900,
  nation:"usa", eras:["19th-century"], movements:["hudson-river-school","romanticism"],
  techniques:["oil-painting","glazing"], style:"romantic",
  palette:["#e8944a","#7da8c9","#3e5e40","#d9c9a0","#5e3a2a"],
  tagline:"The showman of the sublime",
  works:[{t:"Niagara",y:"1857"},{t:"The Heart of the Andes",y:"1859"},{t:"The Icebergs",y:"1861"},{t:"Cotopaxi",y:"1862"},{t:"Aurora Borealis",y:"1865"}],
  life:"Hartford money bought him the only apprenticeship Thomas Cole ever granted, and Alexander von Humboldt's 'Cosmos' gave him a mission: paint the whole planet as connected spectacle. He chased it in person — twice up the Andes, north to iceberg waters off Newfoundland, later to Petra and Jerusalem — until rheumatism crippled his painting arm in his fifties.",
  career:"Church invented the blockbuster: single paintings toured like operas, one canvas alone in a darkened room, tickets twenty-five cents, opera glasses recommended. Twelve thousand New Yorkers queued for The Heart of the Andes in three weeks, and its $10,000 sale set an American record. Niagara did for a waterfall what national anthems do for countries; Cotopaxi staged a volcano as apocalypse with the Civil War burning offstage.",
  outside:"When his hand failed he composed with landscape itself: Olana, the Persian-fantasy house he designed above the Hudson, arranges its windows and carriage roads like framed canvases. It survives intact — furniture, paint pots, views — as one of America's great artist-made places.",
  facts:["The Heart of the Andes was exhibited with a frame built like a window and viewers were encouraged to scan it through opera glasses.",
    "The Icebergs disappeared after an 1863 English sale and was rediscovered in 1979 hanging in a Manchester boys' school stairwell — it now anchors the Dallas Museum of Art.",
    "Mark Twain wrote pages trying to describe his Niagara and gave up, delighted.",
    "He was Thomas Cole's only pupil — the Hudson River School's founder taught exactly one successor, and chose well."] },

{ id:"thomas-cole", name:"Thomas Cole", years:"1801–1848", born:1801, died:1848,
  nation:"usa", eras:["19th-century"], movements:["hudson-river-school","romanticism"],
  techniques:["oil-painting","glazing"], style:"romantic",
  palette:["#3e5e40","#e8944a","#7da8c9","#d9c9a0","#4a3a2a"],
  tagline:"American wilderness, given scripture",
  works:[{t:"The Oxbow",y:"1836"},{t:"The Course of Empire: Destruction",y:"1836"},{t:"The Voyage of Life: Childhood",y:"1842"},{t:"Expulsion from the Garden of Eden",y:"1828"}],
  life:"Born in industrial Lancashire, emigrated at seventeen, and discovered his subject the way America discovered itself — up the Hudson with a sketchbook. In 1825 three of those sketches in a New York shop window stopped the painters Trumbull and Durand in their tracks; American landscape painting effectively begins with that purchase. He settled at Catskill, married, and painted the wilderness while watching the axe arrive.",
  career:"Founder of the Hudson River School — landscape as national epic, wilderness as cathedral. The Course of Empire cycle staged the rise and suicide of a civilization in five acts (a warning, he was clear, not a decoration), while The Oxbow split one canvas between storm-wild nature and the tamed valley — the American argument on a single hinge.",
  outside:"He wrote poetry and essays — his 'Essay on American Scenery' is the movement's manifesto — and worried in print about the railroads eating the valleys he painted. He died suddenly at forty-six; his Catskill studio, Cedar Grove, is now a national historic site facing the mountains he canonized.",
  facts:["He taught exactly one pupil — Frederic Edwin Church — and chose so well the school outgrew its founder.",
    "The Oxbow hides a self-portrait: Cole at his easel, tiny, glancing back at you from the wilderness half.",
    "The Course of Empire was commissioned by a New York merchant who wanted decoration and received a prophecy.",
    "Mount Tom, painted in The Oxbow, now looks back at his work in the Met from a protected reserve."] },

{ id:"andrea-mantegna", name:"Andrea Mantegna", years:"1431–1506", born:1431, died:1506,
  nation:"italy", eras:["15th-century","16th-century"], movements:["early-renaissance"],
  techniques:["tempera","fresco"], style:"renaissance",
  palette:["#8a7a5e","#3e5570","#a85544","#d9c9a0","#4a4540"],
  tagline:"Perspective as a weapon",
  works:[{t:"Lamentation of Christ",y:"c. 1480"},{t:"Camera degli Sposi",y:"1465–74"},{t:"Saint Sebastian",y:"c. 1480"}],
  life:"A tailor's son from near Padua, apprenticed to — and legally adopted by — the painter-dealer Squarcione, whom he sued for exploitation at seventeen and beat. Marriage to Giovanni Bellini's sister allied him with Venice's first family of painting; from 1460 he served the Gonzaga court at Mantua for forty-six years, prickly, proud and irreplaceable.",
  career:"Mantegna treated perspective the way other men treated theology: absolutely. The Lamentation aims Christ's body feet-first at the viewer — the most audacious foreshortening of the century — and the Camera degli Sposi ceiling opens a painted hole to the sky, with putti and servants smirking down over a fake balustrade: the first illusionistic ceiling in Western art, ancestor of every dome that followed.",
  outside:"He collected Roman antiquities with a scholar's obsession, engraved his own designs (prints that traveled to a young Dürer in Nuremberg), and quarreled with nearly everyone — including his Gonzaga patrons, who forgave him because no one else could do what he did.",
  facts:["The Camera degli Sposi oculus is the first di sotto in sù ceiling — the trick Correggio, Tiepolo and every Baroque dome inherited.",
    "The Lamentation's feet-first Christ cheats the perspective — painted honestly, the feet would swallow the picture.",
    "Dürer studied his engravings so closely that art historians can name the exact prints.",
    "He designed his own funerary chapel in Mantua's basilica — bronze bust, Roman gravity, no false modesty."] },

{ id:"edward-burne-jones", name:"Edward Burne-Jones", years:"1833–1898", born:1833, died:1898,
  nation:"britain", eras:["19th-century"], movements:["pre-raphaelites","symbolism"],
  techniques:["oil-painting","tempera"], style:"romantic",
  palette:["#5e6e8a","#c9a45c","#8a9a5e","#d9c9c0","#3e3a4e"],
  tagline:"Knights, dreams and stairways to nowhere",
  works:[{t:"The Golden Stairs",y:"1880"},{t:"King Cophetua and the Beggar Maid",y:"1884"},{t:"The Beguiling of Merlin",y:"1874"}],
  life:"A Birmingham frame-maker's son bound for the church until, at Oxford, he met William Morris and the two discovered Rossetti — theology lost, art history gained. He apprenticed himself to Rossetti, married Georgiana Macdonald (whose memoir of him is a Victorian classic), and survived a scandalous affair with his model Maria Zambaco that nearly ended everything.",
  career:"The second Pre-Raphaelite wave was largely his: medieval dreams slowed to a trance, androgynous figures descending stairs that lead nowhere, Arthurian legend painted as though remembered from another life. The 1877 Grosvenor Gallery made him famous overnight; the French Symbolists took him for a prophet, and Picasso's earliest idols included him.",
  outside:"With Morris & Co. he designed stained glass, tapestries and book illustrations by the acre — the Kelmscott Chaucer is half his; he accepted a baronetcy in 1894 mostly, his wife said, to amuse his son, and never quite lived down his socialist friends' teasing.",
  facts:["The Golden Stairs has no story at all — he refused to explain it, and Victorian critics invented dozens.",
    "The Beguiling of Merlin doubles as autobiography: Zambaco's face is the enchantress trapping the wizard.",
    "His stained glass fills hundreds of churches — many visitors know him without knowing his name.",
    "The Kelmscott Chaucer, with Morris, took four years and set the standard for the printed book as artwork."] },

{ id:"anders-zorn", name:"Anders Zorn", years:"1860–1920", born:1860, died:1920,
  nation:"sweden", eras:["19th-century","20th-century"], movements:["impressionism","realism"],
  techniques:["oil-painting","watercolor","etching"], style:"impressionist",
  palette:["#c98a5e","#3e5570","#e8dcc8","#8a3a3e","#4a4540"],
  tagline:"Three strokes, and the water moves",
  works:[{t:"Midsummer Dance",y:"1897"},{t:"The Omnibus",y:"1892"},{t:"Self-Portrait with Model",y:"1899"}],
  life:"Born to an unmarried brewery worker in Mora and raised on his grandparents' farm, he never met his German father — and ended life as Sweden's international celebrity painter, wealthy enough to collect a museum's worth of art around his Mora estate. The arc from farm boy to painter of presidents took him roughly twenty years and three continents.",
  career:"Zorn's brush was famous for economy: water, skin and lamplight conjured in strokes you can count. He painted three American presidents (Cleveland, Taft and Roosevelt, who pronounced him a genius), the Swedish court, and — closest to his heart — the fiddlers, bathers and midsummer nights of Dalarna. His etchings sold like Rembrandt revivals, which is exactly what collectors called them.",
  outside:"He and his wife Emma built the Zorn Collections in Mora — his house, studio and museum stand as he left them — and endowed the Bellman Prize for Swedish poetry. The famous 'Zorn palette' of four colors is more legend than doctrine, but art teachers repeat it daily anyway.",
  facts:["Theodore Roosevelt sat for him in the White House and reportedly enjoyed the arguing as much as the portrait.",
    "The four-color 'Zorn palette' (white, ochre, vermilion, black) is taught worldwide — he used more when it suited him.",
    "Midsummer Dance was his own favorite: Mora village turning under a sky that never darkens.",
    "His etched self-portraits fetched Rembrandt-level prices during his lifetime — a comparison he did nothing to discourage."] },

{ id:"peder-severin-kroyer", name:"P.S. Krøyer", years:"1851–1909", born:1851, died:1909,
  nation:"denmark", eras:["19th-century","20th-century"], movements:["impressionism","realism"],
  techniques:["oil-painting","alla-prima"], style:"impressionist",
  palette:["#7da8c9","#dce8f0","#c9a45c","#4a5e6e","#e8dcc8"],
  tagline:"The blue hour, bottled at Skagen",
  works:[{t:"Summer Evening on Skagen's Southern Beach",y:"1893"},{t:"Hip, Hip, Hurrah!",y:"1888"},{t:"The Artist and His Wife on Skagen Beach",y:"1899"}],
  life:"Born in Norway, raised by foster parents in Copenhagen after his mother was judged unable to care for him — a prodigy admitted to the academy at nine. From 1882 he anchored the artists' colony at Skagen, the sand-spit village where two seas meet, painting its fishermen, its parties and above all its impossible violet-blue dusk.",
  career:"Krøyer owned the blue hour: that northern moment when sea and sky share one pigment and figures in white seem lit from inside. Hip, Hip, Hurrah! froze the colony mid-toast; the beach walks of Marie Krøyer and Anna Ancher became Scandinavia's most beloved paintings. Syphilis took his sight and his stability by degrees; he painted almost to the end, half-blind.",
  outside:"His marriage to the painter Marie Triepcke — the most painted woman in Denmark, largely by him — collapsed when she left him for the composer Hugo Alfvén; Denmark has turned the whole affair into books, films and pilgrimages to Skagen.",
  facts:["Hip, Hip, Hurrah! took him four years — the toast lasted seconds, the painting outlasted the friendships.",
    "He went progressively blind and joked that he painted his last pictures by memory of where the colors were.",
    "Skagen's light drew the colony; Krøyer's paintings drew the tourists, and still do.",
    "He was admitted to Copenhagen's academy at age nine — the youngest student anyone could remember."] },

{ id:"anna-ancher", name:"Anna Ancher", years:"1859–1935", born:1859, died:1935,
  nation:"denmark", eras:["19th-century","20th-century"], movements:["impressionism","realism"],
  techniques:["oil-painting"], style:"impressionist",
  palette:["#c9d4e8","#e8b43a","#8a5e4a","#dce8f0","#4a4540"],
  tagline:"Sunlight on a blue wall, forever",
  works:[{t:"Sunlight in the Blue Room",y:"1891"},{t:"A Funeral",y:"1891"},{t:"Harvesters",y:"1905"}],
  life:"The only member of the Skagen colony actually born in Skagen — daughter of the Brøndums Inn where the painters gathered — she grew up serving the artists dinner and out-painted most of them. She married Michael Ancher and, against every convention of the era, simply kept working: marriage, motherhood and a career pursued in the same house without apology.",
  career:"While the colony's men chased fishermen and heroics, Anna Ancher painted what was actually there: sunlight crossing a blue wall, women plucking geese, a funeral's black clothes against white light. Her color was the most modern in Denmark — closer to Vermeer and to the coming century than anything her louder colleagues produced.",
  outside:"She and Michael appeared together on the Danish 1000-krone note — the rare banknote featuring two painters who shared a kitchen. Their Skagen house is now a museum, kept as if the two had stepped out to check the light.",
  facts:["Born in the inn where the artists' colony drank — she was Skagen before Skagen was famous.",
    "Sunlight in the Blue Room is Denmark's quiet national treasure: a wall, a child, and light doing everything.",
    "She kept painting after marriage and children when convention demanded she stop — and history sided with her.",
    "The Anchers shared the 1000-krone banknote: the state's official portrait of a working marriage."] },

{ id:"paula-modersohn-becker", name:"Paula Modersohn-Becker", years:"1876–1907", born:1876, died:1907,
  nation:"germany", eras:["19th-century","20th-century"], movements:["expressionism","post-impressionism"],
  techniques:["oil-painting","tempera"], style:"expressionist",
  palette:["#c98a5e","#8a9a5e","#e8d9c0","#a85544","#4a4540"],
  tagline:"The first modern woman to paint herself whole",
  works:[{t:"Self-Portrait at Sixth Wedding Anniversary",y:"1906"},{t:"Self-Portrait with Amber Necklace",y:"1906"},{t:"Old Poorhouse Woman with Glass Ball and Poppies",y:"1907"}],
  life:"Bremen-raised, trained in the Worpswede artists' colony, married to the painter Otto Modersohn — and repeatedly gone: four self-financed escapes to Paris, where Cézanne and Gauguin rearranged her eye. In 1907, weeks after finally achieving the child she had painted herself imagining, she died of an embolism at thirty-one. Her recorded last word was 'Schade' — a pity.",
  career:"In roughly a decade she produced some 750 paintings that quietly pre-invented Expressionism: monumental peasant women, children with enormous eyes, and the self-portraits — including the first known nude self-portraits by a woman, one painted pregnant-bellied while she was not, a fiction about a future she wanted. Germany caught up decades later.",
  outside:"Her friendship with Rilke (who married her best friend) produced one of art's great elegies — his 'Requiem for a Friend' is about her. Her letters and journals, published after her death, became a classic of the inner life of a working artist.",
  facts:["The 1906 anniversary self-portrait shows her pregnant — she wasn't; she painted the wish, then died of its fulfillment.",
    "Bremen opened a museum devoted to her in 1927 — the first museum anywhere dedicated to a woman painter.",
    "Rilke's 'Requiem for a Friend' mourns her; the two argued about art for years and the poem still is.",
    "She sold perhaps three paintings in her lifetime. The catalogue now runs to 750."] },

{ id:"chaim-soutine", name:"Chaïm Soutine", years:"1893–1943", born:1893, died:1943,
  nation:"belarus", eras:["20th-century"], movements:["expressionism"],
  techniques:["oil-painting","impasto"], style:"expressionist",
  palette:["#a12b3a","#3e5570","#c98a3a","#4a3a2a","#e8dcc8"],
  tagline:"Paint that trembles like meat",
  works:[{t:"Carcass of Beef",y:"c. 1925"},{t:"Le Petit Pâtissier",y:"1922–23"},{t:"Landscape with Figures, Céret",y:"1922"}],
  life:"Tenth of eleven children in a Jewish shtetl near Minsk, beaten as a boy for the sin of drawing, he clawed his way through Vilnius art school to Paris's La Ruche — the beehive of penniless immigrant painters — where Modigliani became his closest friend, protector and portraitist. He hid in the French countryside through the occupation and died in 1943 after a desperate, delayed ulcer operation.",
  career:"Soutine painted as if the world were perishable: hanging beef that he kept fresh with buckets of blood while neighbors summoned the police, portraits of pastry cooks and bellboys twisted like flames, Céret landscapes that heave like seasickness. When the American collector Albert Barnes bought over fifty canvases in one 1923 swoop, the starving painter took a taxi to the Riviera — a two-hundred-mile fare — to celebrate.",
  outside:"He destroyed his own work compulsively, hunted down early canvases to slash them, and trusted almost no one except Modigliani — whose deathbed reportedly extracted the promise that Soutine would be looked after. De Kooning called him the missing link to everything.",
  facts:["The Barnes purchase of 1923 turned him from starving to solvent overnight; the first thing he bought was that taxi ride to Nice.",
    "Neighbors called the police about the beef carcass; he argued art and kept painting while it turned.",
    "Modigliani painted him at least four times — the tenderest portraits either man was involved in.",
    "Bacon and de Kooning both named him an ancestor; the trembling flesh of postwar painting starts here."] },

{ id:"arkhip-kuindzhi", name:"Arkhip Kuindzhi", years:"1842–1910", born:1842, died:1910,
  nation:"ukraine", eras:["19th-century","20th-century"], movements:["peredvizhniki","realism"],
  techniques:["oil-painting","glazing"], style:"romantic",
  palette:["#2a2a4e","#8fd94a","#c9a45c","#1d3a4e","#e8e0cc"],
  tagline:"He patented moonlight",
  works:[{t:"Moonlit Night on the Dnieper",y:"1880"},{t:"Birch Grove",y:"1879"},{t:"Red Sunset on the Dnieper",y:"1905–08"}],
  life:"A Greek cobbler's son from Mariupol, orphaned young, rejected by the St Petersburg academy repeatedly before it surrendered. In 1880 he staged Russia's first single-painting exhibition: Moonlit Night on the Dnieper, alone in a darkened room, lit by a directed lamp — the queue wrapped around the block and a Grand Duke bought the picture to carry on his yacht.",
  career:"Kuindzhi painted light as an event: phosphorescent moon-paths, birch trunks in stage-lit sun, sunsets like slow explosions. Rivals whispered that he used secret chemical pigments; he let the rumor breathe. Then, at the height of his fame, he simply stopped exhibiting — for the last thirty years he showed almost nothing, painting for a room only he entered.",
  outside:"He lived like a monk atop his apartment building, fed the birds on his roof daily (Petersburg cartoonists loved it), and secretly funded prizes and poor students on a huge scale — his fortune, from land deals, went almost entirely to an artists' society bearing his name.",
  facts:["Moonlit Night was exhibited alone, in the dark, under a lamp — Russia's first single-painting show, and its first blockbuster.",
    "Collectors inspected the canvas's back for hidden lamps; the glow was just glazing and nerve.",
    "At his peak he withdrew from exhibiting entirely and stayed silent for three decades.",
    "His star pupil Nicholas Roerich carried the light-mysticism into the next century."] },

{ id:"vasily-surikov", name:"Vasily Surikov", years:"1848–1916", born:1848, died:1916,
  nation:"russia", eras:["19th-century","20th-century"], movements:["peredvizhniki","realism"],
  techniques:["oil-painting"], style:"tonal",
  palette:["#dce8f0","#8a3a3e","#3e3a2a","#c9a45c","#4a5e6e"],
  tagline:"Russian history, painted from inside the crowd",
  works:[{t:"The Morning of the Streltsy Execution",y:"1881"},{t:"Boyarynya Morozova",y:"1887"},{t:"Menshikov in Berezovo",y:"1883"}],
  life:"Born to a Cossack family in Siberian Krasnoyarsk — he claimed the seventeenth century was still alive there, and painted like he meant it. A gold merchant paid his way to the St Petersburg academy; Moscow's ancient streets gave him his subject. When his wife died in 1888 he stopped painting entirely, went home to Siberia, and came back two years later with color restored.",
  career:"His great trilogy — the Streltsy rebels awaiting execution, the disgraced Menshikov in exile, the Old Believer martyr Morozova hauled through the snow on a sledge — made the crowd the protagonist of history painting: every onlooker a biography, every winter authentic. No painter has made Russian history feel less like costume and more like weather.",
  outside:"He turned down professorships, distrusted theory, and researched like a historian — riding through Siberia sketching Old Believer faces, testing how sledges actually cut through packed snow for Morozova.",
  facts:["For Boyarynya Morozova he added rows of canvas until the sledge finally seemed to move — visitors swear it does.",
    "He found Morozova's face in an Old Believer woman he glimpsed at a cemetery, and chased the type for years.",
    "After his wife's death he quit painting for two years; Siberia, he said, gave it back.",
    "His daughter married the painter Pyotr Konchalovsky; the film director Nikita Mikhalkov is his great-grandson."] },

{ id:"valentin-serov", name:"Valentin Serov", years:"1865–1911", born:1865, died:1911,
  nation:"russia", eras:["19th-century","20th-century"], movements:["realism","impressionism"],
  techniques:["oil-painting","pastel"], style:"impressionist",
  palette:["#e8d9c0","#c98a5e","#4a5e6e","#8a3a3e","#dce8f0"],
  tagline:"Portraits the sitters feared",
  works:[{t:"Girl with Peaches",y:"1887"},{t:"Portrait of Ida Rubinstein",y:"1910"},{t:"The Abduction of Europa",y:"1910"}],
  life:"Son of a famous composer, he was handed to Repin as a boy and trained at the master's kitchen table; at twenty-two he painted Girl with Peaches — Vera Mamontova in a sunlit dining room — and Russian painting stepped into modern light in one sitting. He became the portraitist everyone needed and many dreaded: tsars, bankers, Diaghilev's dancers.",
  career:"Serov's portraits flattered no one and fascinated everyone — 'I am not a photographer,' he warned sitters, and the results could end friendships. His late work leapt forms in single bounds: the Matisse-flat Ida Rubinstein, the Europa riding a wave-slicked bull toward pure decoration. He died at forty-six, mid-transformation.",
  outside:"An eyewitness to Bloody Sunday in 1905 — he watched troops fire on the crowd from the Academy's windows — he resigned his Academy membership in protest against the Tsar whose family he had painted, and never took it back.",
  facts:["Girl with Peaches was painted at twenty-two and instantly became Russia's most loved portrait.",
    "After witnessing Bloody Sunday from the Academy windows, he resigned and refused all court work.",
    "His Ida Rubinstein scandalized Moscow — bones, angles and green shadow a decade ahead of schedule.",
    "Sitters begged him to soften; he reportedly replied that the truth had taken him months and would stay."] },

{ id:"fitz-henry-lane", name:"Fitz Henry Lane", years:"1804–1865", born:1804, died:1865,
  nation:"usa", eras:["19th-century"], movements:["luminism","hudson-river-school"],
  techniques:["oil-painting","glazing"], style:"tonal",
  palette:["#e8b48a","#c98a5e","#7da8c9","#3e4a5e","#d9c9a0"],
  tagline:"Stillness, measured in light",
  works:[{t:"Lumber Schooners at Evening on Penobscot Bay",y:"1863"},{t:"Boston Harbor, Sunset",y:"c. 1850–55"},{t:"Owl's Head, Penobscot Bay, Maine",y:"1862"},{t:"Brace's Rock",y:"1864"}],
  life:"Born in Gloucester, Massachusetts, and paralyzed in the legs as a small child — family tradition blamed a poisonous seed — he moved on crutches for the rest of his life and saw his harbors mostly from boats and wheeled chairs. Trained as a lithographer in Boston, he came home to Gloucester and built himself a granite house above the working waterfront he would paint for twenty years.",
  career:"Lane painted the sea with the sound turned off: mirror-still water, rigging drawn to the inch, light banded across evening skies, and not one visible brushstroke. The manner had no name in his lifetime — the term Luminism was coined by a curator in 1954, nearly a century later. Summer cruises to Penobscot Bay with his friend Joseph Stevens produced the Maine pictures; the late Brace's Rock series empties even the ships out, leaving stillness itself.",
  outside:"He never married, took a documented interest in the spiritualist currents of his day — readers have connected it to his weightless light, cautiously — and stayed a Gloucester civic fixture. His granite house still stands on Duncan's Point, and the Cape Ann Museum around the corner keeps the world's largest collection of his work.",
  facts:["The word 'Luminism' was invented in 1954 — Lane died ninety years before hearing what he was.",
    "Paralyzed in childhood, he painted the coast he could reach by boat, crutch and chair.",
    "He designed his own granite house in 1849; it still overlooks Gloucester harbor.",
    "The late Brace's Rock canvases, nearly empty of event, are pointed to as proto-modern stillness."] }
]);
