/* PIGMENT — artists 11/13 : Young Poland & Türkiye's painters */
window.ARTISTS.push(
{ id:"akseli-gallen-kallela", name:"Akseli Gallen-Kallela", years:"1865–1931", born:1865, died:1931,
  nation:"finland", eras:["19th-century","20th-century"], movements:["symbolism","art-nouveau"],
  techniques:["oil-painting","tempera","woodblock"], style:"romantic",
  palette:["#2e4a3e","#5e8a96","#caa45c","#8a2e26","#e8e4d8"],
  tagline:"The Kalevala given a face — painting a nation before it existed",
  works:[{t:"The Defense of the Sampo",y:"1896"},{t:"Lemminkäinen's Mother",y:"1897"},{t:"The Aino Myth, Triptych",y:"1891"}],
  life:"Born Axél Gallén in Pori — he Finnicised his Swedish name in 1907, a manifesto in itself — Gallen-Kallela studied in Paris but found his subject in Finland's wilderness and its folk epic, the Kalevala. He painted from a log studio in the backwoods, served in Finland's independence struggle, and died in 1931, mourned as a national founder.",
  career:"His Kalevala paintings — the Sampo defended in a storm of swords, a mother gathering her son's body from death's black river — fused Symbolism, Art Nouveau flatness and folk ornament into images Finland adopted as its self-portrait. His frescoes for the 1900 Paris World's Fair pavilion made 'Finnish art' an international fact while the country was still a Russian duchy.",
  outside:"He built his own castle-studio, designed flags, uniforms and decorations for the newborn republic — including the Cross of Liberty — and spent 1909–11 painting in British East Africa, returning with over 150 canvases. His friendship with Sibelius ran on shared saunas and apocalyptic toasts; he appears mid-revel in his own painting Symposium.",
  facts:["He illustrated the 'Great Kalevala' edition that remains Finland's defining illustrated book.",
    "His Paris 1900 frescoes had to represent a nation that officially wasn't one.",
    "Aalto's generation called his Tarvaspää studio Finland's first Gesamtkunstwerk — it is now his museum."] },

{ id:"jan-matejko", name:"Jan Matejko", years:"1838–1893", born:1838, died:1893,
  nation:"poland", eras:["19th-century"], movements:["romanticism","realism"],
  techniques:["oil-painting","glazing"], style:"baroque",
  palette:["#5e2a2a","#caa45c","#2e4a72","#8a6e46","#1d1a16"],
  tagline:"History painting as national life-support",
  works:[{t:"The Battle of Grunwald",y:"1878"},{t:"Stańczyk",y:"1862"},{t:"Prussian Homage",y:"1882"}],
  life:"Born in Kraków when Poland existed only in memory — partitioned off every map — Matejko devoted his life to painting the nation back into being. Severely myopic, working inches from canvases the size of walls, he led Kraków's art academy, refused offers to leave, and died at fifty-five, mourned with a king's funeral by a country that wasn't a state.",
  career:"The Battle of Grunwald — four by ten metres of colliding knights — and Prussian Homage staged Poland's triumphs at overwhelming scale; Stańczyk, the court jester sitting grief-struck while the ball glitters behind him, gave the nation its conscience in a single figure. His pupils — Wyspiański, Malczewski, Mehoffer — became Young Poland; the teacher painted the past so they could paint the soul.",
  outside:"He compiled an album of Polish historical costume and a portrait series of every Polish monarch, still reprinted in schoolbooks. During his lifetime the Grunwald canvas toured the partitions like a clandestine national assembly; the Nazis later put a price on its head — it spent the war buried.",
  facts:["The Nazis specifically hunted The Battle of Grunwald for destruction; it survived hidden under a road-side shed in Lublin.",
    "Stańczyk's face is Matejko's own.",
    "He turned down the directorship of Prague's academy: 'I belong to Kraków.'"] },

{ id:"jacek-malczewski", name:"Jacek Malczewski", years:"1854–1929", born:1854, died:1929,
  nation:"poland", eras:["19th-century","20th-century"], movements:["young-poland","symbolism"],
  techniques:["oil-painting","glazing"], style:"surreal",
  palette:["#5e7250","#a83a4e","#caa45c","#3e4a6e","#e8d4b0"],
  tagline:"Fauns in the wheatfield — Polish fate with mythological company",
  works:[{t:"Melancholia",y:"1890–94"},{t:"The Vicious Circle",y:"1895–97"},{t:"Thanatos",y:"1898–99"}],
  life:"Son of a patriotic Radom family schooled on Słowacki's poetry and the failed 1863 uprising, Malczewski studied under Matejko, rebelled into symbolism, and became Young Poland's painted conscience. Professor and twice rector in Kraków, he went blind in his final years and died in 1929, asking to be buried in a monk's habit.",
  career:"Melancholia pours a century of insurgents, exiles and children out of a painter's canvas into a room they cannot leave — national history as fever dream. He painted himself relentlessly: in armour, in chains, as Christ among thorns, flanked by fauns, chimeras and Thanatos with her scythe — the artist's vocation dramatised as Poland's. No one fused private myth and national wound so completely.",
  outside:"His Siberian-exile cycle drew on his father's generation of deportees; the props — the prisoner's grey greatcoat above all — recur like stage costumes across decades. His son Rafał became a notable painter in his own right.",
  facts:["He painted dozens of self-portraits — Poland's most varied painted autobiography.",
    "Thanatos is a beautiful woman sharpening a scythe in an orchard at dusk.",
    "Blind, he reportedly said he had already seen everything he needed."] },

{ id:"olga-boznanska", name:"Olga Boznańska", years:"1865–1940", born:1865, died:1940,
  nation:"poland", eras:["19th-century","20th-century"], movements:["young-poland","impressionism"],
  techniques:["oil-painting","pastel"], style:"impressionist",
  palette:["#8a8276","#d9b4be","#5e5648","#a8b4b8","#e8e0d0"],
  tagline:"Portraits in grey mist — painted on cardboard, never varnished",
  works:[{t:"Girl with Chrysanthemums",y:"1894"},{t:"Self-Portrait",y:"c. 1906"},{t:"Portrait of Paul Nauen",y:"1893"}],
  life:"Kraków-born to a Polish engineer and a French drawing teacher, Boznańska trained in Munich — women being barred from Kraków's academy — and from 1898 ran her studio in Paris, declining professorships and marriage alike. Celebrated, then desperately poor, she died in occupied Paris in 1940, her studio a famous chaos of canvases and tamed mice.",
  career:"Girl with Chrysanthemums — a pale child with enormous unchildlike eyes — is Young Poland's quiet masterpiece. She painted on absorbent cardboard, hating gloss, building faces from grey-violet flickers until sitters seem seen through breath on glass; Whistler's tonalism and Velázquez's greys are kin, but the nervous interiority is hers. France made her a Legion of Honour chevalier; Poland claimed her too late.",
  outside:"She fed and named the mice that ran free in her studio, refusing traps; visitors recalled tea among easels, mouse-nibbled biscuits and absolute devotion to work. Her sister's suicide and the lost family fortune darkened her final Paris years.",
  facts:["She refused to varnish or retouch sold paintings — matte surface as signature.",
    "Offered Kraków's academy professorship in 1909? — she declined to leave Paris (the academy had once been closed to her as a student).",
    "Her self-portraits chart five decades of unflinching grey-eyed appraisal."] },

{ id:"stanislaw-wyspianski", name:"Stanisław Wyspiański", years:"1869–1907", born:1869, died:1907,
  nation:"poland", eras:["19th-century","20th-century"], movements:["young-poland","art-nouveau","symbolism"],
  techniques:["pastel","watercolor"], style:"ornament",
  palette:["#5e7250","#d9a8b8","#caa45c","#3e5a8a","#e8dcc4"],
  tagline:"Playwright, stained-glass visionary, pastel portraitist — Young Poland in one man",
  works:[{t:"God the Father — Become! (stained glass)",y:"1897–1904"},{t:"Motherhood",y:"1905"},{t:"Self-Portrait",y:"1902"}],
  life:"Matejko's most gifted pupil — and gentlest rebel — Wyspiański remade every art Kraków offered: painting, stained glass, furniture, typography, and the national drama (his play The Wedding remains Poland's most performed). Allergic-sensitive to oil paints, he worked in pastel; syphilis killed him at thirty-eight, and his funeral became a national demonstration.",
  career:"His Franciscan church windows — God the Father erupting from cosmic chaos — and the floral wall-paintings beneath them are Art Nouveau at cathedral scale and Slavic pitch. The pastel portraits, above all of sleeping and nursing children, marry tenderness to design so clean it reads as modern a century on. He designed his plays' sets, costumes and posters: the total artwork, achieved in a provincial city.",
  outside:"His plan to rebuild Wawel hill as a Polish acropolis — parliament, theatre, cathedral united — remained on paper, the era's grandest unbuilt dream. Dying, he sketched his children from his bed in fast, perfect lines.",
  facts:["The Wedding (1901) is both a real Kraków wedding he attended and the national psychodrama.",
    "He used pastel partly because oils inflamed his health — constraint as style.",
    "Kraków's museum dedicated an entire branch to him in 2021 — playwright filed under painter, painter under prophet."] },

{ id:"witkacy", name:"Witkacy (S. I. Witkiewicz)", years:"1885–1939", born:1885, died:1939,
  nation:"poland", eras:["20th-century"], movements:["expressionism","surrealism"],
  techniques:["pastel","oil-painting"], style:"expressionist",
  palette:["#6e3a8a","#e0427a","#2e8a8a","#e8a82e","#1d1c22"],
  tagline:"The Portrait Firm — prices by type, drugs noted on the margin",
  works:[{t:"Composition with a Self-Portrait",y:"1917–22"},{t:"Portrait of Nena Stachurska",y:"1929"},{t:"Fantasy — Fairy Tale",y:"1922"}],
  life:"Son of Zakopane's cultural patriarch, Stanisław Ignacy Witkiewicz — 'Witkacy' — was painter, novelist, playwright, philosopher and Poland's one-man avant-garde. He witnessed the Russian Revolution as a tsarist officer, theorised 'Pure Form', and took his life on 18 September 1939, the day the Soviets invaded the Poland the Nazis were already devouring.",
  career:"After renouncing 'serious' painting, he ran the S. I. Witkiewicz Portrait Firm with a printed price list: types A to E, from flattering likeness to 'pure form' deformation, customer's choice — the margins annotated with what he had ingested (NP4: 'no smoking, fourth day'; peyote, cocaine duly coded). The joke was a philosophy: art as commerce confessed, consciousness as experiment. Hundreds of electric pastel faces survive.",
  outside:"His plays (The Madman and the Nun, The Shoemakers) anticipated absurdist theatre by decades; his novel Insatiability foresaw totalitarian mind-pills. His catastrophist philosophy predicted the extinction of metaphysical feeling — then 1939 arrived as if to prove it.",
  facts:["Firm motto: 'The customer must be satisfied. Misunderstandings are ruled out.'",
    "Drug annotations make his portraits a unique psychopharmacological archive.",
    "A 1988 state reburial of his remains exhumed the wrong body — an unknown woman; Witkacy would have approved."] },

{ id:"zdzislaw-beksinski", name:"Zdzisław Beksiński", years:"1929–2005", born:1929, died:2005,
  nation:"poland", eras:["20th-century","21st-century"], movements:["surrealism","contemporary-art"],
  techniques:["oil-painting","glazing","mixed-media"], style:"surreal",
  palette:["#8a4a2e","#3e3a36","#d9852e","#5e2a2a","#1d1410"],
  tagline:"Cathedrals of bone under rust-coloured skies — dystopia, untitled",
  works:[{t:"Untitled (the artist titled nothing)",y:"1970s–90s"},{t:"The 'fantastic period' paintings",y:"c. 1968–83"},{t:"Computer-era works",y:"1990s"}],
  life:"An architect by training from Sanok, in Poland's far south-east, Beksiński worked as a bus-body designer before photography, sculpture and finally painting claimed him. His life ended as darkly as his canvases: his wife died in 1998, his son Tomasz — a famous radio presenter — took his own life in 1999, and in 2005 Beksiński was murdered in his Warsaw flat by a caretaker's teenage son he had refused a small loan.",
  career:"Self-taught in painting, he produced his 'fantastic period': hearse-red skies, towers of bone and weed, figures of bandaged flesh — apocalypse rendered with old-master glazing and, he insisted, no meaning to decode: 'I wish to paint as if I were photographing dreams.' He never titled works, never explained, and listened to classical music at full volume while painting. Poland's gothic imagination has a capital, and it is the Sanok museum housing his estate.",
  outside:"Gentle, witty and reclusive — the opposite of his imagery — he avoided his own openings, corresponded copiously, and embraced computers in the 1990s for photo-manipulated works. Before moving to Warsaw in 1977 he burned a selection of canvases in his yard, unwilling to let weaker work survive him.",
  facts:["He refused to title paintings so viewers couldn't outsource their reading of them.",
    "Guillermo del Toro and a generation of game designers cite him; 'Beksiński-esque' is a working adjective in concept art.",
    "The Sanok castle museum holds the world's largest collection of his work — by his own bequest."] },

{ id:"seker-ahmed-pasha", name:"Şeker Ahmed Paşa", years:"1841–1907", born:1841, died:1907,
  nation:"turkey", eras:["19th-century","20th-century"], movements:["realism","orientalism"],
  techniques:["oil-painting","glazing"], style:"tonal",
  palette:["#2e4a3e","#8a6e46","#d9c890","#5e3424","#e8e0c8"],
  tagline:"'Sugar' Ahmed — the gentle Paşa who brought the easel to Istanbul",
  works:[{t:"Self-Portrait",y:"c. 1880s"},{t:"Still Life with Fruit",y:"c. 1900"},{t:"Forest (Woodland Scene)",y:"c. 1890s"}],
  life:"Sent to Paris by Sultan Abdülaziz to study painting under Gérôme and Boulanger, Ahmed Ali returned to serve the palace as court officer, protocol master and tireless evangelist for oil painting — so sweet-tempered that the nickname 'Şeker' (Sugar) replaced his name. He rose to the rank of Paşa and died in Istanbul in 1907.",
  career:"In 1873 he organised what is regarded as Istanbul's first public group painting exhibition — the founding act of the Turkish gallery tradition. His own canvases — orchard fruit heaped with quiet gravity, deep woodland clearings — domesticate French realism with an Ottoman stillness; art historians love the self-portrait in uniform, palette in hand: two civilisations sharing one easel.",
  outside:"As palace protocol officer he escorted visiting European royalty and bought Western paintings for the imperial collection — curator, diplomat and painter in one braided career. He helped young Ottoman painters obtain Paris scholarships, seeding the next two generations.",
  facts:["His 1873 exhibition predates Turkey's first art academy by a decade.",
    "Goupil's Paris gallery exhibited him — an Ottoman officer hanging beside Salon stars.",
    "Turkish still-life painting effectively begins with his pomegranates and quinces."] },

{ id:"osman-hamdi-bey", name:"Osman Hamdi Bey", years:"1842–1910", born:1842, died:1910,
  nation:"turkey", eras:["19th-century","20th-century"], movements:["orientalism","realism"],
  techniques:["oil-painting","glazing"], style:"metaphysical",
  palette:["#1f6e8a","#d9a83e","#b05e32","#2e4a3e","#e8d9b4"],
  tagline:"The Tortoise Trainer — Orientalism, corrected from the inside",
  works:[{t:"The Tortoise Trainer",y:"1906"},{t:"Girl Reciting the Qur'an",y:"1880"},{t:"Two Musician Girls",y:"1880"}],
  life:"Son of a grand vizier, trained in Paris law and in the studios of Gérôme and Boulanger, Osman Hamdi returned to run half of Ottoman culture: founder-director of the Imperial Museum, founder of the fine-arts academy, author of the empire's first antiquities laws, and excavator of Sidon, where his team raised the Alexander Sarcophagus. He painted, magnificently, in the margins of all that — until his death in 1910.",
  career:"He used Orientalism's own polished technique to overturn its clichés: instead of harem fantasy, his figures read books, debate theology, train tortoises by candlelight — Ottomans with inner lives, painted by one. The Tortoise Trainer, long read as a satire of reforming an empire at a tortoise's pace, became in 2004 the most expensive Turkish painting ever sold, anchoring Istanbul's Pera Museum.",
  outside:"His museum (today's Istanbul Archaeology Museums) and his antiquities legislation stopped — or at least slowed — the export of the empire's heritage; archaeologists count him a founding father. He posed for many of his paintings himself, photographed in costume, then painted from the prints.",
  facts:["The Tortoise Trainer sold for about $3.5 million in 2004 — a Turkish record that stood for years.",
    "The Alexander Sarcophagus his dig recovered is among the most celebrated objects in any museum.",
    "He was the model for most of his own painted scholars — self-portrait as civilisation."] },

{ id:"mihri-musfik", name:"Mihri Müşfik Hanım", years:"1885–1954", born:1885, died:1954,
  nation:"turkey", eras:["20th-century"], movements:["impressionism","realism"],
  techniques:["oil-painting","pastel"], style:"impressionist",
  palette:["#8a4a4e","#d9b4be","#5e7a8e","#e9ddc4","#3a3430"],
  tagline:"The first lady of Turkish painting — from the palace to a potter's field",
  works:[{t:"Self-Portrait",y:"c. 1910"},{t:"Portrait of Mustafa Kemal Atatürk",y:"c. 1923"},{t:"Woman in White",y:"c. 1920s"}],
  life:"Born into an aristocratic Istanbul household — her father a pasha and professor of medicine — Mihri Rasim defied convention serially: studying art in Rome and Paris, marrying and divorcing on her own terms, and becoming the Ottoman Empire's first prominent woman painter. Emigrating in the 1920s, she died poor and forgotten in New York in 1954, reportedly buried in a potter's field.",
  career:"As director of drawing at the new Women's Fine Arts School in Istanbul (1914), she fought through scandalous innovations — live models for female students among them — and trained the republic's first generation of women artists. Her pastel portraits, fluent and psychologically direct, ranged from Istanbul society to, reportedly, Pope Benedict XV in Rome and Atatürk in Ankara.",
  outside:"Her salon connected Pierre Loti's Istanbul to Roman and Parisian studios; her great-nephew's archives and a wave of recent retrospectives have been reassembling a career history mislaid for half a century.",
  facts:["She is widely credited as the first woman to direct an Ottoman art school.",
    "Accounts hold she portrayed a sitting Pope — extraordinary access for any painter, let alone a Muslim woman of 1920.",
    "A 2023 Istanbul retrospective drew record crowds — rediscovery, sixty-nine years after the unmarked grave."] },

{ id:"ibrahim-calli", name:"İbrahim Çallı", years:"1882–1960", born:1882, died:1960,
  nation:"turkey", eras:["20th-century"], movements:["impressionism"],
  techniques:["oil-painting","alla-prima"], style:"impressionist",
  palette:["#2e5e8a","#e8c87a","#c4763e","#8aa78a","#f0e8d8"],
  tagline:"The 1914 Generation's ringleader — Turkish light, Paris brushwork",
  works:[{t:"Reclining Woman",y:"c. 1920s"},{t:"Mevlevi Dervishes",y:"c. 1920s"},{t:"Portrait of Atatürk",y:"c. 1930s"}],
  life:"From Çal in Denizli — the hometown became his surname — Çallı reached Istanbul as a penniless clerk's apprentice, won the Paris scholarship, and trained in Fernand Cormon's atelier until the First World War sent the students home. For three decades he ruled the Istanbul academy's painting studio, charming the republic as its best-loved bohemian, and died in 1960.",
  career:"The returning Paris cohort — 'the 1914 Generation', or simply 'the Çallı Generation' — brought Impressionism to Turkish easels: Bosphorus light, picnics, nudes, dervishes mid-whirl, painted with juicy alla prima conviction. Çallı's portraits of Atatürk and the war canvases he made from the Gallipoli home front hang at the founding of republican visual culture.",
  outside:"His wit was as quoted as his paintings; students from Bedri Rahmi to generations of academy painters traded Çallı anecdotes like currency. He painted to the end — slippers, cigarette, raki within reach — the republic's resident old master.",
  facts:["An entire generation of Turkish painting is named after him.",
    "He taught at the academy for nearly 30 years; the studio queue to enter 'Çallı's atelier' was its own institution.",
    "His Mevlevi series put whirling dervishes into Impressionist colour — East and West mid-spin."] },

{ id:"fikret-mualla", name:"Fikret Mualla", years:"1903–1967", born:1903, died:1967,
  nation:"turkey", eras:["20th-century"], movements:["expressionism","fauvism"],
  techniques:["gouache","watercolor","oil-painting"], style:"fauvist",
  palette:["#c4302a","#2e5eaa","#e8c43e","#2e8a5e","#f0e8d8"],
  tagline:"Paris nights in gouache — Istanbul's wounded, brilliant exile",
  works:[{t:"Café Scene, Paris",y:"c. 1950s"},{t:"Circus",y:"c. 1955"},{t:"Street with Figures",y:"c. 1960"}],
  life:"Born in Istanbul, Fikret Mualla Saygı limped from a childhood football injury and bristled through engineering school in Germany before art swallowed him. He settled in Paris in 1939 — poor, alcoholic, repeatedly hospitalised, twice confined to psychiatric wards — and painted ceaselessly until a patron's villa in Provence gave him his few calm years. He died at Reillanne in 1967; Turkey later brought his remains home.",
  career:"His gouaches — cafés, bistros, circuses, métro crowds — compress Paris into shorthand bursts of red, cobalt and black, Fauvist colour driven by an exile's nervous tempo. He sold them for drinks and francs; collectors now chase them across auction rooms. The tragedy and the brilliance are inseparable: a man with no fixed address fixing a city on paper, thousands of sheets deep.",
  outside:"Istanbul friends — including the poet Nâzım Hikmet's circle and the painter Abidin Dino — fed, defended and exhibited him when he couldn't. Madame Angles, his late-life patron, traded him room and board against paintings: the arrangement that finally let him work in peace.",
  facts:["He reportedly paid tabs at Paris cafés in gouaches — some proprietors papered back rooms with them.",
    "Picasso is said to have admired and encouraged him during his hard first Paris years.",
    "Turkey reburied him with honours in Istanbul's Karacaahmet cemetery in 1974."] },

{ id:"fahrelnissa-zeid", name:"Fahrelnissa Zeid", years:"1901–1991", born:1901, died:1991,
  nation:"turkey", eras:["20th-century"], movements:["abstract-art","expressionism"],
  techniques:["oil-painting","mixed-media"], style:"abstract",
  palette:["#c4302a","#2e50c4","#f0c82e","#2e8a5e","#1d1a20"],
  tagline:"Kaleidoscope at palace scale — princess of Istanbul, painter of infinities",
  works:[{t:"My Hell",y:"1951"},{t:"Resolved Problems",y:"1948"},{t:"Break of the Atom and Vegetal Life",y:"1962"}],
  life:"Born on Büyükada island into the brilliant Şakir Paşa family — writers, painters and one famous 'Fisherman of Halicarnassus' — Fahrelnissa married Prince Zeid of the Iraqi royal house and lived between Istanbul, Berlin, Baghdad, London and Paris. The 1958 Baghdad coup murdered the dynasty and ended the embassy life; she answered with her hugest abstractions, later founding an art school in Amman, where she died at ninety.",
  career:"Her postwar Paris canvases — My Hell stretches five metres — shatter space into stained-glass storms of triangles, Byzantine mosaic crossed with Islamic geometry at Abstract Expressionist scale; the École de Paris had nothing else like them. Late in life she returned to hieratic portraits, faces like Fayum icons with enormous eyes. Tate Modern's 2017 retrospective re-fixed her in the international canon.",
  outside:"After the coup stripped the household, the princess famously learned to cook at fifty-seven — then painted on the chicken bones, setting them in resin as 'paléokrystalos'. Her brother was the writer Fisherman of Halicarnassus; her sister Aliye Berger an engraver; her granddaughter a museum's worth of memoirs.",
  facts:["My Hell was repainted from memory after a version was destroyed — she called the act exorcism.",
    "She turned dinner leftovers into resin sculptures — aristocratic thrift as surrealism.",
    "Her Amman school taught Jordanian women artists for fifteen years, free."] },

{ id:"bedri-rahmi-eyuboglu", name:"Bedri Rahmi Eyüboğlu", years:"1911–1975", born:1911, died:1975,
  nation:"turkey", eras:["20th-century"], movements:["expressionism","naive-art"],
  techniques:["oil-painting","gouache","mixed-media","printmaking"], style:"fauvist",
  palette:["#c4663a","#1f6e8a","#e8c43e","#5e3450","#e8dcc0"],
  tagline:"Kilim motifs meet Matisse — painter-poet of the Anatolian eye",
  works:[{t:"Han Coffeehouse",y:"1973"},{t:"Mosaic panel for Expo 58, Brussels",y:"1958"},{t:"Yellow Landscape (Anatolia series)",y:"c. 1950s"}],
  life:"Born in Görele on the Black Sea to a governor-poet father, Eyüboğlu trained in Istanbul and under André Lhote in Paris, married the Romanian-born painter Eren, and taught at the Istanbul academy for four decades. Painter, master printmaker, muralist and one of Turkey's most beloved poets, he died in 1975; half the country can quote his 'Karadut' from memory.",
  career:"His credo was a marriage: folk art's eye — kilims, embroidery, wooden spoons, çini — with modern colour's appetite. Canvases, fabric prints and vast mosaics pulse with Anatolian motifs run through Fauvist heat; his 272-square-metre mosaic wall for the Turkish pavilion at Brussels' Expo 58 took a gold medal, and another mural entered Paris's NATO building. As a teacher he sent students into villages to collect motifs like botanists.",
  outside:"His poems fill anthologies; his atelier's fabric-printing workshops dressed a generation of Istanbul intellectuals. Brother Sabahattin was the great essayist-translator; the family is practically a Turkish humanities faculty.",
  facts:["'Karadut' (Black Mulberry), his most famous poem, is also the nickname of his great muse and model.",
    "His Expo 58 mosaic was rediscovered decades later and re-erected in Brussels in 2015.",
    "He printed designs on dresses, scarves and ties — wearable Anatolia, decades before 'artist collabs'."] },

{ id:"abidin-dino", name:"Abidin Dino", years:"1913–1993", born:1913, died:1993,
  nation:"turkey", eras:["20th-century"], movements:["surrealism","contemporary-art"],
  techniques:["oil-painting","watercolor","etching","mixed-media"], style:"contemporary",
  palette:["#3e4a5e","#c4542e","#8a9bb0","#e8dcc0","#1d1c22"],
  tagline:"'Can you paint happiness, Abidin?' — the line a poet hung on him forever",
  works:[{t:"Hands series",y:"1960s–80s"},{t:"Torture series",y:"1950s"},{t:"Flower drawings",y:"1980s"}],
  life:"Born into a cosmopolitan Istanbul family, Dino co-founded Turkey's modernist 'd Group' at twenty, drew for Soviet film studios in Leningrad, and was internally exiled to Anatolia in the 1940s for his politics — sketching cotton workers in Adana. From 1952 he lived in Paris with his wife, the literature scholar Güzin, at the centre of an extraordinary circle, and died there in 1993.",
  career:"A draughtsman above all — hands clasped, folded, pleading, multiplied across decades; flowers drawn in single unbroken lines; torture documented in ink when words were dangerous. His friendships were collaborations: he illustrated Nâzım Hikmet's poetry from exile to exile, and the poet immortalised him with the line 'can you paint the picture of happiness, Abidin?' — Turkish culture's gentlest impossible commission.",
  outside:"In Paris his studio hosted Picasso, Chagall, Cocteau and Yaşar Kemal between political exiles' kitchen tables; he art-directed the official film of the 1966 World Cup and made ceramics, sculpture and films. Tristan Tzara wrote a preface for him; Turkey eventually gave back every honour exile had cost.",
  facts:["Nâzım's 'happiness' line is quoted at Turkish weddings, funerals and election nights alike.",
    "The 'd Group' (1933) was founded in a Beyoğlu hat shop — five painters and a sculptor against academism.",
    "His Hands now open Istanbul Modern's collection displays — the emigrant's gesture, home for good."] }
);
