/* PIGMENT — artists 4/7 : Impressionists & Post-Impressionists */
window.ARTISTS.push(
{ id:"edgar-degas", name:"Edgar Degas", years:"1834–1917", born:1834, died:1917,
  nation:"france", eras:["19th-century","20th-century"], movements:["impressionism"],
  techniques:["pastel","oil-painting","printmaking"], style:"impressionist",
  palette:["#d9b4be","#8a9bb0","#e8dcc4","#5e4a44","#c4763e"],
  tagline:"Dancers from the wings — the Impressionist who hated the outdoors",
  works:[{t:"The Dance Class",y:"1874"},{t:"L'Absinthe",y:"1875–76"},{t:"Little Dancer Aged Fourteen",y:"1881"},{t:"Woman Combing Her Hair",y:"c. 1888–90"}],
  life:"Born into a Parisian banking family, Degas trained for law before classical drawing claimed him. He never married — 'there is love and there is work, and we have only one heart' — and grew increasingly isolated, his anti-Dreyfus stance costing him old friendships. Nearly blind, he ended his days wandering Paris streets, dying at eighty-three.",
  career:"Degas called himself a realist and scoffed at painting outdoors, yet co-organised the Impressionist exhibitions and out-modernised them all: ballet rehearsals seen from odd balconies, laundresses yawning, compositions cropped like snapshots under Japanese-print influence. Around 1,500 works treat dancers alone — not as glamour but as working bodies. As sight failed, he shifted to ever-bolder pastel and wax sculpture.",
  outside:"His Little Dancer in real tulle and human hair scandalised the 1881 exhibition — critics called her a 'rat' of the opera with a criminal's face. A pioneering art photographer and collector, he owned Ingres, Delacroix, El Greco and his colleagues' best works; its posthumous auction was a sensation.",
  facts:["He repurchased and reportedly destroyed earlier works he deemed unworthy.",
    "Some 150 wax sculptures were found in his studio after death; the bronzes, including the Little Dancer, were cast posthumously.",
    "'I want to be illustrious and unknown,' he said — and nearly managed both."] },

{ id:"camille-pissarro", name:"Camille Pissarro", years:"1830–1903", born:1830, died:1903,
  nation:"france", eras:["19th-century"], movements:["impressionism","neo-impressionism"],
  techniques:["oil-painting","broken-color","pointillism","etching"], style:"impressionist",
  palette:["#a8b88a","#d9c8a0","#7a8a9e","#8a6e4a","#e8e3d0"],
  tagline:"The patriarch — the only painter in all eight Impressionist exhibitions",
  works:[{t:"Boulevard Montmartre at Night",y:"1897"},{t:"The Red Roofs",y:"1877"},{t:"Hoarfrost",y:"1873"}],
  life:"Born on St Thomas in the Danish West Indies to a French-Jewish merchant family, Pissarro chose painting over the family business and Paris over the tropics. Gentle, principled and a convinced anarchist, he fathered eight children — five became painters — and held the quarrelsome Impressionists together by sheer decency until his death at seventy-three.",
  career:"The only artist to show in all eight Impressionist exhibitions, he was mentor to an improbable span: Cézanne ('humble and colossal Pissarro') worked beside him at Pontoise, Gauguin called him master, and at fifty-five he humbly adopted the pointillism of men half his age. When eye trouble ended outdoor work, he painted Paris boulevards from hotel windows — series that rival Monet's cathedrals.",
  outside:"His letters to his son Lucien form one of art's great correspondences: technique, politics, market despair and stubborn hope. His anarchist sympathies were sincere — he drew albums for libertarian journals and fled to Belgium during the 1894 crackdowns.",
  facts:["Prussian soldiers occupied his Louveciennes house in 1870 and used his canvases as duckboards — perhaps 1,400 early works were destroyed.",
    "Cézanne listed himself in a catalogue as 'pupil of Pissarro' at age 63.",
    "A Boulevard Montmartre canvas looted by the Nazis hung in dispute for decades — provenance history in one picture."] },

{ id:"berthe-morisot", name:"Berthe Morisot", years:"1841–1895", born:1841, died:1895,
  nation:"france", eras:["19th-century"], movements:["impressionism"],
  techniques:["oil-painting","watercolor","pastel","alla-prima"], style:"impressionist",
  palette:["#d9d3c8","#a8b8c4","#e8c8b8","#7a8a7e","#f2ece0"],
  tagline:"Impressionism's co-founder, painting at the speed of light itself",
  works:[{t:"The Cradle",y:"1872"},{t:"Summer's Day",y:"1879"},{t:"Young Woman Powdering Her Face",y:"1877"}],
  life:"Born into the haute bourgeoisie (and, family lore insisted, Fragonard's line), Morisot and her sister Edma trained seriously when art for women was meant to stay ornamental; Edma gave it up for marriage — their letters about it still sting. Berthe married Eugène Manet, Édouard's brother, who supported her career entirely, and died of influenza at fifty-four nursing her daughter Julie.",
  career:"A founder of the Impressionist exhibitions, she missed only the year of Julie's birth, and out-sold several male colleagues at the 1874 launch. Her brushwork is the movement's most daring — strokes so fast and open that figures seem about to dissolve into the air around them. The Cradle, her sister watching a sleeping infant through gauze, is Impressionism's quietest masterpiece.",
  outside:"Her salon gathered Renoir, Degas, Whistler and Mallarmé, who became Julie's guardian. She posed often for Manet — the woman with fan, violets, black ribbon — sittings whose intensity biographers still circle. Her death certificate read 'no profession.'",
  facts:["At the 1874 show, the critic who mocked everyone spared her least: 'five or six lunatics, one of them a woman.'",
    "Julie Manet's teenage diary is a key eyewitness source on the Impressionist circle.",
    "Her retrospective the year after her death was hung by Degas, Monet and Renoir personally."] },

{ id:"mary-cassatt", name:"Mary Cassatt", years:"1844–1926", born:1844, died:1926,
  nation:"usa", eras:["19th-century","20th-century"], movements:["impressionism"],
  techniques:["oil-painting","pastel","etching"], style:"impressionist",
  palette:["#e8c8b0","#a8c4b8","#d9a8a0","#f0e6d4","#5e6e6a"],
  tagline:"Pittsburgh's gift to Paris — mothers, children, and the modern print",
  works:[{t:"The Child's Bath",y:"1893"},{t:"Little Girl in a Blue Armchair",y:"1878"},{t:"The Boating Party",y:"1893–94"}],
  life:"Daughter of a Pittsburgh banker who declared he would 'almost rather see her dead' than an artist abroad, Cassatt moved to Paris anyway, the family eventually following her. She never married — 'a woman artist must be capable of making the primary sacrifices' — and painted until cataracts stopped her around 1914, dying at her château at eighty-two.",
  career:"Degas saw her Salon entry and recruited her: 'Here is someone who feels as I do.' The only American in the Impressionist exhibitions, she made the mother-and-child her laboratory — tender in subject, steely in design. Her 1891 colour-print series, fusing drypoint and aquatint with Japanese flatness, is one of printmaking's summits.",
  outside:"She steered America's great collectors — above all her friend Louisine Havemeyer — toward Degas, Manet and El Greco; the Havemeyer bequest seeded the Met's modern French holdings. A committed suffragist, she sold work to fund the cause when her family disapproved.",
  facts:["France made her a Chevalier of the Legion of Honour in 1904; her own country barely knew her name.",
    "Degas added the background figure to her Little Girl in a Blue Armchair — a unique collaboration.",
    "After 1910 she pushed her nieces' generation to buy Cézanne — early and right, as usual."] },

{ id:"james-whistler", name:"James McNeill Whistler", years:"1834–1903", born:1834, died:1903,
  nation:"usa", eras:["19th-century"], movements:["impressionism","symbolism"],
  techniques:["oil-painting","etching","lithography"], style:"colorfield",
  palette:["#26323e","#5e7286","#a8b4b8","#1a2026","#caa45c"],
  tagline:"Art for art's sake — nocturnes, a butterfly signature, and a lawsuit",
  works:[{t:"Arrangement in Grey and Black No. 1 (Whistler's Mother)",y:"1871"},{t:"Nocturne in Black and Gold — The Falling Rocket",y:"1875"},{t:"Symphony in White, No. 1",y:"1862"}],
  life:"Born in Lowell, Massachusetts, raised partly in St Petersburg, expelled from West Point ('Had silicon been a gas, I would have been a major general'), Whistler settled between London and Paris as a dandy, duelist of wit and one-man aesthetic movement. Bankrupted by his own libel suit, he rebuilt his fortunes in Venice etchings and died in London at sixty-nine.",
  career:"He titled paintings like music — arrangements, symphonies, nocturnes — insisting subject mattered less than harmony: his mother's portrait is, officially, an Arrangement in Grey and Black. His twilight Thames nocturnes dissolved the city into floating tone a generation before abstraction. When Ruskin accused him of 'flinging a pot of paint in the public's face,' Whistler sued — won a farthing, lost everything, and published the trial as comedy.",
  outside:"His Peacock Room — a shipping magnate's dining room repainted in blue and gold during the owner's absence, fee disputes included — is interior design as performance art, now reassembled in Washington. His barbed table-talk filled a book, The Gentle Art of Making Enemies.",
  facts:["Asked at trial how long a nocturne took: 'All my life.'",
    "He signed works with a stylised butterfly — armed with a stinger tail.",
    "Oscar Wilde: 'I wish I had said that.' Whistler: 'You will, Oscar, you will.'"] },

{ id:"john-singer-sargent", name:"John Singer Sargent", years:"1856–1925", born:1856, died:1925,
  nation:"usa", eras:["19th-century","20th-century"], movements:["impressionism","realism"],
  techniques:["oil-painting","watercolor","alla-prima"], style:"impressionist",
  palette:["#1d1a18","#e8ddc8","#8a8276","#5e3a3a","#b89a6a"],
  tagline:"The last grand portraitist — silk by the yard, in single strokes",
  works:[{t:"Madame X",y:"1884"},{t:"Carnation, Lily, Lily, Rose",y:"1885–86"},{t:"The Daughters of Edward Darley Boit",y:"1882"}],
  life:"Born in Florence to nomadic American expatriates, Sargent grew up multilingual in hotels and museums. The 1884 scandal of Madame X — a society beauty painted with one strap fallen (he repainted it raised) — drove him from Paris to London, where he became the age's portraitist. Unmarried and intensely private, he died in his sleep at sixty-nine, Beethoven open on the piano.",
  career:"Sargent could state a satin sleeve in one loaded stroke — bravura descended from Velázquez and Hals that made duchesses queue for years. Around 1907 he abruptly quit portraiture ('No more paughtraits!'), turning to dazzling travel watercolours and the Boston murals he considered his real legacy. As a war artist in 1918 he painted Gassed, a frieze of blinded soldiers, his grandest and gravest machine.",
  outside:"An excellent pianist and tireless friend to musicians, he painted Fauré and promoted his music in England. His private drawings and male nude studies, little shown in his lifetime, have driven a wholesale rereading of the man behind the gloss.",
  facts:["Madame X's mother begged him to withdraw the portrait; he refused, and later called it 'the best thing I have done.'",
    "He painted some 900 oils and over 2,000 watercolours while complaining portraiture was 'a pimp's profession.'",
    "Carnation, Lily, Lily, Rose required two years of ten-minute sessions at exact dusk light."] },

{ id:"vincent-van-gogh", name:"Vincent van Gogh", years:"1853–1890", born:1853, died:1890,
  nation:"netherlands", eras:["19th-century"], movements:["post-impressionism"],
  techniques:["oil-painting","impasto","broken-color","alla-prima"], style:"postimpressionist",
  palette:["#1a3a6b","#f4c430","#2e7d32","#c75b39","#e8e3d3"],
  tagline:"Ten years, nine hundred paintings, one sale — then the whole world",
  works:[{t:"The Starry Night",y:"1889"},{t:"Sunflowers",y:"1888"},{t:"The Potato Eaters",y:"1885"},{t:"Wheatfield with Crows",y:"1890"}],
  life:"A Dutch pastor's son who failed as art dealer, teacher and missionary before painting at twenty-seven, Van Gogh compressed an entire career into one decade, funded and steadied by his brother Theo. The Arles breakdown of 1888 — razor, severed ear, asylum at Saint-Rémy — led to a final furious year at Auvers, where he died of a gunshot wound at thirty-seven, Theo at his bedside.",
  career:"From the earth-dark Potato Eaters he vaulted, via Paris and Japanese prints, into colour as pure feeling: sunflowers like suns, a night sky churning over Saint-Rémy painted from his asylum window, cypresses twisting like green flames. Impasto became handwriting — every stroke visible, directional, urgent. In his last seventy days at Auvers he painted roughly seventy canvases.",
  outside:"His 800-plus letters, mostly to Theo, form one of literature's great documents of the inner life — reading lists, colour theory, loneliness, hope. He sold perhaps one painting in his lifetime (The Red Vineyard); Theo's widow Johanna van Gogh-Bonger then spent decades building his fame, publishing the letters and lending the canvases.",
  facts:["The ear went to a young woman at a brothel named in recent research as Gabrielle; the local paper reported it in two dry sentences.",
    "Doctors' diagnoses since: epilepsy, bipolar disorder, lead poisoning, Ménière's — the file remains open.",
    "Johanna van Gogh-Bonger, his sister-in-law, may be the most consequential non-painter in modern art history."] },

{ id:"paul-gauguin", name:"Paul Gauguin", years:"1848–1903", born:1848, died:1903,
  nation:"france", eras:["19th-century","20th-century"], movements:["post-impressionism","synthetism","symbolism"],
  techniques:["oil-painting","flat-color","woodblock"], style:"fauvist",
  palette:["#c4542e","#e89a3e","#6e3a5e","#2e6e5a","#f0d9a8"],
  tagline:"The stockbroker who fled the world — colour as myth, paradise as problem",
  works:[{t:"Vision After the Sermon",y:"1888"},{t:"Where Do We Come From? What Are We? Where Are We Going?",y:"1897–98"},{t:"Tahitian Women on the Beach",y:"1891"}],
  life:"Grandson of socialist firebrand Flora Tristan, raised partly in Peru, Gauguin was a sailor, then a prosperous Paris stockbroker with five children — until the 1882 crash and his own ambition blew the family apart. He left for Tahiti in 1891 chasing an unspoiled world that colonialism had already altered, and died poor and syphilitic in the Marquesas at fifty-four.",
  career:"At Pont-Aven he invented Synthetism: flat planes of unmixed colour bounded by dark line — a red field for a wrestling vision, because feeling outranks fact. His Tahitian canvases fused Polynesian motifs, Christian iconography and invented gods into modern art's most seductive and most contested paradise. The post-Impressionist generation — the Nabis, Fauves and Expressionists — built directly on his licence to lie with colour.",
  outside:"His nine fraught weeks with Van Gogh in Arles ended with the ear and a lifelong correspondence anyway. He wrote constantly — Noa Noa, journals, polemics — and carved, potted and printed; his conduct in Polynesia, including marriages to adolescent girls, is now central to how his work is read.",
  facts:["Where Do We Come From? was painted, he claimed, before a suicide attempt — he survived the arsenic and mailed the painting to France.",
    "He kept exhibition clippings pasted inside his Marquesan hut — fleeing the art world, subscribing to its press.",
    "His house beam carving read 'Maison du Jouir' — the House of Pleasure; the bishop next door was not amused."] },

{ id:"paul-cezanne", name:"Paul Cézanne", years:"1839–1906", born:1839, died:1906,
  nation:"france", eras:["19th-century","20th-century"], movements:["post-impressionism"],
  techniques:["oil-painting","watercolor","broken-color"], style:"fauvist",
  palette:["#6e8a5a","#d9a05e","#5b7a9e","#e8dcc0","#8a5e3e"],
  tagline:"'The father of us all' — apples that toppled five centuries of perspective",
  works:[{t:"Mont Sainte-Victoire series",y:"1880s–1906"},{t:"The Card Players",y:"1890–95"},{t:"The Large Bathers",y:"1898–1905"},{t:"The Basket of Apples",y:"c. 1893"}],
  life:"Son of an Aix-en-Provence banker whose money he resented and relied on, Cézanne was the school friend of Émile Zola — a bond broken when Zola's novel L'Œuvre portrayed a failed painter both recognised. Gruff, devout and pathologically thin-skinned, he withdrew to Aix and painted; caught in a storm at his easel in 1906, he died of pneumonia days later.",
  career:"Cézanne wanted to make of Impressionism 'something solid and durable, like the art of the museums': form built from patches of colour, perspective bent so a table tilts toward you, apples weightier than mountains, the same Mont Sainte-Victoire reconstructed dozens of times. The 1907 memorial retrospective stunned Picasso, Braque and Matisse — Cubism walked out of it, and 'the father of us all' (the phrase passes between Matisse and Picasso) stuck.",
  outside:"He sat models into agony — over a hundred sittings for a single portrait, with the warning 'Does an apple move?' He read Virgil in Latin, feared being 'hooked' by people touching him, and signed letters to friends 'pictor semper virens' — the ever-green painter.",
  facts:["He aimed 'to astonish Paris with an apple' — arguably the most successful fruit in art history.",
    "His banker father secretly doubted him but built him a studio; the Lauves studio survives, brushes in place.",
    "The Card Players' fifth version sold privately in 2011 for a reported $250 million-plus."] },

{ id:"georges-seurat", name:"Georges Seurat", years:"1859–1891", born:1859, died:1891,
  nation:"france", eras:["19th-century"], movements:["post-impressionism","neo-impressionism"],
  techniques:["oil-painting","pointillism","broken-color"], style:"pointillist",
  palette:["#7a9ab8","#a8c49a","#e8d9a8","#d9886e","#4a5a6e"],
  tagline:"Two years, three million dots — Sunday afternoon, frozen forever",
  works:[{t:"A Sunday Afternoon on the Island of La Grande Jatte",y:"1884–86"},{t:"Bathers at Asnières",y:"1884"},{t:"The Circus",y:"1890–91"}],
  life:"A quiet, methodical Parisian of independent means — colleagues called him 'the notary' for his composure — Seurat kept his common-law wife Madeleine Knobloch and their infant son secret even from his mother until days before his death. He died suddenly at thirty-one, probably of diphtheria or meningitis; his son died weeks later.",
  career:"Armed with the colour science of Chevreul and Rood, Seurat replaced Impressionist instinct with system: pure pigment in tiny dots, mixed by the eye at distance. La Grande Jatte — fifty-plus figures, a monkey on a leash, two years and some sixty studies — turned a riverside Sunday into a solemn frieze. In seven working years he produced six monumental canvases and a method (chromoluminarism) that marked Pissarro, Signac and, eventually, Op Art.",
  outside:"He worked in monkish routine, summered on the Channel coast painting harbours of impossible calm, and theorised that line direction itself carried emotion — upward for joy, downward for sadness — a proto-abstract idea his early death left hanging.",
  facts:["La Grande Jatte was mocked at the final Impressionist exhibition of 1886; it now anchors the Art Institute of Chicago.",
    "He repainted the painting's border in dots to control the transition to the frame.",
    "Stephen Sondheim built a musical, Sunday in the Park with George, from the canvas."] },

{ id:"henri-de-toulouse-lautrec", name:"Henri de Toulouse-Lautrec", years:"1864–1901", born:1864, died:1901,
  nation:"france", eras:["19th-century"], movements:["post-impressionism"],
  techniques:["lithography","oil-painting","pastel"], style:"pop",
  palette:["#c4302a","#1d1a20","#e8c84e","#5e7a8e","#e8ddc4"],
  tagline:"Montmartre by gaslight — the poster becomes art",
  works:[{t:"At the Moulin Rouge",y:"1892–95"},{t:"Moulin Rouge: La Goulue (poster)",y:"1891"},{t:"The Bed",y:"c. 1893"}],
  life:"Heir to one of France's oldest noble families, Lautrec inherited a bone disease — likely from his parents being first cousins — and after two teenage fractures his legs stopped growing. He moved into Montmartre's dance halls and brothels as resident chronicler rather than tourist, drank himself into collapse, and died at his mother's estate at thirty-six.",
  career:"His 1891 Moulin Rouge poster — La Goulue kicking against silhouetted top hats — made the street wall a gallery and lithography an art form overnight. He drew performers as workers with personal styles he revered: Jane Avril's nervous elegance, Yvette Guilbert's black gloves, the clowness Cha-U-Kao. His brothel paintings, tender and unsensational, treat the women's off-hours — waiting, laundering, sleeping — as the real subject.",
  outside:"A gourmet who co-wrote a cookbook of surreal recipes and invented cocktails — the 'Earthquake' mixed cognac and absinthe — he carried liquor in a hollowed walking cane. He befriended and portrayed Van Gogh in pastel, and defended his work in at least one near-duel.",
  facts:["He stood about 1.52 m; 'I am a half-bottle,' he joked, and signed some works with an elephant seal.",
    "His mother built his memorial museum in Albi — now home to the world's largest Lautrec collection.",
    "The Moulin Rouge hung his paintings in its foyer as advertising — art and venue promoting each other."] },

{ id:"henri-rousseau", name:"Henri Rousseau", years:"1844–1910", born:1844, died:1910,
  nation:"france", eras:["19th-century","20th-century"], movements:["naive-art"],
  techniques:["oil-painting","flat-color"], style:"naive",
  palette:["#1f4a2e","#3e7a46","#8ab05e","#d9b94e","#c4542e"],
  tagline:"Le Douanier — jungles dreamed by a man who never left France",
  works:[{t:"The Sleeping Gypsy",y:"1897"},{t:"Tiger in a Tropical Storm (Surprised!)",y:"1891"},{t:"The Dream",y:"1910"}],
  life:"A toll collector at the Paris customs gates — hence 'Le Douanier' — Rousseau took up painting seriously around forty, retired on a tiny pension at forty-nine, and lived hand-to-mouth giving violin lessons. Trusting to the point of fraud convictions (twice, naively implicated), widowed twice, he died of an infected leg at sixty-six, with seven mourners at the funeral.",
  career:"Critics laughed at his stiff perspective and solemn lions for twenty years of independent Salons; he serenely quoted the mockery as praise. His jungles — assembled from the Paris botanical gardens, taxidermy halls and magazine engravings — achieve a hallucinatory authority no academic could fake. Picasso, Apollinaire and Delaunay recognised the real thing: total pictorial conviction.",
  outside:"He claimed (falsely) to have seen Mexico with the army, played violin in the street, composed a waltz titled 'Clémence,' and wrote plays. In 1908 Picasso threw the famous Banquet Rousseau in his honour — half homage, half prank, wholly historic; Rousseau told Picasso: 'We are the two greatest painters of this era — you in the Egyptian style, I in the modern.'",
  facts:["The Sleeping Gypsy was rediscovered decades later and became a MoMA icon — and a Simpsons gag.",
    "He kept a sketchbook note: 'Don't forget the monkeys.'",
    "His tomb bears Apollinaire's verse, carved by Brancusi: 'Let our luggage pass duty-free through the gates of heaven.'"] },

{ id:"gustav-klimt", name:"Gustav Klimt", years:"1862–1918", born:1862, died:1918,
  nation:"austria", eras:["19th-century","20th-century"], movements:["art-nouveau","vienna-secession","symbolism"],
  techniques:["oil-painting","gold-leaf"], style:"ornament",
  palette:["#caa43e","#e8cd7a","#8a5e2e","#3e3a30","#a83a4e"],
  tagline:"Vienna gilded — desire wrapped in gold leaf",
  works:[{t:"The Kiss",y:"1907–08"},{t:"Portrait of Adele Bloch-Bauer I",y:"1907"},{t:"The Tree of Life",y:"1905–09"}],
  life:"Son of a Viennese gold engraver, Klimt rose painting theatre ceilings before leading the 1897 Secession revolt under the motto 'To every age its art, to art its freedom.' He never married, living with his mother and sisters while sustaining a lifelong bond with designer Emilie Flöge; paternity claims after his death (stroke and influenza, 1918) numbered around fourteen.",
  career:"His University ceiling paintings were condemned as pornography and 'perverted excess' — Klimt returned the fee and never accepted a public commission again. The Golden Phase answered with armour of ornament: Adele Bloch-Bauer dissolved into Byzantine mosaic, The Kiss making desire sacred. His landscapes, painted on Attersee holidays through a telescope-like viewfinder, are mosaics of another kind.",
  outside:"He worked in a blue painter's smock with (Vienna swore) nothing beneath, surrounded by cats and unfinished canvases. Mentor and protector to the young Schiele, he answered demands for a self-portrait: 'There is nothing special about me. Whoever wants to know something about me ought to look carefully at my pictures.'",
  facts:["Adele Bloch-Bauer I, looted by the Nazis, was recovered by her niece Maria Altmann in 2006 after a US Supreme Court case — then sold for a record $135 million.",
    "The University murals were burned by retreating SS troops in 1945; only photographs survive.",
    "The Kiss was bought by the Austrian state straight from the easel, unfinished, in 1908."] },

{ id:"edvard-munch", name:"Edvard Munch", years:"1863–1944", born:1863, died:1944,
  nation:"norway", eras:["19th-century","20th-century"], movements:["expressionism","symbolism"],
  techniques:["oil-painting","woodblock","lithography"], style:"expressionist",
  palette:["#d96e2e","#e8a84e","#3e5570","#8a3a3e","#1d1c22"],
  tagline:"The scream heard round the world",
  works:[{t:"The Scream",y:"1893"},{t:"Madonna",y:"1894–95"},{t:"The Sick Child",y:"1885–86"},{t:"The Dance of Life",y:"1899–1900"}],
  life:"Munch's childhood in Christiania (Oslo) was a hospital ward: mother dead of tuberculosis when he was five, beloved sister Sophie at fifteen — 'illness, insanity and death were the black angels that kept watch over my cradle.' Alcohol and a famous breakdown led to a Copenhagen clinic in 1908; he spent his last thirty years sober and solitary, painting on his estate outside Oslo.",
  career:"The Scream — a figure on a bridge under a blood sky, 'a scream passing through nature' — became modern anxiety's logo, one panel of his lifelong cycle The Frieze of Life: love, jealousy, illness, death, repainted in versions for decades. His raw, scraped canvases and pioneering woodcuts (grain left showing, blocks sawn like jigsaws) seeded German Expressionism directly.",
  outside:"A relationship with Tulla Larsen ended in 1902 with a revolver and part of a finger — his left hand carried the proof. The Nazis declared him degenerate and seized 82 works; he willed everything he still owned — over a thousand paintings — to the city of Oslo.",
  facts:["Versions of The Scream were stolen in 1994 and 2004; both eventually recovered.",
    "A hidden pencil inscription on the 1893 Scream — 'could only have been painted by a madman!' — was confirmed in 2021 as Munch's own hand.",
    "He left his canvases outdoors in snow and rain — the 'horse cure' — to roughen them up."] },

{ id:"henri-matisse", name:"Henri Matisse", years:"1869–1954", born:1869, died:1954,
  nation:"france", eras:["20th-century"], movements:["fauvism"],
  techniques:["oil-painting","flat-color","collage"], style:"fauvist",
  palette:["#c4302a","#2e5eaa","#2e8a5e","#e8c43e","#f2e8d8"],
  tagline:"King of the wild beasts — and, in the end, of scissors",
  works:[{t:"The Dance",y:"1910"},{t:"Woman with a Hat",y:"1905"},{t:"The Red Studio",y:"1911"},{t:"The Snail",y:"1953"}],
  life:"A grain merchant's son from the grey north of France, Matisse discovered painting at twenty during an appendicitis convalescence when his mother gave him a paint box: 'a kind of paradise.' Abandoning law, he weathered poverty with his formidable wife Amélie, became Picasso's great rival-friend, and after 1941 cancer surgery worked from bed and wheelchair in Nice until eighty-four.",
  career:"The 1905 Salon's 'cage of wild beasts' (fauves) made him notorious: a green stripe down his wife's face, colour freed from fact for what he called expression. The Dance — five vermilion figures wheeling on blue-green — distilled painting to colour, rhythm, joy. Bedridden, he invented a final medium, 'drawing with scissors': painted-paper cut-outs like Jazz and The Snail that are among the most radical works of his century.",
  outside:"He designed the Vence chapel complete — stained glass, vestments, altar — calling it his masterpiece despite lifelong agnosticism. His correspondence-duel with Picasso ('only one of us can have the North Pole') hid deep mutual dependence: after Matisse died, Picasso said simply, 'All things considered, there is only Matisse.'",
  facts:["Critics' label 'fauves' came from a sculpture in the same room — 'Donatello among the wild beasts!'",
    "Woman with a Hat was bought by Gertrude and Leo Stein, launching both his market and their salon.",
    "He kept doves; one became the model for Picasso's Peace Dove."] }
);
