/* PIGMENT — artists 13/13 : the world's moderns — São Paulo to Utopia */
window.ARTISTS.push(
{ id:"tarsila-do-amaral", name:"Tarsila do Amaral", years:"1886–1973", born:1886, died:1973,
  nation:"brazil", eras:["20th-century"], movements:["surrealism","naive-art"],
  techniques:["oil-painting","flat-color"], style:"naive",
  palette:["#2e8a5e","#f0c82e","#2e50c4","#c4663a","#e8d4b0"],
  tagline:"Abaporu — the painting that ate Europe",
  works:[{t:"Abaporu",y:"1928"},{t:"A Negra",y:"1923"},{t:"Antropofagia",y:"1929"}],
  life:"Daughter of São Paulo coffee wealth, Tarsila studied in Paris with Léger while resolving to be 'the painter of my country: the caipira girl from São Bernardo.' Her Abaporu, a birthday gift to her husband, the poet Oswald de Andrade, detonated Brazil's modernist 'cannibalist' movement. The 1929 crash took the fortune; she painted on through social realism and lyric returns until her death at eighty-six.",
  career:"Abaporu — a giant-limbed figure with a tiny head beside a cactus and lemon-slice sun — prompted Oswald's Anthropophagic Manifesto: Brazil should 'cannibalise' European culture, digest it, and make something its own. Her tropical palette ('pure blue, violacious rose... colours I was taught were ugly and caipira') and rounded forms built modern Brazilian painting's founding images.",
  outside:"A 1931 trip to the USSR converted her brushes briefly to workers' causes — and a São Paulo jail cell for a month in 1932. Late in life she became her own movement's archive, interviewed endlessly beneath the paintings that had once scandalised the coffee aristocracy she came from.",
  facts:["Abaporu means 'the man who eats people' in Tupi–Guarani — named after the manifesto it inspired.",
    "It sold in 1995 for $1.5M to Buenos Aires' MALBA — Brazil's most famous painting lives abroad, to national chagrin.",
    "MoMA's 2018 retrospective introduced 'Brazil's Picasso' to crowds who'd never heard her name — the title is backwards, Brazilians note: Picasso never painted an Abaporu."] },

{ id:"wifredo-lam", name:"Wifredo Lam", years:"1902–1982", born:1902, died:1982,
  nation:"cuba", eras:["20th-century"], movements:["surrealism","cubism"],
  techniques:["oil-painting","glazing"], style:"surreal",
  palette:["#1f4a2e","#3e7a46","#8a6e3a","#5e3450","#d9c8a4"],
  tagline:"The Jungle — Afro-Cuba reclaims modernism's masks",
  works:[{t:"The Jungle",y:"1943"},{t:"The Eternal Presence",y:"1944"},{t:"Zambezia, Zambezia",y:"1950"}],
  life:"Born in Sagua la Grande to a Chinese immigrant father — eighty-four at his birth — and a mother of African and Spanish descent, with a godmother who was a Santería priestess, Lam carried three continents in his name. He fought paint-shortages and Franco in Republican Spain, joined Picasso's circle in Paris, escaped Marseille on the same refugee ship as André Breton, and re-met Cuba in 1941 with transformed eyes. He died in Paris at seventy-nine.",
  career:"The Jungle — bamboo-limbed figures with crescent faces rising from sugarcane — hangs near MoMA's entrance as modernism's great reply to itself: Picasso had borrowed African masks; Lam took them home. His femme-cheval spirits, part horse, part orisha, fused Cubism, Surrealism and Santería into what he called 'a Trojan horse' inside Western painting.",
  outside:"Picasso embraced him as kin ('he has the right'); Breton had him illustrate his poem Fata Morgana. The sugar plantations in his canvases were politics: beauty with 'the power to disturb the dreams of the exploiters.'",
  facts:["The refugee ship from Marseille carried Lam, Breton and Lévi-Strauss — Surrealism's most overqualified passenger list.",
    "MoMA first hung The Jungle near the coat check; its promotion to the entrance hall tracked the canon's correction.",
    "His father was reportedly 84 when Wifredo was born — and lived past 100."] },

{ id:"tsuguharu-foujita", name:"Tsuguharu Foujita", years:"1886–1968", born:1886, died:1968,
  nation:"japan", eras:["20th-century"], movements:["expressionism"],
  techniques:["oil-painting","watercolor","etching"], style:"tonal",
  palette:["#e8e0d0","#a8a094","#3e3a36","#c4763e","#1d1a18"],
  tagline:"Montparnasse's bowl-cut dandy — milk-white skin drawn with a sumi line",
  works:[{t:"Reclining Nude with Toile de Jouy",y:"1922"},{t:"Self-Portrait with Cat",y:"1928"},{t:"Café",y:"1949"}],
  life:"Son of an Imperial Army doctor-general, Foujita left Tokyo's academy for 1913 Paris and became Montparnasse's most recognisable figure: bowl haircut, round glasses, gold earrings, a wristwatch tattooed on his wrist. WWII broke the idyll — he painted Japan's war effort and bore the blame after — and he ended a French citizen and Catholic convert, baptised 'Léonard' after Leonardo, dying in Zurich in 1968.",
  career:"His 'grand fond blanc' — a secret milky ground whose recipe died with him — let him draw on oil paint with sumi-ink line: nudes like warm porcelain, cats rendered hair by hair, the only Japanese painter the École de Paris treated as a first-rank star. Kiki of Montparnasse posed; the Salon swooned; his 1920s prices matched Picasso's.",
  outside:"He threw legendary costume balls, made his own clothes and lampshades, and wrote that he 'wished to live as a bridge'. The bridge burned twice — Japan resented the Paris dandy, France the war painter — and his final years built an actual chapel at Reims, frescoed by his own hand, where he is buried.",
  facts:["His Book of Cats (1930) is among the most coveted illustrated books ever auctioned.",
    "The white-ground recipe was reverse-engineered only decades later: talc, magnesium silicate — and Japanese line discipline.",
    "He tattooed a watch on his wrist 'to always have time' — Montparnasse's first wearable."] },

{ id:"qi-baishi", name:"Qi Baishi", years:"1864–1957", born:1864, died:1957,
  nation:"china", eras:["19th-century","20th-century"], movements:["realism"],
  techniques:["watercolor","gouache"], style:"tonal",
  palette:["#e8e0d0","#3e3a36","#c4302a","#8a9bb0","#1d1a18"],
  tagline:"Shrimp in ink — a carpenter who became China's most beloved brush",
  works:[{t:"Shrimp (countless versions)",y:"1920s–50s"},{t:"Eagle Standing on Pine Tree",y:"1946"},{t:"Twelve Landscape Screens",y:"1925"}],
  life:"Born to a poor farming family in Hunan, Qi Baishi worked as a carpenter until woodcarving led him to painting manuals and a late, self-taught start. He moved to Beijing at fifty-five, found his mature style around sixty, and painted into his nineties — dying in 1957 as the People's Republic's officially beloved 'People's Artist', with Picasso reportedly citing him with awe.",
  career:"His shrimp — translucent bodies in three tones of ink, antennae alive with current — took decades of refinement and a courtyard tank of live models; crabs, gourds, frogs and wisteria received the same devotion. 'The excellence of a painting lies between likeness and unlikeness,' he taught: too like is vulgar, too unlike is fraud. His Eagle Standing on Pine Tree sold in 2011 for $65 million, then the most expensive Chinese artwork ever auctioned.",
  outside:"He carved seals as masterfully as he painted, cut his own poems into stone, and famously posted studio price lists — payment strictly per subject, flattery no discount. Picasso, meeting Zhang Daqian, reportedly asked why Chinese artists came to Paris when China had Qi Baishi.",
  facts:["He raised shrimp in a bowl on his desk to study how light passed through them.",
    "A posted studio notice read, roughly: 'Selling paintings, fixed prices; do not bargain with an old man.'",
    "He produced an estimated 10,000+ works — and forgers, he joked, produced more."] },

{ id:"emily-carr", name:"Emily Carr", years:"1871–1945", born:1871, died:1945,
  nation:"canada", eras:["19th-century","20th-century"], movements:["post-impressionism","expressionism"],
  techniques:["oil-painting","watercolor"], style:"postimpressionist",
  palette:["#1f4a2e","#3e7a46","#5e8a96","#8ab05e","#2e3440"],
  tagline:"Rainforest in motion — the Pacific coast's late, great voice",
  works:[{t:"Big Raven",y:"1931"},{t:"Indian Church",y:"1929"},{t:"Above the Gravel Pit",y:"1937"}],
  life:"Born in Victoria, British Columbia, Carr studied in San Francisco, London and Paris, then spent decades unsellable — running a boarding house ('The House of All Sorts'), breeding sheepdogs, barely painting. A 1927 meeting with the Group of Seven — Lawren Harris's 'You are one of us' — relaunched her at fifty-six; heart attacks turned her to writing, and her first book won Canada's top literary prize. She died at seventy-three.",
  career:"Her journeys to First Nations villages produced the totem and longhouse canvases she saw as documents of cultures under siege; her late forests dispense with poles altogether — cedars swirling like green fire, sky scribbled in oil-on-paper gasoline washes of her own invention. Canada's modernist landscape has two inventors, and one wore a hairnet and pushed a pram full of monkey.",
  outside:"The pram carried Woo, her Javanese monkey, alongside sheepdogs, a white rat and a cockatoo, through Victoria's scandalised streets. Klee Wyck — 'Laughing One', the name Nuu-chah-nulth communities gave her — won the Governor General's Award in 1941; her journals remain Canadian literature's backbone.",
  facts:["She invented a cheap medium — house paint thinned with gasoline on manila paper — to sketch forests at speed.",
    "Contemporary curation pairs her totem canvases with First Nations artists' own voices — homage and appropriation debated side by side.",
    "Her caravan 'The Elephant' hauled her, the menagerie and easels into the woods each summer."] },

{ id:"aaron-douglas", name:"Aaron Douglas", years:"1899–1979", born:1899, died:1979,
  nation:"usa", eras:["20th-century"], movements:["harlem-renaissance"],
  techniques:["oil-painting","gouache","flat-color"], style:"artdeco",
  palette:["#3e3a52","#8a9bb0","#caa45c","#5e3450","#d9cdb8"],
  tagline:"Silhouettes in concentric light — the Harlem Renaissance's house style",
  works:[{t:"Aspects of Negro Life: From Slavery Through Reconstruction",y:"1934"},{t:"God's Trombones illustrations",y:"1927"},{t:"Into Bondage",y:"1936"}],
  life:"Born in Topeka, Kansas, Douglas taught high school until Harlem called in 1925; within months his graphics were the New Negro movement's visual signature. He painted the great Depression-era murals, earned a Columbia master's degree, and founded the art department at Fisk University, teaching twenty-nine years and dying in Nashville at seventy-nine.",
  career:"His style — flat silhouettes stepping through concentric circles of light, Egypt and Deco and jazz in one geometry — illustrated Locke's The New Negro, Johnson's God's Trombones and the covers of Crisis and Opportunity. The Schomburg Library's Aspects of Negro Life murals narrate slavery, Reconstruction and the urban North as one continuous procession: history painting reinvented as rhythm.",
  outside:"Du Bois and Locke competed to direct his talent (he quietly kept his own counsel); his Fisk murals made a Nashville library nave into the movement's southern cathedral. Students called him 'Dean' — of the department, and effectively of Black American art education.",
  facts:["He was called 'the father of Black American art' in his lifetime — a title he deflected to his students.",
    "The concentric-circle glow in his murals tracks spirituals' call-and-response — composition as music notation.",
    "His Crisis covers reached more Black households than any gallery of the era could."] },

{ id:"romare-bearden", name:"Romare Bearden", years:"1911–1988", born:1911, died:1988,
  nation:"usa", eras:["20th-century"], movements:["contemporary-art","harlem-renaissance"],
  techniques:["collage","photomontage","watercolor"], style:"cubist",
  palette:["#2e6e5a","#c4663a","#3e4a6e","#e8c89a","#1d1a18"],
  tagline:"Harlem, cut and pasted — jazz you can frame",
  works:[{t:"The Block",y:"1971"},{t:"Patchwork Quilt",y:"1970"},{t:"The Dove",y:"1964"}],
  life:"Born in Charlotte, North Carolina, and raised in Harlem — his mother's salon hosted Hughes and Ellington — Bearden balanced painting with a full-time New York social-work caseload for nearly three decades. The 1963 civil-rights summer turned him to collage at fifty-two; he became its American master, co-founding galleries and writing histories until his death at seventy-six.",
  career:"His Projections and the works after — sliced photographs, painted paper, fabric — reassembled Black Southern memory and Harlem streets into stained-glass jazz: conjur women, trains, baptisms, Saturday kitchens. The Block unrolls a Lenox Avenue façade six metres long, every window a life. MoMA's 1971 retrospective enthroned collage, long a 'minor' medium, at American art's centre.",
  outside:"He co-wrote the standard reference A History of African-American Artists, co-founded Spiral and the Cinque Gallery for young Black artists, and co-composed the jazz standard 'Sea Breeze', recorded by Billy Eckstine. Calypso royalty too: his songwriting credits include hits for Tito Puente's circle.",
  facts:["He kept his Department of Social Services job until 1969 — case files by day, collages by night.",
    "'Sea Breeze' made him perhaps the only canonical painter with a Billboard-charting song credit.",
    "The Bearden Foundation he endowed still funds young artists and scholars."] },

{ id:"alma-thomas", name:"Alma Thomas", years:"1891–1978", born:1891, died:1978,
  nation:"usa", eras:["20th-century"], movements:["abstract-art","color-field"],
  techniques:["acrylic-painting","watercolor"], style:"pointillist",
  palette:["#c4302a","#2e50c4","#f0c82e","#2e8a5e","#f0ece0"],
  tagline:"Mosaic gardens at 75 — the retired teacher who joined the space age",
  works:[{t:"The Eclipse",y:"1970"},{t:"Blast Off",y:"1970"},{t:"Resurrection",y:"1966"}],
  life:"Born in Columbus, Georgia, Thomas moved with her family to Washington DC to escape Jim Crow's worst, became Howard University's first fine-arts graduate, and taught junior-high art for thirty-five years. Full-time painting began at retirement, age 69, arthritis notwithstanding; her first major solo show came at 75, and she worked until her death at 86.",
  career:"Her signature arrived with the late start: irregular tiles of pure colour marching in stripes and circles — azalea gardens seen through wind, Earth seen from orbit (the Apollo missions thrilled her into a 'space series'). In 1972 she became the first Black woman given a solo show at the Whitney; in 2015, her Resurrection became the first work by a Black woman to hang in the White House Collection.",
  outside:"She watched the moon landing transfixed and painted Blast Off at seventy-nine: 'You look down on things. You streak through the clouds so fast you don't know whether the flower below is a violet or what.' Her Washington garden supplied six decades of colour notes.",
  facts:["Asked about bitterness over segregation-era limits: 'I've never bothered painting the ugly things in life... through colour I want to give happiness.'",
    "The Obamas hung her in the family dining room; a second Thomas entered the White House collection by 2015's acquisition.",
    "Her studio was her kitchen table; the late masterpieces left it rolled, in a teacher's tidy tubes."] },

{ id:"arshile-gorky", name:"Arshile Gorky", years:"c. 1904–1948", born:1904, died:1948,
  nation:"armenia", eras:["20th-century"], movements:["surrealism","abstract-expressionism"],
  techniques:["oil-painting","gestural-abstraction"], style:"surreal",
  palette:["#c4663a","#5e7250","#e8c87a","#8a3a4e","#2e3440"],
  tagline:"From Lake Van to Action Painting — the bridge AbEx walked across",
  works:[{t:"The Artist and His Mother",y:"c. 1926–36"},{t:"The Liver Is the Cock's Comb",y:"1944"},{t:"Agony",y:"1947"}],
  life:"Born Vostanik Adoian near Lake Van, Gorky survived the Armenian genocide's death marches; his mother died of starvation in his arms in 1919. In America he reinvented himself — the name claims kinship with Maxim Gorky — and taught himself painting by apprenticeship to Cézanne and Picasso 'in public', via museums. A 1946 studio fire, cancer, a neck-breaking car crash and a collapsing marriage preceded his suicide in 1948, at about forty-four.",
  career:"The Artist and His Mother, painted over a decade from a 1912 photograph, turns genocide's memory into one of the century's great double portraits — her hands left unfinished, washed like a fresco's ghost. His 1940s biomorphic landscapes — hybrids of Miró's signs, Kandinsky's weather and Connecticut meadows — handed Surrealism to the young New York School: de Kooning called him 'first' with no qualifiers.",
  outside:"He tutored friends in museums with proprietary fervour ('Look at this Ingres — look!'), invented aristocratic backstories, and farmed memories: the Virginia fields he painted merged with Van's orchards. His chalk-written farewell read 'Goodbye My Loveds.'",
  facts:["He claimed to be Maxim Gorky's cousin — unaware, colleagues noted, that 'Gorky' was itself the writer's pen name.",
    "Two versions of The Artist and His Mother exist (Whitney and Washington) — neither 'finished', both complete.",
    "Breton declared his Liver Is the Cock's Comb 'one of the most important paintings made in America' — Surrealism's blessing on AbEx's threshold."] },

{ id:"barnett-newman", name:"Barnett Newman", years:"1905–1970", born:1905, died:1970,
  nation:"usa", eras:["20th-century"], movements:["abstract-expressionism","color-field"],
  techniques:["oil-painting","flat-color"], style:"geometric",
  palette:["#c4302a","#8a2634","#e8e0d0","#1d1a18","#3e3a8a"],
  tagline:"The zip — one vertical line, carrying the sublime",
  works:[{t:"Onement I",y:"1948"},{t:"Vir Heroicus Sublimis",y:"1950–51"},{t:"The Stations of the Cross",y:"1958–66"}],
  life:"A Bronx-born son of Polish-Jewish immigrants, Newman wrote criticism, studied ornithology, taught substitute art classes — and once ran a write-in campaign for mayor of New York on a platform of clean air, playgrounds and a municipal opera. The painting that mattered began at forty-three, with a birthday experiment he stared at for eight months before deciding it was finished.",
  career:"Onement I — a cadmium 'zip' splitting a maroon field — became his lifelong instrument: vast colour walls (Vir Heroicus Sublimis runs five and a half metres) interrupted by vertical pulses meant to make the viewer feel, he said, their own scale and presence. Mocked at first even by AbEx peers, the zips became minimalism's permission slip; the Stations of the Cross cycle in raw canvas and black is his austere summa.",
  outside:"His essays ('The Sublime Is Now') argued American painting could start from zero, free of Europe's beauty. Gallery instructions specified viewing distance: close — 'large pictures are intimate.' Vandals slashed Who's Afraid of Red, Yellow and Blue twice in European museums; restorers and philosophers are still arguing.",
  facts:["The 1933 mayoral 'campaign' included a manifesto: On the Need for Political Action by Men of Culture.",
    "He kept his day jobs into his forties; Onement I was painted on his 43rd birthday.",
    "A Berlin restorer's repaint of a slashed Newman caused a second scandal bigger than the knife's."] },

{ id:"agnes-martin", name:"Agnes Martin", years:"1912–2004", born:1912, died:2004,
  nation:"canada", eras:["20th-century","21st-century"], movements:["minimalism","abstract-art"],
  techniques:["acrylic-painting","oil-painting"], style:"geometric",
  palette:["#d9d3c4","#a8b4b8","#e8e4d8","#8a9bb0","#caa45c"],
  tagline:"Hand-drawn grids, six feet of almost-nothing — 'my paintings are about happiness'",
  works:[{t:"Friendship",y:"1963"},{t:"With My Back to the World",y:"1997"},{t:"Untitled #10",y:"1995"}],
  life:"Born on a Saskatchewan farm, Martin swam at Olympic-trial level, taught school, and reached painting slowly via New Mexico and New York's Coenties Slip loft community. In 1967 — schizophrenia pressing, her building condemned, her friend Ad Reinhardt dead — she gave away her materials and vanished west, building an adobe home brick by brick. Seven years later the paintings resumed; she worked in Taos until ninety-two.",
  career:"Her six-foot squares carry pencil grids drawn freehand over whisper-pale washes — geometry that trembles, perfection deliberately humanised. Classed with minimalism, she insisted she was an abstract expressionist painting 'innocence of mind': titles like Friendship, I Love the Whole World. The late horizontal-band paintings are among the most serene objects in any museum — hard-won serenity, her biographers stress.",
  outside:"She lived by chosen austerity — years without newspapers, music or, famously, much furniture — writing lectures on humility and happiness that students traded like scripture. Mornings she waited for inspiration 'with an empty mind'; what arrived, she gridded.",
  facts:["She drove a pickup across the West for years between the two halves of her career.",
    "Her writings sell as philosophy: 'The adventurous state of mind is a high house.'",
    "Tate Modern's 2015 retrospective sealed her standing; the Taos light she chose is now part of how curators hang her."] },

{ id:"sidney-nolan", name:"Sidney Nolan", years:"1917–1992", born:1917, died:1992,
  nation:"australia", eras:["20th-century"], movements:["expressionism","surrealism"],
  techniques:["oil-painting","alla-prima"], style:"naive",
  palette:["#b0502e","#e8a85e","#2e3e8a","#e8dcc0","#1d1a18"],
  tagline:"Ned Kelly's black helmet riding an ochre horizon — Australia's myth, manufactured",
  works:[{t:"Ned Kelly",y:"1946"},{t:"Death of Constable Scanlon",y:"1946"},{t:"Riverbend",y:"1964–65"}],
  life:"A Melbourne tram-driver's son, Nolan deserted the army in 1944 and holed up at Heide, the hothouse home of patrons John and Sunday Reed, painting the first Ned Kelly series on their dining table. He left Australia in 1953 for London — knighthood, opera sets, global fame — but the desert and the outlaw never left the work. He died in London at seventy-five.",
  career:"His Kelly paintings — the bushranger's armour reduced to a black square with a letterbox slot of sky — gave Australia its defining modern image: part folk hero, part abstract sign, riding flat Ripolin-enamel deserts. Series followed series: the shipwrecked Mrs Fraser, Gallipoli, drought carcasses, Antarctic wastes — national mythology produced at industrial pace, some 35,000 works.",
  outside:"The triangle with Sunday Reed (lover, patron, and editor of the Kellys he left behind at Heide) shadowed Australian art history for decades; she eventually gave the first Kelly series to the nation. He collaborated with Benjamin Britten, painted opera safety curtains, and was knighted in 1981.",
  facts:["He painted the first Kelly series as an army deserter using a false name — outlaw painting outlaw.",
    "Sunday Reed donated 25 first-series Kellys to the National Gallery of Australia in 1977.",
    "Riverbend's nine panels stretch over nine metres — Kelly glimpsed through eucalypts like a film strip."] },

{ id:"emily-kame-kngwarreye", name:"Emily Kame Kngwarreye", years:"c. 1910–1996", born:1910, died:1996,
  nation:"australia", eras:["20th-century"], movements:["contemporary-art","abstract-art"],
  techniques:["acrylic-painting","gestural-abstraction","pointillism"], style:"pointillist",
  palette:["#b0502e","#e8a85e","#8ab05e","#5e3424","#f0e0a8"],
  tagline:"Eight years, three thousand paintings — a whole country's Dreaming, late and luminous",
  works:[{t:"Earth's Creation I",y:"1994"},{t:"Big Yam Dreaming",y:"1995"},{t:"Untitled (Alhalkere)",y:"1992"}],
  life:"An Anmatyerre elder from Utopia, north-east of Alice Springs, Kngwarreye worked stock camps and ceremony grounds for seven decades before touching acrylic paint around age seventy-eight, after a decade of community batik. In the eight years left to her she produced some three thousand canvases and became Australia's most celebrated painter; she died in 1996, having barely ever left her country, Alhalkere.",
  career:"Her surfaces evolved at decade-speed: dotted fields like seed-scatter, then raking parallel 'yam lines', then the bare, slabbed colour of the last years — each phase anchored in the yam, the emu, the ceremonial body-paint of Awelye. Big Yam Dreaming spans eight metres of white root-lines on black, painted in two days sitting cross-legged on the canvas. Asked what she painted, she answered: 'Whole lot. That's whole lot.'",
  outside:"Painting money supported a vast kin network — relatives, vehicles, ceremony — wealth handled as obligation, in the desert way. She represented Australia (posthumously) at the 1997 Venice Biennale; major retrospectives have since travelled to Japan and Europe's biggest museums.",
  facts:["Earth's Creation I sold for $2.1M in 2017 — a record for Australian female artists.",
    "Three thousand paintings in eight years averages a canvas a day — at eighty-plus years old.",
    "'Kame' in her name refers to the yam seed she painted all her life: signature as subject."] },

{ id:"ben-enwonwu", name:"Ben Enwonwu", years:"1917–1994", born:1917, died:1994,
  nation:"nigeria", eras:["20th-century"], movements:["contemporary-art"],
  techniques:["oil-painting","watercolor"], style:"fauvist",
  palette:["#2e8a5e","#b0703a","#e8c89a","#3e3a30","#8a3a4e"],
  tagline:"Tutu, the 'African Mona Lisa' — Negritude in oil and bronze",
  works:[{t:"Tutu",y:"1974"},{t:"Anyanwu",y:"1954–55"},{t:"The Dancers (Agbogho Mmuo series)",y:"1940s–80s"}],
  life:"Son of an Onitsha sculptor of Igbo ritual art, Enwonwu took a first-class Slade education to a career lived between worlds: Britain's galleries and Nigeria's independence, imperial commissions and African cultural nationalism. The first African artist to achieve global celebrity, he became independent Nigeria's cultural standard-bearer and died in Lagos in 1994.",
  career:"His Anyanwu — a bronze sun-goddess rising in welcome — stands at the National Museum in Lagos and the UN in New York: the new nation cast in confidence. The 1974 portrait Tutu, an Ife princess painted in profile serenity, became Nigeria's grail when all three versions vanished; one surfaced in a London flat in 2017 and sold for £1.2M as the country watched the auction live.",
  outside:"Queen Elizabeth II sat for him in 1956 — an African artist sculpting the empire's sovereign made world news and divided opinion exactly as he intended. He wrote and lectured on Negritude with Senghor's circle, demanding African modernism be modern and African without apology or permission.",
  facts:["Novelist Ben Okri called Tutu 'the African Mona Lisa'; its 2018 sale quadrupled the estimate.",
    "His royal sitting produced a bronze the Queen approved — and British tabloids couldn't process.",
    "Nigeria's national museum, currency vignettes and embassies all carry his designs — a one-man iconography."] },

{ id:"gerard-sekoto", name:"Gerard Sekoto", years:"1913–1993", born:1913, died:1993,
  nation:"south-africa", eras:["20th-century"], movements:["expressionism","realism"],
  techniques:["oil-painting","gouache"], style:"fauvist",
  palette:["#c4663a","#e8a85e","#2e4a6e","#8a3a4e","#e8d4b0"],
  tagline:"Sophiatown's chronicler — exile's long blue note in Paris",
  works:[{t:"Song of the Pick",y:"1947"},{t:"Yellow Houses, Sophiatown",y:"1940"},{t:"Self-Portrait",y:"1947"}],
  life:"Born on a Lutheran mission station in the Transvaal, Sekoto taught school before painting Johannesburg's Sophiatown, Cape Town's District Six and Pretoria's Eastwood — Black urban life rendered with tenderness the law denied it. In 1947 he left for Paris on a one-way ticket; apartheid hardened behind him, and he never returned, dying in a French retirement home in 1993.",
  career:"Song of the Pick — a line of road workers swinging picks in unison over a watching white overseer — is South African art's most reproduced image: labour as choreography, power as geometry. In Paris he survived playing jazz piano and singing in nightclubs while the paintings turned blue with distance — Senegalese sojourns and memory-Sophiatowns painted from an exile that lasted forty-six years.",
  outside:"In 1940 the Johannesburg Art Gallery bought his Yellow Houses — the first work by a Black South African artist to enter a museum collection there; he could visit it, at the time, only with difficulty. South Africa's democratic government posthumously awarded him the Order of Ikhamanga; his centenary was marked by national retrospectives.",
  facts:["He earned his Paris rent for years as a nightclub pianist — recordings of his songs survive.",
    "Yellow Houses entered the museum while its painter faced pass laws at the door.",
    "His unsold Paris-period works came home after 1994 — exile's archive, repatriated with democracy."] }
);
