/* PIGMENT — artists 10/13 : the wide 19th century */
window.ARTISTS.push(
{ id:"rosa-bonheur", name:"Rosa Bonheur", years:"1822–1899", born:1822, died:1899,
  nation:"france", eras:["19th-century"], movements:["realism"],
  techniques:["oil-painting","glazing"], style:"tonal",
  palette:["#8a6e46","#d9c890","#5e4a32","#a8b09a","#2e2a22"],
  tagline:"The Horse Fair — and a police permit to wear trousers",
  works:[{t:"The Horse Fair",y:"1852–55"},{t:"Ploughing in the Nivernais",y:"1849"},{t:"The Lion at Home",y:"1881"}],
  life:"Daughter of a Saint-Simonian socialist painter who believed in women's equality and taught her accordingly, Bonheur became the nineteenth century's most famous woman artist. She lived openly with Nathalie Micas for forty years, then with the American painter Anna Klumpke, on a château estate filled with her subjects — horses, lions, stags — and died at seventy-seven.",
  career:"The Horse Fair, a thundering five-metre frieze of Percherons, toured Britain and America to mobbed acclaim and now anchors the Met. She studied anatomy in slaughterhouses and horse markets — obtaining official police permission to wear men's trousers there, renewable every six months. Empress Eugénie personally brought her the Legion of Honour: 'genius has no sex.'",
  outside:"Her menagerie included lions (the lioness Fathma followed her like a dog), monkeys, mouflons and eighty-odd birds. Buffalo Bill, touring France, swapped her a Stetson for a portrait; she painted him on his white horse.",
  facts:["She was the first woman artist awarded the Grand Cross... rather, the first woman artist made Officer of the Legion of Honour.",
    "Her trouser permits — 'permission de travestissement' — survive in Paris police archives.",
    "Anna Klumpke became her heir and biographer; the three women share a grave at Père Lachaise."] },

{ id:"utagawa-hiroshige", name:"Utagawa Hiroshige", years:"1797–1858", born:1797, died:1858,
  nation:"japan", eras:["19th-century"], movements:["ukiyo-e"],
  techniques:["woodblock"], style:"ukiyoe",
  palette:["#2e4a72","#7aa7c4","#e8e0c8","#c4663a","#2a2c30"],
  tagline:"Rain you can hear — the poet of the Tōkaidō road",
  works:[{t:"The Fifty-three Stations of the Tōkaidō",y:"1833–34"},{t:"Sudden Shower over Shin-Ōhashi",y:"1857"},{t:"One Hundred Famous Views of Edo",y:"1856–58"}],
  life:"Born into a fire-brigade family in Edo's shogunal service, Hiroshige inherited the post at twelve when his parents died, passing it to relatives as printmaking claimed him. A journey along the Tōkaidō highway in 1832 fixed his life's subject: the road, the weather, the traveller. He died in a cholera epidemic at sixty-one, a lay monk.",
  career:"Where Hokusai gave nature drama, Hiroshige gave it weather and mood: slanting rain on the great bridge, snow hushing a village, travellers bent into wind. His Tōkaidō series was a publishing sensation, and the late Hundred Famous Views of Edo — with its radical croppings and aerial plunges — taught composition to the West: Van Gogh copied two plates in oil, stroke for stroke.",
  outside:"His deathbed poem bid farewell like a traveller: 'I leave my brush in the East / and set forth on my journey / to view the famous places of the Western Land.' Whistler's Thames and Monet's poplars are his unacknowledged students.",
  facts:["Van Gogh's painted copies of his Plum Park and Shin-Ōhashi rain hang in Amsterdam's Van Gogh Museum.",
    "The blue that floods his skies — imported Prussian blue — was the era's hot new pigment.",
    "He produced over 8,000 designs; the rain in Shin-Ōhashi is carved as needle-fine parallel lines."] },

{ id:"ivan-aivazovsky", name:"Ivan Aivazovsky", years:"1817–1900", born:1817, died:1900,
  nation:"armenia", eras:["19th-century"], movements:["romanticism"],
  techniques:["oil-painting","glazing"], style:"romantic",
  palette:["#1f3a5f","#7aa7c4","#e8c87a","#2e6e5a","#f0e8d8"],
  tagline:"Six thousand seas, painted entirely from memory",
  works:[{t:"The Ninth Wave",y:"1850"},{t:"Among the Waves",y:"1898"},{t:"The Black Sea",y:"1881"}],
  life:"Born Hovhannes Aivazian to a poor Armenian family in Crimean Feodosia, Aivazovsky rose through the St Petersburg Academy to become official painter of the Russian Navy and Europe's most celebrated marine artist. He never left his hometown for long, building it an art school, a museum and a water supply piped from his own estate, and died there at eighty-two.",
  career:"He painted some 6,000 canvases — nearly all the sea, nearly all from memory: 'the movement of living elements cannot be captured from nature.' The Ninth Wave, survivors clinging to a mast under a sun that might be salvation, is Russian Romanticism's signature image. His luminous water, glazed over decades-perfected formulas, fooled viewers into looking behind canvases for hidden lamps.",
  outside:"Lionised everywhere — ten one-man shows in Paris alone, honours from the Ottoman court — he reportedly hurled his Turkish medals into the sea after the 1890s massacres of Armenians, telling the consul the sultan could do the same with his paintings.",
  facts:["Chekhov coined the Russian idiom 'worthy of Aivazovsky's brush' for any indescribable scene.",
    "He gave Feodosia its water: 50,000 buckets a day from his Subash springs.",
    "He painted into his final day; The Explosion of the Turkish Flagship stood unfinished on the easel."] },

{ id:"ilya-repin", name:"Ilya Repin", years:"1844–1930", born:1844, died:1930,
  nation:"ukraine", eras:["19th-century","20th-century"], movements:["realism","peredvizhniki"],
  techniques:["oil-painting","alla-prima","chiaroscuro"], style:"tonal",
  palette:["#3e3a2a","#8a6e46","#d9c49a","#5e2a2a","#a8b09a"],
  tagline:"Russia's conscience on canvas — barge haulers, Cossacks, a tsar's bloody panic",
  works:[{t:"Barge Haulers on the Volga",y:"1870–73"},{t:"Reply of the Zaporozhian Cossacks",y:"1880–91"},{t:"Ivan the Terrible and His Son Ivan",y:"1885"}],
  life:"Born to a military-settler family in Chuguev, in what is now Ukraine, Repin trained as an icon painter before conquering the St Petersburg Academy. The realist Wanderers made him their standard-bearer; revolution made him an emigrant by geography — his home at Kuokkala ended up in independent Finland, where he stayed, declining Soviet invitations, until his death at eighty-six.",
  career:"Barge Haulers on the Volga — eleven men dragging a ship like a human harness — became the century's indictment of empire. His laughing Zaporozhian Cossacks took eleven years and a research expedition; his Ivan the Terrible, cradling the son he has just murdered, was slashed by a disturbed viewer in 1913 and attacked again in 2018 — realism that still draws blood.",
  outside:"When his right hand atrophied, he strapped his palette to his belt and painted with the left. His Penates estate ran on eccentric house rules — vegetarian dinners, a revolving table guests served themselves from, speeches by order of a gong.",
  facts:["Both attacks on Ivan the Terrible — 1913 and 2018 — required years of restoration; the painting now sits behind glass.",
    "Tolstoy, Mussorgsky and Mendeleev all sat for him — the whole Russian canon, by one hand.",
    "Ukraine and Russia both claim him; he signed letters from Finland 'a free artist.'"] },

{ id:"albert-bierstadt", name:"Albert Bierstadt", years:"1830–1902", born:1830, died:1902,
  nation:"usa", eras:["19th-century"], movements:["hudson-river-school","romanticism"],
  techniques:["oil-painting","glazing"], style:"romantic",
  palette:["#7a9a6e","#e8c87a","#5e4a32","#a8c4d9","#3e5238"],
  tagline:"The Rockies at opera scale — tickets at the door",
  works:[{t:"The Rocky Mountains, Lander's Peak",y:"1863"},{t:"Among the Sierra Nevada, California",y:"1868"},{t:"A Storm in the Rocky Mountains, Mt. Rosalie",y:"1866"}],
  life:"Born in Solingen and raised in Massachusetts, Bierstadt joined survey expeditions west in 1859 and 1863, sketching the Rockies, Yosemite and Oregon Trail. He built a Hudson River mansion on the proceeds of painting them enormous, watched taste turn against him, lost the mansion to fire and the market to Impressionism, and died nearly forgotten in 1902.",
  career:"His mountain panoramas — six feet by ten of golden light, waterfalls and improbable peaks — were exhibited as events: darkened rooms, curtains, admission fees, opera glasses recommended. Lander's Peak sold for $25,000, then the highest price for an American painting. Geologists grumbled the mountains were rearranged; audiences understood he was painting the national myth, not the map.",
  outside:"His canvases toured Europe convincing emigrants and investors that the West was paradise — landscape painting as advertising campaign. The 1882 fire at his studio-mansion Malkasten destroyed dozens of works and, effectively, his second act.",
  facts:["Congress bought his Discovery of the Hudson; railroads commissioned views the way airlines later shot commercials.",
    "He shipped a buffalo head east as a painting aid; The Last of the Buffalo (1888) was rejected by the Paris jury as old-fashioned.",
    "Modern curators reread him through environmental eyes — the Eden he sold was already vanishing."] },

{ id:"winslow-homer", name:"Winslow Homer", years:"1836–1910", born:1836, died:1910,
  nation:"usa", eras:["19th-century","20th-century"], movements:["realism","american-realism"],
  techniques:["oil-painting","watercolor","etching"], style:"romantic",
  palette:["#1f3a5f","#5e8ab0","#e8d9a8","#2e6e5a","#3a2e22"],
  tagline:"The sea, without sentiment — America's weather-beaten realist",
  works:[{t:"The Gulf Stream",y:"1899"},{t:"Breezing Up (A Fair Wind)",y:"1873–76"},{t:"Snap the Whip",y:"1872"}],
  life:"A Boston bookseller's son, Homer covered the Civil War as an illustrator for Harper's Weekly, taught himself oils, and spent twenty months in an English fishing village watching women haul nets against the North Sea — a turn that hardened his art. From 1883 he lived alone at Prouts Neck, Maine, painting the Atlantic until his death at seventy-four.",
  career:"His war scenes skipped the glory for boredom and aftermath; his post-war children and farm girls carry an elegy inside the sunlight. Then came the sea pictures: The Gulf Stream's becalmed Black sailor ringed by sharks, rescues, fog, the Maine surf pounding year after year — nature as adversary met with neither prayer nor panic. His Bahamas and Adirondacks watercolours are the medium's American summit.",
  outside:"Famously curt — 'the Sun will not rise, or set, without my notice, and thanks' is about as warm as the letters get — he gardened, fished and dodged interviewers. Asked to explain The Gulf Stream, he suggested anxious ladies be told the sailor would be rescued.",
  facts:["He requested his Harper's illustrations be credited 'Homer del.' — and quit illustration the moment oils paid.",
    "The Life Line (1884), a daring sea rescue, sold out as an etching — disaster as bestseller.",
    "His studio at Prouts Neck still stands; the Atlantic he painted is fifty feet away."] },

{ id:"john-everett-millais", name:"John Everett Millais", years:"1829–1896", born:1829, died:1896,
  nation:"britain", eras:["19th-century"], movements:["pre-raphaelites"],
  techniques:["oil-painting","glazing"], style:"renaissance",
  palette:["#2e6e5e","#a83a4e","#caa43e","#3b5a8a","#e8dcc4"],
  tagline:"Ophelia in the bathtub — Victorian England's prodigy",
  works:[{t:"Ophelia",y:"1851–52"},{t:"Christ in the House of His Parents",y:"1849–50"},{t:"The Blind Girl",y:"1856"}],
  life:"The youngest student ever admitted to the Royal Academy schools — aged eleven — Millais co-founded the Pre-Raphaelite Brotherhood at nineteen. He married Effie Gray after her scandalous annulment from the critic Ruskin, raised eight children, became a baronet and, months before dying at sixty-six, President of the very Academy his brotherhood had conspired against.",
  career:"Ophelia — painted petal by petal over a Surrey river, then over Elizabeth Siddal in a tin bath of cooling water — is Victorian art's most loved picture and a botanist's field guide. Dickens savaged his carpenter-shop Christ as blasphemous ugliness; the public eventually couldn't get enough, and his late Bubbles ended up, to highbrow horror, as a soap advertisement.",
  outside:"The Siddal bath sessions famously gave the model a severe chill; her father threatened suit until Millais paid the doctor's bills. His fluent late style made him among the richest artists alive — and a byword, for critics, of genius traded for income.",
  facts:["Bubbles became the face of Pears soap — fine art's first great advertising scandal.",
    "Ophelia's flowers are accurate enough that botanists catalogue the riverbank.",
    "He served as Academy president for less than a year before throat cancer killed him."] },

{ id:"dante-gabriel-rossetti", name:"Dante Gabriel Rossetti", years:"1828–1882", born:1828, died:1882,
  nation:"britain", eras:["19th-century"], movements:["pre-raphaelites","symbolism"],
  techniques:["oil-painting","watercolor"], style:"ornament",
  palette:["#5e2430","#caa43e","#2e6e5e","#8a4a3e","#e8dcc4"],
  tagline:"Painter-poet of obsessive beauty — and one exhumed manuscript",
  works:[{t:"Beata Beatrix",y:"c. 1864–70"},{t:"Proserpine",y:"1874"},{t:"The Blessed Damozel",y:"1875–78"}],
  life:"Son of an exiled Italian Dante scholar, Rossetti founded the Pre-Raphaelite Brotherhood in 1848 and lived as its bohemian heart. His wife and muse Elizabeth Siddal died of laudanum in 1862; grief, chloral and paranoia shadowed his later years in a Chelsea house full of exotic animals. He died at fifty-three.",
  career:"His watercolours and jewel-dense canvases replaced Victorian storytelling with mood: women — Siddal, Fanny Cornforth, Jane Morris — enlarged into icons of longing, half Madonna, half fate. Beata Beatrix transfigures the dead Siddal into Dante's Beatrice. As poet and painter at once, he made the double art a Pre-Raphaelite signature and fed directly into Symbolism and Aestheticism.",
  outside:"He buried his poetry manuscript in Siddal's coffin at Highgate — then, seven years later, sanctioned its exhumation and published the book. His Chelsea menagerie included peacocks, armadillos and a beloved wombat, mourned with a tearful self-caricature.",
  facts:["The wombat, 'Top', reportedly slept in the dinner-table epergne; neighbours' clauses later banned his peacocks.",
    "The exhumed poems made the 1870 volume a sensation — and a moral scandal.",
    "Proserpine's model Jane Morris, wife of his partner William Morris, was the late work's single obsession."] },

{ id:"gustave-moreau", name:"Gustave Moreau", years:"1826–1898", born:1826, died:1898,
  nation:"france", eras:["19th-century"], movements:["symbolism"],
  techniques:["oil-painting","watercolor","glazing"], style:"ornament",
  palette:["#3e3a52","#caa43e","#8a2634","#2e4a3e","#d9c8a4"],
  tagline:"Salomé in jewels — the hermit who taught the Fauves",
  works:[{t:"The Apparition",y:"c. 1876"},{t:"Oedipus and the Sphinx",y:"1864"},{t:"Jupiter and Semele",y:"1895"}],
  life:"A Paris architect's son of private means, Moreau lived almost monastically with his mother in a house he slowly converted into his own museum. Late in life he became the Beaux-Arts' most beloved professor; he died in 1898, leaving house and contents — thousands of works — to the state.",
  career:"His Salomé pictures — the dancer confronted by the Baptist's floating, blood-haloed head — distilled Symbolism before the word: myth re-dreamed as jewelled hallucination, every surface encrusted like a reliquary. Huysmans' novel À rebours canonised him as the decadents' painter; his unfinished abstractions of pure colour startle visitors who think abstraction began in 1910.",
  outside:"As teacher he formed Matisse, Marquet and Rouault, urging them toward themselves rather than himself — 'I am the bridge,' he said, 'over which some of you will pass.' His house-museum, preserved intact with its spiral staircase, is Paris's most concentrated single-artist shrine.",
  facts:["The Musée Gustave Moreau holds roughly 25,000 works — one address, one artist.",
    "Rouault, his favourite pupil, became the museum's first curator.",
    "André Breton called the museum his cathedral; the Surrealists adopted Moreau as a secret ancestor."] },

{ id:"odilon-redon", name:"Odilon Redon", years:"1840–1916", born:1840, died:1916,
  nation:"france", eras:["19th-century","20th-century"], movements:["symbolism"],
  techniques:["lithography","pastel","oil-painting"], style:"surreal",
  palette:["#3e3a52","#d97a8a","#e8c43e","#2e6e5a","#1d1c22"],
  tagline:"Floating eyes, smiling spiders — then, at fifty, an explosion of flowers",
  works:[{t:"The Eye Like a Strange Balloon Mounts Toward Infinity",y:"1882"},{t:"The Cyclops",y:"c. 1914"},{t:"Flower Clouds",y:"c. 1903"}],
  life:"A sickly Bordeaux child raised lonely on a remote estate, Redon studied botany with the naturalist Clavaud and drawing in darkness of his own temperament. For decades he worked in charcoal and lithography almost unknown; family happiness and a late conversion to colour transformed him, and he died at seventy-six amid pastels of impossible bloom.",
  career:"His 'noirs' — charcoal swamps where eyes balloon skyward and spiders smile — illustrated Poe and Flaubert and gave the Symbolists their dream-grammar. Then, around fifty, colour broke in: pastel bouquets, Buddhas, sea-floor light, the Cyclops peeking lovesick over a hill. The Surrealists claimed the first Redon; Matisse and the colourists, the second.",
  outside:"He insisted his monsters obeyed inner logic: 'placing the logic of the visible at the service of the invisible.' At the 1904 Salon d'Automne a whole room honoured him — vindication arriving, as he noted, precisely when he no longer needed it.",
  facts:["Huysmans' decadent hero in À rebours collects Redons — fiction advertising fact.",
    "His son Arï's birth is often credited with the turn to colour; biographers mostly agree with the sentiment.",
    "Botany stayed in the work: his flowers are inventions assembled from real anatomy."] },

{ id:"gustave-caillebotte", name:"Gustave Caillebotte", years:"1848–1894", born:1848, died:1894,
  nation:"france", eras:["19th-century"], movements:["impressionism","realism"],
  techniques:["oil-painting","glazing"], style:"impressionist",
  palette:["#8a9bb0","#d9d3c4","#5e6e7a","#b06a42","#2e3440"],
  tagline:"Paris in the rain — the Impressionist who bankrolled Impressionism",
  works:[{t:"Paris Street; Rainy Day",y:"1877"},{t:"The Floor Scrapers",y:"1875"},{t:"Man at His Window",y:"1875"}],
  life:"Heir to a textile fortune, Caillebotte painted, collected, sailed, gardened and underwrote the Impressionist exhibitions — often paying the rent and buying the unsold canvases. He died of a stroke at forty-five pruning roses in his Petit-Gennevilliers garden, leaving France a bequest that became the core of the Musée d'Orsay.",
  career:"The Floor Scrapers — shirtless workmen planing a parquet against the light — was rejected by the Salon for 'vulgar subject matter'; Paris Street; Rainy Day mapped the new Haussmann city with photographic plunge and umbrella-grey poise. Long filed as 'patron who painted', he has been re-rated as one of the movement's most original eyes.",
  outside:"Champion yachtsman and boat designer, rose-grower, and stamp collector of legend — the collection he built with his brother ended up, via a famous sale, in the British Library's founding philatelic holdings. His bequest of some 65 Impressionist masterpieces was fought over by the academy for years; France finally took about two-thirds.",
  facts:["The state initially refused parts of a gift that included Renoir's Moulin de la Galette and Manet's Balcony.",
    "He funded Monet's rent and bought Renoirs when nobody else would.",
    "Rainy Day's intersection still exists near Gare Saint-Lazare — tourists recreate the angle daily."] },

{ id:"paul-signac", name:"Paul Signac", years:"1863–1935", born:1863, died:1935,
  nation:"france", eras:["19th-century","20th-century"], movements:["neo-impressionism","post-impressionism"],
  techniques:["oil-painting","pointillism","watercolor"], style:"pointillist",
  palette:["#2e50c4","#e8a85e","#7ab0c4","#e8d9a8","#c4542e"],
  tagline:"Seurat's first mate — pointillism under full sail",
  works:[{t:"The Port of Saint-Tropez",y:"1901"},{t:"In the Time of Harmony",y:"1893–95"},{t:"The Papal Palace, Avignon",y:"1900"}],
  life:"A prosperous Paris shopkeeper's son, Signac abandoned architecture for painting after seeing Monet — then met Seurat in 1884 and became the dot's great apostle. A passionate sailor, he owned over thirty boats, discovered Saint-Tropez for art, presided over the Salon des Indépendants for decades, and died at seventy-one.",
  career:"After Seurat's early death, Signac systematised and loosened the method: bigger, mosaic-like strokes, ports in rainbow harmonies, watercolours quick as weather. His treatise From Eugène Delacroix to Neo-Impressionism gave the movement its theory and its genealogy; his presidency of the Indépendants made him the era's great gatekeeper-against-gatekeeping.",
  outside:"A committed anarchist, he named a boat after Manet's Olympia and painted In the Time of Harmony as a utopian answer to state murals. He bought Matisse's scandalous Luxe, Calme et Volupté off the 1905 wall — the old radical funding the new one.",
  facts:["He sailed one of his yachts to nearly every port he painted.",
    "His 1899 treatise converted a generation — including, briefly, Matisse and Mondrian — to the dot.",
    "Saint-Tropez was a fishing village until his canvases advertised its light."] },

{ id:"pierre-bonnard", name:"Pierre Bonnard", years:"1867–1947", born:1867, died:1947,
  nation:"france", eras:["19th-century","20th-century"], movements:["les-nabis","post-impressionism"],
  techniques:["oil-painting","lithography","glazing"], style:"fauvist",
  palette:["#e8a85e","#d97a8a","#7ab0c4","#8aa75e","#f0e8d8"],
  tagline:"Marthe in the bath, forever — colour as slow memory",
  works:[{t:"Nude in the Bath",y:"1936"},{t:"The Open Window",y:"1921"},{t:"Dining Room in the Country",y:"1913"}],
  life:"A reluctant law graduate turned 'very Japanese Nabi', Bonnard spent his life painting one woman: Marthe de Méligny, his model, companion and finally wife, whose long baths and fragile health structured their reclusive days in Normandy and Le Cannet. He outlived her by five years, dying in 1947 at seventy-nine.",
  career:"He painted from memory, never the motif — canvases tacked unstretched to the wall, colour adjusted for years until rooms glowed like recollection itself: tablecloths hotter than the Midi, Marthe ageless in violet bathwater. Dismissed by Picasso's circle as a 'potpourri of indecision', he has outlasted the dismissal; painters now study him like scripture for colour.",
  outside:"The famous anecdote has him revisiting his paintings in museums with a pocket paintbox while a friend distracted the guard — retouching after varnish, after sale, after decades. French has a verb for it: 'bonnardiser'.",
  facts:["Marthe appears in around 380 paintings — almost always as the young woman he first met in 1893.",
    "Days before dying he had a nephew change a green to gold on his last painting, Almond Tree in Blossom.",
    "His diary recorded daily weather in one word — the real subject, some say, of every canvas."] },

{ id:"suzanne-valadon", name:"Suzanne Valadon", years:"1865–1938", born:1865, died:1938,
  nation:"france", eras:["19th-century","20th-century"], movements:["post-impressionism"],
  techniques:["oil-painting","pastel","etching"], style:"fauvist",
  palette:["#8a4a3e","#2e6e5a","#d9a05e","#3e3a44","#e8d4b0"],
  tagline:"From trapeze to easel — the model who out-painted her painters",
  works:[{t:"The Blue Room",y:"1923"},{t:"Adam and Eve",y:"1909"},{t:"Self-Portrait",y:"1898"}],
  life:"Born to an unmarried laundress in Montmartre, Valadon was a circus acrobat until a trapeze fall at fifteen, then the neighbourhood's favourite model — for Puvis, Renoir, Toulouse-Lautrec — absorbing technique from the other side of the easel. Mother at eighteen of the painter Maurice Utrillo, she scandalised and conquered Paris, dying at seventy-two.",
  career:"Degas saw her drawings and bought them — 'you are one of us' — teaching her etching and pushing her into exhibition. Her nudes reversed the genre's politics: working women bathing on their own terms, her Blue Room odalisque smoking in striped pyjamas where Venus used to recline. She was among the first women admitted to the Société Nationale des Beaux-Arts.",
  outside:"Legend (well-fed by Valadon herself) says she kept a goat in the studio to eat her bad drawings and fed her cats caviar on Fridays. Her marriage to André Utter, twenty-one years younger, made the Valadon-Utter-Utrillo household Montmartre's most combustible artistic firm.",
  facts:["Her son Utrillo's alcoholism was managed partly by setting him to paint — the cure became a career.",
    "Adam and Eve (1909), herself with Utter, was among the first female-painted male nudes shown publicly — fig leaf added for the Salon.",
    "Lautrec reportedly suggested the name 'Suzanne' — the model among the elders."] },

{ id:"joaquin-sorolla", name:"Joaquín Sorolla", years:"1863–1923", born:1863, died:1923,
  nation:"spain", eras:["19th-century","20th-century"], movements:["impressionism","realism"],
  techniques:["oil-painting","alla-prima"], style:"impressionist",
  palette:["#f2d9a0","#7ab0c4","#e8e0d0","#c4763e","#2e5e8a"],
  tagline:"Valencia at noon — nobody ever painted sunlight wetter",
  works:[{t:"Walk on the Beach",y:"1909"},{t:"Sad Inheritance",y:"1899"},{t:"Vision of Spain",y:"1913–19"}],
  life:"Orphaned at two by cholera and raised by an aunt and locksmith uncle in Valencia, Sorolla painted his way to international stardom — gold medals, packed shows in Paris, London and New York. A stroke felled him mid-portrait in his garden in 1920; he died three years later at sixty, his Madrid house now one of Europe's most loved house-museums.",
  career:"His beach scenes — children glistening, mothers in white, oxen hauling sails out of a violet sea — made sunlight itself the protagonist, brushed wet and fast at full scale on the sand. Sad Inheritance, polio-stricken boys bathing under a monk's care, won Paris's Grand Prix. The Hispanic Society's Vision of Spain consumed his last decade: fourteen monumental panels painted province by province, on location.",
  outside:"He painted standing in the surf under a huge hat, canvases lashed against the wind, working 'like a man possessed by light'. His friendship-rivalry with the American Sargent ran on mutual awe; New York's 1909 Sorolla exhibition drew 160,000 visitors in a month.",
  facts:["The Hispanic Society commission ran to roughly 70 metres of canvas — he called it 'my life sentence'.",
    "He painted the Spanish king on horseback outdoors, in sittings the horse tolerated better than the monarch.",
    "His garden-studio in Madrid preserves brushes, unfinished portrait and all — frozen at the stroke."] },

{ id:"vilhelm-hammershoi", name:"Vilhelm Hammershøi", years:"1864–1916", born:1864, died:1916,
  nation:"denmark", eras:["19th-century","20th-century"], movements:["symbolism","realism"],
  techniques:["oil-painting","glazing"], style:"tonal",
  palette:["#8a9bb0","#d9d3c4","#5e6e7a","#3a4450","#e8e4d8"],
  tagline:"Grey rooms, a woman's turned back — silence you can hang on a wall",
  works:[{t:"Interior with Young Woman from Behind",y:"c. 1904"},{t:"Dust Motes Dancing in the Sunbeams",y:"1900"},{t:"Interior, Strandgade 30",y:"1901"}],
  life:"A Copenhagen merchant's son, Hammershøi lived quietly with his wife Ida, painting their successive apartments — above all Strandgade 30 — in greys, whites and the dust of northern light. Renowned but reticent in his lifetime, he died of throat cancer at fifty-one, then slid into decades of obscurity before a triumphant rediscovery.",
  career:"He painted perhaps sixty views of his own rooms: doors ajar onto further doors, Ida from behind reading or simply standing, sunlight crossing a floor as the day's whole event. The palette rarely exceeds grey, white, black and a breath of ochre — yet the stillness hums; critics reach for Vermeer, then note that Hammershøi removed even Vermeer's stories.",
  outside:"Rilke met him, planned an essay and confessed defeat before the silence. Contemporaries found the man like the paintings — courteous, unknowable; he gave almost no interviews and left almost no writings.",
  facts:["He repainted the same rooms with furniture removed — reality edited toward emptiness.",
    "London fog disappointed him on a visit: too dramatic.",
    "His revival since the 1990s has made him Denmark's most internationally exhibited painter."] }
);
