/* PIGMENT — artists 2/7 : Baroque & the 18th century */
window.ARTISTS.push(
{ id:"peter-paul-rubens", name:"Peter Paul Rubens", years:"1577–1640", born:1577, died:1640,
  nation:"belgium", eras:["17th-century"], movements:["flemish-baroque","baroque"],
  techniques:["oil-painting","glazing","alla-prima"], style:"baroque",
  palette:["#a8412e","#e0b380","#3b5570","#d9cdb4","#5e3424"],
  tagline:"Painter, diplomat, one-man industry of abundance",
  works:[{t:"The Descent from the Cross",y:"1612–14"},{t:"The Marie de' Medici Cycle",y:"1622–25"},{t:"The Garden of Love",y:"c. 1633"}],
  life:"Born in exile in Germany to an Antwerp family, Rubens combined a humanist's education with eight years in Italy before settling in Antwerp as the most successful painter in Europe. Widowed at fifty-three, he scandalised and charmed society by marrying sixteen-year-old Hélène Fourment, retired to a country castle, and died of gout at sixty-two, wealthy beyond any painter before him.",
  career:"His workshop produced some 1,400 works — altarpieces, royal cycles, hunts, allegories — with Rubens designing, retouching and pricing according to how much was 'entirely by my own hand.' The Marie de' Medici cycle turned a difficult queen's biography into twenty-four canvases of upholstered mythology. His swirling compositions and pearlescent flesh fixed the meaning of 'Baroque' — and of 'Rubenesque.'",
  outside:"Fluent in five or six languages, he doubled as a trusted diplomat, knighted by both Philip IV of Spain and Charles I of England after helping negotiate their peace in 1630. He rose at four, heard daily Mass, and worked while a reader recited Tacitus aloud — visitors described the studio as a court in itself.",
  facts:["He was knighted by two enemy kings — for diplomacy, not painting.",
    "His house in Antwerp, an Italian palazzo of his own design, is now a museum.",
    "He wrote that he preferred small commissions 'entirely by my own hand' — then accepted every enormous one anyway."] },

{ id:"anthony-van-dyck", name:"Anthony van Dyck", years:"1599–1641", born:1599, died:1641,
  nation:"belgium", eras:["17th-century"], movements:["flemish-baroque","baroque"],
  techniques:["oil-painting","glazing","etching"], style:"baroque",
  palette:["#1d2430","#6e3a2a","#c8a86e","#8a9bb0","#e6dcc8"],
  tagline:"The man who taught aristocracy how to look effortless",
  works:[{t:"Charles I at the Hunt",y:"c. 1635"},{t:"Equestrian Portrait of Charles I",y:"c. 1637–38"},{t:"Self-Portrait with a Sunflower",y:"c. 1632"}],
  life:"An Antwerp silk merchant's son and child prodigy, Van Dyck was running his own studio in his teens and serving as Rubens's chief assistant by nineteen. After years in Genoa painting its nobility into elegance, he settled in London in 1632 as court painter to Charles I, was knighted within months, and died at just forty-two as the king's world slid toward civil war.",
  career:"Van Dyck invented the aristocratic portrait as we know it: elongated figures, liquid silk, hands of impossible refinement, and an air of melancholy command. His portraits of Charles I — hunting, mounted, in triple view for a sculptor — are royal image-making at its most sophisticated. English portraiture from Gainsborough to Sargent is one long footnote to him.",
  outside:"Famously elegant — 'his manners were those of a lord' — he kept musicians and a fashionable table, and his liaison and later marriage into Scottish nobility tied him to the court he glamorised. His etched portrait series, the Iconographie, recorded the faces of his age with startling freshness.",
  facts:["The pointed 'Van Dyke' beard is named after him.",
    "He painted Charles I's head from three angles on one canvas so Bernini could carve a bust in Rome.",
    "He was buried in Old St Paul's Cathedral, which burned in the Great Fire of 1666."] },

{ id:"rembrandt", name:"Rembrandt van Rijn", years:"1606–1669", born:1606, died:1669,
  nation:"netherlands", eras:["17th-century"], movements:["dutch-golden-age","baroque"],
  techniques:["oil-painting","impasto","chiaroscuro","etching"], style:"baroque",
  palette:["#1a140e","#4a3520","#9c6b2f","#d9aa4e","#e8d9b0"],
  tagline:"Gold out of gloom — the painter of the human soul",
  works:[{t:"The Night Watch",y:"1642"},{t:"Self-Portrait with Two Circles",y:"c. 1665–69"},{t:"The Jewish Bride",y:"c. 1665"},{t:"The Anatomy Lesson of Dr Tulp",y:"1632"}],
  life:"A Leiden miller's son, Rembrandt conquered Amsterdam in his twenties, married the patrician Saskia van Uylenburgh, and bought a house far beyond his means. Then the long fall: Saskia's death in 1642, bankruptcy in 1656, the deaths of his companion Hendrickje and his son Titus — until he was buried in 1669 in a rented, unmarked church grave.",
  career:"Across portraits, biblical scenes and some eighty self-portraits, Rembrandt traded Baroque theatre for inner weather: light that seems to come from inside the people. The Night Watch turned a routine militia portrait into a thunderclap of movement. His late style — paint troweled, scraped and dragged into almost abstract crusts — was called unfinished by contemporaries and is called miraculous now.",
  outside:"He compulsively collected — armour, shells, Mughal miniatures, busts, exotic stuffed creatures — a hoard that helped bankrupt him and was auctioned off in lots. As an etcher he was equally revolutionary, reworking plates state by state; collectors across Europe prized his prints even as Amsterdam's portrait market cooled toward him.",
  facts:["Roughly one in ten of his paintings is a self-portrait — an autobiography in oil spanning forty years.",
    "The Night Watch is actually a daytime scene; centuries of darkened varnish named it.",
    "In 1642 he was paid about 1,600 guilders for The Night Watch — and in 1656 his entire collection couldn't cover his debts."] },

{ id:"johannes-vermeer", name:"Johannes Vermeer", years:"1632–1675", born:1632, died:1675,
  nation:"netherlands", eras:["17th-century"], movements:["dutch-golden-age","baroque"],
  techniques:["oil-painting","glazing"], style:"baroque",
  palette:["#2b4a6e","#d9b94e","#e9e2cf","#7a8a96","#3a3026"],
  tagline:"Thirty-some paintings of daylight, and three centuries of silence",
  works:[{t:"Girl with a Pearl Earring",y:"c. 1665"},{t:"The Milkmaid",y:"c. 1658–60"},{t:"View of Delft",y:"c. 1660–61"},{t:"The Art of Painting",y:"c. 1666–68"}],
  life:"Vermeer spent his whole life in Delft, running the family inn and art-dealing business, converting to Catholicism for marriage, and fathering fifteen children, eleven of whom survived. The French invasion year of 1672 collapsed the art market; three years later he died at forty-three, in debt, leaving his widow to plead that the war had ruined them.",
  career:"Perhaps thirty-six paintings survive — mostly a single quiet room, a window on the left, a woman reading, pouring, weighing. Within that whisper of a subject Vermeer achieved the most perfect light in Western art, laying pearls of paint and ultramarine he could barely afford. Forgotten for two centuries, he was resurrected by the French critic Thoré-Bürger in 1866 and has never left the world's imagination since.",
  outside:"He may have used optical aids — the camera obscura debate still rages — but no documents, drawings or pupils survive to tell us. His patron Pieter van Ruijven quietly bought half his output, which is partly why so little ever circulated.",
  facts:["He used costly lapis-lazuli ultramarine even on underlayers — luxury hidden beneath luxury.",
    "Forger Han van Meegeren sold fake Vermeers to Hermann Göring, then proved the forgery in court by painting one.",
    "Girl with a Pearl Earring is nicknamed 'the Mona Lisa of the North'; the 'pearl' is five or six strokes of paint."] },

{ id:"frans-hals", name:"Frans Hals", years:"c. 1582–1666", born:1582, died:1666,
  nation:"netherlands", eras:["17th-century"], movements:["dutch-golden-age","baroque"],
  techniques:["oil-painting","alla-prima"], style:"impressionist",
  palette:["#23201c","#8a8276","#caa45c","#5e2a2a","#e8e0d0"],
  tagline:"The fastest smile in the Dutch Golden Age",
  works:[{t:"The Laughing Cavalier",y:"1624"},{t:"Banquet of the Officers of the St George Militia",y:"1616"},{t:"Malle Babbe",y:"c. 1633–35"}],
  life:"Born in Antwerp, raised in Haarlem after his family fled the Spanish, Hals spent his life in that one city — painting its militias, merchants, fishwives and drinkers. Father of many children on a painter's unsteady income, he ended his days on a small municipal pension from the city he had immortalised, dying at about eighty-four.",
  career:"Hals painted speed itself: slashing, visible strokes that snap into silk, lace and grins at viewing distance. His great militia banquets solved the group portrait a generation before Rembrandt, and his late, nearly monochrome regents' portraits are as raw as anything painted before the modern era. The Impressionists made pilgrimages to Haarlem — Manet and Van Gogh studied him like scripture.",
  outside:"Archives show an ordinary, hard-pressed civic life — guild offices, small debts, a baker's lien on his property — rather than the legendary drunkard later biographers invented from his tavern subjects.",
  facts:["Courbet, Manet, Whistler and Van Gogh all copied or praised him; Van Gogh counted '27 blacks' in his palette.",
    "The Laughing Cavalier isn't laughing — the title was invented by Victorian critics.",
    "He painted his only collaboration with a woman artist, Judith Leyster's circle, in a city where she was his most gifted follower."] },

{ id:"diego-velazquez", name:"Diego Velázquez", years:"1599–1660", born:1599, died:1660,
  nation:"spain", eras:["17th-century"], movements:["baroque"],
  techniques:["oil-painting","alla-prima","chiaroscuro"], style:"baroque",
  palette:["#2a2622","#7a4a3a","#b89a6a","#46586a","#e3d8c4"],
  tagline:"The painter's painter — truth at court, mirrors within mirrors",
  works:[{t:"Las Meninas",y:"1656"},{t:"Portrait of Innocent X",y:"1650"},{t:"The Surrender of Breda",y:"1634–35"},{t:"Rokeby Venus",y:"c. 1647–51"}],
  life:"A Seville prodigy who married his teacher's daughter, Velázquez became court painter to Philip IV at twenty-four and spent his life inside the Spanish palace, rising through courtly offices to knighthood in the Order of Santiago. He died at sixty-one, weeks after exhausting himself organising a royal wedding on the French border.",
  career:"From bodegón kitchen scenes to popes and kings, Velázquez painted what was actually there — air included. Innocent X muttered 'troppo vero' (too true) of his portrait; Las Meninas, the infanta and her court caught mid-moment with the painter himself at his easel, remains painting's supreme riddle about looking. His feathery late brushwork, dissolving at close range, made Manet call him 'the painter of painters.'",
  outside:"Court duties consumed him — decorating, ceremonies, quarters assignments — leaving perhaps 120 paintings from a forty-year career. In Rome he painted his enslaved assistant Juan de Pareja, then freed him; Pareja became a painter in his own right.",
  facts:["The red cross of Santiago on his chest in Las Meninas was added after his death — legend says by the king's own hand.",
    "His Rokeby Venus was slashed by suffragette Mary Richardson in 1914 in protest at Emmeline Pankhurst's arrest.",
    "Manet, Whistler, Bacon and Picasso (44 variations on Las Meninas) all rebuilt their art around him."] },

{ id:"georges-de-la-tour", name:"Georges de La Tour", years:"1593–1652", born:1593, died:1652,
  nation:"france", eras:["17th-century"], movements:["baroque"],
  techniques:["oil-painting","tenebrism","chiaroscuro"], style:"baroque",
  palette:["#120c08","#7a2e14","#d9852e","#f0c878","#3a2416"],
  tagline:"One candle against the dark",
  works:[{t:"The Penitent Magdalene",y:"c. 1640"},{t:"The Cheat with the Ace of Diamonds",y:"c. 1636–38"},{t:"Joseph the Carpenter",y:"c. 1642"}],
  life:"A baker's son from Lorraine who married into minor nobility, La Tour grew wealthy and reportedly unpopular in plague- and war-ravaged Lunéville, where archives record grain dealing and sharp lawsuits alongside his royal title of 'Painter to the King.' He died in an epidemic in 1652 — and was then utterly forgotten for over 250 years.",
  career:"La Tour reduced Caravaggism to its essence: a single candle, a circle of faces, geometry smoothed almost to abstraction. By day he painted cheats and fortune tellers fleecing velvet-clad dupes; by night, Magdalenes staring into flames. Rediscovered by scholars in 1915 from a handful of signed canvases, he now stands among the unmistakable styles of the century — roughly forty paintings carry his whole fame.",
  outside:"Documents show him quarrelling over taxes, hunting rights and beaten peasants — an abrasive squire whose serenely silent paintings could hardly contrast more with his court records.",
  facts:["His entire modern reputation was rebuilt in the twentieth century from archival detective work.",
    "He often painted the same composition twice or more; both versions of The Cheat hang an ocean apart.",
    "His candle flames are sometimes shielded by a hand glowing red — a trick Wright of Derby revived a century later."] },

{ id:"nicolas-poussin", name:"Nicolas Poussin", years:"1594–1665", born:1594, died:1665,
  nation:"france", eras:["17th-century"], movements:["baroque","neoclassicism"],
  techniques:["oil-painting","glazing"], style:"neoclassical",
  palette:["#3b5a8a","#b0703a","#6e8a5a","#d9c8a4","#2e3a2c"],
  tagline:"Reason's painter — antiquity rebuilt one wax figurine at a time",
  works:[{t:"Et in Arcadia Ego",y:"c. 1638"},{t:"The Abduction of the Sabine Women",y:"c. 1634"},{t:"The Four Seasons",y:"1660–64"}],
  life:"A Norman farmer's son who walked to Paris and then, at thirty, to Rome, Poussin stayed there for the rest of his life — apart from a miserable two-year recall to decorate the Louvre, which he fled. Frugal and severe, he lived quietly with his wife near the Spanish Steps, painting slowly for a circle of learned collectors until his hands shook too much to hold a brush.",
  career:"Poussin composed like a philosopher: stoic shepherds, measured tragedies and landscapes ordered like arguments. He built miniature stage sets with wax figures to perfect each composition, sometimes taking years per canvas. French academic doctrine canonised him as the patron saint of line over colour — and three centuries later Cézanne declared his ambition was 'to redo Poussin from nature.'",
  outside:"His letters constitute a treatise on art and conduct; visitors found him discoursing on the ruins as 'a professor of antiquity.' He declined court honours, observing that the climb at court was paved with humiliations he preferred to study at a distance.",
  facts:["He turned down the directorship of France's royal academy to keep his Roman solitude.",
    "Et in Arcadia Ego — shepherds puzzling over a tomb — has generated centuries of conspiracy literature.",
    "Cézanne's homage made him, improbably, a grandfather of modern art."] },

{ id:"antoine-watteau", name:"Antoine Watteau", years:"1684–1721", born:1684, died:1721,
  nation:"france", eras:["18th-century"], movements:["rococo"],
  techniques:["oil-painting","glazing"], style:"rococo",
  palette:["#a8c4b8","#d9b4be","#cfc49a","#6e8a96","#f0e8d8"],
  tagline:"The melancholy inventor of the endless garden party",
  works:[{t:"Pilgrimage to Cythera",y:"1717"},{t:"Pierrot (Gilles)",y:"c. 1718–19"},{t:"Gersaint's Shopsign",y:"1720–21"}],
  life:"Born in Valenciennes, a Flemish town only recently French, Watteau arrived in Paris poor, intense and already tubercular. Restless and self-critical, he changed lodgings constantly, kept no school and few possessions, and died at thirty-six in a friend's arms — reportedly dissatisfied with a crucifix's craftsmanship to the last.",
  career:"The Academy had to invent a category for his reception piece: the fête galante — silk-clad lovers drifting through parks where music is implied and dusk is always near. Beneath the powder lies an ache; his white-clad Pierrot stares out like an actor who has forgotten why he's on stage. In two short decades he set the tone of an entire century's pleasure — and its undertow.",
  outside:"His thousands of red-and-black chalk drawings, bound in albums he guarded jealously, were prized even above his paintings. In his final year he painted a shop sign for his dealer Gersaint in a few mornings — a casual masterpiece showing Louis XIV's portrait being crated away: an era boxed up.",
  facts:["The 'Watteau pleat' in fashion is named for the cascading back-fold his painted gowns made famous.",
    "He asked that some indecorous works be destroyed at his death — friends complied selectively.",
    "Gersaint's Shopsign hung outdoors over a Paris bridge shop — arguably history's most valuable advertisement."] },

{ id:"jean-honore-fragonard", name:"Jean-Honoré Fragonard", years:"1732–1806", born:1732, died:1806,
  nation:"france", eras:["18th-century"], movements:["rococo"],
  techniques:["oil-painting","alla-prima","etching"], style:"rococo",
  palette:["#7da26e","#e8b4c8","#f2d9a8","#8aa7c4","#5e7250"],
  tagline:"Painted mischief at full speed — then history pulled the rope",
  works:[{t:"The Swing",y:"1767"},{t:"The Progress of Love",y:"1771–72"},{t:"The Bolt",y:"c. 1777"}],
  life:"Born in Grasse, the perfume town, Fragonard trained under Chardin briefly and Boucher decisively, won the Prix de Rome, and chose private pleasure-painting over an official career. The Revolution erased his patrons and his style overnight; he died in 1806, a forgotten old man in a Paris that had moved on to David's Romans.",
  career:"The Swing says it all: a slipper flying, a hidden lover gazing up silk skirts, a bishop unwittingly pulling the rope — frivolity executed with brushwork so alive it outclasses the joke. His 'fantasy portraits', each allegedly painted in an hour, are pure velocity. Madame du Barry's rejection of his Progress of Love panels for a newer Neoclassical look was the era's verdict in miniature.",
  outside:"Improbably, the Revolution's chief painter David protected him, securing him a curator's role at the new Louvre. His sister-in-law Marguerite Gérard became a successful painter from his studio; his grandson Théophile would design for porcelain — pleasure outliving politics in the bloodline.",
  facts:["The patron who commissioned The Swing originally wanted a bishop pushing it; Fragonard kept the clergy but improved the physics.",
    "He painted the fantasy portrait of the Abbé de Saint-Non, by inscription, 'in one hour's time.'",
    "From Grasse to the Louvre: his hometown's perfume museum now occupies a villa with his decorative panels."] },

{ id:"jean-simeon-chardin", name:"Jean-Siméon Chardin", years:"1699–1779", born:1699, died:1779,
  nation:"france", eras:["18th-century"], movements:["rococo","realism"],
  techniques:["oil-painting","pastel","glazing"], style:"tonal",
  palette:["#5e5648","#a08562","#cdb892","#7a3a2a","#e8dfd0"],
  tagline:"Copper pots and soap bubbles, painted like sacraments",
  works:[{t:"The Ray",y:"1728"},{t:"Saying Grace",y:"c. 1740"},{t:"Soap Bubbles",y:"c. 1733–34"},{t:"Self-Portrait with Spectacles",y:"1771"}],
  life:"A Paris carpenter's son who almost never left the city, Chardin rose through the Academy on the strength of a gutted ray-fish painted with horrifying magnificence. He lived modestly in the Louvre's artist lodgings, managed the Salon hangings for decades with legendary fairness, and turned to pastel self-portraits in old age when lead-based oils strained his eyes.",
  career:"In the century of Boucher's nymphs, Chardin painted kitchen maids, water glasses and children's games with a slow, granular touch that made critics reach for words like 'magic.' Diderot wrote that one stops before a Chardin 'as a weary traveller sits down.' His quiet authority — matter itself made luminous — later anchored Cézanne, Morandi and Lucian Freud.",
  outside:"He worked at a famously glacial pace, exhibiting few pictures and repeating compositions on demand. His late pastel self-portraits — visor, spectacles, knotted scarf — are among the most candid images any artist made of his own old age.",
  facts:["Diderot's Salon reviews made him the first painter canonised by modern art criticism.",
    "He was received into the Academy as a painter of 'animals and fruits' — the lowest genre — and quietly transcended the hierarchy.",
    "Proust's essay on Chardin taught generations to find splendour in the everyday."] },

{ id:"canaletto", name:"Canaletto", years:"1697–1768", born:1697, died:1768,
  nation:"italy", eras:["18th-century"], movements:["rococo"],
  techniques:["oil-painting","etching"], style:"neoclassical",
  palette:["#7aa7c4","#d9cba4","#b06a42","#3e5a70","#ece4d0"],
  tagline:"Venice, bottled for export",
  works:[{t:"The Stonemason's Yard",y:"c. 1725"},{t:"Return of the Bucentaur",y:"c. 1733–34"},{t:"Eton College Chapel",y:"c. 1754"}],
  life:"Giovanni Antonio Canal, son of a theatrical scene-painter, traded opera sets for the grandest stage of all: Venice itself. When the War of the Austrian Succession cut off his Grand Tourist clientele, he followed the customers, spending nearly a decade in England before returning to die in the city he had sold to the world.",
  career:"Canaletto perfected the veduta — the view painting — rendering regattas, feast days and everyday canals with crystalline light and surveyor's accuracy, often aided by the camera obscura. English milords bought him by the crateload as the ultimate souvenir, which is why Britain's royal collection owns more Canalettos than Venice does. His early Stonemason's Yard shows what he could do with working Venice before the postcards took over.",
  outside:"His nephew Bernardo Bellotto exported the family franchise to Dresden and Warsaw under the same trade name — Bellotto's Warsaw views were so exact they guided the city's reconstruction after WWII.",
  facts:["Joseph Smith, British consul in Venice, was agent, patron and middleman — then sold his vast Canaletto holdings to King George III.",
    "Skeptical London rivals spread rumours the 'real' Canaletto hadn't come — he painted a view in public to silence them.",
    "His etchings of imaginary 'capricci' show the fantasist hiding inside the documentarian."] },

{ id:"giambattista-tiepolo", name:"Giovanni Battista Tiepolo", years:"1696–1770", born:1696, died:1770,
  nation:"italy", eras:["18th-century"], movements:["rococo"],
  techniques:["fresco","oil-painting","etching"], style:"rococo",
  palette:["#9ec0d9","#e8d4a8","#d98a6e","#7a8ab0","#f2ecdc"],
  tagline:"The last great ceiling painter — skies without end",
  works:[{t:"Apollo and the Continents (Würzburg)",y:"1752–53"},{t:"The Banquet of Cleopatra",y:"1743–44"},{t:"Apotheosis of the Spanish Monarchy",y:"1762–66"}],
  life:"Venetian by birth and temperament, Tiepolo rose from a shipping merchant's family to become Europe's most sought-after fresco painter, working with his painter sons Giandomenico and Lorenzo as a flying squad of illusionists. Summoned to Madrid by Charles III in his sixties, he died there suddenly in 1770, just as Neoclassical taste — and its lobbyists — turned against everything he stood for.",
  career:"Above the Würzburg Residenz staircase he painted the largest fresco in the world: four continents swirling around Apollo in a sky that seems to dissolve the architecture. No one before or since has made enormous painted heavens feel so weightless — gods lounging on clouds like aristocrats on divans, all executed at outrageous speed with seemingly effortless drawing.",
  outside:"His etching suites of capricci and scherzi — magicians, owls, serpents, punchinellos — reveal a private, enigmatic imagination beneath the public splendour; his son Giandomenico's Punchinello drawings carried the family wit into darker registers.",
  facts:["The Würzburg ceiling covers about 677 square metres — still the largest fresco ever painted.",
    "Goya was deeply marked by the Tiepolos' Madrid years.",
    "Court rival Anton Raphael Mengs's clique ensured Tiepolo's Spanish altarpieces were dismantled — Neoclassicism's palace coup."] },

{ id:"william-hogarth", name:"William Hogarth", years:"1697–1764", born:1697, died:1764,
  nation:"britain", eras:["18th-century"], movements:["rococo","realism"],
  techniques:["oil-painting","etching"], style:"tonal",
  palette:["#4a3a2e","#8a5e3a","#c4a878","#5e3030","#e6dcc6"],
  tagline:"Satire in series — the moralist with the engraver's burin",
  works:[{t:"A Rake's Progress",y:"1733–35"},{t:"Marriage A-la-Mode",y:"1743–45"},{t:"Gin Lane",y:"1751"}],
  life:"Son of a Latin teacher who spent years in debtors' prison — a wound Hogarth never forgot — he apprenticed as a silver engraver and clawed his way up London's image trade. Pugnacious, patriotic and proud of his pug Trump, he married the painter Thornhill's daughter by elopement and battled critics, foreigners and connoisseurs until his death at sixty-six.",
  career:"Hogarth invented the picture-story: 'modern moral subjects' like A Rake's Progress and Marriage A-la-Mode, painted, then engraved, then sold by subscription to a mass public — the ancestor of the comic strip and the editorial cartoon. Gin Lane remains the most savage public-health poster ever made. Between satires he painted portraits of bracing directness, including his servants, just because.",
  outside:"Piracy of his prints drove him to lobby Parliament; the Engravers' Copyright Act of 1735 is still called Hogarth's Act. A founding governor of the Foundling Hospital, he organised art exhibitions there — effectively Britain's first public gallery — and wrote an art theory book, The Analysis of Beauty, championing the serpentine 'line of beauty.'",
  facts:["His self-portrait pairs him with his pug — 'one line of beauty' inscribed on the palette beside two British loyalties.",
    "Gin Lane's companion print Beer Street presents ale as the patriotic alternative.",
    "He once tactlessly sketched a sentry while detained as a spy in Calais — the resulting painting mocked France right back."] },

{ id:"thomas-gainsborough", name:"Thomas Gainsborough", years:"1727–1788", born:1727, died:1788,
  nation:"britain", eras:["18th-century"], movements:["rococo"],
  techniques:["oil-painting","alla-prima"], style:"romantic",
  palette:["#5b7a9e","#9eb4c8","#d9cdb0","#4a5a44","#e9e4d4"],
  tagline:"Faces for a living, landscapes for love",
  works:[{t:"The Blue Boy",y:"c. 1770"},{t:"Mr and Mrs Andrews",y:"c. 1750"},{t:"The Morning Walk",y:"1785"}],
  life:"A Suffolk clothier's son who sketched the woods before he could spell them, Gainsborough built fashionable portrait practices in Bath and London while grumbling that he'd rather paint landscapes. Witty, music-mad and allergic to academic theory, he feuded amiably with his rival Reynolds, who delivered the definitive eulogy after Gainsborough died of cancer at sixty-one.",
  career:"His portraits dissolve aristocrats into feathery, almost dripping brushwork — seen close, The Blue Boy's satin is a storm of strokes. Mr and Mrs Andrews seats a landowning couple beside their real subject: their land, painted with a freshness England hadn't seen. His late 'fancy pictures' of cottage children and his pure landscapes fed straight into Constable, who said Gainsborough's trees made him weep.",
  outside:"He preferred musicians to lords, collecting instruments he played badly and friendships with composers like J.C. Bach. He painted by candlelight with brushes on six-foot sticks, experimented with a 'show box' for backlit landscape transparencies, and reconciled with Reynolds on his deathbed: 'We are all going to heaven, and Van Dyck is of the company.'",
  facts:["The Blue Boy may answer Reynolds's rule that blue shouldn't dominate a picture — executed in Van Dyck costume as homage and dare.",
    "When The Blue Boy left Britain in 1922, crowds queued for a farewell viewing; it returned on loan a century later.",
    "His landscape models were often broccoli, coal and moss arranged on his table."] }
);
