/* PIGMENT — artists 6/7 : mid-century — Mexico City to New York */
window.ARTISTS.push(
{ id:"max-ernst", name:"Max Ernst", years:"1891–1976", born:1891, died:1976,
  nation:"germany", eras:["20th-century"], movements:["dada","surrealism"],
  techniques:["oil-painting","collage","frottage","automatism"], style:"surreal",
  palette:["#5e6e52","#a8743e","#3e4a5e","#d9c8a0","#22201c"],
  tagline:"Bird-man of the unconscious — rubbing, scraping and gluing dreams loose",
  works:[{t:"The Elephant Celebes",y:"1921"},{t:"Two Children Are Threatened by a Nightingale",y:"1924"},{t:"Europe After the Rain II",y:"1940–42"}],
  life:"A Cologne philosophy student gassed and shelled in WWI — he listed his death and rebirth in his autobiography — Ernst founded Cologne Dada, then jumped to Paris Surrealism. Interned in France as an enemy alien, he escaped to America with Peggy Guggenheim, whom he briefly married, finally settling in France with painter Dorothea Tanning until his death at eighty-four.",
  career:"Ernst was Surrealism's chief engineer of accident: collage novels stitched from Victorian engravings (Une Semaine de Bonté), frottage rubbings that turned floorboards into forests, grattage, decalcomania — each a machine for outwitting intention. Europe After the Rain II, painted while fleeing the catastrophe it depicts, renders a continent as melted coral: prophecy by technique.",
  outside:"His alter ego was a bird, Loplop, 'superior of the birds' — hatched, he claimed, from a childhood confusion of a dying cockatoo and a newborn sister. Convicted of nothing yet interned three times, he reached New York with canvases as luggage; son Jimmy Ernst became an AbEx painter.",
  facts:["He won the 1954 Venice Biennale and was promptly expelled — retroactively — from the Surrealist movement for accepting it.",
    "His collage novels were assembled with scissors so precisely that originals fool the eye at arm's length.",
    "Pollock saw Ernst's 'oscillation' paint-can experiments at Guggenheim's gallery — dripping had ancestors."] },

{ id:"tamara-de-lempicka", name:"Tamara de Lempicka", years:"1898–1980", born:1898, died:1980,
  nation:"poland", eras:["20th-century"], movements:["art-deco","cubism"],
  techniques:["oil-painting","glazing"], style:"artdeco",
  palette:["#9aa8b8","#c43e4e","#2a3440","#e8d9c0","#5e7286"],
  tagline:"Chrome-plated goddesses — Art Deco's high priestess at the wheel",
  works:[{t:"Self-Portrait in a Green Bugatti",y:"1929"},{t:"Young Lady with Gloves",y:"1930"},{t:"Adam and Eve",y:"1932"}],
  life:"Born Tamara Gurwik-Górska in Warsaw, she fled revolutionary Petrograd after personally negotiating her husband's release from Cheka custody. Reinvented in Paris as a baroness of the brush — and later actually a baroness by second marriage — she conquered café society, fled again to America in 1939, and died in Mexico, her ashes scattered over the Popocatépetl volcano.",
  career:"Lempicka fused soft Cubism with fashion-plate gloss into the defining portraits of the Jazz Age: liquid metal flesh, skyscraper backdrops, women with gunmetal eyelids and total self-possession. Her Green Bugatti self-portrait — commissioned for a German fashion magazine cover — remains the era's emblem: the woman as driver, never passenger.",
  outside:"Her affairs with women and men were conducted as publicly as her career; cocktail parties in her Left Bank studio, designed by Mallet-Stevens, doubled as showrooms. Forgotten by mid-century, she was resurrected by 1970s Deco revival and by collectors from Jack Nicholson to Madonna, who has lent her Lempickas to world tours.",
  facts:["She painted in couture and pearls, claiming elegance was discipline.",
    "Her daughter Kizette, her frequent model, wrote the memoir that anchors her biography.",
    "A musical about her life, 'Lempicka', reached Broadway in 2024."] },

{ id:"frida-kahlo", name:"Frida Kahlo", years:"1907–1954", born:1907, died:1954,
  nation:"mexico", eras:["20th-century"], movements:["surrealism","naive-art","symbolism"],
  techniques:["oil-painting"], style:"naive",
  palette:["#2e7a52","#c4302a","#e8a82e","#3e5570","#e8d4b0"],
  tagline:"'I paint my own reality' — the unflinching self, garlanded in thorns",
  works:[{t:"The Two Fridas",y:"1939"},{t:"Self-Portrait with Thorn Necklace and Hummingbird",y:"1940"},{t:"The Broken Column",y:"1944"}],
  life:"Born in the Blue House in Coyoacán, Kahlo survived polio at six and, at eighteen, a bus crash that drove a steel handrail through her pelvis — some thirty operations followed. She married Diego Rivera twice ('the second accident'), turned her plaster corsets into canvases, and died at forty-seven, her last diary page reading 'I hope the exit is joyful.'",
  career:"Of her roughly 150 paintings, a third are self-portraits: monkey-attended, thorn-necklaced, twinned, split open — autobiography conducted in votive-painting style with surgical honesty. Breton called her a Surrealist; she answered that she never painted dreams, only her own reality. The Louvre bought The Frame in 1939 — its first work by a 20th-century Mexican artist; her global cult now eclipses every label.",
  outside:"Her politics were communist and loudly worn; Trotsky was a houseguest and briefly more. The Casa Azul filled with xolo dogs, spider monkeys, a fawn named Granizo and parrots that drank beer. Her Tehuana dress was armour, banner and palette at once.",
  facts:["She altered her birth year to 1910 to be 'a daughter of the Revolution.'",
    "She arrived at her first solo show in Mexico by ambulance and held court from a four-poster bed installed in the gallery.",
    "Her face has appeared on the 500-peso note — opposite Diego's."] },

{ id:"diego-rivera", name:"Diego Rivera", years:"1886–1957", born:1886, died:1957,
  nation:"mexico", eras:["20th-century"], movements:["muralism","cubism"],
  techniques:["fresco","oil-painting","encaustic"], style:"fauvist",
  palette:["#b0703a","#6e8a5a","#c4423e","#e8cd9a","#3e3a30"],
  tagline:"History on the wall — frescoes for the people, scandals for the press",
  works:[{t:"Detroit Industry Murals",y:"1932–33"},{t:"Man, Controller of the Universe",y:"1934"},{t:"Dream of a Sunday Afternoon in Alameda Park",y:"1947"}],
  life:"A Guanajuato prodigy sent to Paris, Rivera spent a decade as a respected Cubist before the Mexican Revolution called him home to paint its meaning. Gargantuan in appetite, charm and self-mythology — he claimed, tongue somewhere near cheek, to have sampled human flesh — he married Frida Kahlo twice and died three years after her, at seventy.",
  career:"With Orozco and Siqueiros he revived true fresco at industrial scale, covering ministries, palaces and chapels with conquest, labour and revolution. The Detroit Industry cycle — assembly lines as modern creation myth — is his masterpiece. When his Rockefeller Center mural included Lenin in 1933, the Rockefellers had it jackhammered; Rivera repainted it in Mexico City, adding John D. Jr. to a nightclub scene.",
  outside:"An obsessive collector of pre-Columbian art, he built the lava-stone Anahuacalli museum to house 50,000 pieces and willed it to Mexico. His autobiography cheerfully contradicts itself; his FBI and Soviet files were both thick.",
  facts:["He helped secure Trotsky's Mexican asylum — then fell out with him, personally and politically.",
    "The destroyed Rockefeller mural survives in photographs taken secretly before demolition.",
    "He painted himself as a fat-cheeked boy holding an umbrella in the Alameda dreamscape — between Death and his own wife."] },

{ id:"georgia-okeeffe", name:"Georgia O'Keeffe", years:"1887–1986", born:1887, died:1986,
  nation:"usa", eras:["20th-century"], movements:["american-modernism"],
  techniques:["oil-painting","watercolor","pastel"], style:"postimpressionist",
  palette:["#e8c8d4","#d97a8a","#f0e4d0","#a8c4b8","#8a4a52"],
  tagline:"Flowers at billboard scale, bones against blue — the desert's modernist",
  works:[{t:"Jimson Weed / White Flower No. 1",y:"1932"},{t:"Cow's Skull: Red, White, and Blue",y:"1931"},{t:"Sky Above Clouds IV",y:"1965"}],
  life:"A Wisconsin dairy farmer's daughter, O'Keeffe was teaching in Texas when photographer Alfred Stieglitz exhibited her charcoals without asking; he became her champion, husband and obsessive portraitist (over 300 photographs). From 1929 she summered — then settled — in New Mexico's Ghost Ranch, painting until her sight failed and dying at ninety-eight.",
  career:"She enlarged flowers until they became landscapes — 'I'll paint it big and they will be surprised into taking time to look' — and bristled all her life at the gendered readings critics layered on. Her bleached skulls floating over desert, adobe walls, and the door of her Abiquiú patio painted again and again made her American modernism's most singular voice.",
  outside:"She collected bones and river stones like jewellery, drove her Model A Ford as a mobile studio, and at seventy-three rafted the Colorado. Nearly blind from macular degeneration, she made pottery and, with assistant Juan Hamilton, worked until her final years.",
  facts:["Jimson Weed sold in 2014 for $44.4 million — then the record for any woman artist at auction.",
    "She answered the 'female imagery' critics: 'Well — I made you take time to look at what I saw.'",
    "Her response to flattering dinner talk was reportedly to discuss the quality of the bread."] },

{ id:"edward-hopper", name:"Edward Hopper", years:"1882–1967", born:1882, died:1967,
  nation:"usa", eras:["20th-century"], movements:["american-realism"],
  techniques:["oil-painting","watercolor","etching"], style:"metaphysical",
  palette:["#2e5e52","#e8d9a8","#c4763e","#1d2630","#9ab0a8"],
  tagline:"Nighthawks at the diner — American loneliness, beautifully lit",
  works:[{t:"Nighthawks",y:"1942"},{t:"Automat",y:"1927"},{t:"House by the Railroad",y:"1925"},{t:"Morning Sun",y:"1952"}],
  life:"A tall, laconic son of Nyack, New York, Hopper survived two decades as a commercial illustrator he hated before selling a second painting at forty-one. He married painter Josephine 'Jo' Nivison, who modelled for every woman he painted thereafter and logged each canvas in ledgers; they lived in the same Washington Square walk-up for over fifty years.",
  career:"Hopper painted the spaces between events: a late-night diner glowing on an empty corner, a woman alone with coffee, morning light crossing a bed like a verdict. House by the Railroad became the first painting to enter MoMA's collection in 1930. His framing — windows, thresholds, oblique stages — taught cinema as much as cinema taught him.",
  outside:"A devoted moviegoer ('When I don't feel in the mood for painting I go to the movies for a week'), he read Verlaine and Goethe in the original and answered interviewers in sentences shorter than his shadows. Jo's diaries, acid and devoted, are the indispensable record of the marriage and the work.",
  facts:["Nighthawks was painted in the weeks after Pearl Harbor; the corner is a composite, hunted by New Yorkers ever since.",
    "Hitchcock's Psycho house is openly modelled on House by the Railroad.",
    "Asked what he was after: 'I'm after ME.'"] },

{ id:"jacob-lawrence", name:"Jacob Lawrence", years:"1917–2000", born:1917, died:2000,
  nation:"usa", eras:["20th-century"], movements:["harlem-renaissance"],
  techniques:["tempera","watercolor","flat-color"], style:"fauvist",
  palette:["#c4302a","#f0c82e","#2e50c4","#1a1a1a","#e8dcc4"],
  tagline:"The Migration Series — sixty panels, one people moving north",
  works:[{t:"The Migration Series",y:"1940–41"},{t:"The Builders series",y:"1946–98"},{t:"War Series",y:"1946–47"}],
  life:"Born in Atlantic City and forged in Depression-era Harlem's workshops and libraries, Lawrence was painting his community's history by his early twenties. He served in a segregated Coast Guard unit in WWII, weathered a 1949 depression hospitalisation by painting fellow patients, and taught for decades at the University of Washington, dying at eighty-two.",
  career:"At twenty-three he painted the sixty-panel Migration Series — the Black exodus from the rural South told in flat tempera colours and captions, all panels painted colour-by-colour simultaneously so the hues matched across the epic. Fortune magazine reproduced it; MoMA and the Phillips Collection split the panels, odd and even, and Lawrence became the first Black artist represented by a major New York gallery.",
  outside:"He called his style 'dynamic cubism,' crediting Harlem's patterns — fire escapes, quilts, pool halls — over Paris. Married for sixty years to painter Gwendolyn Knight, he illustrated books, made prints for hospitals and schools, and mentored generations of students.",
  facts:["He mixed his colours from the same jars across all sixty Migration panels — a logistics insight as much as an aesthetic one.",
    "The series was reunited for blockbuster tours in 1995 and 2015 — odd and even panels meeting like separated family.",
    "His Struggle series panel of Washington crossing the Delaware reframes the boat with unnamed rowers."] },

{ id:"amrita-sher-gil", name:"Amrita Sher-Gil", years:"1913–1941", born:1913, died:1941,
  nation:"india", eras:["20th-century"], movements:["post-impressionism"],
  techniques:["oil-painting"], style:"fauvist",
  palette:["#b0502e","#e8a85e","#6e3a32","#2e4a3e","#e8d4b0"],
  tagline:"Paris technique, Indian light — modern Indian painting's founding fire",
  works:[{t:"Young Girls",y:"1932"},{t:"Three Girls",y:"1935"},{t:"Bride's Toilet",y:"1937"}],
  life:"Born in Budapest to a Sikh aristocrat-scholar and a Hungarian opera singer, Sher-Gil trained at Paris's École des Beaux-Arts as a teenager, then renounced the salons in 1934: 'Europe belongs to Picasso, Matisse, Braque… India belongs only to me.' She died suddenly and mysteriously in Lahore at twenty-eight, days before her first major solo show.",
  career:"At nineteen her Young Girls won a gold medal at the Paris Salon, making her its youngest-ever associate and the only Asian recipient. Back in India she fused Gauguin's flat planes and Ajanta fresco rhythms into canvases of village women — waiting, bathing, enduring — whose quiet monumentality founded modern Indian art. The Indian state has declared her works National Art Treasures, barred from export.",
  outside:"Her letters crackle with wit, appetite and self-knowledge; her bisexual love affairs scandalised two continents' drawing rooms. Her great-niece is the contemporary artist Vivan Sundaram's circle's muse — the family remains an Indian cultural dynasty.",
  facts:["She is often called 'India's Frida Kahlo' — a comparison that cuts both ways, as Kahlo was her exact contemporary.",
    "Fewer than 200 of her paintings survive; most hang in Delhi's National Gallery of Modern Art.",
    "UNESCO declared 2013, her centenary, the international year of Amrita Sher-Gil."] },

{ id:"jackson-pollock", name:"Jackson Pollock", years:"1912–1956", born:1912, died:1956,
  nation:"usa", eras:["20th-century"], movements:["abstract-expressionism","action-painting"],
  techniques:["dripping","gestural-abstraction","oil-painting"], style:"drip",
  palette:["#1a1a1a","#e8e0d0","#c4763e","#5e7286","#caa43e"],
  tagline:"Jack the Dripper — the canvas on the floor, the painter inside the painting",
  works:[{t:"No. 5, 1948",y:"1948"},{t:"Autumn Rhythm (Number 30)",y:"1950"},{t:"Blue Poles",y:"1952"},{t:"Mural",y:"1943"}],
  life:"Born in Cody, Wyoming, youngest of five sons of a failed farmer, Pollock came to New York at eighteen and fought alcoholism all his life — Jungian analysis, sanatoria, two sober years that produced his masterpieces. Married to painter Lee Krasner, he moved to a farmhouse in Springs, Long Island, and died there in 1956, drunk at the wheel, at forty-four.",
  career:"In a barn-turned-studio he laid canvas on the floor and moved around — inside — it, trailing enamel from hardened brushes and sticks: 'energy and motion made visible.' Peggy Guggenheim's 1943 Mural commission cracked him open; the 1947–50 drip paintings made him the first American painter to lead world art, with Life magazine asking in 1949 if he was the greatest living US painter.",
  outside:"Sullen at parties and tender with dogs, crows and gardens, he resented the cowboy myth even as he rode it. The 1950 Hans Namuth films — painting on glass, cigarette dangling — froze him into an icon and, friends said, helped tip him off the wagon: being watched broke the spell.",
  facts:["Analysis of his drip rhythms has been (controversially) described as fractal — physicists keep publishing about him.",
    "Australia's purchase of Blue Poles for $1.3M in 1973 caused a parliamentary scandal; it's now worth a fortune.",
    "He renamed paintings with numbers so viewers would look 'passively' — titles, he said, gave too much."] },

{ id:"lee-krasner", name:"Lee Krasner", years:"1908–1984", born:1908, died:1984,
  nation:"usa", eras:["20th-century"], movements:["abstract-expressionism","action-painting"],
  techniques:["oil-painting","collage","gestural-abstraction"], style:"gestural",
  palette:["#c4542e","#e8c89a","#5e4a6e","#2e3a2c","#e8e0d0"],
  tagline:"Out of Pollock's shadow — the relentless reinventor who cut up her own past",
  works:[{t:"The Seasons",y:"1957"},{t:"Little Images series",y:"1946–50"},{t:"Gaea",y:"1966"}],
  life:"Born Lena Krassner to Russian-Jewish immigrants in Brooklyn, she trained harder than anyone — Cooper Union, the Academy, Hans Hofmann's studio. Married to Pollock from 1945, she managed his career and her own marginalisation simultaneously; widowed by his crash in 1956, she painted in his barn for three more decades, dying months before her MoMA retrospective opened.",
  career:"Hofmann's notorious compliment — 'This is so good you would not know it was painted by a woman' — set the terms she fought. Her Little Images glitter like mosaic script; after Pollock's death came huge umber gestures painted at night, and in the 1970s she sliced up her own earlier drawings into ferocious collages. Critics now read her constant self-revision as the point: refusal to brand, insistence on growth.",
  outside:"She guarded the Pollock estate with famous toughness, steering it to found the Pollock-Krasner Foundation, which has given hundreds of millions to working artists. The Springs farmhouse is now a museum where her studio floor, like his, is a relic.",
  facts:["She was one of only a few women given a MoMA retrospective by 1984 — it opened just after her death.",
    "She repainted over or destroyed much early work; scholars treat surviving pieces like archaeology.",
    "Asked about being 'Mrs Pollock': 'I was a painter before I met Jackson, and that's the whole story.'"] },

{ id:"willem-de-kooning", name:"Willem de Kooning", years:"1904–1997", born:1904, died:1997,
  nation:"usa", eras:["20th-century"], movements:["abstract-expressionism","action-painting"],
  techniques:["oil-painting","gestural-abstraction","alla-prima"], style:"gestural",
  palette:["#e8b4c8","#f0e8d0","#c4302a","#5e8ab0","#e8c43e"],
  tagline:"'Flesh was the reason oil paint was invented'",
  works:[{t:"Woman I",y:"1950–52"},{t:"Excavation",y:"1950"},{t:"Interchange",y:"1955"},{t:"Door to the River",y:"1960"}],
  life:"A Rotterdam working-class kid trained in commercial art, de Kooning stowed away on a freighter to America in 1926 with no English and total confidence. House painter, then painter, he became AbEx's supreme craftsman and its hardest drinker; in old age, with dementia advancing, he painted on — luminous late ribbon paintings whose status critics still argue — dying at ninety-two.",
  career:"He refused the purity wars: 'Flesh was the reason oil paint was invented.' Woman I — two years, hundreds of scrapings, a grinning goddess-monster — scandalised abstraction's priests by being a figure at all. His method was perpetual revision: paint, scrape with newspaper, repaint, until canvases held twenty pictures' archaeology. Excavation and the highway-fast landscapes of the '50s made gesture itself voluptuous.",
  outside:"His marriage to painter and critic Elaine de Kooning was an open, combative, finally devoted alliance — separated for decades, reunited in dry old age. His Springs studio, with its rocking chair and Long Island light, shaped the late paintings' airy glide.",
  facts:["Interchange sold privately in 2015 for about $300 million — then the highest price ever paid for a painting.",
    "He sanded and scraped Woman I so often that friends saved discarded states from his trash.",
    "Rauschenberg asked him for a drawing specifically to erase — Erased de Kooning Drawing is now a museum piece, with his blessing."] },

{ id:"mark-rothko", name:"Mark Rothko", years:"1903–1970", born:1903, died:1970,
  nation:"usa", eras:["20th-century"], movements:["abstract-expressionism","color-field"],
  techniques:["oil-painting","glazing"], style:"colorfield",
  palette:["#c43e2a","#e87a2e","#8a2634","#5e2a52","#1d1a18"],
  tagline:"Doorways of colour — tragedy, ecstasy, doom, eighteen inches away",
  works:[{t:"Orange and Yellow",y:"1956"},{t:"The Seagram Murals",y:"1958–59"},{t:"Rothko Chapel paintings",y:"1964–67"},{t:"No. 61 (Rust and Blue)",y:"1953"}],
  life:"Born Markus Rothkowitz in Daugavpils (now Latvia), he emigrated at ten to Portland, Oregon, dropped out of Yale (which he found bigoted and later told off in an honorary-degree speech), and reached his floating rectangles only in his mid-forties. Depressed and ill, he took his own life in his studio in 1970 at sixty-six.",
  career:"His stacked, soft-edged blocks of colour — layered in thin glazes that seem lit from within — were, he insisted, not abstractions but 'basic human emotions: tragedy, ecstasy, doom.' He wanted them hung low, close, in dim rooms, viewers at eighteen inches: immersion, not decoration. The commissions tell the arc — Seagram murals withheld from a luxury restaurant, the ecumenical Rothko Chapel in Houston as final statement.",
  outside:"He grew combative about viewing conditions, refusing sales to collectors he suspected of decorating. The posthumous trial over his estate — dealers convicted of fraud — reshaped American art law; his children recovered the works.",
  facts:["He returned the Seagram advance, reportedly saying a restaurant where the rich dined was no place for his pictures; the Tate's set arrived in London the day he died.",
    "He pulled out of the Four Seasons deal after dining there once.",
    "The Rothko Chapel hosts weddings, protests and meditation — exactly the temple-of-no-creed he intended."] },

{ id:"helen-frankenthaler", name:"Helen Frankenthaler", years:"1928–2011", born:1928, died:2011,
  nation:"usa", eras:["20th-century","21st-century"], movements:["abstract-expressionism","color-field"],
  techniques:["soak-stain","gestural-abstraction","oil-painting","woodblock"], style:"colorfield",
  palette:["#7ab0c4","#e8a8b8","#a8c49a","#f0e8d8","#d9a85e"],
  tagline:"Mountains and Sea at twenty-three — colour poured straight into the canvas",
  works:[{t:"Mountains and Sea",y:"1952"},{t:"The Bay",y:"1963"},{t:"Madame Butterfly (woodcut)",y:"2000"}],
  life:"A New York State Supreme Court judge's daughter raised on Park Avenue, Frankenthaler had the confidence of her upbringing and the work ethic to justify it. Married for a stormy decade to Robert Motherwell ('the golden couple'), she painted for six decades from Manhattan and Connecticut, made a Dame-equivalent of American art honours, and died at eighty-three.",
  career:"In 1952, aged twenty-three, she thinned oils to washes and poured them onto raw unprimed canvas on the floor: Mountains and Sea. Morris Louis called it 'a bridge between Pollock and what was possible' — he and Noland drove to see it and Colour Field painting followed. Her stain technique married accident to a landscape-trained eye; her late woodcuts, like Madame Butterfly, reinvented that medium too.",
  outside:"Sharp-tongued about being labelled a 'woman painter,' she also resisted feminist framing — 'For me, being a “lady painter” was never an issue. I don't resent being a female painter. I don't exploit it. I paint.'",
  facts:["Mountains and Sea was painted after a Nova Scotia trip — from memory, in an afternoon, on the floor.",
    "Her studio rule: 'There are no rules… that is how art is born.'",
    "She taught at Yale, Princeton and Harvard without ever needing the salary — and said the students kept her honest."] },

{ id:"joan-mitchell", name:"Joan Mitchell", years:"1925–1992", born:1925, died:1992,
  nation:"usa", eras:["20th-century"], movements:["abstract-expressionism","action-painting"],
  techniques:["oil-painting","gestural-abstraction","pastel"], style:"gestural",
  palette:["#2e50c4","#e8c43e","#2e8a5e","#e87a8a","#f0ece0"],
  tagline:"Remembered landscapes at hurricane force — sunflowers, grief and cobalt",
  works:[{t:"La Grande Vallée cycle",y:"1983–84"},{t:"Hemlock",y:"1956"},{t:"Sunflowers",y:"1990–91"}],
  life:"Daughter of a Chicago physician and a poetry-magazine editor, Mitchell was a champion junior figure skater before trading ice for paint. She joined New York's AbEx inner circle — one of few women admitted to the Cedar Bar's brutal company — then moved in 1959 to France, settling at Vétheuil above a bend of the Seine once painted by Monet, where she worked, drank, raged and gardened until her death at sixty-seven.",
  career:"'I carry my landscapes around with me' — her huge diptychs and quadriptychs compress remembered fields, rivers and dogs into slashing, dripping colour that stays rigorously composed at storm pitch. The late La Grande Vallée cycle and Sunflowers, painted through grief and illness, rank with the century's grandest colour. Her market and critical standing have soared since her death — overdue, as she'd have noted, profanely.",
  outside:"Legendarily generous to young painters and ferocious to everyone else, she funded a foundation that still supports artists. Her dogs — German shepherds, notably — appear in titles; poets from Frank O'Hara onward were her closest tribe, and several of her paintings answer poems line for line.",
  facts:["She kept Monet's view but rejected the comparison: 'I am not a lady Monet.'",
    "She painted at night by strong electric light, music loud — Bach to Billie Holiday.",
    "A Mitchell retrospective and a Monet pairing show at the Fondation Louis Vuitton in 2022 drew over a million visitors."] },

{ id:"francis-bacon", name:"Francis Bacon", years:"1909–1992", born:1909, died:1992,
  nation:"britain", eras:["20th-century"], movements:["expressionism","school-of-london"],
  techniques:["oil-painting","alla-prima"], style:"expressionist",
  palette:["#c4542e","#1d1a18","#8a2634","#d9b894","#3e3a36"],
  tagline:"Screaming popes and glass cages — the nervous system painted raw",
  works:[{t:"Three Studies for Figures at the Base of a Crucifixion",y:"1944"},{t:"Study after Velázquez's Portrait of Pope Innocent X",y:"1953"},{t:"Triptych May–June 1973",y:"1973"}],
  life:"Born in Dublin to an English horse-trainer father who horsewhipped him and expelled him at sixteen over his sexuality, Bacon drifted through Berlin and Paris into London's Soho, where he held court for decades at the Colony Room between gambling sprees. The 1971 suicide of his lover George Dyer, on the eve of Bacon's Grand Palais triumph, haunted his late triptychs. He died in Madrid at eighty-two.",
  career:"His 1944 Three Studies — writhing furies on orange grounds — announced a post-war art of the scream. The Velázquez pope, caged in glass and shrieking, became his signature series (he never saw the original, by choice). Working from photographs, Muybridge motion studies and medical plates, he smeared portraits of friends into centrifuged flesh — 'the brutality of fact' — while insisting he was an optimist 'about nothing.'",
  outside:"His Reece Mews studio — a knee-deep compost of photographs, slashed canvases and champagne boxes — was moved item by item (7,000 of them) to Dublin after his death and reassembled as a museum. He destroyed canvases by the dozen; rejected works occasionally surface, against his wishes, at auction.",
  facts:["Three Studies of Lucian Freud sold in 2013 for $142.4 million — briefly the most expensive artwork ever auctioned.",
    "He painted on the raw, unprimed back of the canvas — preferring its tooth.",
    "Margaret Thatcher reportedly called him 'that man who paints those dreadful pictures'; he relished it."] }
);
