/* PIGMENT — batch 21: twenty painters, added together (duo session, 2026-09-19).

   Chosen from what the atlas itself says it is missing. Nine are named in
   existing prose with no record of their own (docs/ATLAS_COVERAGE.md, Gap 4):
   Cimabue, Simone Martini, Ambrogio Lorenzetti, Filippo Lippi, Ghirlandaio,
   Campin, Pontormo, Böcklin, Mucha. Two fill the canon around them: Uccello and
   Antonello. Three are women the roster lacked: Sirani, Schjerfbeck, Gwen John.
   Six stand for traditions with no painter here before them: Abbasid Baghdad
   (al-Wasiti), Potosí (Pérez de Holguín), Rinpa's founder (Sōtatsu), Joseon
   genre painting (Shin Yun-bok), Uruguay (Torres-García), Venezuela (Michelena).

   Every one died in or before 1955, so each page shows sourced Commons images
   rather than a generative cover. That death year only decided whom to try;
   it is not a rights determination (OD-5). Each image's Commons file, its
   metadata and the work it shows are recorded, with a source for every claim
   in the prose, in docs/roster-batch-21/<id>.json. */
window.ARTISTS = (window.ARTISTS || []).concat([

{ id:"cimabue", name:"Cimabue", years:"c. 1240–1302", born:1240, died:1302,
  nation:"italy", eras:["13th-century","14th-century"], movements:["proto-renaissance"],
  techniques:["tempera","gold-leaf","fresco"], style:"ornament",
  palette:["#c9a24a","#2e3e6e","#8a2e24","#3e3226","#e8dcc0"],
  tagline:"The first Italian to loosen the Byzantine icon — then eclipsed by Giotto",
  works:[{t:"Santa Trinita Maestà",y:"c. 1290–1300"},{t:"Crucifix of Santa Croce",y:"after 1272"},{t:"The Mocking of Christ",y:"c. 1280"},{t:"Maestà of the Louvre",y:"c. 1280"}],
  life:"Cenni di Pepo was born in Florence around 1240 and died in Pisa around 1302, and little else about his life is certain. His nickname translates as \"ox-head\", and perhaps also as \"one who crushes the views of others\". A contemporary quoted by Vasari called him so proud that if anyone pointed out a flaw in a work, he would destroy it, however precious.",
  career:"He trained on Byzantine models and was among the first Italian painters to break from them, with more lifelike proportions and shading that suggests volume. He is documented in Rome around 1272, and afterwards painted the great Crucifix for Santa Croce in Florence. His Maestà of about 1280, now in the Louvre, set a type that Duccio and Giotto both followed. He worked at Assisi, and ended his life in Pisa on the cathedral's apse mosaic, where his Saint John is the only surviving work documented as his.",
  outside:"Vasari made him Giotto's discoverer: the shepherd boy drawing sheep on a stone, and the painted fly the master kept trying to brush off a portrait. Many scholars now discount the apprenticeship altogether. Dante, in the Purgatorio, uses him to show how quickly fame passes once a Giotto arrives. In 2019 a small panel found in a kitchen in northern France sold for €24 million as his Mocking of Christ.",
  facts:["None of his works is signed or securely dated; every attribution is scholarship.",
    "The Santa Croce Crucifix was damaged in the 1966 Arno flood, and has been restored.",
    "Duccio's Rucellai Madonna was long wrongly credited to him.",
    "The Mocking of Christ sat in a French kitchen until its 2019 sale."] },

{ id:"simone-martini", name:"Simone Martini", years:"c. 1284–1344", born:1284, died:1344,
  nation:"italy", eras:["14th-century"], movements:["proto-renaissance"],
  techniques:["tempera","gold-leaf","fresco"], style:"ornament",
  palette:["#c9a24a","#1f3e7a","#a8402f","#e8d8b8","#2e2a24"],
  tagline:"Siena's most elegant line — carried from the council hall to the papal court",
  works:[{t:"Annunciation with Saints Margaret and Ansanus",y:"1333"},{t:"Saint Louis of Toulouse Crowning Robert of Anjou",y:"1317"},{t:"Maestà",y:"1315–21"},{t:"Orsini Polyptych",y:"c. 1333"}],
  life:"He was born in Siena around 1284, and very little documentation of his life survives. He is thought to have trained under Duccio, though Vasari made him Giotto's pupil instead. His brother-in-law was the painter Lippo Memmi. He spent his last decade at the papal court in Avignon, where he probably moved in 1334 or 1335, and died there in 1344.",
  career:"Among his first documented works is the Maestà of 1315 in Siena's Palazzo Pubblico, whose model other painters followed for the rest of the century. In Naples, at the king's request, he painted Saint Louis of Toulouse Crowning Robert of Anjou (1317). Against Florentine weight he set soft, sinuous line and courtly elegance, learned partly from French manuscripts and ivories that reached Siena along the pilgrim road to Rome. The Uffizi Annunciation of 1333 is its best-known statement.",
  outside:"In Avignon he became a friend of Petrarch, and two of the poet's sonnets refer to a portrait of Laura de Noves that, according to Vasari, Simone painted for him. His frescoes for the porch of Avignon Cathedral are reduced to faint sinopia outlines. What travelled was the manner: the International Gothic style that spread across Europe owes him a great deal.",
  facts:["Lippo Memmi, his brother-in-law, painted a similar Maestà for San Gimignano soon after his.",
    "Two of Petrarch's sonnets refer to his portrait of Laura.",
    "Only faint sinopia outlines remain of his Avignon Cathedral frescoes.",
    "He died in the service of the papal court at Avignon, in 1344."] },

{ id:"ambrogio-lorenzetti", name:"Ambrogio Lorenzetti", years:"c. 1290–1348", born:1290, died:1348,
  nation:"italy", eras:["14th-century"], movements:["proto-renaissance"],
  techniques:["fresco","tempera","gold-leaf"], style:"renaissance",
  palette:["#c8a468","#7a8a5e","#a84a2e","#e8dcc0","#3e3a30"],
  tagline:"A whole city at peace on a council-room wall — then the plague year",
  works:[{t:"Effects of Good Government in the City",y:"1338–39"},{t:"Presentation in the Temple",y:"1342"},{t:"Annunciation",y:"1344"},{t:"Maestà of Massa Marittima",y:"c. 1335"}],
  life:"He was born in Siena around 1290, the younger brother of the painter Pietro Lorenzetti, and was active from about 1317. He is documented in Florence until 1321 and returned there after some years at home. His will is dated 9 August 1348, and he and his brother are both believed to have died of the plague that year. Vasari thought his manners \"more those of a gentleman and philosopher than those of an artist\".",
  career:"His work shows the influence of Simone Martini, made more naturalistic. From Byzantine and classical models he built something more individual than patrons usually allowed: experiments with perspective and physiognomy, and a study of classical antiquity. His Maestà of about 1335 adds a Virgin and Child locked in each other's gaze, unusual in Sienese art of the time. His last work, the Annunciation of 1344, has one of the first clear uses of linear perspective, its floor diagonals pushing back against a flat gold ground.",
  outside:"His masterwork is civic, not sacred. On the walls of the Sala dei Nove in Siena's Palazzo Pubblico, where the Nine who governed the republic met, he painted the Allegory of Good and Bad Government and its effects on town and country. The better-preserved, well-governed side is an encyclopedia of incidents in a peaceful town and its fields, and its landscape is the first in Western art since antiquity to be a subject in its own right.",
  facts:["His earliest dated work is a Madonna and Child of 1319.",
    "One of his Bad Government frescoes may hold the earliest surviving picture of an hourglass.",
    "His brother Pietro Lorenzetti was also a painter.",
    "His will is dated 9 August 1348."] },

{ id:"filippo-lippi", name:"Filippo Lippi", years:"c. 1406–1469", born:1406, died:1469,
  nation:"italy", eras:["15th-century"], movements:["early-renaissance"],
  techniques:["tempera","fresco"], style:"renaissance",
  palette:["#2e4a7a","#c8a878","#a8402f","#e8dcc8","#4a5a3e"],
  tagline:"The Carmelite friar who painted tender Madonnas — and ran off with his model",
  works:[{t:"Madonna and Child with Two Angels",y:"c. 1460–65"},{t:"Adoration in the Forest",y:"c. 1459"},{t:"Coronation of the Virgin",y:"1439–47"},{t:"Barbadori Altarpiece",y:"1437–38"}],
  life:"He was born in Florence in 1406, a butcher's son, orphaned at two and placed with the Carmelites of Santa Maria del Carmine at eight. He took vows at sixteen, was ordained around 1425, and left the priory in 1432 without being released from his vows. In Prato in 1458 he met Lucrezia Buti, a boarder or novice at a convent there, and took her to his house; their son Filippino became a painter too. He died in Spoleto in 1469.",
  career:"The Carmine's chapel had just been frescoed by Masaccio, and the young friar went there so often that, Vasari says, people claimed Masaccio's spirit had entered him. With Medici support his pictures became popular, and his workshop trained Sandro Botticelli. His Madonnas grew lighter and more human; the Uffizi Madonna and Child with Two Angels, its angel smiling out at us, is the type. He spent his last years on the fresco cycles of the cathedrals at Prato and Spoleto.",
  outside:"His life reads like a novel, and much of it may be one. Vasari has him captured by Barbary pirates and freed for his skill at portrait sketches, a tale the Catholic Encyclopedia called \"assuredly nothing but a romance\". Cosimo de' Medici reportedly locked him in to make him work, and he escaped down a rope of bedsheets. Robert Browning made him the speaker of the poem \"Fra Lippo Lippi\" in 1855.",
  facts:["Lucrezia Buti is thought to be the model for many of his Madonnas.",
    "In a letter of 1439 he called himself the poorest friar in Florence.",
    "His pupil Botticelli and his son Filippino both became major painters.",
    "How he died is disputed; one story says he was poisoned."] },

{ id:"paolo-uccello", name:"Paolo Uccello", years:"1397–1475", born:1397, died:1475,
  nation:"italy", eras:["15th-century"], movements:["early-renaissance"],
  techniques:["tempera","fresco"], style:"renaissance",
  palette:["#2e3e2e","#c84a2e","#d8c8a8","#6a5a4a","#1e2226"],
  tagline:"Up all night with the vanishing point — and a battle of toy-bright horses",
  works:[{t:"The Battle of San Romano",y:"c. 1438–40"},{t:"Saint George and the Dragon",y:"c. 1470"},{t:"The Hunt in the Forest",y:"c. 1470"},{t:"Monument to Sir John Hawkwood",y:"1436"}],
  life:"Paolo di Dono was born in 1397, probably at Pratovecchio, the son of a barber-surgeon; the nickname Uccello, \"little bird\", came from his fondness for painting birds. From 1412 to 1416 he was apprenticed to the sculptor Lorenzo Ghiberti, and around then began a lifelong friendship with Donatello. He married Tommasa Malifici. Their son was named Donato, after Donatello, and their daughter Antonia became a Carmelite nun whom Vasari called a daughter who knew how to draw. He died in 1475.",
  career:"Vasari's Uccello is obsessed with perspective, up all night in his study trying to fix the vanishing point, and his Annunciation for Santa Maria Maggiore became a model for painters who wanted illusions of space. Yet his pictures keep one foot in the Late Gothic, all colour and pageant. The three Battle of San Romano panels celebrate Florence's victory over Siena in 1432 with lances and horses foreshortened in many planes. In 1436 he received the commission for the monochrome fresco of Sir John Hawkwood in Florence Cathedral.",
  outside:"He left no school of followers, and his style is best described as idiosyncratic. Vasari tells how the abbot of San Miniato fed him cheese pies and cheese soup until he ran off the job, returning only when promised a better diet. He kept pictures of animals at home, above all birds. Twentieth-century writers from Marcel Schwob to Antonin Artaud wrote about him.",
  facts:["Uccello means \"little bird\", after his fondness for painting birds.",
    "He trained in the workshop of Lorenzo Ghiberti.",
    "The San Romano panels were long misnamed the Battle of Sant'Egidio.",
    "Vasari says he walked off a job over cheese soup."] },

{ id:"domenico-ghirlandaio", name:"Domenico Ghirlandaio", years:"1448–1494", born:1448, died:1494,
  nation:"italy", eras:["15th-century"], movements:["early-renaissance"],
  techniques:["fresco","tempera"], style:"renaissance",
  palette:["#b8483a","#d8c29a","#4a6a8a","#6a7a4e","#2e2a26"],
  tagline:"Bible stories set in his patrons' Florence — with the patrons standing in them",
  works:[{t:"An Old Man and His Grandson",y:"c. 1490"},{t:"Portrait of Giovanna Tornabuoni",y:"1488"},{t:"Calling of the First Apostles",y:"1481"},{t:"Adoration of the Magi",y:"1485–88"}],
  life:"Domenico Bigordi was born in Florence in 1448. The name Ghirlandaio, \"garland-maker\", came from his father, famed for the metal garland headdresses worn by Florentine women. Vasari says the boy first worked in his father's shop and caught the likeness of anyone who passed through. He trained with Alesso Baldovinetti, ran a large and efficient workshop with his brothers Davide and Benedetto, and died in January 1494, in his forty-fifth year.",
  career:"Fresco was his strength. In 1481 Pope Sixtus IV called him to Rome with the team painting the walls of the Sistine Chapel, where he painted the Calling of the First Apostles. Back in Florence he frescoed the Sassetti Chapel in Santa Trinita for the director of the Medici bank, then, from 1485 to 1490, the Tornabuoni Chapel in Santa Maria Novella. His gift was to set sacred stories among contemporary people, and the humanists of the Medici circle stand in his frescoes.",
  outside:"The young Michelangelo passed through his workshop as an apprentice. His panel portraits are few and famous: Giovanna Tornabuoni in profile, commissioned in 1488, and the Louvre's Old Man and His Grandson, remarkable for its tenderness. A Milanese agent reported to his lord in 1484 that Ghirlandaio was \"a good painter on panel and better in mural fresco\".",
  facts:["He painted the Calling of the First Apostles in the Sistine Chapel.",
    "His nickname means \"garland-maker\", after his father's trade.",
    "His workshop included his brothers Davide and Benedetto.",
    "Michelangelo trained in his workshop."] },

{ id:"antonello-da-messina", name:"Antonello da Messina", years:"c. 1430–1479", born:1430, died:1479,
  nation:"italy", eras:["15th-century"], movements:["early-renaissance"],
  techniques:["oil-painting","glazing"], style:"renaissance",
  palette:["#263d51","#a74132","#ceb27a","#302a22","#e2d8b8"],
  tagline:"A face turns out of darkness — Sicily learns to look north",
  works:[{t:"Saint Jerome in His Study",y:"c. 1475"},{t:"Virgin Annunciate",y:"c. 1476"},{t:"Saint Sebastian",y:"1478"},{t:"Portrait of a Man",y:"c. 1475"}],
  life:"Antonello came from Messina, the son of a sculptor who gave him his first training. A letter written in 1524 places him in the workshop of Colantonio in Naples around 1450. By his first documented commission in 1457, for a confraternity's banner, he was married and had a son, Jacobello.",
  career:"Paintings by Jan van Eyck and Rogier van der Weyden helped shape his early work. His portraits turn a bust-length sitter towards us against darkness, replacing the profile familiar in earlier Italian portraiture. He worked in Venice in 1475–76, where his San Cassiano Altarpiece influenced Venetian painters. Giovanni Bellini, in turn, helped sharpen Antonello's attention to anatomy and expression.",
  outside:"Vasari claims Antonello introduced oil painting to Italy; that account is now rejected. The northern connection does not establish a northern journey: no documentary evidence places him outside Italy. While in Venice he declined an offer to become the Duke of Milan's court portrait painter. He returned to Sicily by September 1476 and died in Messina in 1479; Jacobello finished some of the pictures he left incomplete.",
  facts:["His first recorded commission was a banner, in 1457.",
    "The San Cassiano Altarpiece survives only as a fragment.",
    "Vasari's story that he introduced oil painting to Italy is rejected."] },

{ id:"robert-campin", name:"Robert Campin", years:"c. 1378–1444", born:1378, died:1444,
  nation:"belgium", nationNote:"Probably born in Valenciennes; worked all his known life in Tournai", eras:["15th-century"], movements:["early-netherlandish"],
  techniques:["oil-painting","glazing"], style:"renaissance",
  palette:["#8a2e24","#3e5a3e","#c8b48a","#2e3444","#e8e0cc"],
  tagline:"Not one signed picture — and early Netherlandish realism begins with him",
  works:[{t:"Werl Triptych",y:"1438"},{t:"Nativity",y:"c. 1425"},{t:"Portrait of a Woman",y:"c. 1430–35"},{t:"Seilern Triptych",y:"c. 1425"}],
  life:"He was settled in Tournai by 1405–06 as a free master of the guild of goldsmiths and painters, possibly having come from Valenciennes. He bought citizenship in 1410, owned houses and city bonds, and in 1427 represented his guild on the city council. Prosecuted in 1432 for an affair, he was sentenced to a year's banishment, until Margaret of Burgundy intervened and the penalty became a fine. He died in Tournai in 1444, childless.",
  career:"No surviving painting can be tied to him by a signature or a contemporary document. One group of works has long carried his name, and another was credited to an anonymous \"Master of Flémalle\"; most scholars now think they are the same hand. With Jan van Eyck he opened early Netherlandish painting, and his observation, pushed by new uses of oil paint, was more realistic than any earlier artist's. His workshop trained Rogier van der Weyden and Jacques Daret.",
  outside:"He led Tournai's painting for thirty years, and he and van Eyck are recorded as meeting in 1427. The Werl Triptych, dated 1438, shows him still at work late; its two wings are in the Prado and the centre is lost. The strictest account of his own hand keeps only a few pictures, among them the Nativity at Dijon and the two London portraits of a man and a woman.",
  facts:["No painting can be tied to him by a signature or a document.",
    "He and Jan van Eyck are recorded as meeting in 1427.",
    "Rogier van der Weyden appears in his records as \"Rogelet de la Pasture\".",
    "The Werl Triptych's centre panel is lost; its wings are in Madrid."] },

{ id:"pontormo", name:"Pontormo", years:"1494–1557", born:1494, died:1557,
  nation:"italy", eras:["16th-century"], movements:["mannerism"],
  techniques:["oil-painting","fresco"], style:"renaissance",
  palette:["#e89aa8","#6a9ac8","#e8b85a","#8ab89a","#3e3a44"],
  tagline:"Bodies without weight in a room without floor — the Renaissance, unsettled",
  works:[{t:"Deposition from the Cross",y:"1525–28"},{t:"Visitation",y:"1528–29"},{t:"Portrait of a Halberdier",y:"1529–30"},{t:"Joseph in Egypt",y:"1517–18"}],
  life:"Jacopo Carucci was born in 1494 at Pontorme, near Empoli, and took the village's name. Vasari calls the orphaned boy \"young, solitary, and melancholy\", passed from master to master in Florence: Leonardo, Albertinelli, Piero di Cosimo and, in 1512, Andrea del Sarto, who is said not to have wished him well. When plague broke out in Florence in 1522 he withdrew to the Certosa di Galluzzo, a monastery whose monks kept vows of silence. He died in 1557.",
  career:"Medici patronage kept him in and around Florence. His early Visitation of 1514–16 keeps a classical distance; the Carmignano Visitation a decade later brings the women almost uncomfortably close, drifting toward each other in clouds of drapery. In one of the Joseph panels in London, Vasari says, the boy on the step is his apprentice Bronzino. His masterpiece, the Deposition for the Capponi Chapel in Santa Felicita (1528), is a swirl of brilliant colour in a flattened space.",
  outside:"At the Certosa he painted a Passion cycle, now badly damaged, drawing openly on Albrecht Dürer's engravings, which kept feeding him after his return to Florence. A trip to Rome, largely to see Michelangelo, left its mark on his later figures: haunted faces and elongated bodies. His twining poses and uncertain spaces, where figures seem to float free of gravity, broke with the calm perspective of the Florentine Renaissance.",
  facts:["The Deposition in Santa Felicita has no cross in it.",
    "Vasari says the boy on the step in Joseph in Egypt is Bronzino.",
    "He sat out the 1522 plague among silent Carthusian monks.",
    "Dürer's engravings shaped his Passion frescoes at the Certosa."] },

{ id:"elisabetta-sirani", name:"Elisabetta Sirani", years:"1638–1665", born:1638, died:1665,
  nation:"italy", eras:["17th-century"], movements:["baroque"],
  techniques:["oil-painting","chiaroscuro","etching"], style:"baroque",
  palette:["#943c36","#dbad6e","#34372d","#655179","#eee0be"],
  tagline:"They doubted her speed — she invited them to watch her paint",
  works:[{t:"Timoclea Kills the Captain of Alexander the Great",y:"1659"},{t:"Portia Wounding Her Thigh",y:"1664"},{t:"Virgin and Child",y:"1663"},{t:"Portrait of Vincenzo Ferdinando Ranuzzi as Cupid",y:"c. 1663"}],
  life:"Born in Bologna in 1638, Elisabetta trained in the studio of her father, Giovanni Andrea Sirani. When gout incapacitated him in 1654, she began running the family workshop. Portrait commissions and teaching fees made her the household's principal earner. Malvasia later claimed credit for persuading her father to teach her; his account gives its author a conspicuously helpful part.",
  career:"Sirani painted more than 200 pictures and kept a list of commissions from 1655. She studied Annibale Carracci's work, while Guido Reni's example remained close to her style. Her own pictures heighten the contrasts of light and dark and brighten the colour. In Portia Wounding Her Thigh, the heroine raises a small knife above an already wounded leg, while attendants weave at the left.",
  outside:"Her workshop was also a classroom: she taught her sisters Barbara and Anna Maria and at least twelve other young women. Doubters of her output were invited to watch her complete a portrait in one sitting in 1664. She died suddenly the next year, aged 27. A servant was accused of poisoning her, but her father withdrew the charges; the accusation is not an established cause of death.",
  facts:["She recorded her paintings and their commissioners from 1655.",
    "Her pupils included both her younger sisters.",
    "She was buried in the same tomb as Guido Reni."] },

{ id:"tawaraya-sotatsu", name:"Tawaraya Sōtatsu", years:"c. 1570–c. 1640", born:1570, died:1640,
  nation:"japan", eras:["16th-century","17th-century"], movements:["rinpa"],
  techniques:["ink-wash","tarashikomi","gold-leaf"], style:"ornament",
  palette:["#bc9d52","#2f4e4c","#dad0ac","#31322f","#8d6842"],
  tagline:"Gold, cranes and gathering clouds — wet paint meets wetter paint",
  works:[{t:"Wind God and Thunder God",y:"17th century"},{t:"Waves at Matsushima",y:"17th century"},{t:"Sekiya and Miotsukushi Screens",y:"1631"},{t:"Deer Scroll",y:"c. 1610"}],
  life:"Sōtatsu's birth date and birthplace are unknown; around 1570 is the usual estimate. In Kyoto he opened Tawaraya, a shop selling fans, lantern paper, screens, dolls and kimono patterns. He also accepted commissions to decorate interiors. In 1602 he was hired to repair the Heike nōkyō sutra scrolls at Itsukushima shrine.",
  career:"He collaborated with the calligrapher Hon'ami Kōetsu on decorated books and scrolls. In the crane scroll, gold and silver birds stand or fly beneath a gathering of classical poems. He popularised tarashikomi, applying another layer of paint before the first had dried. In Dragons and Clouds, pooled ink becomes cloud. The method makes the behaviour of wet material part of the image itself.",
  outside:"Sōtatsu and Kōetsu are credited with founding Rinpa, a tradition connected by influence rather than a single formal school. Ogata Kōrin later copied Wind God and Thunder God in homage. The Wind God and Thunder God screens carry neither inscription nor seal, though the attribution is accepted. He decorated Yōgen-in's doors and screens in 1621 and received the Buddhist artists' rank of hokkyō in 1630. His death, probably around 1640, is poorly documented.",
  facts:["Tawaraya sold kimono patterns as well as screens and fans.",
    "Tarashikomi adds paint before the previous layer dries.",
    "Wind God and Thunder God has no inscription or seal."] },

{ id:"al-wasiti", name:"Yahya ibn Mahmud al-Wasiti", years:"fl. 1237", born:1237, died:1237,
  nation:"iraq", nationNote:"Filed under present-day Iraq; his manuscript is associated with medieval Mesopotamia.", eras:["13th-century"], movements:["baghdad-school"],
  techniques:["miniature-painting","gold-leaf"], style:"ornament",
  palette:["#be893b","#294e66","#ad4534","#e6d3a6","#3d4939"],
  tagline:"A rogue talks his way through town — the manuscript watches everyone",
  works:[{t:"Abu Zayd before the Governor of Rahba",y:"1237"},{t:"The Pilgrims' Caravan",y:"1237"},{t:"A Village",y:"1237"},{t:"The Eastern Island",y:"1237"}],
  life:"Almost nothing is known about al-Wasiti's life; he was probably born in Wasit, south of Baghdad. What survives is a double achievement: in 1237 he copied and illustrated al-Hariri's Maqamat. The manuscript is associated with Baghdad, but that place of production remains conjectural. Its colophon fixes the copying to 634 AH, or 1237 CE.",
  career:"Red and black writing shares the page with miniatures, many decorated with gold. Al-Hariri's fifty tales follow Abu Zayd, a traveller who uses his command of language to deceive people and earn rewards. Al-Wasiti gives this social satire expressive figures and carefully controlled colour. Clothing does some of the storytelling: military figures wear boots and distinctive headgear, while judges and merchants appear in turbans.",
  outside:"The manuscript belongs to the Bibliothèque nationale de France, where it is catalogued as Arabe 5847. It is also known as the Schefer Hariri, one copy in a much wider manuscript tradition. More than a hundred manuscripts of al-Hariri's text are known, though only thirteen are illustrated. Al-Wasiti's pictures later inspired the modern Baghdad art movement.",
  facts:["He copied the text as well as illustrating it.",
    "His birthplace is probable, not securely documented.",
    "Only thirteen of the hundred-plus known manuscripts of the Maqamat are illustrated."] },

{ id:"melchor-perez-de-holguin", name:"Melchor Pérez de Holguín", years:"c. 1660–c. 1735", born:1660, died:1735,
  nation:"bolivia", nationNote:"Born in Cochabamba, colonial Alto Perú; worked chiefly in Potosí, now Bolivia.", eras:["17th-century","18th-century"], movements:["viceregal-painting","baroque"],
  techniques:["oil-painting","chiaroscuro"], style:"baroque",
  palette:["#6a4534","#b99e69","#343b36","#d7c7a1","#8b3932"],
  tagline:"Potosí's Golden Brush — dark tones give way to colour",
  works:[{t:"Entry of Viceroy Morcillo into Potosí",y:"1716"},{t:"Saint Christopher",y:"c. 1710"},{t:"Saint Peter of Alcántara and Saint Teresa",y:"1724"},{t:"Virgin of the Rosary",y:"c. 1700"}],
  life:"Holguín was born around 1660 in Cochabamba and made his career in Potosí, in what is now Bolivia. The dates at either end of his life remain approximate; accounts place his death in 1732 or around 1735. His teacher is unknown, though a 1678 contract already records an apprentice placed under his care. He married Micaela del Castillo in Potosí in March 1695.",
  career:"Religious orders supplied most of his commissions, with wealthy landowners also among his patrons. Francisco de Zurbarán and Bartolomé Esteban Murillo influenced his painting. His early pictures favour dark tones; later paintings open towards more colour. Flemish prints were another source, carried into a practice centred on Potosí and Chuquisaca. He also painted the arrival of Viceroy Morcillo in Potosí in 1716.",
  outside:"Painting was not his only trade: he drew up plans for the church of San Lorenzo in Potosí. After his lifetime he became known as Brocha de Oro, the Golden Brush. The Casa Nacional de Moneda in Potosí holds a substantial group of his pictures, including the full-length Evangelists signed in 1724. Its room devoted to him includes a life-size figure based on his self-portrait.",
  facts:["His teacher's identity is unknown.",
    "He made architectural plans for San Lorenzo in Potosí.",
    "Brocha de Oro means Golden Brush."] },

{ id:"shin-yun-bok", name:"Shin Yun-bok", years:"1758–after 1813", born:1758, died:1813,
  nation:"korea", eras:["18th-century","19th-century"], movements:["joseon-painting","pungsokhwa"],
  techniques:["ink-wash","silk-painting"], style:"tonal",
  palette:["#cdbaa0","#a43936","#36536b","#e6d9b8","#343833"],
  tagline:"A red skirt swings — two monks are watching",
  works:[{t:"Portrait of a Beauty",y:"c. 1805"},{t:"Dano Day",y:"c. 1805"},{t:"Lovers under the Moon",y:"c. 1805"},{t:"Sword Dance",y:"c. 1805"}],
  life:"Shin Yun-bok, known as Hyewon, came from a family of painters; his father Hanpyeong worked on royal portraits. His own biography is less secure, including whether he belonged to the royal painting institute at all. The Korean account records work as late as 1813, while leaving his exact death date and place unknown.",
  career:"Kim Hong-do influenced him, but Shin's townspeople and kisaeng occupy a different world from Kim's peasants. He used bright colour and delicate strokes to make scenes of urban life, courtship and shamanism. Dano Day sets bathers in a stream, a woman in a red hanbok on a swing, and two young monks peeping from behind. Portrait of a Beauty turns the same precision towards the details of a figure's dress.",
  outside:"Many paintings carry a short verse and a seal but no date, making a stylistic chronology difficult to establish. His Hyewon album gathers thirty paintings and was designated a Korean National Treasure in 1970. He also painted landscapes and animals, beyond the social encounters for which he is remembered. The later novel Painter of the Wind recasts him as a woman disguised as a man; that is a fictional portrayal.",
  facts:["Hyewon was his art name.",
    "The Hyewon album contains thirty paintings.",
    "Two young monks spy on the scene in Dano Day."] },

{ id:"arnold-bocklin", name:"Arnold Böcklin", years:"1827–1901", born:1827, died:1901,
  nation:"switzerland", eras:["19th-century"], movements:["symbolism"],
  techniques:["oil-painting","fresco"], style:"romantic",
  palette:["#2e3a3e","#4a5a4e","#c8b89a","#1a1e22","#8a6a4a"],
  tagline:"A rowing boat, a white figure, a cypress island — a dream everyone borrowed",
  works:[{t:"Isle of the Dead",y:"1880–86"},{t:"Self-Portrait with Death Playing the Fiddle",y:"1872"},{t:"The Plague",y:"1898"},{t:"War",y:"1896"}],
  life:"He was born in Basel in 1827, the son of a silk merchant, and trained at the Düsseldorf academy under Schirmer, who sent him to copy the Flemish and Dutch masters in Antwerp and Brussels. In 1850 he went to Rome, and married Angela Pascucci there in 1853. They had fourteen children; five died in childhood and three more before him. He nearly died of typhoid in 1859, and died at Fiesole in 1901.",
  career:"Rome turned a landscape painter into a painter of myths: nymphs and satyrs, centaurs and sea idylls, set among classical architecture and often haunted by death. A professorship at Weimar followed, then years in Basel, Munich, Florence and Zurich. Between 1880 and 1886 he painted five versions of the Isle of the Dead. The first was commissioned by a widow who wanted a dreamlike picture, and the island partly evokes the English Cemetery in Florence, near his studio, where his baby daughter Maria was buried.",
  outside:"Famous in central Europe in his lifetime, he fell from fashion quickly after his death; in 1947 Clement Greenberg called his work a consummate expression of all that was then disliked about the late nineteenth century. Giorgio de Chirico disagreed: \"Each of Böcklin's works is a shock.\" Max Ernst and Salvador Dalí admired him, late Romantic composers set the Isle of the Dead to music, and H. R. Giger painted a homage to it.",
  facts:["He painted five versions of the Isle of the Dead between 1880 and 1886.",
    "His Self-Portrait with Death Playing the Fiddle dates from 1872.",
    "De Chirico said each of his works was a shock.",
    "Marcel Duchamp once named him as a major influence; whether seriously is still debated."] },

{ id:"arturo-michelena", name:"Arturo Michelena", years:"1863–1898", born:1863, died:1898,
  nation:"venezuela", eras:["19th-century"], movements:["academicism"],
  techniques:["oil-painting"], style:"neoclassical",
  palette:["#664737","#c6a982","#333e49","#a3513e","#e2d7bf"],
  tagline:"From Valencia's workshop to the Paris Salon — history on a larger stage",
  works:[{t:"Miranda in La Carraca",y:"1896"},{t:"The Young Mother",y:"1889"},{t:"Charlotte Corday",y:"1889"},{t:"Penthesilea",y:"1891"}],
  life:"Born in Valencia in 1863, Michelena learned painting from his father, Juan Antonio; his maternal grandfather was a muralist. At eleven he illustrated Costumbres venezolanas for the writer Francisco de Sales Pérez, who became his sponsor. From 1879 to 1882 father and son ran a private academy in Valencia, taking orders for portraits, murals and copies of old paintings. A government grant took him to Paris in 1885.",
  career:"At the Académie Julian he studied with Jean-Paul Laurens, who encouraged him to enter the Salon. The Sick Child received a second-class gold medal there in 1887. Charlotte Corday, showing her on the way to execution, won another gold medal at the 1889 Exposition Universelle. Returning to Venezuela after contracting tuberculosis in 1892, he became a sought-after portraitist and official painter to Joaquín Crespo.",
  outside:"Michelena married the collector Lastenia Tello Mendoza after returning to Venezuela in 1889, then went back to Paris with her. In 1890 he was commissioned to illustrate Victor Hugo's Hernani. He also painted Vuelvan Caras as a Venezuelan gift to New York, thanking the city for its welcome to the exiled José Antonio Páez. He died in 1898 at thirty-five, leaving numerous pictures unfinished.",
  facts:["He illustrated Costumbres venezolanas at eleven.",
    "He and his father ran a painting academy in Valencia.",
    "A commission in 1890 put his illustrations into Hugo's Hernani."] },

{ id:"alphonse-mucha", name:"Alphonse Mucha", years:"1860–1939", born:1860, died:1939,
  nation:"czechia", eras:["19th-century","20th-century"], movements:["art-nouveau"],
  techniques:["lithography","oil-painting"], style:"ornament",
  palette:["#d8b87a","#8aa47a","#c86a4a","#e8dcc4","#4a5a6e"],
  tagline:"Sarah Bernhardt's poster artist — who spent his second life on the Slav Epic",
  works:[{t:"Gismonda",y:"1894"},{t:"Job",y:"1896"},{t:"The Seasons",y:"1896"},{t:"The Slav Epic",y:"1910–28"}],
  life:"He was born in 1860 in Ivančice in Moravia, a court usher's son, and sang in a Brno church choir to pay for school. The Prague Academy rejected him in 1878 and advised him to find a different career. He painted theatre scenery in Vienna and murals for a Moravian count, who paid for his training in Munich, and he made his name in Paris. After Prague was occupied in 1939 he was arrested and interrogated for several days; his health broken, he died of pneumonia that July.",
  career:"At the end of 1894 Sarah Bernhardt ordered a new poster in a hurry for her play Gismonda, and Mucha, who was at the printer's correcting proofs, got it. The poster, over two metres high, set a rainbow-shaped arch behind her head like a halo, and the arch appeared in every theatre poster he made after it. For the printer Champenois he then produced decorative panels, posters with no text, sold in large runs at a modest price; The Seasons of 1896 was the first series.",
  outside:"In his later career he went home and gave himself to The Slav Epic, twenty monumental canvases on the history of the Slavic peoples, painted between 1912 and 1926. In 1928, on the tenth anniversary of Czechoslovak independence, he presented the series to the Czech nation. He considered it his most important work.",
  facts:["The Prague Academy told him in 1878 to find a different career.",
    "His Gismonda poster stands more than two metres tall.",
    "The halo-like arch behind Bernhardt's head recurs in all his later theatre posters.",
    "He gave the twenty-canvas Slav Epic to the Czech nation in 1928."] },

{ id:"helene-schjerfbeck", name:"Helene Schjerfbeck", years:"1862–1946", born:1862, died:1946,
  nation:"finland", eras:["19th-century","20th-century"], movements:["realism","modernism"],
  techniques:["oil-painting"], style:"tonal",
  palette:["#c6b8a3","#332f2d","#8e5e51","#dfd9c8","#77847a"],
  tagline:"The face stays — the paint learns how much it can leave out",
  works:[{t:"The Convalescent",y:"1888"},{t:"Wounded Warrior in the Snow",y:"1880"},{t:"Self-Portrait with Black Background",y:"1915"},{t:"Girl with Blonde Hair",y:"1916"}],
  life:"Born in Helsinki in 1862, Schjerfbeck injured her hip in a childhood fall and lived with a lasting limp. She entered the Finnish Art Society's drawing school at eleven, with fees paid by Adolf von Becker. A travel grant took her to Paris in 1880. She later painted in Brittany and Cornwall; The Convalescent, made at St Ives, won a bronze medal at the 1889 Paris World Fair.",
  career:"Her early history pictures gave way to portraits and still lifes, with description gradually pared towards abstraction. After illness ended her teaching, she moved with her mother to Hyvinkää in 1902. There she painted her mother, schoolgirls and women workers, while friends sent books and magazines to keep contemporary art within reach. Girl with Blonde Hair depicts Impi Tamlander, one of the neighbours who helped with the household.",
  outside:"Gösta Stenman sought her out in 1913 and organised her first solo exhibition in 1917. That year her friend Einar Reuter published the first monograph on her work under the name H. Ahtela. War cancelled a planned American retrospective in 1939. With Stenman's help she moved to Sweden in 1944, continuing her late self-portraits at the Saltsjöbaden spa hotel until her final years.",
  facts:["She enrolled in drawing school at eleven.",
    "The Convalescent won a bronze medal at the 1889 Paris World Fair.",
    "Books and magazines helped her follow contemporary art from Hyvinkää."] },

{ id:"gwen-john", name:"Gwen John", years:"1876–1939", born:1876, died:1939,
  nation:"britain", nationNote:"Welsh-born; she spent most of her working life in France.", eras:["19th-century","20th-century"], movements:["modernism"],
  techniques:["oil-painting","glazing","watercolor"], style:"tonal",
  palette:["#a29b8b","#d7cbbb","#525958","#877d72","#e5decf"],
  tagline:"Hands in laps, colours close together — a room for looking slowly",
  works:[{t:"Self-Portrait",y:"1902"},{t:"A Corner of the Artist's Room in Paris",y:"1907–09"},{t:"Nude Girl",y:"1909–10"},{t:"Girl Reading at the Window",y:"1911"}],
  life:"Gwen John was born in Haverfordwest in 1876 and grew up sketching on the coast at Tenby. She studied at the Slade from 1895 to 1898, then with James McNeill Whistler in Paris. In 1903 she and Dorelia McNeill set out to walk from Bordeaux to Rome, selling portrait sketches along the way. They reached Toulouse; John settled in Paris the following year, finding work as an artist's model.",
  career:"Her portraits bring closely related tones around a seated woman, often with hands resting in her lap. Early thin glazes gave way to small, thicker touches of paint in the Mère Poussepin series, begun around 1913. Those portraits of the religious order's founder were based on a prayer card. The collector John Quinn bought most of the works she sold between 1910 and 1924, freeing her from modelling to concentrate on painting.",
  outside:"John moved to Meudon in 1910 and entered the Catholic Church around 1913. Alongside the oils, she made thousands of drawings: cats, and women and children seen in church, often from behind. Her notebooks numbered colours and set down personal rules for observing and painting, retaining Whistler's emphasis on systematic preparation. She had just one solo exhibition during her lifetime, in London in 1926.",
  facts:["Her portraits of Mère Poussepin began with a prayer card.",
    "Her surviving oils rarely exceed 61 centimetres in either dimension.",
    "The attempted walk to Rome ended in Toulouse."] },

{ id:"joaquin-torres-garcia", name:"Joaquín Torres-García", years:"1874–1949", born:1874, died:1949,
  nation:"uruguay", nationNote:"Born in Montevideo; a long Barcelona career preceded his return to Uruguay in 1934.", eras:["19th-century","20th-century"], movements:["constructivism","modernism"],
  techniques:["oil-painting","fresco"], style:"geometric",
  palette:["#ac8b53","#373935","#c6bca0","#8c4936","#ded6bd"],
  tagline:"South America turns upside down — the compass becomes an argument",
  works:[{t:"Inverted America",y:"1943"},{t:"Two Figures",y:"1930"},{t:"Constructive Clock",y:"1936"},{t:"Portrait of Josep Pijoan",y:"c. 1910"}],
  life:"Torres-García was born in Montevideo in 1874, the son of a Catalan shopkeeper and a Uruguayan mother. He spent much of his childhood in his father's general store, drawing and examining goods arriving from abroad. The family moved to Spain in 1891, and he studied art in Barcelona. He married Manolita Piña in 1909; their four children also became artists.",
  career:"His mature paintings place simplified figures and signs inside a geometric structure, holding representation and abstraction together. He called this language Universal Constructivism, treating geometry as something cultures could share. Earlier he designed stained glass for Gaudí and painted monumental frescoes for the Catalan government. Teaching at the experimental Mont d'Or school meant drawing leaves, fruit and animals from observation instead of copying casts.",
  outside:"He returned to Montevideo in 1934 after forty-three years away and founded the Taller Torres-García there. His 1943 ink drawing Inverted America puts south at the top of the continent. The reversal argues for an autonomous Latin American art, connected to his School of the South manifesto. He had also designed toys whose coloured parts could combine into dogs, cars or cities.",
  facts:["He returned to Montevideo after forty-three years abroad.",
    "Inverted America puts south at the top.",
    "His toys could assemble colour and shape into a dog, car or city."] }
]);
