/* PIGMENT — artists 5/7 : the modernist explosion */
window.ARTISTS.push(
{ id:"pablo-picasso", name:"Pablo Picasso", years:"1881–1973", born:1881, died:1973,
  nation:"spain", eras:["20th-century"], movements:["cubism"],
  techniques:["oil-painting","collage","etching"], style:"cubist",
  palette:["#5e7286","#a8896e","#8a4a42","#3e3a36","#d9cdb4"],
  tagline:"The century in one career — blue, rose, shattered, remade",
  works:[{t:"Les Demoiselles d'Avignon",y:"1907"},{t:"Guernica",y:"1937"},{t:"The Weeping Woman",y:"1937"},{t:"Girl before a Mirror",y:"1932"}],
  life:"Born in Málaga to a drawing teacher who, legend says, handed over his own brushes when the boy surpassed him, Picasso conquered Paris from a cold Montmartre studio. Through two world wars, two wives, a procession of muses whose faces mark his periods, and late-life celebrity on the Riviera, he worked virtually every day until his death at ninety-one.",
  career:"The melancholy Blue and circus-tinted Rose periods would alone have secured a reputation; instead came Les Demoiselles d'Avignon — five fractured nudes that cracked five centuries of perspective — and, with Braque, Cubism itself. Guernica, painted in a month of fury after the Basque town's bombing, became the twentieth century's defining history painting. Estimates of his total output run to 50,000 works across painting, sculpture, ceramics and prints.",
  outside:"He hoarded everything — bus tickets, butts of pencils, châteaux to store it all — and kept a menagerie from goats to an owl. A Communist Party member from 1944, he drew the dove that became the international peace symbol, while his treatment of the women in his life remains the sharpest edge of his legend.",
  facts:["His full baptismal name runs to over twenty words.",
    "When the Mona Lisa vanished in 1911, Picasso was actually questioned — he and Apollinaire had bought statuettes stolen from the Louvre.",
    "Guernica toured for decades and only entered Spain in 1981, after Franco's death, as Picasso had insisted."] },

{ id:"georges-braque", name:"Georges Braque", years:"1882–1963", born:1882, died:1963,
  nation:"france", eras:["20th-century"], movements:["cubism","fauvism"],
  techniques:["oil-painting","collage"], style:"cubist",
  palette:["#6e6252","#a89272","#4a5246","#8a6e4a","#d9d0bc"],
  tagline:"Cubism's co-inventor — the quiet half of the rope team",
  works:[{t:"Houses at L'Estaque",y:"1908"},{t:"Violin and Candlestick",y:"1910"},{t:"Fruit Dish and Glass",y:"1912"},{t:"The Birds",y:"1953"}],
  life:"A house-painter's son from Argenteuil trained in decorative technique, Braque passed through Fauvism before Cézanne's memorial show rerouted his life. Severely wounded and trepanned in WWI, he returned to a slower, graver art, living out his days in Normandy and Paris as France's most honoured living painter — the first to see his own work hung in the Louvre.",
  career:"From 1908 to 1914 he and Picasso worked, in Braque's phrase, 'like mountaineers roped together,' often unable to tell their canvases apart — analytic Cubism's shattered violins and cafés were a genuine two-man invention. It was Braque who pasted imitation wood-grain paper into Fruit Dish and Glass, inventing papier collé. His later studio series and black birds traded revolution for a deep, husky poetry.",
  outside:"Methodical and private where Picasso was volcanic, he boxed, played the accordion, and designed everything from ballet sets to a jewel-like ceiling for the Louvre's Etruscan room. 'Picasso and I said things to each other during those years that no one will ever say again… that no one will ever be able to understand.'",
  facts:["A critic mocking his 'little cubes' at L'Estaque gave Cubism its name.",
    "His WWI head wound left him blind for days; he resumed painting two years later, changed.",
    "In 1961 the Louvre exhibited him while alive — an honour France had never granted a painter."] },

{ id:"wassily-kandinsky", name:"Wassily Kandinsky", years:"1866–1944", born:1866, died:1944,
  nation:"russia", eras:["20th-century"], movements:["expressionism","der-blaue-reiter","abstract-art"],
  techniques:["oil-painting","watercolor","woodblock"], style:"abstract",
  palette:["#2e5eaa","#e8c43e","#c4302a","#2e8a5e","#1d1a20"],
  tagline:"Painting as music — abstraction's loudest prophet",
  works:[{t:"Composition VII",y:"1913"},{t:"Improvisation 28",y:"1912"},{t:"Composition VIII",y:"1923"},{t:"Several Circles",y:"1926"},{t:"Yellow-Red-Blue",y:"1925"}],
  life:"A Moscow tea merchant's son, Kandinsky was a thirty-year-old law lecturer offered a professorship when a Monet haystack and a Wagner opera convinced him to paint instead. He taught at Munich, revolutionary Moscow and the Bauhaus, fled the Nazis to Paris, and died a French citizen in 1944, still painting biomorphic constellations.",
  career:"Kandinsky claimed the first abstract painting (a 1910 watercolour, though Hilma af Klint had quietly beaten everyone) and wrote abstraction's scripture, Concerning the Spiritual in Art: colour as vibration striking the soul. With Franz Marc he founded Der Blaue Reiter; his pre-war Compositions are apocalypses of colour, his Bauhaus geometry their cooled, precise afterlife.",
  outside:"He experienced synesthesia — hearing colours, seeing sounds — and named paintings like concert programmes: improvisations, compositions. Trained as an ethnographer, he traced his colour-mysticism partly to painted peasant houses in Vologda that felt like 'walking into a painting.'",
  facts:["Composition VII required over thirty preparatory studies — then was painted in under a week.",
    "The Nazis included him in the Degenerate Art show; the Bauhaus had already been shut around him.",
    "His Munich companion Gabriele Münter hid hundreds of his works through two wars, then gave them to the city."] },

{ id:"piet-mondrian", name:"Piet Mondrian", years:"1872–1944", born:1872, died:1944,
  nation:"netherlands", eras:["20th-century"], movements:["de-stijl","abstract-art"],
  techniques:["oil-painting","flat-color"], style:"mondrian",
  palette:["#e02e2e","#2e50c4","#f0c82e","#f4f1e8","#1a1a1a"],
  tagline:"Right angles toward utopia — and a late-life boogie-woogie",
  works:[{t:"Composition with Red, Blue and Yellow",y:"1930"},{t:"Broadway Boogie Woogie",y:"1942–43"},{t:"The Gray Tree",y:"1911"}],
  life:"A strict Calvinist schoolmaster's son from Amersfoort, Mondrian abstracted himself by degrees: Dutch windmills, theosophy, Cubist Paris, then the grid. He lived monastically — one cooked meal a day, studio walls arranged like his canvases — fleeing war from Paris to London to Manhattan, where jazz and street lights re-electrified him before pneumonia took him at seventy-one.",
  career:"Through De Stijl, founded with Theo van Doesburg in 1917, Mondrian pursued 'neoplasticism': only verticals, horizontals and primaries, balance without symmetry — a visual ethics he believed could redesign the world. He broke with van Doesburg over the diagonal, a heresy. In New York the black lines dissolved into pulsing coloured tape: Broadway Boogie Woogie, austerity learning to dance.",
  outside:"An obsessive ballroom dancer with a private horror of green (he reportedly turned a tulip's leaves white with paint), he loved jazz records almost as much as theosophical tracts. His rented studios, recreated in museums, were artworks themselves — coloured rectangles pinned to every wall.",
  facts:["Yves Saint Laurent's 1965 Mondrian dresses fused his grid to fashion forever.",
    "He left Victory Boogie Woogie unfinished on his easel — taped, not painted, in places.",
    "L'Oréal once trademarked-styled packaging from him; few painters are more pirated by design."] },

{ id:"kazimir-malevich", name:"Kazimir Malevich", years:"1879–1935", born:1879, died:1935,
  nation:"ukraine", eras:["20th-century"], movements:["suprematism","abstract-art"],
  techniques:["oil-painting","flat-color"], style:"geometric",
  palette:["#1a1a1a","#c4302a","#f4f1e8","#3e3a36","#caa43e"],
  tagline:"The Black Square — painting's full stop and new alphabet",
  works:[{t:"Black Square",y:"1915"},{t:"White on White",y:"1918"},{t:"Suprematist Composition (Blue Rectangle over Red Beam)",y:"1916"}],
  life:"Born near Kyiv to a Polish family, Malevich rose through icon-influenced peasant scenes and Cubo-Futurism to revolutionary Petrograd's avant-garde summit. Soviet orthodoxy then closed in: arrested and interrogated in 1930, he returned to figurative peasants with hidden geometries. He died of cancer at fifty-six and was buried under an oak tree, beneath a black square.",
  career:"At the 1915 '0,10' exhibition he hung Black Square across the room's corner — the place of the icon — declaring painting reduced 'to the zero of form' and rebuilt from pure feeling: Suprematism. Floating rectangles, tilted beams, then White on White's near-invisible square; he even declared painting finished and turned to teaching, writing and architectural models before history forced his retreat.",
  outside:"He designed costumes and sets for the futurist opera Victory over the Sun, whose backdrop prefigured the Square. Students worshipped him; rivals (Tatlin above all) feuded with him at legendary volume. His grave was lost in WWII; suburban Moscow housing now stands nearby.",
  facts:["Conservators found craquelure revealing colour compositions hidden beneath Black Square — and a scrawled joke referencing 'Negroes battling in a cellar.'",
    "His coffin, painted with Suprematist motifs, was followed through Leningrad by crowds saluting a black square on the hearse.",
    "Both Ukraine and Russia claim him; he wrote some autobiographical texts in Ukrainian."] },

{ id:"hilma-af-klint", name:"Hilma af Klint", years:"1862–1944", born:1862, died:1944,
  nation:"sweden", eras:["20th-century"], movements:["abstract-art","symbolism"],
  techniques:["oil-painting","watercolor","tempera","automatism"], style:"abstract",
  palette:["#e8b4c8","#9ab8d9","#f0e0a8","#caa45c","#5e5648"],
  tagline:"Abstraction's secret first mover — sealed by her own will for decades",
  works:[{t:"The Ten Largest",y:"1907"},{t:"Paintings for the Temple",y:"1906–15"},{t:"The Swan series",y:"1914–15"}],
  life:"A Swedish naval officer's daughter and academy-trained portraitist, af Klint supported herself with conventional botanical and landscape work while conducting, with four women friends — 'The Five' — séances that she said commissioned her true art. She never married, cared for her blind mother for years, and died after a tram accident at eighty-one.",
  career:"From 1906 — years before Kandinsky or Mondrian — she painted monumental abstractions: the ten-foot Ten Largest swirl with spirals, letters and biomorphic blooms charting life's ages. The 193-work Paintings for the Temple cycle was, she believed, dictated through her. Convinced the world wasn't ready, she barred exhibition until twenty years after her death; the 2018 Guggenheim show became the museum's most-visited ever.",
  outside:"Her notebooks — tens of thousands of pages — map a private cosmology of theosophy, Rosicrucianism and Rudolf Steiner, whose lukewarm reaction to the paintings reportedly wounded her deeply. She willed everything to a nephew with instructions to keep the boxes shut.",
  facts:["Her abstractions predate Kandinsky's famous 1910 watercolour by four years.",
    "MoMA's landmark 1936 abstraction survey, mapping the field's 'inventors,' did not know she existed.",
    "She painted some works on the floor, walking around them — half a century before Pollock."] },

{ id:"paul-klee", name:"Paul Klee", years:"1879–1940", born:1879, died:1940,
  nation:"switzerland", eras:["20th-century"], movements:["expressionism","der-blaue-reiter","abstract-art"],
  techniques:["watercolor","oil-painting","etching"], style:"geometric",
  palette:["#d9886e","#caa45c","#5e8a96","#a85e6e","#e8dcc0"],
  tagline:"Taking a line for a walk — wit, colour and ten thousand small miracles",
  works:[{t:"Twittering Machine",y:"1922"},{t:"Senecio",y:"1922"},{t:"Highway and Byways",y:"1929"},{t:"Death and Fire",y:"1940"}],
  life:"Born near Bern to a German music teacher and a Swiss singer, Klee was a violinist good enough for the municipal orchestra before choosing the slower art. The 1914 Tunisia journey unlocked him — 'Colour and I are one. I am a painter.' He taught a decade at the Bauhaus, was dismissed by the Nazis, and spent his last years in Bern with scleroderma stiffening his skin, working faster than ever.",
  career:"Klee built a private universe at postcard scale: fish, moons, arrows, twittering birds cranked by a handle, grids of colour like irrigated fields. His Bauhaus notebooks — 'taking a line for a walk' — are modern art's most poetic pedagogy, treating pictures as organisms grown rather than made. Nearly 10,000 catalogued works range across techniques he often invented, like oil-transfer drawing.",
  outside:"He played Bach and Mozart on the violin most mornings, wrote diaries dense with irony, and ceded family cooking to no one — his recipes survive. His cat Bimbo is art history's best-documented studio supervisor; Klee let cats walk on wet work, saying future connoisseurs would wonder at the paw prints.",
  facts:["The Nazis seized 102 of his works from German museums as 'degenerate.'",
    "In his final year, dying, he produced over 1,200 works — his largest annual output.",
    "Angelus Novus, bought by Walter Benjamin, became philosophy's most famous 'angel of history.'"] },

{ id:"marc-chagall", name:"Marc Chagall", years:"1887–1985", born:1887, died:1985,
  nation:"belarus", eras:["20th-century"], movements:["expressionism","surrealism"],
  techniques:["oil-painting","watercolor","etching"], style:"surreal",
  palette:["#2e3e8a","#6e3a8a","#c4302a","#2e8a5e","#e8c43e"],
  tagline:"Fiddlers on roofs, lovers in mid-air — Vitebsk carried around the world",
  works:[{t:"I and the Village",y:"1911"},{t:"The Birthday",y:"1915"},{t:"White Crucifixion",y:"1938"},{t:"Paris Opera ceiling",y:"1964"}],
  life:"Eldest of nine in a Hasidic family in Vitebsk (now Belarus), Chagall painted his hometown's fiddlers, herring sellers and floating brides for seventy years from Paris, wartime New York and Provence. The death of his wife and lifelong subject Bella in 1944 silenced him for months. He died at ninety-seven, the last living first-generation modernist.",
  career:"Cubism gave him structure, but gravity never applied: in his canvases lovers levitate, cows dream and time runs on memory's clock — Breton claimed him for Surrealism; Chagall politely declined all labels. His later decades went monumental: stained glass for Jerusalem, Reims and the UN, the Paris Opera's ceiling painted at seventy-seven, and the America Windows in Chicago.",
  outside:"Briefly Vitebsk's revolutionary arts commissar, he lost the local power struggle to Malevich's Suprematists and left for good. He escaped Vichy France in 1941 with Varian Fry's rescue network, crossing with crates of canvases. Picasso: 'When Matisse dies, Chagall will be the only painter left who understands what colour really is.'",
  facts:["His White Crucifixion — Christ in a prayer shawl amid pogrom scenes — is reportedly Pope Francis's favourite painting.",
    "He painted the Paris Opera ceiling on 2,400 square feet of canvas panels, refusing payment.",
    "Notre-Dame-de-Toute-Grâce on the Plateau d'Assy unites Chagall, Matisse, Bonnard and Léger — modernism's chapel."] },

{ id:"amedeo-modigliani", name:"Amedeo Modigliani", years:"1884–1920", born:1884, died:1920,
  nation:"italy", eras:["20th-century"], movements:["expressionism"],
  techniques:["oil-painting","alla-prima"], style:"fauvist",
  palette:["#c47a52","#8a4a3e","#2e3a44","#d9b894","#1d1a18"],
  tagline:"Swan necks and almond eyes — Montparnasse's doomed prince",
  works:[{t:"Reclining Nude",y:"1917"},{t:"Jeanne Hébuterne in a Yellow Sweater",y:"1918–19"},{t:"Portrait of Chaim Soutine",y:"1916"}],
  life:"Born to a Sephardic Jewish family in Livorno already bankrupt at his birth, 'Modì' arrived in Paris in 1906 — elegant, tubercular, reciting Dante. He hid his disease behind drink and hashish, scraping by in Montparnasse until dying of tubercular meningitis at thirty-five; his pregnant fiancée Jeanne Hébuterne threw herself from a window the next day.",
  career:"His mature style is instantly his: necks like columns, faces like masks, eyes often blank almonds — 'When I know your soul, I will paint your eyes,' he reportedly told a sitter. His 1917 one-man show was closed by police on opening day over its frank nudes, the succès de scandale selling almost nothing. Within a few years of his death the same nudes commanded fortunes; one sold in 2015 for $170 million.",
  outside:"For several years he abandoned painting for sculpture — limestone heads carved under Brancusi's spell, allegedly from stone pilfered off building sites — until dust and poverty drove him back to canvas. His daughter Jeanne, orphaned at fourteen months, grew up to write his standard biography.",
  facts:["In 1984, students hoaxed Livorno's 100th-birthday dredging of his canal by carving fake heads with a power drill — experts authenticated them.",
    "He traded paintings for meals; some café owners' descendants became millionaires.",
    "Friends called him 'Modì' — a pun on 'maudit', the accursed."] },

{ id:"egon-schiele", name:"Egon Schiele", years:"1890–1918", born:1890, died:1918,
  nation:"austria", eras:["20th-century"], movements:["expressionism","vienna-secession"],
  techniques:["watercolor","oil-painting"], style:"expressionist",
  palette:["#b0703a","#8a3a32","#3e4a52","#e8dcc4","#22201e"],
  tagline:"The body as confession — Vienna's enfant terrible, gone at twenty-eight",
  works:[{t:"Self-Portrait with Physalis",y:"1912"},{t:"Death and the Maiden",y:"1915"},{t:"The Embrace",y:"1917"}],
  life:"Son of a syphilitic stationmaster whose madness and death scarred him, Schiele was admitted to Vienna's Academy at sixteen and adopted by Klimt, who traded drawings with him and sent him models. He married Edith Harms in 1915; in October 1918 the Spanish flu killed her, six months pregnant, and then him three days later, at twenty-eight.",
  career:"In a decade he produced around 330 paintings and thousands of works on paper: bodies twisted into angular hieroglyphs of desire and dread, self-portraits grimacing, emaciated, doubled. His line — nervous, unerring, drawn without correction — may be the surest in modern art. The 1912 Neulengbach affair (24 days jailed, one drawing burned by the judge) only sharpened the legend.",
  outside:"Obsessed with his own image, he posed before mirrors like an actor and wrote poems as overheated as his gouaches. In his last year, respectability arriving, his Secession show sold out — death caught him precisely at the turn of fortune.",
  facts:["He painted his dying wife's portrait the night before her death — his last work.",
    "Over a hundred self-portraits survive: art history's most relentless selfie archive before the word.",
    "Restitution battles over his Nazi-looted works (notably Portrait of Wally) reshaped international art law."] },

{ id:"ernst-ludwig-kirchner", name:"Ernst Ludwig Kirchner", years:"1880–1938", born:1880, died:1938,
  nation:"germany", eras:["20th-century"], movements:["expressionism","die-brucke"],
  techniques:["oil-painting","woodblock"], style:"expressionist",
  palette:["#e0427a","#2e8a8a","#e8a82e","#3e3a52","#1d1c22"],
  tagline:"Electric streets, jagged nerves — Die Brücke's burning core",
  works:[{t:"Street, Berlin",y:"1913"},{t:"Self-Portrait as a Soldier",y:"1915"},{t:"Marzella",y:"1909–10"}],
  life:"An architecture student in Dresden, Kirchner co-founded Die Brücke in 1905 — four young men vowing to bridge to a freer art and life. WWI service broke him; discharged after a breakdown, addicted to morphine, he recovered in Davos painting Alpine peace. In 1938, sick and branded 'degenerate' by the Nazis, he shot himself outside his mountain house.",
  career:"His Berlin street scenes — cocottes like exotic birds, crowds slashed in feathered strokes of pink and poison green — are Expressionism's metropolitan masterpieces. With Die Brücke he revived the woodcut's splintered force, and his angular nudes in studios hung with carved furniture and batiks proposed art as total bohemian life. Self-Portrait as a Soldier, painting hand 'amputated,' is the war's most chilling artist-image.",
  outside:"In Davos he chronicled himself compulsively — photographs, alpine diaries, even reviews of his own work published under the invented critic 'Louis de Marsalle.' Over 600 of his works were seized from German museums in 1937.",
  facts:["He backdated canvases to claim priority over rivals — art historians untangle his chronology to this day.",
    "32 of his works hung in the Nazis' Degenerate Art exhibition the year before his suicide.",
    "Die Brücke's name came from Nietzsche: man as 'a bridge and not an end.'"] },

{ id:"giorgio-de-chirico", name:"Giorgio de Chirico", years:"1888–1978", born:1888, died:1978,
  nation:"italy", eras:["20th-century"], movements:["metaphysical-painting","surrealism"],
  techniques:["oil-painting","tempera","glazing"], style:"metaphysical",
  palette:["#2e8a7a","#d9a83e","#b05e32","#3e4a6e","#e8d9b4"],
  tagline:"Empty piazzas at five o'clock — the stage Surrealism stole",
  works:[{t:"The Song of Love",y:"1914"},{t:"Mystery and Melancholy of a Street",y:"1914"},{t:"The Disquieting Muses",y:"1916–18"}],
  life:"Born to Italian parents in Volos, Greece — son of a railway engineer, hence perhaps all those trains — de Chirico absorbed Nietzsche and Böcklin in Munich before unveiling his deserted squares in Paris. After 1919 he pivoted to old-master classicism, feuding spectacularly with the Surrealists who worshipped his early work. He died in Rome at ninety, signing himself 'Pictor Optimus.'",
  career:"Between 1911 and 1918 he painted the century's loneliest places: arcades casting wrong shadows, towers, gloves, artichokes, a girl with a hoop running toward something unseen. Magritte wept before The Song of Love in reproduction; Breton built Surrealism on the mood. His later renunciation — and his habit of backdating new 'metaphysical' canvases — created an authentication minefield he seemed to enjoy.",
  outside:"He wrote a hallucinatory novel, Hebdomeros, designed for the ballet and opera, and conducted a one-man war on modern art critics ('I am the only true painter'). His brother, under the name Alberto Savinio, was a notable Surrealist writer-painter himself.",
  facts:["He sued collectors and galleries over works he falsely claimed were forgeries — including some he had genuinely painted.",
    "He repainted his 1910s masterpieces on demand for decades — 'verifalsi', true-fakes, now haunt auction houses.",
    "Hitchcock, Antonioni and countless video games borrowed his empty-piazza dread."] },

{ id:"salvador-dali", name:"Salvador Dalí", years:"1904–1989", born:1904, died:1989,
  nation:"spain", eras:["20th-century"], movements:["surrealism"],
  techniques:["oil-painting","glazing","etching"], style:"surreal",
  palette:["#d9b894","#8aa7c4","#5e4a32","#e8d4a8","#2a3440"],
  tagline:"Melting clocks and a waxed moustache — the dream rendered in miniature precision",
  works:[{t:"The Persistence of Memory",y:"1931"},{t:"Swans Reflecting Elephants",y:"1937"},{t:"Christ of Saint John of the Cross",y:"1951"}],
  life:"Born in Figueres, Catalonia — named for a dead elder brother, a ghost he said he spent life distinguishing himself from — Dalí was expelled from Madrid's academy for declaring the examiners incompetent. With Gala, his manager-muse-wife, he conquered Paris, then America, returning to Spain under Franco to build his own museum, where he lies buried beneath the stage.",
  career:"His 'paranoiac-critical method' — systematic self-induced delirium — produced the canon of dream painting: soft watches, spider-legged elephants, lobster telephones, all executed with Vermeer-grade technique he called 'hand-painted dream photographs.' Expelled from the Surrealist group in 1934 for politics and showmanship, he answered: 'I myself am Surrealism.'",
  outside:"He co-wrote Un Chien Andalou with Buñuel, designed Hitchcock's Spellbound dream sequence and the Chupa Chups logo, walked an anteater on a leash in Paris, and arrived at a lecture in a diving suit (nearly suffocating). The moustache, he explained, served as antennae for receiving ideas.",
  facts:["Asked if he took drugs: 'I don't do drugs. I am drugs.'",
    "He signed sheets of blank paper for lithographs — a forger's paradise he found hilarious.",
    "His brother died nine months before his birth; his parents told him he was the reincarnation."] },

{ id:"rene-magritte", name:"René Magritte", years:"1898–1967", born:1898, died:1967,
  nation:"belgium", eras:["20th-century"], movements:["surrealism"],
  techniques:["oil-painting","glazing"], style:"surreal",
  palette:["#7aa7d9","#e8e4d4","#2a3440","#5e6e5a","#1d1c1a"],
  tagline:"This is not a painter — the bowler-hatted saboteur of common sense",
  works:[{t:"The Treachery of Images (Ceci n'est pas une pipe)",y:"1929"},{t:"The Son of Man",y:"1964"},{t:"Empire of Light",y:"1953–54"},{t:"Golconda",y:"1953"}],
  life:"Born in provincial Belgium, Magritte was thirteen when his mother drowned herself in the Sambre — she was found, the story goes, with her nightdress over her face, an image readers find everywhere in his veiled heads. He lived a deliberately unremarkable Brussels life with his wife Georgette and a Pomeranian, painting in the dining room in a suit, and died of cancer at sixty-eight.",
  career:"Magritte painted impossibilities with a notary's neatness: a pipe captioned 'this is not a pipe,' day and night sharing one street, a green apple obscuring a bowler-hatted everyman, men raining on the suburbs. No melting, no bravura — just logic quietly cut at the wires. Conceptual art, Pop and the entire advertising industry have been drawing on his account ever since.",
  outside:"He worked years in advertising and, during the war, allegedly forged Picassos, Braques — and banknotes — with his brother to survive. The Surrealist pope Breton once scolded Georgette's crucifix at a party; Magritte sided with his wife over the movement.",
  facts:["The Son of Man was commissioned as a self-portrait — apple included by way of evasion.",
    "He painted multiple Empires of Light because collectors kept asking; each is subtly different.",
    "Paul McCartney's Magritte collection inspired the Beatles' Apple Corps name and logo."] },

{ id:"joan-miro", name:"Joan Miró", years:"1893–1983", born:1893, died:1983,
  nation:"spain", eras:["20th-century"], movements:["surrealism","abstract-art"],
  techniques:["oil-painting","automatism","lithography","collage"], style:"abstract",
  palette:["#c4302a","#2e50c4","#f0c82e","#1a1a1a","#f4f1e8"],
  tagline:"Constellations and ladders of escape — the assassin of painting, smiling",
  works:[{t:"The Farm",y:"1921–22"},{t:"Harlequin's Carnival",y:"1924–25"},{t:"Constellations series",y:"1940–41"},{t:"Blue II",y:"1961"}],
  life:"A Barcelona goldsmith's son who suffered a breakdown clerking in an office, Miró split his life between Paris's avant-garde and the Catalan farm at Mont-roig that anchored everything. Quiet, punctual and privately ferocious, he opposed Franco from within Spain in later years, settling in Mallorca where he worked until ninety.",
  career:"The Farm — every leaf and lizard of his family's land inventoried — was bought by Hemingway, who said it held everything Spain made you feel. Then Surrealist Paris dissolved the inventory into floating signs: stars, eyes, birds, genitalia, dancing in fields of blue. Declaring his wish to 'assassinate painting,' he attacked it lovingly with collage, burnt canvases, ceramic walls and bronze monsters for sixty years.",
  outside:"Early Paris hunger fed the visions — he claimed the hallucinations of an empty stomach put shapes on his ceiling. He designed for Diaghilev's ballet (earning a Surrealist scolding), made the World Cup '82 poster, and the giant Woman and Bird that greets visitors to Barcelona.",
  facts:["The Constellations, painted while fleeing WWII town to town, fit in a suitcase — 23 gouaches of pocket-size cosmos.",
    "Hemingway paid off The Farm in instalments borrowed from bartenders, by his own telling.",
    "His Mallorca studio, designed by Josep Lluís Sert, is preserved exactly as he left it — unfinished canvases waiting."] }
);
