/* PIGMENT — atlas widening batch 4: four painters the atlas already named.

   Backlog B3. Each of these was cited in Pigment's own prose — in another
   painter's life text, in a movement blurb, or in the name of the curator role
   itself — while having no record of their own. They are holes the atlas dug
   for itself, and they are the cheapest holes in it to fill, because the
   surrounding text already argues for their importance.

   All four died before 1955, so their work is public domain and their pages
   carry real reproductions rather than generative covers. */
window.ARTISTS = (window.ARTISTS || []).concat([

{ id:"giovanni-bellini", name:"Giovanni Bellini", years:"c. 1430–1516", born:1430, died:1516,
  nation:"italy", eras:["15th-century","16th-century"],
  movements:["early-renaissance","venetian-school","renaissance"],
  techniques:["oil-painting","tempera","glazing"], style:"renaissance",
  palette:["#2f5d7c","#c96f4a","#e6d3a8","#3f6b4f","#1b2733"],
  tagline:"The man who taught Venice that light was the subject",
  works:[{t:"Doge Leonardo Loredan",y:"c. 1501"},{t:"St Francis in the Desert",y:"c. 1480"},{t:"San Zaccaria Altarpiece",y:"1505"},{t:"The Feast of the Gods",y:"1514"}],
  life:"He was raised in the household of Jacopo Bellini, a painter long assumed to be his father — a relationship modern scholarship now questions rather than asserts. His brother Gentile was the more celebrated of the two in their lifetimes, and posterity has quietly reversed that verdict. Andrea Mantegna, the hardest and most sculptural draughtsman in northern Italy, married into the family and became his brother-in-law, which gave Giovanni a lifelong argument to paint against.",
  career:"Bellini changed what Venetian painting was for. Where Florence reasoned in line, he reasoned in colour and air, and the slow-drying oil paint arriving from the north let him build tone in translucent layers instead of laying it down once in tempera. The result was weather: skies that carry time of day, landscapes that hold a saint without upstaging him, faces lit rather than outlined. He ran the busiest workshop in Venice for half a century, and Giorgione and Titian both came through it — which means the whole Venetian tradition, and a good deal of what Europe later did with oil paint, runs back through this one studio.",
  outside:"He was still taking on new ideas in his eighties: The Feast of the Gods was painted at about eighty-four, and Titian later reworked part of its landscape. Albrecht Dürer, visiting Venice in 1506, wrote home that Bellini was very old and still the best in painting. The Bellini cocktail, invented at Harry's Bar in the twentieth century, is named after him for the colour.",
  facts:["Giorgione and Titian both trained in his workshop — the Venetian school begins here.",
    "His brother Gentile was the more famous Bellini in their own lifetimes.",
    "Andrea Mantegna was his brother-in-law, and the two painted the same subjects very differently.",
    "Dürer, visiting Venice in 1506, called him old and still the best painter there.",
    "The paternity long assumed between him and Jacopo Bellini is now questioned, not settled."] },

{ id:"andrea-del-verrocchio", name:"Andrea del Verrocchio", years:"c. 1435–1488", born:1435, died:1488,
  nation:"italy", eras:["15th-century"],
  movements:["early-renaissance","renaissance"],
  techniques:["oil-painting","tempera"], style:"renaissance",
  palette:["#8a6a3f","#c2b280","#2e4a3c","#7d3b2e","#e8dcc0"],
  tagline:"The workshop that produced Leonardo — and barely signed anything",
  works:[{t:"The Baptism of Christ",y:"c. 1475"},{t:"Madonna and Child",y:"c. 1470"},{t:"Tobias and the Angel",y:"c. 1470–75"}],
  life:"He was born Andrea di Michele di Francesco de' Cioni and took the name Verrocchio from the goldsmith he trained under — a working man's inheritance rather than a family one. Goldsmithing came first, then sculpture, then painting, and he never really stopped being all three at once. His Florence workshop became the most consequential room in fifteenth-century art: Leonardo da Vinci was apprenticed there, and Perugino and Lorenzo di Credi passed through as well.",
  career:"Verrocchio is the rare master whose importance is easier to prove through other people's work than his own. Very few paintings are attributed to him with certainty — the surviving panels are shared with pupils, argued over, and often filed as workshop rather than autograph. The Baptism of Christ is the famous case: the young Leonardo painted at least one of the angels, and the difference in handling is visible enough that Vasari built a story on it. As a sculptor the ground is firmer, and the equestrian monument to Bartolomeo Colleoni in Venice is his by common consent.",
  outside:"Vasari tells the story that Verrocchio, seeing what his teenage apprentice had done to that angel, resolved never to paint again. It is a good story, repeated for four centuries, and there is no contemporary evidence for it — Vasari was born nearly forty years after the picture was finished, and his Lives are known to be least reliable exactly here.",
  facts:["Leonardo da Vinci was his apprentice and worked on The Baptism of Christ.",
    "Very few paintings are certainly his; the workshop's output is shared and disputed.",
    "He was a goldsmith and sculptor first, and took his name from his own master.",
    "Perugino and Lorenzo di Credi also came out of his workshop.",
    "The story that Leonardo's angel made him give up painting is Vasari's, and unevidenced."] },

{ id:"giorgio-vasari", name:"Giorgio Vasari", years:"1511–1574", born:1511, died:1574,
  nation:"italy", eras:["16th-century"],
  movements:["mannerism","renaissance"],
  techniques:["oil-painting","fresco"], style:"renaissance",
  palette:["#7b2f3a","#3c5a8a","#d8b44a","#2b2a26","#e7dbc2"],
  tagline:"He invented art history, then wrote himself into the middle of it",
  works:[{t:"Six Tuscan Poets",y:"1544"},{t:"Self-Portrait",y:"c. 1567"},{t:"Portrait of Lorenzo de' Medici",y:"c. 1534"},{t:"Perseus and Andromeda",y:"c. 1570–72"}],
  life:"Born in Arezzo and trained in Florence, Vasari made himself indispensable to the Medici — effectively the court's minister of culture, running painting, architecture and pageantry for a state that understood all three as politics. He was highly regarded as a painter in his own day; later centuries have been markedly cooler about the pictures and warmer about everything else he did.",
  career:"His Lives of the Most Excellent Painters, Sculptors and Architects (1550, expanded 1568) is the foundation of Western art history — the first attempt to treat art as a story with a direction, told through the biographies of the people who made it. It is also a partisan document: it argues, with enduring success, that Florence was where art was reborn and best. Modern scholarship reads it as indispensable and unreliable in the same breath, especially on artists who died before he was born. As an architect he built the Uffizi; as a designer of tributes he built Michelangelo's tomb in Santa Croce.",
  outside:"He described Giotto's break with the old manner as a rinascita, a rebirth. Nearly three centuries later the historian Jules Michelet took that word into French as Renaissance, and it is now the name of the period — a whole era of art named by a painter nobody ranks in its first tier.",
  facts:["His Lives (1550, expanded 1568) is the founding text of Western art history.",
    "It is also openly partisan for Florence, and unreliable on painters he never met.",
    "He designed the Uffizi, and Michelangelo's tomb in Santa Croce.",
    "His word rinascita became, via Michelet in 1835, our word Renaissance.",
    "He was the Medici court's cultural manager as much as he was a painter."] },

{ id:"jean-leon-gerome", name:"Jean-Léon Gérôme", years:"1824–1904", born:1824, died:1904,
  nation:"france", eras:["19th-century"],
  movements:["academicism","orientalism"],
  techniques:["oil-painting"], style:"neoclassical",
  palette:["#c8a24a","#8c3b2f","#e9dcc3","#3e5f7a","#1f1b16"],
  tagline:"The most famous painter alive in 1880, and the case against his own genre",
  works:[{t:"The Snake Charmer",y:"c. 1879"},{t:"Pollice Verso",y:"1872"},{t:"Bonaparte Before the Sphinx",y:"1886"},{t:"Cleopatra and Caesar",y:"1866"}],
  life:"Gérôme trained under Paul Delaroche and rose fast inside the French academic system, which he then largely ran: Salon medals, a professorship at the École des Beaux-Arts, and a teaching career long enough to touch several generations. With Meissonier and Cabanel he was one of the three great commercial successes of the Second Empire, and by 1880 reproductions had made him arguably the most famous living artist in the world.",
  career:"His subjects were history, Greek myth, portraiture and the Near East, all painted with a finish so smooth it reads as photographic — the surface that made him a fortune in prints and made the Impressionists treat him as the enemy. He fought them publicly and lost; the twentieth century wrote academic painting out of the story almost entirely, and only recently put it back in as something to be examined rather than dismissed. The examination is not gentle. Linda Nochlin's essay The Imaginary Orient (1983) took his Snake Charmer as its central exhibit, arguing that such pictures present an invented, timeless, unpoliced East for European consumption and pass the invention off as documentary. Pigment holds the picture and the argument together, because they belong together.",
  outside:"He taught an extraordinary roll of students, several of whom are in this atlas: Osman Hamdi Bey, the Ottoman painter and archaeologist who turned the Orientalist manner back on its makers, and Mary Cassatt, who left the academic path entirely. Thomas Eakins and Edwin Lord Weeks were his pupils too.",
  facts:["By 1880 reproductions had made him arguably the most famous living artist on earth.",
    "He taught Osman Hamdi Bey and Mary Cassatt, who both went on to refuse most of what he stood for.",
    "Nochlin's The Imaginary Orient (1983) made his Snake Charmer the standard case against Orientalism.",
    "He campaigned publicly against the Impressionists, and lost the argument with posterity.",
    "He was a sculptor as well, and turned to it seriously in his last twenty years."] }

,

{ id:"jose-clemente-orozco", name:"José Clemente Orozco", years:"1883–1949", born:1883, died:1949,
  nation:"mexico", eras:["20th-century"],
  movements:["muralism","symbolism"],
  techniques:["fresco","oil-painting"], style:"expressionist",
  palette:["#a5322b","#d9a441","#3b5c4a","#2a2320","#e0d2b4"],
  tagline:"The muralist who refused to make the revolution look good",
  works:[{t:"Zapatistas",y:"1931"},{t:"Prometheus",y:"1930"},{t:"Barricade",y:"1931"},{t:"The Subway",y:"1928"}],
  life:"He lost his left hand and much of his hearing to a childhood accident with gunpowder, and came to painting through architectural drawing and political cartooning. The Mexican Revolution shaped everything he made, but not in the way a state commission usually wants: he had watched it up close, and what he took from it was less a programme than a grasp of what crowds and violence do to people.",
  career:"With Diego Rivera and David Alfaro Siqueiros he made the Mexican mural renaissance, and he is the one who complicates it. Rivera and Siqueiros were committed Marxists whose walls argue a case; Orozco's carry a leftist charge but keep flinching at their own side — his revolutionaries are as capable of cruelty as the men they overthrew, and his masses are frightening as often as they are heroic. Between 1922 and 1948 he painted in Mexico City, Orizaba, Guadalajara and Jiquilpan, and in the United States at Pomona College, the New School in New York and Dartmouth.",
  outside:"Prometheus at Pomona, painted in 1930, is generally counted the first significant modern fresco made in the United States, and Jackson Pollock travelled to see his work. The Hospicio Cabañas cycle in Guadalajara, with its Man of Fire in the dome, is a UNESCO World Heritage Site.",
  facts:["He lost a hand and most of his hearing to a gunpowder accident as a boy.",
    "He was the least doctrinaire of the three great muralists, and the bleakest.",
    "His 1930 Prometheus at Pomona is often called the first modern fresco in the United States.",
    "The Hospicio Cabañas cycle in Guadalajara is a UNESCO World Heritage Site.",
    "He began as a political cartoonist, and the bite never entirely left the murals."] },

{ id:"david-alfaro-siqueiros", name:"David Alfaro Siqueiros", years:"1896–1974", born:1896, died:1974,
  nation:"mexico", eras:["20th-century"],
  movements:["muralism"],
  techniques:["fresco","oil-painting"], style:"expressionist",
  palette:["#b3342c","#2f4f6b","#d7b45a","#1e1b18","#8a8f7d"],
  tagline:"Muralist, soldier, communist — and a would-be assassin",
  works:[{t:"Echo of a Scream",y:"1937"},{t:"Collective Suicide",y:"1936"},{t:"The March of Humanity",y:"1964–71"}],
  life:"Born in the city of Chihuahua — long misreported as Camargo until a baptismal record settled it in 2003 — he took his mother's surname in the Spanish manner, as Picasso and Lorca did. He fought in the Mexican Revolution as a teenager and never really stopped being a soldier: he went to Spain to defend the Republic against Franco and served in frontline combat as a lieutenant colonel through 1938.",
  career:"He was the technical radical of the three great muralists, working with industrial paints, spray guns and photographic projection while his colleagues used fresco, and arguing that a revolutionary art needed revolutionary tools. The politics were not a pose. He was a member of the Mexican Communist Party, and in 1940 he led an armed attack on Leon Trotsky's house in Mexico City: Trotsky survived, his fourteen-year-old grandson was shot, and the American communist Robert Sheldon Harte was taken away and killed. Siqueiros went on the run, was caught in Jalisco, and was released without ever being brought to trial.",
  outside:"He was jailed again in the 1960s for social dissolution, and painted in prison. The Polyforum Siqueiros in Mexico City, which houses The March of Humanity, is the largest mural he ever made — and among the largest anywhere.",
  facts:["He led the failed 1940 attack on Trotsky's house; a boy was shot and a man was killed.",
    "He was never brought to trial for it.",
    "He fought in Spain against Franco as a lieutenant colonel.",
    "He used spray guns and industrial paint when the others used fresco.",
    "His work is still in copyright, so this page carries a generative cover, not a reproduction."] },

{ id:"jozef-mehoffer", name:"Józef Mehoffer", years:"1869–1946", born:1869, died:1946,
  nation:"poland", eras:["19th-century","20th-century"],
  movements:["young-poland","symbolism"],
  techniques:["oil-painting"], style:"ornament",
  palette:["#2f6b4e","#c9a227","#7a3b52","#e6dfc8","#1d2b2a"],
  tagline:"Young Poland's decorator, and a garden that will not behave",
  works:[{t:"Strange Garden",y:"1903"},{t:"Zinnias",y:"1911"},{t:"Self-Portrait",y:"1897"}],
  life:"He trained in Kraków and then in Vienna and Paris, and came home into the Young Poland generation — the turn-of-the-century movement that carried Symbolism and Art Nouveau into a country that did not, at the time, exist on the map. He worked across painting, stained glass and decorative design without treating any of them as the lesser job.",
  career:"His stained glass is the largest part of the work and the least portable: the windows for the collegiate church in Fribourg, won in an international competition in 1895, occupied him for decades. On canvas his reputation rests substantially on one picture, Strange Garden (1903) — his wife and son in a sunlit orchard under an enormous golden dragonfly that nobody has ever satisfactorily explained. It is realist in handling and completely unreal in effect, which is Young Poland in one frame.",
  outside:"He edited the arts journal Life, designed banknotes and postage stamps for the reborn Polish state after 1918, and taught at the Kraków academy for most of his working life.",
  facts:["Strange Garden's giant golden dragonfly has never been satisfactorily explained.",
    "He won the Fribourg cathedral stained-glass commission in 1895 and worked on it for decades.",
    "He designed banknotes and stamps for Poland after it reappeared as a state in 1918.",
    "He was a leading figure of Young Poland, alongside Wyspiański."] },

{ id:"aliye-berger", name:"Aliye Berger", years:"1903–1974", born:1903, died:1974,
  nation:"turkey", eras:["20th-century"],
  movements:["expressionism"],
  techniques:["printmaking"], style:"expressionist",
  palette:["#1f1c1a","#c4c0b6","#8c4a34","#5a6b74","#e8e2d6"],
  tagline:"One of Turkey's first engravers, who started at forty-four",
  works:[{t:"Sun (competition painting)",y:"1954"},{t:"Istanbul engravings",y:"1950s"},{t:"Boats on the Bosphorus",y:"1950s"}],
  life:"She was born into the remarkable Şakir Pasha family — her sister was the painter Fahrelnissa Zeid, her brother the writer known as the Fisherman of Halicarnassus. She married the Hungarian musician Karl Berger, and after his death in 1947 she went to London to learn engraving, beginning the working life she is remembered for at forty-four.",
  career:"She became one of the first engravers in Turkey, and the expressionist bite of the prints — Istanbul rooftops, boats, crowds, all cut in restless line — is the reason the medium took hold there when it did. In 1954 she won the Yapı Kredi Bank painting competition, a decision that caused a public argument loud enough to be remembered as a turning point in Turkish art: a woman, a printmaker, and a late starter, beating the establishment.",
  outside:"The Şakir Pasha family produced so many artists and writers that Turkish criticism treats it as a phenomenon in itself. Her sister Fahrelnissa Zeid became the better-known painter internationally; Aliye stayed with the burin.",
  facts:["She took up engraving at forty-four, after her husband's death.",
    "She was one of the first engravers working in Turkey.",
    "Her 1954 competition win caused a public row now read as a turning point.",
    "Her sister was the painter Fahrelnissa Zeid.",
    "Her work is still in copyright, so this page carries a generative cover, not a reproduction."] }

]);
