/* PIGMENT — artwork catalog, formerly copyright-held throughout.
   Most records here still deliberately omit reproductions: their seeded
   generative covers identify them throughout the atlas without imitating the
   original compositions. Every work remains admirable, saveable and linkable.

   EXCEPTION — the seven Matisse works of 1905–1916 (2026-08-27). Matisse died
   in 1954, so the atlas's own died-≤-1955 rule always covered him; the records
   were walled anyway. Commons now carries these seven under PD-old-70 / PD-Art
   / PD-US-expired, and each record cites the file page asserting it. His two
   late works (Blue Nude II 1952, The Snail 1953) stay walled: a life+70 term
   ran out in Europe, but their US term has not. Basis recorded in
   docs/corrections/matisse-public-domain.md. Nothing here is a rights
   determination or legal advice (OD-5). */
window.CATALOG = (window.CATALOG || []).concat([

/* ---------- Henri Matisse ---------- */
{ id:"woman-with-a-hat", tier:1, title:"Woman with a Hat", artistId:"henri-matisse",
  year:{display:"1905",sort:1905}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"sfmoma",name:"San Francisco Museum of Modern Art",city:"San Francisco"},
  worksKey:"Woman with a Hat",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Matisse-Woman-with-a-Hat.jpg/500px-Matisse-Woman-with-a-Hat.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Matisse-Woman-with-a-Hat.jpg", status:"pd" },
  coords:{F:-65,D:40,E:65,C:-60,M:-35}, coordsSource:"override",
  description:"His wife Amélie, in a black dress — Matisse said so himself when asked, though nothing here is black. The hat is a landslide of orange and violet; a green shadow divides the face for no reason the eye can justify. Hung at the 1905 Salon d'Automne in the room a critic nicknamed the cage of wild beasts, it was laughed at and scratched at. Gertrude and Leo Stein bought it anyway, and Fauvism had its first patron.",
  notice:["The green stripe down her face — the shadow that started the scandal",
          "Matisse insisted the dress was black; the paint says every colour but",
          "Bare canvas shows through at the edges: finished, and left unfinished"],
  tags:["portrait", "red", "experimental", "would-hang"],
  related:["the-joy-of-life", "open-window-collioure"] },
{ id:"the-joy-of-life", tier:1, title:"The Joy of Life", artistId:"henri-matisse",
  year:{display:"1905–06",sort:1905}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"barnes-foundation",name:"Barnes Foundation",city:"Philadelphia"},
  worksKey:"The Joy of Life",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Le_Bonheur_de_vivre_Barnes_%2801c%29_-_Flickr_-_rverc.jpg/500px-Le_Bonheur_de_vivre_Barnes_%2801c%29_-_Flickr_-_rverc.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Le_Bonheur_de_vivre_Barnes_(01c)_-_Flickr_-_rverc.jpg", status:"pd" },
  coords:{F:-45,D:5,E:70,C:-80,M:45}, coordsSource:"override",
  description:"An Arcadia with the rules removed: bodies drawn in one sinuous line, colour cut loose from description, each figure keeping its own scale as though the picture were assembled out of separate dreams. Signac, who had backed him, called it a catastrophe. Leo Stein bought it and hung it near his Picassos, setting off the rivalry that produced Les Demoiselles d'Avignon a year later. The ring of dancers at the centre would become, in 1910, The Dance.",
  notice:["The small ring of dancers at the back — the seed of The Dance",
          "Every figure is scaled to itself; nothing shares a horizon",
          "Line does the drawing, colour does the mood, and they never quite agree"],
  tags:["landscape", "nude", "would-hang", "experimental"],
  related:["the-dance-matisse", "woman-with-a-hat"] },
{ id:"open-window-collioure", tier:1, title:"Open Window, Collioure", artistId:"henri-matisse",
  year:{display:"1905",sort:1905}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"national-gallery-dc",name:"National Gallery of Art",city:"Washington, D.C."},
  worksKey:"Open Window, Collioure",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Matisse-Open-Window.jpg/500px-Matisse-Open-Window.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Matisse-Open-Window.jpg", status:"pd" },
  coords:{F:-55,D:-25,E:60,C:-75,M:-55}, coordsSource:"override",
  description:"Summer in a Catalan fishing port, painted with the shutters thrown open and the rules thrown out. Boats ride a harbour of pink and turquoise; the wall on the left is green, the wall on the right violet, and nothing explains it except that the pairing sings. Inside and outside sit on one flat plane, the window frame doing the work perspective used to do. Matisse painted windows for another fifty years. This is the one that opened.",
  notice:["Interior and exterior share a single flat surface — intervals, not depth",
          "The two walls are different colours; the picture never justifies it",
          "Painted at Collioure with Derain, the summer Fauvism was invented"],
  tags:["interior", "landscape", "would-hang", "experimental"],
  related:["woman-with-a-hat", "the-red-studio"] },
{ id:"the-dance-matisse", tier:1, title:"The Dance", artistId:"henri-matisse",
  year:{display:"1910",sort:1910}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"hermitage",name:"The State Hermitage Museum",city:"St Petersburg"},
  worksKey:"The Dance",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/La_Danse_II%2C_par_Henri_Matisse.jpg/500px-La_Danse_II%2C_par_Henri_Matisse.jpg",
          page:"https://commons.wikimedia.org/wiki/File:La_Danse_II,_par_Henri_Matisse.jpg", status:"pd" },
  coords:{F:-35,D:65,E:70,C:-70,M:70}, coordsSource:"override",
  description:"Three colours and five bodies and nothing else at all: vermilion figures on blue sky and green earth, circling a hill that curves like the top of the world. Matisse painted it for the staircase of the Moscow merchant Sergei Shchukin, who panicked about the nudity, accepted it anyway, and hung it where every guest had to climb past. Look at the left-hand pair — the ring is broken, the grip slipping. The whole dance strains to close it.",
  notice:["The circle is broken at the left: two hands not quite meeting",
          "Three colours carry the entire painting — vermilion, blue, green",
          "Painted for a staircase, to be seen from below while climbing"],
  tags:["figures", "dance", "monumental-scale", "would-hang"],
  related:["the-joy-of-life", "the-red-studio"] },
{ id:"the-red-studio", tier:1, title:"The Red Studio", artistId:"henri-matisse",
  year:{display:"1911",sort:1911}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"},
  worksKey:"The Red Studio",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/L%27Atelier_rouge%2C_par_Henri_Matisse.jpg/500px-L%27Atelier_rouge%2C_par_Henri_Matisse.jpg",
          page:"https://commons.wikimedia.org/wiki/File:L%27Atelier_rouge,_par_Henri_Matisse.jpg", status:"pd" },
  coords:{F:15,D:-15,E:75,C:-55,M:20}, coordsSource:"override",
  description:"A room drowned in Venetian red — floor, walls, table, all one continuous field — with the furniture surviving only as thin lines where the red was left open. The paintings on the walls keep their colours. In Matisse's studio the art is more solid than the furniture holding it up. Conservators later found a blue-green room underneath: he painted the studio conventionally, then flooded it. No buyer wanted it for eleven years.",
  notice:["The furniture is drawn by absence — bare lines where the red stops",
          "His own canvases keep full colour; the room around them does not",
          "Beneath the red is a blue-green studio, found by conservators"],
  tags:["interior", "red", "experimental", "would-hang"],
  related:["the-piano-lesson", "goldfish-matisse"] },
{ id:"goldfish-matisse", tier:1, title:"Goldfish", artistId:"henri-matisse",
  year:{display:"1912",sort:1912}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"pushkin-museum",name:"Pushkin State Museum of Fine Arts",city:"Moscow"},
  worksKey:"Goldfish",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/I_pesci_rossi.jpg/500px-I_pesci_rossi.jpg",
          page:"https://commons.wikimedia.org/wiki/File:I_pesci_rossi.jpg", status:"pd" },
  coords:{F:-45,D:-55,E:45,C:-70,M:-55}, coordsSource:"override",
  description:"Four fish in a glass cylinder, seen twice at once: from the side through the water, and from above as red commas resting on the surface. Matisse had returned from Morocco, where he watched men gaze into pools for hours, and he wanted the picture to work the way that trance did. Greenery crowds in; the pink table tilts up to meet you. The fish hold the only pure colour, and the whole room leans toward them.",
  notice:["The bowl is shown from the side and from above simultaneously",
          "The table tilts up toward you — depth traded for pattern",
          "Pure red appears only in the fish; everything else is held back"],
  tags:["interior", "quiet", "would-hang", "green"],
  related:["the-red-studio", "the-piano-lesson"] },
{ id:"the-piano-lesson", tier:1, title:"The Piano Lesson", artistId:"henri-matisse",
  year:{display:"1916",sort:1916}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"},
  worksKey:"The Piano Lesson",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/La_Le%C3%A7on_de_piano%2C_par_Henri_Matisse.jpg/500px-La_Le%C3%A7on_de_piano%2C_par_Henri_Matisse.jpg",
          page:"https://commons.wikimedia.org/wiki/File:La_Le%C3%A7on_de_piano,_par_Henri_Matisse.jpg", status:"pd" },
  coords:{F:5,D:-30,E:70,C:-20,M:-35}, coordsSource:"override",
  description:"His son Pierre at the keyboard, reduced to a wedge of grey with a scored triangle of shadow across one eye. This is Matisse at his most severe: wartime, Cubist-adjacent, colour rationed to grey-green and one slice of garden. Two of his own works stand guard — a painted woman perched high at the right, a bronze nude reclining at the left. The metronome ticks in the middle. Practice, watched by art, in a house where the war goes unmentioned.",
  notice:["The grey triangle across Pierre's eye — a shadow with a ruler's edge",
          "Top right is Matisse's own painting; bottom left, his own sculpture",
          "Green enters once, through the window, and nowhere else"],
  tags:["interior", "geometry", "quiet", "figures"],
  related:["the-red-studio", "goldfish-matisse"] },
{ id:"blue-nude-ii", tier:2, title:"Blue Nude II", artistId:"henri-matisse",
  year:{display:"1952",sort:1952}, movements:["fauvism"], techniques:["collage","flat-color"], nation:"france",
  museum:{id:"centre-pompidou",name:"Centre Pompidou",city:"Paris"}, image:{status:"copyright"},
  coords:{F:10,D:10,E:85,C:-65,M:10}, tags:["nude","blue","cut-paper"] },
{ id:"the-snail", tier:2, title:"The Snail", artistId:"henri-matisse",
  year:{display:"1953",sort:1953}, movements:["fauvism"], techniques:["collage","flat-color"], nation:"france",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"}, image:{status:"copyright"},
  coords:{F:75,D:-10,E:90,C:-35,M:45}, tags:["abstract","pattern","playful"] },

/* ---------- Pablo Picasso ---------- */
{ id:"the-old-guitarist", tier:2, title:"The Old Guitarist", artistId:"pablo-picasso",
  year:{display:"1903–04",sort:1903}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"art-institute-chicago",name:"The Art Institute of Chicago",city:"Chicago"}, image:{status:"copyright"},
  coords:{F:-75,D:55,E:25,C:10,M:-55}, tags:["portrait","blue","lonely"] },
{ id:"family-of-saltimbanques", tier:2, title:"Family of Saltimbanques", artistId:"pablo-picasso",
  year:{display:"1905",sort:1905}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"national-gallery-dc",name:"National Gallery of Art",city:"Washington, D.C."}, image:{status:"copyright"},
  coords:{F:-70,D:15,E:35,C:-20,M:5}, tags:["figures","circus","lonely"] },
{ id:"les-demoiselles-davignon", tier:2, title:"Les Demoiselles d'Avignon", artistId:"pablo-picasso",
  year:{display:"1907",sort:1907}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:-25,D:75,E:95,C:20,M:55}, tags:["nude","unsettling","experimental"] },
{ id:"ma-jolie", tier:2, title:"Ma Jolie", artistId:"pablo-picasso",
  year:{display:"1911–12",sort:1911}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:65,D:10,E:90,C:30,M:-10}, tags:["portrait","geometry","pattern"] },
{ id:"still-life-chair-caning", tier:2, title:"Still Life with Chair Caning", artistId:"pablo-picasso",
  year:{display:"1912",sort:1912}, movements:["cubism"], techniques:["collage","oil-painting"], nation:"spain",
  museum:{id:"musee-picasso-paris",name:"Musée Picasso",city:"Paris"}, image:{status:"copyright"},
  coords:{F:55,D:-5,E:95,C:60,M:-35}, tags:["still-life","collage","experimental"] },
{ id:"three-musicians", tier:2, title:"Three Musicians", artistId:"pablo-picasso",
  year:{display:"1921",sort:1921}, movements:["cubism"], techniques:["oil-painting","collage"], nation:"spain",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:25,D:20,E:75,C:-15,M:35}, tags:["figures","music","geometry"] },
{ id:"girl-before-a-mirror", tier:2, title:"Girl before a Mirror", artistId:"pablo-picasso",
  year:{display:"1932",sort:1932}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:-10,D:45,E:75,C:-40,M:15}, tags:["portrait","mirror","pattern"] },
{ id:"guernica", tier:2, title:"Guernica", artistId:"pablo-picasso",
  year:{display:"1937",sort:1937}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"reina-sofia",name:"Museo Reina Sofía",city:"Madrid"}, image:{status:"copyright"},
  coords:{F:-30,D:100,E:85,C:65,M:95}, tags:["historical","war","monumental-scale"] },
{ id:"the-weeping-woman", tier:2, title:"The Weeping Woman", artistId:"pablo-picasso",
  year:{display:"1937",sort:1937}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"}, image:{status:"copyright"},
  coords:{F:-30,D:90,E:80,C:20,M:-25}, tags:["portrait","unsettling","mourning"] },
{ id:"las-meninas-picasso", tier:2, title:"Las Meninas (series)", artistId:"pablo-picasso",
  year:{display:"1957",sort:1957}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"museu-picasso-barcelona",name:"Museu Picasso",city:"Barcelona"}, image:{status:"copyright"},
  coords:{F:10,D:45,E:80,C:45,M:55}, tags:["interior","historical","series"] },

/* ---------- Salvador Dalí ---------- */
{ id:"the-great-masturbator", tier:2, title:"The Great Masturbator", artistId:"salvador-dali",
  year:{display:"1929",sort:1929}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"reina-sofia",name:"Museo Reina Sofía",city:"Madrid"}, image:{status:"copyright"},
  coords:{F:-40,D:65,E:70,C:40,M:-25}, tags:["dream","unsettling","desire"] },
{ id:"the-persistence-of-memory", tier:2, title:"The Persistence of Memory", artistId:"salvador-dali",
  year:{display:"1931",sort:1931}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:-45,D:45,E:75,C:45,M:-45}, tags:["dream","landscape","time"] },
{ id:"swans-reflecting-elephants", tier:2, title:"Swans Reflecting Elephants", artistId:"salvador-dali",
  year:{display:"1937",sort:1937}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:-50,D:25,E:70,C:35,M:-20}, tags:["dream","reflection","double-image"] },
{ id:"metamorphosis-of-narcissus", tier:2, title:"Metamorphosis of Narcissus", artistId:"salvador-dali",
  year:{display:"1937",sort:1937}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"}, image:{status:"copyright"},
  coords:{F:-45,D:35,E:75,C:50,M:0}, tags:["mythological","double-image","dream"] },
{ id:"dream-flight-bee", tier:2, title:"Dream Caused by the Flight of a Bee", artistId:"salvador-dali",
  year:{display:"1944",sort:1944}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"thyssen-bornemisza",name:"Museo Nacional Thyssen-Bornemisza",city:"Madrid"}, image:{status:"copyright"},
  coords:{F:-55,D:70,E:65,C:10,M:5}, tags:["dream","tiger","unsettling"] },
{ id:"christ-saint-john-cross", tier:2, title:"Christ of Saint John of the Cross", artistId:"salvador-dali",
  year:{display:"1951",sort:1951}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"kelvingrove",name:"Kelvingrove Art Gallery and Museum",city:"Glasgow"}, image:{status:"copyright"},
  coords:{F:-75,D:70,E:15,C:15,M:75}, tags:["sacred","spiritual","monumental-scale"] },
{ id:"sacrament-last-supper", tier:2, title:"The Sacrament of the Last Supper", artistId:"salvador-dali",
  year:{display:"1955",sort:1955}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"national-gallery-dc",name:"National Gallery of Art",city:"Washington, D.C."}, image:{status:"copyright"},
  coords:{F:-60,D:30,E:20,C:25,M:80}, tags:["sacred","geometry","spiritual"] },
{ id:"hallucinogenic-toreador", tier:2, title:"The Hallucinogenic Toreador", artistId:"salvador-dali",
  year:{display:"1969–70",sort:1969}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"dali-museum-florida",name:"The Dalí Museum",city:"St Petersburg"}, image:{status:"copyright"},
  coords:{F:-15,D:70,E:70,C:55,M:90}, tags:["double-image","bullfight","monumental-scale"] },

/* ---------- Frida Kahlo ---------- */
{ id:"self-portrait-velvet-dress", tier:2, title:"Self-Portrait in a Velvet Dress", artistId:"frida-kahlo",
  year:{display:"1926",sort:1926}, movements:["naive-art","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:-90,D:20,E:25,C:-20,M:-65}, tags:["portrait","tender","intimate"] },
{ id:"henry-ford-hospital", tier:2, title:"Henry Ford Hospital", artistId:"frida-kahlo",
  year:{display:"1932",sort:1932}, movements:["surrealism","naive-art"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"museo-dolores-olmedo",name:"Museo Dolores Olmedo",city:"Mexico City"}, image:{status:"copyright"},
  coords:{F:-80,D:85,E:55,C:55,M:-80}, tags:["body","mourning","unsettling"] },
{ id:"my-birth-kahlo", tier:2, title:"My Birth", artistId:"frida-kahlo",
  year:{display:"1932",sort:1932}, movements:["surrealism","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:-75,D:95,E:60,C:55,M:-75}, tags:["body","birth","unsettling"] },
{ id:"the-two-fridas", tier:2, title:"The Two Fridas", artistId:"frida-kahlo",
  year:{display:"1939",sort:1939}, movements:["surrealism","naive-art","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"museo-arte-moderno-mexico",name:"Museo de Arte Moderno",city:"Mexico City"}, image:{status:"copyright"},
  coords:{F:-80,D:75,E:55,C:45,M:20}, tags:["self-portrait","double","mourning"] },
{ id:"thorn-necklace-hummingbird", tier:2, title:"Self-Portrait with Thorn Necklace and Hummingbird", artistId:"frida-kahlo",
  year:{display:"1940",sort:1940}, movements:["surrealism","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"harry-ransom-center",name:"Harry Ransom Center",city:"Austin"}, image:{status:"copyright"},
  coords:{F:-90,D:60,E:45,C:35,M:-70}, tags:["self-portrait","animal","unsettling"] },
{ id:"the-broken-column", tier:2, title:"The Broken Column", artistId:"frida-kahlo",
  year:{display:"1944",sort:1944}, movements:["surrealism","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"museo-dolores-olmedo",name:"Museo Dolores Olmedo",city:"Mexico City"}, image:{status:"copyright"},
  coords:{F:-85,D:95,E:50,C:45,M:-55}, tags:["self-portrait","body","pain"] },
{ id:"the-wounded-deer", tier:2, title:"The Wounded Deer", artistId:"frida-kahlo",
  year:{display:"1946",sort:1946}, movements:["surrealism","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:-65,D:80,E:55,C:35,M:-45}, tags:["self-portrait","animal","wound"] },
{ id:"diego-and-i", tier:2, title:"Diego and I", artistId:"frida-kahlo",
  year:{display:"1949",sort:1949}, movements:["surrealism","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:-90,D:75,E:45,C:40,M:-85}, tags:["self-portrait","mourning","intimate"] },
{ id:"marxism-health-sick", tier:2, title:"Marxism Will Give Health to the Sick", artistId:"frida-kahlo",
  year:{display:"1954",sort:1954}, movements:["symbolism","naive-art"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"museo-frida-kahlo",name:"Museo Frida Kahlo",city:"Mexico City"}, image:{status:"copyright"},
  coords:{F:-55,D:70,E:65,C:75,M:5}, tags:["self-portrait","political","body"] },

/* ---------- Jackson Pollock ---------- */
{ id:"mural-pollock", tier:2, title:"Mural", artistId:"jackson-pollock",
  year:{display:"1943",sort:1943}, movements:["abstract-expressionism","action-painting"], techniques:["oil-painting","gestural-abstraction"], nation:"usa",
  museum:{id:"stanley-museum-iowa",name:"Stanley Museum of Art",city:"Iowa City"}, image:{status:"copyright"},
  coords:{F:70,D:85,E:75,C:0,M:90}, tags:["abstract","rhythm","monumental-scale"] },
{ id:"full-fathom-five", tier:1, title:"Full Fathom Five", artistId:"jackson-pollock",
  year:{display:"1947",sort:1947}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:90,D:80,E:90,C:5,M:55},
  description:"One of the first paintings Pollock made by pouring, and there are objects buried in it: nails, tacks, buttons, keys, coins, a cigarette and matches, pressed into the paint and then poured over. The title is Ariel's song from The Tempest — full fathom five thy father lies — and the debris sits below the surface in very nearly the way the song describes.",
  notice:["Nails, buttons, keys and a cigarette are set into it",
          "The title is Ariel's song from The Tempest",
          "One of his earliest poured paintings, from 1947"], tags:["abstract","drip","dense"] },
{ id:"cathedral-pollock", tier:2, title:"Cathedral", artistId:"jackson-pollock",
  year:{display:"1947",sort:1947}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"dallas-museum-art",name:"Dallas Museum of Art",city:"Dallas"}, image:{status:"copyright"},
  coords:{F:90,D:80,E:90,C:5,M:60}, tags:["abstract","drip","black"] },
{ id:"number-5-1948", tier:2, title:"No. 5, 1948", artistId:"jackson-pollock",
  year:{display:"1948",sort:1948}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:95,D:85,E:90,C:10,M:55}, tags:["abstract","drip","dense"] },
{ id:"number-1a-1948", tier:2, title:"Number 1A, 1948", artistId:"jackson-pollock",
  year:{display:"1948",sort:1948}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:90,D:90,E:90,C:5,M:65}, tags:["abstract","drip","handprint"] },
{ id:"autumn-rhythm", tier:1, title:"Autumn Rhythm (Number 30)", artistId:"jackson-pollock",
  year:{display:"1950",sort:1950}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"met",name:"The Metropolitan Museum of Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:95,D:80,E:90,C:0,M:90},
  description:"Pollock laid the canvas flat on the floor of a barn at Springs and worked around all four sides of it, flinging and pouring household paint from sticks and stiffened brushes that never touched the surface. There is no up. There is no centre, and nowhere the eye is instructed to rest, which was the whole argument — and which is why the eye will not stop moving.",
  notice:["Painted flat on the floor, from all four sides",
          "House paint flung from sticks that never touch it",
          "No centre: nowhere the eye is told to settle"], tags:["abstract","drip","monumental-scale"] },
{ id:"convergence-pollock", tier:2, title:"Convergence", artistId:"jackson-pollock",
  year:{display:"1952",sort:1952}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"buffalo-akg",name:"Buffalo AKG Art Museum",city:"Buffalo"}, image:{status:"copyright"},
  coords:{F:90,D:95,E:90,C:5,M:85}, tags:["abstract","drip","color"] },
{ id:"blue-poles", tier:2, title:"Blue Poles", artistId:"jackson-pollock",
  year:{display:"1952",sort:1952}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"national-gallery-australia",name:"National Gallery of Australia",city:"Canberra"}, image:{status:"copyright"},
  coords:{F:85,D:90,E:85,C:5,M:90}, tags:["abstract","blue","monumental-scale"] },

/* ---------- Mark Rothko ---------- */
{ id:"slow-swirl-edge-sea", tier:2, title:"Slow Swirl at the Edge of the Sea", artistId:"mark-rothko",
  year:{display:"1944",sort:1944}, movements:["abstract-expressionism"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:30,D:-5,E:55,C:10,M:5}, tags:["mythological","figures","dream"] },
{ id:"no-61-rust-blue", tier:2, title:"No. 61 (Rust and Blue)", artistId:"mark-rothko",
  year:{display:"1953",sort:1953}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"moca-la",name:"Museum of Contemporary Art",city:"Los Angeles"}, image:{status:"copyright"},
  coords:{F:95,D:20,E:60,C:-5,M:65}, tags:["abstract","blue","meditative"] },
{ id:"no-14-rothko", tier:1, title:"No. 14", artistId:"mark-rothko",
  year:{display:"1960",sort:1960}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"sfmoma",name:"San Francisco Museum of Modern Art",city:"San Francisco"}, image:{status:"copyright"},
  coords:{F:95,D:15,E:60,C:-10,M:70},
  description:"Two rectangles of colour hovering on a ground, their edges left soft so that nothing quite sits still. Rothko built them from many thin washes, one over another, so the colour seems to come from behind the canvas rather than off it. He asked that his paintings be hung low and looked at from close up, and he objected to being called an abstract painter at all.",
  notice:["Thin washes: the colour appears lit from behind",
          "He wanted them hung low, and seen from close up",
          "He denied that he was an abstract painter"], tags:["abstract","orange","meditative"] },
{ id:"orange-and-yellow", tier:2, title:"Orange and Yellow", artistId:"mark-rothko",
  year:{display:"1956",sort:1956}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"buffalo-akg",name:"Buffalo AKG Art Museum",city:"Buffalo"}, image:{status:"copyright"},
  coords:{F:95,D:-15,E:55,C:-25,M:70}, tags:["abstract","golden","meditative"] },
{ id:"four-darks-in-red", tier:2, title:"Four Darks in Red", artistId:"mark-rothko",
  year:{display:"1958",sort:1958}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"whitney",name:"Whitney Museum of American Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:95,D:45,E:55,C:0,M:75}, tags:["abstract","red","unsettling"] },
{ id:"seagram-murals", tier:2, title:"The Seagram Murals", artistId:"mark-rothko",
  year:{display:"1958–59",sort:1958}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"}, image:{status:"copyright"},
  coords:{F:95,D:60,E:60,C:10,M:90}, tags:["abstract","red","monumental-scale"] },
{ id:"rothko-chapel-paintings", tier:2, title:"Rothko Chapel paintings", artistId:"mark-rothko",
  year:{display:"1964–67",sort:1964}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"rothko-chapel",name:"Rothko Chapel",city:"Houston"}, image:{status:"copyright"},
  coords:{F:98,D:60,E:55,C:5,M:100}, tags:["abstract","spiritual","monumental-scale"] },
{ id:"untitled-black-gray", tier:2, title:"Untitled (Black on Gray)", artistId:"mark-rothko",
  year:{display:"1969–70",sort:1969}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"guggenheim-ny",name:"Solomon R. Guggenheim Museum",city:"New York"}, image:{status:"copyright"},
  coords:{F:98,D:65,E:55,C:5,M:65}, tags:["abstract","black","unsettling"] },

/* ---------- Andy Warhol ---------- */
{ id:"campbells-soup-cans", tier:1, title:"Campbell's Soup Cans", artistId:"andy-warhol",
  year:{display:"1962",sort:1962}, movements:["pop-art"], techniques:["silkscreen","flat-color"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:-45,D:-10,E:80,C:90,M:35},
  description:"Thirty-two canvases, one for each variety Campbell's sold at the time, hand-painted rather than printed and shown in a row on shelves like a grocery display. The gallery sold them off individually until a later owner reassembled the set. Warhol's stated reason for the subject was that he had eaten the same lunch for twenty years, which may well be true.",
  notice:["Thirty-two canvases: one per variety then sold",
          "Hand-painted, and displayed on shelves like a shop",
          "He said he had eaten it for lunch for twenty years"], tags:["consumer","repetition","red"] },
{ id:"gold-marilyn-monroe", tier:2, title:"Gold Marilyn Monroe", artistId:"andy-warhol",
  year:{display:"1962",sort:1962}, movements:["pop-art"], techniques:["silkscreen","acrylic-painting"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:-55,D:25,E:75,C:80,M:25}, tags:["portrait","golden","celebrity"] },
{ id:"marilyn-diptych", tier:1, title:"Marilyn Diptych", artistId:"andy-warhol",
  year:{display:"1962",sort:1962}, movements:["pop-art"], techniques:["silkscreen","acrylic-painting"], nation:"usa",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"}, image:{status:"copyright"},
  coords:{F:-35,D:45,E:80,C:85,M:55},
  description:"Fifty identical Marilyns silkscreened from a single 1953 publicity still: twenty-five in colour on the left panel, twenty-five in black and white on the right, smearing and fading across the surface until the last of them are barely there at all. She had died a few weeks before he made it. The repetition is the point, and so is the fading.",
  notice:["Fifty Marilyns from one 1953 publicity photograph",
          "She had died weeks before he made it",
          "The right panel fades until she is barely there"], tags:["portrait","repetition","death"] },
{ id:"129-die-in-jet", tier:2, title:"129 Die in Jet!", artistId:"andy-warhol",
  year:{display:"1962",sort:1962}, movements:["pop-art"], techniques:["silkscreen","acrylic-painting"], nation:"usa",
  museum:{id:"museum-ludwig",name:"Museum Ludwig",city:"Cologne"}, image:{status:"copyright"},
  coords:{F:-40,D:65,E:80,C:95,M:40}, tags:["news","death","unsettling"] },
{ id:"silver-car-crash", tier:2, title:"Silver Car Crash (Double Disaster)", artistId:"andy-warhol",
  year:{display:"1963",sort:1963}, movements:["pop-art"], techniques:["silkscreen","acrylic-painting"], nation:"usa",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:-20,D:80,E:85,C:90,M:80}, tags:["death","repetition","unsettling"] },
{ id:"brillo-box", tier:2, title:"Brillo Box", artistId:"andy-warhol",
  year:{display:"1964",sort:1964}, movements:["pop-art"], techniques:["silkscreen","flat-color"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:-10,D:-20,E:90,C:100,M:20}, tags:["consumer","object","repetition"] },
{ id:"mao-warhol", tier:2, title:"Mao", artistId:"andy-warhol",
  year:{display:"1972",sort:1972}, movements:["pop-art"], techniques:["silkscreen","acrylic-painting"], nation:"usa",
  museum:{id:"art-institute-chicago",name:"The Art Institute of Chicago",city:"Chicago"}, image:{status:"copyright"},
  coords:{F:-45,D:35,E:80,C:95,M:55}, tags:["portrait","political","celebrity"] },
{ id:"self-portrait-fright-wig", tier:2, title:"Self-Portrait (Fright Wig)", artistId:"andy-warhol",
  year:{display:"1986",sort:1986}, movements:["pop-art"], techniques:["silkscreen","acrylic-painting"], nation:"usa",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"}, image:{status:"copyright"},
  coords:{F:-40,D:55,E:75,C:75,M:-25}, tags:["self-portrait","black","death"] }
]);
