/* PIGMENT — copyright-held artwork catalog.
   These canonical records deliberately omit reproductions. Their seeded
   generative covers identify them throughout the atlas without imitating the
   original compositions. Every work remains admirable, saveable and linkable. */
window.CATALOG = (window.CATALOG || []).concat([

/* ---------- Henri Matisse ---------- */
{ id:"woman-with-a-hat", tier:2, title:"Woman with a Hat", artistId:"henri-matisse",
  year:{display:"1905",sort:1905}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"sfmoma",name:"San Francisco Museum of Modern Art",city:"San Francisco"}, image:{status:"copyright"},
  coords:{F:-65,D:40,E:65,C:-60,M:-35}, tags:["portrait","red","experimental"] },
{ id:"the-joy-of-life", tier:2, title:"The Joy of Life", artistId:"henri-matisse",
  year:{display:"1905–06",sort:1905}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"barnes-foundation",name:"Barnes Foundation",city:"Philadelphia"}, image:{status:"copyright"},
  coords:{F:-45,D:5,E:70,C:-80,M:45}, tags:["landscape","nude","would-hang"] },
{ id:"open-window-collioure", tier:2, title:"Open Window, Collioure", artistId:"henri-matisse",
  year:{display:"1905",sort:1905}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"national-gallery-dc",name:"National Gallery of Art",city:"Washington, D.C."}, image:{status:"copyright"},
  coords:{F:-55,D:-25,E:60,C:-75,M:-55}, tags:["interior","landscape","would-hang"] },
{ id:"the-dance-matisse", tier:2, title:"The Dance", artistId:"henri-matisse",
  year:{display:"1910",sort:1910}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"hermitage",name:"The State Hermitage Museum",city:"St Petersburg"}, image:{status:"copyright"},
  coords:{F:-35,D:65,E:70,C:-70,M:70}, tags:["figures","dance","monumental-scale"] },
{ id:"the-red-studio", tier:2, title:"The Red Studio", artistId:"henri-matisse",
  year:{display:"1911",sort:1911}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:15,D:-15,E:75,C:-55,M:20}, tags:["interior","red","experimental"] },
{ id:"goldfish-matisse", tier:2, title:"Goldfish", artistId:"henri-matisse",
  year:{display:"1912",sort:1912}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"pushkin-museum",name:"Pushkin State Museum of Fine Arts",city:"Moscow"}, image:{status:"copyright"},
  coords:{F:-45,D:-55,E:45,C:-70,M:-55}, tags:["interior","quiet","would-hang"] },
{ id:"the-piano-lesson", tier:2, title:"The Piano Lesson", artistId:"henri-matisse",
  year:{display:"1916",sort:1916}, movements:["fauvism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:5,D:-30,E:70,C:-20,M:-35}, tags:["interior","geometric","quiet"] },
{ id:"blue-nude-ii", tier:2, title:"Blue Nude II", artistId:"henri-matisse",
  year:{display:"1952",sort:1952}, movements:["fauvism"], techniques:["collage","flat-color"], nation:"france",
  museum:{id:"centre-pompidou",name:"Centre Pompidou",city:"Paris"}, image:{status:"copyright"},
  coords:{F:10,D:10,E:85,C:-65,M:10}, tags:["nude","blue","cut-paper"] },
{ id:"the-snail", tier:2, title:"The Snail", artistId:"henri-matisse",
  year:{display:"1953",sort:1953}, movements:["fauvism"], techniques:["collage","flat-color"], nation:"france",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"}, image:{status:"copyright"},
  coords:{F:75,D:-10,E:90,C:-35,M:45}, tags:["abstract","pattern","playful"] },

/* ---------- Pablo Picasso ---------- */
{ id:"the-old-guitarist", tier:2, title:"The Old Guitarist", artistId:"pablo-picasso",
  year:{display:"1903–04",sort:1903}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"art-institute-chicago",name:"The Art Institute of Chicago",city:"Chicago"}, image:{status:"copyright"},
  coords:{F:-75,D:55,E:25,C:10,M:-55}, tags:["portrait","blue","lonely"] },
{ id:"family-of-saltimbanques", tier:2, title:"Family of Saltimbanques", artistId:"pablo-picasso",
  year:{display:"1905",sort:1905}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"national-gallery-dc",name:"National Gallery of Art",city:"Washington, D.C."}, image:{status:"copyright"},
  coords:{F:-70,D:15,E:35,C:-20,M:5}, tags:["figures","circus","lonely"] },
{ id:"les-demoiselles-davignon", tier:2, title:"Les Demoiselles d'Avignon", artistId:"pablo-picasso",
  year:{display:"1907",sort:1907}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:-25,D:75,E:95,C:20,M:55}, tags:["nude","unsettling","experimental"] },
{ id:"ma-jolie", tier:2, title:"Ma Jolie", artistId:"pablo-picasso",
  year:{display:"1911–12",sort:1911}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:65,D:10,E:90,C:30,M:-10}, tags:["portrait","geometric","pattern"] },
{ id:"still-life-chair-caning", tier:2, title:"Still Life with Chair Caning", artistId:"pablo-picasso",
  year:{display:"1912",sort:1912}, movements:["cubism"], techniques:["collage","oil-painting"], nation:"spain",
  museum:{id:"musee-picasso-paris",name:"Musée Picasso",city:"Paris"}, image:{status:"copyright"},
  coords:{F:55,D:-5,E:95,C:60,M:-35}, tags:["still-life","collage","experimental"] },
{ id:"three-musicians", tier:2, title:"Three Musicians", artistId:"pablo-picasso",
  year:{display:"1921",sort:1921}, movements:["cubism"], techniques:["oil-painting","collage"], nation:"spain",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:25,D:20,E:75,C:-15,M:35}, tags:["figures","music","geometric"] },
{ id:"girl-before-a-mirror", tier:2, title:"Girl before a Mirror", artistId:"pablo-picasso",
  year:{display:"1932",sort:1932}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:-10,D:45,E:75,C:-40,M:15}, tags:["portrait","mirror","pattern"] },
{ id:"guernica", tier:2, title:"Guernica", artistId:"pablo-picasso",
  year:{display:"1937",sort:1937}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"reina-sofia",name:"Museo Reina Sofía",city:"Madrid"}, image:{status:"copyright"},
  coords:{F:-30,D:100,E:85,C:65,M:95}, tags:["historical","war","monumental-scale"] },
{ id:"the-weeping-woman", tier:2, title:"The Weeping Woman", artistId:"pablo-picasso",
  year:{display:"1937",sort:1937}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"}, image:{status:"copyright"},
  coords:{F:-30,D:90,E:80,C:20,M:-25}, tags:["portrait","unsettling","grief"] },
{ id:"las-meninas-picasso", tier:2, title:"Las Meninas (series)", artistId:"pablo-picasso",
  year:{display:"1957",sort:1957}, movements:["cubism"], techniques:["oil-painting"], nation:"spain",
  museum:{id:"museu-picasso-barcelona",name:"Museu Picasso",city:"Barcelona"}, image:{status:"copyright"},
  coords:{F:10,D:45,E:80,C:45,M:55}, tags:["interior","historical","series"] },

/* ---------- Salvador Dalí ---------- */
{ id:"the-great-masturbator", tier:2, title:"The Great Masturbator", artistId:"salvador-dali",
  year:{display:"1929",sort:1929}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"reina-sofia",name:"Museo Reina Sofía",city:"Madrid"}, image:{status:"copyright"},
  coords:{F:-40,D:65,E:70,C:40,M:-25}, tags:["dream","unsettling","desire"] },
{ id:"the-persistence-of-memory", tier:2, title:"The Persistence of Memory", artistId:"salvador-dali",
  year:{display:"1931",sort:1931}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:-45,D:45,E:75,C:45,M:-45}, tags:["dream","landscape","time"] },
{ id:"swans-reflecting-elephants", tier:2, title:"Swans Reflecting Elephants", artistId:"salvador-dali",
  year:{display:"1937",sort:1937}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:-50,D:25,E:70,C:35,M:-20}, tags:["dream","reflection","double-image"] },
{ id:"metamorphosis-of-narcissus", tier:2, title:"Metamorphosis of Narcissus", artistId:"salvador-dali",
  year:{display:"1937",sort:1937}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"}, image:{status:"copyright"},
  coords:{F:-45,D:35,E:75,C:50,M:0}, tags:["myth","double-image","dream"] },
{ id:"dream-flight-bee", tier:2, title:"Dream Caused by the Flight of a Bee", artistId:"salvador-dali",
  year:{display:"1944",sort:1944}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"thyssen-bornemisza",name:"Museo Nacional Thyssen-Bornemisza",city:"Madrid"}, image:{status:"copyright"},
  coords:{F:-55,D:70,E:65,C:10,M:5}, tags:["dream","tiger","unsettling"] },
{ id:"christ-saint-john-cross", tier:2, title:"Christ of Saint John of the Cross", artistId:"salvador-dali",
  year:{display:"1951",sort:1951}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"kelvingrove",name:"Kelvingrove Art Gallery and Museum",city:"Glasgow"}, image:{status:"copyright"},
  coords:{F:-75,D:70,E:15,C:15,M:75}, tags:["biblical","spiritual","monumental-scale"] },
{ id:"sacrament-last-supper", tier:2, title:"The Sacrament of the Last Supper", artistId:"salvador-dali",
  year:{display:"1955",sort:1955}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"national-gallery-dc",name:"National Gallery of Art",city:"Washington, D.C."}, image:{status:"copyright"},
  coords:{F:-60,D:30,E:20,C:25,M:80}, tags:["biblical","geometric","spiritual"] },
{ id:"hallucinogenic-toreador", tier:2, title:"The Hallucinogenic Toreador", artistId:"salvador-dali",
  year:{display:"1969–70",sort:1969}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  museum:{id:"dali-museum-florida",name:"The Dalí Museum",city:"St Petersburg"}, image:{status:"copyright"},
  coords:{F:-15,D:70,E:70,C:55,M:90}, tags:["double-image","bullfight","monumental-scale"] },

/* ---------- Frida Kahlo ---------- */
{ id:"self-portrait-velvet-dress", tier:2, title:"Self-Portrait in a Velvet Dress", artistId:"frida-kahlo",
  year:{display:"1926",sort:1926}, movements:["naive-art","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:-90,D:20,E:25,C:-20,M:-65}, tags:["portrait","tender","intimate"] },
{ id:"henry-ford-hospital", tier:2, title:"Henry Ford Hospital", artistId:"frida-kahlo",
  year:{display:"1932",sort:1932}, movements:["surrealism","naive-art"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"museo-dolores-olmedo",name:"Museo Dolores Olmedo",city:"Mexico City"}, image:{status:"copyright"},
  coords:{F:-80,D:85,E:55,C:55,M:-80}, tags:["body","grief","unsettling"] },
{ id:"my-birth-kahlo", tier:2, title:"My Birth", artistId:"frida-kahlo",
  year:{display:"1932",sort:1932}, movements:["surrealism","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:-75,D:95,E:60,C:55,M:-75}, tags:["body","birth","unsettling"] },
{ id:"the-two-fridas", tier:2, title:"The Two Fridas", artistId:"frida-kahlo",
  year:{display:"1939",sort:1939}, movements:["surrealism","naive-art","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"museo-arte-moderno-mexico",name:"Museo de Arte Moderno",city:"Mexico City"}, image:{status:"copyright"},
  coords:{F:-80,D:75,E:55,C:45,M:20}, tags:["self-portrait","double","grief"] },
{ id:"thorn-necklace-hummingbird", tier:2, title:"Self-Portrait with Thorn Necklace and Hummingbird", artistId:"frida-kahlo",
  year:{display:"1940",sort:1940}, movements:["surrealism","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"harry-ransom-center",name:"Harry Ransom Center",city:"Austin"}, image:{status:"copyright"},
  coords:{F:-90,D:60,E:45,C:35,M:-70}, tags:["self-portrait","animals","unsettling"] },
{ id:"the-broken-column", tier:2, title:"The Broken Column", artistId:"frida-kahlo",
  year:{display:"1944",sort:1944}, movements:["surrealism","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"museo-dolores-olmedo",name:"Museo Dolores Olmedo",city:"Mexico City"}, image:{status:"copyright"},
  coords:{F:-85,D:95,E:50,C:45,M:-55}, tags:["self-portrait","body","pain"] },
{ id:"the-wounded-deer", tier:2, title:"The Wounded Deer", artistId:"frida-kahlo",
  year:{display:"1946",sort:1946}, movements:["surrealism","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:-65,D:80,E:55,C:35,M:-45}, tags:["self-portrait","animal","wound"] },
{ id:"diego-and-i", tier:2, title:"Diego and I", artistId:"frida-kahlo",
  year:{display:"1949",sort:1949}, movements:["surrealism","symbolism"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:-90,D:75,E:45,C:40,M:-85}, tags:["self-portrait","grief","intimate"] },
{ id:"marxism-health-sick", tier:2, title:"Marxism Will Give Health to the Sick", artistId:"frida-kahlo",
  year:{display:"1954",sort:1954}, movements:["symbolism","naive-art"], techniques:["oil-painting"], nation:"mexico",
  museum:{id:"museo-frida-kahlo",name:"Museo Frida Kahlo",city:"Mexico City"}, image:{status:"copyright"},
  coords:{F:-55,D:70,E:65,C:75,M:5}, tags:["self-portrait","political","body"] },

/* ---------- Jackson Pollock ---------- */
{ id:"mural-pollock", tier:2, title:"Mural", artistId:"jackson-pollock",
  year:{display:"1943",sort:1943}, movements:["abstract-expressionism","action-painting"], techniques:["oil-painting","gestural-abstraction"], nation:"usa",
  museum:{id:"stanley-museum-iowa",name:"Stanley Museum of Art",city:"Iowa City"}, image:{status:"copyright"},
  coords:{F:70,D:85,E:75,C:0,M:90}, tags:["abstract","rhythm","monumental-scale"] },
{ id:"full-fathom-five", tier:2, title:"Full Fathom Five", artistId:"jackson-pollock",
  year:{display:"1947",sort:1947}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:90,D:80,E:90,C:5,M:55}, tags:["abstract","drip","dense"] },
{ id:"cathedral-pollock", tier:2, title:"Cathedral", artistId:"jackson-pollock",
  year:{display:"1947",sort:1947}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"dallas-museum-art",name:"Dallas Museum of Art",city:"Dallas"}, image:{status:"copyright"},
  coords:{F:90,D:80,E:90,C:5,M:60}, tags:["abstract","drip","black"] },
{ id:"number-5-1948", tier:2, title:"No. 5, 1948", artistId:"jackson-pollock",
  year:{display:"1948",sort:1948}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:95,D:85,E:90,C:10,M:55}, tags:["abstract","drip","dense"] },
{ id:"number-1a-1948", tier:2, title:"Number 1A, 1948", artistId:"jackson-pollock",
  year:{display:"1948",sort:1948}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:90,D:90,E:90,C:5,M:65}, tags:["abstract","drip","handprint"] },
{ id:"autumn-rhythm", tier:2, title:"Autumn Rhythm (Number 30)", artistId:"jackson-pollock",
  year:{display:"1950",sort:1950}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"met",name:"The Metropolitan Museum of Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:95,D:80,E:90,C:0,M:90}, tags:["abstract","drip","monumental-scale"] },
{ id:"convergence-pollock", tier:2, title:"Convergence", artistId:"jackson-pollock",
  year:{display:"1952",sort:1952}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"buffalo-akg",name:"Buffalo AKG Art Museum",city:"Buffalo"}, image:{status:"copyright"},
  coords:{F:90,D:95,E:90,C:5,M:85}, tags:["abstract","drip","color"] },
{ id:"blue-poles", tier:2, title:"Blue Poles", artistId:"jackson-pollock",
  year:{display:"1952",sort:1952}, movements:["abstract-expressionism","action-painting"], techniques:["dripping","gestural-abstraction"], nation:"usa",
  museum:{id:"national-gallery-australia",name:"National Gallery of Australia",city:"Canberra"}, image:{status:"copyright"},
  coords:{F:85,D:90,E:85,C:5,M:90}, tags:["abstract","blue","monumental-scale"] },

/* ---------- Mark Rothko ---------- */
{ id:"slow-swirl-edge-sea", tier:2, title:"Slow Swirl at the Edge of the Sea", artistId:"mark-rothko",
  year:{display:"1944",sort:1944}, movements:["abstract-expressionism"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:30,D:-5,E:55,C:10,M:5}, tags:["myth","figures","dream"] },
{ id:"no-61-rust-blue", tier:2, title:"No. 61 (Rust and Blue)", artistId:"mark-rothko",
  year:{display:"1953",sort:1953}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"moca-la",name:"Museum of Contemporary Art",city:"Los Angeles"}, image:{status:"copyright"},
  coords:{F:95,D:20,E:60,C:-5,M:65}, tags:["abstract","blue","meditative"] },
{ id:"no-14-rothko", tier:2, title:"No. 14", artistId:"mark-rothko",
  year:{display:"1960",sort:1960}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"sfmoma",name:"San Francisco Museum of Modern Art",city:"San Francisco"}, image:{status:"copyright"},
  coords:{F:95,D:15,E:60,C:-10,M:70}, tags:["abstract","orange","meditative"] },
{ id:"orange-and-yellow", tier:2, title:"Orange and Yellow", artistId:"mark-rothko",
  year:{display:"1956",sort:1956}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"buffalo-akg",name:"Buffalo AKG Art Museum",city:"Buffalo"}, image:{status:"copyright"},
  coords:{F:95,D:-15,E:55,C:-25,M:70}, tags:["abstract","golden","meditative"] },
{ id:"four-darks-in-red", tier:2, title:"Four Darks in Red", artistId:"mark-rothko",
  year:{display:"1958",sort:1958}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"whitney",name:"Whitney Museum of American Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:95,D:45,E:55,C:0,M:75}, tags:["abstract","red","unsettling"] },
{ id:"seagram-murals", tier:2, title:"The Seagram Murals", artistId:"mark-rothko",
  year:{display:"1958–59",sort:1958}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"}, image:{status:"copyright"},
  coords:{F:95,D:60,E:60,C:10,M:90}, tags:["abstract","red","monumental-scale"] },
{ id:"rothko-chapel-paintings", tier:2, title:"Rothko Chapel paintings", artistId:"mark-rothko",
  year:{display:"1964–67",sort:1964}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"rothko-chapel",name:"Rothko Chapel",city:"Houston"}, image:{status:"copyright"},
  coords:{F:98,D:60,E:55,C:5,M:100}, tags:["abstract","spiritual","monumental-scale"] },
{ id:"untitled-black-gray", tier:2, title:"Untitled (Black on Gray)", artistId:"mark-rothko",
  year:{display:"1969–70",sort:1969}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","glazing"], nation:"usa",
  museum:{id:"guggenheim-ny",name:"Solomon R. Guggenheim Museum",city:"New York"}, image:{status:"copyright"},
  coords:{F:98,D:65,E:55,C:5,M:65}, tags:["abstract","black","unsettling"] },

/* ---------- Andy Warhol ---------- */
{ id:"campbells-soup-cans", tier:2, title:"Campbell's Soup Cans", artistId:"andy-warhol",
  year:{display:"1962",sort:1962}, movements:["pop-art"], techniques:["silkscreen","flat-color"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:-45,D:-10,E:80,C:90,M:35}, tags:["consumer","repetition","red"] },
{ id:"gold-marilyn-monroe", tier:2, title:"Gold Marilyn Monroe", artistId:"andy-warhol",
  year:{display:"1962",sort:1962}, movements:["pop-art"], techniques:["silkscreen","acrylic-painting"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:-55,D:25,E:75,C:80,M:25}, tags:["portrait","golden","celebrity"] },
{ id:"marilyn-diptych", tier:2, title:"Marilyn Diptych", artistId:"andy-warhol",
  year:{display:"1962",sort:1962}, movements:["pop-art"], techniques:["silkscreen","acrylic-painting"], nation:"usa",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"}, image:{status:"copyright"},
  coords:{F:-35,D:45,E:80,C:85,M:55}, tags:["portrait","repetition","death"] },
{ id:"129-die-in-jet", tier:2, title:"129 Die in Jet!", artistId:"andy-warhol",
  year:{display:"1962",sort:1962}, movements:["pop-art"], techniques:["silkscreen","acrylic-painting"], nation:"usa",
  museum:{id:"museum-ludwig",name:"Museum Ludwig",city:"Cologne"}, image:{status:"copyright"},
  coords:{F:-40,D:65,E:80,C:95,M:40}, tags:["news","death","unsettling"] },
{ id:"silver-car-crash", tier:2, title:"Silver Car Crash (Double Disaster)", artistId:"andy-warhol",
  year:{display:"1963",sort:1963}, movements:["pop-art"], techniques:["silkscreen","acrylic-painting"], nation:"usa",
  museum:{id:"private-collection",name:"Private collection",city:null}, image:{status:"copyright"},
  coords:{F:-20,D:80,E:85,C:90,M:80}, tags:["death","repetition","unsettling"] },
{ id:"brillo-box", tier:2, title:"Brillo Box", artistId:"andy-warhol",
  year:{display:"1964",sort:1964}, movements:["pop-art"], techniques:["silkscreen","flat-color"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"}, image:{status:"copyright"},
  coords:{F:-10,D:-20,E:90,C:100,M:20}, tags:["consumer","object","repetition"] },
{ id:"mao-warhol", tier:2, title:"Mao", artistId:"andy-warhol",
  year:{display:"1972",sort:1972}, movements:["pop-art"], techniques:["silkscreen","acrylic-painting"], nation:"usa",
  museum:{id:"art-institute-chicago",name:"The Art Institute of Chicago",city:"Chicago"}, image:{status:"copyright"},
  coords:{F:-45,D:35,E:80,C:95,M:55}, tags:["portrait","political","celebrity"] },
{ id:"self-portrait-fright-wig", tier:2, title:"Self-Portrait (Fright Wig)", artistId:"andy-warhol",
  year:{display:"1986",sort:1986}, movements:["pop-art"], techniques:["silkscreen","acrylic-painting"], nation:"usa",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"}, image:{status:"copyright"},
  coords:{F:-40,D:55,E:75,C:75,M:-25}, tags:["self-portrait","black","death"] }
]);
