/* PIGMENT — artwork catalog 5 (ARTWORK_SCHEMA v1).
   The twenty-two records specified in docs/CATALOG_BATCH_01.md (10, one artwork per
   zero-artwork nation) and docs/CATALOG_BATCH_02.md (12, ranked by consequence),
   with the `description` and `notice` copy from docs/CATALOG_BATCH_COPY.md.

   All 22 are Tier 2. Each carries hand-scored coords (coordsSource:"override"),
   a description and exactly 3 notice bullets, so each meets §4's FIELD
   requirements for Tier 1 — they are held at Tier 2 by §8's inbound-link rule
   alone, which is the Curator's call. Promotion is purely additive and the URL
   never changes.

   `image.status:"pd"` is a rendering token, not a legal finding (§3, OD-5): it
   records that a Commons file page asserts a public-domain basis. Every dims
   string here was sanity-checked by the specification; a-burial-at-ornans is
   CONVERTED FROM METRES (Wikidata unit Q11573) — see ARTWORK_SCHEMA §7.1 rule 1,
   the unit bug this batch found. red-and-white-plum-blossoms carries the word
   "each" that Wikidata's own figure does not (§7.1 rule 3). */
window.CATALOG = (window.CATALOG || []).concat([

{ id:"the-tortoise-trainer", tier:2,
  title:"The Tortoise Trainer",
  artistId:"osman-hamdi-bey", year:{ display:"1906", sort:1906 },
  movements:["realism"], techniques:["oil-painting"], nation:"turkey",
  museum:{ id:"pera-museum", name:"Pera Museum", city:"Istanbul" },
  dims:"221.5 × 120 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Osman_Hamdi_Bey_-_The_Tortoise_Trainer_-_Google_Art_Project.jpg/500px-Osman_Hamdi_Bey_-_The_Tortoise_Trainer_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/The_Tortoise_Trainer", status:"pd" },
  coords:{ F:-85, D:-40, E:-25, C:45, M:10 }, coordsSource:"override",
  description:"A man in Ottoman dress stands stooped over his tortoises, a naqareh drum slung on his back, waiting for them to learn something. They do not hurry. Nothing in the picture moves at all. Osman Hamdi Bey built it to be read rather than felt, and gave two and a quarter metres of canvas to the slowest lesson in the room.",
  notice:["The drum on his back is a naqareh",
          "Nothing in this picture is in a hurry",
          "That the trainer wears the painter's own face — widely repeated, unestablished"],
  tags:["interior","quiet","monumental-scale"] },

{ id:"stanczyk", tier:2,
  title:"Stańczyk",
  artistId:"jan-matejko", year:{ display:"1862", sort:1862 },
  movements:["romanticism"], techniques:["oil-painting"], nation:"poland",
  museum:{ id:"national-museum-warsaw", name:"National Museum in Warsaw", city:"Warsaw" },
  dims:"88 × 120 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Jan_Matejko%2C_Sta%C5%84czyk.jpg/500px-Jan_Matejko%2C_Sta%C5%84czyk.jpg",
          page:"https://en.wikipedia.org/wiki/Sta%C5%84czyk_(painting)", status:"pd" },
  coords:{ F:-85, D:35, E:-60, C:40, M:-15 }, coordsSource:"override",
  description:"A court ball is going on through the doorway behind him, bright and busy. The jester sits apart in red, out of the light, and does not perform. He has read the dispatch; the dancers have not. Matejko painted it in 1862 in entirely conventional means, and gave the loudest man at court the only silence in the room.",
  notice:["The ball is bright; his corner is not",
          "In costume, and the only figure not performing",
          "He has read the dispatch; the dancers haven't"],
  tags:["historical","interior","lonely","red"] },

{ id:"senecio", tier:2,
  title:"Senecio",
  artistId:"paul-klee", year:{ display:"1922", sort:1922 },
  movements:["expressionism","abstract-art"], techniques:["oil-painting"], nation:"switzerland",
  museum:{ id:"kunstmuseum-basel", name:"Kunstmuseum Basel", city:"Basel" },
  dims:"40.3 × 37.4 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Paul_Klee%2C_1922%2C_Senecio%2C_oil_on_gauze%2C_40.3_%C3%97_37.4_cm%2C_Kunstmuseum_Basel.jpg/500px-Paul_Klee%2C_1922%2C_Senecio%2C_oil_on_gauze%2C_40.3_%C3%97_37.4_cm%2C_Kunstmuseum_Basel.jpg",
          page:"https://en.wikipedia.org/wiki/Senecio_(Klee)", status:"pd" },
  coords:{ F:35, D:-20, E:65, C:15, M:-70 }, coordsSource:"override",
  description:"A head, still legible as a head, assembled out of squares and wedges the way a bricklayer would build one. The gaze is level and it holds. Klee was teaching at the Bauhaus in 1922, laying colour down as a system rather than as a description — and the system came out amused. Forty centimetres square. You could carry it under one arm.",
  notice:["A head built from squares and wedges",
          "The gaze is level, and it holds yours",
          "Oil on gauze, or oil and canvas — sources disagree"],
  tags:["portrait","geometry","flatness","playful"] },

{ id:"sunlight-in-the-blue-room", tier:2,
  title:"Sunlight in the Blue Room",
  artistId:"anna-ancher", year:{ display:"1891", sort:1891 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"denmark",
  museum:{ id:"skagens-museum", name:"Skagens Museum", city:"Skagen" },
  dims:"65.2 × 58.8 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Anna_Ancher_-_Sunlight_in_the_blue_room_-_Google_Art_Project.jpg/500px-Anna_Ancher_-_Sunlight_in_the_blue_room_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Sunlight_in_the_Blue_Room", status:"pd" },
  coords:{ F:-80, D:-70, E:-10, C:-45, M:-60 }, coordsSource:"override",
  description:"A child sits in a blue room, and the event of the picture is sunlight arriving on the wall behind her. That is the whole plot. Ancher painted it in 1891 at sixty-five centimetres — a corner of a house rather than a scene — and gave the light more attention than the sitter, which is why your eye goes to the wall first.",
  notice:["The wall holds the light; the child holds still",
          "Blue throughout, warmed only where the sun lands",
          "Sixty-five centimetres: a corner, not a scene"],
  tags:["interior","quiet","everyday-life","blue"] },

{ id:"three-girls", tier:2,
  title:"Three Girls", worksKey:"Three Girls",
  artistId:"amrita-sher-gil", year:{ display:"1935", sort:1935 },
  movements:["post-impressionism"], techniques:["oil-painting"], nation:"india",
  museum:{ id:"ngma-new-delhi", name:"National Gallery of Modern Art", city:"New Delhi" },
  dims:"99.5 × 73.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Amrita_Sher-Gil_Group_of_Three_Girls.jpg/500px-Amrita_Sher-Gil_Group_of_Three_Girls.jpg",
          page:"https://en.wikipedia.org/wiki/Three_Girls_(painting)", status:"pd" },
  coords:{ F:-85, D:-50, E:10, C:-20, M:-35 }, coordsSource:"override",
  description:"Three young women sit close together and not one of them looks at another, or at you. Nothing happens. Sher-Gil trained in Paris and turned that training on an Indian subject — modern in its colour and its flattening, conventional in every other means — so the picture works by mood instead of by argument. A metre of canvas, three figures, no story offered.",
  notice:["Nobody meets anybody's eye, including yours",
          "Modern in colour and flattening, conventional in means",
          "Reportedly won a gold medal from the Bombay Art Society"],
  tags:["group-scene","quiet","everyday-life"] },

{ id:"the-artist-and-his-mother", tier:2,
  title:"The Artist and His Mother",
  artistId:"arshile-gorky", year:{ display:"c. 1926–1936", sort:1926 },
  movements:["modernism"], techniques:["oil-painting"], nation:"armenia",
  museum:{ id:"whitney", name:"Whitney Museum of American Art", city:"New York" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Arshile_Gorky%2C_The_Artist_and_His_Mother.jpg/960px-Arshile_Gorky%2C_The_Artist_and_His_Mother.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Arshile_Gorky,_The_Artist_and_His_Mother.jpg", status:"pd" },
  coords:{ F:-45, D:-25, E:45, C:25, M:-5 }, coordsSource:"override",
  description:"Gorky worked from a childhood photograph taken in Van: himself as a boy, standing beside his mother. In the aftermath of the genocide she died of starvation in Yerevan, in 1919. He painted this over roughly a decade and never called it finished. The surfaces are scraped back and laid again, the faces pressed towards outline and plane. Two versions exist. This is the one at the Whitney.",
  notice:["Painted from a childhood photograph taken in Van",
          "Scraped back and repainted for a decade, never finished",
          "A second version is in Washington"],
  tags:["portrait","mourning","flatness"] },

{ id:"lemminkainens-mother", tier:2,
  title:"Lemminkäinen's Mother",
  artistId:"akseli-gallen-kallela", year:{ display:"1897", sort:1897 },
  movements:["symbolism"], techniques:["tempera"], nation:"finland",
  museum:{ id:"ateneum", name:"Ateneum Art Museum", city:"Helsinki" },
  dims:"85.5 × 108.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Gallen_Kallela_Lemminkainens_Mother.jpg/500px-Gallen_Kallela_Lemminkainens_Mother.jpg",
          page:"https://en.wikipedia.org/wiki/Lemmink%C3%A4inen's_Mother", status:"pd" },
  coords:{ F:-80, D:45, E:20, C:10, M:25 }, coordsSource:"override",
  description:"A mother kneels on the bank of the river of the dead and puts her dismembered son back together. Gallen-Kallela painted it in 1897 in tempera rather than salon oil — flattened, hard-edged, bounded like decoration — so that a scene of that kind holds absolutely still. The stillness is not calm. Nothing in the picture moves and everything in it is at pitch.",
  notice:["Tempera, not oil — a refusal of salon finish",
          "The body is being assembled, not mourned",
          "Motionless, and not remotely calm"],
  tags:["mythological","mourning","nude","golden"] },

{ id:"the-lovers-abbasi", tier:2,
  title:"The Lovers", worksKey:"Two Lovers",
  artistId:"reza-abbasi", year:{ display:"1630", sort:1630 },
  movements:["persian-miniature"], techniques:["miniature-painting"], nation:"iran",
  museum:{ id:"met", name:"The Metropolitan Museum of Art", city:"New York" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Reza_Abbasi_-_Two_Lovers_%281630%29.jpg/500px-Reza_Abbasi_-_Two_Lovers_%281630%29.jpg",
          page:"https://en.wikipedia.org/wiki/The_Lovers_(Abbasi)", status:"pd" },
  coords:{ F:-70, D:-55, E:-55, C:-65, M:-80 }, coordsSource:"override",
  description:"Two figures fold into one another on a page you could hold in one hand. Nothing happens but the touching — no depth, no room, no story arriving. Reza Abbasi worked inside Safavid album convention at the height of it, and the whole picture is about how a sleeve sits against a shoulder. The sheet carries its own date: 8 Shawwal 1039, which is 21 May 1630.",
  notice:["The sheet is dated 8 Shawwal 1039 — 21 May 1630",
          "No depth is attempted; the idiom never wanted it",
          "The real subject is the fall of cloth"],
  tags:["tender","pattern","miniature-scale","golden"] },

{ id:"birds-in-a-lotus-pond", tier:2,
  title:"Birds in a Lotus Pond", worksKey:"Lotus and Birds",
  artistId:"bada-shanren", year:{ display:"1690", sort:1690 },
  movements:["literati-painting"], techniques:["ink-wash"], nation:"china",
  museum:{ id:"met", name:"The Metropolitan Museum of Art", city:"New York" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Bada_Shanren_%28Zhu_Da%29_-_Birds_in_a_lotus_pond_-_1989.363.135_-_Metropolitan_Museum_of_Art.jpg/960px-Bada_Shanren_%28Zhu_Da%29_-_Birds_in_a_lotus_pond_-_1989.363.135_-_Metropolitan_Museum_of_Art.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Bada_Shanren_(Zhu_Da)_-_Birds_in_a_lotus_pond_-_1989.363.135_-_Metropolitan_Museum_of_Art.jpg", status:"pd" },
  coords:{ F:-35, D:-30, E:30, C:5, M:-45 }, coordsSource:"override",
  description:"One perched bird, made of two strokes and a dot for an eye, on a great deal of empty paper. Bada Shanren painted inside the literati tradition and at its far edge — the reduction was his, not the convention's. The mood is not serene. It is sour, and the bird looks as though it has formed an opinion about you.",
  notice:["The eye is a single dot, and it judges",
          "Most of the sheet is left as paper",
          "The 1690 date rests on one source"],
  tags:["animal","quiet","monochrome","gesture"] },

{ id:"ssireum", tier:2,
  title:"Ssireum", worksKey:"Ssireum (Wrestling)",
  artistId:"kim-hong-do", year:{ display:"18th century", sort:1780 },
  movements:["pungsokhwa"], techniques:["ink-wash","watercolor"], nation:"korea",
  museum:{ id:"national-museum-korea", name:"National Museum of Korea", city:"Seoul" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Danwon_Ssireum.jpg/960px-Danwon_Ssireum.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Danwon_Ssireum.jpg", status:"pd" },
  coords:{ F:-85, D:20, E:-30, C:-40, M:-70 }, coordsSource:"override",
  description:"Two wrestlers at the moment the contest tips, and a ring of spectators around them, every one of them a separate person. There is no ground and no background — just figures on empty paper. It is played for comedy rather than violence. One leaf out of an album of 25. Nobody knows the year: no date survives on the record, and the album is placed in the 18th century.",
  notice:["No ground, no background — figures on bare paper",
          "One leaf from an album of 25",
          "The date is unknown; the century is a placing"],
  tags:["group-scene","everyday-life","playful"] },

{ id:"ognissanti-madonna", tier:2,
  title:"Ognissanti Madonna", worksKey:"Ognissanti Madonna",
  artistId:"giotto", year:{ display:"c. 1300–1305", sort:1300 },
  movements:["proto-renaissance"], techniques:["tempera","gold-leaf"], nation:"italy",
  museum:{ id:"uffizi", name:"Gallerie degli Uffizi", city:"Florence" },
  dims:"325 × 204 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Giotto%2C_1267_Around-1337_-_Maest%C3%A0_-_Google_Art_Project.jpg/500px-Giotto%2C_1267_Around-1337_-_Maest%C3%A0_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Ognissanti_Madonna", status:"pd" },
  coords:{ F:-75, D:-55, E:35, C:-25, M:75 }, coordsSource:"override",
  description:"Gold ground, angels ranked by importance, everything the convention asked for — and then a knee pushes out under the drapery and the whole thing changes. Giotto kept the hierarchy of a Byzantine Maestà and threw the flatness away. The throne is built in depth. The body has weight. Three and a quarter metres of panel, made to be met across a church.",
  notice:["A knee carries real weight under the drapery",
          "The throne is built in depth, not stacked",
          "Gold ground kept; the flatness thrown out"],
  tags:["sacred","group-scene","golden","monumental-scale"] },

{ id:"the-holy-trinity-masaccio", tier:2,
  title:"The Holy Trinity",
  artistId:"masaccio", year:{ display:"1425–1426", sort:1425 },
  movements:["early-renaissance"], techniques:["fresco"], nation:"italy",
  museum:{ id:"santa-maria-novella", name:"Santa Maria Novella", city:"Florence" },
  dims:"667 × 317 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Masaccio%2C_trinit%C3%A0.jpg/500px-Masaccio%2C_trinit%C3%A0.jpg",
          page:"https://en.wikipedia.org/wiki/Holy_Trinity_(Masaccio)", status:"pd" },
  coords:{ F:-80, D:-40, E:55, C:30, M:80 }, coordsSource:"override",
  description:"The architecture behind the figures is built in one-point perspective, and the vanishing point sits at the eye level of someone standing in the church — so the painted space is not a backdrop, it is the room you are in. A painted tomb and its inscription run beneath. Masaccio put this on a wall around 1425, and afterwards the tradition had to use it or refuse it.",
  notice:["The vanishing point sits at your standing eye level",
          "A painted tomb and inscription run beneath",
          "This is a wall, not a panel"],
  tags:["sacred","group-scene","geometry","monumental-scale"] },

{ id:"the-descent-from-the-cross-van-der-weyden", tier:2,
  title:"The Descent from the Cross",
  artistId:"rogier-van-der-weyden", year:{ display:"c. 1435–1438", sort:1435 },
  movements:["early-netherlandish"], techniques:["oil-painting"], nation:"belgium",
  museum:{ id:"prado", name:"Museo del Prado", city:"Madrid" },
  dims:"204.5 × 261.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/El_Descendimiento%2C_by_Rogier_van_der_Weyden%2C_from_Prado_in_Google_Earth.jpg/960px-El_Descendimiento%2C_by_Rogier_van_der_Weyden%2C_from_Prado_in_Google_Earth.jpg",
          page:"https://commons.wikimedia.org/wiki/File:El_Descendimiento,_by_Rogier_van_der_Weyden,_from_Prado_in_Google_Earth.jpg", status:"pd" },
  coords:{ F:-85, D:55, E:-10, C:-30, M:45 }, coordsSource:"override",
  description:"Ten figures at life size, packed into a box barely deeper than a carved shrine — there is nowhere for any of them to go. The Virgin has collapsed, and her body is drawn as a near-exact rhyme of her son's: same curve, same fall, one directly above the other. That is the invention. The grief is not performed by the faces; it is built into the composition.",
  notice:["The Virgin's body rhymes with Christ's, curve for curve",
          "Ten life-size figures in a shrine-shallow box",
          "Grief at full pitch, and nothing is moving"],
  tags:["sacred","group-scene","mourning","theatrical"] },

{ id:"the-tempest", tier:2,
  title:"The Tempest",
  artistId:"giorgione", year:{ display:"c. 1505", sort:1505 },
  movements:["venetian-school"], techniques:["oil-painting"], nation:"italy",
  museum:{ id:"accademia-venice", name:"Gallerie dell'Accademia", city:"Venice" },
  dims:"82 × 73 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Giorgione_-_Das_Gewitter.jpg/500px-Giorgione_-_Das_Gewitter.jpg",
          page:"https://en.wikipedia.org/wiki/The_Tempest_(Giorgione)", status:"pd" },
  coords:{ F:-70, D:30, E:25, C:10, M:-30 }, coordsSource:"override",
  description:"A man stands on one bank, a woman nurses a child on the other, lightning goes off behind them, and neither reacts. No figure carries an attribute that would identify it; no action connects the two. The readings proposed for the subject are numerous and mutually exclusive, and none has settled. Meanwhile the landscape takes most of the picture and carries all its weather.",
  notice:["Lightning behind them, and nobody reacts",
          "No attribute identifies anyone in the picture",
          "The proposed readings are many, and mutually exclusive"],
  tags:["landscape","storm","unsettling","nude"] },

{ id:"venus-of-urbino", tier:2,
  title:"Venus of Urbino",
  artistId:"titian", year:{ display:"1538", sort:1538 },
  movements:["venetian-school"], techniques:["oil-painting"], nation:"italy",
  museum:{ id:"uffizi", name:"Gallerie degli Uffizi", city:"Florence" },
  dims:"119 × 165.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Tiziano_-_Venere_di_Urbino_-_Google_Art_Project.jpg/500px-Tiziano_-_Venere_di_Urbino_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Venus_of_Urbino", status:"pd" },
  coords:{ F:-85, D:-25, E:-20, C:-35, M:-5 }, coordsSource:"override",
  description:"A woman on a bed in an ordinary sixteenth-century bedroom, looking at you, and looking as though she has been for some time. Two maids at a chest in the background, a dog asleep, white linen and fur. Nothing here is mythological except the word Venus in the title. The reclining nude that Western painting used for the next three hundred years starts about here.",
  notice:["She met your eye before you arrived",
          "The only mythology is in the title",
          "Two maids at a chest; a dog asleep"],
  tags:["nude","interior","tender","everyday-life"] },

{ id:"lamentation-of-christ-mantegna", tier:2,
  title:"Lamentation of Christ", worksKey:"Lamentation of Christ",
  artistId:"andrea-mantegna", year:{ display:"c. 1470–1474", sort:1470 },
  movements:["early-renaissance"], techniques:["tempera"], nation:"italy",
  museum:{ id:"brera", name:"Pinacoteca di Brera", city:"Milan" },
  dims:"68 × 81 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/The_dead_Christ_and_three_mourners%2C_by_Andrea_Mantegna.jpg/500px-The_dead_Christ_and_three_mourners%2C_by_Andrea_Mantegna.jpg",
          page:"https://en.wikipedia.org/wiki/Lamentation_of_Christ_(Mantegna)", status:"pd" },
  coords:{ F:-80, D:25, E:60, C:25, M:-10 }, coordsSource:"override",
  description:"The body is laid out feet-first, straight at you, in the hardest thing perspective can be asked to do. Then Mantegna adjusts it: the proportions are visibly tuned so that the feet do not swallow the head. Three mourners weep beside him. It is a technical demonstration wearing the clothes of a devotional picture, and the whole thing is 68 centimetres wide.",
  notice:["Feet-first foreshortening, the hardest problem perspective has",
          "The proportions are tuned so feet don't dominate",
          "68 centimetres — narrower than a briefcase is wide"],
  tags:["sacred","mourning","geometry","group-scene"] },

{ id:"haboku-sansui", tier:2,
  title:"Haboku Sansui (Splashed-Ink Landscape)", worksKey:"Haboku (Splashed Ink) Landscape",
  artistId:"sesshu-toyo", year:{ display:"1495", sort:1495 },
  movements:["zen-painting"], techniques:["ink-wash","splashed-ink"], nation:"japan",
  museum:{ id:"tokyo-national-museum", name:"Tokyo National Museum", city:"Tokyo" },
  dims:"148.6 × 32.7 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Sesshu_-_Haboku-Sansui_-_complete.jpg/960px-Sesshu_-_Haboku-Sansui_-_complete.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Sesshu_-_Haboku-Sansui_-_complete.jpg", status:"pd" },
  coords:{ F:-20, D:10, E:50, C:0, M:-35 }, coordsSource:"override",
  description:"A cliff, a hut, a boat and two small figures — and above them the ink simply stops describing anything, just fast wet blots on a sheet a metre and a half tall. Haboku is the most extreme manner the tradition had, and Sesshū took it to the edge in 1495. This is about as close to non-figuration as the fifteenth century gets anywhere. Stand close: the whole landscape is a handful of strokes.",
  notice:["The top of the sheet stops describing anything",
          "A cliff, a hut, a boat, two figures",
          "Two sources call it a National Treasure of Japan"],
  tags:["landscape","monochrome","gesture","quiet"] },

{ id:"red-and-white-plum-blossoms", tier:2,
  title:"Red and White Plum Blossoms",
  artistId:"ogata-korin", year:{ display:"c. 1714–1715", sort:1714 },
  movements:["rinpa"], techniques:["tarashikomi","gold-leaf"], nation:"japan",
  museum:{ id:"moa-museum-of-art", name:"MOA Museum of Art", city:"Atami" },
  dims:"156.5 × 172.5 cm (each of two screens)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Ogata_Korin_-_RED_AND_WHITE_PLUM_BLOSSOMS_%28National_Treasure%29_-_Google_Art_Project.jpg/500px-Ogata_Korin_-_RED_AND_WHITE_PLUM_BLOSSOMS_%28National_Treasure%29_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Red_and_White_Plum_Blossoms", status:"pd" },
  coords:{ F:-25, D:-20, E:45, C:-25, M:30 }, coordsSource:"override",
  description:"A river runs down the middle as flat repeating pattern, with no attempt whatsoever to look like water, and a plum tree stands on either bank. The bark is mottled because Kōrin laid a second pigment down before the first had dried — tarashikomi. It is spring, and it stays spring. Nothing else happens. Two screens, each over a metre and a half tall.",
  notice:["The river is pattern; no attempt at water",
          "Mottled bark: wet pigment dropped into wet",
          "Undated — 1714 to 1715 is Yamane's attribution"],
  tags:["pattern","flatness","golden","gesture"] },

{ id:"oath-of-the-horatii", tier:2,
  title:"Oath of the Horatii",
  artistId:"jacques-louis-david", year:{ display:"1784–1785", sort:1784 },
  movements:["neoclassicism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"louvre", name:"Musée du Louvre", city:"Paris" },
  dims:"330 × 425 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Le_Serment_des_Horaces_-_Jacques-Louis_David_-_Mus%C3%A9e_du_Louvre_Peintures_INV_3692_%3B_MR_1432.jpg/500px-Le_Serment_des_Horaces_-_Jacques-Louis_David_-_Mus%C3%A9e_du_Louvre_Peintures_INV_3692_%3B_MR_1432.jpg",
          page:"https://en.wikipedia.org/wiki/Oath_of_the_Horatii", status:"pd" },
  coords:{ F:-85, D:65, E:-35, C:55, M:70 }, coordsSource:"override",
  description:"Three sons, three arms, three swords, all converging on the single point their father holds. To the right the women have collapsed into a separate curve, so that duty and grief do not share a shape. Everything a history painting used to arrange for beauty, David arranges to make a proposition instead. The oath has not been spoken yet. Four and a quarter metres, pitched at a nation.",
  notice:["Three arms, three swords, one point",
          "The women make a curve; the men make angles",
          "The instant before the oath is spoken"],
  tags:["historical","group-scene","theatrical","monumental-scale"] },

{ id:"the-raft-of-the-medusa", tier:2,
  title:"The Raft of the Medusa",
  artistId:"theodore-gericault", year:{ display:"1818–1819", sort:1818 },
  movements:["romanticism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"louvre", name:"Musée du Louvre", city:"Paris" },
  dims:"491 × 716 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg/500px-JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg",
          page:"https://en.wikipedia.org/wiki/The_Raft_of_the_Medusa", status:"pd" },
  coords:{ F:-85, D:85, E:10, C:20, M:90 }, coordsSource:"override",
  description:"Seven metres of canvas — the size the Salon reserved for scripture and antiquity — given over to a news story. Bodies pile into a pyramid, the dead at the base and the living straining up out of it, and at the apex there is no hero, no state and no moral resolution: only a figure signalling at a speck on the horizon.",
  notice:["Seven metres wide, at Salon scale, for contemporary news",
          "The apex holds no hero and no state",
          "A speck on the horizon is the whole plot"],
  tags:["seascape","group-scene","storm","monumental-scale"] },

{ id:"a-burial-at-ornans", tier:2,
  title:"A Burial at Ornans",
  artistId:"gustave-courbet", year:{ display:"1849–1850", sort:1849 },
  movements:["realism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"315 × 668 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Gustave_Courbet_-_A_Burial_at_Ornans_-_Google_Art_Project_2.jpg/500px-Gustave_Courbet_-_A_Burial_at_Ornans_-_Google_Art_Project_2.jpg",
          page:"https://en.wikipedia.org/wiki/A_Burial_at_Ornans", status:"pd" },
  coords:{ F:-85, D:-15, E:15, C:30, M:85 }, coordsSource:"override",
  description:"Six and a half metres of canvas, the scale the Salon kept for coronations, spent on a village funeral. Nobody is ennobled. Nothing is arranged into a hierarchy — the mourners stand in a row and wait, and the open grave is at your feet in the foreground. That was the scandal: not the brushwork, which is coarse, but the size, and who Courbet thought deserved it.",
  notice:["The open grave sits at the viewer's feet",
          "A row of people waiting — the drama is withheld",
          "Coronation scale, given to a village funeral"],
  tags:["group-scene","mourning","everyday-life","monumental-scale"] },

{ id:"a-sunday-afternoon-on-the-island-of-la-grande-jatte", tier:2,
  title:"A Sunday Afternoon on the Island of La Grande Jatte",
  artistId:"georges-seurat", year:{ display:"1884–1886", sort:1884 },
  movements:["neo-impressionism"], techniques:["oil-painting","pointillism"], nation:"france",
  museum:{ id:"art-institute-chicago", name:"Art Institute of Chicago", city:"Chicago" },
  dims:"207.5 × 308.1 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/500px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg",
          page:"https://en.wikipedia.org/wiki/A_Sunday_Afternoon_on_the_Island_of_La_Grande_Jatte", status:"pd" },
  coords:{ F:-75, D:-55, E:60, C:35, M:35 }, coordsSource:"override",
  description:"Dots of unmixed colour, set side by side and left to mix in your eye instead of on the palette — two years of that, across two by three metres. The park is full of people and every one of them is frozen in profile or full face, stiff as a frieze. Nothing moves, including the dog. The stiffness is not a failure; it is the argument.",
  notice:["The colours mix in your eye, not the palette",
          "Every figure is profile or full face, and rigid",
          "Nothing moves, including the dog"],
  tags:["landscape","group-scene","everyday-life","quiet"] }

,
{ id:"young-man-at-his-window", tier:2,
  title:"Young Man at His Window", worksKey:"Man at His Window",
  artistId:"gustave-caillebotte", year:{ display:"1876", sort:1876 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"getty", name:"The Getty Center", city:"Los Angeles" },
  dims:"117 \u00d7 82 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Gustave_Caillebotte_-_Jeune_homme_%C3%A0_sa_fen%C3%AAtre_%28B_32%29.jpg/960px-Gustave_Caillebotte_-_Jeune_homme_%C3%A0_sa_fen%C3%AAtre_%28B_32%29.jpg",
          page:"https://en.wikipedia.org/wiki/Young_Man_at_His_Window", status:"pd" },
  coords:{ F:-85, D:-55, E:15, C:-15, M:-45 }, coordsSource:"override",
  description:"Ren\u00e9 Caillebotte stands at the window of the family apartment on the rue de Miromesnil, hands in his pockets, watching a woman cross the boulevard below. He is the painter\u2019s brother, and he blocks the view we came for. Caillebotte gives the street an engineer\u2019s exactness and gives the man nothing but a dark silhouette. Zola, seeing it at the 1876 Impressionist exhibition, called that exactness \u201canti-artistic\u201d. The complaint was the point. The picture is about the act of looking, and it puts you behind someone who will not turn round.",
  notice:["The figure blocks the view entirely",
          "Zola called its exactness anti-artistic",
          "A French national treasure, sold abroad in 2021"],
  tags:["interior","quiet","lonely","everyday-life"] }

,

/* Added 2026-08-12 for the Actuality list (docs/ACTUALITY.md). Enwonwu died in
   1994, so the work is in copyright: image.status "copyright" with no src, and
   the page carries a generative cover. It is also the catalog's FIRST African
   record — the artists were here, the works were not. */
{ id:"tutu-enwonwu", tier:2,
  title:"Tutu", worksKey:"Tutu",
  artistId:"ben-enwonwu", year:{ display:"1973", sort:1973 },
  movements:["contemporary-art"], techniques:["oil-painting"], nation:"nigeria",
  museum:{ id:"private-collection", name:"Private collection", city:"—" },
  image:{ status:"copyright" },
  coords:{ F:-80, D:-30, E:10, C:-10, M:-35 }, coordsSource:"override",
  description:"A young woman turns her head over her shoulder and looks past you, in a green wrapper against a flat ground. She is Adetutu Ademiluyi, an Ife princess, and Enwonwu painted her in 1973 in a manner that is neither European portraiture nor traditional Igbo sculpture but argues with both. The picture became the most reproduced image in modern Nigerian art, and then it disappeared for forty years.",
  notice:["Three versions were painted; all vanished after 1975",
          "Found in a north London flat in late 2017",
          "Still in copyright, so this page shows no reproduction"],
  tags:["portrait","quiet","would-hang"] }

,

/* Added 2026-08-12 for the August Actuality list. Rousseau died in 1910 and is
   public domain; Tarsila do Amaral died in 1973 and is not, so her record is
   flagged as in-copyright and carries a generative cover.
   NB: this comment deliberately avoids writing that flag out as a literal
   key/value pair — tools/asset_inventory.py counts the string wherever it
   appears, so a comment quoting it inflates copyright_refs by one. */
{ id:"the-dream-rousseau", tier:2,
  title:"The Dream", worksKey:"The Dream",
  artistId:"henri-rousseau", year:{ display:"1910", sort:1910 },
  movements:["naive-art","post-impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"moma", name:"The Museum of Modern Art", city:"New York" },
  dims:"204.5 \u00d7 298.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Henri_Rousseau_005.jpg/500px-Henri_Rousseau_005.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Henri_Rousseau_005.jpg", status:"pd" },
  coords:{ F:-70, D:-20, E:35, C:-30, M:20 }, coordsSource:"override",
  description:"A woman reclines on a Paris sofa in the middle of a jungle, and neither she nor the jungle finds this odd. Lions watch, a snake charmer plays in the half-dark, and every leaf is drawn with the patience of a man copying from life \u2014 which he was, only the life was in a hothouse. Rousseau finished it months before he died, and told a critic the woman was dreaming herself there.",
  notice:["He never left France, let alone saw a jungle",
          "Painted from the Paris botanical gardens and picture books",
          "Finished months before his death in 1910"],
  tags:["landscape","unsettling","monumental-scale","nude"] },

{ id:"tiger-in-a-tropical-storm", tier:2,
  title:"Tiger in a Tropical Storm (Surprised!)", worksKey:"Tiger in a Tropical Storm",
  artistId:"henri-rousseau", year:{ display:"1891", sort:1891 },
  movements:["naive-art","post-impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"national-gallery-london", name:"The National Gallery", city:"London" },
  dims:"129.8 \u00d7 161.9 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Surprised-Rousseau.jpg/500px-Surprised-Rousseau.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Surprised-Rousseau.jpg", status:"pd" },
  coords:{ F:-70, D:35, E:30, C:-25, M:5 }, coordsSource:"override",
  description:"His first jungle, and the storm is doing most of the work: silver rain drawn in diagonal lines straight across the canvas, grasses bent flat, and a tiger caught mid-pounce with its eyes wide. Critics laughed at the flat leaves and the toy-like beast. The bent grass and the rain are, in fact, exactly observed \u2014 he had watched storms, if not tigers.",
  notice:["His first jungle painting, and the critics laughed",
          "The rain is drawn as literal silver lines",
          "Nobody has agreed what surprised the tiger"],
  tags:["landscape","storm","unsettling"] },

{ id:"abaporu", tier:2,
  title:"Abaporu", worksKey:"Abaporu",
  artistId:"tarsila-do-amaral", year:{ display:"1928", sort:1928 },
  movements:["modernism"], techniques:["oil-painting"], nation:"brazil",
  museum:{ id:"private-collection", name:"Private collection", city:"\u2014" },
  image:{ status:"copyright" },
  coords:{ F:-45, D:-25, E:55, C:5, M:10 }, coordsSource:"override",
  description:"A seated figure with an enormous foot in the foreground and a tiny head against a hot sun and a cactus. Tarsila painted it as a birthday present for her husband, the poet Oswald de Andrade, who took one look and wrote the Cannibalist Manifesto around it: Brazil should devour foreign influence and digest it into something its own. The title is Tupi\u2013Guarani for the man who eats people.",
  notice:["The painting came first; the manifesto came after",
          "Abaporu is Tupi\u2013Guarani for man-eater",
          "Still in copyright, so this page shows no reproduction"],
  tags:["portrait","monumental-scale","unsettling"] }

]);
