/* Pigment catalog — part 4 (Tier 1 elevation batch B: Degas, Gauguin,
   Hilma af Klint, Cassatt, Repin). Contract: docs/ARTWORK_SCHEMA.md. */
window.CATALOG = (window.CATALOG || []).concat([

/* ——— The Degas wing ——— */

{ id:"the-bellelli-family", tier:2,
  title:"The Bellelli Family",
  artistId:"edgar-degas", year:{ display:"1858–67", sort:1860 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"200 × 250 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Edgar_Degas_-_The_Bellelli_Family_-_Google_Art_Project.jpg/500px-Edgar_Degas_-_The_Bellelli_Family_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/The_Bellelli_Family", status:"pd" },
  tags:["portrait","interior","quiet"] },

{ id:"cotton-office-new-orleans", tier:2,
  title:"A Cotton Office in New Orleans",
  artistId:"edgar-degas", year:{ display:"1873", sort:1873 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"musee-pau", name:"Musée des Beaux-Arts", city:"Pau" },
  dims:"73 × 92 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cottonexchange1873-Degas.jpg/500px-Cottonexchange1873-Degas.jpg",
          page:"https://en.wikipedia.org/wiki/A_Cotton_Office_in_New_Orleans", status:"pd" },
  tags:["everyday-life","interior","historical"] },

{ id:"the-dance-class", tier:1,
  title:"The Dance Class", worksKey:"The Dance Class",
  artistId:"edgar-degas", year:{ display:"1874", sort:1874 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"85 × 75 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Edgar_Degas_-_La_Classe_de_danse.jpg/500px-Edgar_Degas_-_La_Classe_de_danse.jpg",
          page:"https://en.wikipedia.org/wiki/The_Ballet_Class_(Degas%2C_Mus%C3%A9e_d%27Orsay)", status:"pd" },
  coords:{ F:-80, D:0, E:45, C:5, M:-50 }, coordsSource:"override",
  description:"Degas haunted the Paris Opéra's rehearsal rooms, not its stages: here the old ballet master Jules Perrot taps his stick while two dozen girls stretch, scratch, yawn and fuss with ribbons — labor, not spectacle. A dog wanders the parquet. The composition tilts like a snapshot a decade before snapshots, figures sliced casually by the frame. Degas called himself a realist, never an Impressionist: what he shared with them was modern life; what he kept was drawing.",
  notice:["Nobody is dancing — the subject is waiting, fidgeting, work",
          "A girl on the piano scratches her back; another adjusts an earring",
          "The floorboards' perspective does the composing — follow them"],
  tags:["everyday-life","interior","quiet","would-hang"],
  related:["labsinthe","the-childs-bath"] },

{ id:"labsinthe", tier:1,
  title:"L'Absinthe", worksKey:"L'Absinthe",
  artistId:"edgar-degas", year:{ display:"1875–76", sort:1875 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"92 × 68.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Edgar_Degas_-_In_a_Caf%C3%A9_-_Google_Art_Project_2.jpg/500px-Edgar_Degas_-_In_a_Caf%C3%A9_-_Google_Art_Project_2.jpg",
          page:"https://en.wikipedia.org/wiki/L%27Absinthe", status:"pd" },
  coords:{ F:-80, D:25, E:50, C:15, M:-60 }, coordsSource:"override",
  description:"A woman stares into the middle distance over a glass of absinthe; the man beside her looks elsewhere; the marble tables wedge them into a corner of the Nouvelle Athènes café. Both were actors posing, but England didn't know that: when the picture surfaced in London it was booed as a temperance lesson in French degradation. Degas meant no sermon — just modern loneliness observed at an oblique angle, with the empty tables doing the talking.",
  notice:["The tables have no legs in view — the space floats, queasily",
          "Her shadow and his merge in the mirror behind them",
          "Nobody looks at anybody: the real subject of the picture"],
  tags:["interior","lonely","everyday-life","unsettling"],
  related:["the-dance-class","the-night-cafe"] },

{ id:"place-de-la-concorde", tier:2,
  title:"Place de la Concorde",
  artistId:"edgar-degas", year:{ display:"1875", sort:1875 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"hermitage", name:"The State Hermitage Museum", city:"St Petersburg" },
  dims:"78.4 × 117.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Edgar_Degas_Place_de_la_Concorde.jpg/500px-Edgar_Degas_Place_de_la_Concorde.jpg",
          page:"https://en.wikipedia.org/wiki/Place_de_la_Concorde_(Degas)", status:"pd" },
  tags:["everyday-life","portrait","quiet"] },

{ id:"l-etoile", tier:2,
  title:"L'Étoile (The Star)",
  artistId:"edgar-degas", year:{ display:"1878", sort:1878 },
  movements:["impressionism"], techniques:["pastel"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"58.4 × 42 cm (pastel)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Ballet_%28L%27%C3%89toile%29%2C_Edgar_Degas.jpg/500px-Ballet_%28L%27%C3%89toile%29%2C_Edgar_Degas.jpg",
          page:"https://en.wikipedia.org/wiki/L%27%C3%89toile_(Degas)", status:"pd" },
  tags:["everyday-life","tender","would-hang"] },

{ id:"miss-la-la", tier:2,
  title:"Miss La La at the Cirque Fernando",
  artistId:"edgar-degas", year:{ display:"1879", sort:1879 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"national-gallery-london", name:"The National Gallery", city:"London" },
  dims:"117.2 × 77.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Edgar_Degas%2C_Miss_La_La_at_the_Cirque_Fernando%2C_1879.jpg/500px-Edgar_Degas%2C_Miss_La_La_at_the_Cirque_Fernando%2C_1879.jpg",
          page:"https://en.wikipedia.org/wiki/Miss_La_La_at_the_Cirque_Fernando", status:"pd" },
  tags:["portrait","monumental-scale","golden"] },

{ id:"little-dancer-aged-fourteen", tier:2,
  title:"Little Dancer Aged Fourteen", worksKey:"Little Dancer Aged Fourteen",
  artistId:"edgar-degas", year:{ display:"1878–81", sort:1880 },
  movements:["impressionism"], nation:"france",
  museum:{ id:"philadelphia-museum-of-art", name:"Philadelphia Museum of Art", city:"Philadelphia" },
  dims:"98 cm (bronze cast; wax original in Washington)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Degas_Little_Dancer_PMA%2805c%29_%2815675423180%29.jpg/500px-Degas_Little_Dancer_PMA%2805c%29_%2815675423180%29.jpg",
          page:"https://en.wikipedia.org/wiki/Little_Dancer_of_Fourteen_Years", status:"pd" },
  tags:["portrait","historical","unsettling"] },

{ id:"women-ironing", tier:2,
  title:"Women Ironing",
  artistId:"edgar-degas", year:{ display:"c. 1884–86", sort:1884 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"76 × 81.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Edgar_Degas_-_Repasseuses_-_Mus%C3%A9e_d%27Orsay.jpg/500px-Edgar_Degas_-_Repasseuses_-_Mus%C3%A9e_d%27Orsay.jpg",
          page:"https://en.wikipedia.org/wiki/Women_Ironing", status:"pd" },
  tags:["everyday-life","interior","quiet"] },

{ id:"the-tub", tier:2,
  title:"The Tub",
  artistId:"edgar-degas", year:{ display:"1886", sort:1886 },
  movements:["impressionism"], techniques:["pastel"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"60 × 83 cm (pastel)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Edgar_Degas_-_Le_Tub_%281886_Mus%C3%A9e_d%27Orsay%29.jpg/500px-Edgar_Degas_-_Le_Tub_%281886_Mus%C3%A9e_d%27Orsay%29.jpg",
          page:"https://en.wikipedia.org/wiki/The_Tub_(Degas)", status:"pd" },
  tags:["nude","interior","quiet"] },

{ id:"woman-combing-her-hair", tier:2,
  title:"Woman Combing Her Hair", worksKey:"Woman Combing Her Hair",
  artistId:"edgar-degas", year:{ display:"c. 1888–90", sort:1888 },
  movements:["impressionism"], techniques:["pastel"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"61.3 × 46 cm (pastel)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/%28Albi%29_Femme_nue%2C_assise_par_terre_se_peignant_-_Edgar_Degas_-_Mus%C3%A9e_d%27Orsay.jpg/500px-%28Albi%29_Femme_nue%2C_assise_par_terre_se_peignant_-_Edgar_Degas_-_Mus%C3%A9e_d%27Orsay.jpg",
          page:"https://commons.wikimedia.org/wiki/File:(Albi)_Femme_nue,_assise_par_terre_se_peignant_-_Edgar_Degas_-_Mus%C3%A9e_d%27Orsay.jpg", status:"pd" },
  tags:["nude","quiet","tender"] },

/* ——— The Gauguin wing ——— */

{ id:"vision-after-the-sermon", tier:1,
  title:"Vision After the Sermon", worksKey:"Vision After the Sermon",
  artistId:"paul-gauguin", year:{ display:"1888", sort:1888 },
  movements:["post-impressionism","synthetism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{ id:"scottish-national-gallery", name:"Scottish National Gallery", city:"Edinburgh" },
  dims:"72.2 × 91 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/La_vision_apr%C3%A8s_le_sermon_%28Paul_Gauguin%29.jpg/500px-La_vision_apr%C3%A8s_le_sermon_%28Paul_Gauguin%29.jpg",
          page:"https://en.wikipedia.org/wiki/Vision_After_the_Sermon", status:"pd" },
  coords:{ F:-45, D:35, E:75, C:35, M:-10 }, coordsSource:"override",
  description:"Breton women in starched white coifs close their eyes after church — and share one hallucination: Jacob wrestling the angel on a field of pure vermilion. Gauguin painted the ground red because feeling demanded it, fenced the vision off with a diagonal tree trunk borrowed from Japanese prints, and declared painting freed from appearances. He offered the canvas to two village churches; both priests politely refused. Synthetism — color as emotion, outline as scripture — starts here.",
  notice:["The ground is red because the sermon was, not the grass",
          "The tree trunk divides real women from shared vision",
          "The wrestlers come from Hokusai's sketchbooks, via Brittany"],
  tags:["religious","red","pattern","would-hang"],
  related:["where-do-we-come-from","the-yellow-christ"] },

{ id:"the-yellow-christ", tier:2,
  title:"The Yellow Christ",
  artistId:"paul-gauguin", year:{ display:"1889", sort:1889 },
  movements:["post-impressionism","synthetism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{ id:"buffalo-akg", name:"Buffalo AKG Art Museum", city:"Buffalo" },
  dims:"91.1 × 73.4 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Paul_Gauguin_-_The_Yellow_Christ_%28Le_Christ_jaune%29_1889.jpg/500px-Paul_Gauguin_-_The_Yellow_Christ_%28Le_Christ_jaune%29_1889.jpg",
          page:"https://en.wikipedia.org/wiki/The_Yellow_Christ", status:"pd" },
  tags:["religious","golden","pattern"] },

{ id:"ia-orana-maria", tier:2,
  title:"Ia Orana Maria (Hail Mary)",
  artistId:"paul-gauguin", year:{ display:"1891", sort:1891 },
  movements:["post-impressionism","synthetism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"met", name:"The Metropolitan Museum of Art", city:"New York" },
  dims:"113.7 × 87.6 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Paul_Gauguin_Ia_Orana_Maria_%28Hail_Mary%29_The_Metropolitan_Museum_of_Art1.jpg/500px-Paul_Gauguin_Ia_Orana_Maria_%28Hail_Mary%29_The_Metropolitan_Museum_of_Art1.jpg",
          page:"https://en.wikipedia.org/wiki/Ia_Orana_Maria", status:"pd" },
  tags:["religious","golden","tender"] },

{ id:"vahine-no-te-tiare", tier:2,
  title:"Vahine no te tiare (Woman with a Flower)",
  artistId:"paul-gauguin", year:{ display:"1891", sort:1891 },
  movements:["post-impressionism","synthetism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"ny-carlsberg-glyptotek", name:"Ny Carlsberg Glyptotek", city:"Copenhagen" },
  dims:"70.5 × 46.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Paul_gauguin%2C_vahine_no_te_tiare_%28la_donna_coi_fiori%29%2C_1891%2C_MIN_1828%2C_02.jpg/500px-Paul_gauguin%2C_vahine_no_te_tiare_%28la_donna_coi_fiori%29%2C_1891%2C_MIN_1828%2C_02.jpg",
          page:"https://en.wikipedia.org/wiki/Vahine_no_te_tiare", status:"pd" },
  tags:["portrait","quiet","tender"] },

{ id:"tahitian-women-on-the-beach", tier:2,
  title:"Tahitian Women on the Beach", worksKey:"Tahitian Women on the Beach",
  artistId:"paul-gauguin", year:{ display:"1891", sort:1891 },
  movements:["post-impressionism","synthetism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"69 × 91.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Paul_Gauguin_056.jpg/500px-Paul_Gauguin_056.jpg",
          page:"https://en.wikipedia.org/wiki/Tahitian_Women_on_the_Beach", status:"pd" },
  tags:["portrait","quiet","pattern"] },

{ id:"spirit-of-the-dead-watching", tier:2,
  title:"Spirit of the Dead Watching (Manao tupapau)",
  artistId:"paul-gauguin", year:{ display:"1892", sort:1892 },
  movements:["post-impressionism","synthetism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"buffalo-akg", name:"Buffalo AKG Art Museum", city:"Buffalo" },
  dims:"116.1 × 134.6 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Paul_Gauguin-_Manao_tupapau_%28The_Spirit_of_the_Dead_Keep_Watch%29.JPG/500px-Paul_Gauguin-_Manao_tupapau_%28The_Spirit_of_the_Dead_Keep_Watch%29.JPG",
          page:"https://en.wikipedia.org/wiki/Spirit_of_the_Dead_Watching", status:"pd" },
  tags:["nude","night","unsettling"] },

{ id:"nevermore", tier:2,
  title:"Nevermore",
  artistId:"paul-gauguin", year:{ display:"1897", sort:1897 },
  movements:["post-impressionism","synthetism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"courtauld-gallery", name:"The Courtauld Gallery", city:"London" },
  dims:"60.5 × 116 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Paul_Gauguin_091.jpg/500px-Paul_Gauguin_091.jpg",
          page:"https://en.wikipedia.org/wiki/Nevermore_(Gauguin)", status:"pd" },
  tags:["nude","lonely","unsettling"] },

{ id:"where-do-we-come-from", tier:1,
  title:"Where Do We Come From? What Are We? Where Are We Going?",
  worksKey:"Where Do We Come From? What Are We? Where Are We Going?",
  artistId:"paul-gauguin", year:{ display:"1897–98", sort:1897 },
  movements:["post-impressionism","synthetism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"mfa-boston", name:"Museum of Fine Arts", city:"Boston" },
  dims:"139 × 375 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gauguin_-_Where_Do_We_Come_From%3F_What_Are_We%3F_Where_Are_We_Going%3F_%281897-98%29.jpg/500px-Gauguin_-_Where_Do_We_Come_From%3F_What_Are_We%3F_Where_Are_We_Going%3F_%281897-98%29.jpg",
          page:"https://en.wikipedia.org/wiki/Where_Do_We_Come_From%3F_What_Are_We%3F_Where_Are_We_Going%3F", status:"pd" },
  coords:{ F:-50, D:30, E:70, C:45, M:70 }, coordsSource:"override",
  description:"Painted flat-out in Tahiti after news of his daughter's death, intended — he said — as his testament before a suicide attempt: read it right to left, from the sleeping infant to the old woman awaiting death, with the blue idol of the Beyond watching. Gauguin insisted the title's questions stay unanswered and painted them into the corner like graffiti on a golden wall. Boston got the century's most ambitious painted sermon; Gauguin got seven more ragged years.",
  notice:["Read it right to left: infancy, appetite, doubt, the end",
          "The title is painted into the top left corner, like graffiti",
          "The blue idol watches everything and explains nothing"],
  tags:["monumental-scale","golden","unsettling","historical"],
  related:["vision-after-the-sermon","the-scream"] },

{ id:"self-portrait-with-halo", tier:2,
  title:"Self-Portrait with Halo and Snake",
  artistId:"paul-gauguin", year:{ display:"1889", sort:1889 },
  movements:["post-impressionism","synthetism"], techniques:["oil-painting","flat-color"], nation:"france",
  museum:{ id:"national-gallery-dc", name:"National Gallery of Art", city:"Washington" },
  dims:"79.2 × 51.3 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Paul_Gauguin_-_Self-Portrait_with_Halo_and_Snake.jpg/500px-Paul_Gauguin_-_Self-Portrait_with_Halo_and_Snake.jpg",
          page:"https://en.wikipedia.org/wiki/Self-Portrait_with_Halo_and_Snake", status:"pd" },
  tags:["portrait","pattern","red"] },

/* ——— The Hilma af Klint wing ——— */

{ id:"the-ten-largest-no-2", tier:2,
  title:"The Ten Largest, No. 2, Childhood",
  artistId:"hilma-af-klint", year:{ display:"1907", sort:1907 },
  movements:["abstract-art","symbolism"], techniques:["tempera"], nation:"sweden",
  museum:{ id:"moderna-museet", name:"Moderna Museet", city:"Stockholm" },
  dims:"328 × 240 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Hilma_af_Klint_-_The_Ten_Largest_No._2_-_Childhood_-_1907.jpg/500px-Hilma_af_Klint_-_The_Ten_Largest_No._2_-_Childhood_-_1907.jpg",
          page:"https://en.wikipedia.org/wiki/The_Ten_Largest", status:"pd" },
  tags:["pattern","tender","monumental-scale"] },

{ id:"the-ten-largest-no-7", tier:1,
  title:"The Ten Largest, No. 7, Adulthood", worksKey:"The Ten Largest",
  artistId:"hilma-af-klint", year:{ display:"1907", sort:1907 },
  movements:["abstract-art","symbolism"], techniques:["tempera"], nation:"sweden",
  museum:{ id:"moderna-museet", name:"Moderna Museet", city:"Stockholm" },
  dims:"328 × 240 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Hilma_af_Klint_-_The_Ten_Largest_No._7_-_Adulthood_-_1907.jpg/500px-Hilma_af_Klint_-_The_Ten_Largest_No._7_-_Adulthood_-_1907.jpg",
          page:"https://en.wikipedia.org/wiki/The_Ten_Largest", status:"pd" },
  coords:{ F:80, D:-15, E:90, C:45, M:60 }, coordsSource:"override",
  description:"Three metres tall, painted in tempera on paper in a matter of days — one panel of ten charting life from childhood to old age, commissioned, af Klint said, by the spirit guides she called the High Masters. Adulthood unfurls as looping script, orbiting discs and botanical geometry with no visible world behind them: pure abstraction in 1907, four years before Kandinsky's claimed first. She showed them to almost no one. The future had to wait in storage.",
  notice:["Painted in 1907 — check the date against everything around it",
          "The looping script quotes no alphabet; it only behaves like one",
          "Wall-sized, on paper, by a woman working for an audience of spirits"],
  tags:["pattern","monumental-scale","would-hang","historical"],
  related:["swan-no-17","composition-vii"] },

{ id:"the-ten-largest-no-9", tier:2,
  title:"The Ten Largest, No. 9, Old Age",
  artistId:"hilma-af-klint", year:{ display:"1907", sort:1907 },
  movements:["abstract-art","symbolism"], techniques:["tempera"], nation:"sweden",
  museum:{ id:"moderna-museet", name:"Moderna Museet", city:"Stockholm" },
  dims:"328 × 240 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/4_hilma_af_klint%2C_the_ten_largest%2C_no_9.jpg/500px-4_hilma_af_klint%2C_the_ten_largest%2C_no_9.jpg",
          page:"https://commons.wikimedia.org/wiki/File:4_hilma_af_klint,_the_ten_largest,_no_9.jpg", status:"pd" },
  tags:["pattern","quiet","monumental-scale"] },

{ id:"swan-no-17", tier:1,
  title:"The Swan, No. 17", worksKey:"The Swan series",
  artistId:"hilma-af-klint", year:{ display:"1915", sort:1915 },
  movements:["abstract-art","symbolism"], techniques:["oil-painting"], nation:"sweden",
  museum:{ id:"moderna-museet", name:"Moderna Museet", city:"Stockholm" },
  dims:"150.5 × 151 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Hilma_af_Klint%2C_1915%2C_Svanen%2C_No._17.jpg/500px-Hilma_af_Klint%2C_1915%2C_Svanen%2C_No._17.jpg",
          page:"https://en.wikipedia.org/wiki/The_Swan_(af_Klint)", status:"pd" },
  coords:{ F:95, D:0, E:90, C:60, M:0 }, coordsSource:"override",
  description:"By the seventeenth painting of the series, the swans are gone: what remains is their collision distilled into a target of concentric color on a field split black and white. Af Klint painted it in 1915 as occult research — opposites uniting, spirit and matter reconciled — and filed it away with the rest of the Temple paintings. Hung today it reads as hard-edge abstraction arriving five decades early. Almost nobody was allowed to see it for seventy years.",
  notice:["Start from the title: find what remains of two swans",
          "The black and white halves swap charge across the centre line",
          "1915: geometry this clean won't be fashionable until the 1960s"],
  tags:["pattern","quiet","would-hang","historical"],
  related:["the-ten-largest-no-7","several-circles"] },

{ id:"altarpiece-group-x-no-1", tier:2,
  title:"Group X, No. 1, Altarpiece",
  artistId:"hilma-af-klint", year:{ display:"1915", sort:1915 },
  movements:["abstract-art","symbolism"], techniques:["oil-painting","gold-leaf"], nation:"sweden",
  museum:{ id:"moderna-museet", name:"Moderna Museet", city:"Stockholm" },
  dims:"237.5 × 179.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Hilma_af_Klint_-_Altarpiece_No._1_Group_X_%2813919%29.jpg/500px-Hilma_af_Klint_-_Altarpiece_No._1_Group_X_%2813919%29.jpg",
          page:"https://en.wikipedia.org/wiki/Paintings_for_the_Temple", status:"pd" },
  tags:["pattern","golden","monumental-scale"] },

{ id:"tree-of-knowledge-no-1", tier:2,
  title:"Tree of Knowledge, No. 1",
  artistId:"hilma-af-klint", year:{ display:"1913–15", sort:1913 },
  movements:["abstract-art","symbolism"], techniques:["watercolor"], nation:"sweden",
  museum:{ id:"glenstone", name:"Glenstone", city:"Potomac" },
  dims:"45.7 × 29.5 cm (watercolour)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Tree_of_Knowledge_No._1%2C_Hilma_af_Klint%2C_1913-1915%2C_Glenstone_2023.jpg/500px-Tree_of_Knowledge_No._1%2C_Hilma_af_Klint%2C_1913-1915%2C_Glenstone_2023.jpg",
          page:"https://en.wikipedia.org/wiki/Tree_of_Knowledge_(af_Klint)", status:"pd" },
  tags:["pattern","tender","quiet"] },

/* ——— The Cassatt wing ——— */

{ id:"little-girl-in-a-blue-armchair", tier:2,
  title:"Little Girl in a Blue Armchair", worksKey:"Little Girl in a Blue Armchair",
  artistId:"mary-cassatt", year:{ display:"1878", sort:1878 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"usa",
  museum:{ id:"national-gallery-dc", name:"National Gallery of Art", city:"Washington" },
  dims:"89.5 × 129.8 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Cassatt_Mary_Little_Girl_in_a_blue_armchair_Sun_Unedited_1878.jpg/500px-Cassatt_Mary_Little_Girl_in_a_blue_armchair_Sun_Unedited_1878.jpg",
          page:"https://en.wikipedia.org/wiki/Little_Girl_in_a_Blue_Armchair", status:"pd" },
  tags:["portrait","interior","tender"] },

{ id:"woman-with-a-pearl-necklace", tier:2,
  title:"Woman with a Pearl Necklace in a Loge",
  artistId:"mary-cassatt", year:{ display:"1879", sort:1879 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"usa",
  museum:{ id:"philadelphia-museum-of-art", name:"Philadelphia Museum of Art", city:"Philadelphia" },
  dims:"81.3 × 59.7 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Mary_Cassatt_-_Woman_with_a_Pearl_Necklace.jpg/500px-Mary_Cassatt_-_Woman_with_a_Pearl_Necklace.jpg",
          page:"https://en.wikipedia.org/wiki/Woman_with_a_Pearl_Necklace_in_a_Loge", status:"pd" },
  tags:["portrait","golden","everyday-life"] },

{ id:"the-cup-of-tea", tier:2,
  title:"The Cup of Tea",
  artistId:"mary-cassatt", year:{ display:"c. 1880–81", sort:1880 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"usa",
  museum:{ id:"met", name:"The Metropolitan Museum of Art", city:"New York" },
  dims:"92.4 × 65.4 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Cassatt_Mary_The_Cup_of_Tea_1880.jpg/500px-Cassatt_Mary_The_Cup_of_Tea_1880.jpg",
          page:"https://en.wikipedia.org/wiki/The_Cup_of_Tea", status:"pd" },
  tags:["interior","quiet","tender"] },

{ id:"lydia-crocheting", tier:2,
  title:"Lydia Crocheting in the Garden at Marly",
  artistId:"mary-cassatt", year:{ display:"1880", sort:1880 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"usa",
  museum:{ id:"met", name:"The Metropolitan Museum of Art", city:"New York" },
  dims:"65.6 × 92.6 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Lydia_Crocheting_in_the_Garden_at_Marly_MET_DP165250.jpg/500px-Lydia_Crocheting_in_the_Garden_at_Marly_MET_DP165250.jpg",
          page:"https://en.wikipedia.org/wiki/Lydia_Crocheting_in_the_Garden_at_Marly", status:"pd" },
  tags:["everyday-life","quiet","tender"] },

{ id:"the-letter", tier:2,
  title:"The Letter",
  artistId:"mary-cassatt", year:{ display:"1890–91", sort:1890 },
  movements:["impressionism"], techniques:["etching"], nation:"usa",
  museum:{ id:"national-gallery-dc", name:"National Gallery of Art", city:"Washington" },
  dims:"34.5 × 21.1 cm (drypoint and aquatint)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Mary_Cassatt%2C_The_Letter%2C_1890-1891%2C_NGA_168826.jpg/500px-Mary_Cassatt%2C_The_Letter%2C_1890-1891%2C_NGA_168826.jpg",
          page:"https://en.wikipedia.org/wiki/The_Letter_(Cassatt)", status:"pd" },
  tags:["interior","pattern","quiet"] },

{ id:"the-childs-bath", tier:1,
  title:"The Child's Bath", worksKey:"The Child's Bath",
  artistId:"mary-cassatt", year:{ display:"1893", sort:1893 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"usa",
  museum:{ id:"art-institute-chicago", name:"Art Institute of Chicago", city:"Chicago" },
  dims:"100.3 × 66.1 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Mary_Cassatt_-_The_Child%27s_Bath_-_Google_Art_Project.jpg/500px-Mary_Cassatt_-_The_Child%27s_Bath_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/The_Child%27s_Bath", status:"pd" },
  coords:{ F:-80, D:-40, E:30, C:-35, M:-75 }, coordsSource:"override",
  description:"A mother scrubs a child's feet in a basin, both heads bowed on the same diagonal — hygiene as tenderness, observed from above like a Japanese print and patterned within an inch of its life: stripes, florals, carpet, wallpaper. Cassatt took the maternal subject the Salon sentimentalized and made it rigorous — no eye contact with the viewer, all attention inside the picture. Chicago bought it in 1910, when American museums owned almost nothing this modern.",
  notice:["The view is from above — Utamaro's angle, not the Salon's",
          "Count the competing patterns living peacefully on one canvas",
          "Nobody looks at you; the picture is complete without us"],
  tags:["tender","interior","pattern","would-hang"],
  related:["the-dance-class","the-milkmaid"] },

{ id:"the-boating-party", tier:2,
  title:"The Boating Party", worksKey:"The Boating Party",
  artistId:"mary-cassatt", year:{ display:"1893–94", sort:1893 },
  movements:["impressionism"], techniques:["oil-painting","flat-color"], nation:"usa",
  museum:{ id:"national-gallery-dc", name:"National Gallery of Art", city:"Washington" },
  dims:"90 × 117.3 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Mary_Cassatt_-_The_Boating_Party_-_Google_Art_Project.jpg/500px-Mary_Cassatt_-_The_Boating_Party_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/The_Boating_Party", status:"pd" },
  tags:["everyday-life","tender","would-hang"] },

/* ——— The Repin wing ——— */

{ id:"barge-haulers-on-the-volga", tier:1,
  title:"Barge Haulers on the Volga", worksKey:"Barge Haulers on the Volga",
  artistId:"ilya-repin", year:{ display:"1870–73", sort:1870 },
  movements:["realism","peredvizhniki"], techniques:["oil-painting"], nation:"ukraine",
  museum:{ id:"russian-museum", name:"State Russian Museum", city:"St Petersburg" },
  dims:"131.5 × 281 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Ilia_Efimovich_Repin_%281844-1930%29_-_Volga_Boatmen_%281870-1873%29.jpg/500px-Ilia_Efimovich_Repin_%281844-1930%29_-_Volga_Boatmen_%281870-1873%29.jpg",
          page:"https://en.wikipedia.org/wiki/Barge_Haulers_on_the_Volga", status:"pd" },
  coords:{ F:-90, D:45, E:-10, C:10, M:55 }, coordsSource:"override",
  description:"Eleven men in harness drag a ship against the Volga's current — each one a studied portrait, led by Kanin, a defrocked priest whose philosopher's face Repin found on a sketching trip. The twenty-something painter balanced indictment and monument: the boy at the centre lifts his strap as if about to shrug off the whole empire. Dostoevsky praised the picture for preaching nothing. It became Russian realism's flagship — and, ironically, the Tsar's son bought it.",
  notice:["Eleven faces, eleven biographies — start with Kanin at the front",
          "The boy in the centre is the only one fighting the harness",
          "A tiny steamship on the horizon: the future, ignoring them"],
  tags:["historical","everyday-life","monumental-scale","lonely"],
  related:["ivan-the-terrible-and-his-son","the-potato-eaters"] },

{ id:"sadko", tier:2,
  title:"Sadko",
  artistId:"ilya-repin", year:{ display:"1876", sort:1876 },
  movements:["realism","peredvizhniki"], techniques:["oil-painting"], nation:"ukraine",
  museum:{ id:"russian-museum", name:"State Russian Museum", city:"St Petersburg" },
  dims:"322.5 × 230 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Ilya_Repin_-_Sadko_-_Google_Art_Project_levels_adjustment_2.jpg/500px-Ilya_Repin_-_Sadko_-_Google_Art_Project_levels_adjustment_2.jpg",
          page:"https://en.wikipedia.org/wiki/Sadko_(painting)", status:"pd" },
  tags:["historical","night","monumental-scale"] },

{ id:"religious-procession-in-kursk", tier:2,
  title:"Religious Procession in Kursk Governorate",
  artistId:"ilya-repin", year:{ display:"1880–83", sort:1880 },
  movements:["realism","peredvizhniki"], techniques:["oil-painting"], nation:"ukraine",
  museum:{ id:"tretyakov", name:"Tretyakov Gallery", city:"Moscow" },
  dims:"175 × 280 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Procesi%C3%B3n_de_Pascua_en_la_regi%C3%B3n_de_Kursk%2C_por_Ili%C3%A1_Repin.jpg/500px-Procesi%C3%B3n_de_Pascua_en_la_regi%C3%B3n_de_Kursk%2C_por_Ili%C3%A1_Repin.jpg",
          page:"https://en.wikipedia.org/wiki/Religious_Procession_in_Kursk_Governorate", status:"pd" },
  tags:["historical","everyday-life","monumental-scale"] },

{ id:"portrait-of-mussorgsky", tier:2,
  title:"Portrait of Modest Mussorgsky",
  artistId:"ilya-repin", year:{ display:"1881", sort:1881 },
  movements:["realism","peredvizhniki"], techniques:["oil-painting","alla-prima"], nation:"ukraine",
  museum:{ id:"tretyakov", name:"Tretyakov Gallery", city:"Moscow" },
  dims:"69 × 57 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Modest_M%C3%BAsorgski%2C_por_Ili%C3%A1_Repin.jpg/500px-Modest_M%C3%BAsorgski%2C_por_Ili%C3%A1_Repin.jpg",
          page:"https://en.wikipedia.org/wiki/Portrait_of_Modest_Mussorgsky", status:"pd" },
  tags:["portrait","unsettling","historical"] },

{ id:"ivan-the-terrible-and-his-son", tier:1,
  title:"Ivan the Terrible and His Son Ivan", worksKey:"Ivan the Terrible and His Son Ivan",
  artistId:"ilya-repin", year:{ display:"1885", sort:1885 },
  movements:["realism","peredvizhniki"], techniques:["oil-painting"], nation:"ukraine",
  museum:{ id:"tretyakov", name:"Tretyakov Gallery", city:"Moscow" },
  dims:"199.5 × 254 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Iv%C3%A1n_el_Terrible_y_su_hijo%2C_por_Ili%C3%A1_Repin.jpg/500px-Iv%C3%A1n_el_Terrible_y_su_hijo%2C_por_Ili%C3%A1_Repin.jpg",
          page:"https://en.wikipedia.org/wiki/Ivan_the_Terrible_and_His_Son_Ivan", status:"pd" },
  coords:{ F:-85, D:90, E:15, C:15, M:20 }, coordsSource:"override",
  description:"Seconds after the blow: Ivan clutches his dying son, eyes blown wide with the understanding that he has just ended his own dynasty. Repin painted history as psychological catastrophe — the brocade, the overturned throne, the carpets, all swallowed by those eyes. Alexander III banned it from exhibition, a first in Russia; a distressed viewer slashed it in 1913, and another attacked it in 2018. It hangs in the Tretyakov behind glass, still radioactive.",
  notice:["The Tsar's eyes: horror arriving one heartbeat after the act",
          "The son forgives — his hand rests gently on his father's arm",
          "An overturned throne in the shadows tells the dynasty's future"],
  tags:["historical","unsettling","red","interior"],
  related:["barge-haulers-on-the-volga","saturn-devouring-his-son"] },

{ id:"they-did-not-expect-him", tier:2,
  title:"They Did Not Expect Him",
  artistId:"ilya-repin", year:{ display:"1884–88", sort:1884 },
  movements:["realism","peredvizhniki"], techniques:["oil-painting"], nation:"ukraine",
  museum:{ id:"tretyakov", name:"Tretyakov Gallery", city:"Moscow" },
  dims:"160.5 × 167.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Ilya_Repin_Unexpected_visitors.jpg/500px-Ilya_Repin_Unexpected_visitors.jpg",
          page:"https://en.wikipedia.org/wiki/They_Did_Not_Expect_Him", status:"pd" },
  tags:["interior","historical","tender"] },

{ id:"portrait-of-leo-tolstoy", tier:2,
  title:"Portrait of Leo Tolstoy",
  artistId:"ilya-repin", year:{ display:"1887", sort:1887 },
  movements:["realism","peredvizhniki"], techniques:["oil-painting"], nation:"ukraine",
  museum:{ id:"tretyakov", name:"Tretyakov Gallery", city:"Moscow" },
  dims:"124 × 88 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Ilya_Efimovich_Repin_%281844-1930%29_-_Portrait_of_Leo_Tolstoy_%281887%29.jpg/500px-Ilya_Efimovich_Repin_%281844-1930%29_-_Portrait_of_Leo_Tolstoy_%281887%29.jpg",
          page:"https://en.wikipedia.org/wiki/Leo_Tolstoy", status:"pd" },
  tags:["portrait","quiet","historical"] },

{ id:"reply-of-the-zaporozhian-cossacks", tier:2,
  title:"Reply of the Zaporozhian Cossacks", worksKey:"Reply of the Zaporozhian Cossacks",
  artistId:"ilya-repin", year:{ display:"1880–91", sort:1880 },
  movements:["realism","peredvizhniki"], techniques:["oil-painting"], nation:"ukraine",
  museum:{ id:"russian-museum", name:"State Russian Museum", city:"St Petersburg" },
  dims:"203 × 358 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Ilja_Jefimowitsch_Repin_-_Reply_of_the_Zaporozhian_Cossacks_-_Yorck.jpg/500px-Ilja_Jefimowitsch_Repin_-_Reply_of_the_Zaporozhian_Cossacks_-_Yorck.jpg",
          page:"https://en.wikipedia.org/wiki/Reply_of_the_Zaporozhian_Cossacks", status:"pd" },
  tags:["historical","everyday-life","monumental-scale"] }
]);
