/* PIGMENT — catalogue batch 13: every painter gets a work.

   Owner's decision, 2026-09-29: the 70 painters who died after 1955 (or are
   living) and had no catalogued work at all get Tier 2 records. They cannot
   carry an image -- the work is under copyright -- so each record carries a
   generative cover, never a reproduction, exactly as Guernica and the
   Abstract Expressionists do. With batches 10-12, this closes the gap the
   depth plan measured: no painter in the atlas is left without something to
   admire, save, or link to.

   One work per painter, chosen from the painter's own declared works, with
   specific single pictures preferred over series wherever the declared list
   allowed it.

   THE MUSEUM FIELD IS FILLED ONLY WHERE IT WAS EVIDENCED. 23 of 70 carry one.
   The rest are left blank, which the schema permits for Tier 2 ("required if
   known"), rather than filled from memory. Evidence came from two sources,
   and the second exists because the first was blind:

     1. The work's Wikipedia infobox museum field -- which silently returns
        nothing for the MOST famous pictures, because their infoboxes are
        Wikidata-driven and have no museum line in the wikitext at all.
        Nighthawks was invisible to it.
     2. The work's own Wikidata item, reached through the article (never a
        guessed QID), accepted only when the creator matches and the article
        title matches the work exactly, and reading the CURRENT holder only --
        a collection statement with an end date is ignored.

   Three candidate venues were rejected on review:
     - Braque -> MOCA Los Angeles: a fuzzy name match on the word
       "contemporary". The work is in Lille, and both sources agree on Lille.
     - de Kooning's Woman I -> University of Arizona: the title reduced to the
       single word "woman" and matched Woman-Ochre, a different de Kooning.
       Woman I is at MoMA, which the Wikidata pass then confirmed.
     - Kerry James Marshall's Past Times -> the Met: contradicts the painting's
       documented 2018 sale to a private buyer. Where sources disagree the
       field is left blank.

   Two venues join the registry because both sources agreed on them: LACMA
   (The Treachery of Images) and LaM Lille (Houses at L'Estaque). */
window.CATALOG = (window.CATALOG || []).concat([

{ id:"the-fantastic-period-paintings", tier:2, title:"The 'fantastic period' paintings", artistId:"zdzislaw-beksinski",
  year:{display:"c. 1968–83",sort:1968}, movements:["surrealism","contemporary-art"], techniques:["oil-painting","glazing"], nation:"poland",
  image:{status:"copyright"},
  coords:{F:-45,D:80,E:55,C:25,M:50}, tags:["unsettling","fever-dream","texture"] },
{ id:"mevlevi-dervishes-call", tier:2, title:"Mevlevi Dervishes", artistId:"ibrahim-calli",
  year:{display:"c. 1920s",sort:1920}, movements:["impressionism"], techniques:["oil-painting","alla-prima"], nation:"turkey",
  image:{status:"copyright"},
  coords:{F:-70,D:30,E:10,C:-10,M:10}, tags:["sacred","gesture","group-scene"] },
{ id:"cafe-scene-paris", tier:2, title:"Café Scene, Paris", artistId:"fikret-mualla",
  year:{display:"c. 1950s",sort:1950}, movements:["expressionism","fauvism"], techniques:["gouache","watercolor"], nation:"turkey",
  image:{status:"copyright"},
  coords:{F:-65,D:20,E:30,C:-35,M:-30}, tags:["everyday-life","playful","red"] },
{ id:"my-hell-zeid", tier:2, title:"My Hell", artistId:"fahrelnissa-zeid",
  year:{display:"1951",sort:1951}, movements:["abstract-art","expressionism"], techniques:["oil-painting","mixed-media"], nation:"turkey",
  image:{status:"copyright"},
  coords:{F:70,D:70,E:65,C:30,M:70}, tags:["pattern","monumental-scale","ecstatic"] },
{ id:"han-coffeehouse-eyuboglu", tier:2, title:"Han Coffeehouse", artistId:"bedri-rahmi-eyuboglu",
  year:{display:"1973",sort:1973}, movements:["expressionism","naive-art"], techniques:["oil-painting","gouache"], nation:"turkey",
  image:{status:"copyright"},
  coords:{F:-45,D:0,E:35,C:-15,M:0}, tags:["everyday-life","pattern","flatness"] },
{ id:"hands-series-dino", tier:2, title:"Hands series", artistId:"abidin-dino",
  year:{display:"1960s–80s",sort:1960}, movements:["surrealism","contemporary-art"], techniques:["oil-painting","watercolor"], nation:"turkey",
  image:{status:"copyright"},
  coords:{F:-40,D:30,E:40,C:30,M:-40}, tags:["gesture","monochrome","tender"] },
{ id:"blue-symphony-dogancay", tier:2, title:"Blue Symphony", artistId:"burhan-dogancay",
  year:{display:"1987",sort:1987}, movements:["contemporary-art","pop-art"], techniques:["acrylic-painting","collage"], nation:"turkey",
  image:{status:"copyright"},
  coords:{F:65,D:10,E:55,C:40,M:20}, tags:["blue","pattern","texture"] },
{ id:"amorpha-fugue-in-two-colors", tier:2, title:"Amorpha: Fugue in Two Colors", artistId:"frantisek-kupka",
  year:{display:"1912",sort:1912}, movements:["orphism","abstract-art"], techniques:["oil-painting","glazing"], nation:"czechia",
  image:{status:"copyright"},
  coords:{F:90,D:40,E:80,C:55,M:40}, tags:["geometry","pattern","red"] },
{ id:"bal-bullier-delaunay", tier:2, title:"Bal Bullier", artistId:"sonia-delaunay",
  year:{display:"1913",sort:1913}, movements:["orphism","abstract-art"], techniques:["oil-painting","flat-color"], nation:"france",
  image:{status:"copyright"},
  coords:{F:40,D:55,E:70,C:15,M:45}, tags:["pattern","ecstatic","group-scene"] },
{ id:"portrait-of-the-journalist-sylvia-von-harden", tier:2, title:"Portrait of the Journalist Sylvia von Harden", artistId:"otto-dix",
  year:{display:"1926",sort:1926}, movements:["new-objectivity","expressionism"], techniques:["oil-painting","etching"], nation:"germany",
  museum:{id:"centre-pompidou",name:"Centre Pompidou",city:"Paris"},
  image:{status:"copyright"},
  coords:{F:-85,D:35,E:35,C:25,M:-35}, tags:["portrait","unsettling","red"] },
{ id:"cut-with-the-kitchen-knife-dada", tier:2, title:"Cut with the Kitchen Knife Dada through the Last Weimar Beer-Belly Cultural Epoch of Germany", artistId:"hannah-hoch",
  year:{display:"1919–20",sort:1919}, movements:["dada"], techniques:["photomontage","collage"], nation:"germany",
  image:{status:"copyright"},
  coords:{F:-10,D:65,E:85,C:70,M:10}, tags:["texture","playful","pattern"] },
{ id:"self-portrait-carrington", tier:2, title:"Self-Portrait (Inn of the Dawn Horse)", artistId:"leonora-carrington",
  year:{display:"1937–38",sort:1937}, movements:["surrealism"], techniques:["oil-painting","tempera"], nation:"mexico",
  museum:{id:"met",name:"The Metropolitan Museum of Art",city:"New York"},
  image:{status:"copyright"},
  coords:{F:-65,D:35,E:60,C:45,M:-10}, tags:["self-portrait","unsettling","animal"] },
{ id:"embroidering-the-earth-s-mantle", tier:2, title:"Embroidering the Earth's Mantle", artistId:"remedios-varo",
  year:{display:"1961",sort:1961}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"spain",
  image:{status:"copyright"},
  coords:{F:-60,D:10,E:60,C:55,M:0}, tags:["fever-dream","pattern","quiet"] },
{ id:"t1935-1-hartung", tier:2, title:"T1935-1", artistId:"hans-hartung",
  year:{display:"1935",sort:1935}, movements:["art-informel","abstract-art"], techniques:["oil-painting","gestural-abstraction"], nation:"germany",
  image:{status:"copyright"},
  coords:{F:90,D:55,E:70,C:35,M:20}, tags:["gesture","monochrome"] },
{ id:"zebra-vasarely", tier:2, title:"Zebra", artistId:"victor-vasarely",
  year:{display:"1937",sort:1937}, movements:["op-art","abstract-art"], techniques:["acrylic-painting","flat-color"], nation:"hungary",
  image:{status:"copyright"},
  coords:{F:40,D:30,E:65,C:50,M:-10}, tags:["animal","monochrome","pattern"] },
{ id:"the-jungle-lam", tier:2, title:"The Jungle", artistId:"wifredo-lam",
  year:{display:"1943",sort:1943}, movements:["surrealism","cubism"], techniques:["oil-painting","glazing"], nation:"cuba",
  image:{status:"copyright"},
  coords:{F:-20,D:70,E:75,C:40,M:75}, tags:["unsettling","pattern","monumental-scale"] },
{ id:"reclining-nude-with-toile-de-jouy", tier:2, title:"Reclining Nude with Toile de Jouy", artistId:"tsuguharu-foujita",
  year:{display:"1922",sort:1922}, movements:["expressionism"], techniques:["oil-painting","watercolor"], nation:"japan",
  image:{status:"copyright"},
  coords:{F:-85,D:-35,E:25,C:-40,M:30}, tags:["nude","quiet","pattern"] },
{ id:"eagle-standing-on-pine-tree", tier:2, title:"Eagle Standing on Pine Tree", artistId:"qi-baishi",
  year:{display:"1946",sort:1946}, movements:["literati-painting","realism"], techniques:["ink-wash","watercolor"], nation:"china",
  image:{status:"copyright"},
  coords:{F:-45,D:25,E:15,C:10,M:55}, tags:["animal","monochrome","gesture"] },
{ id:"aspects-of-negro-life-from-slavery", tier:2, title:"Aspects of Negro Life: From Slavery Through Reconstruction", artistId:"aaron-douglas",
  year:{display:"1934",sort:1934}, movements:["harlem-renaissance"], techniques:["oil-painting","gouache"], nation:"usa",
  image:{status:"copyright"},
  coords:{F:-35,D:40,E:40,C:45,M:70}, tags:["historical","flatness","monumental-scale"] },
{ id:"the-block-bearden", tier:2, title:"The Block", artistId:"romare-bearden",
  year:{display:"1971",sort:1971}, movements:["contemporary-art","harlem-renaissance"], techniques:["collage","photomontage"], nation:"usa",
  image:{status:"copyright"},
  coords:{F:-40,D:25,E:65,C:40,M:45}, tags:["everyday-life","pattern","group-scene"] },
{ id:"vir-heroicus-sublimis", tier:2, title:"Vir Heroicus Sublimis", artistId:"barnett-newman",
  year:{display:"1950–51",sort:1950}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","flat-color"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"},
  image:{status:"copyright"},
  coords:{F:95,D:25,E:70,C:70,M:100}, tags:["red","monumental-scale","flatness"] },
{ id:"friendship-martin", tier:2, title:"Friendship", artistId:"agnes-martin",
  year:{display:"1963",sort:1963}, movements:["minimalism","abstract-art"], techniques:["acrylic-painting","oil-painting"], nation:"canada",
  image:{status:"copyright"},
  coords:{F:95,D:-80,E:55,C:65,M:30}, tags:["golden","geometry","quiet"] },
{ id:"ned-kelly-nolan", tier:2, title:"Ned Kelly", artistId:"sidney-nolan",
  year:{display:"1946",sort:1946}, movements:["expressionism","surrealism"], techniques:["oil-painting","alla-prima"], nation:"australia",
  image:{status:"copyright"},
  coords:{F:-45,D:35,E:40,C:30,M:10}, tags:["landscape","historical","flatness"] },
{ id:"earth-s-creation-i", tier:2, title:"Earth's Creation I", artistId:"emily-kame-kngwarreye",
  year:{display:"1994",sort:1994}, movements:["contemporary-art","abstract-art"], techniques:["acrylic-painting","gestural-abstraction"], nation:"australia",
  image:{status:"copyright"},
  coords:{F:80,D:40,E:45,C:40,M:85}, tags:["pattern","landscape","monumental-scale"] },
{ id:"song-of-the-pick-sekoto", tier:2, title:"Song of the Pick", artistId:"gerard-sekoto",
  year:{display:"1947",sort:1947}, movements:["expressionism","realism"], techniques:["oil-painting","gouache"], nation:"south-africa",
  image:{status:"copyright"},
  coords:{F:-70,D:45,E:25,C:25,M:10}, tags:["everyday-life","group-scene","gesture"] },
{ id:"nude-descending-a-staircase-no-2", tier:2, title:"Nude Descending a Staircase, No. 2", artistId:"marcel-duchamp",
  year:{display:"1912",sort:1912}, movements:["dada","cubism"], techniques:["oil-painting","mixed-media"], nation:"france",
  museum:{id:"philadelphia-museum-of-art",name:"Philadelphia Museum of Art",city:"Philadelphia"},
  image:{status:"copyright"},
  coords:{F:10,D:55,E:85,C:75,M:15}, tags:["nude","geometry","gesture"] },
{ id:"at-the-dressing-table", tier:2, title:"At the Dressing-Table (Self-Portrait)", artistId:"zinaida-serebriakova",
  year:{display:"1909",sort:1909}, movements:["realism","impressionism"], techniques:["oil-painting","pastel"], nation:"russia",
  museum:{id:"tretyakov",name:"Tretyakov Gallery",city:"Moscow"},
  image:{status:"copyright"},
  coords:{F:-90,D:-40,E:10,C:-40,M:-45}, tags:["self-portrait","tender","interior"] },
{ id:"cyclist-goncharova", tier:2, title:"Cyclist", artistId:"natalia-goncharova",
  year:{display:"1913",sort:1913}, movements:["rayonism","abstract-art","expressionism"], techniques:["oil-painting","flat-color"], nation:"russia",
  museum:{id:"russian-museum",name:"State Russian Museum",city:"St Petersburg"},
  image:{status:"copyright"},
  coords:{F:0,D:70,E:80,C:40,M:10}, tags:["gesture","pattern","everyday-life"] },
{ id:"panorama-of-mount-lu", tier:2, title:"Panorama of Mount Lu", artistId:"zhang-daqian",
  year:{display:"1981–83",sort:1981}, movements:["literati-painting","abstract-art"], techniques:["ink-wash","splashed-ink"], nation:"china",
  image:{status:"copyright"},
  coords:{F:20,D:30,E:55,C:30,M:95}, tags:["landscape","blue","monumental-scale"] },
{ id:"tree-and-two-women", tier:2, title:"Tree and Two Women", artistId:"park-soo-keun",
  year:{display:"1962",sort:1962}, movements:["realism","naive-art"], techniques:["oil-painting","impasto"], nation:"korea",
  image:{status:"copyright"},
  coords:{F:-50,D:-45,E:35,C:10,M:-20}, tags:["texture","quiet","everyday-life"] },
{ id:"between-the-spider-and-the-lamp", tier:2, title:"Between the Spider and the Lamp", artistId:"mf-husain",
  year:{display:"1956",sort:1956}, movements:["modernism","expressionism"], techniques:["oil-painting","acrylic-painting"], nation:"india",
  image:{status:"copyright"},
  coords:{F:-35,D:30,E:55,C:55,M:25}, tags:["flatness","unsettling","red"] },
{ id:"1957-d-no-1", tier:2, title:"1957-D No. 1", artistId:"clyfford-still",
  year:{display:"1957",sort:1957}, movements:["abstract-expressionism","color-field"], techniques:["oil-painting","palette-knife"], nation:"usa",
  image:{status:"copyright"},
  coords:{F:95,D:55,E:65,C:45,M:90}, tags:["texture","monumental-scale","monochrome"] },
{ id:"migrating-birds-lewis", tier:2, title:"Migrating Birds", artistId:"norman-lewis",
  year:{display:"1953",sort:1953}, movements:["abstract-expressionism"], techniques:["oil-painting","gestural-abstraction"], nation:"usa",
  image:{status:"copyright"},
  coords:{F:70,D:10,E:55,C:40,M:20}, tags:["animal","pattern","monochrome"] },
{ id:"beta-zeta-louis", tier:2, title:"Beta Zeta", artistId:"morris-louis",
  year:{display:"1960–61",sort:1960}, movements:["color-field","washington-color-school"], techniques:["acrylic-painting","soak-stain"], nation:"usa",
  image:{status:"copyright"},
  coords:{F:95,D:-20,E:65,C:40,M:70}, tags:["pattern","flatness","monumental-scale"] },
{ id:"homage-to-the-square-apparition", tier:2, title:"Homage to the Square: Apparition", artistId:"josef-albers",
  year:{display:"1959",sort:1959}, movements:["abstract-art","op-art","minimalism","bauhaus"], techniques:["oil-painting","flat-color"], nation:"germany",
  image:{status:"copyright"},
  coords:{F:95,D:-60,E:50,C:80,M:-20}, tags:["geometry","flatness","quiet"] },
{ id:"echo-of-a-scream-siqueiros", tier:2, title:"Echo of a Scream", artistId:"david-alfaro-siqueiros",
  year:{display:"1937",sort:1937}, movements:["muralism"], techniques:["fresco","oil-painting"], nation:"mexico",
  image:{status:"copyright"},
  coords:{F:-50,D:90,E:65,C:50,M:40}, tags:["unsettling","mourning","storm"] },
{ id:"sun-berger", tier:2, title:"Sun (competition painting)", artistId:"aliye-berger",
  year:{display:"1954",sort:1954}, movements:["expressionism"], techniques:["printmaking"], nation:"turkey",
  image:{status:"copyright"},
  coords:{F:80,D:40,E:55,C:25,M:30}, tags:["golden","pattern","ecstatic"] },
{ id:"white-sun-boeck", tier:2, title:"White Sun", artistId:"felix-de-boeck",
  year:{display:"1921",sort:1921}, movements:["abstract-art","constructivism"], techniques:["oil-painting","flat-color"], nation:"belgium",
  image:{status:"copyright"},
  coords:{F:85,D:10,E:70,C:55,M:20}, tags:["geometry","quiet","flatness"] },
{ id:"houses-at-l-estaque", tier:2, title:"Houses at L'Estaque", artistId:"georges-braque",
  year:{display:"1908",sort:1908}, movements:["cubism","fauvism"], techniques:["oil-painting","collage"], nation:"france",
  museum:{id:"lam-lille",name:"LaM — Lille Métropole Museum of Modern Art",city:"Villeneuve-d'Ascq"},
  image:{status:"copyright"},
  coords:{F:-20,D:-10,E:75,C:55,M:10}, tags:["landscape","geometry","flatness"] },
{ id:"i-and-the-village-chagall", tier:2, title:"I and the Village", artistId:"marc-chagall",
  year:{display:"1911",sort:1911}, movements:["expressionism","surrealism"], techniques:["oil-painting","watercolor"], nation:"belarus",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"},
  image:{status:"copyright"},
  coords:{F:-40,D:35,E:70,C:40,M:20}, tags:["animal","fever-dream","pattern"] },
{ id:"the-song-of-love-chirico", tier:2, title:"The Song of Love", artistId:"giorgio-de-chirico",
  year:{display:"1914",sort:1914}, movements:["metaphysical-painting","surrealism"], techniques:["oil-painting","tempera"], nation:"italy",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"},
  image:{status:"copyright"},
  coords:{F:-45,D:-10,E:70,C:65,M:20}, tags:["unsettling","fever-dream","still-life"] },
{ id:"the-treachery-of-images-magritte", tier:2, title:"The Treachery of Images (Ceci n'est pas une pipe)", artistId:"rene-magritte",
  year:{display:"1929",sort:1929}, movements:["surrealism"], techniques:["oil-painting","glazing"], nation:"belgium",
  museum:{id:"lacma",name:"Los Angeles County Museum of Art",city:"Los Angeles"},
  image:{status:"copyright"},
  coords:{F:-70,D:-50,E:60,C:95,M:-30}, tags:["still-life","playful","flatness"] },
{ id:"the-farm-miro", tier:2, title:"The Farm", artistId:"joan-miro",
  year:{display:"1921–22",sort:1921}, movements:["surrealism","abstract-art"], techniques:["oil-painting","automatism"], nation:"spain",
  museum:{id:"national-gallery-dc",name:"National Gallery of Art",city:"Washington, D.C."},
  image:{status:"copyright"},
  coords:{F:-50,D:-20,E:45,C:30,M:25}, tags:["landscape","pattern","everyday-life"] },
{ id:"the-elephant-celebes-ernst", tier:2, title:"The Elephant Celebes", artistId:"max-ernst",
  year:{display:"1921",sort:1921}, movements:["dada","surrealism"], techniques:["oil-painting","collage"], nation:"germany",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"},
  image:{status:"copyright"},
  coords:{F:-40,D:40,E:75,C:55,M:35}, tags:["unsettling","fever-dream","animal"] },
{ id:"self-portrait-in-a-green-bugatti", tier:2, title:"Self-Portrait in a Green Bugatti", artistId:"tamara-de-lempicka",
  year:{display:"1929",sort:1929}, movements:["art-deco","cubism"], techniques:["oil-painting","glazing"], nation:"poland",
  image:{status:"copyright"},
  coords:{F:-80,D:15,E:35,C:-20,M:-20}, tags:["self-portrait","theatrical","flatness"] },
{ id:"detroit-industry-murals", tier:2, title:"Detroit Industry Murals", artistId:"diego-rivera",
  year:{display:"1932–33",sort:1932}, movements:["muralism","cubism"], techniques:["fresco","oil-painting"], nation:"mexico",
  museum:{id:"detroit-institute-of-arts",name:"Detroit Institute of Arts",city:"Detroit"},
  image:{status:"copyright"},
  coords:{F:-60,D:55,E:30,C:45,M:100}, tags:["historical","group-scene","monumental-scale"] },
{ id:"jimson-weed-white-flower-no-1", tier:2, title:"Jimson Weed / White Flower No. 1", artistId:"georgia-okeeffe",
  year:{display:"1932",sort:1932}, movements:["american-modernism"], techniques:["oil-painting","watercolor"], nation:"usa",
  image:{status:"copyright"},
  coords:{F:-15,D:-40,E:40,C:10,M:70}, tags:["still-life","quiet","monumental-scale"] },
{ id:"nighthawks-hopper", tier:2, title:"Nighthawks", artistId:"edward-hopper",
  year:{display:"1942",sort:1942}, movements:["american-realism"], techniques:["oil-painting","watercolor"], nation:"usa",
  museum:{id:"art-institute-chicago",name:"The Art Institute of Chicago",city:"Chicago"},
  image:{status:"copyright"},
  coords:{F:-85,D:-35,E:15,C:15,M:0}, tags:["nocturne","lonely","everyday-life"] },
{ id:"the-migration-series-lawrence", tier:2, title:"The Migration Series", artistId:"jacob-lawrence",
  year:{display:"1940–41",sort:1940}, movements:["harlem-renaissance"], techniques:["tempera","watercolor"], nation:"usa",
  image:{status:"copyright"},
  coords:{F:-45,D:45,E:45,C:55,M:40}, tags:["historical","flatness","group-scene"] },
{ id:"the-seasons-krasner", tier:2, title:"The Seasons", artistId:"lee-krasner",
  year:{display:"1957",sort:1957}, movements:["abstract-expressionism","action-painting"], techniques:["oil-painting","collage"], nation:"usa",
  image:{status:"copyright"},
  coords:{F:75,D:65,E:65,C:15,M:80}, tags:["gesture","monumental-scale","ecstatic"] },
{ id:"woman-i-kooning", tier:2, title:"Woman I", artistId:"willem-de-kooning",
  year:{display:"1950–52",sort:1950}, movements:["abstract-expressionism","action-painting"], techniques:["oil-painting","gestural-abstraction"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"},
  image:{status:"copyright"},
  coords:{F:-25,D:85,E:75,C:25,M:40}, tags:["nude","gesture","unsettling"] },
{ id:"mountains-and-sea-frankenthaler", tier:2, title:"Mountains and Sea", artistId:"helen-frankenthaler",
  year:{display:"1952",sort:1952}, movements:["abstract-expressionism","color-field"], techniques:["soak-stain","gestural-abstraction"], nation:"usa",
  museum:{id:"national-gallery-dc",name:"National Gallery of Art",city:"Washington, D.C."},
  image:{status:"copyright"},
  coords:{F:65,D:0,E:75,C:25,M:65}, tags:["landscape","pastel","flatness"] },
{ id:"hemlock-mitchell", tier:2, title:"Hemlock", artistId:"joan-mitchell",
  year:{display:"1956",sort:1956}, movements:["abstract-expressionism","action-painting"], techniques:["oil-painting","gestural-abstraction"], nation:"usa",
  museum:{id:"whitney",name:"Whitney Museum of American Art",city:"New York"},
  image:{status:"copyright"},
  coords:{F:80,D:60,E:60,C:15,M:50}, tags:["gesture","landscape","texture"] },
{ id:"three-studies-for-figures-at-the", tier:2, title:"Three Studies for Figures at the Base of a Crucifixion", artistId:"francis-bacon",
  year:{display:"1944",sort:1944}, movements:["expressionism","school-of-london"], techniques:["oil-painting","alla-prima"], nation:"britain",
  museum:{id:"tate-britain",name:"Tate Britain",city:"London"},
  image:{status:"copyright"},
  coords:{F:-40,D:95,E:75,C:40,M:10}, tags:["unsettling","red","mourning"] },
{ id:"benefits-supervisor-sleeping", tier:2, title:"Benefits Supervisor Sleeping", artistId:"lucian-freud",
  year:{display:"1995",sort:1995}, movements:["school-of-london","realism"], techniques:["oil-painting","impasto"], nation:"britain",
  museum:{id:"private-collection",name:"Private collection",city:null},
  image:{status:"copyright"},
  coords:{F:-95,D:10,E:20,C:-60,M:30}, tags:["nude","texture","lonely"] },
{ id:"whaam-lichtenstein", tier:2, title:"Whaam!", artistId:"roy-lichtenstein",
  year:{display:"1963",sort:1963}, movements:["pop-art"], techniques:["oil-painting","acrylic-painting"], nation:"usa",
  museum:{id:"tate-modern",name:"Tate Modern",city:"London"},
  image:{status:"copyright"},
  coords:{F:-55,D:85,E:65,C:70,M:40}, tags:["historical","flatness","playful"] },
{ id:"hollywood-africans-basquiat", tier:2, title:"Hollywood Africans", artistId:"jean-michel-basquiat",
  year:{display:"1983",sort:1983}, movements:["neo-expressionism","street-art"], techniques:["acrylic-painting","spray-paint"], nation:"usa",
  museum:{id:"whitney",name:"Whitney Museum of American Art",city:"New York"},
  image:{status:"copyright"},
  coords:{F:-20,D:60,E:80,C:75,M:20}, tags:["portrait","texture","playful"] },
{ id:"tuttomondo-haring", tier:2, title:"Tuttomondo", artistId:"keith-haring",
  year:{display:"1989",sort:1989}, movements:["street-art","pop-art"], techniques:["spray-paint","flat-color"], nation:"usa",
  image:{status:"copyright"},
  coords:{F:-20,D:55,E:55,C:35,M:90}, tags:["playful","pattern","monumental-scale"] },
{ id:"mona-lisa-age-twelve", tier:2, title:"Mona Lisa, Age Twelve", artistId:"fernando-botero",
  year:{display:"1959",sort:1959}, movements:["contemporary-art"], techniques:["oil-painting","pastel"], nation:"colombia",
  image:{status:"copyright"},
  coords:{F:-70,D:-25,E:40,C:55,M:10}, tags:["portrait","playful","flatness"] },
{ id:"flag-johns", tier:2, title:"Flag", artistId:"jasper-johns",
  year:{display:"1954–55",sort:1954}, movements:["neo-dada","pop-art"], techniques:["encaustic","oil-painting"], nation:"usa",
  museum:{id:"moma",name:"The Museum of Modern Art",city:"New York"},
  image:{status:"copyright"},
  coords:{F:25,D:-10,E:75,C:90,M:10}, tags:["flatness","texture","red"] },
{ id:"a-bigger-splash-hockney", tier:2, title:"A Bigger Splash", artistId:"david-hockney",
  year:{display:"1967",sort:1967}, movements:["pop-art","contemporary-art"], techniques:["acrylic-painting","oil-painting"], nation:"britain",
  museum:{id:"tate-britain",name:"Tate Britain",city:"London"},
  image:{status:"copyright"},
  coords:{F:-60,D:-40,E:45,C:40,M:10}, tags:["blue","quiet","flatness"] },
{ id:"betty-richter", tier:2, title:"Betty", artistId:"gerhard-richter",
  year:{display:"1988",sort:1988}, movements:["contemporary-art","abstract-art","postmodernism"], techniques:["oil-painting","squeegee"], nation:"germany",
  image:{status:"copyright"},
  coords:{F:-85,D:-10,E:45,C:55,M:-20}, tags:["portrait","quiet","red"] },
{ id:"infinity-nets-series", tier:2, title:"Infinity Nets series", artistId:"yayoi-kusama",
  year:{display:"1958–",sort:1958}, movements:["contemporary-art","pop-art"], techniques:["acrylic-painting","flat-color"], nation:"japan",
  image:{status:"copyright"},
  coords:{F:90,D:-10,E:75,C:60,M:60}, tags:["pattern","monochrome","texture"] },
{ id:"margarethe-kiefer", tier:2, title:"Margarethe", artistId:"anselm-kiefer",
  year:{display:"1981",sort:1981}, movements:["neo-expressionism","contemporary-art"], techniques:["oil-painting","impasto"], nation:"germany",
  image:{status:"copyright"},
  coords:{F:10,D:50,E:70,C:80,M:80}, tags:["mourning","texture","golden"] },
{ id:"the-painter-dumas", tier:2, title:"The Painter", artistId:"marlene-dumas",
  year:{display:"1994",sort:1994}, movements:["contemporary-art"], techniques:["oil-painting","watercolor"], nation:"south-africa",
  image:{status:"copyright"},
  coords:{F:-60,D:40,E:55,C:50,M:30}, tags:["portrait","unsettling","nude"] },
{ id:"past-times-marshall", tier:2, title:"Past Times", artistId:"kerry-james-marshall",
  year:{display:"1997",sort:1997}, movements:["contemporary-art"], techniques:["acrylic-painting","collage"], nation:"usa",
  image:{status:"copyright"},
  coords:{F:-65,D:-10,E:40,C:70,M:60}, tags:["everyday-life","landscape","group-scene"] },
{ id:"stadia-ii-mehretu", tier:2, title:"Stadia II", artistId:"julie-mehretu",
  year:{display:"2004",sort:2004}, movements:["contemporary-art","abstract-art"], techniques:["acrylic-painting","mixed-media"], nation:"ethiopia",
  image:{status:"copyright"},
  coords:{F:75,D:65,E:85,C:70,M:75}, tags:["geometry","pattern","monumental-scale"] },
{ id:"727-murakami", tier:2, title:"727", artistId:"takashi-murakami",
  year:{display:"1996",sort:1996}, movements:["superflat","pop-art","contemporary-art","postmodernism","nihonga"], techniques:["acrylic-painting","flat-color"], nation:"japan",
  image:{status:"copyright"},
  coords:{F:-10,D:55,E:75,C:60,M:60}, tags:["playful","flatness","blue"] },
{ id:"girl-with-balloon-banksy", tier:2, title:"Girl with Balloon", artistId:"banksy",
  year:{display:"2002",sort:2002}, movements:["street-art","contemporary-art"], techniques:["spray-paint","flat-color"], nation:"britain",
  image:{status:"copyright"},
  coords:{F:-60,D:0,E:60,C:80,M:-20}, tags:["tender","monochrome","red"] },
{ id:"i-refuse-to-be-invisible", tier:2, title:"I Refuse to be Invisible", artistId:"njideka-akunyili-crosby",
  year:{display:"2010",sort:2010}, movements:["contemporary-art"], techniques:["acrylic-painting","collage"], nation:"nigeria",
  image:{status:"copyright"},
  coords:{F:-75,D:-25,E:65,C:60,M:0}, tags:["portrait","interior","pattern"] }
]);
