/* PIGMENT — artwork catalog 1 (ARTWORK_SCHEMA v1).
   17 Tier 1 records (full pages) + 3 Tier 2 thin pages.
   Tier 1: explicit coords (−100…+100, TASTE_MATH scale), 50–80 word description,
   exactly 3 "notice" bullets, ≥3 vocabulary tags, authored related[].
   `worksKey` links back to the artist's works array when titles differ. */
window.CATALOG = (window.CATALOG || []).concat([

{ id:"the-calling-of-saint-matthew", tier:1,
  title:"The Calling of Saint Matthew", worksKey:"The Calling of St Matthew",
  artistId:"caravaggio", year:{ display:"1599–1600", sort:1599 },
  movements:["baroque"], techniques:["oil-painting","tenebrism","chiaroscuro"], nation:"italy",
  museum:{ id:"san-luigi-dei-francesi", name:"Contarelli Chapel, San Luigi dei Francesi", city:"Rome" },
  dims:"322 × 340 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Caravaggio_%E2%80%94_The_Calling_of_Saint_Matthew.jpg/500px-Caravaggio_%E2%80%94_The_Calling_of_Saint_Matthew.jpg",
          page:"https://en.wikipedia.org/wiki/The_Calling_of_Saint_Matthew", status:"pd" },
  coords:{ F:-85, D:92, E:-30, C:-20, M:55 }, coordsSource:"override",
  description:"A tax collector's back room, men counting coins in their Sunday feathers — and a shaft of light cuts the gloom like an accusation. Christ, half-hidden at the right edge, points; Matthew points at himself: who, me? Caravaggio staged a miracle as a police raid, and four centuries of dramatic lighting, from Rembrandt to cinema, walked in through this window.",
  notice:["Christ's languid hand quotes Adam's from the Sistine ceiling",
          "The light enters where no window exists",
          "Which man is Matthew? Scholars still point at two"],
  tags:["sacred","group-scene","interior","candlelit","chiaroscuro","theatrical"],
  related:["judith-slaying-holofernes","the-third-of-may-1808"] },

{ id:"judith-slaying-holofernes", tier:1,
  title:"Judith Slaying Holofernes",
  artistId:"artemisia-gentileschi", year:{ display:"c. 1620", sort:1620 },
  movements:["baroque"], techniques:["oil-painting","tenebrism"], nation:"italy",
  museum:{ id:"uffizi", name:"Gallerie degli Uffizi", city:"Florence" },
  dims:"199 × 162.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Judit_decapitando_a_Holofernes%2C_por_Artemisia_Gentileschi.jpg/500px-Judit_decapitando_a_Holofernes%2C_por_Artemisia_Gentileschi.jpg",
          page:"https://en.wikipedia.org/wiki/Judith_beheading_Holofernes", status:"pd" },
  coords:{ F:-88, D:97, E:-25, C:-15, M:40 }, coordsSource:"override",
  description:"Most painters gave Judith a delicate shudder. Artemisia gave her leverage. Sleeves rolled, brow set, the widow of Bethulia braces her weight against the general's skull while her maid pins him down — teamwork, not theatre. The blood arcs with hydraulic honesty. Grand dukes reportedly found it too disturbing to hang; modern viewers find it the most alive painting in the room.",
  notice:["Judith's forearms carry real anatomical strain — this is labour",
          "Blood sprays in arcs, not decorous trickles",
          "The maid is young and strong — a co-conspirator, not a witness"],
  tags:["sacred","group-scene","unsettling","theatrical","chiaroscuro","night"],
  related:["the-calling-of-saint-matthew","saturn-devouring-his-son"] },

{ id:"the-starry-night", tier:1,
  title:"The Starry Night",
  artistId:"vincent-van-gogh", year:{ display:"1889", sort:1889 },
  movements:["post-impressionism"], techniques:["oil-painting","impasto"], nation:"netherlands",
  museum:{ id:"moma", name:"The Museum of Modern Art", city:"New York" },
  dims:"73.7 × 92.1 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/500px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/The_Starry_Night", status:"pd" },
  coords:{ F:-45, D:75, E:55, C:-35, M:20 }, coordsSource:"override",
  description:"Painted from the window of an asylum at Saint-Rémy — partly from sight, mostly from need — the night sky churns like water while the village below sleeps through it. Eleven stars, a spiral galaxy nobody had photographed yet, and a cypress like a green flame connecting earth to heaven. Van Gogh thought it a failure. It became the most beloved night in art.",
  notice:["The village is invented — that spire is more Dutch than French",
          "One spiral matches drawings of galaxies published years earlier",
          "The paint is thick enough to cast its own shadows"],
  tags:["landscape","nocturne","blue","texture","gesture","lonely"],
  related:["the-scream","composition-vii","impression-sunrise"] },

{ id:"sunflowers", tier:1,
  title:"Sunflowers",
  artistId:"vincent-van-gogh", year:{ display:"1888", sort:1888 },
  movements:["post-impressionism"], techniques:["oil-painting","impasto"], nation:"netherlands",
  museum:{ id:"national-gallery-london", name:"The National Gallery", city:"London" },
  dims:"92.1 × 73 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Vincent_Willem_van_Gogh_127.jpg/500px-Vincent_Willem_van_Gogh_127.jpg",
          page:"https://en.wikipedia.org/wiki/Sunflowers_(Van_Gogh_series)", status:"pd" },
  coords:{ F:-60, D:15, E:35, C:-60, M:-40 }, coordsSource:"override",
  description:"Yellow on yellow on yellow — a still life with the palette of a dare. Van Gogh painted these to decorate Gauguin's bedroom in the Yellow House, working fast before the cut flowers drooped; some heads are fresh, some already dying, and he kept both. He signed it 'Vincent' on the vase, like a friend, not a monument. The monument happened anyway.",
  notice:["Count the yellows — there are at least three different ones fighting",
          "Some blooms are seed-heads already: the bouquet is aging in real time",
          "The signature sits on the vase, glaze-blue and casual"],
  tags:["still-life","golden","texture","tender","would-hang"],
  related:["the-starry-night","impression-sunrise"] },

{ id:"girl-with-a-pearl-earring", tier:1,
  title:"Girl with a Pearl Earring",
  artistId:"johannes-vermeer", year:{ display:"c. 1665", sort:1665 },
  movements:["dutch-golden-age"], techniques:["oil-painting","glazing"], nation:"netherlands",
  museum:{ id:"mauritshuis", name:"Mauritshuis", city:"The Hague" },
  dims:"44.5 × 39 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/500px-1665_Girl_with_a_Pearl_Earring.jpg",
          page:"https://en.wikipedia.org/wiki/Girl_with_a_Pearl_Earring", status:"pd" },
  coords:{ F:-90, D:-35, E:-35, C:-55, M:-75 }, coordsSource:"override",
  description:"Not a portrait — a 'tronie', a study of a type, a face turning toward you or away, forever mid-decision. The background was once deep green, now aged to black, which only sharpens the trick: she exists nowhere, lit by nothing, looking at you specifically. The famous pearl is five or six strokes of paint and probably isn't even a pearl.",
  notice:["The 'pearl' has no hook, no ear contact — it floats",
          "Her lips are parted just enough to be about to speak",
          "There are no eyebrows; nobody notices until told"],
  tags:["portrait","quiet","tender","interior","would-hang"],
  related:["the-milkmaid","mona-lisa"] },

{ id:"the-milkmaid", tier:2,
  title:"The Milkmaid",
  artistId:"johannes-vermeer", year:{ display:"c. 1658–60", sort:1658 },
  movements:["dutch-golden-age"], techniques:["oil-painting"], nation:"netherlands",
  museum:{ id:"rijksmuseum", name:"Rijksmuseum", city:"Amsterdam" },
  dims:"45.5 × 41 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.png/500px-Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.png",
          page:"https://en.wikipedia.org/wiki/The_Milkmaid_(Vermeer)", status:"pd" },
  tags:["interior","quiet","everyday-life"] },

{ id:"las-meninas", tier:1,
  title:"Las Meninas",
  artistId:"diego-velazquez", year:{ display:"1656", sort:1656 },
  movements:["baroque"], techniques:["oil-painting","alla-prima"], nation:"spain",
  museum:{ id:"prado", name:"Museo del Prado", city:"Madrid" },
  dims:"318 × 276 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg/500px-Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg",
          page:"https://en.wikipedia.org/wiki/Las_Meninas", status:"pd" },
  coords:{ F:-88, D:15, E:10, C:15, M:60 }, coordsSource:"override",
  description:"A princess, her maids, a dwarf, a dog, a painter — and in the mirror at the back, the king and queen standing exactly where you are standing. Velázquez painted the act of being painted, then stepped into it himself, brush raised. Art history's favorite riddle about looking: three and a half centuries in, nobody agrees who this picture is actually of.",
  notice:["Find the mirror: the royal couple occupies your spot",
          "Velázquez's red cross was added later — legend says by the king",
          "The dog is the only one refusing to perform"],
  tags:["group-scene","interior","portrait","monumental-scale","historical"],
  related:["the-arnolfini-portrait","mona-lisa"] },

{ id:"the-garden-of-earthly-delights", tier:1,
  title:"The Garden of Earthly Delights",
  artistId:"hieronymus-bosch", year:{ display:"c. 1490–1510", sort:1490 },
  movements:["northern-renaissance"], techniques:["oil-painting"], nation:"netherlands",
  museum:{ id:"prado", name:"Museo del Prado", city:"Madrid" },
  dims:"205.5 × 384.9 cm (open)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg/500px-The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg",
          page:"https://commons.wikimedia.org/wiki/File:The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg", status:"pd" },
  coords:{ F:-70, D:70, E:65, C:45, M:80 }, coordsSource:"override",
  description:"Three panels, one slide: Eden on the left, a naked carnival of strawberry-eating humanity in the middle, and on the right a hell where musical instruments become torture devices and a bird-headed thing eats sinners whole. Painted five centuries before Surrealism, owned by the most Catholic king in Europe, and still the strangest object in any museum that holds it.",
  notice:["The hell panel contains music written on a sinner's backside",
          "Closed, the shutters show the world on day three — in grey",
          "Nobody in the centre panel is older than about twenty-five"],
  tags:["sacred","fever-dream","unsettling","group-scene","mythological","monumental-scale"],
  related:["saturn-devouring-his-son","the-scream"] },

{ id:"the-great-wave-off-kanagawa", tier:1,
  title:"The Great Wave off Kanagawa",
  artistId:"katsushika-hokusai", year:{ display:"c. 1831", sort:1831 },
  movements:["ukiyo-e"], techniques:["woodblock"], nation:"japan",
  museum:{ id:"met", name:"The Metropolitan Museum of Art (among many impressions)", city:"New York" },
  dims:"25.7 × 37.9 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tsunami_by_hokusai_19th_century.jpg/500px-Tsunami_by_hokusai_19th_century.jpg",
          page:"https://en.wikipedia.org/wiki/The_Great_Wave_off_Kanagawa", status:"pd" },
  coords:{ F:-55, D:65, E:20, C:-30, M:10 }, coordsSource:"override",
  description:"The wave rears like a claw; three boats of oarsmen flatten themselves into the troughs; and far away, tiny and eternal, Fuji sits — the only thing in the picture not moving. Printed in the thousands and sold for the price of noodles, made with imported Prussian blue, it became the single most reproduced image in art. The mountain always wins.",
  notice:["Fuji is smaller than the foam — that's the whole philosophy",
          "The spray dissolves into snowflakes falling toward the mountain",
          "This is a print: thousands exist, no two aged alike"],
  tags:["seascape","storm","blue","pattern","theatrical"],
  related:["the-starry-night","impression-sunrise"] },

{ id:"impression-sunrise", tier:1,
  title:"Impression, Sunrise",
  artistId:"claude-monet", year:{ display:"1872", sort:1872 },
  movements:["impressionism"], techniques:["oil-painting","broken-color"], nation:"france",
  museum:{ id:"musee-marmottan", name:"Musée Marmottan Monet", city:"Paris" },
  dims:"48 × 63 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/500px-Monet_-_Impression%2C_Sunrise.jpg",
          page:"https://en.wikipedia.org/wiki/Impression%2C_Sunrise", status:"pd" },
  coords:{ F:-35, D:-25, E:45, C:-65, M:-30 }, coordsSource:"override",
  description:"Le Havre harbour at dawn, sketched in under an hour: an orange sun, its shivering reflection, two rowboats, and a forest of masts dissolved in blue mist. A critic sneered that wallpaper was more finished and coined 'Impressionism' from the title as an insult. The insult became the most successful brand name in art history. The sun, measured by luminance, is no brighter than the sky — it only insists.",
  notice:["Cover the orange sun with a thumb — the painting nearly vanishes",
          "Two strokes make a rowboat; your eye does the rest",
          "The 'finished' ships are ghosts; the sketch is the subject"],
  tags:["seascape","fog","golden","quiet","everyday-life"],
  related:["the-great-wave-off-kanagawa","sunflowers"] },

{ id:"water-lilies-grandes-decorations", tier:2,
  title:"Water Lilies (Grandes Décorations)", worksKey:"Water Lilies (Grandes Décorations)",
  artistId:"claude-monet", year:{ display:"c. 1915–26", sort:1915 },
  movements:["impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"orangerie", name:"Musée de l'Orangerie", city:"Paris" },
  dims:"200 × 600 cm (panel)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Claude_Monet_-_The_Water_Lilies_-_Setting_Sun_-_Google_Art_Project.jpg/500px-Claude_Monet_-_The_Water_Lilies_-_Setting_Sun_-_Google_Art_Project.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Claude_Monet_-_The_Water_Lilies_-_Setting_Sun_-_Google_Art_Project.jpg", status:"pd" },
  tags:["landscape","quiet","monumental-scale"] },

{ id:"the-kiss", tier:1,
  title:"The Kiss",
  artistId:"gustav-klimt", year:{ display:"1907–08", sort:1907 },
  movements:["vienna-secession","art-nouveau"], techniques:["oil-painting","gold-leaf"], nation:"austria",
  museum:{ id:"belvedere", name:"Österreichische Galerie Belvedere", city:"Vienna" },
  dims:"180 × 180 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg/500px-The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
          page:"https://en.wikipedia.org/wiki/The_Kiss_(Klimt)", status:"pd" },
  coords:{ F:-55, D:20, E:30, C:-50, M:10 }, coordsSource:"override",
  description:"Two lovers dissolve into one golden shape at the edge of a flowered cliff — his robe patterned in hard black rectangles, hers in soft circles, desire diagrammed in geometry. Klimt, a goldsmith's son, used real gold leaf, making the painting glow like the Byzantine icons it secretly is. Austria bought it straight off the easel, unfinished. Nobody has ever asked for a refund.",
  notice:["His pattern is rectangles, hers is circles — geometry as gender",
          "Her toes grip the cliff edge; the ecstasy has a precipice",
          "The gold is real leaf: the painting emits, not reflects"],
  tags:["portrait","golden","tender","pattern","would-hang"],
  related:["girl-with-a-pearl-earring","the-trinity"] },

{ id:"the-scream", tier:1,
  title:"The Scream",
  artistId:"edvard-munch", year:{ display:"1893", sort:1893 },
  movements:["expressionism","symbolism"], techniques:["oil-painting","tempera","pastel"], nation:"norway",
  museum:{ id:"nasjonalmuseet-oslo", name:"Nasjonalmuseet", city:"Oslo" },
  dims:"91 × 73.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/500px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg",
          page:"https://en.wikipedia.org/wiki/The_Scream", status:"pd" },
  coords:{ F:-55, D:95, E:60, C:10, M:-10 }, coordsSource:"override",
  description:"Munch was walking at sunset when, he wrote, he sensed 'a scream passing through nature' — and painted the sensation, not the scene. The figure isn't screaming; it's hearing the scream and holding its skull shut. The sky's blood-red waves may echo the Krakatoa sunsets that reached Norway. Painted on cheap cardboard, it became the modern face of anxiety — and a hidden pencil note calls its maker mad.",
  notice:["The two figures behind keep walking — that's the horror",
          "The fjord's lines bend to match the skull's curve",
          "Look close: it's cardboard, and the paint is thin as panic"],
  tags:["landscape","unsettling","storm","red","lonely"],
  related:["the-starry-night","saturn-devouring-his-son"] },

{ id:"composition-vii", tier:1,
  title:"Composition VII",
  artistId:"wassily-kandinsky", year:{ display:"1913", sort:1913 },
  movements:["abstract-art","der-blaue-reiter"], techniques:["oil-painting"], nation:"russia",
  museum:{ id:"tretyakov", name:"Tretyakov Gallery", city:"Moscow" },
  dims:"200.6 × 302.2 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Composition_VII_-_Wassily_Kandinsky%2C_GAC.jpg/500px-Composition_VII_-_Wassily_Kandinsky%2C_GAC.jpg",
          page:"https://en.wikipedia.org/wiki/Composition_VII", status:"pd" },
  coords:{ F:85, D:80, E:85, C:20, M:45 }, coordsSource:"override",
  description:"Over thirty studies, then four days of painting: a three-metre apocalypse with no objects left in it — only collisions of colour that Kandinsky, who heard hues as sounds, composed like a symphony about the Flood and the Resurrection at once. Stand close and it's chaos; step back and a vortex organizes everything around a small blue-violet centre, like an eye of a storm that believes in heaven.",
  notice:["Find the dark oval left of centre — everything orbits it",
          "No up or down survives; the canvas works rotated (he checked)",
          "Thirty-plus studies exist for a painting of 'improvisation'"],
  tags:["gesture","pattern","storm","fever-dream","monumental-scale"],
  related:["black-square","the-starry-night"] },

{ id:"black-square", tier:1,
  title:"Black Square",
  artistId:"kazimir-malevich", year:{ display:"1915", sort:1915 },
  movements:["suprematism"], techniques:["oil-painting"], nation:"ukraine",
  museum:{ id:"tretyakov", name:"Tretyakov Gallery", city:"Moscow" },
  dims:"79.5 × 79.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Kazimir_Malevich%2C_1915%2C_Black_Suprematic_Square%2C_oil_on_linen_canvas%2C_79.5_x_79.5_cm%2C_Tretyakov_Gallery%2C_Moscow.jpg/500px-Kazimir_Malevich%2C_1915%2C_Black_Suprematic_Square%2C_oil_on_linen_canvas%2C_79.5_x_79.5_cm%2C_Tretyakov_Gallery%2C_Moscow.jpg",
          page:"https://en.wikipedia.org/wiki/Black_Square", status:"pd" },
  coords:{ F:100, D:-20, E:100, C:90, M:-20 }, coordsSource:"override",
  description:"A black square on a white ground — and, in 1915 Petrograd, the loudest painting in the world. Malevich hung it across the room's top corner, the place reserved for icons, announcing painting reduced 'to the zero of form.' It is not even a perfect square, and the black has cracked to reveal colours underneath: the void, it turns out, was painted over a picture.",
  notice:["It hung in the icon corner — a god replaced, not removed",
          "The edges are hand-drawn: no ruler touched the void",
          "Craquelure reveals an earlier colour composition beneath"],
  tags:["geometry","monochrome","flatness","pattern"],
  related:["composition-vii","the-trinity"] },

{ id:"the-trinity", tier:1,
  title:"The Trinity",
  artistId:"andrei-rublev", year:{ display:"c. 1425–27", sort:1425 },
  movements:["icon-painting"], techniques:["tempera","gold-leaf"], nation:"russia",
  museum:{ id:"tretyakov", name:"Tretyakov Gallery (in church custody since 2023)", city:"Moscow" },
  dims:"142 × 114 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Andrey_Rublev_-_%D0%A1%D0%B2._%D0%A2%D1%80%D0%BE%D0%B8%D1%86%D0%B0_-_Google_Art_Project.jpg/960px-Andrey_Rublev_-_%D0%A1%D0%B2._%D0%A2%D1%80%D0%BE%D0%B8%D1%86%D0%B0_-_Google_Art_Project.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Andrey_Rublev_-_%D0%A1%D0%B2._%D0%A2%D1%80%D0%BE%D0%B8%D1%86%D0%B0_-_Google_Art_Project.jpg", status:"pd" },
  coords:{ F:-60, D:-60, E:-40, C:25, M:10 }, coordsSource:"override",
  description:"Three angels — Abraham's mysterious visitors, read as the Trinity — sit around a table bearing a single cup, their heads inclined in a conversation conducted entirely in silence. The composition is a circle you feel rather than see; the fourth place at the table faces you. Six centuries of Orthodox theology declared it the icon all icons should imitate. Its calm has outlasted empires.",
  notice:["The three staffs are identical: no angel outranks another",
          "An invisible circle joins them; the cup is its centre",
          "The empty side of the table is your seat"],
  tags:["sacred","quiet","golden","icon-corner","tender"],
  related:["black-square","the-kiss"] },

{ id:"saturn-devouring-his-son", tier:1,
  title:"Saturn Devouring His Son",
  artistId:"francisco-goya", year:{ display:"c. 1820–23", sort:1820 },
  movements:["romanticism"], techniques:["oil-painting"], nation:"spain",
  museum:{ id:"prado", name:"Museo del Prado", city:"Madrid" },
  dims:"143.5 × 81.4 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/500px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg",
          page:"https://en.wikipedia.org/wiki/Saturn_Devouring_His_Son", status:"pd" },
  coords:{ F:-70, D:98, E:40, C:10, M:-20 }, coordsSource:"override",
  description:"Goya painted this directly onto the dining-room wall of his farmhouse — for himself, for no one, never meant to be seen. The old god's eyes are not cruel; they are terrified, caught mid-atrocity like an animal in a lamp. Deaf, ill, and done with mankind, Goya made the darkest image in Western art and then ate his meals beneath it.",
  notice:["Saturn's eyes show terror, not appetite",
          "It was a mural in a dining room — dinner faced this",
          "The darkness isn't background; it's the whole world"],
  tags:["mythological","unsettling","night","monochrome","fever-dream"],
  related:["the-scream","judith-slaying-holofernes","the-third-of-may-1808"] },

{ id:"the-third-of-may-1808", tier:2,
  title:"The Third of May 1808",
  artistId:"francisco-goya", year:{ display:"1814", sort:1814 },
  movements:["romanticism"], techniques:["oil-painting"], nation:"spain",
  museum:{ id:"prado", name:"Museo del Prado", city:"Madrid" },
  dims:"268 × 347 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_thin_black_margin.jpg/500px-El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_thin_black_margin.jpg",
          page:"https://en.wikipedia.org/wiki/The_Third_of_May_1808", status:"pd" },
  tags:["historical","unsettling","night","candlelit"] },

{ id:"the-arnolfini-portrait", tier:1,
  title:"The Arnolfini Portrait",
  artistId:"jan-van-eyck", year:{ display:"1434", sort:1434 },
  movements:["early-netherlandish"], techniques:["oil-painting","glazing"], nation:"belgium",
  museum:{ id:"national-gallery-london", name:"The National Gallery", city:"London" },
  dims:"82.2 × 60 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/500px-Van_Eyck_-_Arnolfini_Portrait.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Van_Eyck_-_Arnolfini_Portrait.jpg", status:"pd" },
  coords:{ F:-92, D:-40, E:-20, C:-10, M:-70 }, coordsSource:"override",
  description:"A Bruges merchant and his wife stand in their bedroom among conspicuous possessions — oranges, a brass chandelier, a small indignant dog — while the convex mirror behind them reflects the entire room, two extra visitors included. Above it, in legal script: 'Jan van Eyck was here, 1434.' Wedding certificate, memorial, or flex? Six centuries of argument, zero resolution, one immortal dog.",
  notice:["The mirror reflects two visitors — one may be the painter",
          "The graffiti above it is a signature posing as testimony",
          "Every object is arguing something: oranges, clogs, one candle"],
  tags:["portrait","interior","quiet","everyday-life","pattern"],
  related:["las-meninas","girl-with-a-pearl-earring"] },

{ id:"mona-lisa", tier:1,
  title:"Mona Lisa",
  artistId:"leonardo-da-vinci", year:{ display:"c. 1503–19", sort:1503 },
  movements:["high-renaissance"], techniques:["oil-painting","sfumato"], nation:"italy",
  museum:{ id:"louvre", name:"Musée du Louvre", city:"Paris" },
  dims:"77 × 53 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/500px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
          page:"https://en.wikipedia.org/wiki/Mona_Lisa", status:"pd" },
  coords:{ F:-85, D:-45, E:-15, C:-25, M:-55 }, coordsSource:"override",
  description:"Leonardo carried her for sixteen years, adding glaze upon glaze until the corners of her mouth and eyes dissolved into smoke — sfumato — precisely where a smile lives or dies. That's the trick: your eye finishes the expression, so she responds to you. A merchant's wife, never delivered to the client, stolen in 1911, and now viewed for an average of fifteen seconds through glass.",
  notice:["The smile changes if you stare at her eyes instead",
          "The horizon on the left sits lower than the right",
          "No eyebrows — fashion, over-cleaning, or both; the debate lives"],
  tags:["portrait","quiet","tender","landscape"],
  related:["girl-with-a-pearl-earring","las-meninas"] },

{ id:"the-naked-maja", tier:1,
  title:"The Naked Maja",
  artistId:"francisco-goya", year:{ display:"c. 1797–1800", sort:1797 },
  movements:["romanticism"], techniques:["oil-painting"], nation:"spain",
  museum:{ id:"prado", name:"Museo del Prado", city:"Madrid" },
  dims:"97 × 190 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Goya_Maja_naga2.jpg/500px-Goya_Maja_naga2.jpg",
          page:"https://en.wikipedia.org/wiki/La_maja_desnuda", status:"pd" },
  coords:{ F:-90, D:5, E:25, C:-70, M:-30 }, coordsSource:"override",
  description:"No goddess, no myth, no fig-leaf of allegory — just a woman on a divan, arms behind her head, meeting your stare before you've finished arriving. Painted for a private cabinet (likely Godoy's, who kept a clothed twin to swap over it for visitors), it earned Goya an Inquisition summons in 1815. He never named who she is. Two centuries on, she still looks less embarrassed than you do.",
  notice:["Her gaze lands first — the body is the second thing you see",
          "Reportedly the first Western nude to show actual body hair",
          "The satin gets looser, faster brushwork than her skin does"],
  tags:["nude","portrait","interior","tender"],
  related:["the-kiss","girl-with-a-pearl-earring"] },

/* ——— The Munch wing — first exhibition-grade artist gallery (arc pilot) ——— */

{ id:"the-sick-child", tier:1,
  title:"The Sick Child", worksKey:"The Sick Child",
  artistId:"edvard-munch", year:{ display:"1885–86", sort:1886 },
  movements:["expressionism","symbolism"], techniques:["oil-painting"], nation:"norway",
  museum:{ id:"nasjonalmuseet-oslo", name:"Nasjonalmuseet", city:"Oslo" },
  dims:"120 × 118.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Munch_Det_Syke_Barn_1885-86.jpg/500px-Munch_Det_Syke_Barn_1885-86.jpg",
          page:"https://en.wikipedia.org/wiki/The_Sick_Child_(Munch)", status:"pd" },
  coords:{ F:-70, D:45, E:45, C:-15, M:-75 }, coordsSource:"override",
  description:"Munch's sister Sophie died of tuberculosis at fifteen; a decade later he painted the sickroom back into existence — his aunt Karen bowed at the bedside, a hired model in Sophie's pillow. He scraped and repainted the canvas for a year until the surface looked as wounded as the memory. Critics at the 1886 Autumn Exhibition jeered at the 'half-rubbed-out sketch.' Munch never budged: most of what he later did, he said, was born in this picture.",
  notice:["The surface is scratched and scored — he attacked it with the brush's end",
          "The mother's head is bowed; it's the dying child who consoles",
          "The pillow dissolves toward halo — memory eating the detail"],
  tags:["interior","quiet","tender","unsettling"],
  related:["the-scream","the-third-of-may-1808"] },

{ id:"madonna-munch", tier:1,
  title:"Madonna", worksKey:"Madonna",
  artistId:"edvard-munch", year:{ display:"1894–95", sort:1894 },
  movements:["symbolism","expressionism"], techniques:["oil-painting"], nation:"norway",
  museum:{ id:"munch-museum", name:"Munch Museum", city:"Oslo" },
  dims:"90 × 68.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Edvard_Munch_-_Madonna_-_Google_Art_Project.jpg/500px-Edvard_Munch_-_Madonna_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Madonna_(Munch)", status:"pd" },
  coords:{ F:-60, D:55, E:55, C:15, M:-35 }, coordsSource:"override",
  description:"A Madonna at the moment no altarpiece dared paint: conception, ecstasy and death fused in one figure, the halo red instead of gold. The pose reportedly owes to Dagny Juel, the writer at the magnetic centre of Munch's Berlin circle. In the lithograph version a fetus crouches in the frame's corner among swimming sperm — and Munch meant every version to be read that way: the instant life begins, witnessed with equal awe and terror.",
  notice:["The halo is red, not gold",
          "Her eyes are closed — ecstasy and death-mask at once",
          "The aura's wave-lines are the Scream sky, slowed down"],
  tags:["nude","portrait","red","unsettling"],
  related:["the-scream","the-kiss"] },

{ id:"the-dance-of-life", tier:1,
  title:"The Dance of Life", worksKey:"The Dance of Life",
  artistId:"edvard-munch", year:{ display:"1899–1900", sort:1899 },
  movements:["symbolism","expressionism"], techniques:["oil-painting"], nation:"norway",
  museum:{ id:"nasjonalmuseet-oslo", name:"Nasjonalmuseet", city:"Oslo" },
  dims:"125.5 × 190.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Edvard_Munch_-_The_dance_of_life_%281899-1900%29.jpg/500px-Edvard_Munch_-_The_dance_of_life_%281899-1900%29.jpg",
          page:"https://en.wikipedia.org/wiki/The_Dance_of_Life_(Munch)", status:"pd" },
  coords:{ F:-65, D:40, E:40, C:5, M:-15 }, coordsSource:"override",
  description:"On a midsummer shore, couples wheel under a low sun while one woman watches in white and one mourns in black — both are Tulla Larsen, before and after the love affair that would end, three years later, with a revolver going off in Munch's studio. In the centre he paints himself dancing with a woman in red, eyes locked on nothing. It is the whole Frieze of Life on one canvas: desire arriving, desire consuming, desire buried.",
  notice:["One woman, three dresses — white, red, black, left to right",
          "The midnight sun lays a golden column on the water",
          "Look at the dancers' faces: nobody is smiling"],
  tags:["landscape","red","lonely","unsettling"],
  related:["madonna-munch","the-kiss"] },

{ id:"evening-on-karl-johan", tier:2,
  title:"Evening on Karl Johan",
  artistId:"edvard-munch", year:{ display:"1892", sort:1892 },
  movements:["expressionism","symbolism"], techniques:["oil-painting"], nation:"norway",
  museum:{ id:"kode-bergen", name:"KODE Bergen Art Museum", city:"Bergen" },
  dims:"84.5 × 121 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Edvard_Munch_-_Evening_on_Karl_Johan_Street_%281892%29.jpg/500px-Edvard_Munch_-_Evening_on_Karl_Johan_Street_%281892%29.jpg",
          page:"https://en.wikipedia.org/wiki/Evening_on_Karl_Johan", status:"pd" },
  tags:["unsettling","lonely","everyday-life"] },

{ id:"anxiety-munch", tier:2,
  title:"Anxiety",
  artistId:"edvard-munch", year:{ display:"1894", sort:1894 },
  movements:["expressionism","symbolism"], techniques:["oil-painting"], nation:"norway",
  museum:{ id:"munch-museum", name:"Munch Museum", city:"Oslo" },
  dims:"94 × 74 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Edvard_Munch_-_Anxiety_-_Google_Art_Project.jpg/500px-Edvard_Munch_-_Anxiety_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Anxiety_(Munch)", status:"pd" },
  tags:["unsettling","red","lonely"] },

{ id:"puberty-munch", tier:2,
  title:"Puberty",
  artistId:"edvard-munch", year:{ display:"1894–95", sort:1895 },
  movements:["expressionism","symbolism"], techniques:["oil-painting"], nation:"norway",
  museum:{ id:"nasjonalmuseet-oslo", name:"Nasjonalmuseet", city:"Oslo" },
  dims:"151.5 × 110 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Puberty_%281894-95%29_by_Edvard_Munch.jpg/500px-Puberty_%281894-95%29_by_Edvard_Munch.jpg",
          page:"https://en.wikipedia.org/wiki/Puberty_(Munch)", status:"pd" },
  tags:["portrait","quiet","unsettling"] },

{ id:"the-sun-munch", tier:2,
  title:"The Sun",
  artistId:"edvard-munch", year:{ display:"1911", sort:1911 },
  movements:["expressionism","symbolism"], techniques:["oil-painting"], nation:"norway",
  museum:{ id:"oslo-university-aula", name:"University of Oslo Aula", city:"Oslo" },
  dims:"455 × 780 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Edvard_Munch_-_The_Sun_-_Google_Art_Project.jpg/500px-Edvard_Munch_-_The_Sun_-_Google_Art_Project.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Edvard_Munch_-_The_Sun_-_Google_Art_Project.jpg", status:"pd" },
  tags:["landscape","golden","storm"] },

{ id:"self-portrait-with-cigarette", tier:2,
  title:"Self-Portrait with Cigarette",
  artistId:"edvard-munch", year:{ display:"1895", sort:1895 },
  movements:["expressionism","symbolism"], techniques:["oil-painting"], nation:"norway",
  museum:{ id:"nasjonalmuseet-oslo", name:"Nasjonalmuseet", city:"Oslo" },
  dims:"110.5 × 85.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Munch_SelfBurningCigarette.jpg/500px-Munch_SelfBurningCigarette.jpg",
          page:"https://en.wikipedia.org/wiki/Self-Portrait_with_Cigarette", status:"pd" },
  tags:["portrait","lonely","interior"] },

{ id:"between-the-clock-and-the-bed", tier:2,
  title:"Self-Portrait. Between the Clock and the Bed",
  artistId:"edvard-munch", year:{ display:"1940–43", sort:1943 },
  movements:["expressionism"], techniques:["oil-painting"], nation:"norway",
  museum:{ id:"munch-museum", name:"Munch Museum", city:"Oslo" },
  dims:"149.5 × 120.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Edvard_Munch%2C_autoritratto%2C_tra_l%27orologio_e_il_letto%2C_1940-43.jpg/500px-Edvard_Munch%2C_autoritratto%2C_tra_l%27orologio_e_il_letto%2C_1940-43.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Edvard_Munch,_autoritratto,_tra_l%27orologio_e_il_letto,_1940-43.jpg", status:"pd" },
  tags:["portrait","interior","lonely"] }
]);
