/* Pigment catalog — part 3 (Tier 1 elevation batch A: Botticelli, Dürer,
   Bruegel, El Greco, Manet, Raphael). Same record contract as catalog-1/2
   (docs/ARTWORK_SCHEMA.md). */
window.CATALOG = (window.CATALOG || []).concat([

/* ——— The Botticelli wing ——— */

{ id:"the-birth-of-venus", tier:1,
  title:"The Birth of Venus", worksKey:"The Birth of Venus",
  artistId:"sandro-botticelli", year:{ display:"c. 1485", sort:1485 },
  movements:["early-renaissance"], techniques:["tempera"], nation:"italy",
  museum:{ id:"uffizi", name:"Galleria degli Uffizi", city:"Florence" },
  dims:"172.5 × 278.9 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/500px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
          page:"https://en.wikipedia.org/wiki/The_Birth_of_Venus", status:"pd" },
  coords:{ F:-70, D:-20, E:20, C:-40, M:30 }, coordsSource:"override",
  description:"The first monumental female nude of the post-classical West arrives standing on a shell, blown ashore by entwined wind gods — a pagan goddess painted at altarpiece scale, for a Medici villa, in a city run by monks. Botticelli ignored his era's perspective obsession: no depth, no weight, just line — the neck too long, the shoulder impossible, and nobody has ever wanted them corrected. Venus's face reportedly borrows from Simonetta Vespucci, Florence's adored beauty, dead years before at twenty-two.",
  notice:["The neck and shoulder are anatomically impossible — and better for it",
          "Every windblown rose is outlined and weightless, like enamel",
          "Her pose quotes an ancient Venus statue the Medici owned"],
  tags:["nude","tender","would-hang","historical"],
  related:["primavera","olympia"] },

{ id:"primavera", tier:1,
  title:"Primavera", worksKey:"Primavera",
  artistId:"sandro-botticelli", year:{ display:"c. 1480", sort:1480 },
  movements:["early-renaissance"], techniques:["tempera"], nation:"italy",
  museum:{ id:"uffizi", name:"Galleria degli Uffizi", city:"Florence" },
  dims:"202 × 314 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Botticelli-primavera.jpg/500px-Botticelli-primavera.jpg",
          page:"https://en.wikipedia.org/wiki/Primavera_(Botticelli)", status:"pd" },
  coords:{ F:-70, D:-15, E:15, C:10, M:30 }, coordsSource:"override",
  description:"Nine figures in an orange grove, five hundred plant species, and not one settled explanation. Mercury stirs the clouds, the Graces dance, Venus presides — and at the right Zephyrus seizes the nymph Chloris, who transforms mid-panel into Flora scattering roses. Painted for a Medici wedding (probably) and read through Neoplatonic philosophy (endlessly), it is the Renaissance's great secular puzzle-picture: mythology given full devotional treatment a century before anyone else dared.",
  notice:["Chloris becomes Flora mid-picture — transformation painted as sequence",
          "Botanists have identified some five hundred plant species in the meadow",
          "Blindfolded Cupid aims at the middle Grace — follow the arrow"],
  tags:["pattern","tender","historical","would-hang"],
  related:["the-birth-of-venus","the-kiss"] },

{ id:"adoration-magi-botticelli", tier:2,
  title:"Adoration of the Magi",
  artistId:"sandro-botticelli", year:{ display:"1475", sort:1475 },
  movements:["early-renaissance"], techniques:["tempera"], nation:"italy",
  museum:{ id:"uffizi", name:"Galleria degli Uffizi", city:"Florence" },
  dims:"111 × 134 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Botticelli_-_Adoration_of_the_Magi_%28Zanobi_Altar%29_-_Uffizi.jpg/500px-Botticelli_-_Adoration_of_the_Magi_%28Zanobi_Altar%29_-_Uffizi.jpg",
          page:"https://en.wikipedia.org/wiki/Adoration_of_the_Magi_(Botticelli)", status:"pd" },
  tags:["religious","historical","golden"] },

{ id:"venus-and-mars", tier:2,
  title:"Venus and Mars",
  artistId:"sandro-botticelli", year:{ display:"c. 1485", sort:1485 },
  movements:["early-renaissance"], techniques:["tempera"], nation:"italy",
  museum:{ id:"national-gallery-london", name:"The National Gallery", city:"London" },
  dims:"69.2 × 173.4 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Venus_and_Mars_National_Gallery.jpg/500px-Venus_and_Mars_National_Gallery.jpg",
          page:"https://en.wikipedia.org/wiki/Venus_and_Mars_(Botticelli)", status:"pd" },
  tags:["tender","everyday-life","would-hang"] },

{ id:"madonna-of-the-magnificat", tier:2,
  title:"Madonna of the Magnificat",
  artistId:"sandro-botticelli", year:{ display:"1481", sort:1481 },
  movements:["early-renaissance"], techniques:["tempera"], nation:"italy",
  museum:{ id:"uffizi", name:"Galleria degli Uffizi", city:"Florence" },
  dims:"⌀ 118 cm (tondo)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Magnificat_Madonna_-_Botticelli_%28uffici%29_b.jpg/500px-Magnificat_Madonna_-_Botticelli_%28uffici%29_b.jpg",
          page:"https://en.wikipedia.org/wiki/Madonna_of_the_Magnificat", status:"pd" },
  tags:["religious","golden","tender"] },

{ id:"calumny-of-apelles", tier:2,
  title:"Calumny of Apelles",
  artistId:"sandro-botticelli", year:{ display:"c. 1495", sort:1495 },
  movements:["early-renaissance"], techniques:["tempera"], nation:"italy",
  museum:{ id:"uffizi", name:"Galleria degli Uffizi", city:"Florence" },
  dims:"62 × 91 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Sandro_Botticelli_La_calumnia_de_Apeles.jpg/500px-Sandro_Botticelli_La_calumnia_de_Apeles.jpg",
          page:"https://en.wikipedia.org/wiki/Calumny_of_Apelles", status:"pd" },
  tags:["historical","unsettling","interior"] },

{ id:"the-mystical-nativity", tier:2,
  title:"The Mystical Nativity", worksKey:"The Mystical Nativity",
  artistId:"sandro-botticelli", year:{ display:"1500–01", sort:1500 },
  movements:["early-renaissance"], techniques:["tempera"], nation:"italy",
  museum:{ id:"national-gallery-london", name:"The National Gallery", city:"London" },
  dims:"108.6 × 74.9 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Mystic_Nativity%2C_Sandro_Botticelli.jpg/500px-Mystic_Nativity%2C_Sandro_Botticelli.jpg",
          page:"https://en.wikipedia.org/wiki/The_Mystical_Nativity", status:"pd" },
  tags:["religious","golden","unsettling"] },

{ id:"idealized-portrait-of-a-lady", tier:2,
  title:"Idealized Portrait of a Lady (Simonetta Vespucci as Nymph)",
  artistId:"sandro-botticelli", year:{ display:"c. 1480–85", sort:1482 },
  movements:["early-renaissance"], techniques:["tempera"], nation:"italy",
  museum:{ id:"stadel", name:"Städel Museum", city:"Frankfurt" },
  dims:"81.3 × 54 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Sandro_Botticelli_-_Idealized_Portrait_of_a_Lady_%28Portrait_of_Simonetta_Vespucci_as_Nymph%29_-_Google_Art_Project.jpg/500px-Sandro_Botticelli_-_Idealized_Portrait_of_a_Lady_%28Portrait_of_Simonetta_Vespucci_as_Nymph%29_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Portrait_of_a_Young_Woman_(Botticelli%2C_Frankfurt)", status:"pd" },
  tags:["portrait","tender","pattern"] },

/* ——— The Dürer wing ——— */

{ id:"self-portrait-at-28", tier:1,
  title:"Self-Portrait at Twenty-Eight", worksKey:"Self-Portrait at 28",
  artistId:"albrecht-durer", year:{ display:"1500", sort:1500 },
  movements:["northern-renaissance"], techniques:["oil-painting"], nation:"germany",
  museum:{ id:"alte-pinakothek", name:"Alte Pinakothek", city:"Munich" },
  dims:"67.1 × 48.9 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Albrecht_D%C3%BCrer_-_1500_self-portrait_%28High_resolution_and_detail%29.jpg/500px-Albrecht_D%C3%BCrer_-_1500_self-portrait_%28High_resolution_and_detail%29.jpg",
          page:"https://en.wikipedia.org/wiki/Self-Portrait_(D%C3%BCrer,_Munich)", status:"pd" },
  coords:{ F:-90, D:10, E:35, C:30, M:-55 }, coordsSource:"override",
  description:"No artist before had painted himself like this: full-frontal, symmetrical, long-haired, hand raised toward the chest — a pose and gaze that a thousand years of art had reserved for Christ. It is either blasphemy or a thesis, and Dürer meant the thesis: the artist as creator, made in God's image, signing in Latin that he painted himself 'thus, with undying colors,' at twenty-eight. Nuremberg kept the panel. The swagger has never aged a day.",
  notice:["The pose is Christ's — frontal, iconic, entirely deliberate",
          "The Latin inscription and monogram float like a legal seal",
          "Every strand of fur is separate; the point is demonstration"],
  tags:["portrait","historical","would-hang"],
  related:["melencolia-i","mona-lisa"] },

{ id:"melencolia-i", tier:1,
  title:"Melencolia I", worksKey:"Melencolia I",
  artistId:"albrecht-durer", year:{ display:"1514", sort:1514 },
  movements:["northern-renaissance"], techniques:["etching"], nation:"germany",
  museum:{ id:"met", name:"The Metropolitan Museum of Art", city:"New York" },
  dims:"24 × 18.5 cm (engraving)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Albrecht_D%C3%BCrer_-_Melencolia_I_-_Google_Art_Project_%28_AGDdr3EHmNGyA%29.jpg/500px-Albrecht_D%C3%BCrer_-_Melencolia_I_-_Google_Art_Project_%28_AGDdr3EHmNGyA%29.jpg",
          page:"https://en.wikipedia.org/wiki/Melencolia_I", status:"pd" },
  coords:{ F:-60, D:20, E:40, C:75, M:-70 }, coordsSource:"override",
  description:"The most argued-over engraving ever cut: a winged genius sits slumped among the instruments of geometry and craft — compass idle, polyhedron mute, magic square ticking on the wall — too full of thought to act. Dürer made thinking's dead end into a picture, and four centuries of scholars have proven the point by disagreeing about every object in it. Printed by the hundreds, it made melancholy the artist's official temperament, and the studio's patron mood.",
  notice:["The magic square's every row sums to 34 — and its bottom row dates the print: 1514",
          "The polyhedron has never been conclusively explained; careers have tried",
          "Comet and rainbow at the horizon: hope, or its postponement"],
  tags:["unsettling","pattern","historical","lonely"],
  related:["self-portrait-at-28","the-dog"] },

{ id:"young-hare", tier:2,
  title:"Young Hare", worksKey:"Young Hare",
  artistId:"albrecht-durer", year:{ display:"1502", sort:1502 },
  movements:["northern-renaissance"], techniques:["watercolor"], nation:"germany",
  museum:{ id:"albertina", name:"Albertina", city:"Vienna" },
  dims:"25.1 × 22.6 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Albrecht_D%C3%BCrer_-_Hare%2C_1502_-_Google_Art_Project.jpg/500px-Albrecht_D%C3%BCrer_-_Hare%2C_1502_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Young_Hare", status:"pd" },
  tags:["quiet","tender","would-hang"] },

{ id:"knight-death-and-the-devil", tier:2,
  title:"Knight, Death and the Devil", worksKey:"Knight, Death and the Devil",
  artistId:"albrecht-durer", year:{ display:"1513", sort:1513 },
  movements:["northern-renaissance"], techniques:["etching"], nation:"germany",
  museum:{ id:"met", name:"The Metropolitan Museum of Art", city:"New York" },
  dims:"24.5 × 19 cm (engraving)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Albrecht_D%C3%BCrer%2C_Knight%2C_Death_and_Devil%2C_1513%2C_NGA_6637.jpg/500px-Albrecht_D%C3%BCrer%2C_Knight%2C_Death_and_Devil%2C_1513%2C_NGA_6637.jpg",
          page:"https://en.wikipedia.org/wiki/Knight%2C_Death_and_the_Devil", status:"pd" },
  tags:["unsettling","historical","night"] },

{ id:"praying-hands", tier:2,
  title:"Praying Hands",
  artistId:"albrecht-durer", year:{ display:"1508", sort:1508 },
  movements:["northern-renaissance"], nation:"germany",
  museum:{ id:"albertina", name:"Albertina", city:"Vienna" },
  dims:"29.1 × 19.7 cm (brush drawing)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Albrecht_D%C3%BCrer_-_Praying_Hands%2C_1508_-_Google_Art_Project.jpg/500px-Albrecht_D%C3%BCrer_-_Praying_Hands%2C_1508_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Praying_Hands_(D%C3%BCrer)", status:"pd" },
  tags:["religious","quiet","tender"] },

{ id:"four-horsemen", tier:2,
  title:"The Four Horsemen of the Apocalypse",
  artistId:"albrecht-durer", year:{ display:"1498", sort:1498 },
  movements:["northern-renaissance"], techniques:["woodblock"], nation:"germany",
  museum:{ id:"met", name:"The Metropolitan Museum of Art", city:"New York" },
  dims:"39.4 × 28.1 cm (woodcut)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/D%C3%BCrer_Apocalypse_0.jpg/500px-D%C3%BCrer_Apocalypse_0.jpg",
          page:"https://en.wikipedia.org/wiki/Apocalypse_(D%C3%BCrer)", status:"pd" },
  tags:["religious","storm","unsettling"] },

{ id:"adam-and-eve-durer", tier:2,
  title:"Adam and Eve",
  artistId:"albrecht-durer", year:{ display:"1504", sort:1504 },
  movements:["northern-renaissance"], techniques:["etching"], nation:"germany",
  museum:{ id:"met", name:"The Metropolitan Museum of Art", city:"New York" },
  dims:"24.8 × 19.2 cm (engraving)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Albrecht_D%C3%BCrer%2C_Adam_and_Eve%2C_1504%2C_Engraving.jpg/500px-Albrecht_D%C3%BCrer%2C_Adam_and_Eve%2C_1504%2C_Engraving.jpg",
          page:"https://en.wikipedia.org/wiki/Adam_and_Eve_(D%C3%BCrer)", status:"pd" },
  tags:["nude","religious","pattern"] },

{ id:"great-piece-of-turf", tier:2,
  title:"Great Piece of Turf",
  artistId:"albrecht-durer", year:{ display:"1503", sort:1503 },
  movements:["northern-renaissance"], techniques:["watercolor"], nation:"germany",
  museum:{ id:"albertina", name:"Albertina", city:"Vienna" },
  dims:"40.8 × 31.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Albrecht_D%C3%BCrer_-_The_Large_Piece_of_Turf%2C_1503_-_Google_Art_Project.jpg/500px-Albrecht_D%C3%BCrer_-_The_Large_Piece_of_Turf%2C_1503_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Great_Piece_of_Turf", status:"pd" },
  tags:["quiet","everyday-life","would-hang"] },

{ id:"durers-rhinoceros", tier:2,
  title:"The Rhinoceros",
  artistId:"albrecht-durer", year:{ display:"1515", sort:1515 },
  movements:["northern-renaissance"], techniques:["woodblock"], nation:"germany",
  museum:{ id:"national-gallery-dc", name:"National Gallery of Art", city:"Washington" },
  dims:"23.8 × 29.9 cm (woodcut)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/The_Rhinoceros_%28NGA_1964.8.697%29_enhanced.png/500px-The_Rhinoceros_%28NGA_1964.8.697%29_enhanced.png",
          page:"https://en.wikipedia.org/wiki/D%C3%BCrer's_Rhinoceros", status:"pd" },
  tags:["pattern","historical","would-hang"] },

/* ——— The Bruegel wing ——— */

{ id:"hunters-in-the-snow", tier:1,
  title:"The Hunters in the Snow", worksKey:"Hunters in the Snow",
  artistId:"pieter-bruegel", year:{ display:"1565", sort:1565 },
  movements:["northern-renaissance"], techniques:["oil-painting"], nation:"belgium",
  museum:{ id:"kunsthistorisches", name:"Kunsthistorisches Museum", city:"Vienna" },
  dims:"117 × 162 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_%28Winter%29_-_Google_Art_Project.jpg/500px-Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_%28Winter%29_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/The_Hunters_in_the_Snow", status:"pd" },
  coords:{ F:-80, D:-10, E:15, C:-20, M:-5 }, coordsSource:"override",
  description:"Three tired men and their dogs crest a ridge; below, a whole valley gets on with winter — skaters, chimney fires, crows, a bird trap, and Alps that Bruegel imported into Flanders because the picture needed them. Painted for a rich man's dining room as one month in a cycle of the seasons, it became the West's definitive image of winter: filmmakers from Tarkovsky onward quote it whenever they need cold that feels like memory.",
  notice:["Follow the diagonal — dogs, hunters, ridge, skaters, peaks: one long glide",
          "The inn fire at left is the only warm color on the panel",
          "A single magpie in mid-flight balances the entire composition"],
  tags:["landscape","everyday-life","quiet","would-hang"],
  related:["the-tower-of-babel","the-magpie"] },

{ id:"the-tower-of-babel", tier:1,
  title:"The Tower of Babel", worksKey:"The Tower of Babel",
  artistId:"pieter-bruegel", year:{ display:"1563", sort:1563 },
  movements:["northern-renaissance"], techniques:["oil-painting"], nation:"belgium",
  museum:{ id:"kunsthistorisches", name:"Kunsthistorisches Museum", city:"Vienna" },
  dims:"114 × 155 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project_-_edited.jpg/960px-Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project_-_edited.jpg",
          page:"https://en.wikipedia.org/wiki/The_Tower_of_Babel_(Bruegel)", status:"pd" },
  coords:{ F:-80, D:25, E:20, C:40, M:75 }, coordsSource:"override",
  description:"Bruegel builds the Bible's doomed skyscraper with Flemish engineering: cranes, ramps, mortar-carriers, a visiting king ignored by his own masons — and a structure already tilting, its courses out of true, clouds sawing off the summit. He had seen the Colosseum in Rome and quotes its arches floor by floor. Awe and warning at once: the most loving portrait of a construction site ever painted, of a project guaranteed to fail.",
  notice:["The tower leans — check the horizontal courses against the sea",
          "Hundreds of tiny workers; the king is being ignored at lower left",
          "Upper floors rise before the lower ones are finished — there's the flaw"],
  tags:["historical","monumental-scale","unsettling"],
  related:["hunters-in-the-snow","the-garden-of-earthly-delights"] },

{ id:"netherlandish-proverbs", tier:2,
  title:"Netherlandish Proverbs", worksKey:"Netherlandish Proverbs",
  artistId:"pieter-bruegel", year:{ display:"1559", sort:1559 },
  movements:["northern-renaissance"], techniques:["oil-painting"], nation:"belgium",
  museum:{ id:"gemaldegalerie-berlin", name:"Gemäldegalerie", city:"Berlin" },
  dims:"117 × 163 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Pieter_Brueghel_the_Elder_-_The_Dutch_Proverbs_-_Google_Art_Project.jpg/500px-Pieter_Brueghel_the_Elder_-_The_Dutch_Proverbs_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Netherlandish_Proverbs", status:"pd" },
  tags:["everyday-life","pattern","historical"] },

{ id:"the-peasant-wedding", tier:2,
  title:"The Peasant Wedding",
  artistId:"pieter-bruegel", year:{ display:"1567", sort:1567 },
  movements:["northern-renaissance"], techniques:["oil-painting"], nation:"belgium",
  museum:{ id:"kunsthistorisches", name:"Kunsthistorisches Museum", city:"Vienna" },
  dims:"114 × 164 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Pieter_Bruegel_the_Elder_-_Peasant_Wedding_-_Google_Art_Project_2.jpg/500px-Pieter_Bruegel_the_Elder_-_Peasant_Wedding_-_Google_Art_Project_2.jpg",
          page:"https://en.wikipedia.org/wiki/The_Peasant_Wedding", status:"pd" },
  tags:["everyday-life","interior","tender"] },

{ id:"fall-of-icarus", tier:2,
  title:"Landscape with the Fall of Icarus",
  artistId:"pieter-bruegel", year:{ display:"c. 1560", sort:1560 },
  movements:["northern-renaissance"], techniques:["oil-painting"], nation:"belgium",
  museum:{ id:"royal-museums-brussels", name:"Royal Museums of Fine Arts of Belgium", city:"Brussels" },
  dims:"73.5 × 112 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Pieter_Bruegel_the_Elder_-_Landscape_with_the_Fall_of_Icarus_-_Brussels%2C_Royal_Museums_of_Fine_Arts_of_Belgium_-_Google_Arts_%26_Culture.jpg/500px-Pieter_Bruegel_the_Elder_-_Landscape_with_the_Fall_of_Icarus_-_Brussels%2C_Royal_Museums_of_Fine_Arts_of_Belgium_-_Google_Arts_%26_Culture.jpg",
          page:"https://en.wikipedia.org/wiki/Landscape_with_the_Fall_of_Icarus", status:"pd" },
  tags:["landscape","everyday-life","lonely"] },

{ id:"triumph-of-death", tier:2,
  title:"The Triumph of Death",
  artistId:"pieter-bruegel", year:{ display:"c. 1562", sort:1562 },
  movements:["northern-renaissance"], techniques:["oil-painting"], nation:"belgium",
  museum:{ id:"prado", name:"Museo del Prado", city:"Madrid" },
  dims:"117 × 162 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Triumph_of_Death_Brueghel.jpg/500px-Triumph_of_Death_Brueghel.jpg",
          page:"https://en.wikipedia.org/wiki/The_Triumph_of_Death", status:"pd" },
  tags:["unsettling","storm","historical"] },

{ id:"childrens-games", tier:2,
  title:"Children's Games",
  artistId:"pieter-bruegel", year:{ display:"1560", sort:1560 },
  movements:["northern-renaissance"], techniques:["oil-painting"], nation:"belgium",
  museum:{ id:"kunsthistorisches", name:"Kunsthistorisches Museum", city:"Vienna" },
  dims:"118 × 161 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Pieter_Bruegel_the_Elder_-_Children%E2%80%99s_Games_-_Google_Art_Project.jpg/500px-Pieter_Bruegel_the_Elder_-_Children%E2%80%99s_Games_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Children%27s_Games_(Bruegel)", status:"pd" },
  tags:["everyday-life","pattern","tender"] },

{ id:"the-harvesters", tier:2,
  title:"The Harvesters",
  artistId:"pieter-bruegel", year:{ display:"1565", sort:1565 },
  movements:["northern-renaissance"], techniques:["oil-painting"], nation:"belgium",
  museum:{ id:"met", name:"The Metropolitan Museum of Art", city:"New York" },
  dims:"119 × 162 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Pieter_Bruegel_the_Elder-_The_Harvesters_-_Google_Art_Project.jpg/500px-Pieter_Bruegel_the_Elder-_The_Harvesters_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/The_Harvesters_(painting)", status:"pd" },
  tags:["landscape","everyday-life","golden"] },

{ id:"blind-leading-the-blind", tier:2,
  title:"The Blind Leading the Blind",
  artistId:"pieter-bruegel", year:{ display:"1568", sort:1568 },
  movements:["northern-renaissance"], techniques:["tempera"], nation:"belgium",
  museum:{ id:"capodimonte", name:"Museo di Capodimonte", city:"Naples" },
  dims:"86 × 154 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/%D0%9F%D1%80%D0%B8%D1%82%D1%87%D0%B0_%D0%BE_%D1%81%D0%BB%D0%B5%D0%BF%D1%8B%D1%85.jpeg/500px-%D0%9F%D1%80%D0%B8%D1%82%D1%87%D0%B0_%D0%BE_%D1%81%D0%BB%D0%B5%D0%BF%D1%8B%D1%85.jpeg",
          page:"https://en.wikipedia.org/wiki/The_Parable_of_the_Blind", status:"pd" },
  tags:["unsettling","everyday-life","historical"] },

/* ——— The El Greco wing ——— */

{ id:"burial-of-the-count-of-orgaz", tier:1,
  title:"The Burial of the Count of Orgaz", worksKey:"The Burial of the Count of Orgaz",
  artistId:"el-greco", year:{ display:"1586–88", sort:1586 },
  movements:["mannerism"], techniques:["oil-painting"], nation:"greece",
  museum:{ id:"santo-tome", name:"Iglesia de Santo Tomé", city:"Toledo" },
  dims:"480 × 360 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/El_Greco_-_The_Burial_of_the_Count_of_Orgaz.JPG/500px-El_Greco_-_The_Burial_of_the_Count_of_Orgaz.JPG",
          page:"https://en.wikipedia.org/wiki/The_Burial_of_the_Count_of_Orgaz", status:"pd" },
  coords:{ F:-75, D:45, E:55, C:20, M:80 }, coordsSource:"override",
  description:"Toledo's parish miracle at civic scale: as the pious count is lowered into his tomb, Saints Stephen and Augustine descend in gold to do the lowering themselves, while above, in a sky of cloud-flesh, the count's soul rises like smoke toward the court of heaven. Below stands a line of black-clad Toledo gentlemen — real, named, ruffed — watching with lawyerly calm. Earth is a portrait gallery; heaven is pure El Greco weather. It has never left the wall it was painted for.",
  notice:["The boy pointing at the miracle is El Greco's son — the signature is on his handkerchief",
          "Count the white ruffs: Toledo's establishment, painted from life",
          "The soul rises as a translucent infant through a birth-canal of cloud"],
  tags:["religious","historical","monumental-scale","golden"],
  related:["view-of-toledo","the-calling-of-saint-matthew"] },

{ id:"view-of-toledo", tier:1,
  title:"View of Toledo", worksKey:"View of Toledo",
  artistId:"el-greco", year:{ display:"c. 1599", sort:1599 },
  movements:["mannerism"], techniques:["oil-painting"], nation:"greece",
  museum:{ id:"met", name:"The Metropolitan Museum of Art", city:"New York" },
  dims:"121.3 × 108.6 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/El_Greco_View_of_Toledo.jpg/500px-El_Greco_View_of_Toledo.jpg",
          page:"https://en.wikipedia.org/wiki/View_of_Toledo", status:"pd" },
  coords:{ F:-60, D:75, E:65, C:-10, M:25 }, coordsSource:"override",
  description:"The first great landscape of Spanish art and still its strangest: Toledo under a sky that has already decided something terrible or magnificent, the hills lit green-silver as if by lightning held in reserve. El Greco moved buildings where composition demanded — the cathedral shifted, the alcázar looming — because this is not topography; it is the city's soul under weather. Three centuries on, Cézanne and the Expressionists recognized a colleague.",
  notice:["The skyline is rearranged — Toledo never looked like this from anywhere",
          "There are no people; the drama is entirely sky against hill",
          "Nocturnal green under storm-noon light: impossible, and deliberate"],
  tags:["landscape","storm","unsettling","would-hang"],
  related:["burial-of-the-count-of-orgaz","the-starry-night"] },

{ id:"the-opening-of-the-fifth-seal", tier:2,
  title:"The Opening of the Fifth Seal", worksKey:"The Opening of the Fifth Seal",
  artistId:"el-greco", year:{ display:"1608–14", sort:1610 },
  movements:["mannerism"], techniques:["oil-painting"], nation:"greece",
  museum:{ id:"met", name:"The Metropolitan Museum of Art", city:"New York" },
  dims:"224.8 × 199.4 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/El_Greco%2C_The_Vision_of_Saint_John_%281608-1614%29.jpg/500px-El_Greco%2C_The_Vision_of_Saint_John_%281608-1614%29.jpg",
          page:"https://en.wikipedia.org/wiki/The_Vision_of_Saint_John", status:"pd" },
  tags:["religious","unsettling","storm"] },

{ id:"disrobing-of-christ", tier:2,
  title:"The Disrobing of Christ (El Espolio)",
  artistId:"el-greco", year:{ display:"1577–79", sort:1577 },
  movements:["mannerism"], techniques:["oil-painting"], nation:"greece",
  museum:{ id:"toledo-cathedral", name:"Toledo Cathedral", city:"Toledo" },
  dims:"285 × 173 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/El_Expolio%2C_por_El_Greco.jpg/500px-El_Expolio%2C_por_El_Greco.jpg",
          page:"https://en.wikipedia.org/wiki/The_Disrobing_of_Christ", status:"pd" },
  tags:["religious","red","unsettling"] },

{ id:"laocoon-el-greco", tier:2,
  title:"Laocoön",
  artistId:"el-greco", year:{ display:"c. 1610–14", sort:1612 },
  movements:["mannerism"], techniques:["oil-painting"], nation:"greece",
  museum:{ id:"national-gallery-dc", name:"National Gallery of Art", city:"Washington" },
  dims:"137.5 × 172.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/El_Greco_%28Domenikos_Theotokopoulos%29_-_Laoco%C3%B6n_-_Google_Art_Project.jpg/500px-El_Greco_%28Domenikos_Theotokopoulos%29_-_Laoco%C3%B6n_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Laoco%C3%B6n_(El_Greco)", status:"pd" },
  tags:["historical","unsettling","nude"] },

{ id:"adoration-shepherds-el-greco", tier:2,
  title:"The Adoration of the Shepherds",
  artistId:"el-greco", year:{ display:"1612–14", sort:1613 },
  movements:["mannerism"], techniques:["oil-painting"], nation:"greece",
  museum:{ id:"prado", name:"Museo del Prado", city:"Madrid" },
  dims:"319 × 180 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/La_adoraci%C3%B3n_de_los_pastores_%28El_Greco%29.jpg/500px-La_adoraci%C3%B3n_de_los_pastores_%28El_Greco%29.jpg",
          page:"https://en.wikipedia.org/wiki/Adoration_of_the_Shepherds_(El_Greco%2C_Madrid)", status:"pd" },
  tags:["religious","night","candlelit"] },

{ id:"nobleman-hand-on-chest", tier:2,
  title:"The Nobleman with his Hand on his Chest",
  artistId:"el-greco", year:{ display:"c. 1580", sort:1580 },
  movements:["mannerism"], techniques:["oil-painting"], nation:"greece",
  museum:{ id:"prado", name:"Museo del Prado", city:"Madrid" },
  dims:"82 × 66 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/El_caballero_de_la_mano_en_el_pecho.jpg/500px-El_caballero_de_la_mano_en_el_pecho.jpg",
          page:"https://en.wikipedia.org/wiki/The_Nobleman_with_his_Hand_on_his_Chest", status:"pd" },
  tags:["portrait","quiet","night"] },

/* ——— The Manet wing ——— */

{ id:"olympia", tier:1,
  title:"Olympia", worksKey:"Olympia",
  artistId:"edouard-manet", year:{ display:"1863", sort:1863 },
  movements:["realism","impressionism"], techniques:["oil-painting","alla-prima"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"130.5 × 191 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edouard_Manet_-_Olympia_-_Google_Art_ProjectFXD.jpg/500px-Edouard_Manet_-_Olympia_-_Google_Art_ProjectFXD.jpg",
          page:"https://en.wikipedia.org/wiki/Olympia_(Manet)", status:"pd" },
  coords:{ F:-85, D:35, E:70, C:40, M:-15 }, coordsSource:"override",
  description:"Manet repainted Titian's Venus as a working Parisienne who meets your eye and waits. The scandal of 1865 wasn't the nudity — the Salon ran on nudes — it was the gaze, the flat harsh light, the black cat where Titian put a sleeping dog, the servant delivering a client's flowers. Guards were posted to protect the canvas; critics called her a 'female gorilla.' Painting's modern age arguably begins here: the nude stripped of mythology, looking back.",
  notice:["Her hand: Titian's Venus yields, Olympia's blocks",
          "The choker, the slipper, the orchid — currency, not allegory",
          "The black cat arches exactly where the old masters put fidelity"],
  tags:["nude","portrait","historical","unsettling"],
  related:["the-naked-maja","a-bar-at-the-folies-bergere"] },

{ id:"a-bar-at-the-folies-bergere", tier:1,
  title:"A Bar at the Folies-Bergère", worksKey:"A Bar at the Folies-Bergère",
  artistId:"edouard-manet", year:{ display:"1882", sort:1882 },
  movements:["realism","impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"courtauld-gallery", name:"The Courtauld Gallery", city:"London" },
  dims:"96 × 130 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/%22Un_Bar_aux_Folies-Berg%C3%A8re%22_by_%C3%89douard_Manet_%281882%29.jpg/500px-%22Un_Bar_aux_Folies-Berg%C3%A8re%22_by_%C3%89douard_Manet_%281882%29.jpg",
          page:"https://en.wikipedia.org/wiki/A_Bar_at_the_Folies-Berg%C3%A8re", status:"pd" },
  coords:{ F:-80, D:5, E:60, C:40, M:-25 }, coordsSource:"override",
  description:"Manet's last great painting, made while he was dying: a barmaid stands at attention before a mirror that refuses to behave — her reflection slides right, the customer she faces exists only in the glass, the crowd is a glitter of gaslight and opera glasses. Suzon, a real Folies employee, wears the era's saddest expression: perfectly present, entirely elsewhere. Scholars have argued about the mirror for a century; the loneliness has never needed explaining.",
  notice:["The reflection is displaced — hers and the customer's; it is not a mistake",
          "A trapeze artist's green boots dangle in the upper left corner",
          "The signature hides on the label of the rose-wine bottle"],
  tags:["portrait","interior","lonely","would-hang"],
  related:["olympia","evening-on-karl-johan"] },

{ id:"le-dejeuner-sur-lherbe", tier:2,
  title:"Le Déjeuner sur l'herbe", worksKey:"Le Déjeuner sur l'herbe",
  artistId:"edouard-manet", year:{ display:"1863", sort:1863 },
  movements:["realism","impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"208 × 264.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Edouard_Manet_-_Luncheon_on_the_Grass_-_Google_Art_Project.jpg/500px-Edouard_Manet_-_Luncheon_on_the_Grass_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Le_D%C3%A9jeuner_sur_l%27herbe", status:"pd" },
  tags:["nude","landscape","historical"] },

{ id:"music-in-the-tuileries", tier:2,
  title:"Music in the Tuileries",
  artistId:"edouard-manet", year:{ display:"1862", sort:1862 },
  movements:["realism","impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"national-gallery-london", name:"The National Gallery", city:"London" },
  dims:"76.2 × 118.1 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/MANET_-_M%C3%BAsica_en_las_Tuller%C3%ADas_%28National_Gallery%2C_Londres%2C_1862%29.jpg/500px-MANET_-_M%C3%BAsica_en_las_Tuller%C3%ADas_%28National_Gallery%2C_Londres%2C_1862%29.jpg",
          page:"https://en.wikipedia.org/wiki/Music_in_the_Tuileries", status:"pd" },
  tags:["everyday-life","historical","pattern"] },

{ id:"the-fifer", tier:2,
  title:"The Fifer",
  artistId:"edouard-manet", year:{ display:"1866", sort:1866 },
  movements:["realism","impressionism"], techniques:["oil-painting","alla-prima"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"160.5 × 97 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Manet%2C_Edouard_-_Young_Flautist%2C_or_The_Fifer%2C_1866_%282%29.jpg/500px-Manet%2C_Edouard_-_Young_Flautist%2C_or_The_Fifer%2C_1866_%282%29.jpg",
          page:"https://en.wikipedia.org/wiki/The_Fifer", status:"pd" },
  tags:["portrait","everyday-life","would-hang"] },

{ id:"the-balcony-manet", tier:2,
  title:"The Balcony",
  artistId:"edouard-manet", year:{ display:"1868–69", sort:1868 },
  movements:["realism","impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"170 × 124.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Edouard_Manet_-_The_Balcony_-_Google_Art_Project.jpg/500px-Edouard_Manet_-_The_Balcony_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/The_Balcony_(Manet)", status:"pd" },
  tags:["portrait","everyday-life","quiet"] },

{ id:"execution-of-maximilian", tier:2,
  title:"The Execution of Emperor Maximilian",
  artistId:"edouard-manet", year:{ display:"1868–69", sort:1869 },
  movements:["realism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"kunsthalle-mannheim", name:"Kunsthalle Mannheim", city:"Mannheim" },
  dims:"252 × 305 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Edouard_Manet_022.jpg/500px-Edouard_Manet_022.jpg",
          page:"https://en.wikipedia.org/wiki/The_Execution_of_Emperor_Maximilian", status:"pd" },
  tags:["historical","unsettling","monumental-scale"] },

{ id:"berthe-morisot-violets", tier:2,
  title:"Berthe Morisot with a Bouquet of Violets",
  artistId:"edouard-manet", year:{ display:"1872", sort:1872 },
  movements:["realism","impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"55.5 × 40.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Edouard_Manet_-_Berthe_Morisot_With_a_Bouquet_of_Violets_-_Google_Art_Project.jpg/500px-Edouard_Manet_-_Berthe_Morisot_With_a_Bouquet_of_Violets_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Berthe_Morisot_with_a_Bouquet_of_Violets", status:"pd" },
  tags:["portrait","tender","night"] },

{ id:"the-railway", tier:2,
  title:"The Railway",
  artistId:"edouard-manet", year:{ display:"1873", sort:1873 },
  movements:["realism","impressionism"], techniques:["oil-painting"], nation:"france",
  museum:{ id:"national-gallery-dc", name:"National Gallery of Art", city:"Washington" },
  dims:"93.3 × 111.5 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Edouard_Manet_-_Le_Chemin_de_fer_-_Google_Art_Project.jpg/500px-Edouard_Manet_-_Le_Chemin_de_fer_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/The_Railway", status:"pd" },
  tags:["everyday-life","portrait","historical"] },

{ id:"asparagus-manet", tier:2,
  title:"Asparagus",
  artistId:"edouard-manet", year:{ display:"1880", sort:1880 },
  movements:["realism","impressionism"], techniques:["oil-painting","alla-prima"], nation:"france",
  museum:{ id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris" },
  dims:"16.9 × 21.9 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Edouard_Manet_-_Asparagus_-_Google_Art_Project.jpg/500px-Edouard_Manet_-_Asparagus_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Asparagus_(painting)", status:"pd" },
  tags:["quiet","everyday-life","would-hang"] },

/* ——— The Raphael wing ——— */

{ id:"the-school-of-athens", tier:1,
  title:"The School of Athens", worksKey:"The School of Athens",
  artistId:"raphael", year:{ display:"1509–11", sort:1509 },
  movements:["high-renaissance"], techniques:["fresco"], nation:"italy",
  museum:{ id:"vatican-museums", name:"Vatican Museums", city:"Vatican City" },
  dims:"c. 500 × 770 cm (fresco)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/500px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg",
          page:"https://en.wikipedia.org/wiki/The_School_of_Athens", status:"pd" },
  coords:{ F:-80, D:-10, E:-20, C:50, M:90 }, coordsSource:"override",
  description:"Philosophy's family portrait, frescoed for the pope's private library: Plato points up, Aristotle levels his palm, and around them Raphael casts antiquity with modern faces — Leonardo as Plato, Bramante as Euclid, himself watching from the edge, and, added late after he saw the Sistine ceiling next door, Michelangelo brooding on the steps as Heraclitus. A twenty-something painted humanism's entire self-image in one sweep of perspective, and made it look effortless.",
  notice:["Plato points to heaven, Aristotle to the world — the whole argument in two hands",
          "Michelangelo broods on the steps — added after Raphael saw the ceiling",
          "Raphael's own face watches you from the far right edge"],
  tags:["historical","monumental-scale","pattern"],
  related:["sistine-madonna","sistine-chapel-ceiling"] },

{ id:"sistine-madonna", tier:1,
  title:"Sistine Madonna", worksKey:"Sistine Madonna",
  artistId:"raphael", year:{ display:"1512", sort:1512 },
  movements:["high-renaissance"], techniques:["oil-painting"], nation:"italy",
  museum:{ id:"gemaldegalerie-dresden", name:"Gemäldegalerie Alte Meister", city:"Dresden" },
  dims:"265 × 196 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/RAFAEL_-_Madonna_Sixtina_%28Gem%C3%A4ldegalerie_Alter_Meister%2C_Dresden%2C_1513-14._%C3%93leo_sobre_lienzo%2C_265_x_196_cm%29.jpg/500px-RAFAEL_-_Madonna_Sixtina_%28Gem%C3%A4ldegalerie_Alter_Meister%2C_Dresden%2C_1513-14._%C3%93leo_sobre_lienzo%2C_265_x_196_cm%29.jpg",
          page:"https://en.wikipedia.org/wiki/Sistine_Madonna", status:"pd" },
  coords:{ F:-85, D:-15, E:-30, C:-25, M:50 }, coordsSource:"override",
  description:"Painted as a gift for a monastery altar, the Virgin walks off the clouds toward you with the Child — no throne, no architecture, just curtains pulled back on heaven as theatre. The nineteenth century made it Germany's obsession (Dresden bought it; Dostoevsky kept a print above his writing desk), but modernity chose the bottom edge: two bored putti leaning on the frame, the most reproduced cherubs on earth, forever waiting for the miracle to finish.",
  notice:["The two putti at the base — art history's most merchandised bystanders",
          "The 'clouds' behind the Virgin resolve into dozens of angel faces",
          "Saint Sixtus's papal tiara sits on the ledge, inside the painted theatre"],
  tags:["religious","tender","monumental-scale","would-hang"],
  related:["the-school-of-athens","madonna-of-the-magnificat"] },

{ id:"la-fornarina", tier:2,
  title:"La Fornarina", worksKey:"La Fornarina",
  artistId:"raphael", year:{ display:"c. 1518–19", sort:1518 },
  movements:["high-renaissance"], techniques:["oil-painting"], nation:"italy",
  museum:{ id:"palazzo-barberini", name:"Palazzo Barberini", city:"Rome" },
  dims:"87 × 63 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/La_Fornarina_by_Raffaello.jpg/500px-La_Fornarina_by_Raffaello.jpg",
          page:"https://en.wikipedia.org/wiki/La_fornarina", status:"pd" },
  tags:["portrait","nude","tender"] },

{ id:"the-transfiguration-raphael", tier:2,
  title:"The Transfiguration",
  artistId:"raphael", year:{ display:"1516–20", sort:1518 },
  movements:["high-renaissance"], techniques:["oil-painting","tempera"], nation:"italy",
  museum:{ id:"vatican-museums", name:"Vatican Museums", city:"Vatican City" },
  dims:"410 × 279 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Transfiguration_Raphael.jpg/500px-Transfiguration_Raphael.jpg",
          page:"https://en.wikipedia.org/wiki/Transfiguration_(Raphael)", status:"pd" },
  tags:["religious","monumental-scale","storm"] },

{ id:"baldassare-castiglione", tier:2,
  title:"Portrait of Baldassare Castiglione",
  artistId:"raphael", year:{ display:"c. 1514–15", sort:1514 },
  movements:["high-renaissance"], techniques:["oil-painting"], nation:"italy",
  museum:{ id:"louvre", name:"Musée du Louvre", city:"Paris" },
  dims:"82 × 67 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Baldassare_Castiglione%2C_by_Raffaello_Sanzio%2C_from_C2RMF_retouched.jpg/500px-Baldassare_Castiglione%2C_by_Raffaello_Sanzio%2C_from_C2RMF_retouched.jpg",
          page:"https://en.wikipedia.org/wiki/Portrait_of_Baldassare_Castiglione", status:"pd" },
  tags:["portrait","quiet","would-hang"] },

{ id:"madonna-of-the-meadow", tier:2,
  title:"Madonna of the Meadow",
  artistId:"raphael", year:{ display:"1506", sort:1506 },
  movements:["high-renaissance"], techniques:["oil-painting"], nation:"italy",
  museum:{ id:"kunsthistorisches", name:"Kunsthistorisches Museum", city:"Vienna" },
  dims:"113 × 88 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Raphael_-_Madonna_in_the_Meadow_-_Google_Art_Project.jpg/500px-Raphael_-_Madonna_in_the_Meadow_-_Google_Art_Project.jpg",
          page:"https://en.wikipedia.org/wiki/Madonna_del_Prato_(Raphael)", status:"pd" },
  tags:["religious","tender","landscape"] },

{ id:"raphael-self-portrait", tier:2,
  title:"Self-Portrait",
  artistId:"raphael", year:{ display:"c. 1504–06", sort:1505 },
  movements:["high-renaissance"], techniques:["tempera"], nation:"italy",
  museum:{ id:"uffizi", name:"Galleria degli Uffizi", city:"Florence" },
  dims:"47.5 × 33 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Raffaello_Sanzio.jpg/500px-Raffaello_Sanzio.jpg",
          page:"https://en.wikipedia.org/wiki/Self-portrait_(Raphael)", status:"pd" },
  tags:["portrait","quiet","tender"] },

{ id:"marriage-of-the-virgin", tier:2,
  title:"The Marriage of the Virgin",
  artistId:"raphael", year:{ display:"1504", sort:1504 },
  movements:["high-renaissance"], techniques:["oil-painting"], nation:"italy",
  museum:{ id:"brera", name:"Pinacoteca di Brera", city:"Milan" },
  dims:"174 × 121 cm",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Raffaello_-_Spozalizio_-_Web_Gallery_of_Art.jpg/500px-Raffaello_-_Spozalizio_-_Web_Gallery_of_Art.jpg",
          page:"https://en.wikipedia.org/wiki/The_Marriage_of_the_Virgin_(Raphael)", status:"pd" },
  tags:["religious","historical","pattern"] },

{ id:"triumph-of-galatea", tier:2,
  title:"The Triumph of Galatea",
  artistId:"raphael", year:{ display:"c. 1512", sort:1512 },
  movements:["high-renaissance"], techniques:["fresco"], nation:"italy",
  museum:{ id:"villa-farnesina", name:"Villa Farnesina", city:"Rome" },
  dims:"295 × 225 cm (fresco)",
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Galatea_Raphael.jpg/500px-Galatea_Raphael.jpg",
          page:"https://en.wikipedia.org/wiki/Galatea_(Raphael)", status:"pd" },
  tags:["nude","tender","monumental-scale"] }
]);
