/* PIGMENT — catalogue batch 10: the Italian spine, Cimabue to Veronese.

   A depth batch, not a widening one. The atlas held 280 painters and 398
   works, but 160 of those painters had no catalogued work at all — a bio and
   nothing to look at. Ninety of the 160 died before 1956 and so can carry a
   public-domain image, and every one of the ninety already had images sitting
   unused in js/artworks.js.

   These twelve are the Italian foundations: the atlas named Cimabue, Duccio,
   Simone Martini, Piero and Veronese and could not show you a single picture
   by any of them. Four of the twelve are Trecento, where the catalogue held
   one work per century.

   Every image was checked against Commons metadata and then looked at. Two
   corrections came out of that: the San Romano file is the UFFIZI panel, not
   the London one the artist record implied, and the Resurrection image in the
   pool was a CC BY-SA detail crop, replaced here with a public-domain view of
   the whole fresco. */
window.CATALOG = (window.CATALOG || []).concat([

{ id:"santa-trinita-maesta", tier:1,
  title:"Santa Trinita Maestà", worksKey:"Santa Trinita Maestà",
  artistId:"cimabue", year:{ display:"c. 1290–1300", sort:1290 },
  movements:["proto-renaissance"], techniques:["tempera", "gold-leaf"], nation:"italy",
  museum:{ id:"uffizi", name:"Gallerie degli Uffizi", city:"Florence" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Cimabue_-_Maest%C3%A0_di_Santa_Trinita_-_Google_Art_Project.jpg/500px-Cimabue_-_Maest%C3%A0_di_Santa_Trinita_-_Google_Art_Project.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Cimabue_-_Maest%C3%A0_di_Santa_Trinita_-_Google_Art_Project.jpg", status:"pd" },
  coords:{ F:-70, D:0, E:-35, C:35, M:75 }, coordsSource:"override",
  description:"Gold, and a throne built like a piece of architecture. Eight angels stack up its sides rather than standing around it, and four prophets watch from the arcade underneath, each holding a scroll that argues the case for the Incarnation. Cimabue worked before painting learned perspective and gets depth anyway by carpentry: the throne recedes because it is drawn as a building. The gold is not a background. It is the light.",
  notice:["Eight angels are stacked, not spaced — the throne is a structure",
          "Four prophets sit in the arcade below, holding their scrolls of proof",
          "No perspective yet: the depth is joinery, done in gold"],
  tags:["sacred", "golden", "monumental-scale", "pattern"] },

{ id:"rucellai-madonna", tier:1,
  title:"Rucellai Madonna", worksKey:"Rucellai Madonna",
  artistId:"duccio", year:{ display:"1285", sort:1285 },
  movements:["proto-renaissance"], techniques:["tempera", "gold-leaf"], nation:"italy",
  museum:{ id:"uffizi", name:"Gallerie degli Uffizi", city:"Florence" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Duccio_-_Rucellai_Madonna.jpg/500px-Duccio_-_Rucellai_Madonna.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Duccio_-_Rucellai_Madonna.jpg", status:"pd" },
  coords:{ F:-70, D:-15, E:-30, C:30, M:75 }, coordsSource:"override",
  description:"The largest panel painted in Italy in its century, ordered by a lay confraternity for their chapel in Santa Maria Novella. Six angels kneel on the frame rather than in the space, holding the throne up like porters. Duccio was Sienese and the commission was Florentine, and for centuries Florence preferred to believe Cimabue had painted it. The tenderness gives him away: the cloth falls in curves nobody in Florence was drawing yet.",
  notice:["The angels kneel on the frame itself, not in the picture",
          "Florence attributed it to Cimabue for roughly six hundred years",
          "Ordered by a confraternity of laymen, not by the church"],
  tags:["sacred", "golden", "monumental-scale", "tender"] },

{ id:"annunciation-simone-martini", tier:1,
  title:"Annunciation with Saints Margaret and Ansanus", worksKey:"Annunciation with Saints Margaret and Ansanus",
  artistId:"simone-martini", year:{ display:"1333", sort:1333 },
  movements:["proto-renaissance"], techniques:["tempera", "gold-leaf"], nation:"italy",
  museum:{ id:"uffizi", name:"Gallerie degli Uffizi", city:"Florence" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Simone_Martini_%E2%80%94_Annunciation_with_St._Margaret_and_St._Ansanus.jpg/500px-Simone_Martini_%E2%80%94_Annunciation_with_St._Margaret_and_St._Ansanus.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Simone_Martini_%E2%80%94_Annunciation_with_St._Margaret_and_St._Ansanus.jpg", status:"pd" },
  coords:{ F:-65, D:20, E:-20, C:40, M:45 }, coordsSource:"override",
  description:"Gabriel has just spoken and the words run out of his mouth in raised gold letters, straight across the panel to Mary — who pulls away, gathers her cloak, and looks as though she would rather not. That recoil is the whole picture. Painted for Siena cathedral, where the lily that belongs in this scene was a Florentine emblem, so the olive branch stands in for it. Diplomacy, in gold leaf.",
  notice:["The angel's words are raised gold, crossing the panel as an object",
          "Mary pulls back and gathers her cloak — she is not pleased",
          "An olive branch replaces the lily, which was Florence's flower"],
  tags:["sacred", "golden", "tender", "pattern"] },

{ id:"presentation-in-the-temple", tier:1,
  title:"Presentation in the Temple", worksKey:"Presentation in the Temple",
  artistId:"ambrogio-lorenzetti", year:{ display:"1342", sort:1342 },
  movements:["proto-renaissance"], techniques:["tempera", "gold-leaf"], nation:"italy",
  museum:{ id:"uffizi", name:"Gallerie degli Uffizi", city:"Florence" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Ambrogio_Lorenzetti_-_Presentazione_di_Ges%C3%B9_al_tempio_-_Google_Art_Project.jpg/500px-Ambrogio_Lorenzetti_-_Presentazione_di_Ges%C3%B9_al_tempio_-_Google_Art_Project.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Ambrogio_Lorenzetti_-_Presentazione_di_Ges%C3%B9_al_tempio_-_Google_Art_Project.jpg", status:"pd" },
  coords:{ F:-70, D:-20, E:0, C:25, M:40 }, coordsSource:"override",
  description:"A building, painted from inside, with a floor that actually goes somewhere. Lorenzetti tiles the pavement and runs the columns back into depth a full lifetime before perspective was codified, and he does it by eye. The ceremony is quiet — an old man holds the child, a priest waits, the mother watches — and the architecture does the arguing. Six years later the Black Death killed him, and Siena stopped painting like this.",
  notice:["The tiled floor recedes correctly, decades before the rules existed",
          "The scene is set inside a building that behaves like one",
          "He died in the plague of 1348, and this line of painting stopped"],
  tags:["sacred", "golden", "interior", "geometry"] },

{ id:"battle-of-san-romano", tier:1,
  title:"The Battle of San Romano", worksKey:"The Battle of San Romano",
  artistId:"paolo-uccello", year:{ display:"c. 1438–40", sort:1438 },
  movements:["early-renaissance"], techniques:["tempera"], nation:"italy",
  museum:{ id:"uffizi", name:"Gallerie degli Uffizi", city:"Florence" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Uccello_%E2%80%94_the_Battle_of_San_Romano.jpg/500px-Uccello_%E2%80%94_the_Battle_of_San_Romano.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Uccello_%E2%80%94_the_Battle_of_San_Romano.jpg", status:"pd" },
  coords:{ F:-55, D:60, E:35, C:20, M:60 }, coordsSource:"override",
  description:"One of three panels made for a Florentine bedroom, and this is the middle of the fight: a commander going backwards off a white horse, lances crossing overhead like a roof. Uccello laid the broken weapons on the ground in a deliberate grid because perspective was the thing he actually cared about. Behind the carnage, on a brown hillside, hares run from dogs. Vasari said his wife complained he would not come to bed.",
  notice:["The broken lances on the ground are laid out as a perspective grid",
          "Behind the battle the hillside carries a small hunt, hares and all",
          "One of three panels; the others are in London and Paris"],
  tags:["historical", "group-scene", "geometry", "theatrical"] },

{ id:"the-resurrection-piero", tier:1,
  title:"The Resurrection", worksKey:"The Resurrection",
  artistId:"piero-della-francesca", year:{ display:"c. 1463–65", sort:1463 },
  movements:["early-renaissance"], techniques:["fresco"], nation:"italy",
  museum:{ id:"museo-civico-sansepolcro", name:"Museo Civico", city:"Sansepolcro" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Piero_della_Francesca_-_Resurrection_-_WGA17609.jpg/500px-Piero_della_Francesca_-_Resurrection_-_WGA17609.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Piero_della_Francesca_-_Resurrection_-_WGA17609.jpg", status:"pd" },
  coords:{ F:-60, D:25, E:10, C:45, M:60 }, coordsSource:"override",
  description:"Christ steps out of the tomb with one foot on its edge and stares straight out, while four soldiers sleep underneath in a heap of armour. Look at the trees: bare on the left, in leaf on the right, so the landscape performs the resurrection as well. Piero painted it for his own town hall. In 1944 a British officer shelling the town recalled reading that the best picture in the world was here, and stopped.",
  notice:["The trees are winter on the left and summer on the right",
          "Christ's foot rests on the lip of the tomb, halfway out",
          "A 1944 bombardment was called off because of this painting"],
  tags:["sacred", "historical", "monumental-scale", "quiet"] },

{ id:"saint-jerome-in-his-study", tier:1,
  title:"Saint Jerome in His Study", worksKey:"Saint Jerome in His Study",
  artistId:"antonello-da-messina", year:{ display:"c. 1475", sort:1475 },
  movements:["early-renaissance"], techniques:["oil-painting", "glazing"], nation:"italy",
  museum:{ id:"national-gallery-london", name:"The National Gallery", city:"London" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Antonello_da_Messina_-_St_Jerome_in_his_study_-_National_Gallery_London.jpg/500px-Antonello_da_Messina_-_St_Jerome_in_his_study_-_National_Gallery_London.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Antonello_da_Messina_-_St_Jerome_in_his_study_-_National_Gallery_London.jpg", status:"pd" },
  coords:{ F:-70, D:-55, E:20, C:25, M:-40 }, coordsSource:"override",
  description:"A study inside a church inside a stone arch, like a set of boxes opened for inspection, and the saint sits in the middle of it reading. Antonello had learned oil paint from Netherlandish pictures and brought the method to Italy, which is why the slippers, the partridge and the brass bowl all hold their own light. The lion is in the shadows on the right, walking. Everything is small, and nothing is vague.",
  notice:["The lion paces in the shadowed arcade on the right",
          "Northern oil technique, painted by a Sicilian — the transfer point",
          "A partridge and a peacock stand on the step, lit like portraits"],
  tags:["interior", "quiet", "geometry", "sacred"] },

{ id:"baptism-of-christ-verrocchio", tier:1,
  title:"The Baptism of Christ", worksKey:"The Baptism of Christ",
  artistId:"andrea-del-verrocchio", year:{ display:"c. 1475", sort:1475 },
  movements:["early-renaissance"], techniques:["oil-painting", "tempera"], nation:"italy",
  museum:{ id:"uffizi", name:"Gallerie degli Uffizi", city:"Florence" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Andrea_del_Verrocchio%2C_Leonardo_da_Vinci_-_Baptism_of_Christ_-_Uffizi.jpg/500px-Andrea_del_Verrocchio%2C_Leonardo_da_Vinci_-_Baptism_of_Christ_-_Uffizi.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Andrea_del_Verrocchio,_Leonardo_da_Vinci_-_Baptism_of_Christ_-_Uffizi.jpg", status:"pd" },
  coords:{ F:-70, D:0, E:10, C:25, M:35 }, coordsSource:"override",
  description:"A workshop picture, and you can see the seam. The angel on the far left — the one turned away, with the soft hair and the landscape dissolving behind it — was painted by an apprentice named Leonardo, in oil, while the rest is his master's tempera. Vasari says Verrocchio looked at that corner and never painted again. He did, in fact. But the story survives because the corner really is different.",
  notice:["The left-hand angel is Leonardo's, and it is painted in oil",
          "The rest is tempera by the master — the two surfaces disagree",
          "Vasari's tale of a teacher quitting in despair is a good story"],
  tags:["sacred", "historical", "tender", "landscape"] },

{ id:"old-man-and-his-grandson", tier:1,
  title:"An Old Man and His Grandson", worksKey:"An Old Man and His Grandson",
  artistId:"domenico-ghirlandaio", year:{ display:"c. 1490", sort:1490 },
  movements:["early-renaissance"], techniques:["tempera"], nation:"italy",
  museum:{ id:"louvre", name:"Musée du Louvre", city:"Paris" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Ghirlandaio%2C_Domenico_-_An_Old_Man_and_His_Grandson_-_Louvre_-_Google_Art_Project.jpg/500px-Ghirlandaio%2C_Domenico_-_An_Old_Man_and_His_Grandson_-_Louvre_-_Google_Art_Project.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Ghirlandaio,_Domenico_-_An_Old_Man_and_His_Grandson_-_Louvre_-_Google_Art_Project.jpg", status:"pd" },
  coords:{ F:-85, D:-30, E:5, C:-10, M:-45 }, coordsSource:"override",
  description:"The old man's nose is deformed by disease and Ghirlandaio paints it exactly, lumps and all, then paints the child looking up at him with complete trust. Neither fact cancels the other, which is the whole achievement. A window at the back opens onto a winding road, the way Flemish portraits did it. Nobody knows who they were. It is one of the few Renaissance portraits where affection, rather than status, is the subject.",
  notice:["The nose is rhinophyma, recorded without softening",
          "The child's hand rests on his chest; he is not flinching",
          "The window and road are borrowed from Netherlandish portraiture"],
  tags:["portrait", "tender", "everyday-life", "would-hang"] },

{ id:"madonna-with-the-long-neck", tier:1,
  title:"Madonna with the Long Neck", worksKey:"Madonna with the Long Neck",
  artistId:"parmigianino", year:{ display:"1534–40", sort:1534 },
  movements:["mannerism"], techniques:["oil-painting", "glazing"], nation:"italy",
  museum:{ id:"uffizi", name:"Gallerie degli Uffizi", city:"Florence" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Parmigianino_-_Madonna_and_Child_with_Angels%2C_known_as_the_Madonna_with_the_Long_Neck.jpg/500px-Parmigianino_-_Madonna_and_Child_with_Angels%2C_known_as_the_Madonna_with_the_Long_Neck.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Parmigianino_-_Madonna_and_Child_with_Angels,_known_as_the_Madonna_with_the_Long_Neck.jpg", status:"pd" },
  coords:{ F:-55, D:20, E:55, C:35, M:40 }, coordsSource:"override",
  description:"Everything is stretched — the neck, the fingers, the thigh under the silk, the enormous child asleep across her lap like a body being carried. On the right a row of columns supports nothing and stops in mid-air, and a prophet the size of a thumb stands at their base unrolling a scroll. Parmigianino never finished it and died at thirty-seven. Beauty pushed until it goes wrong is exactly the point.",
  notice:["The colonnade on the right holds nothing up and simply stops",
          "The prophet at its foot is painted at a fraction of proper scale",
          "Unfinished: the panel was still in the studio when he died"],
  tags:["sacred", "unsettling", "experimental", "pattern"] },

{ id:"allegory-venus-and-cupid", tier:1,
  title:"An Allegory with Venus and Cupid", worksKey:"An Allegory with Venus and Cupid",
  artistId:"bronzino", year:{ display:"c. 1545", sort:1545 },
  movements:["mannerism"], techniques:["oil-painting", "glazing"], nation:"italy",
  museum:{ id:"national-gallery-london", name:"The National Gallery", city:"London" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Angelo_Bronzino_-_Venus%2C_Cupid%2C_Folly_and_Time_-_National_Gallery%2C_London.jpg/500px-Angelo_Bronzino_-_Venus%2C_Cupid%2C_Folly_and_Time_-_National_Gallery%2C_London.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Angelo_Bronzino_-_Venus,_Cupid,_Folly_and_Time_-_National_Gallery,_London.jpg", status:"pd" },
  coords:{ F:-60, D:35, E:40, C:55, M:25 }, coordsSource:"override",
  description:"Flesh painted like cold enamel, a kiss that is not quite a kiss, and a crowd of figures nobody has fully explained. A laughing child hurls roses; behind him a girl with a sweet face has the body of a reptile and hands attached the wrong way round; an old man hauls a curtain across the top. It was a diplomatic gift to the King of France. Pleasure and its consequences, arranged as a puzzle.",
  notice:["The girl offering the honeycomb has reversed hands and a serpent's body",
          "Father Time draws the curtain from above, ending the scene",
          "Painted in Florence as a gift for François I"],
  tags:["mythological", "unsettling", "nude", "theatrical"] },

{ id:"the-wedding-at-cana", tier:1,
  title:"The Wedding at Cana", worksKey:"The Wedding at Cana",
  artistId:"paolo-veronese", year:{ display:"1563", sort:1563 },
  movements:["venetian-school"], techniques:["oil-painting"], nation:"italy",
  museum:{ id:"louvre", name:"Musée du Louvre", city:"Paris" },
  image:{ src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Paolo_Veronese_008.jpg/500px-Paolo_Veronese_008.jpg",
          page:"https://commons.wikimedia.org/wiki/File:Paolo_Veronese_008.jpg", status:"pd" },
  coords:{ F:-60, D:45, E:15, C:-15, M:95 }, coordsSource:"override",
  description:"Ten metres of wedding party, about a hundred and thirty guests, and Christ sitting dead centre being entirely ignored by nearly all of them. Veronese painted it for a monastery refectory in Venice, so the monks ate their supper facing a better one. Napoleon's army took it in 1797 and cut it in half to move it. It now hangs in the Louvre on the wall opposite the Mona Lisa, watching the crowd watch her.",
  notice:["Christ is at the centre and almost nobody at the table notices",
          "The musicians in the foreground are portraits of Venetian painters",
          "Cut in two by Napoleon's troops to get it out of Venice"],
  tags:["group-scene", "monumental-scale", "theatrical", "sacred"] }
]);
