/* Pigment editorial lists — v1
   Schema: { id (kebab, permanent), title (≤64 chars), lede (15–60 words, house voice),
             cover (artwork id, must appear in works), featured (bool, homepage),
             works: [{ id: catalog artwork id, note: one line ≤120 chars — why it's here }] }
   Rules enforced by tools/validate.jxa.js. Works may appear in many lists — lists reuse
   canonical artwork pages, never duplicate artwork data. */
window.EDITORIAL_LISTS = [

{ id:"paintings-that-still-scare-us", featured:true,
  title:"Paintings That Still Scare Us",
  lede:"Horror films age badly; painted dread doesn't. Five centuries of artists found the exact frequencies of fear — grief, appetite, crowds, silence — and pinned them down where they can't stop humming. Viewer discretion pointless.",
  cover:"the-scream",
  works:[
    { id:"the-scream", note:"Not screaming — hearing it. That's worse." },
    { id:"saturn-devouring-his-son", note:"Painted on his dining-room wall. He ate facing it." },
    { id:"the-dog", note:"A head, a void, nothing else. Possibly the loneliest picture ever made." },
    { id:"judith-beheading-holofernes", note:"Caravaggio stages the exact moment — and stands you exactly where you don't want to be." },
    { id:"the-garden-of-earthly-delights", note:"The right panel invented a hell five centuries haven't matched." },
    { id:"anxiety-munch", note:"The Karl Johan crowd again — except now they're looking at you." },
    { id:"the-third-of-may-1808", note:"The firing squad has no faces. That's the point." },
    { id:"witches-sabbath", note:"The great he-goat holds office hours by moonlight." },
    { id:"temptation-of-saint-anthony", note:"Demon machinery, centuries before machines." },
    { id:"129-die-in-jet", note:"Warhol repeats the headline until you notice you've stopped flinching." }] },

{ id:"the-night-shift", featured:false,
  title:"The Night Shift",
  lede:"Painting nights is a technical dare — how do you make darkness visible without losing it? Here are the painters who worked the late hours: gaslight, candle flame, moonlit water, and one famous night sky painted from memory at dawn.",
  cover:"cafe-terrace-at-night",
  works:[
    { id:"cafe-terrace-at-night", note:"A whole night painted without a single drop of black." },
    { id:"the-night-cafe", note:"A place, Vincent said, where you could ruin yourself, go mad, or commit a crime." },
    { id:"fishermen-at-sea", note:"Turner's first exhibited oil: the moon outgunned by a lantern." },
    { id:"evening-on-karl-johan", note:"Dusk as social dread — every window burning, every face a mask." },
    { id:"the-calling-of-saint-matthew", note:"One diagonal of light doing the work of God." },
    { id:"the-starry-night", note:"The most famous night in art, painted from memory — at dawn, indoors." },
    { id:"old-woman-frying-eggs", note:"Candlelight on eggs and copper, observed by a teenager." },
    { id:"judith-and-her-maidservant-detroit", note:"One shielded candle, two women listening for footsteps." },
    { id:"black-fuji", note:"Fuji by lightning — the Great Wave's dark twin." }] },

{ id:"stolen-slashed-survived", featured:true,
  title:"Stolen, Slashed, Survived",
  lede:"Masterpieces lead dangerous lives. These have been carried out windows, cut from frames, attacked with acid, knives and hammers — and, mostly, come back. Two are still missing; their frames hang empty, waiting.",
  cover:"the-storm-on-the-sea-of-galilee",
  works:[
    { id:"the-storm-on-the-sea-of-galilee", note:"Rembrandt's only seascape — cut from its frame in 1990, missing ever since." },
    { id:"the-concert", note:"Taken the same Boston night; among the most valuable stolen objects on earth." },
    { id:"ghent-altarpiece", note:"Thirteen crimes and counting; the Just Judges panel missing since 1934." },
    { id:"mona-lisa", note:"The 1911 theft is what made her the most famous painting alive." },
    { id:"the-scream", note:"Stolen in 1994 and again in 2004. Recovered twice. Still screaming." },
    { id:"rokeby-venus", note:"Slashed seven times by a suffragette in 1914 — 'the most beautiful woman in mythological history' for justice." },
    { id:"the-night-watch", note:"Knifed twice and doused with acid across one century. Still marching." },
    { id:"danae-rembrandt", note:"Acid and knife, 1985; twelve years on the restorers' table." },
    { id:"pieta", note:"Attacked with a hammer in 1972 — fifteen blows. Behind glass ever since." },
    { id:"guernica", note:"Spray-painted in 1974; the varnish took the hit. The protest is part of its story now." }] },

{ id:"painted-in-their-last-year", featured:false,
  title:"Painted in Their Last Year",
  lede:"What does a painter do with the final twelve months? Some plead, some take inventory, some keep the appointment at the easel as if nothing were happening. No genre is more honest — nobody decorates on a deadline like this.",
  cover:"wheatfield-with-crows",
  works:[
    { id:"wheatfield-with-crows", note:"Not actually his last canvas — but the legend refuses to hear otherwise." },
    { id:"between-the-clock-and-the-bed", note:"Munch stations himself between time and the deathbed. Literally." },
    { id:"david-with-the-head-of-goliath", note:"Caravaggio mails his own severed head to Rome as an apology." },
    { id:"self-portrait-at-63", note:"Rembrandt's final year, recorded without one ounce of self-pity." },
    { id:"marxism-health-sick", note:"Frida painting from the wheelchair, still recruiting." },
    { id:"untitled-black-gray", note:"Rothko's last horizon: black over gray, and no door in it." },
    { id:"self-portrait-fright-wig", note:"Warhol, months before the end — the machine finally looks frightened." }] },

{ id:"the-same-thing-obsessively", featured:false,
  title:"The Same Thing, Obsessively",
  lede:"Amateurs change subjects; obsessives change the light. Painting the same thing again and again isn't repetition — it's the discovery that the subject was never the thing at all, but time moving across it.",
  cover:"grainstacks",
  works:[
    { id:"grainstacks", note:"Twenty-five stacks of wheat; the real subject is the clock." },
    { id:"rouen-cathedral-full-sunlight", note:"Thirty façades. The stone never moves; the hour never stops." },
    { id:"water-lilies-grandes-decorations", note:"One pond, three decades, no horizon." },
    { id:"sunflowers", note:"Seven versions — wallpaper for Gauguin's bedroom, then for the world." },
    { id:"the-great-wave-off-kanagawa", note:"One mountain, thirty-six excuses to keep looking." },
    { id:"red-fuji", note:"Same series, opposite temperament: the Wave's silent twin." },
    { id:"judith-slaying-holofernes", note:"Artemisia repainted this beheading her whole career. She had her reasons." },
    { id:"marilyn-diptych", note:"Fifty Marilyns, fading left to right like a worn film reel." },
    { id:"campbells-soup-cans", note:"Thirty-two flavors, one shelf, no comment." },
    { id:"mont-sainte-victoire", note:"Cézanne climbed the same mountain some eighty times in paint." }] },

{ id:"doorways-into-abstraction", featured:true,
  title:"Doorways into Abstraction",
  lede:"Nobody wakes up loving squares. Abstraction has staircases — a castle dissolving into sunrise, a pond losing its horizon, a mountain becoming a chord — and if you climb them in order, the top floor feels inevitable.",
  cover:"composition-viii",
  works:[
    { id:"norham-castle-sunrise", note:"1845: the castle is already optional." },
    { id:"the-dog", note:"1820: Goya got there first — by accident, in despair." },
    { id:"water-lilies-grandes-decorations", note:"Stand close: abstraction. Step back: a pond. Repeat until converted." },
    { id:"blue-mountain", note:"A mountain on its way to becoming a chord." },
    { id:"first-abstract-watercolor", note:"The claimed first — dated 1910, argued about ever since." },
    { id:"improvisation-28", note:"Flood and cannon still visible, if you squint." },
    { id:"composition-viii", note:"Geometry with a pulse." },
    { id:"black-square", note:"The full stop. Or the door." },
    { id:"autumn-rhythm", note:"No objects left — only weather, made of paint." },
    { id:"no-14-rothko", note:"Color doing what music does." }] },

{ id:"judith-one-story-many-knives", featured:true,
  title:"Judith: One Story, Many Knives",
  lede:"The Book of Judith handed painters a licensed murder: a widow, a tyrant, a tent, a sword. Every era retold it in its own accent — Caravaggio's shock, Artemisia's testimony, Klimt's gilded afterglow. Same story; the knife keeps changing hands.",
  cover:"judith-slaying-holofernes",
  works:[
    { id:"judith-beheading-holofernes", note:"Caravaggio's version: mid-stroke, no mercy, nowhere to look away." },
    { id:"judith-beheading-holofernes-naples", note:"Artemisia's first answer — painted within a year of her trial." },
    { id:"judith-slaying-holofernes", note:"Her second: bigger, darker, bloodier. The Uffizi keeps it lit like evidence." },
    { id:"judith-and-her-maidservant-detroit", note:"The sequel — the getaway, by one shielded candle." },
    { id:"judith-i", note:"Vienna's Judith: gilded, post-coital, terrifying in an entirely new way." }] },

{ id:"paint-you-can-touch", featured:false,
  title:"Paint You Can Almost Touch",
  lede:"Some painters describe light; these ones build it. Paint troweled, dripped, loaded and left standing — surfaces with actual topography, where the picture casts its own shadows and reproduction always slightly lies.",
  cover:"the-jewish-bride",
  works:[
    { id:"the-jewish-bride", note:"The golden sleeve is sculpture. Van Gogh offered ten years of his life to keep looking." },
    { id:"self-portrait-with-two-circles", note:"Troweled like plaster, lit like a verdict." },
    { id:"the-starry-night", note:"The sky has a wake." },
    { id:"sunflowers", note:"Chrome yellow laid on like butter." },
    { id:"wheatfield-with-crows", note:"Each crow is one loaded brush-hit." },
    { id:"snow-storm-steamboat", note:"Paint whipped into actual weather." },
    { id:"full-fathom-five", note:"Nails, buttons, coins and cigarettes buried under the skin of paint." }] },

{ id:"rooms-you-can-almost-enter", featured:false,
  title:"Rooms You Can Almost Enter",
  lede:"The interior is painting's quietest genre and its most inhabited: light through a left-hand window, bread on a table, a bed that promises rest or refuses it. Nine rooms with the door left open.",
  cover:"the-art-of-painting",
  works:[
    { id:"the-milkmaid", note:"Bread, milk, a nail hole in the wall — inventory as poetry." },
    { id:"the-art-of-painting", note:"The curtain is pulled back for you alone." },
    { id:"woman-in-blue", note:"Morning light, a letter, held breath." },
    { id:"the-lacemaker", note:"Twenty-four centimetres of total concentration." },
    { id:"the-bedroom", note:"Painted flat on purpose — 'to rest the brain.'" },
    { id:"the-night-cafe", note:"A room you enter and immediately want to leave. That's the achievement." },
    { id:"las-meninas", note:"The room looks back." },
    { id:"the-arnolfini-portrait", note:"Every object a witness; the mirror holds two more." },
    { id:"the-red-studio", note:"A room dissolved into one long red thought." }] },

{ id:"ways-of-water", featured:false,
  title:"Ways of Water",
  lede:"Water is painting's oldest impossible assignment: it moves, it mirrors, it swallows light whole. Every solution looks nothing like the others — a claw of foam, a shorthand of broken color, a sea called as courtroom witness.",
  cover:"the-great-wave-off-kanagawa",
  works:[
    { id:"the-great-wave-off-kanagawa", note:"The claw that hangs forever." },
    { id:"impression-sunrise", note:"The harbor that named a movement." },
    { id:"la-grenouillere", note:"Water's modern shorthand, invented in a few afternoons." },
    { id:"the-storm-on-the-sea-of-galilee", note:"Rembrandt puts you in the boat — one of the faces is his." },
    { id:"slave-ship", note:"The sea as courtroom." },
    { id:"view-of-delft", note:"A city doubled in its own harbor." },
    { id:"amida-falls", note:"A waterfall falling as strings of beads." },
    { id:"bridge-over-a-pond-of-water-lilies", note:"The pond, back when it still had edges." },
    { id:"fishermen-at-sea", note:"Black water breathing under moonlight." }] },

{ id:"faces-that-follow-you", featured:false,
  title:"Faces That Follow You",
  lede:"Museums are full of portraits you walk past; these are the ones that walk after you. Ten gazes engineered to outlast their sitters — level, sideways, gilded, wounded — each still conducting its half of the conversation.",
  cover:"girl-with-a-pearl-earring",
  works:[
    { id:"mona-lisa", note:"The gaze that started the whole argument." },
    { id:"girl-with-a-pearl-earring", note:"She turns for you, forever mid-question." },
    { id:"portrait-of-innocent-x", note:"'Too true,' said the sitter — and kept it anyway." },
    { id:"juan-de-pareja", note:"Level, unhurried, unforgettable." },
    { id:"lady-with-an-ermine", note:"Both of them track something off-frame — the same thing." },
    { id:"ginevra-de-benci", note:"Leonardo's first psychological portrait: she is already tired of you." },
    { id:"self-portrait-with-cigarette", note:"Munch materializes out of his own smoke." },
    { id:"adele-bloch-bauer-i", note:"A face surviving its own flood of gold." },
    { id:"thorn-necklace-hummingbird", note:"Frida stares you down with a dead hummingbird at her throat." },
    { id:"man-in-a-red-turban", note:"Probably van Eyck. Definitely watching." }] },

{ id:"the-gold-standard", featured:false,
  title:"The Gold Standard",
  lede:"Gold entered painting as heaven's color and never fully left — it just changed employers: Byzantine icons, Flemish altarpieces, Viennese desire, American celebrity. What gold means keeps shifting; what it does to a room does not.",
  cover:"the-kiss",
  works:[
    { id:"the-trinity", note:"Where gold still means heaven, not money." },
    { id:"ghent-altarpiece", note:"Oil glazes that make actual gold look poor beside them." },
    { id:"the-jewish-bride", note:"Gold as thick paint, not leaf — light you could trip over." },
    { id:"the-kiss", note:"Gold leaf as the temperature of desire." },
    { id:"adele-bloch-bauer-i", note:"A society portrait promoted to icon." },
    { id:"danae-klimt", note:"The god arrives as a rain of gold. Klimt entirely approves." },
    { id:"tree-of-life-stoclet", note:"The family trade — his father was a gilder — made immortal." },
    { id:"beethoven-frieze", note:"A choir of angels waiting at the end of a gold corridor." },
    { id:"gold-marilyn-monroe", note:"A Byzantine icon of celebrity, painted by an altar boy." }] }
,

/* ---- Actuality, September 2026 (docs/ACTUALITY.md, product type 2) ----
   The blockbuster-news list. The news is the door; the atlas is the room. No
   image here is new and none illustrates the news — it cannot, and that
   constraint is what forces the list to answer out of the collection instead.
   Tone: light, because a basketball signing carries it. Goya's king is the one
   entry written straight, and the essay says why. */
{ id:"the-king-goes-to-philadelphia", featured:false,
  title:"The King Goes to Philadelphia",
  lede:"On 24 July 2026 LeBron James signed with the 76ers — forty-one years old, twenty-fourth season, two years and eight million dollars. Philadelphia has been receiving famous arrivals for a while. Five things already hanging in the city, and one very uneasy king.",
  cover:"the-large-bathers",
  works:[
    { id:"woman-with-a-pearl-necklace",
      note:"Pennsylvania's own Impressionist, on a Philadelphia wall.",
      essay:"Cassatt was born in Allegheny City, Pennsylvania in 1844 and trained at the Pennsylvania Academy of the Fine Arts in Philadelphia before Paris got her — so of everything in this list she is the closest thing to a local. The picture is a loge scene: a woman in a theatre box, fan down, half-turned, and behind her a mirror carrying the rest of the auditorium in a golden blur. What it is actually about is the traffic of looking. She has come to watch, she is being watched, and Cassatt puts you in the third position, watching the watching. It is 81 by 60 centimetres, which is small for how much social machinery it contains." },
    { id:"the-large-bathers",
      note:"The biggest Cézanne on earth, and the city bought it.",
      essay:"Cézanne worked on the three Grandes Baigneuses through the last years of his life, and this is the largest — two and a half metres across, unfinished in the sense that Cézanne finished almost nothing. The bodies are not really bodies; they are wedges arranged to make the trees lean the way he wanted. Look at how the trunks bend inward at the top: he is building an architecture out of people, which is roughly what Cubism took from him a few years later. Philadelphia acquired it, and it is now the single object most often given as the reason to go to the museum at all." },
    { id:"the-burning-of-the-houses",
      note:"Turner watched Parliament burn, then sold the fire twice.",
      essay:"On the night of 16 October 1834 the Palace of Westminster caught fire and most of London came out to watch. Turner watched from the river, sketching in a rented boat, and afterwards made two oil paintings of it — this one, and another now in Cleveland. What he cared about was not the building. The architecture is barely there: it is a smear of heat, reflected in the Thames, with the crowd reduced to a dark shoal on the bridge. It is one of the moments where you can see nineteenth-century painting deciding that light matters more than things." },
    { id:"little-dancer-aged-fourteen",
      note:"Real hair, a real skirt, and Paris was appalled.",
      essay:"Degas modelled Marie van Goethem, a fourteen-year-old student at the Paris Opéra ballet school, in wax — then dressed the figure in a real bodice, a real tutu and a real hair ribbon, and put a wig of actual hair on her head. When it was shown in 1881 the critics were not charmed. They called her ugly, they read vice into her face, and one of them compared her to a specimen in a medical museum. The sculpture is now the most reproduced thing Degas ever made. Philadelphia's is one of the bronzes cast after his death; the wax original is in Washington." },
    { id:"the-boating-party",
      note:"Cassatt's most muscular picture: all effort, no small talk.",
      essay:"This is the other Cassatt here and the tougher one. A man rows, his back filling the bottom-left corner in a single dark mass, and a woman holds a child who is sprawled and heavy in the way real children are. The composition is straight out of the Japanese prints Cassatt had been studying: the high viewpoint, the boat sliced by the frame, the flat blocks of colour with no shadow in them. Nobody is charming anybody. It is a picture about physical work and the weight of a tired kid, painted by an artist usually filed under tenderness." },
    { id:"charles-iv-of-spain-and-his-family",
      note:"A king who ordered his own portrait, and got this one.",
      essay:"The one non-Philadelphian here, on the strength of a nickname. Goya painted the Spanish royal family in 1800–01 at nearly three metres wide, and the result has puzzled people ever since: the king is soft and vacant, the queen is placed dead centre where the monarch should be, and the whole group stands in a flat brown gloom, wearing a fortune in sashes and medals. Goya himself is at the back-left in shadow at his easel — the same trick Velázquez pulls in Las Meninas, quoted deliberately. Whether he was mocking them or simply painting what he saw is still argued; the court accepted it and paid." }
  ] }

];
