/* PIGMENT — taxonomy: movements, techniques, eras, nations.
   Movements & techniques may have a `parent` id → branches and sub-branches. */

window.MOVEMENTS = [
  // ---- Renaissance family ----
  { id:"renaissance", name:"Renaissance", parent:null, period:"c. 1400–1600", style:"renaissance",
    palette:["#7a2419","#caa45c","#2b3a52","#e8dcc3","#3e3a30"],
    blurb:"The rebirth of classical learning that re-founded European painting on perspective, anatomy and humanism.",
    desc:"Beginning in the Italian city-states and spreading north, the Renaissance replaced medieval flatness with mathematical perspective, observed anatomy and a new confidence in human dignity. Painters became scholars: dissecting bodies, studying optics and antiquity, and elevating their craft from guild trade to liberal art. Its branches range from the grandeur of Rome and Florence to the oil-glazed precision of the North." },
  { id:"high-renaissance", name:"High Renaissance", parent:"renaissance", period:"c. 1490–1527", style:"renaissance",
    palette:["#7a1f2b","#1f3a5f","#d9b46a","#e9ddc8","#5b7a5e"],
    blurb:"The brief, blazing summit — Leonardo, Michelangelo and Raphael working at once.",
    desc:"For roughly three decades, centred on Florence and Rome, painting reached an equilibrium of harmony, balance and idealised naturalism that Europe would measure itself against for four centuries. It ended abruptly with the Sack of Rome in 1527, but its protagonists had already become the very definition of artistic genius." },
  { id:"northern-renaissance", name:"Northern Renaissance", parent:"renaissance", period:"c. 1430–1580", style:"renaissance",
    palette:["#4a3b28","#86683f","#c7b287","#2f3d34","#ece4d2"],
    blurb:"The Renaissance north of the Alps — oil paint, microscopic detail and moral imagination.",
    desc:"Flemish, Dutch and German masters matched Italian idealism with something different: jewel-like oil technique, obsessive surface detail, print culture and a taste for everyday life, landscape and moral allegory. Dürer carried Italian theory home to Nuremberg; Bruegel and Bosch built entire worlds the Italians never imagined." },
  { id:"mannerism", name:"Mannerism", parent:"renaissance", period:"c. 1520–1600", style:"renaissance",
    palette:["#5e2430","#7b8fb0","#cfa44e","#2b3a52","#e3d5b8"],
    blurb:"Elegance pushed past nature — elongated figures, acid colour, deliberate strangeness.",
    desc:"After perfection, what next? Mannerist painters answered with sophistication: serpentine poses, impossible anatomy, crowded compositions and hyper-refined artifice. Long dismissed as decadent, the style is now read as the first avant-garde — El Greco's flame-like saints feel closer to Expressionism than to Raphael." },
  { id:"venetian-school", name:"Venetian School", parent:"renaissance", period:"c. 1480–1600", style:"renaissance",
    palette:["#7a2419","#c4541f","#e0a95e","#2b3a52","#efe1c4"],
    blurb:"Colore over disegno — Venice's painters built form from colour and light itself.",
    desc:"While Florence drew, Venice painted. Titian, Tintoretto and Veronese exploited the new canvas-and-oil medium to make colour, texture and atmosphere the very structure of a picture, painting wet-into-wet with unprecedented freedom. Every loose, sensuous brushstroke from Rubens to de Kooning descends from this lagoon." },

  // ---- Baroque family ----
  { id:"baroque", name:"Baroque", parent:null, period:"c. 1600–1750", style:"baroque",
    palette:["#120e0a","#5e1f1a","#b06a32","#d9b27c","#26343f"],
    blurb:"Drama, darkness and ecstasy — painting as theatre for the Counter-Reformation age.",
    desc:"Born in Rome around 1600, the Baroque weaponised emotion: raking light, violent diagonals, saints caught mid-miracle and beggars cast as apostles. From Caravaggio's tenebrous realism to Rubens's swirling abundance, it made viewers participants rather than spectators, and spread from papal chapels to Protestant merchant parlours." },
  { id:"dutch-golden-age", name:"Dutch Golden Age", parent:"baroque", period:"c. 1610–1680", style:"baroque",
    palette:["#1a140e","#4a3520","#9c6b2f","#d9aa4e","#e8d9b0"],
    blurb:"A republic of pictures — merchants, maids and windmills painted for the open market.",
    desc:"In the newly independent, Calvinist Netherlands, painting left the church and entered the home. An open art market produced unheard-of specialisation — portraits, still lifes, seascapes, tavern scenes — and two of painting's supreme poets of light: Rembrandt and Vermeer. Millions of pictures were produced; ordinary life became a worthy subject forever." },
  { id:"flemish-baroque", name:"Flemish Baroque", parent:"baroque", period:"c. 1600–1670", style:"baroque",
    palette:["#a8412e","#e0b380","#3b5570","#d9cdb4","#5e3424"],
    blurb:"Antwerp's grand manner — Rubens's workshop and the most opulent painting in Europe.",
    desc:"In the Catholic southern Netherlands, painting stayed monumental: altarpieces, royal allegories and hunting scenes executed with athletic brushwork and shameless sensuality. Rubens ran Antwerp like a multinational of images, and his pupil Van Dyck exported the style to define English aristocratic portraiture." },

  // ---- 18th century ----
  { id:"rococo", name:"Rococo", parent:null, period:"c. 1715–1780", style:"rococo",
    palette:["#a8c4b8","#d9b4be","#cfc49a","#8aa7c4","#f0e8d8"],
    blurb:"Powdered, pastel and pleasure-bound — the art of the aristocratic fête.",
    desc:"After Louis XIV's pompous sun set, French art relaxed into intimacy: gardens of flirtation, boudoir mythologies, silver-pink palettes and brushwork like whipped cream. Watteau invented its bittersweet poetry, Fragonard its mischief. The Revolution would guillotine its patrons — and its reputation — but the sheer painterly joy survives." },
  { id:"neoclassicism", name:"Neoclassicism", parent:null, period:"c. 1760–1830", style:"neoclassical",
    palette:["#8a1f2b","#3b5a8a","#d9c49a","#2a2622","#e8e0cc"],
    blurb:"Virtue in marble light — antiquity reborn as moral and political theatre.",
    desc:"Fuelled by the excavation of Pompeii and Enlightenment ideals, Neoclassicism scrubbed away Rococo froth in favour of severe contours, frieze-like compositions and Roman virtue. In David's hands it became the official art of the French Revolution and then of Napoleon — painting as civic instruction, line as law." },
  { id:"romanticism", name:"Romanticism", parent:null, period:"c. 1790–1850", style:"romantic",
    palette:["#9aacb8","#d9d3c4","#5e6e7a","#3a4450","#e8e4d8"],
    blurb:"The sublime and the storm — feeling enthroned over reason.",
    desc:"Romantic painters turned from civic virtue to inner weather: shipwrecks, fog-bound wanderers, revolutions, nightmares and the terror of nature's scale. Turner dissolved the world into light, Friedrich into longing, Goya into darkness. The movement's true subject was the modern self — solitary, feeling, and small before the infinite." },
  { id:"ukiyo-e", name:"Ukiyo-e", parent:null, period:"c. 1650–1880", style:"ukiyoe",
    palette:["#1f3a5f","#5e8ab0","#e8e0c8","#b0b8b4","#2a2c30"],
    blurb:"Pictures of the floating world — Japan's woodblock art of waves, actors and Mount Fuji.",
    desc:"Ukiyo-e prints captured Edo Japan's pleasure districts, landscapes and legends in flat colour and flowing line, produced collaboratively by designer, carver and printer. When the prints reached Europe in the 1860s as packing paper and curiosities, they detonated Western perspective — Monet, Degas, Van Gogh and Toulouse-Lautrec never recovered." },

  // ---- Realism family ----
  { id:"realism", name:"Realism", parent:null, period:"c. 1840–1880", style:"tonal",
    palette:["#2e3a2c","#5e6e4a","#8a6e46","#d9cfb4","#1d1a16"],
    blurb:"Paint what you see — labourers and stone-breakers given the scale of kings.",
    desc:"Rejecting both academic mythology and Romantic melodrama, Realists insisted that modern, ordinary life was the only honest subject. Courbet's peasants on history-painting canvases scandalised Paris precisely because they were not idealised. The movement's democratic premise — that truth outranks beauty — underwrites nearly all modern art." },
  { id:"barbizon-school", name:"Barbizon School", parent:"realism", period:"c. 1830–1870", style:"tonal",
    palette:["#9a8a5e","#d9c890","#6e5a3a","#a8b09a","#3e3a2a"],
    blurb:"Painters in the forest of Fontainebleau, sketching nature face to face.",
    desc:"Settling in the village of Barbizon, these painters left the studio for the forest and field, treating landscape and peasant labour with unsentimental directness. Their plein-air habits and tonal palettes laid the path the Impressionists would sprint down a generation later." },
  { id:"american-realism", name:"American Realism", parent:"realism", period:"c. 1900–1960", style:"metaphysical",
    palette:["#2e5e52","#e8d9a8","#c4763e","#1d2630","#9ab0a8"],
    blurb:"Diners, gas stations and morning light — the poetry of American solitude.",
    desc:"American Realists painted the new world of cities, motels and movie houses without European varnish. In Hopper's hands the style became metaphysics: light falling on an empty street, figures together yet alone — the loneliness of modern life given permanent form." },

  // ---- Impressionism and after ----
  { id:"impressionism", name:"Impressionism", parent:null, period:"c. 1860–1890", style:"impressionist",
    palette:["#9ab8d9","#b4d9c4","#e8c8d4","#f0e8c8","#7a8ab0"],
    blurb:"Light, caught alive — broken colour painted outdoors at the speed of seeing.",
    desc:"Mocked into existence by a critic sneering at Monet's 'Impression, Sunrise', the Impressionists abandoned the studio, black paint and finished surfaces to chase fugitive light with strokes of pure colour. Their eight independent exhibitions (1874–1886) broke the Salon's monopoly and invented the modern artist-led movement." },
  { id:"post-impressionism", name:"Post-Impressionism", parent:null, period:"c. 1885–1910", style:"postimpressionist",
    palette:["#1a3a6b","#f4c430","#2e7d32","#c75b39","#e8e3d3"],
    blurb:"After the impression — colour and form bent to structure, symbol and feeling.",
    desc:"The generation after Impressionism kept its bright palette but rejected its objectivity. Cézanne rebuilt nature into geometry, Van Gogh turned brushwork into emotion, Gauguin into symbol, Seurat into science. Four private revolutions that, together, opened every door of twentieth-century art." },
  { id:"neo-impressionism", name:"Neo-Impressionism", parent:"post-impressionism", period:"c. 1884–1900", style:"pointillist",
    palette:["#7a9ab8","#a8c49a","#e8d9a8","#d9886e","#4a5a6e"],
    blurb:"Pointillism — optics as method, the dot as atom of light.",
    desc:"Seurat replaced the Impressionists' instinct with system: tiny dots of unmixed pigment, calculated from colour theory, fusing in the viewer's eye. The technique — pointillism or divisionism — made painting laboratory-precise while producing images of strange, frozen serenity." },
  { id:"synthetism", name:"Synthetism", parent:"post-impressionism", period:"c. 1888–1900", style:"fauvist",
    palette:["#c4542e","#e89a3e","#6e3a5e","#2e6e5a","#f0d9a8"],
    blurb:"Flat colour, bold outline — painting from memory and meaning, not observation.",
    desc:"Around Gauguin in Pont-Aven, painters 'synthesised' appearance, feeling and decorative form: zones of flat colour bounded by dark contour, like cloisonné enamel. By licensing colour to mean rather than describe, Synthetism fed directly into Symbolism, the Nabis and Fauvism." },
  { id:"symbolism", name:"Symbolism", parent:null, period:"c. 1880–1910", style:"surreal",
    palette:["#3e3a52","#8a3a4e","#caa45c","#26424e","#d9c8a4"],
    blurb:"The inward turn — dreams, myths and moods painted instead of facts.",
    desc:"Symbolists held that a painting should evoke, not record: anxiety, eros, death and the sacred rendered through suggestive colour and mythic imagery. From Munch's psychic landscapes to Klimt's gilded allegories, Symbolism is the bridge between Romanticism and both Expressionism and Surrealism." },
  { id:"art-nouveau", name:"Art Nouveau", parent:null, period:"c. 1890–1910", style:"ornament",
    palette:["#caa43e","#e8cd7a","#8a5e2e","#3e3a30","#a83a4e"],
    blurb:"The whiplash line — art as total ornament, from posters to palaces.",
    desc:"A deliberately 'new art' that refused the academy and the factory alike, Art Nouveau wound organic, botanical line through architecture, glass, posters and painting. It dreamed of dissolving the border between fine and decorative art — a dream Klimt's golden Vienna very nearly realised." },
  { id:"vienna-secession", name:"Vienna Secession", parent:"art-nouveau", period:"1897–1914", style:"ornament",
    palette:["#caa43e","#e8cd7a","#3e3a30","#a83a4e","#e8dcc4"],
    blurb:"'To every age its art, to art its freedom' — Klimt's gilded rebellion.",
    desc:"Founded in 1897 with Klimt as first president, the Secession broke from Vienna's conservative artists' association to exhibit modern art on its own terms, building its own temple with a golden dome of laurel. Its ornamental splendour and frankness about desire scandalised and seduced the empire in equal measure." },

  // ---- Expressionism family ----
  { id:"expressionism", name:"Expressionism", parent:null, period:"c. 1905–1935", style:"expressionist",
    palette:["#e0427a","#2e8a8a","#e8a82e","#3e3a52","#1d1c22"],
    blurb:"The scream made visible — colour and distortion in service of raw feeling.",
    desc:"Expressionists painted not the world but the nerve it struck: jagged forms, clashing colour, faces as masks of anxiety or ecstasy. Rooted in Van Gogh and Munch and flowering in German cities before the First World War, it treated distortion as honesty — the outer image bent until it told the inner truth." },
  { id:"die-brucke", name:"Die Brücke", parent:"expressionism", period:"1905–1913", style:"expressionist",
    palette:["#e0427a","#2e8a8a","#e8a82e","#1d1c22","#e8dcc4"],
    blurb:"'The Bridge' — Dresden's young radicals of angular nudes and electric streets.",
    desc:"Four architecture students founded Die Brücke in 1905 to bridge old art and new life. They revived the woodcut's savage line, painted with house-paint urgency, and chronicled the modern city's glamour and alienation — Kirchner's Berlin street scenes remain its jagged masterpieces." },
  { id:"der-blaue-reiter", name:"Der Blaue Reiter", parent:"expressionism", period:"1911–1914", style:"abstract",
    palette:["#2e5eaa","#e8c43e","#c4302a","#2e8a5e","#1d1a20"],
    blurb:"'The Blue Rider' — Munich's spiritual expressionists, riding toward abstraction.",
    desc:"Gathered around Kandinsky and Franz Marc in Munich, the Blue Rider group believed colour and form could sound the soul directly, like music. Their almanac and exhibitions mixed folk art, children's drawings and the avant-garde; the war scattered them, but Kandinsky had already crossed into pure abstraction." },
  { id:"school-of-london", name:"School of London", parent:"expressionism", period:"c. 1945–1990", style:"expressionist",
    palette:["#c4542e","#1d1a18","#8a2634","#d9b894","#3e3a36"],
    blurb:"Paint as flesh — figurative intensity in the age of abstraction.",
    desc:"While the post-war world went abstract, a loose London circle — Bacon, Freud, Auerbach, Kossoff — doubled down on the human body, painted with unsparing, almost forensic intensity. Their wager paid off: figuration returned, and their portraits now read as the era's most visceral documents." },

  // ---- Early modernism ----
  { id:"fauvism", name:"Fauvism", parent:null, period:"1905–1908", style:"fauvist",
    palette:["#c4302a","#2e5eaa","#2e8a5e","#e8c43e","#f2e8d8"],
    blurb:"The wild beasts — colour unchained from description.",
    desc:"When Matisse and friends showed their blazing canvases in 1905, a critic dubbed them 'fauves' — wild beasts. Their crime: green-striped faces, vermilion trees, colour chosen for feeling and structure rather than fact. Fauvism lasted barely three years, but colour never went back in its cage." },
  { id:"cubism", name:"Cubism", parent:null, period:"c. 1907–1920", style:"cubist",
    palette:["#5e7286","#a8896e","#8a4a42","#3e3a36","#d9cdb4"],
    blurb:"The shattered eye — objects seen from everywhere at once.",
    desc:"Invented in tandem by Picasso and Braque, Cubism abandoned the single viewpoint that had governed painting since the Renaissance, splintering objects into facets and reassembling them on the flat canvas. With collage, it also let the real world — newsprint, wallpaper — into the picture. Modern art's central earthquake." },
  { id:"dada", name:"Dada", parent:null, period:"1916–1924", style:"cubist",
    palette:["#1a1a1a","#c4302a","#e8e0d0","#5e7286","#caa43e"],
    blurb:"Anti-art for a world at war — chance, collage and beautiful nonsense.",
    desc:"Born in a Zurich cabaret while Europe bled, Dada declared that a civilisation capable of the trenches deserved mockery, not masterpieces. Chance procedures, photomontage, readymades and absurdist performance redefined what could count as art — a question we have been answering ever since." },
  { id:"neo-dada", name:"Neo-Dada", parent:"dada", period:"c. 1953–1962", style:"pop",
    palette:["#b03a32","#e8e0c8","#2e3e8a","#caa45c","#3e3a36"],
    blurb:"Flags, targets and junk — Dada's questions asked again in post-war America.",
    desc:"Johns and Rauschenberg revived Dada's found objects and deadpan irony just as Abstract Expressionism's heroics were hardening into formula. By painting things 'the mind already knows' — flags, numbers, targets — Johns turned painting into philosophy and opened the road to Pop." },

  // ---- Abstraction family ----
  { id:"abstract-art", name:"Abstraction", parent:null, period:"c. 1910–today", style:"abstract",
    palette:["#2e5eaa","#e8c43e","#c4302a","#2e8a5e","#1d1a20"],
    blurb:"Painting freed from depiction — colour, line and form as the entire subject.",
    desc:"Around 1910, several painters in several countries — Kandinsky, Malevich, Mondrian, and before any of them Hilma af Klint — concluded that painting need not picture anything at all. Abstraction became modernity's lingua franca, ranging from geometric order to gestural storm, from the spiritual to the purely optical." },
  { id:"suprematism", name:"Suprematism", parent:"abstract-art", period:"1915–1925", style:"geometric",
    palette:["#1a1a1a","#c4302a","#f4f1e8","#3e3a36","#caa43e"],
    blurb:"The zero of form — Malevich's black square and the supremacy of pure feeling.",
    desc:"Unveiled in revolutionary Petrograd, Malevich's floating squares and bars proposed art's absolute degree zero: no objects, no horizon, only 'the supremacy of pure feeling'. Hung across a corner like a Russian icon, the Black Square remains modern art's most radical full stop — and starting point." },
  { id:"de-stijl", name:"De Stijl", parent:"abstract-art", period:"1917–1931", style:"mondrian",
    palette:["#e02e2e","#2e50c4","#f0c82e","#f4f1e8","#1a1a1a"],
    blurb:"Right angles and primary colours — a Dutch grammar for universal harmony.",
    desc:"De Stijl ('The Style') reduced art to horizontals, verticals and primary colours, seeking a visual harmony so universal it could rebuild the post-war world — paintings, chairs, houses, cities. Mondrian kept the faith with monastic rigour, famously breaking with the group when diagonals were admitted." },

  // ---- Surrealism family ----
  { id:"metaphysical-painting", name:"Metaphysical Painting", parent:null, period:"c. 1911–1920", style:"metaphysical",
    palette:["#2e8a7a","#d9a83e","#b05e32","#3e4a6e","#e8d9b4"],
    blurb:"Empty squares, long shadows — de Chirico's enigmas before Surrealism's dreams.",
    desc:"In de Chirico's deserted piazzas — arcades, mannequins, trains forever leaving — ordinary things radiate inexplicable menace. The 'pittura metafisica' he and Carrà devised supplied Surrealism with its entire stagecraft a decade before the movement existed." },
  { id:"surrealism", name:"Surrealism", parent:null, period:"1924–c. 1966", style:"surreal",
    palette:["#d9b894","#8aa7c4","#5e4a32","#e8d4a8","#2a3440"],
    blurb:"The dream made flesh — painting dictated by the unconscious.",
    desc:"Founded by poet André Breton on Freud's couch, Surrealism set out to liberate the unconscious: dream imagery rendered with hallucinatory precision (Dalí, Magritte) or coaxed out by automatic techniques and chance (Ernst, Miró). Its images escaped the gallery long ago — advertising, cinema and the word 'surreal' itself are its monuments." },

  // ---- Between the wars ----
  { id:"art-deco", name:"Art Deco", parent:null, period:"c. 1920–1939", style:"artdeco",
    palette:["#9aa8b8","#c43e4e","#2a3440","#e8d9c0","#5e7286"],
    blurb:"Machine-age glamour — chrome curves, sharp suits and cocktail speed.",
    desc:"Named for the 1925 Paris exposition, Art Deco streamlined Cubism's angles into luxury: skyscrapers, ocean liners, jewellery and Lempicka's polished, perfumed portraits. It is modernism with lipstick — geometry in the service of glamour." },
  { id:"naive-art", name:"Naïve Art", parent:null, period:"c. 1885–today", style:"naive",
    palette:["#1f4a2e","#3e7a46","#8ab05e","#d9b94e","#c4542e"],
    blurb:"The self-taught eye — flat perspective, fierce sincerity, unforgettable visions.",
    desc:"Painters outside academic training — toll-collector Rousseau above all — turned 'wrong' perspective and licked surfaces into a virtue: images of dreamlike clarity and total conviction. The modernists who first laughed soon recognised what they were seeing — freedom — and collected it greedily." },
  { id:"muralism", name:"Mexican Muralism", parent:null, period:"c. 1920–1960", style:"fauvist",
    palette:["#b0703a","#6e8a5a","#c4423e","#e8cd9a","#3e3a30"],
    blurb:"History painted wall-sized — art for the people, in fresco and fury.",
    desc:"After the Mexican Revolution, the state commissioned painters to tell the nation's story on public walls. Rivera, Orozco and Siqueiros revived Renaissance fresco at industrial scale, fusing indigenous heritage, labour and politics into art that needed no museum — only a wall and a passer-by." },
  { id:"harlem-renaissance", name:"Harlem Renaissance", parent:null, period:"c. 1920–1945", style:"fauvist",
    palette:["#c4302a","#f0c82e","#2e50c4","#1a1a1a","#e8dcc4"],
    blurb:"Black modernism in full voice — rhythm, migration and pride on canvas.",
    desc:"Centred in 1920s–30s Harlem, this flowering of Black literature, music and art claimed modernism on its own terms. In painting, Jacob Lawrence's flat, syncopated panel cycles gave the Great Migration its definitive visual epic — history painting reinvented in tempera and rhythm." },
  { id:"american-modernism", name:"American Modernism", parent:null, period:"c. 1910–1950", style:"postimpressionist",
    palette:["#e8c8d4","#d97a8a","#f0e4d0","#a8c4b8","#8a4a52"],
    blurb:"A new world's new forms — skyscrapers, deserts and O'Keeffe's monumental flowers.",
    desc:"American painters absorbed European modernism and turned it on native ground: Manhattan's geometry, New Mexico's bones and mesas, the close-up forms of nature enlarged to billboard scale. O'Keeffe's flowers and skulls made the style's case: abstraction and the real need not be enemies." },

  // ---- Post-war ----
  { id:"abstract-expressionism", name:"Abstract Expressionism", parent:null, period:"c. 1943–1965", style:"gestural",
    palette:["#1a1a1a","#e8e0d0","#c4763e","#5e7286","#caa43e"],
    blurb:"The New York School — painting as event, canvas as arena.",
    desc:"In post-war New York, painters fused Surrealist automatism with mural scale to make the first American movement to lead world art. Whether flung in arcs of enamel or floated in fields of colour, the picture became a record of its own making — 'not a picture but an event', as critic Harold Rosenberg wrote." },
  { id:"action-painting", name:"Action Painting", parent:"abstract-expressionism", period:"c. 1947–1960", style:"drip",
    palette:["#1a1a1a","#e8e0d0","#c4763e","#5e7286","#caa43e"],
    blurb:"The gesture is the picture — dripped, flung, scraped, danced.",
    desc:"For Pollock, de Kooning, Kline and Mitchell, the canvas recorded a performance: the body's movement preserved in paint. Pollock's drip method — canvas on the floor, paint trailed from sticks and hardened brushes — remains the emblem: painting you can almost replay like a film of its own making." },
  { id:"color-field", name:"Colour Field", parent:"abstract-expressionism", period:"c. 1947–1970", style:"colorfield",
    palette:["#c43e2a","#e87a2e","#8a2634","#5e2a52","#1d1a18"],
    blurb:"Vast breathing colour — the sublime, stained into canvas.",
    desc:"The quieter wing of Abstract Expressionism abandoned gesture for immersion: Rothko's hovering rectangles, Newman's zips, Frankenthaler's poured stains. Scale was the argument — canvases big enough to fill vision and induce something like awe. Rothko wanted viewers to stand close enough to be inside." },

  // ---- Pop & after ----
  { id:"pop-art", name:"Pop Art", parent:null, period:"c. 1955–1975", style:"pop",
    palette:["#e0427a","#f0c82e","#2e8a8a","#c4302a","#1a1a1a"],
    blurb:"Soup cans and comic strips — mass culture promoted to museum walls.",
    desc:"Pop turned painting's eye from the soul to the supermarket: advertising, celebrity, comics and packaging rendered with commercial techniques like silkscreen and Ben-Day dots. Warhol's deadpan and Lichtenstein's romance panels asked the era's sharpest question — in a world of images, what exactly is an original?" },
  { id:"neo-expressionism", name:"Neo-Expressionism", parent:null, period:"c. 1978–1990", style:"expressionist",
    palette:["#1a1a1a","#e8c43e","#c4302a","#2e8a8a","#f0ece0"],
    blurb:"The return of the brush — raw, mythic, big painting after minimalism's silence.",
    desc:"At the end of the 1970s, painting came roaring back: huge, urgent, figurative and unashamedly emotional. Kiefer excavated German memory in lead and ash; Basquiat fused graffiti, anatomy and jazz into crowned heads. Critics called it regression; the public called it alive." },
  { id:"contemporary-art", name:"Contemporary Painting", parent:null, period:"c. 1980–today", style:"contemporary",
    palette:["#e0427a","#7ac4e8","#3e4a5e","#e8e4d8","#2e8a5e"],
    blurb:"Painting now — global, plural, and arguing with its own history.",
    desc:"Contemporary painting has no single style — that is its style. Richter moves between photo-blur and squeegee abstraction; Marshall repaints the Western canon with Black protagonists; Mehretu layers maps into storms. What unites them is self-awareness: every canvas knows the five centuries that came before it." },
  { id:"street-art", name:"Street Art", parent:"contemporary-art", period:"c. 1975–today", style:"street",
    palette:["#1a1a1a","#c4302a","#8a8a8a","#e8e4d8","#3e3e3e"],
    blurb:"From subway car to auction house — art that never asked permission.",
    desc:"Graffiti's energy, stencils' speed and the city as canvas: street art moved from outlaw signature to global language inside a generation. Haring chalked subways, Basquiat crossed into galleries, and Banksy — identity still unknown — turned the stunt itself into the artwork." },
  { id:"superflat", name:"Superflat", parent:"contemporary-art", period:"2000–today", style:"pop",
    palette:["#e0427a","#7ac4e8","#f0c82e","#2e8a5e","#f4f1e8"],
    blurb:"Anime meets art history — Murakami's theory of Japan's flattened image world.",
    desc:"Coined by Murakami in 2001, Superflat links Edo-period flatness, anime and otaku culture, and consumer society into one lineage — then erases the wall between fine art and merchandise on purpose. Smiling flowers on museum walls and handbags alike: that's the argument." },

  // ---- expansion: new schools & branches ----
  { id:"ottoman-miniature", name:"Ottoman Miniature", parent:null, period:"c. 1450–1800", style:"ornament",
    palette:["#1f6e8a","#c4302a","#caa43e","#2e4a3e","#e8dcc0"],
    blurb:"The sultan's picture-workshops — history, festivals and cities painted jewel-bright on paper.",
    desc:"In the nakkaşhane, the palace workshop, teams of miniaturists illustrated chronicles, campaign routes and forty-day festivals in flat, luminous colour — art meant for the turning page, not the wall. From Matrakçı Nasuh's figure-less city portraits to Levni's tulip-era elegance, it is one of painting's great parallel traditions, with its own rules of space, time and gold." },
  { id:"orientalism", name:"Orientalism", parent:null, period:"c. 1820–1910", style:"metaphysical",
    palette:["#1f6e8a","#d9a83e","#b05e32","#3e4a6e","#e8d9b4"],
    blurb:"Europe paints the 'East' — and Osman Hamdi Bey paints back.",
    desc:"Academic Europe filled the Salons with imagined harems and bazaars: technically dazzling, often fantasy. The movement's most interesting painter worked from inside it — Osman Hamdi Bey, Ottoman archaeologist and museum founder, used Orientalist technique to show his own culture reading, debating and thinking, quietly correcting the genre from within." },
  { id:"pre-raphaelites", name:"Pre-Raphaelites", parent:null, period:"1848–c. 1900", style:"renaissance",
    palette:["#2e6e5e","#a83a4e","#caa43e","#3b5a8a","#e8dcc4"],
    blurb:"The brotherhood that rewound painting to before Raphael — jewel colour, medieval longing.",
    desc:"Three young Londoners founded a secret 'Brotherhood' in 1848 to overthrow academic convention with truth to nature, blazing colour on wet white ground, and subjects from Dante, Shakespeare and Arthurian legend. Scandalous, then beloved, the Pre-Raphaelites became Victorian Britain's defining image-makers — and, through Morris and Burne-Jones, godparents of Art Nouveau." },
  { id:"hudson-river-school", name:"Hudson River School", parent:"romanticism", period:"c. 1825–1880", style:"romantic",
    palette:["#7a9a6e","#e8c87a","#5e4a32","#a8c4d9","#3e5238"],
    blurb:"America's first art movement — wilderness as cathedral, canvas as panorama.",
    desc:"Painting the Hudson Valley, the Rockies and beyond at theatrical scale, these artists made landscape the young republic's national epic. Bierstadt toured his giant canvases like blockbuster films, complete with curtains and ticket sales — sublime nature as both worship and entertainment." },
  { id:"les-nabis", name:"Les Nabis", parent:"post-impressionism", period:"1888–1900", style:"fauvist",
    palette:["#8a5e3e","#d9a8b8","#5e7250","#caa45c","#e8dcc8"],
    blurb:"'The prophets' — Gauguin's lesson turned into wallpapered, intimate magic.",
    desc:"A secret society of young Paris painters took Gauguin's flat colour and turned it inward: interiors, gardens, mothers and lamplight, patterned like the wallpaper they loved. Bonnard and Vuillard made domesticity radiant — 'a picture, before being a battle horse or a nude, is essentially a flat surface covered with colours,' as member Maurice Denis famously decreed." },
  { id:"young-poland", name:"Young Poland", parent:"symbolism", period:"c. 1890–1918", style:"ornament",
    palette:["#5e7250","#a83a4e","#caa45c","#3e3a52","#e8dcc4"],
    blurb:"Młoda Polska — a partitioned nation dreams itself in symbol, pastel and stained glass.",
    desc:"With Poland erased from the map, its artists painted the nation into being: Malczewski's fauns and chained Polonias, Wyspiański's stained-glass visions and pastel children, Boznańska's misty portraits. Centred on Kraków, Young Poland fused Symbolism, folk art and Art Nouveau into one of Europe's most distinctive fin-de-siècle schools." },
  { id:"orphism", name:"Orphism", parent:"cubism", period:"c. 1912–1920", style:"abstract",
    palette:["#c4302a","#2e50c4","#f0c82e","#2e8a5e","#f4f1e8"],
    blurb:"Cubism set spinning — pure colour discs named after the poet of music.",
    desc:"Apollinaire coined 'Orphism' for the Delaunays' rainbow-wheeled abstraction: Cubism's structure flooded with prismatic 'simultaneous contrasts' of colour. Sonia Delaunay carried it off the canvas entirely — onto quilts, dresses, cars and book bindings — decades before anyone said 'design crossover.'" },
  { id:"new-objectivity", name:"New Objectivity", parent:"expressionism", period:"c. 1920–1933", style:"expressionist",
    palette:["#3e4a52","#8a3a32","#caa45c","#1d1c22","#d9cdb8"],
    blurb:"Weimar Germany in a cold mirror — satire sharpened to a surgical edge.",
    desc:"After Expressionism's scream came the icy stare: war profiteers, maimed veterans and cabaret nights painted with deliberate, unforgiving precision. Otto Dix and George Grosz made the style a moral instrument; the Nazis, recognising themselves, burned what they could find of it." },
  { id:"regionalism", name:"Regionalism", parent:"american-realism", period:"c. 1928–1945", style:"naive",
    palette:["#7a9a5e","#d9c890","#8a5e3a","#3e5238","#e8e0c8"],
    blurb:"American Gothic and the painted Midwest — homegrown art for hard times.",
    desc:"In the Depression, a group of painters turned from Paris to the prairie: rolling Iowa fields, threshing crews, small-town faces. Grant Wood's stern farm couple became the most parodied image in American art — proof that a region painted honestly becomes universal." },
  { id:"minimalism", name:"Minimalism", parent:null, period:"c. 1960–1975", style:"geometric",
    palette:["#d9d3c4","#a8b4b8","#8a9bb0","#e8e4d8","#5e6e7a"],
    blurb:"Nothing extra — the grid, the field, the almost-nothing that holds everything.",
    desc:"Minimalism stripped art to elemental order: repeated units, bare surfaces, the object itself. In painting, Agnes Martin's hand-drawn grids showed the style's secret — what looks like geometry from afar dissolves, up close, into tremulous, human pencil lines and washes 'about innocence of mind.'" },
  { id:"op-art", name:"Op Art", parent:"abstract-art", period:"c. 1960–1975", style:"geometric",
    palette:["#1a1a1a","#f4f1e8","#2e50c4","#e0427a","#f0c82e"],
    blurb:"Painting that attacks the eye — grids that bulge, vibrate and refuse to sit still.",
    desc:"Optical art weaponised perception: precisely calculated patterns that shimmer, warp and move while hanging perfectly still. Vasarely, its grand engineer, dreamed of an art reproducible as an alphabet — multiples for every home — and briefly, in the mid-sixties, op patterns swallowed fashion, album covers and an entire decade's look." },
  { id:"art-informel", name:"Art Informel & Tachisme", parent:"abstract-art", period:"c. 1945–1965", style:"gestural",
    palette:["#1d1c22","#3e5570","#caa45c","#8a2634","#e8e0d0"],
    blurb:"Europe's answer to Action Painting — the stain, the scratch, the lightning stroke.",
    desc:"In post-war Paris, painters abandoned geometry for raw matter and gesture: tachisme ('stain-ism'), lyrical abstraction, matter painting. Hans Hartung's whiplash black strokes — some made with garden sprayers and rakes — gave the movement its signature: energy itself, recorded at the speed of a nervous system." }
];

window.TECHNIQUES = [
  { id:"oil-painting", name:"Oil Painting", parent:null, style:"renaissance",
    palette:["#7a2419","#caa45c","#2b3a52","#e8dcc3","#3e3a30"],
    blurb:"Pigment in slow-drying oil — five centuries of painting's dominant medium.",
    desc:"Perfected in the fifteenth-century Netherlands, oil paint dries slowly enough to blend, layer and rework, and spans every effect from enamel smoothness to sculptural crust. Nearly every painter in this atlas reached for it; its sub-techniques — glazing, impasto, alla prima — are dialects of one language." },
  { id:"glazing", name:"Glazing", parent:"oil-painting", style:"renaissance",
    palette:["#5e1f1a","#b06a32","#d9b27c","#2b3a52","#e8dcc3"],
    blurb:"Transparent layers of colour, light passing through like stained glass.",
    desc:"Thin films of transparent paint laid over dried layers let light travel into the picture and bounce back, producing glows no mixed colour can match — Titian's crimsons, Vermeer's blue gowns, Rothko's breathing fields. Slow, patient, and luminous." },
  { id:"impasto", name:"Impasto", parent:"oil-painting", style:"postimpressionist",
    palette:["#1a3a6b","#f4c430","#2e7d32","#c75b39","#e8e3d3"],
    blurb:"Paint laid on thick — strokes you could read with your fingertips.",
    desc:"Impasto leaves paint standing in ridges and peaks, catching real light and recording the gesture that made it. Rembrandt built faces from it, Van Gogh turned it into handwriting, and Freud and Kiefer pushed it toward sculpture." },
  { id:"alla-prima", name:"Alla Prima", parent:"oil-painting", style:"impressionist",
    palette:["#23201c","#8a8276","#caa45c","#5e2a2a","#e8e0d0"],
    blurb:"'At first attempt' — wet-into-wet painting finished in one sitting.",
    desc:"Skipping the old layered process, alla prima painters work wet paint into wet, committing to each stroke. It rewards nerve and economy: Hals's flashing cuffs, Manet's black coats, Sargent's silk — bravura made permanent." },
  { id:"sfumato", name:"Sfumato", parent:"oil-painting", style:"renaissance",
    palette:["#3b2f1e","#6b5635","#a08552","#d6c39a","#5a6b5d"],
    blurb:"Leonardo's smoke — contours melted until they disappear.",
    desc:"From the Italian for 'smoked', sfumato blends tones so gradually that lines vanish, leaving forms to emerge from shadow. It is why the Mona Lisa's smile cannot be pinned down: the corners of mouth and eyes dissolve exactly where expression lives." },
  { id:"palette-knife", name:"Palette Knife", parent:"oil-painting", style:"tonal",
    palette:["#2e3a2c","#5e6e4a","#8a6e46","#d9cfb4","#1d1a16"],
    blurb:"Painting with the blade — slabs and scrapes instead of strokes.",
    desc:"Applying paint with a flexible steel blade gives broad, troweled planes and brusque honesty. Courbet scandalised the Salon with knife-built landscapes; the tool's descendants include de Kooning's scrapers and Richter's giant squeegees." },
  { id:"chiaroscuro", name:"Chiaroscuro", parent:null, style:"baroque",
    palette:["#120e0a","#5e1f1a","#b06a32","#d9b27c","#26343f"],
    blurb:"Light against dark — modelling the world out of shadow.",
    desc:"Italian for 'light-dark', chiaroscuro builds volume and drama through strong contrast. From Leonardo's soft modelling to Rembrandt's golden gloom, it is painting's oldest special effect: turn down the world, and turn up what matters." },
  { id:"tenebrism", name:"Tenebrism", parent:"chiaroscuro", style:"baroque",
    palette:["#0e0c0a","#5e1f1a","#b06a32","#d9b27c","#3a2e22"],
    blurb:"Darkness as stage — figures spotlit against engulfing black.",
    desc:"Chiaroscuro pushed to violence: backgrounds swallowed in black, figures blasted by a single raking light. Caravaggio invented the look, Artemisia Gentileschi and Georges de La Tour refined it, and cinema's film noir still runs on it." },
  { id:"fresco", name:"Fresco", parent:null, style:"renaissance",
    palette:["#2e4a62","#b06a4a","#d9b27c","#7a8e66","#e8dcc3"],
    blurb:"Painting into wet plaster — images fused with the wall itself.",
    desc:"In buon fresco, pigment is brushed onto fresh lime plaster and becomes part of the wall as it cures — no second chances, a day's patch at a time. The Sistine ceiling and Rivera's Detroit cycle prove its scale; its permanence is measured in centuries." },
  { id:"tempera", name:"Tempera", parent:null, style:"fauvist",
    palette:["#c4302a","#f0c82e","#2e50c4","#1a1a1a","#e8dcc4"],
    blurb:"Pigment bound in egg — the crisp, fast-drying medium oil replaced.",
    desc:"Egg tempera dries in seconds to a matte, luminous surface that never yellows, demanding precise hatched strokes. The medium of medieval panels and Botticelli, it was revived by modern painters — Jacob Lawrence's Migration Series owes its clean fire to it." },
  { id:"watercolor", name:"Watercolour", parent:null, style:"romantic",
    palette:["#f2d9a0","#e8a85e","#a8b8c4","#d97a3e","#f4ecd8"],
    blurb:"Pigment, water, white paper — the fastest route from eye to image.",
    desc:"Transparent washes over white paper give watercolour its inner light — and its terror: no overpainting, no taking back. Dürer made it serious, Turner made it sublime, and Sargent and O'Keeffe used it as a laboratory for risk." },
  { id:"pastel", name:"Pastel", parent:null, style:"impressionist",
    palette:["#d9b4be","#8a9bb0","#e8dcc4","#5e4a44","#c4763e"],
    blurb:"Pure pigment in a stick — drawing and painting in the same gesture.",
    desc:"Pastel is almost pure pigment, velvet-soft and immediate, sitting on the surface like coloured dust. Degas became its greatest modern master, layering and steaming it into smoky dancers; Cassatt and Toulouse-Lautrec kept its intimacy alive." },
  { id:"printmaking", name:"Printmaking", parent:null, style:"ukiyoe",
    palette:["#1f3a5f","#5e8ab0","#e8e0c8","#b0b8b4","#2a2c30"],
    blurb:"The multiplied image — art that travels, from woodcut to silkscreen.",
    desc:"Printmaking made images portable and affordable, spreading styles across continents centuries before the internet. Each process has its own voice: the woodcut's bold cut, etching's nervous line, lithography's crayon softness, silkscreen's flat punch." },
  { id:"etching", name:"Etching", parent:"printmaking", style:"tonal",
    palette:["#1a140e","#4a3520","#9c6b2f","#d9aa4e","#e8d9b0"],
    blurb:"Lines bitten by acid — printmaking's most painterly needle.",
    desc:"The artist draws through wax on a copper plate; acid bites the exposed lines; ink fills them for printing. Free as pen drawing but infinitely reworkable, etching gave us Rembrandt's luminous shadows and Goya's nightmares." },
  { id:"woodblock", name:"Woodcut", parent:"printmaking", style:"ukiyoe",
    palette:["#1f3a5f","#5e8ab0","#e8e0c8","#2a2c30","#b0b8b4"],
    blurb:"Carved, inked, pressed — the oldest and boldest print.",
    desc:"Cutting away wood to leave raised lines produces prints of stark graphic force. Dürer raised it to virtuosity, Japanese masters like Hokusai perfected colour registration across multiple blocks, and the Expressionists revived its splintered roughness as a modern voice." },
  { id:"lithography", name:"Lithography", parent:"printmaking", style:"pop",
    palette:["#c4302a","#1d1a20","#e8c84e","#5e7a8e","#e8ddc4"],
    blurb:"Drawing on stone — the technique behind the modern poster.",
    desc:"Based on grease repelling water, lithography reproduces every nuance of crayon and wash. It powered the nineteenth-century poster boom — Toulouse-Lautrec's Moulin Rouge sheets above all — and remains a favourite of painters who draw." },
  { id:"silkscreen", name:"Silkscreen", parent:"printmaking", style:"pop",
    palette:["#e0427a","#f0c82e","#2e8a8a","#c4302a","#1a1a1a"],
    blurb:"Ink through stencilled mesh — Warhol's assembly line for images.",
    desc:"Squeegeeing ink through a stencilled screen yields flat, repeatable colour — commercial printing's workhorse until Warhol made repetition itself the subject. Marilyn after Marilyn, soup can after soup can: the medium is the message." },
  { id:"acrylic-painting", name:"Acrylic", parent:null, style:"contemporary",
    palette:["#e0427a","#7ac4e8","#3e4a5e","#e8e4d8","#2e8a5e"],
    blurb:"The fast, plastic, post-war paint — matte, bright and unfussy.",
    desc:"Acrylics dry in minutes, stick to anything and hold flat, saturated colour without yellowing. Pop artists loved their commercial crispness; Hockney's California pools and Marshall's history paintings show the medium doing what oil cannot — staying perfectly cool." },
  { id:"collage", name:"Collage", parent:null, style:"cubist",
    palette:["#5e7286","#a8896e","#8a4a42","#3e3a36","#d9cdb4"],
    blurb:"The glued world — real fragments pasted into the picture.",
    desc:"When Braque and Picasso pasted newsprint and wallpaper onto canvas in 1912, they broke painting's window-illusion forever: the picture became an object that includes reality instead of imitating it. From Matisse's cut-outs to Njideka Akunyili Crosby's photo-laden interiors, collage is modernism's connective tissue." },
  { id:"mixed-media", name:"Mixed Media", parent:null, style:"contemporary",
    palette:["#3e4a5e","#8a9bb0","#d9d3c4","#c4542e","#1d1c22"],
    blurb:"Whatever the image needs — paint plus straw, lead, fabric, photographs.",
    desc:"Contemporary painters routinely break the paint barrier: Kiefer embeds straw, ash and lead; Basquiat layered oilstick, xerox and spray; Mehretu builds ink and acrylic in laminated strata. The category is less a technique than a refusal to choose one." },
  { id:"automatism", name:"Automatism", parent:null, style:"surreal",
    palette:["#d9b894","#8aa7c4","#5e4a32","#e8d4a8","#2a3440"],
    blurb:"Switching off the pilot — drawing from the unconscious, by accident and trance.",
    desc:"Surrealist automatism sought marks uncensored by intention: doodling without looking, rubbing, dripping, blotting, then finding the image inside. Miró's floating signs and Hilma af Klint's séance-guided drawings show its range; Pollock's drip carried it to mural scale." },
  { id:"frottage", name:"Frottage", parent:"automatism", style:"surreal",
    palette:["#5e6e52","#a8743e","#3e4a5e","#d9c8a0","#22201c"],
    blurb:"Ernst's rubbings — textures lifted from floorboards into dreams.",
    desc:"Max Ernst laid paper over rough surfaces and rubbed with pencil, letting wood grain and string suggest forests, birds and fossil worlds. A child's technique turned divining rod: the image arrives before the idea." },
  { id:"gestural-abstraction", name:"Gestural Abstraction", parent:null, style:"gestural",
    palette:["#1a1a1a","#e8e0d0","#c4763e","#5e7286","#caa43e"],
    blurb:"The body's trace — sweeping, slashing, scraping paint as pure movement.",
    desc:"Here the brushstroke stops describing and starts performing: arm-wide arcs, loaded slashes, scraped recoveries. De Kooning, Kline, Mitchell and Krasner made the gesture itself the picture's subject — energy you can re-feel by looking." },
  { id:"dripping", name:"Dripping", parent:"gestural-abstraction", style:"drip",
    palette:["#1a1a1a","#e8e0d0","#c4763e","#5e7286","#caa43e"],
    blurb:"Paint in free fall — Pollock's dance recorded in skeins of enamel.",
    desc:"Canvas on the floor, brush never touching: paint trailed, flung and dripped from sticks and basting syringes in looping aerial skeins. Pollock's method dissolved the line between drawing and painting, image and event — and gave abstraction its most famous signature." },
  { id:"soak-stain", name:"Soak-Stain", parent:"gestural-abstraction", style:"colorfield",
    palette:["#7ab0c4","#e8a8b8","#a8c49a","#f0e8d8","#d9a85e"],
    blurb:"Frankenthaler's pour — thinned colour drunk straight into raw canvas.",
    desc:"In 1952 Helen Frankenthaler poured turpentine-thinned paint onto unprimed canvas, letting it soak in like watercolour into paper: colour and surface became one thing. Louis and Noland saw 'Mountains and Sea' and changed course — Colour Field painting was born on the spot." },
  { id:"squeegee", name:"Squeegee", parent:"gestural-abstraction", style:"gestural",
    palette:["#8a8a8a","#c4c4c4","#3e3e3e","#c4302a","#e8e8e8"],
    blurb:"Richter's blade — layers dragged, smeared and excavated by chance.",
    desc:"Gerhard Richter drags a metre-wide squeegee across wet layered paint, simultaneously destroying and revealing: chance does the composing, the artist does the judging. The resulting surfaces — part landscape, part static — are contemporary abstraction's signature texture." },
  { id:"broken-color", name:"Broken Colour", parent:null, style:"impressionist",
    palette:["#9ab8d9","#b4d9c4","#e8c8d4","#f0e8c8","#7a8ab0"],
    blurb:"Unmixed strokes side by side — colour blended in the eye, not the palette.",
    desc:"Instead of smoothing tones together, broken colour lays separate touches of pure pigment that fuse optically at viewing distance, making surfaces vibrate with light. It is Impressionism's engine — and through Delacroix, its patent runs back to Romanticism." },
  { id:"pointillism", name:"Pointillism", parent:"broken-color", style:"pointillist",
    palette:["#7a9ab8","#a8c49a","#e8d9a8","#d9886e","#4a5a6e"],
    blurb:"The dot, systematised — Seurat's science of shimmering light.",
    desc:"Pointillism reduces broken colour to its atom: uniform dots of pure pigment placed by colour-theory calculation. Up close, confetti; at distance, a luminous haze no mixed paint can equal. Seurat called it chromoluminarism; a century later Kusama's infinity dots gave the atom a new charge." },
  { id:"flat-color", name:"Flat Colour & Hard Edge", parent:null, style:"mondrian",
    palette:["#e02e2e","#2e50c4","#f0c82e","#f4f1e8","#1a1a1a"],
    blurb:"No shading, no fuss — zones of colour with clean, decisive borders.",
    desc:"From ukiyo-e prints through Gauguin's Synthetism to Mondrian's grids and Pop's commercial crispness, flat colour rejects illusionistic depth in favour of graphic punch. The edge does the drawing; the colour does the feeling." },
  { id:"benday-dots", name:"Ben-Day Dots", parent:"flat-color", style:"pop",
    palette:["#c4302a","#f0c82e","#2e50c4","#f4f1e8","#1a1a1a"],
    blurb:"Comic-book halftone, blown up — Lichtenstein's mechanical romance.",
    desc:"Named for printer Benjamin Day, these cheap halftone dots simulated tone in pulp comics. Lichtenstein enlarged them by hand through stencils, turning printing's most humble shortcut into high art's wittiest signature." },
  { id:"encaustic", name:"Encaustic", parent:null, style:"pop",
    palette:["#b03a32","#e8e0c8","#2e3e8a","#caa45c","#3e3a36"],
    blurb:"Pigment in molten wax — ancient technique, frozen brushstrokes.",
    desc:"Encaustic suspends pigment in heated beeswax that hardens instantly, embalming each stroke mid-gesture. Used for Roman mummy portraits two millennia ago, it was resurrected by Jasper Johns, whose wax-sealed flags trap newspaper scraps like flies in amber." },
  { id:"gold-leaf", name:"Gold Leaf", parent:null, style:"ornament",
    palette:["#caa43e","#e8cd7a","#8a5e2e","#3e3a30","#a83a4e"],
    blurb:"Real gold on canvas — light that comes from the picture itself.",
    desc:"Hammered to microns and burnished onto panel or canvas, gold leaf reflects actual light rather than depicting it — the radiance of Byzantine icons. Klimt, a goldsmith's son, fused that sacred glow with modern desire in his Golden Phase." },
  { id:"spray-paint", name:"Spray & Stencil", parent:null, style:"street",
    palette:["#1a1a1a","#c4302a","#8a8a8a","#e8e4d8","#3e3e3e"],
    blurb:"The aerosol line — fast, illegal, and built for walls.",
    desc:"Spray paint covers metres in seconds and never drips twice the same way; stencils add precision and speed for artists who may have ninety seconds before the police arrive. Basquiat's SAMO tags, Haring's radiant figures and Banksy's stencilled satire took it from vandalism's toolbox to the auction block." },

  // ---- expansion ----
  { id:"miniature-painting", name:"Miniature Painting", parent:null, style:"ornament",
    palette:["#1f6e8a","#c4302a","#caa43e","#2e4a3e","#e8dcc0"],
    blurb:"Painting at whisper scale — books, lockets and worlds a hand-span wide.",
    desc:"From the Ottoman nakkaşhane's illustrated chronicles to Hilliard's Elizabethan portrait-jewels, miniature painting demands single-hair brushes, burnished gold and total control. Held in the hand rather than hung on the wall, it is painting at its most intimate — and, per square centimetre, its most demanding." },
  { id:"gouache", name:"Gouache", parent:"watercolor", style:"fauvist",
    palette:["#c4302a","#2e5eaa","#e8c43e","#2e8a5e","#f0e8d8"],
    blurb:"Opaque watercolour — matte, velvety, and fast as thought.",
    desc:"Watercolour's opaque sibling dries flat and chalky-bright, covers mistakes, and loves paper. Miniaturists ground it with gum for manuscript pages; centuries later Fikret Mualla filled Paris café nights with it, proving a humble medium can hold a whole city's electricity." },
  { id:"photomontage", name:"Photomontage", parent:"collage", style:"cubist",
    palette:["#1a1a1a","#c4302a","#8a9bb0","#e8e0d0","#caa43e"],
    blurb:"Scissors versus the press — new truths cut from newspaper photographs.",
    desc:"Berlin Dada discovered that mass-printed photographs could be re-edited into argument: Hannah Höch's kitchen knife sliced through Weimar politics and gender alike. Photomontage became the activist's medium of the century — its grammar lives on in every meme." }
];

window.ERAS = [
  { id:"16th-century", name:"16th Century", range:"1500–1599", start:1500, end:1599, style:"renaissance",
    palette:["#7a2419","#caa45c","#2b3a52","#e8dcc3","#3e3a30"],
    blurb:"The High Renaissance and its aftershocks — perfection achieved, then gleefully bent.",
    desc:"The century opens with Leonardo, Michelangelo and Raphael at work simultaneously and closes with El Greco's flames and Caravaggio's first shadows. Between them: Venice discovers colour, the North discovers print, Mannerism discovers strangeness, and the painter is promoted from craftsman to genius." },
  { id:"17th-century", name:"17th Century", range:"1600–1699", start:1600, end:1699, style:"baroque",
    palette:["#120e0a","#5e1f1a","#b06a32","#d9b27c","#26343f"],
    blurb:"The Baroque century — light versus darkness on every canvas in Europe.",
    desc:"Caravaggio's tenebrism electrifies Rome, Rubens industrialises splendour in Antwerp, Velázquez plays mirror-games in Madrid, and the new Dutch Republic buys pictures of itself by the hundred thousand. Painting learns drama, psychology, and the value of an honest day's light." },
  { id:"18th-century", name:"18th Century", range:"1700–1799", start:1700, end:1799, style:"rococo",
    palette:["#a8c4b8","#d9b4be","#cfc49a","#8aa7c4","#f0e8d8"],
    blurb:"From powdered fêtes to revolutionary oaths — pleasure, then the guillotine.",
    desc:"Watteau and Fragonard paint the aristocracy's endless garden party; Chardin paints its kitchens with more devotion. Hogarth invents pictorial satire, Canaletto sells Venice to tourists — and then David's Roman oaths announce that the party is over. The century ends with Goya watching, and worrying." },
  { id:"19th-century", name:"19th Century", range:"1800–1899", start:1800, end:1899, style:"impressionist",
    palette:["#9ab8d9","#b4d9c4","#e8c8d4","#f0e8c8","#7a8ab0"],
    blurb:"The century of -isms — from Romantic storms to Post-Impressionist suns.",
    desc:"Painting's most crowded hundred years: Romanticism, Realism, the Barbizon woods, Japan's prints arriving like lightning, Impressionism breaking the Salon, and the Post-Impressionists breaking Impressionism. By 1899, Cézanne, Van Gogh and Seurat have separately drafted the twentieth century." },
  { id:"20th-century", name:"20th Century", range:"1900–1999", start:1900, end:1999, style:"cubist",
    palette:["#c4302a","#2e50c4","#f0c82e","#1a1a1a","#f4f1e8"],
    blurb:"Everything, everywhere — abstraction, dreams, soup cans and the death and rebirth of painting.",
    desc:"Fauvist colour, Cubist fracture, pure abstraction by 1915, Dada's laughter, Surrealist dreams, New York stealing the avant-garde, Pop's deadpan, and painting declared dead and resurrected roughly once a decade. The century in which art's only rule became that there are no rules." },
  { id:"21st-century", name:"21st Century", range:"2000–today", start:2000, end:2026, style:"contemporary",
    palette:["#e0427a","#7ac4e8","#3e4a5e","#e8e4d8","#2e8a5e"],
    blurb:"Painting now — global voices, mixed media, and the brush outliving every obituary.",
    desc:"Painting enters its sixth century more plural than ever: Kusama's infinity rooms draw stadium crowds, Banksy shreds his own canvas at auction, Marshall and Akunyili Crosby repaint who gets pictured, and Richter and Hockney — both born before WWII — keep reinventing it. Reports of painting's death remain greatly exaggerated." }
];

window.NATIONS = [
  { id:"italy", name:"Italy", flag:"🇮🇹", palette:["#7a2419","#2e6e5e","#d9b46a","#e9ddc8","#3e3a30"],
    blurb:"The Renaissance heartland — where modern painting was invented, twice (ask Caravaggio)." },
  { id:"spain", name:"Spain", flag:"🇪🇸", palette:["#8a1f2b","#caa43e","#2a2622","#d9cba8","#5e3424"],
    blurb:"Velázquez's mirrors, Goya's darkness, Picasso's century, Dalí's dreams — Spain paints in extremes." },
  { id:"france", name:"France", flag:"🇫🇷", palette:["#2e50c4","#e8e4d8","#c4302a","#9ab8d9","#caa45c"],
    blurb:"From Poussin to Matisse, the world's art capital for three centuries — every -ism passed through Paris." },
  { id:"netherlands", name:"Netherlands", flag:"🇳🇱", palette:["#2b4a6e","#d9aa4e","#e8d9b0","#8a2e26","#1a140e"],
    blurb:"Rembrandt's gold, Vermeer's silence, Van Gogh's fire, Mondrian's grid — a small country of immense light." },
  { id:"belgium", name:"Belgium & Flanders", flag:"🇧🇪", palette:["#a8412e","#e0b380","#3b5570","#26424e","#d9cdb4"],
    blurb:"Bruegel's peasants, Rubens's splendour, Magritte's bowler hats — realism and the surreal sharing one flat horizon." },
  { id:"germany", name:"Germany", flag:"🇩🇪", palette:["#3e3a36","#c4302a","#e8c43e","#5e6e7a","#d9d3c4"],
    blurb:"Dürer's line, Friedrich's fog, Expressionism's cry, Richter's blur — painting as philosophy by other means." },
  { id:"austria", name:"Austria", flag:"🇦🇹", palette:["#caa43e","#e8cd7a","#a83a4e","#3e3a30","#e8dcc4"],
    blurb:"Vienna 1900 — Klimt's gold and Schiele's nerves, an empire's twilight painted in ornament and anxiety." },
  { id:"switzerland", name:"Switzerland", flag:"🇨🇭", palette:["#c4302a","#e8e4d8","#5e8a96","#d9886e","#3e3a36"],
    blurb:"Klee's pedagogical magic and Dada's Zurich cradle — small, neutral, quietly radical." },
  { id:"britain", name:"Britain & Ireland", flag:"🇬🇧", palette:["#2e3e8a","#c4302a","#e8e4d8","#5b7a9e","#3e5238"],
    blurb:"Turner's light, Constable's clouds, Bacon's screams, Hockney's pools — and one anonymous Bristolian with a stencil." },
  { id:"greece", name:"Greece", flag:"🇬🇷", palette:["#2b3a52","#7b8fb0","#bfc8d8","#5e2430","#cfa44e"],
    blurb:"Birthplace of Doménikos Theotokópoulos — who signed his blazing Spanish canvases in Greek to the end." },
  { id:"norway", name:"Norway", flag:"🇳🇴", palette:["#c4302a","#2e3e8a","#e8e4d8","#d96e2e","#1d1c22"],
    blurb:"Long winters, long shadows — Munch turned Nordic light and dread into modern art's loudest scream." },
  { id:"sweden", name:"Sweden", flag:"🇸🇪", palette:["#2e50c4","#f0c82e","#e8b4c8","#9ab8d9","#5e5648"],
    blurb:"Home of Hilma af Klint, who painted abstraction before anyone — then hid it for half a century." },
  { id:"poland", name:"Poland", flag:"🇵🇱", palette:["#e8e4d8","#c43e4e","#9aa8b8","#2a3440","#caa45c"],
    blurb:"Lempicka's chrome-and-velvet glamour carried Warsaw elegance through Paris, Hollywood and exile." },
  { id:"russia", name:"Russia", flag:"🇷🇺", palette:["#e8e4d8","#2e50c4","#c4302a","#2e8a5e","#1d1a20"],
    blurb:"Icons, avant-gardes and exile — Kandinsky rode out of Moscow toward pure abstraction." },
  { id:"ukraine", name:"Ukraine", flag:"🇺🇦", palette:["#2e50c4","#f0c82e","#e8e4d8","#3e3a36","#c4302a"],
    blurb:"Kyiv-born Malevich pushed painting to its zero point — the Black Square — and beyond." },
  { id:"belarus", name:"Belarus", flag:"🇧🇾", palette:["#2e3e8a","#6e3a8a","#c4302a","#2e8a5e","#e8c43e"],
    blurb:"Chagall's Vitebsk — a town of fiddlers and floating lovers he repainted from memory all his life." },
  { id:"japan", name:"Japan", flag:"🇯🇵", palette:["#e8e4d8","#c4302a","#1f3a5f","#e0427a","#2a2c30"],
    blurb:"From Hokusai's wave to Kusama's dots and Murakami's flowers — flatness as a five-century superpower." },
  { id:"mexico", name:"Mexico", flag:"🇲🇽", palette:["#2e7a52","#e8e4d8","#c4302a","#e8a82e","#3e5570"],
    blurb:"Walls and wounds — Rivera painted the nation's history, Kahlo painted its (and her) heart." },
  { id:"usa", name:"United States", flag:"🇺🇸", palette:["#2e3e8a","#c4302a","#e8e4d8","#caa43e","#1a1a1a"],
    blurb:"From Whistler's nocturnes to Pollock's drips and Warhol's Factory — the 20th century's centre of gravity." },
  { id:"colombia", name:"Colombia", flag:"🇨🇴", palette:["#f0c82e","#2e50c4","#c4302a","#e8c8a8","#8a4a42"],
    blurb:"Botero's rounded world — volume as joy, satire and national style in one inflatable package." },
  { id:"india", name:"India", flag:"🇮🇳", palette:["#e8a85e","#e8e4d8","#2e7a52","#b0502e","#2e4a3e"],
    blurb:"Amrita Sher-Gil fused Paris training with Indian light and made modern Indian painting possible." },
  { id:"nigeria", name:"Nigeria", flag:"🇳🇬", palette:["#2e8a5e","#e8e4d8","#b0703a","#8a3a4e","#3e3a30"],
    blurb:"Akunyili Crosby's layered interiors hold Lagos and Los Angeles on a single, intimate surface." },
  { id:"south-africa", name:"South Africa", flag:"🇿🇦", palette:["#2e8a5e","#f0c82e","#c4302a","#2e3e8a","#1a1a1a"],
    blurb:"Marlene Dumas left apartheid-era Cape Town to paint the human face at its most exposed." },
  { id:"ethiopia", name:"Ethiopia", flag:"🇪🇹", palette:["#2e8a5e","#f0c82e","#c4302a","#3e4a5e","#d9d3c4"],
    blurb:"Addis-born Julie Mehretu layers maps, riots and weather into abstraction's biggest storms." },

  // ---- expansion ----
  { id:"turkey", name:"Türkiye", flag:"🇹🇷", palette:["#c4302a","#e8e4d8","#1f6e8a","#caa43e","#2e4a3e"],
    blurb:"From the sultan's miniature workshops to Paris gouaches and New York walls — five centuries of painting between two continents." },
  { id:"denmark", name:"Denmark", flag:"🇩🇰", palette:["#c4302a","#e8e4d8","#8a9bb0","#5e6e7a","#d9d3c4"],
    blurb:"Hammershøi's grey rooms — Copenhagen silence turned into some of painting's quietest poetry." },
  { id:"finland", name:"Finland", flag:"🇫🇮", palette:["#2e50c4","#e8e4d8","#5e8a96","#3e5238","#caa45c"],
    blurb:"Gallen-Kallela painted the Kalevala into being — a nation's epic, illustrated before its independence." },
  { id:"brazil", name:"Brazil", flag:"🇧🇷", palette:["#2e8a5e","#f0c82e","#2e50c4","#e8e4d8","#b0703a"],
    blurb:"Tarsila's Abaporu swallowed Europe whole and made modernism speak Portuguese — antropofagia!" },
  { id:"cuba", name:"Cuba", flag:"🇨🇺", palette:["#2e50c4","#e8e4d8","#c4302a","#2e6e5a","#caa43e"],
    blurb:"Wifredo Lam brought the jungle and the orishas into modernism's living room." },
  { id:"china", name:"China", flag:"🇨🇳", palette:["#c4302a","#f0c82e","#3e3a36","#e8e0d0","#5e6e5a"],
    blurb:"Qi Baishi's shrimp swim on a thousand years of ink — tradition renewed one brushstroke at a time." },
  { id:"canada", name:"Canada", flag:"🇨🇦", palette:["#c4302a","#e8e4d8","#2e6e5a","#5e4a32","#8aa7c4"],
    blurb:"Emily Carr painted the rainforest and totem poles of the Pacific coast into Canadian memory." },
  { id:"armenia", name:"Armenia", flag:"🇦🇲", palette:["#c4302a","#2e50c4","#e8a82e","#3e3a36","#d9cdb8"],
    blurb:"Aivazovsky's seas and Gorky's exiled abstractions — Armenian painting between empire and diaspora." },
  { id:"czechia", name:"Czechia", flag:"🇨🇿", palette:["#2e50c4","#e8e4d8","#c4302a","#5e3450","#caa43e"],
    blurb:"Kupka painted pure abstraction in 1912 Prague-to-Paris — fugues in colour before the word existed." },
  { id:"hungary", name:"Hungary", flag:"🇭🇺", palette:["#c4302a","#e8e4d8","#2e6e5a","#1a1a1a","#f0c82e"],
    blurb:"From Pécs came Vasarely, who set the world's eyes vibrating — op art's grand engineer." },
  { id:"australia", name:"Australia", flag:"🇦🇺", palette:["#b0502e","#e8a85e","#2e3e8a","#e8dcc0","#5e3424"],
    blurb:"Nolan's black-helmeted outlaw and Kngwarreye's desert dreamings — two Australias, both painted from memory of country." }
];
