/* PIGMENT — venue registry (ARTWORK_SCHEMA §5b).
   Stable slugs for museums, churches, palaces and sites. References are permanent:
   renames are forbidden (add an alias instead). Museum PAGES arrive with the
   Museums deliverable; these ids are load-bearing from day one.
   Sentinels: private-collection · lost · unknown. */
window.VENUES = [
  /* ---- sentinels ---- */
  { id:"private-collection", name:"Private collection", city:null, country:null, type:"site" },
  { id:"lost", name:"Lost or destroyed", city:null, country:null, type:"site" },
  { id:"unknown", name:"Location unknown", city:null, country:null, type:"site" },

  /* ---- Europe ---- */
  { id:"louvre", name:"Musée du Louvre", city:"Paris", country:"France", type:"museum" },
  { id:"musee-dorsay", name:"Musée d'Orsay", city:"Paris", country:"France", type:"museum" },
  { id:"orangerie", name:"Musée de l'Orangerie", city:"Paris", country:"France", type:"museum" },
  { id:"musee-marmottan", name:"Musée Marmottan Monet", city:"Paris", country:"France", type:"museum" },
  { id:"centre-pompidou", name:"Centre Pompidou", city:"Paris", country:"France", type:"museum" },
  { id:"prado", name:"Museo del Prado", city:"Madrid", country:"Spain", type:"museum" },
  { id:"reina-sofia", name:"Museo Reina Sofía", city:"Madrid", country:"Spain", type:"museum" },
  { id:"uffizi", name:"Gallerie degli Uffizi", city:"Florence", country:"Italy", type:"museum" },
  { id:"galleria-borghese", name:"Galleria Borghese", city:"Rome", country:"Italy", type:"museum" },
  { id:"vatican-museums", name:"Vatican Museums", city:"Vatican City", country:"Vatican", type:"museum" },
  { id:"sistine-chapel", name:"Sistine Chapel", city:"Vatican City", country:"Vatican", type:"church" },
  { id:"san-luigi-dei-francesi", name:"Contarelli Chapel, San Luigi dei Francesi", city:"Rome", country:"Italy", type:"church" },
  { id:"santa-maria-delle-grazie", name:"Santa Maria delle Grazie", city:"Milan", country:"Italy", type:"church" },
  { id:"scrovegni-chapel", name:"Scrovegni Chapel", city:"Padua", country:"Italy", type:"church" },
  { id:"museo-civico-sansepolcro", name:"Museo Civico", city:"Sansepolcro", country:"Italy", type:"museum" },
  { id:"national-gallery-london", name:"The National Gallery", city:"London", country:"United Kingdom", type:"museum" },
  { id:"tate-modern", name:"Tate Modern", city:"London", country:"United Kingdom", type:"museum" },
  { id:"tate-britain", name:"Tate Britain", city:"London", country:"United Kingdom", type:"museum" },
  { id:"rijksmuseum", name:"Rijksmuseum", city:"Amsterdam", country:"Netherlands", type:"museum" },
  { id:"van-gogh-museum", name:"Van Gogh Museum", city:"Amsterdam", country:"Netherlands", type:"museum" },
  { id:"mauritshuis", name:"Mauritshuis", city:"The Hague", country:"Netherlands", type:"museum" },
  { id:"st-bavo-cathedral", name:"St Bavo's Cathedral", city:"Ghent", country:"Belgium", type:"church" },
  { id:"alte-pinakothek", name:"Alte Pinakothek", city:"Munich", country:"Germany", type:"museum" },
  { id:"stadel", name:"Städel Museum", city:"Frankfurt", country:"Germany", type:"museum" },
  { id:"kunsthistorisches", name:"Kunsthistorisches Museum", city:"Vienna", country:"Austria", type:"museum" },
  { id:"belvedere", name:"Österreichische Galerie Belvedere", city:"Vienna", country:"Austria", type:"museum" },
  { id:"hermitage", name:"The State Hermitage Museum", city:"St Petersburg", country:"Russia", type:"museum" },
  { id:"tretyakov", name:"Tretyakov Gallery", city:"Moscow", country:"Russia", type:"museum" },
  { id:"nasjonalmuseet-oslo", name:"Nasjonalmuseet", city:"Oslo", country:"Norway", type:"museum" },
  { id:"munch-museum", name:"Munch Museum", city:"Oslo", country:"Norway", type:"museum" },
  { id:"oslo-university-aula", name:"University of Oslo Aula", city:"Oslo", country:"Norway", type:"site" },
  { id:"kode-bergen", name:"KODE Bergen Art Museum", city:"Bergen", country:"Norway", type:"museum" },
  { id:"palazzo-barberini", name:"Palazzo Barberini (Gallerie Nazionali)", city:"Rome", country:"Italy", type:"palace" },
  { id:"pio-monte-della-misericordia", name:"Pio Monte della Misericordia", city:"Naples", country:"Italy", type:"church" },
  { id:"st-johns-co-cathedral", name:"St John's Co-Cathedral", city:"Valletta", country:"Malta", type:"church" },
  { id:"kenwood-house", name:"Kenwood House", city:"London", country:"United Kingdom", type:"palace" },
  { id:"courtauld-gallery", name:"The Courtauld Gallery", city:"London", country:"United Kingdom", type:"museum" },
  { id:"kroller-muller", name:"Kröller-Müller Museum", city:"Otterlo", country:"Netherlands", type:"museum" },
  { id:"lazaro-galdiano", name:"Museo Lázaro Galdiano", city:"Madrid", country:"Spain", type:"museum" },
  { id:"kimbell-art-museum", name:"Kimbell Art Museum", city:"Fort Worth", country:"United States", type:"museum" },
  { id:"isabella-stewart-gardner", name:"Isabella Stewart Gardner Museum", city:"Boston", country:"United States", type:"museum" },
  { id:"yale-university-art-gallery", name:"Yale University Art Gallery", city:"New Haven", country:"United States", type:"museum" },
  { id:"minneapolis-institute-of-art", name:"Minneapolis Institute of Art", city:"Minneapolis", country:"United States", type:"museum" },
  { id:"scottish-national-gallery", name:"Scottish National Gallery", city:"Edinburgh", country:"United Kingdom", type:"museum" },
  { id:"doria-pamphilj", name:"Galleria Doria Pamphilj", city:"Rome", country:"Italy", type:"palace" },
  { id:"capodimonte", name:"Museo di Capodimonte", city:"Naples", country:"Italy", type:"museum" },
  { id:"schloss-weissenstein", name:"Schloss Weißenstein", city:"Pommersfelden", country:"Germany", type:"palace" },
  { id:"royal-collection", name:"Royal Collection, Windsor Castle", city:"Windsor", country:"United Kingdom", type:"palace" },
  { id:"detroit-institute-of-arts", name:"Detroit Institute of Arts", city:"Detroit", country:"United States", type:"museum" },
  { id:"philadelphia-museum-of-art", name:"Philadelphia Museum of Art", city:"Philadelphia", country:"United States", type:"museum" },
  { id:"czartoryski", name:"Czartoryski Museum", city:"Kraków", country:"Poland", type:"museum" },
  { id:"accademia-venice", name:"Gallerie dell'Accademia", city:"Venice", country:"Italy", type:"museum" },
  { id:"accademia-florence", name:"Galleria dell'Accademia", city:"Florence", country:"Italy", type:"museum" },
  { id:"st-peters-basilica", name:"St Peter's Basilica", city:"Vatican City", country:"Italy", type:"church" },
  { id:"mnaa-lisbon", name:"Museu Nacional de Arte Antiga", city:"Lisbon", country:"Portugal", type:"museum" },
  { id:"groeningemuseum", name:"Groeningemuseum", city:"Bruges", country:"Belgium", type:"museum" },
  { id:"gemaldegalerie-berlin", name:"Gemäldegalerie", city:"Berlin", country:"Germany", type:"museum" },
  { id:"baltimore-museum-of-art", name:"Baltimore Museum of Art", city:"Baltimore", country:"United States", type:"museum" },
  { id:"secession-vienna", name:"Secession Building", city:"Vienna", country:"Austria", type:"site" },
  { id:"mak-vienna", name:"MAK — Museum of Applied Arts", city:"Vienna", country:"Austria", type:"museum" },
  { id:"wien-museum", name:"Wien Museum", city:"Vienna", country:"Austria", type:"museum" },
  { id:"leopold-museum", name:"Leopold Museum", city:"Vienna", country:"Austria", type:"museum" },
  { id:"guggenheim-ny", name:"Solomon R. Guggenheim Museum", city:"New York", country:"United States", type:"museum" },
  { id:"k20-dusseldorf", name:"Kunstsammlung Nordrhein-Westfalen (K20)", city:"Düsseldorf", country:"Germany", type:"museum" },
  { id:"musee-picasso-paris", name:"Musée Picasso", city:"Paris", country:"France", type:"museum" },
  { id:"museu-picasso-barcelona", name:"Museu Picasso", city:"Barcelona", country:"Spain", type:"museum" },
  { id:"thyssen-bornemisza", name:"Museo Nacional Thyssen-Bornemisza", city:"Madrid", country:"Spain", type:"museum" },
  { id:"kelvingrove", name:"Kelvingrove Art Gallery and Museum", city:"Glasgow", country:"United Kingdom", type:"museum" },
  { id:"pushkin-museum", name:"Pushkin State Museum of Fine Arts", city:"Moscow", country:"Russia", type:"museum" },
  { id:"museum-ludwig", name:"Museum Ludwig", city:"Cologne", country:"Germany", type:"museum" },

  /* ---- United States ---- */
  { id:"met", name:"The Metropolitan Museum of Art", city:"New York", country:"United States", type:"museum" },
  { id:"moma", name:"The Museum of Modern Art", city:"New York", country:"United States", type:"museum" },
  { id:"neue-galerie", name:"Neue Galerie", city:"New York", country:"United States", type:"museum" },
  { id:"art-institute-chicago", name:"The Art Institute of Chicago", city:"Chicago", country:"United States", type:"museum" },
  { id:"national-gallery-dc", name:"National Gallery of Art", city:"Washington, D.C.", country:"United States", type:"museum" },
  { id:"getty", name:"The Getty Center", city:"Los Angeles", country:"United States", type:"museum" },
  { id:"mfa-boston", name:"Museum of Fine Arts", city:"Boston", country:"United States", type:"museum" },
  { id:"phillips-collection", name:"The Phillips Collection", city:"Washington, D.C.", country:"United States", type:"museum" },
  { id:"sfmoma", name:"San Francisco Museum of Modern Art", city:"San Francisco", country:"United States", type:"museum" },
  { id:"barnes-foundation", name:"Barnes Foundation", city:"Philadelphia", country:"United States", type:"museum" },
  { id:"whitney", name:"Whitney Museum of American Art", city:"New York", country:"United States", type:"museum" },
  { id:"moca-la", name:"Museum of Contemporary Art", city:"Los Angeles", country:"United States", type:"museum" },
  { id:"buffalo-akg", name:"Buffalo AKG Art Museum", city:"Buffalo", country:"United States", type:"museum" },
  { id:"dallas-museum-art", name:"Dallas Museum of Art", city:"Dallas", country:"United States", type:"museum" },
  { id:"stanley-museum-iowa", name:"Stanley Museum of Art", city:"Iowa City", country:"United States", type:"museum" },
  { id:"harry-ransom-center", name:"Harry Ransom Center", city:"Austin", country:"United States", type:"museum" },
  { id:"rothko-chapel", name:"Rothko Chapel", city:"Houston", country:"United States", type:"site" },
  { id:"dali-museum-florida", name:"The Dalí Museum", city:"St Petersburg", country:"United States", type:"museum" },

  /* ---- Türkiye ---- */
  { id:"pera-museum", name:"Pera Museum", city:"Istanbul", country:"Türkiye", type:"museum" },
  { id:"istanbul-modern", name:"İstanbul Modern", city:"Istanbul", country:"Türkiye", type:"museum" },
  { id:"sakip-sabanci", name:"Sakıp Sabancı Museum", city:"Istanbul", country:"Türkiye", type:"museum" },
  { id:"istanbul-resim-heykel", name:"İstanbul Resim ve Heykel Müzesi", city:"Istanbul", country:"Türkiye", type:"museum" },

  /* ---- Mexico ---- */
  { id:"museo-arte-moderno-mexico", name:"Museo de Arte Moderno", city:"Mexico City", country:"Mexico", type:"museum" },
  { id:"museo-dolores-olmedo", name:"Museo Dolores Olmedo", city:"Mexico City", country:"Mexico", type:"museum" },
  { id:"museo-frida-kahlo", name:"Museo Frida Kahlo", city:"Mexico City", country:"Mexico", type:"museum" },

  /* ---- rest of the world ---- */
  { id:"nmwa-tokyo", name:"National Museum of Western Art", city:"Tokyo", country:"Japan", type:"museum" },
  { id:"ngv", name:"National Gallery of Victoria", city:"Melbourne", country:"Australia", type:"museum" },
  { id:"national-gallery-australia", name:"National Gallery of Australia", city:"Canberra", country:"Australia", type:"museum" },
  { id:"masp", name:"São Paulo Museum of Art", city:"São Paulo", country:"Brazil", type:"museum" },
  { id:"albertina", name:"Albertina", city:"Vienna", country:"Austria", type:"museum" },
  { id:"royal-museums-brussels", name:"Royal Museums of Fine Arts of Belgium", city:"Brussels", country:"Belgium", type:"museum" },
  { id:"santo-tome", name:"Iglesia de Santo Tomé", city:"Toledo", country:"Spain", type:"church" },
  { id:"toledo-cathedral", name:"Toledo Cathedral", city:"Toledo", country:"Spain", type:"church" },
  { id:"kunsthalle-mannheim", name:"Kunsthalle Mannheim", city:"Mannheim", country:"Germany", type:"museum" },
  { id:"gemaldegalerie-dresden", name:"Gemäldegalerie Alte Meister", city:"Dresden", country:"Germany", type:"museum" },
  { id:"brera", name:"Pinacoteca di Brera", city:"Milan", country:"Italy", type:"museum" },
  { id:"villa-farnesina", name:"Villa Farnesina", city:"Rome", country:"Italy", type:"palace" },
  { id:"musee-pau", name:"Musée des Beaux-Arts de Pau", city:"Pau", country:"France", type:"museum" },
  { id:"ny-carlsberg-glyptotek", name:"Ny Carlsberg Glyptotek", city:"Copenhagen", country:"Denmark", type:"museum" },
  { id:"moderna-museet", name:"Moderna Museet", city:"Stockholm", country:"Sweden", type:"museum" },
  { id:"russian-museum", name:"State Russian Museum", city:"St Petersburg", country:"Russia", type:"museum" },
  { id:"glenstone", name:"Glenstone", city:"Potomac", country:"United States", type:"museum" }
];
